## Extraction of images from videos

```
conda create -n ImgExtraction
conda activate ImgExtraction
pip install opencv-python
python3 -m ipykernel install --user --name ImgExtraction --display-name "Image extraction from videos"
```

## Anotación de imagenes

Las carpetas están organizadas de la siguiente manera

```
PUMA_CONCOLOR
  |
  +-- IMG001_imagen_001.jpg
  |
  +-- IMG001_imagen_002.jpg
```

In [ ]:
import os
import cv2
from datetime import datetime, timedelta
import ffmpeg  # Requires ffmpeg-python (install with `pip install ffmpeg-python`)
import piexif  # Requires piexif library (install with `pip install piexif`)
from concurrent.futures import ThreadPoolExecutor
from avi_r import AVIReader

def extract_images_from_video_with_exif(video_path, output_folder, video_file_name, target_duration=10, num_images=10):
    """
    Extract images from a video file, save them to the output folder, 
    and update the EXIF timestamp to match the video's frame time.
    """
    os.makedirs(output_folder, exist_ok=True)

    # Handle .AVI files
    if video_path.endswith(".AVI"):
        new_video_path = video_path[:-4] + ".avi"
        os.rename(video_path, new_video_path)
        video_path = new_video_path

    # Extract video creation timestamp using ffmpeg
    try:
        video_metadata = ffmpeg.probe(video_path)
        creation_time_str = next(
            stream['tags']['creation_time']
            for stream in video_metadata['streams']
            if 'tags' in stream and 'creation_time' in stream['tags']
        )
        # Convert to a datetime object
        video_creation_time = datetime.fromisoformat(creation_time_str.replace("Z", "+00:00"))
    except Exception as e:
        print(f"Warning: Could not extract creation time: {e}. Frames will be extracted without adding creation time metadata")
    
    # Determine if the video is an AVI file and use avi_r if necessary
    if video_path.endswith(".avi"):
        try:
            video = AVIReader(video_path)
            fps = video.frame_rate
            total_frames = int(video.num_frames)
        except Exception as e:
            print(f"Error reading AVI file with avi_r: {e}")
            return        
    else:
        video = cv2.VideoCapture(video_path)
        fps = video.get(cv2.CAP_PROP_FPS)
        total_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
    
    # Open video 
    video = cv2.VideoCapture(video_path)
    frames_to_capture = min(int(target_duration * fps), total_frames)
    interval = max(1, frames_to_capture // num_images)

    frame_count = 0
    captured_count = 0
    frame_duration = 1 / fps  # Duration of each frame in seconds

    while True:
        ret, frame = video.read()
        if not ret or captured_count >= num_images:
            break

        if frame_count % interval == 0:
            # Calculate timestamp for the current frame
            try:
                frame_timestamp = video_creation_time + timedelta(seconds=frame_count * frame_duration)
                exif_timestamp = frame_timestamp.strftime("%Y:%m:%d %H:%M:%S")  # EXIF-compliant format
            except:
                print(f'Warning: Error adding creation time, no video_creation_time detected')

            # Save the frame as an image
            image_filename = f"{video_file_name}_image{captured_count + 1:03d}.jpg"
            image_path = os.path.join(output_folder, image_filename)
            cv2.imwrite(image_path, frame)

            # Add EXIF timestamp metadata
            try:
                exif_dict = {"Exif": {piexif.ExifIFD.DateTimeOriginal: exif_timestamp.encode("utf-8")}}
                exif_bytes = piexif.dump(exif_dict)
                piexif.insert(exif_bytes, image_path)
                print(f"Captured: {image_path} with EXIF timestamp {exif_timestamp}")
            except Exception as e:
                print(f"Warning: Error adding EXIF data to {image_filename}: {e}")

            captured_count += 1

        frame_count += 1

    video.release()
    print(f"Extraction complete. {captured_count} images saved to {output_folder}.")

def process_directory(input_dir, output_root):
    """
    Process all videos in a given directory, saving extracted frames to a new folder.
    Handles duplicate filenames with different extensions.
    """
    video_extensions = {".mp4", ".avi", ".mov", ".mkv"}  # Add more extensions as needed
    species_name = os.path.basename(input_dir)
    output_folder = os.path.join(output_root, f"{species_name}_extracted")
    os.makedirs(output_folder, exist_ok=True)  # Create output folder if it doesn't exist

    video_filenames = set()  # Set to track unique filenames

    for file_name in os.listdir(input_dir):
        file_path = os.path.join(input_dir, file_name)
        if os.path.isfile(file_path) and os.path.splitext(file_name)[1].lower() in video_extensions:
            base_name, ext = os.path.splitext(file_name)
            if base_name in video_filenames:
                # Handle duplicate filenames with different extensions
                video_file_name = f"{base_name}_{ext[1:]}" 
            else:
                video_file_name = base_name
            video_filenames.add(base_name) 
            extract_images_from_video_with_exif(file_path, output_folder, video_file_name)

def main(input_root, output_root, max_workers=4):
    """
    Main function to process all subdirectories in parallel.
    """
    os.makedirs(output_root, exist_ok=True)
    subdirs = [os.path.join(input_root, d) for d in os.listdir(input_root) if os.path.isdir(os.path.join(input_root, d))]

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(process_directory, subdir, output_root) for subdir in subdirs]
        for future in futures:
            future.result()  # Wait for all tasks to complete

if __name__ == "__main__":
   input_root = "/mnt/STORAGE/csar/pipo_images"  # Replace with the path to your main directory
   output_root = "../data/images_from_videos"  # Replace with the path to save extracted frames
   main(input_root, output_root, max_workers=20)

# if __name__ == "__main__":
#    input_root = "/mnt/STORAGE/sofia/test_folder"  # Replace with the path to your main directory
#    output_root = "../data/test_avi"  # Replace with the path to save extracted frames
#    main(input_root, output_root, max_workers=20)

Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0184_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0184_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/PUMA_CONCOLOR_2022_extracted/IMG_0015_image001.jpg with EXIF timestamp 2022:07:20 09:02:57
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0094_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding EXIF data to IMG_0184_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0210_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Captured: ../data/images_from_videos/PUMA_CONCOLOR_2022_extracted/IMG_0015_image002.jpg with EXIF timestamp 2022:07:20 09:02:58
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0092_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0184_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Captured: ../data/images_from_videos/ROEDORES_extracted/IMG_0019_image001.jpg with EXIF timestamp 2022:09:30 05:35:08
Warning: Error adding creation time, no video_creation_time detected
Captured: ../data/images_from_videos/PUMA_CONCOLOR_2022_extracted/IMG_0015_image003.jpg with EXIF timestamp 2022:07:20 09:02:59
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0028_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding EXIF data to IMG_0070_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Warning: Error adding EXIF data to IMG_0106_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0184_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0081_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/PECARI_TAJACU_2022_extracted/IMG_0015_image001.jpg with EXIF timestamp 2022:07:04 22:05:16
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Captured: ../data/images_from_videos/PUMA_CONCOLOR_2022_extracted/IMG_0015_image004.jpg with EXIF timestamp 2022:07:20 09:03:00
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0184_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0184_image006.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/SYLVILAGUS_SP_extracted/IMG_0029 (2)_image001.jpg with EXIF timestamp 2022:05:23 09:06:28
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/LYNX_RUFUS_extracted/IMG_0049 (2)_image001.jpg with EXIF timestamp 2022:06:19 06:52:05
Captured: ../data/images_from_videos/ROEDORES_extracted/IMG_0019_image002.jpg with EXIF timestamp 2022:09:30 05:35:09
Warning: Error adding creation time, no video_creation_time detected
Captured: ../data/images_from_videos/PUMA_CONCOLOR_2022_extracted/IMG_0015_image005.jpg with EXIF timestamp 2022:07:20 09:03:01
Warning: Error adding EXIF data to IMG_0184_image007.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/GANADO_2022_extracted/IMG_0106 (2)_image001.jpg with EXIF timestamp 2022:06:15 23:50:57
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0094_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/SCIURUS_OCOLATUS_extracted/IMG_0015_image001.jpg with EXIF timestamp 2022:09:04 08:06:21
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0184_image008.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0092_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0028_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0210_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/PUMA_CONCOLOR_2022_extracted/IMG_0015_image006.jpg with EXIF timestamp 2022:07:20 09:03:02
Captured: ../data/images_from_videos/SPILOGALE_GRACILIS_2022_extracted/IMG_0099_image001.jpg with EXIF timestamp 2022:11:25 00:27:05
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0081_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Captured: ../data/images_from_videos/PECARI_TAJACU_2022_extracted/IMG_0015_image002.jpg with EXIF timestamp 2022:07:04 22:05:17
Warning: Error adding EXIF data to IMG_0184_image009.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/ROEDORES_extracted/IMG_0019_image003.jpg with EXIF timestamp 2022:09:30 05:35:10
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image006.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding EXIF data to IMG_0106_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0028_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/SYLVILAGUS_SP_extracted/IMG_0029 (2)_image002.jpg with EXIF timestamp 2022:05:23 09:06:29
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0092_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image007.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0184_image010.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding EXIF data to IMG_0094_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Extraction complete. 10 images saved to ../data/images_from_videos/BASSSEISCUS_ASTUTUS_extracted.
Warning: Error adding EXIF data to IMG_0081_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/UROCYON_CINEREORGENTEUS_extracted/IMG_0386 (2)_image001.jpg with EXIF timestamp 2022:06:17 23:59:12
Captured: ../data/images_from_videos/PUMA_CONCOLOR_2022_extracted/IMG_0015_image007.jpg with EXIF timestamp 2022:07:20 09:03:03
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image008.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/LYNX_RUFUS_extracted/IMG_0049 (2)_image002.jpg with EXIF timestamp 2022:06:19 06:52:06
Captured: ../data/images_from_videos/GANADO_2022_extracted/IMG_0106 (2)_image002.jpg with EXIF timestamp 2022:06:15 23:50:58
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image009.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0028_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0106_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0210_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0070_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3084_image010.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/BASSSEISCUS_ASTUTUS_extracted/IMG_0031_image001.jpg with EXIF timestamp 2022:09:02 06:17:14
Extraction complete. 10 images saved to ../data/images_from_videos/ODOCOILEUS_VIRGINIANUS_2022_extracted.
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0081_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Captured: ../data/images_from_videos/PECARI_TAJACU_2022_extracted/IMG_0015_image003.jpg with EXIF timestamp 2022:07:04 22:05:18
Warning: Error adding EXIF data to IMG_0094_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0092_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding EXIF data to IMG_0184_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/SCIURUS_OCOLATUS_extracted/IMG_0015_image002.jpg with EXIF timestamp 2022:09:04 08:06:22
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0028_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Captured: ../data/images_from_videos/ROEDORES_extracted/IMG_0019_image004.jpg with EXIF timestamp 2022:09:30 05:35:11
Warning: Error adding EXIF data to IMG_0106_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Could not extract creation time: . Frames will be extracted without adding creation time metadata
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0210_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3067_image001.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/PUMA_CONCOLOR_2022_extracted/IMG_0015_image008.jpg with EXIF timestamp 2022:07:20 09:03:04
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0070_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Captured: ../data/images_from_videos/UROCYON_CINEREORGENTEUS_extracted/IMG_0386 (2)_image002.jpg with EXIF timestamp 2022:06:17 23:59:13
Warning: Error adding EXIF data to IMG_0094_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0081_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Captured: ../data/images_from_videos/GANADO_2022_extracted/IMG_0106 (2)_image003.jpg with EXIF timestamp 2022:06:15 23:50:59
Warning: Error adding EXIF data to IMG_0028_image006.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3067_image002.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0184_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3067_image003.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/BASSSEISCUS_ASTUTUS_extracted/IMG_0031_image002.jpg with EXIF timestamp 2022:09:02 06:17:15
Captured: ../data/images_from_videos/SPILOGALE_GRACILIS_2022_extracted/IMG_0099_image002.jpg with EXIF timestamp 2022:11:25 00:27:06
Warning: Error adding creation time, no video_creation_time detected
Captured: ../data/images_from_videos/SYLVILAGUS_SP_extracted/IMG_0029 (2)_image003.jpg with EXIF timestamp 2022:05:23 09:06:30
Warning: Error adding EXIF data to IMG_0092_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/LYNX_RUFUS_extracted/IMG_0049 (2)_image003.jpg with EXIF timestamp 2022:06:19 06:52:07
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0106_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3067_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding EXIF data to IMG_0210_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/PECARI_TAJACU_2022_extracted/IMG_0015_image004.jpg with EXIF timestamp 2022:07:04 22:05:19
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0028_image007.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0094_image006.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0070_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding EXIF data to IMG_0081_image006.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3067_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/ROEDORES_extracted/IMG_0019_image005.jpg with EXIF timestamp 2022:09:30 05:35:12
Captured: ../data/images_from_videos/SCIURUS_OCOLATUS_extracted/IMG_0015_image003.jpg with EXIF timestamp 2022:09:04 08:06:23
Warning: Error adding creation time, no video_creation_time detectedCaptured: ../data/images_from_videos/PUMA_CONCOLOR_2022_extracted/IMG_0015_image009.jpg with EXIF timestamp 2022:07:20 09:03:05

Warning: Error adding EXIF data to IMG_0184_image004.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to MFDC3067_image006.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0092_image006.jpg: local variable 'exif_timestamp' referenced before assignment
Captured: ../data/images_from_videos/UROCYON_CINEREORGENTEUS_extracted/IMG_0386 (2)_image003.jpg with EXIF timestamp 2022:06:17 23:59:14
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0106_image006.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding creation time, no video_creation_time detected
Captured: ../data/images_from_videos/GANADO_2022_extracted/IMG_0106 (2)_image004.jpg with EXIF timestamp 2022:06:15 23:51:00
Warning: Error adding EXIF data to IMG_0070_image005.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding EXIF data to MFDC3067_image007.jpg: local variable 'exif_timestamp' referenced before assignment
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding creation time, no video_creation_time detected
Warning: Error adding EXIF data to IMG_0028_image008.jpg: local variable 'exif_timestamp' referenced before assignment

## Revisar que todos los archivos hayan sido extraidos

Solo hubo problemas en los archivos de las aves. No entiendo bien por que.

In [52]:
import os
import pandas as pd
import shutil

In [71]:
# Revisar que todos los videos hayan sido extraidos

root_dir = '/mnt/STORAGE/csar/pipo_images'

# Initialize a list to store the data
data = []

# Walk through the filesystem
for parent, species_dirs, _ in os.walk(root_dir):
    for species in species_dirs:
        species_path = os.path.join(parent, species)
        #print(species_path)
        for image in os.listdir(species_path):
            image_path = os.path.join(species_path, image)
            if os.path.isfile(image_path):  # Check if it's a file (image)
                # Append the four levels to the list
                data.append([os.path.basename(root_dir),  # Parent folder name
                                    species,                    # Species folder name
                                    image])                     # Image file name

# Create a DataFrame from the collected data
original_df = pd.DataFrame(data, columns=["Parent_Folder", "Species", "Image"])
original_df_videos = original_df[~original_df['Image'].str.contains('.JPG')]
original_df_videos.loc[:, 'Original_file'] = original_df['Image'].str.replace(r'\.\w*$', '', regex=True)

original_df_videos_filtered = original_df_videos[~original_df_videos['Image'].str.contains('.M4V')]

print(original_df['Image'].str.split('.', expand = True)[1].unique())
print(original_df_videos['Image'].str.split('.', expand = True)[1].unique())
print(original_df_videos_filtered[original_df_videos_filtered['Species'] == 'AVES_2022'].head())
print(original_df_videos_filtered.shape)

['MP4' 'avi' 'JPG' 'M4V' 'AVI']
['MP4' 'avi' 'M4V' 'AVI']
   Parent_Folder    Species         Image Original_file
12   pipo_images  AVES_2022  IMG_0184.avi      IMG_0184
13   pipo_images  AVES_2022  IMG_0106.avi      IMG_0106
16   pipo_images  AVES_2022  IMG_0297.MP4      IMG_0297
17   pipo_images  AVES_2022  IMG_0478.MP4      IMG_0478
18   pipo_images  AVES_2022  IMG_0471.MP4      IMG_0471
(1802, 4)

/tmp/ipykernel_21012/2601685913.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  original_df_videos.loc[:, 'Original_file'] = original_df['Image'].str.replace(r'\.\w*$', '', regex=True)

In [82]:
# Define the root directory (change this to your actual root folder path)
root_dir = "../data/images_from_videos"

# Initialize a list to store the data
data = []

# Walk through the filesystem
for parent, species_dirs, _ in os.walk(root_dir):
    for species in species_dirs:
        species_path = os.path.join(parent, species)
        #print(species_path)
        for image in os.listdir(species_path):
            image_path = os.path.join(species_path, image)
            if os.path.isfile(image_path):  # Check if it's a file (image)
                # Append the four levels to the list
                data.append([os.path.basename(root_dir),  # Parent folder name
                                    species,                    # Species folder name
                                    image])                     # Image file name

# Create a DataFrame from the collected data
extracted_df = pd.DataFrame(data, columns=["Parent_Folder", "Species", "Image"])
extracted_df[['Original_file','img']] = extracted_df['Image'].str.split(r'_(?=[Ii]mage)', n=1, expand=True)
extracted_df['Sp'] = extracted_df['Species'].str.replace('_extracted','')

extracted_df.shape

(15290, 6)

In [73]:
# Revisar que haya el mismo numero de archivos con nombre original antes y despues de la extracción.

counts_extracted = extracted_df.groupby(['Species','Original_file']).count().reset_index()
counts_extracted['Original_sp'] = counts_extracted['Species'].str.replace('_extracted','')

print(counts_extracted.groupby(['Species']).count()['Original_file'])

counts_original = original_df_videos_filtered[['Species','Image']].groupby(['Species']).count()

#print(counts_extracted)
print(counts_original)

Species
AVES_2022_extracted                      291
BASSSEISCUS_ASTUTUS_extracted              5
CONEPATUS_LEUCONOTUS_2022_extracted       39
DIDELPHIS_VIRGINIATA_2022_extracted       28
GANADO_2022_extracted                    312
LYNX_RUFUS_extracted                      16
MEPITIS_MACROURA_2022_extracted           80
NASUA_NARICA_2022_extracted                4
ODOCOILEUS_VIRGINIANUS_2022_extracted     45
OTOSPERMOPHILUS_VERIEGATUS_extracted       4
PECARI_TAJACU_2022_extracted             108
PERROS_extracted                           2
PUMA_CONCOLOR_2022_extracted              35
REPTILES_extracted                         3
ROEDORES_extracted                        12
SCIURUS_OCOLATUS_extracted                43
SPILOGALE_GRACILIS_2022_extracted          5
SYLVILAGUS_SP_extracted                  206
UROCYON_CINEREORGENTEUS_extracted        291
Name: Original_file, dtype: int64
                             Image
Species
AVES_2022                      564
BASSSEISCUS_ASTUTUS              5
CONEPATUS_LEUCONOTUS_2022       39
DIDELPHIS_VIRGINIATA_2022       28
GANADO_2022                    312
LYNX_RUFUS                      16
MEPITIS_MACROURA_2022           80
NASUA_NARICA_2022                4
ODOCOILEUS_VIRGINIANUS_2022     45
OTOSPERMOPHILUS_VERIEGATUS       4
PECARI_TAJACU_2022             108
PERROS                           2
PUMA_CONCOLOR_2022              35
REPTILES                         3
ROEDORES                        12
SCIURUS_OCOLATUS                43
SPILOGALE_GRACILIS_2022          5
SYLVILAGUS_SP                  206
UROCYON_CINEREORGENTEUS        291

In [83]:
extracted_df['Path'] = extracted_df.apply(lambda row: os.path.join('../data/',row['Parent_Folder'], row['Species'], row['Image']), axis=1)
extracted_df.head()

,Parent_Folder,Species,Image,Original_file,img,Sp,Path
0,images_from_videos,DIDELPHIS_VIRGINIATA_2022_extracted,IMG_0009_image010.jpg,IMG_0009,image010.jpg,DIDELPHIS_VIRGINIATA_2022,../data/images_from_videos/DIDELPHIS_VIRGINIAT...
1,images_from_videos,DIDELPHIS_VIRGINIATA_2022_extracted,IMG_0063_image008.jpg,IMG_0063,image008.jpg,DIDELPHIS_VIRGINIATA_2022,../data/images_from_videos/DIDELPHIS_VIRGINIAT...
2,images_from_videos,DIDELPHIS_VIRGINIATA_2022_extracted,IMG_0252_image003.jpg,IMG_0252,image003.jpg,DIDELPHIS_VIRGINIATA_2022,../data/images_from_videos/DIDELPHIS_VIRGINIAT...
3,images_from_videos,DIDELPHIS_VIRGINIATA_2022_extracted,IMG_0094_image002.jpg,IMG_0094,image002.jpg,DIDELPHIS_VIRGINIATA_2022,../data/images_from_videos/DIDELPHIS_VIRGINIAT...
4,images_from_videos,DIDELPHIS_VIRGINIATA_2022_extracted,IMG_0063_image007.jpg,IMG_0063,image007.jpg,DIDELPHIS_VIRGINIATA_2022,../data/images_from_videos/DIDELPHIS_VIRGINIAT...

In [84]:
extracted_df.to_csv('../data/images_from_videos_metadata.csv', index=False)

# Detección de imagenes

Muchas de las imagenes que se extrajeron no tienen animales por lo que es necesario filtrarlas. 

**NOTA:** Hay que cambiar de Kernel! USAR pytorch_wildlife

In [1]:
import os
import pandas as pd
import torch
from PytorchWildlife.models import detection as pw_detection
from PytorchWildlife import utils as pw_utils

DEVICE = 'cpu'

# Initializing the MegaDetectorV6 model for image detection
detection_model = pw_detection.MegaDetectorV6(device=DEVICE, pretrained=True, version="yolov9c")

# Function to extract detections from each image. The images can be joined with species metadata by path and image name
def extract_data_from_detections(results):
    """
    Extracts data from a list of detection results and creates a DataFrame.

    Parameters:
    results (list of dict): A list of dictionaries where each dictionary contains:
        - 'img_id' (str): The image ID.
        - 'labels' (list of str): A list of labels, where each label is a string containing two words: 
          the label name and the certainty score separated by a space.

    Returns:
    pd.DataFrame: A DataFrame with the following columns:
        - 'img_id' (str): The image ID.
        - 'label' (str): The label name.
        - 'certainty' (float): The certainty score.
    """
    
    # List to store the extracted data
    extracted_data = []

    # Extract the keys 'labels' and 'img_id'
    for d in results:
        img_id = d['img_id']
        for label in d['labels']:
            label_name, certainty = label.split()
            extracted_data.append({'img_id': img_id, 'label': label_name, 'certainty': float(certainty)})

    # Create DataFrame
    df = pd.DataFrame(extracted_data)
    return df

Ultralytics 8.3.48 🚀 Python-3.8.20 torch-2.4.1+cu121 CPU (Intel Xeon E5-2697 v4 2.30GHz)
YOLOv9c summary (fused): 384 layers, 25,321,561 parameters, 0 gradients, 102.3 GFLOPs

In [4]:
# Detect for all folders in mod_images_from_videos

results_per_species = []
all_images_detection_metadata = pd.DataFrame()

# Define the path where results will be saved
out_path = '../data/img_from_video_metadata/'

# Ensure the folder exists
os.makedirs(out_path, exist_ok=True)

for species in os.listdir('../data/images_from_videos'):

    print(f'Detecting images from {species}')
    
    folder_path = os.path.join("..","data","images_from_videos",species)
    results = detection_model.batch_image_detection(folder_path, batch_size=16)
    results_per_species.append(results)

    metadata = extract_data_from_detections(results)
    metadata.to_csv(os.path.join(out_path, species + '.csv'))

Detecting images from DIDELPHIS_VIRGINIATA_2022_extracted

  0%|                                                                                                                                                  | 0/18 [00:00<?, ?it/s]

0: 640x640 1 animal, 413.0ms
1: 640x640 1 animal, 413.0ms
2: 640x640 1 animal, 413.0ms
3: 640x640 1 animal, 413.0ms
4: 640x640 1 animal, 413.0ms
5: 640x640 1 animal, 413.0ms
6: 640x640 1 animal, 413.0ms
7: 640x640 1 animal, 413.0ms
8: 640x640 1 animal, 413.0ms
9: 640x640 1 animal, 413.0ms
10: 640x640 1 animal, 413.0ms
11: 640x640 1 animal, 413.0ms
12: 640x640 1 animal, 413.0ms
13: 640x640 1 animal, 413.0ms
14: 640x640 (no detections), 413.0ms
15: 640x640 (no detections), 413.0ms
Speed: 3.1ms preprocess, 413.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  6%|███████▋                                                                                                                                  | 1/18 [00:07<02:03,  7.26s/it]

0: 640x640 (no detections), 408.5ms
1: 640x640 (no detections), 408.5ms
2: 640x640 (no detections), 408.5ms
3: 640x640 (no detections), 408.5ms
4: 640x640 1 animal, 408.5ms
5: 640x640 1 animal, 408.5ms
6: 640x640 1 animal, 408.5ms
7: 640x640 1 animal, 408.5ms
8: 640x640 1 animal, 408.5ms
9: 640x640 1 animal, 408.5ms
10: 640x640 (no detections), 408.5ms
11: 640x640 (no detections), 408.5ms
12: 640x640 (no detections), 408.5ms
13: 640x640 1 animal, 408.5ms
14: 640x640 2 animals, 408.5ms
15: 640x640 1 animal, 408.5ms
Speed: 2.5ms preprocess, 408.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 11%|███████████████▎                                                                                                                          | 2/18 [00:14<01:56,  7.26s/it]

0: 384x640 1 animal, 240.2ms
1: 384x640 1 animal, 240.2ms
2: 384x640 1 animal, 240.2ms
3: 384x640 1 animal, 240.2ms
4: 384x640 1 animal, 240.2ms
5: 384x640 1 animal, 240.2ms
6: 384x640 1 animal, 240.2ms
7: 384x640 1 animal, 240.2ms
8: 384x640 1 animal, 240.2ms
9: 384x640 1 animal, 240.2ms
10: 384x640 1 animal, 240.2ms
11: 384x640 1 animal, 240.2ms
12: 384x640 1 animal, 240.2ms
13: 384x640 2 animals, 240.2ms
14: 384x640 (no detections), 240.2ms
15: 384x640 (no detections), 240.2ms
Speed: 1.8ms preprocess, 240.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 17%|███████████████████████                                                                                                                   | 3/18 [00:18<01:28,  5.87s/it]

0: 640x640 (no detections), 413.3ms
1: 640x640 (no detections), 413.3ms
2: 640x640 1 animal, 413.3ms
3: 640x640 1 animal, 413.3ms
4: 640x640 1 animal, 413.3ms
5: 640x640 1 animal, 413.3ms
6: 640x640 1 animal, 413.3ms
7: 640x640 2 animals, 413.3ms
8: 640x640 1 animal, 413.3ms
9: 640x640 1 animal, 413.3ms
10: 640x640 1 animal, 413.3ms
11: 640x640 2 animals, 413.3ms
12: 640x640 1 animal, 413.3ms
13: 640x640 1 animal, 413.3ms
14: 640x640 1 animal, 413.3ms
15: 640x640 1 animal, 413.3ms
Speed: 2.8ms preprocess, 413.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 22%|██████████████████████████████▋                                                                                                           | 4/18 [00:26<01:30,  6.45s/it]

0: 384x640 1 animal, 241.1ms
1: 384x640 1 animal, 241.1ms
2: 384x640 1 animal, 241.1ms
3: 384x640 1 animal, 241.1ms
4: 384x640 1 animal, 241.1ms
5: 384x640 1 animal, 241.1ms
6: 384x640 1 animal, 241.1ms
7: 384x640 1 animal, 241.1ms
8: 384x640 1 animal, 241.1ms
9: 384x640 (no detections), 241.1ms
10: 384x640 (no detections), 241.1ms
11: 384x640 (no detections), 241.1ms
12: 384x640 (no detections), 241.1ms
13: 384x640 (no detections), 241.1ms
14: 384x640 (no detections), 241.1ms
15: 384x640 (no detections), 241.1ms
Speed: 1.8ms preprocess, 241.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 28%|██████████████████████████████████████▎                                                                                                   | 5/18 [00:30<01:15,  5.77s/it]

0: 384x640 2 animals, 237.2ms
1: 384x640 1 animal, 237.2ms
2: 384x640 1 animal, 237.2ms
3: 384x640 2 animals, 237.2ms
4: 384x640 2 animals, 237.2ms
5: 384x640 1 animal, 237.2ms
6: 384x640 1 animal, 237.2ms
7: 384x640 1 animal, 237.2ms
8: 384x640 1 animal, 237.2ms
9: 384x640 1 animal, 237.2ms
10: 384x640 1 animal, 237.2ms
11: 384x640 1 animal, 237.2ms
12: 384x640 1 animal, 237.2ms
13: 384x640 1 animal, 237.2ms
14: 384x640 2 animals, 237.2ms
15: 384x640 1 animal, 237.2ms
Speed: 1.9ms preprocess, 237.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 33%|██████████████████████████████████████████████                                                                                            | 6/18 [00:34<01:02,  5.24s/it]

0: 384x640 1 animal, 236.3ms
1: 384x640 1 animal, 236.3ms
2: 384x640 1 animal, 236.3ms
3: 384x640 1 animal, 236.3ms
4: 384x640 1 animal, 236.3ms
5: 384x640 1 animal, 236.3ms
6: 384x640 1 animal, 236.3ms
7: 384x640 1 animal, 236.3ms
8: 384x640 1 animal, 236.3ms
9: 384x640 1 animal, 236.3ms
10: 384x640 1 animal, 236.3ms
11: 384x640 1 animal, 236.3ms
12: 384x640 1 animal, 236.3ms
13: 384x640 1 animal, 236.3ms
14: 384x640 1 animal, 236.3ms
15: 384x640 1 animal, 236.3ms
Speed: 1.8ms preprocess, 236.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 39%|█████████████████████████████████████████████████████▋                                                                                    | 7/18 [00:38<00:53,  4.88s/it]

0: 640x640 1 animal, 404.6ms
1: 640x640 1 animal, 404.6ms
2: 640x640 1 animal, 404.6ms
3: 640x640 1 animal, 404.6ms
4: 640x640 1 animal, 404.6ms
5: 640x640 1 animal, 404.6ms
6: 640x640 1 animal, 404.6ms
7: 640x640 1 animal, 404.6ms
8: 640x640 1 animal, 404.6ms
9: 640x640 1 animal, 404.6ms
10: 640x640 1 animal, 404.6ms
11: 640x640 1 animal, 404.6ms
12: 640x640 1 animal, 404.6ms
13: 640x640 1 animal, 404.6ms
14: 640x640 1 animal, 404.6ms
15: 640x640 (no detections), 404.6ms
Speed: 2.5ms preprocess, 404.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 44%|█████████████████████████████████████████████████████████████▎                                                                            | 8/18 [00:46<00:55,  5.57s/it]

0: 384x640 (no detections), 238.1ms
1: 384x640 (no detections), 238.1ms
2: 384x640 1 animal, 238.1ms
3: 384x640 1 animal, 238.1ms
4: 384x640 (no detections), 238.1ms
5: 384x640 (no detections), 238.1ms
6: 384x640 (no detections), 238.1ms
7: 384x640 (no detections), 238.1ms
8: 384x640 (no detections), 238.1ms
9: 384x640 (no detections), 238.1ms
10: 384x640 (no detections), 238.1ms
11: 384x640 (no detections), 238.1ms
12: 384x640 1 animal, 238.1ms
13: 384x640 1 animal, 238.1ms
14: 384x640 1 animal, 238.1ms
15: 384x640 2 animals, 238.1ms
Speed: 1.9ms preprocess, 238.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 50%|█████████████████████████████████████████████████████████████████████                                                                     | 9/18 [00:50<00:47,  5.25s/it]

0: 640x640 1 animal, 404.9ms
1: 640x640 1 animal, 404.9ms
2: 640x640 (no detections), 404.9ms
3: 640x640 1 animal, 404.9ms
4: 640x640 1 animal, 404.9ms
5: 640x640 (no detections), 404.9ms
6: 640x640 1 animal, 404.9ms
7: 640x640 1 animal, 404.9ms
8: 640x640 1 animal, 404.9ms
9: 640x640 1 animal, 404.9ms
10: 640x640 1 animal, 404.9ms
11: 640x640 1 animal, 404.9ms
12: 640x640 1 animal, 404.9ms
13: 640x640 1 animal, 404.9ms
14: 640x640 1 animal, 404.9ms
15: 640x640 1 animal, 404.9ms
Speed: 2.5ms preprocess, 404.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 56%|████████████████████████████████████████████████████████████████████████████                                                             | 10/18 [00:57<00:46,  5.80s/it]

0: 384x640 1 animal, 231.1ms
1: 384x640 1 animal, 231.1ms
2: 384x640 1 animal, 231.1ms
3: 384x640 (no detections), 231.1ms
4: 384x640 (no detections), 231.1ms
5: 384x640 (no detections), 231.1ms
6: 384x640 (no detections), 231.1ms
7: 384x640 (no detections), 231.1ms
8: 384x640 (no detections), 231.1ms
9: 384x640 (no detections), 231.1ms
10: 384x640 1 animal, 231.1ms
11: 384x640 1 animal, 231.1ms
12: 384x640 (no detections), 231.1ms
13: 384x640 (no detections), 231.1ms
14: 384x640 (no detections), 231.1ms
15: 384x640 (no detections), 231.1ms
Speed: 1.8ms preprocess, 231.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 61%|███████████████████████████████████████████████████████████████████████████████████▋                                                     | 11/18 [01:01<00:36,  5.27s/it]

0: 384x640 (no detections), 236.5ms
1: 384x640 (no detections), 236.5ms
2: 384x640 (no detections), 236.5ms
3: 384x640 (no detections), 236.5ms
4: 384x640 1 animal, 236.5ms
5: 384x640 1 animal, 236.5ms
6: 384x640 1 animal, 236.5ms
7: 384x640 1 animal, 236.5ms
8: 384x640 1 animal, 236.5ms
9: 384x640 1 animal, 236.5ms
10: 384x640 1 animal, 236.5ms
11: 384x640 1 animal, 236.5ms
12: 384x640 1 animal, 236.5ms
13: 384x640 1 animal, 236.5ms
14: 384x640 1 animal, 236.5ms
15: 384x640 1 animal, 236.5ms
Speed: 1.9ms preprocess, 236.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▎                                             | 12/18 [01:05<00:29,  4.93s/it]

0: 640x640 1 animal, 404.0ms
1: 640x640 1 animal, 404.0ms
2: 640x640 1 animal, 404.0ms
3: 640x640 1 animal, 404.0ms
4: 640x640 1 animal, 404.0ms
5: 640x640 1 animal, 404.0ms
6: 640x640 1 animal, 404.0ms
7: 640x640 1 animal, 404.0ms
8: 640x640 1 animal, 404.0ms
9: 640x640 1 animal, 404.0ms
10: 640x640 1 animal, 404.0ms
11: 640x640 1 animal, 404.0ms
12: 640x640 1 animal, 404.0ms
13: 640x640 1 animal, 404.0ms
14: 640x640 1 animal, 404.0ms
15: 640x640 1 animal, 404.0ms
Speed: 2.3ms preprocess, 404.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                                      | 13/18 [01:12<00:27,  5.57s/it]

0: 640x640 1 animal, 392.5ms
1: 640x640 (no detections), 392.5ms
2: 640x640 1 animal, 392.5ms
3: 640x640 1 animal, 392.5ms
4: 640x640 1 animal, 392.5ms
5: 640x640 (no detections), 392.5ms
6: 640x640 (no detections), 392.5ms
7: 640x640 (no detections), 392.5ms
8: 640x640 (no detections), 392.5ms
9: 640x640 (no detections), 392.5ms
10: 640x640 (no detections), 392.5ms
11: 640x640 (no detections), 392.5ms
12: 640x640 1 animal, 392.5ms
13: 640x640 1 animal, 392.5ms
14: 640x640 1 animal, 392.5ms
15: 640x640 1 animal, 392.5ms
Speed: 2.5ms preprocess, 392.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 14/18 [01:19<00:23,  5.98s/it]

0: 640x640 1 animal, 397.4ms
1: 640x640 1 animal, 397.4ms
2: 640x640 1 animal, 397.4ms
3: 640x640 1 animal, 397.4ms
4: 640x640 1 animal, 397.4ms
5: 640x640 1 animal, 397.4ms
6: 640x640 1 animal, 397.4ms
7: 640x640 1 animal, 397.4ms
8: 640x640 1 animal, 397.4ms
9: 640x640 1 animal, 397.4ms
10: 640x640 1 animal, 397.4ms
11: 640x640 1 animal, 397.4ms
12: 640x640 1 animal, 397.4ms
13: 640x640 1 animal, 397.4ms
14: 640x640 1 animal, 397.4ms
15: 640x640 (no detections), 397.4ms
Speed: 2.5ms preprocess, 397.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 15/18 [01:26<00:18,  6.28s/it]

0: 384x640 1 animal, 230.3ms
1: 384x640 1 animal, 230.3ms
2: 384x640 1 animal, 230.3ms
3: 384x640 1 animal, 230.3ms
4: 384x640 1 animal, 230.3ms
5: 384x640 1 animal, 230.3ms
6: 384x640 1 animal, 230.3ms
7: 384x640 1 animal, 230.3ms
8: 384x640 1 animal, 230.3ms
9: 384x640 1 animal, 230.3ms
10: 384x640 1 animal, 230.3ms
11: 384x640 1 animal, 230.3ms
12: 384x640 1 animal, 230.3ms
13: 384x640 1 animal, 230.3ms
14: 384x640 1 animal, 230.3ms
15: 384x640 1 animal, 230.3ms
Speed: 1.8ms preprocess, 230.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 16/18 [01:30<00:11,  5.61s/it]

0: 640x640 1 animal, 385.7ms
1: 640x640 1 animal, 385.7ms
2: 640x640 1 animal, 385.7ms
3: 640x640 1 animal, 385.7ms
4: 640x640 1 animal, 385.7ms
5: 640x640 1 animal, 385.7ms
6: 640x640 1 animal, 385.7ms
7: 640x640 1 animal, 385.7ms
8: 640x640 1 animal, 385.7ms
9: 640x640 1 animal, 385.7ms
10: 640x640 1 animal, 385.7ms
11: 640x640 1 animal, 385.7ms
12: 640x640 (no detections), 385.7ms
13: 640x640 (no detections), 385.7ms
14: 640x640 1 animal, 385.7ms
15: 640x640 1 animal, 385.7ms
Speed: 2.7ms preprocess, 385.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 17/18 [01:37<00:05,  5.98s/it]

0: 384x640 2 animals, 204.9ms
1: 384x640 1 animal, 204.9ms
2: 384x640 1 animal, 204.9ms
3: 384x640 1 animal, 204.9ms
4: 384x640 1 animal, 204.9ms
5: 384x640 (no detections), 204.9ms
6: 384x640 (no detections), 204.9ms
7: 384x640 (no detections), 204.9ms
Speed: 1.9ms preprocess, 204.9ms inference, 0.4ms postprocess per image at shape (8, 3, 384, 640)

00%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [01:39<00:00,  5.54s/it]

Detecting images from SYLVILAGUS_SP_extracted

  0%|                                                                                                                                                 | 0/129 [00:00<?, ?it/s]

0: 384x640 (no detections), 224.2ms
1: 384x640 (no detections), 224.2ms
2: 384x640 (no detections), 224.2ms
3: 384x640 (no detections), 224.2ms
4: 384x640 (no detections), 224.2ms
5: 384x640 (no detections), 224.2ms
6: 384x640 (no detections), 224.2ms
7: 384x640 (no detections), 224.2ms
8: 384x640 (no detections), 224.2ms
9: 384x640 (no detections), 224.2ms
10: 384x640 1 animal, 224.2ms
11: 384x640 1 animal, 224.2ms
12: 384x640 1 animal, 224.2ms
13: 384x640 (no detections), 224.2ms
14: 384x640 (no detections), 224.2ms
15: 384x640 (no detections), 224.2ms
Speed: 1.8ms preprocess, 224.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

  1%|█                                                                                                                                        | 1/129 [00:03<08:31,  3.99s/it]

0: 640x640 (no detections), 381.9ms
1: 640x640 (no detections), 381.9ms
2: 640x640 (no detections), 381.9ms
3: 640x640 (no detections), 381.9ms
4: 640x640 1 animal, 381.9ms
5: 640x640 (no detections), 381.9ms
6: 640x640 (no detections), 381.9ms
7: 640x640 (no detections), 381.9ms
8: 640x640 1 animal, 381.9ms
9: 640x640 (no detections), 381.9ms
10: 640x640 (no detections), 381.9ms
11: 640x640 (no detections), 381.9ms
12: 640x640 (no detections), 381.9ms
13: 640x640 (no detections), 381.9ms
14: 640x640 1 animal, 381.9ms
15: 640x640 1 animal, 381.9ms
Speed: 2.5ms preprocess, 381.9ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

  2%|██                                                                                                                                       | 2/129 [00:10<11:39,  5.51s/it]

0: 640x640 1 animal, 384.5ms
1: 640x640 (no detections), 384.5ms
2: 640x640 1 animal, 384.5ms
3: 640x640 1 animal, 384.5ms
4: 640x640 1 animal, 384.5ms
5: 640x640 1 animal, 384.5ms
6: 640x640 1 animal, 384.5ms
7: 640x640 1 animal, 384.5ms
8: 640x640 (no detections), 384.5ms
9: 640x640 (no detections), 384.5ms
10: 640x640 (no detections), 384.5ms
11: 640x640 (no detections), 384.5ms
12: 640x640 (no detections), 384.5ms
13: 640x640 (no detections), 384.5ms
14: 640x640 (no detections), 384.5ms
15: 640x640 (no detections), 384.5ms
Speed: 2.3ms preprocess, 384.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  2%|███▏                                                                                                                                     | 3/129 [00:17<12:45,  6.08s/it]

0: 384x640 (no detections), 222.2ms
1: 384x640 (no detections), 222.2ms
2: 384x640 2 animals, 222.2ms
3: 384x640 2 animals, 222.2ms
4: 384x640 1 animal, 222.2ms
5: 384x640 1 animal, 222.2ms
6: 384x640 1 animal, 222.2ms
7: 384x640 1 animal, 222.2ms
8: 384x640 2 animals, 222.2ms
9: 384x640 1 animal, 222.2ms
10: 384x640 1 animal, 222.2ms
11: 384x640 1 animal, 222.2ms
12: 384x640 (no detections), 222.2ms
13: 384x640 (no detections), 222.2ms
14: 384x640 (no detections), 222.2ms
15: 384x640 (no detections), 222.2ms
Speed: 1.7ms preprocess, 222.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  3%|████▏                                                                                                                                    | 4/129 [00:21<10:54,  5.24s/it]

0: 640x640 (no detections), 379.8ms
1: 640x640 (no detections), 379.8ms
2: 640x640 (no detections), 379.8ms
3: 640x640 (no detections), 379.8ms
4: 640x640 (no detections), 379.8ms
5: 640x640 (no detections), 379.8ms
6: 640x640 1 animal, 379.8ms
7: 640x640 1 animal, 379.8ms
8: 640x640 1 animal, 379.8ms
9: 640x640 1 animal, 379.8ms
10: 640x640 1 animal, 379.8ms
11: 640x640 1 animal, 379.8ms
12: 640x640 1 animal, 379.8ms
13: 640x640 2 animals, 379.8ms
14: 640x640 2 animals, 379.8ms
15: 640x640 2 animals, 379.8ms
Speed: 2.5ms preprocess, 379.8ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  4%|█████▎                                                                                                                                   | 5/129 [00:27<11:54,  5.76s/it]

0: 384x640 1 animal, 224.8ms
1: 384x640 1 animal, 224.8ms
2: 384x640 1 animal, 224.8ms
3: 384x640 1 animal, 224.8ms
4: 384x640 1 animal, 224.8ms
5: 384x640 1 animal, 224.8ms
6: 384x640 1 animal, 224.8ms
7: 384x640 1 animal, 224.8ms
8: 384x640 1 animal, 224.8ms
9: 384x640 1 animal, 224.8ms
10: 384x640 1 animal, 224.8ms
11: 384x640 1 animal, 224.8ms
12: 384x640 1 animal, 224.8ms
13: 384x640 1 animal, 224.8ms
14: 384x640 1 animal, 224.8ms
15: 384x640 1 animal, 224.8ms
Speed: 2.0ms preprocess, 224.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  5%|██████▎                                                                                                                                  | 6/129 [00:32<10:51,  5.30s/it]

0: 640x640 1 animal, 380.2ms
1: 640x640 1 animal, 380.2ms
2: 640x640 1 animal, 380.2ms
3: 640x640 1 animal, 380.2ms
4: 640x640 1 animal, 380.2ms
5: 640x640 1 animal, 380.2ms
6: 640x640 1 animal, 380.2ms
7: 640x640 (no detections), 380.2ms
8: 640x640 (no detections), 380.2ms
9: 640x640 (no detections), 380.2ms
10: 640x640 (no detections), 380.2ms
11: 640x640 (no detections), 380.2ms
12: 640x640 (no detections), 380.2ms
13: 640x640 (no detections), 380.2ms
14: 640x640 1 animal, 380.2ms
15: 640x640 1 animal, 380.2ms
Speed: 2.6ms preprocess, 380.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  5%|███████▍                                                                                                                                 | 7/129 [00:38<11:37,  5.72s/it]

0: 384x640 1 animal, 224.5ms
1: 384x640 (no detections), 224.5ms
2: 384x640 (no detections), 224.5ms
3: 384x640 (no detections), 224.5ms
4: 384x640 (no detections), 224.5ms
5: 384x640 (no detections), 224.5ms
6: 384x640 (no detections), 224.5ms
7: 384x640 (no detections), 224.5ms
8: 384x640 2 animals, 224.5ms
9: 384x640 2 animals, 224.5ms
10: 384x640 1 animal, 224.5ms
11: 384x640 1 animal, 224.5ms
12: 384x640 1 animal, 224.5ms
13: 384x640 2 animals, 224.5ms
14: 384x640 1 animal, 224.5ms
15: 384x640 1 animal, 224.5ms
Speed: 1.7ms preprocess, 224.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  6%|████████▍                                                                                                                                | 8/129 [00:42<10:25,  5.17s/it]

0: 640x640 1 animal, 383.1ms
1: 640x640 1 animal, 383.1ms
2: 640x640 1 animal, 383.1ms
3: 640x640 1 animal, 383.1ms
4: 640x640 1 animal, 383.1ms
5: 640x640 1 animal, 383.1ms
6: 640x640 1 animal, 383.1ms
7: 640x640 1 animal, 383.1ms
8: 640x640 1 animal, 383.1ms
9: 640x640 1 animal, 383.1ms
10: 640x640 1 animal, 383.1ms
11: 640x640 1 animal, 383.1ms
12: 640x640 1 animal, 383.1ms
13: 640x640 1 animal, 383.1ms
14: 640x640 1 animal, 383.1ms
15: 640x640 1 animal, 383.1ms
Speed: 2.5ms preprocess, 383.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  7%|█████████▌                                                                                                                               | 9/129 [00:49<11:22,  5.69s/it]

0: 384x640 1 animal, 226.9ms
1: 384x640 1 animal, 226.9ms
2: 384x640 1 animal, 226.9ms
3: 384x640 1 animal, 226.9ms
4: 384x640 1 animal, 226.9ms
5: 384x640 1 animal, 226.9ms
6: 384x640 1 animal, 226.9ms
7: 384x640 1 animal, 226.9ms
8: 384x640 1 animal, 226.9ms
9: 384x640 1 animal, 226.9ms
10: 384x640 (no detections), 226.9ms
11: 384x640 (no detections), 226.9ms
12: 384x640 (no detections), 226.9ms
13: 384x640 (no detections), 226.9ms
14: 384x640 (no detections), 226.9ms
15: 384x640 (no detections), 226.9ms
Speed: 1.7ms preprocess, 226.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  8%|██████████▌                                                                                                                             | 10/129 [00:54<10:33,  5.33s/it]

0: 384x640 1 animal, 226.3ms
1: 384x640 1 animal, 226.3ms
2: 384x640 1 animal, 226.3ms
3: 384x640 1 animal, 226.3ms
4: 384x640 1 animal, 226.3ms
5: 384x640 (no detections), 226.3ms
6: 384x640 (no detections), 226.3ms
7: 384x640 (no detections), 226.3ms
8: 384x640 (no detections), 226.3ms
9: 384x640 (no detections), 226.3ms
10: 384x640 1 animal, 226.3ms
11: 384x640 1 animal, 226.3ms
12: 384x640 1 animal, 226.3ms
13: 384x640 1 animal, 226.3ms
14: 384x640 1 animal, 226.3ms
15: 384x640 1 animal, 226.3ms
Speed: 1.8ms preprocess, 226.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  9%|███████████▌                                                                                                                            | 11/129 [00:58<10:00,  5.09s/it]

0: 384x640 1 animal, 229.1ms
1: 384x640 1 animal, 229.1ms
2: 384x640 1 animal, 229.1ms
3: 384x640 1 animal, 229.1ms
4: 384x640 1 animal, 229.1ms
5: 384x640 1 animal, 229.1ms
6: 384x640 1 animal, 229.1ms
7: 384x640 1 animal, 229.1ms
8: 384x640 1 animal, 229.1ms
9: 384x640 1 animal, 229.1ms
10: 384x640 1 animal, 229.1ms
11: 384x640 1 animal, 229.1ms
12: 384x640 1 animal, 229.1ms
13: 384x640 1 animal, 229.1ms
14: 384x640 1 animal, 229.1ms
15: 384x640 1 animal, 229.1ms
Speed: 1.8ms preprocess, 229.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  9%|████████████▋                                                                                                                           | 12/129 [01:03<09:34,  4.91s/it]

0: 384x640 (no detections), 234.0ms
1: 384x640 (no detections), 234.0ms
2: 384x640 (no detections), 234.0ms
3: 384x640 1 animal, 234.0ms
4: 384x640 (no detections), 234.0ms
5: 384x640 (no detections), 234.0ms
6: 384x640 (no detections), 234.0ms
7: 384x640 (no detections), 234.0ms
8: 384x640 1 animal, 234.0ms
9: 384x640 1 animal, 234.0ms
10: 384x640 1 animal, 234.0ms
11: 384x640 1 animal, 234.0ms
12: 384x640 1 animal, 234.0ms
13: 384x640 1 animal, 234.0ms
14: 384x640 1 animal, 234.0ms
15: 384x640 1 animal, 234.0ms
Speed: 1.7ms preprocess, 234.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 10%|█████████████▋                                                                                                                          | 13/129 [01:08<09:22,  4.85s/it]

0: 384x640 1 animal, 233.0ms
1: 384x640 1 animal, 233.0ms
2: 384x640 1 animal, 233.0ms
3: 384x640 1 animal, 233.0ms
4: 384x640 1 animal, 233.0ms
5: 384x640 1 animal, 233.0ms
6: 384x640 1 animal, 233.0ms
7: 384x640 1 animal, 233.0ms
8: 384x640 1 animal, 233.0ms
9: 384x640 1 animal, 233.0ms
10: 384x640 1 animal, 233.0ms
11: 384x640 1 animal, 233.0ms
12: 384x640 1 animal, 233.0ms
13: 384x640 1 animal, 233.0ms
14: 384x640 1 animal, 233.0ms
15: 384x640 1 animal, 233.0ms
Speed: 1.7ms preprocess, 233.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 11%|██████████████▊                                                                                                                         | 14/129 [01:12<09:08,  4.77s/it]

0: 384x640 1 animal, 232.9ms
1: 384x640 1 animal, 232.9ms
2: 384x640 1 animal, 232.9ms
3: 384x640 (no detections), 232.9ms
4: 384x640 (no detections), 232.9ms
5: 384x640 (no detections), 232.9ms
6: 384x640 1 animal, 232.9ms
7: 384x640 1 animal, 232.9ms
8: 384x640 1 animal, 232.9ms
9: 384x640 1 animal, 232.9ms
10: 384x640 2 animals, 232.9ms
11: 384x640 1 animal, 232.9ms
12: 384x640 (no detections), 232.9ms
13: 384x640 (no detections), 232.9ms
14: 384x640 (no detections), 232.9ms
15: 384x640 (no detections), 232.9ms
Speed: 1.7ms preprocess, 232.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 12%|███████████████▊                                                                                                                        | 15/129 [01:17<08:52,  4.67s/it]

0: 384x640 1 animal, 234.4ms
1: 384x640 1 animal, 234.4ms
2: 384x640 1 animal, 234.4ms
3: 384x640 1 animal, 234.4ms
4: 384x640 1 animal, 234.4ms
5: 384x640 1 animal, 234.4ms
6: 384x640 1 animal, 234.4ms
7: 384x640 1 animal, 234.4ms
8: 384x640 1 animal, 234.4ms
9: 384x640 1 animal, 234.4ms
10: 384x640 (no detections), 234.4ms
11: 384x640 1 animal, 234.4ms
12: 384x640 1 animal, 234.4ms
13: 384x640 1 animal, 234.4ms
14: 384x640 2 animals, 234.4ms
15: 384x640 (no detections), 234.4ms
Speed: 1.9ms preprocess, 234.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 12%|████████████████▊                                                                                                                       | 16/129 [01:21<08:43,  4.64s/it]

0: 384x640 (no detections), 234.7ms
1: 384x640 (no detections), 234.7ms
2: 384x640 (no detections), 234.7ms
3: 384x640 (no detections), 234.7ms
4: 384x640 2 animals, 234.7ms
5: 384x640 1 animal, 234.7ms
6: 384x640 (no detections), 234.7ms
7: 384x640 1 animal, 234.7ms
8: 384x640 1 animal, 234.7ms
9: 384x640 1 animal, 234.7ms
10: 384x640 1 animal, 234.7ms
11: 384x640 1 animal, 234.7ms
12: 384x640 1 animal, 234.7ms
13: 384x640 (no detections), 234.7ms
14: 384x640 1 animal, 234.7ms
15: 384x640 1 animal, 234.7ms
Speed: 1.7ms preprocess, 234.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 13%|█████████████████▉                                                                                                                      | 17/129 [01:26<08:34,  4.60s/it]

0: 384x640 1 animal, 235.2ms
1: 384x640 1 animal, 235.2ms
2: 384x640 1 animal, 235.2ms
3: 384x640 1 animal, 235.2ms
4: 384x640 1 animal, 235.2ms
5: 384x640 1 animal, 235.2ms
6: 384x640 1 animal, 235.2ms
7: 384x640 1 animal, 235.2ms
8: 384x640 2 animals, 235.2ms
9: 384x640 1 animal, 235.2ms
10: 384x640 1 animal, 235.2ms
11: 384x640 2 animals, 235.2ms
12: 384x640 2 animals, 235.2ms
13: 384x640 1 animal, 235.2ms
14: 384x640 2 animals, 235.2ms
15: 384x640 2 animals, 235.2ms
Speed: 1.7ms preprocess, 235.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 14%|██████████████████▉                                                                                                                     | 18/129 [01:30<08:35,  4.64s/it]

0: 384x640 2 animals, 235.6ms
1: 384x640 2 animals, 235.6ms
2: 384x640 1 animal, 235.6ms
3: 384x640 1 animal, 235.6ms
4: 384x640 1 animal, 235.6ms
5: 384x640 1 animal, 235.6ms
6: 384x640 1 animal, 235.6ms
7: 384x640 1 animal, 235.6ms
8: 384x640 2 animals, 235.6ms
9: 384x640 1 animal, 235.6ms
10: 384x640 1 animal, 235.6ms
11: 384x640 1 animal, 235.6ms
12: 384x640 1 animal, 235.6ms
13: 384x640 1 animal, 235.6ms
14: 384x640 1 animal, 235.6ms
15: 384x640 1 animal, 235.6ms
Speed: 1.8ms preprocess, 235.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 15%|████████████████████                                                                                                                    | 19/129 [01:35<08:35,  4.68s/it]

0: 384x640 1 animal, 233.5ms
1: 384x640 1 animal, 233.5ms
2: 384x640 1 animal, 233.5ms
3: 384x640 (no detections), 233.5ms
4: 384x640 1 animal, 233.5ms
5: 384x640 1 animal, 233.5ms
6: 384x640 1 animal, 233.5ms
7: 384x640 1 animal, 233.5ms
8: 384x640 1 animal, 233.5ms
9: 384x640 1 animal, 233.5ms
10: 384x640 1 animal, 233.5ms
11: 384x640 1 animal, 233.5ms
12: 384x640 1 animal, 233.5ms
13: 384x640 1 animal, 233.5ms
14: 384x640 1 animal, 233.5ms
15: 384x640 1 animal, 233.5ms
Speed: 1.7ms preprocess, 233.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 16%|█████████████████████                                                                                                                   | 20/129 [01:40<08:27,  4.66s/it]

0: 384x640 1 animal, 234.4ms
1: 384x640 1 animal, 234.4ms
2: 384x640 2 animals, 234.4ms
3: 384x640 1 animal, 234.4ms
4: 384x640 2 animals, 234.4ms
5: 384x640 1 animal, 234.4ms
6: 384x640 1 animal, 234.4ms
7: 384x640 1 animal, 234.4ms
8: 384x640 1 animal, 234.4ms
9: 384x640 (no detections), 234.4ms
10: 384x640 1 animal, 234.4ms
11: 384x640 1 animal, 234.4ms
12: 384x640 1 animal, 234.4ms
13: 384x640 1 animal, 234.4ms
14: 384x640 1 animal, 234.4ms
15: 384x640 1 animal, 234.4ms
Speed: 1.7ms preprocess, 234.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 16%|██████████████████████▏                                                                                                                 | 21/129 [01:44<08:25,  4.68s/it]

0: 384x640 (no detections), 234.9ms
1: 384x640 (no detections), 234.9ms
2: 384x640 (no detections), 234.9ms
3: 384x640 1 animal, 234.9ms
4: 384x640 1 animal, 234.9ms
5: 384x640 1 animal, 234.9ms
6: 384x640 1 animal, 234.9ms
7: 384x640 1 animal, 234.9ms
8: 384x640 1 animal, 234.9ms
9: 384x640 2 animals, 234.9ms
10: 384x640 2 animals, 234.9ms
11: 384x640 1 animal, 234.9ms
12: 384x640 1 animal, 234.9ms
13: 384x640 1 animal, 234.9ms
14: 384x640 1 animal, 234.9ms
15: 384x640 1 animal, 234.9ms
Speed: 2.0ms preprocess, 234.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 17%|███████████████████████▏                                                                                                                | 22/129 [01:49<08:23,  4.71s/it]

0: 384x640 1 animal, 235.1ms
1: 384x640 1 animal, 235.1ms
2: 384x640 2 animals, 235.1ms
3: 384x640 (no detections), 235.1ms
4: 384x640 1 animal, 235.1ms
5: 384x640 1 animal, 235.1ms
6: 384x640 1 animal, 235.1ms
7: 384x640 1 animal, 235.1ms
8: 384x640 1 animal, 235.1ms
9: 384x640 1 animal, 235.1ms
10: 384x640 1 animal, 235.1ms
11: 384x640 1 animal, 235.1ms
12: 384x640 1 animal, 235.1ms
13: 384x640 1 animal, 235.1ms
14: 384x640 1 animal, 235.1ms
15: 384x640 1 animal, 235.1ms
Speed: 1.7ms preprocess, 235.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 18%|████████████████████████▏                                                                                                               | 23/129 [01:54<08:20,  4.72s/it]

0: 384x640 (no detections), 235.2ms
1: 384x640 1 animal, 235.2ms
2: 384x640 1 animal, 235.2ms
3: 384x640 2 animals, 235.2ms
4: 384x640 1 animal, 235.2ms
5: 384x640 (no detections), 235.2ms
6: 384x640 (no detections), 235.2ms
7: 384x640 (no detections), 235.2ms
8: 384x640 (no detections), 235.2ms
9: 384x640 (no detections), 235.2ms
10: 384x640 (no detections), 235.2ms
11: 384x640 (no detections), 235.2ms
12: 384x640 1 animal, 235.2ms
13: 384x640 2 animals, 235.2ms
14: 384x640 1 animal, 235.2ms
15: 384x640 1 animal, 235.2ms
Speed: 1.7ms preprocess, 235.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 19%|█████████████████████████▎                                                                                                              | 24/129 [01:59<08:11,  4.68s/it]

0: 640x640 (no detections), 402.6ms
1: 640x640 2 animals, 402.6ms
2: 640x640 1 animal, 402.6ms
3: 640x640 (no detections), 402.6ms
4: 640x640 (no detections), 402.6ms
5: 640x640 (no detections), 402.6ms
6: 640x640 1 animal, 402.6ms
7: 640x640 1 animal, 402.6ms
8: 640x640 1 animal, 402.6ms
9: 640x640 1 animal, 402.6ms
10: 640x640 1 animal, 402.6ms
11: 640x640 1 animal, 402.6ms
12: 640x640 1 animal, 402.6ms
13: 640x640 1 animal, 402.6ms
14: 640x640 (no detections), 402.6ms
15: 640x640 (no detections), 402.6ms
Speed: 2.7ms preprocess, 402.6ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 19%|██████████████████████████▎                                                                                                             | 25/129 [02:06<09:21,  5.40s/it]

0: 640x640 1 animal, 401.6ms
1: 640x640 1 animal, 401.6ms
2: 640x640 1 animal, 401.6ms
3: 640x640 1 animal, 401.6ms
4: 640x640 1 animal, 401.6ms
5: 640x640 1 animal, 401.6ms
6: 640x640 1 animal, 401.6ms
7: 640x640 1 animal, 401.6ms
8: 640x640 1 animal, 401.6ms
9: 640x640 1 animal, 401.6ms
10: 640x640 1 animal, 401.6ms
11: 640x640 1 animal, 401.6ms
12: 640x640 1 animal, 401.6ms
13: 640x640 (no detections), 401.6ms
14: 640x640 (no detections), 401.6ms
15: 640x640 (no detections), 401.6ms
Speed: 2.7ms preprocess, 401.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 20%|███████████████████████████▍                                                                                                            | 26/129 [02:13<10:07,  5.90s/it]

0: 640x640 (no detections), 403.5ms
1: 640x640 (no detections), 403.5ms
2: 640x640 (no detections), 403.5ms
3: 640x640 (no detections), 403.5ms
4: 640x640 1 animal, 403.5ms
5: 640x640 1 animal, 403.5ms
6: 640x640 1 animal, 403.5ms
7: 640x640 1 animal, 403.5ms
8: 640x640 1 animal, 403.5ms
9: 640x640 1 animal, 403.5ms
10: 640x640 1 animal, 403.5ms
11: 640x640 1 animal, 403.5ms
12: 640x640 1 animal, 403.5ms
13: 640x640 1 animal, 403.5ms
14: 640x640 1 animal, 403.5ms
15: 640x640 1 animal, 403.5ms
Speed: 2.6ms preprocess, 403.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 21%|████████████████████████████▍                                                                                                           | 27/129 [02:20<10:42,  6.30s/it]

0: 640x640 (no detections), 404.0ms
1: 640x640 (no detections), 404.0ms
2: 640x640 (no detections), 404.0ms
3: 640x640 (no detections), 404.0ms
4: 640x640 (no detections), 404.0ms
5: 640x640 (no detections), 404.0ms
6: 640x640 (no detections), 404.0ms
7: 640x640 (no detections), 404.0ms
8: 640x640 1 animal, 404.0ms
9: 640x640 1 animal, 404.0ms
10: 640x640 1 animal, 404.0ms
11: 640x640 1 animal, 404.0ms
12: 640x640 1 animal, 404.0ms
13: 640x640 1 animal, 404.0ms
14: 640x640 1 animal, 404.0ms
15: 640x640 1 animal, 404.0ms
Speed: 2.6ms preprocess, 404.0ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 22%|█████████████████████████████▌                                                                                                          | 28/129 [02:27<11:01,  6.55s/it]

0: 384x640 1 animal, 235.0ms
1: 384x640 1 animal, 235.0ms
2: 384x640 1 animal, 235.0ms
3: 384x640 1 animal, 235.0ms
4: 384x640 1 animal, 235.0ms
5: 384x640 1 animal, 235.0ms
6: 384x640 1 animal, 235.0ms
7: 384x640 1 animal, 235.0ms
8: 384x640 1 animal, 235.0ms
9: 384x640 1 animal, 235.0ms
10: 384x640 1 animal, 235.0ms
11: 384x640 1 animal, 235.0ms
12: 384x640 1 animal, 235.0ms
13: 384x640 1 animal, 235.0ms
14: 384x640 1 animal, 235.0ms
15: 384x640 1 animal, 235.0ms
Speed: 1.7ms preprocess, 235.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 22%|██████████████████████████████▌                                                                                                         | 29/129 [02:32<09:57,  5.97s/it]

0: 384x640 1 animal, 234.7ms
1: 384x640 1 animal, 234.7ms
2: 384x640 1 animal, 234.7ms
3: 384x640 1 animal, 234.7ms
4: 384x640 1 animal, 234.7ms
5: 384x640 1 animal, 234.7ms
6: 384x640 1 animal, 234.7ms
7: 384x640 (no detections), 234.7ms
8: 384x640 1 animal, 234.7ms
9: 384x640 (no detections), 234.7ms
10: 384x640 (no detections), 234.7ms
11: 384x640 (no detections), 234.7ms
12: 384x640 (no detections), 234.7ms
13: 384x640 (no detections), 234.7ms
14: 384x640 (no detections), 234.7ms
15: 384x640 (no detections), 234.7ms
Speed: 1.9ms preprocess, 234.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 23%|███████████████████████████████▋                                                                                                        | 30/129 [02:36<09:08,  5.54s/it]

0: 384x640 1 animal, 231.6ms
1: 384x640 1 animal, 231.6ms
2: 384x640 1 animal, 231.6ms
3: 384x640 1 animal, 231.6ms
4: 384x640 1 animal, 231.6ms
5: 384x640 1 animal, 231.6ms
6: 384x640 1 animal, 231.6ms
7: 384x640 1 animal, 231.6ms
8: 384x640 1 animal, 231.6ms
9: 384x640 1 animal, 231.6ms
10: 384x640 1 animal, 231.6ms
11: 384x640 1 animal, 231.6ms
12: 384x640 1 animal, 231.6ms
13: 384x640 1 animal, 231.6ms
14: 384x640 1 animal, 231.6ms
15: 384x640 1 animal, 231.6ms
Speed: 2.0ms preprocess, 231.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 24%|████████████████████████████████▋                                                                                                       | 31/129 [02:41<08:33,  5.24s/it]

0: 384x640 2 animals, 234.9ms
1: 384x640 1 animal, 234.9ms
2: 384x640 2 animals, 234.9ms
3: 384x640 1 animal, 234.9ms
4: 384x640 1 animal, 234.9ms
5: 384x640 1 animal, 234.9ms
6: 384x640 1 animal, 234.9ms
7: 384x640 1 animal, 234.9ms
8: 384x640 1 animal, 234.9ms
9: 384x640 1 animal, 234.9ms
10: 384x640 1 animal, 234.9ms
11: 384x640 1 animal, 234.9ms
12: 384x640 1 animal, 234.9ms
13: 384x640 1 animal, 234.9ms
14: 384x640 2 animals, 234.9ms
15: 384x640 (no detections), 234.9ms
Speed: 1.7ms preprocess, 234.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 25%|█████████████████████████████████▋                                                                                                      | 32/129 [02:45<08:09,  5.04s/it]

0: 384x640 2 animals, 234.8ms
1: 384x640 1 animal, 234.8ms
2: 384x640 1 animal, 234.8ms
3: 384x640 1 animal, 234.8ms
4: 384x640 1 animal, 234.8ms
5: 384x640 1 animal, 234.8ms
6: 384x640 1 animal, 234.8ms
7: 384x640 1 animal, 234.8ms
8: 384x640 1 animal, 234.8ms
9: 384x640 1 animal, 234.8ms
10: 384x640 1 animal, 234.8ms
11: 384x640 1 animal, 234.8ms
12: 384x640 1 animal, 234.8ms
13: 384x640 1 animal, 234.8ms
14: 384x640 1 animal, 234.8ms
15: 384x640 1 animal, 234.8ms
Speed: 1.7ms preprocess, 234.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 26%|██████████████████████████████████▊                                                                                                     | 33/129 [02:50<07:50,  4.90s/it]

0: 384x640 1 animal, 232.3ms
1: 384x640 1 animal, 232.3ms
2: 384x640 1 animal, 232.3ms
3: 384x640 1 animal, 232.3ms
4: 384x640 1 animal, 232.3ms
5: 384x640 1 animal, 232.3ms
6: 384x640 1 animal, 232.3ms
7: 384x640 1 animal, 232.3ms
8: 384x640 1 animal, 232.3ms
9: 384x640 1 animal, 232.3ms
10: 384x640 1 animal, 232.3ms
11: 384x640 1 animal, 232.3ms
12: 384x640 1 animal, 232.3ms
13: 384x640 1 animal, 232.3ms
14: 384x640 1 animal, 232.3ms
15: 384x640 1 animal, 232.3ms
Speed: 1.7ms preprocess, 232.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 26%|███████████████████████████████████▊                                                                                                    | 34/129 [02:54<07:34,  4.79s/it]

0: 384x640 1 animal, 234.0ms
1: 384x640 1 animal, 234.0ms
2: 384x640 1 animal, 234.0ms
3: 384x640 1 animal, 234.0ms
4: 384x640 1 animal, 234.0ms
5: 384x640 1 animal, 234.0ms
6: 384x640 1 animal, 234.0ms
7: 384x640 (no detections), 234.0ms
8: 384x640 (no detections), 234.0ms
9: 384x640 (no detections), 234.0ms
10: 384x640 (no detections), 234.0ms
11: 384x640 (no detections), 234.0ms
12: 384x640 (no detections), 234.0ms
13: 384x640 (no detections), 234.0ms
14: 384x640 (no detections), 234.0ms
15: 384x640 (no detections), 234.0ms
Speed: 1.8ms preprocess, 234.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 27%|████████████████████████████████████▉                                                                                                   | 35/129 [02:59<07:21,  4.70s/it]

0: 640x640 1 animal, 401.3ms
1: 640x640 (no detections), 401.3ms
2: 640x640 (no detections), 401.3ms
3: 640x640 (no detections), 401.3ms
4: 640x640 (no detections), 401.3ms
5: 640x640 (no detections), 401.3ms
6: 640x640 (no detections), 401.3ms
7: 640x640 (no detections), 401.3ms
8: 640x640 (no detections), 401.3ms
9: 640x640 (no detections), 401.3ms
10: 640x640 1 animal, 401.3ms
11: 640x640 1 animal, 401.3ms
12: 640x640 1 animal, 401.3ms
13: 640x640 1 animal, 401.3ms
14: 640x640 (no detections), 401.3ms
15: 640x640 (no detections), 401.3ms
Speed: 2.5ms preprocess, 401.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 28%|█████████████████████████████████████▉                                                                                                  | 36/129 [03:06<08:23,  5.41s/it]

0: 640x640 (no detections), 392.1ms
1: 640x640 (no detections), 392.1ms
2: 640x640 (no detections), 392.1ms
3: 640x640 (no detections), 392.1ms
4: 640x640 1 animal, 392.1ms
5: 640x640 1 animal, 392.1ms
6: 640x640 1 animal, 392.1ms
7: 640x640 (no detections), 392.1ms
8: 640x640 (no detections), 392.1ms
9: 640x640 (no detections), 392.1ms
10: 640x640 (no detections), 392.1ms
11: 640x640 (no detections), 392.1ms
12: 640x640 (no detections), 392.1ms
13: 640x640 (no detections), 392.1ms
14: 640x640 (no detections), 392.1ms
15: 640x640 (no detections), 392.1ms
Speed: 2.6ms preprocess, 392.1ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 29%|███████████████████████████████████████                                                                                                 | 37/129 [03:13<09:00,  5.87s/it]

0: 384x640 (no detections), 228.2ms
1: 384x640 (no detections), 228.2ms
2: 384x640 (no detections), 228.2ms
3: 384x640 (no detections), 228.2ms
4: 384x640 (no detections), 228.2ms
5: 384x640 (no detections), 228.2ms
6: 384x640 (no detections), 228.2ms
7: 384x640 1 animal, 228.2ms
8: 384x640 1 animal, 228.2ms
9: 384x640 1 animal, 228.2ms
10: 384x640 1 animal, 228.2ms
11: 384x640 1 animal, 228.2ms
12: 384x640 1 animal, 228.2ms
13: 384x640 1 animal, 228.2ms
14: 384x640 1 animal, 228.2ms
15: 384x640 1 animal, 228.2ms
Speed: 2.0ms preprocess, 228.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 29%|████████████████████████████████████████                                                                                                | 38/129 [03:17<08:17,  5.46s/it]

0: 640x640 1 animal, 390.4ms
1: 640x640 1 animal, 390.4ms
2: 640x640 1 animal, 390.4ms
3: 640x640 1 animal, 390.4ms
4: 640x640 1 animal, 390.4ms
5: 640x640 1 animal, 390.4ms
6: 640x640 1 animal, 390.4ms
7: 640x640 1 animal, 390.4ms
8: 640x640 1 animal, 390.4ms
9: 640x640 1 animal, 390.4ms
10: 640x640 1 animal, 390.4ms
11: 640x640 1 animal, 390.4ms
12: 640x640 1 animal, 390.4ms
13: 640x640 (no detections), 390.4ms
14: 640x640 (no detections), 390.4ms
15: 640x640 (no detections), 390.4ms
Speed: 2.5ms preprocess, 390.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 30%|█████████████████████████████████████████                                                                                               | 39/129 [03:24<08:53,  5.92s/it]

0: 640x640 (no detections), 389.4ms
1: 640x640 (no detections), 389.4ms
2: 640x640 (no detections), 389.4ms
3: 640x640 (no detections), 389.4ms
4: 640x640 (no detections), 389.4ms
5: 640x640 (no detections), 389.4ms
6: 640x640 2 animals, 389.4ms
7: 640x640 1 animal, 389.4ms
8: 640x640 1 animal, 389.4ms
9: 640x640 1 animal, 389.4ms
10: 640x640 2 animals, 389.4ms
11: 640x640 2 animals, 389.4ms
12: 640x640 1 animal, 389.4ms
13: 640x640 1 animal, 389.4ms
14: 640x640 1 animal, 389.4ms
15: 640x640 1 animal, 389.4ms
Speed: 2.6ms preprocess, 389.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 31%|██████████████████████████████████████████▏                                                                                             | 40/129 [03:31<09:14,  6.23s/it]

0: 384x640 1 animal, 228.2ms
1: 384x640 1 animal, 228.2ms
2: 384x640 1 animal, 228.2ms
3: 384x640 1 animal, 228.2ms
4: 384x640 1 animal, 228.2ms
5: 384x640 1 animal, 228.2ms
6: 384x640 1 animal, 228.2ms
7: 384x640 1 animal, 228.2ms
8: 384x640 1 animal, 228.2ms
9: 384x640 1 animal, 228.2ms
10: 384x640 1 animal, 228.2ms
11: 384x640 1 animal, 228.2ms
12: 384x640 1 animal, 228.2ms
13: 384x640 1 animal, 228.2ms
14: 384x640 1 animal, 228.2ms
15: 384x640 1 animal, 228.2ms
Speed: 1.8ms preprocess, 228.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 32%|███████████████████████████████████████████▏                                                                                            | 41/129 [03:36<08:20,  5.69s/it]

0: 384x640 1 animal, 229.9ms
1: 384x640 1 animal, 229.9ms
2: 384x640 1 animal, 229.9ms
3: 384x640 1 animal, 229.9ms
4: 384x640 1 animal, 229.9ms
5: 384x640 1 animal, 229.9ms
6: 384x640 (no detections), 229.9ms
7: 384x640 (no detections), 229.9ms
8: 384x640 (no detections), 229.9ms
9: 384x640 (no detections), 229.9ms
10: 384x640 (no detections), 229.9ms
11: 384x640 (no detections), 229.9ms
12: 384x640 (no detections), 229.9ms
13: 384x640 (no detections), 229.9ms
14: 384x640 1 animal, 229.9ms
15: 384x640 1 animal, 229.9ms
Speed: 1.7ms preprocess, 229.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 33%|████████████████████████████████████████████▎                                                                                           | 42/129 [03:40<07:42,  5.32s/it]

0: 384x640 1 animal, 228.2ms
1: 384x640 1 animal, 228.2ms
2: 384x640 1 animal, 228.2ms
3: 384x640 1 animal, 228.2ms
4: 384x640 1 animal, 228.2ms
5: 384x640 1 animal, 228.2ms
6: 384x640 1 animal, 228.2ms
7: 384x640 1 animal, 228.2ms
8: 384x640 1 animal, 228.2ms
9: 384x640 1 animal, 228.2ms
10: 384x640 2 animals, 228.2ms
11: 384x640 1 animal, 228.2ms
12: 384x640 1 animal, 228.2ms
13: 384x640 1 animal, 228.2ms
14: 384x640 1 animal, 228.2ms
15: 384x640 1 animal, 228.2ms
Speed: 1.8ms preprocess, 228.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 33%|█████████████████████████████████████████████▎                                                                                          | 43/129 [03:45<07:13,  5.04s/it]

0: 384x640 1 animal, 231.2ms
1: 384x640 1 animal, 231.2ms
2: 384x640 1 animal, 231.2ms
3: 384x640 1 animal, 231.2ms
4: 384x640 1 animal, 231.2ms
5: 384x640 1 animal, 231.2ms
6: 384x640 1 animal, 231.2ms
7: 384x640 1 animal, 231.2ms
8: 384x640 1 animal, 231.2ms
9: 384x640 1 animal, 231.2ms
10: 384x640 1 animal, 231.2ms
11: 384x640 1 animal, 231.2ms
12: 384x640 1 animal, 231.2ms
13: 384x640 1 animal, 231.2ms
14: 384x640 1 animal, 231.2ms
15: 384x640 (no detections), 231.2ms
Speed: 2.2ms preprocess, 231.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 34%|██████████████████████████████████████████████▍                                                                                         | 44/129 [03:49<06:54,  4.88s/it]

0: 384x640 (no detections), 230.3ms
1: 384x640 (no detections), 230.3ms
2: 384x640 (no detections), 230.3ms
3: 384x640 (no detections), 230.3ms
4: 384x640 (no detections), 230.3ms
5: 384x640 (no detections), 230.3ms
6: 384x640 1 animal, 230.3ms
7: 384x640 (no detections), 230.3ms
8: 384x640 (no detections), 230.3ms
9: 384x640 1 animal, 230.3ms
10: 384x640 (no detections), 230.3ms
11: 384x640 (no detections), 230.3ms
12: 384x640 (no detections), 230.3ms
13: 384x640 (no detections), 230.3ms
14: 384x640 (no detections), 230.3ms
15: 384x640 (no detections), 230.3ms
Speed: 1.7ms preprocess, 230.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 35%|███████████████████████████████████████████████▍                                                                                        | 45/129 [03:54<06:41,  4.78s/it]

0: 384x640 1 animal, 229.8ms
1: 384x640 1 animal, 229.8ms
2: 384x640 1 animal, 229.8ms
3: 384x640 (no detections), 229.8ms
4: 384x640 (no detections), 229.8ms
5: 384x640 (no detections), 229.8ms
6: 384x640 (no detections), 229.8ms
7: 384x640 (no detections), 229.8ms
8: 384x640 (no detections), 229.8ms
9: 384x640 (no detections), 229.8ms
10: 384x640 1 animal, 229.8ms
11: 384x640 1 animal, 229.8ms
12: 384x640 1 animal, 229.8ms
13: 384x640 1 animal, 229.8ms
14: 384x640 1 animal, 229.8ms
15: 384x640 1 animal, 229.8ms
Speed: 1.7ms preprocess, 229.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 36%|████████████████████████████████████████████████▍                                                                                       | 46/129 [03:58<06:33,  4.73s/it]

0: 384x640 1 animal, 229.1ms
1: 384x640 1 animal, 229.1ms
2: 384x640 1 animal, 229.1ms
3: 384x640 1 animal, 229.1ms
4: 384x640 1 animal, 229.1ms
5: 384x640 1 animal, 229.1ms
6: 384x640 1 animal, 229.1ms
7: 384x640 1 animal, 229.1ms
8: 384x640 1 animal, 229.1ms
9: 384x640 1 animal, 229.1ms
10: 384x640 1 animal, 229.1ms
11: 384x640 1 animal, 229.1ms
12: 384x640 1 animal, 229.1ms
13: 384x640 1 animal, 229.1ms
14: 384x640 1 animal, 229.1ms
15: 384x640 1 animal, 229.1ms
Speed: 1.7ms preprocess, 229.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 36%|█████████████████████████████████████████████████▌                                                                                      | 47/129 [04:03<06:25,  4.70s/it]

0: 384x640 1 animal, 230.6ms
1: 384x640 1 animal, 230.6ms
2: 384x640 1 animal, 230.6ms
3: 384x640 1 animal, 230.6ms
4: 384x640 1 animal, 230.6ms
5: 384x640 1 animal, 230.6ms
6: 384x640 1 animal, 230.6ms
7: 384x640 (no detections), 230.6ms
8: 384x640 1 animal, 230.6ms
9: 384x640 1 animal, 230.6ms
10: 384x640 1 animal, 230.6ms
11: 384x640 1 animal, 230.6ms
12: 384x640 1 animal, 230.6ms
13: 384x640 1 animal, 230.6ms
14: 384x640 1 animal, 230.6ms
15: 384x640 1 animal, 230.6ms
Speed: 1.7ms preprocess, 230.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 37%|██████████████████████████████████████████████████▌                                                                                     | 48/129 [04:08<06:18,  4.67s/it]

0: 384x640 1 animal, 234.2ms
1: 384x640 1 animal, 234.2ms
2: 384x640 1 animal, 234.2ms
3: 384x640 1 animal, 234.2ms
4: 384x640 1 animal, 234.2ms
5: 384x640 1 animal, 234.2ms
6: 384x640 1 animal, 234.2ms
7: 384x640 1 animal, 234.2ms
8: 384x640 1 animal, 234.2ms
9: 384x640 1 animal, 234.2ms
10: 384x640 1 animal, 234.2ms
11: 384x640 1 animal, 234.2ms
12: 384x640 1 animal, 234.2ms
13: 384x640 1 animal, 234.2ms
14: 384x640 1 animal, 234.2ms
15: 384x640 1 animal, 234.2ms
Speed: 1.7ms preprocess, 234.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 38%|███████████████████████████████████████████████████▋                                                                                    | 49/129 [04:12<06:10,  4.64s/it]

0: 384x640 (no detections), 234.9ms
1: 384x640 (no detections), 234.9ms
2: 384x640 (no detections), 234.9ms
3: 384x640 (no detections), 234.9ms
4: 384x640 (no detections), 234.9ms
5: 384x640 (no detections), 234.9ms
6: 384x640 1 animal, 234.9ms
7: 384x640 1 animal, 234.9ms
8: 384x640 1 animal, 234.9ms
9: 384x640 1 animal, 234.9ms
10: 384x640 1 animal, 234.9ms
11: 384x640 1 animal, 234.9ms
12: 384x640 1 animal, 234.9ms
13: 384x640 1 animal, 234.9ms
14: 384x640 1 animal, 234.9ms
15: 384x640 1 animal, 234.9ms
Speed: 1.8ms preprocess, 234.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 39%|████████████████████████████████████████████████████▋                                                                                   | 50/129 [04:17<06:05,  4.62s/it]

0: 384x640 1 animal, 234.8ms
1: 384x640 1 animal, 234.8ms
2: 384x640 1 animal, 234.8ms
3: 384x640 1 animal, 234.8ms
4: 384x640 1 animal, 234.8ms
5: 384x640 1 animal, 234.8ms
6: 384x640 1 animal, 234.8ms
7: 384x640 1 animal, 234.8ms
8: 384x640 1 animal, 234.8ms
9: 384x640 1 animal, 234.8ms
10: 384x640 2 animals, 234.8ms
11: 384x640 1 animal, 234.8ms
12: 384x640 1 animal, 234.8ms
13: 384x640 1 animal, 234.8ms
14: 384x640 1 animal, 234.8ms
15: 384x640 1 animal, 234.8ms
Speed: 2.0ms preprocess, 234.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 40%|█████████████████████████████████████████████████████▊                                                                                  | 51/129 [04:21<06:01,  4.63s/it]

0: 384x640 1 animal, 240.0ms
1: 384x640 1 animal, 240.0ms
2: 384x640 1 animal, 240.0ms
3: 384x640 1 animal, 240.0ms
4: 384x640 1 animal, 240.0ms
5: 384x640 1 animal, 240.0ms
6: 384x640 1 animal, 240.0ms
7: 384x640 1 animal, 240.0ms
8: 384x640 (no detections), 240.0ms
9: 384x640 1 animal, 240.0ms
10: 384x640 1 animal, 240.0ms
11: 384x640 1 animal, 240.0ms
12: 384x640 1 animal, 240.0ms
13: 384x640 1 animal, 240.0ms
14: 384x640 2 animals, 240.0ms
15: 384x640 2 animals, 240.0ms
Speed: 1.7ms preprocess, 240.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 40%|██████████████████████████████████████████████████████▊                                                                                 | 52/129 [04:26<06:01,  4.70s/it]

0: 640x640 3 animals, 401.7ms
1: 640x640 2 animals, 401.7ms
2: 640x640 2 animals, 401.7ms
3: 640x640 2 animals, 401.7ms
4: 640x640 2 animals, 401.7ms
5: 640x640 1 animal, 401.7ms
6: 640x640 (no detections), 401.7ms
7: 640x640 (no detections), 401.7ms
8: 640x640 1 animal, 401.7ms
9: 640x640 1 animal, 401.7ms
10: 640x640 1 animal, 401.7ms
11: 640x640 1 animal, 401.7ms
12: 640x640 1 animal, 401.7ms
13: 640x640 1 animal, 401.7ms
14: 640x640 1 animal, 401.7ms
15: 640x640 1 animal, 401.7ms
Speed: 2.5ms preprocess, 401.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 41%|███████████████████████████████████████████████████████▉                                                                                | 53/129 [04:33<06:52,  5.42s/it]

0: 640x640 1 animal, 396.9ms
1: 640x640 1 animal, 396.9ms
2: 640x640 1 animal, 396.9ms
3: 640x640 1 animal, 396.9ms
4: 640x640 1 animal, 396.9ms
5: 640x640 1 animal, 396.9ms
6: 640x640 1 animal, 396.9ms
7: 640x640 1 animal, 396.9ms
8: 640x640 1 animal, 396.9ms
9: 640x640 (no detections), 396.9ms
10: 640x640 (no detections), 396.9ms
11: 640x640 (no detections), 396.9ms
12: 640x640 1 animal, 396.9ms
13: 640x640 1 animal, 396.9ms
14: 640x640 1 animal, 396.9ms
15: 640x640 1 animal, 396.9ms
Speed: 2.7ms preprocess, 396.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 42%|████████████████████████████████████████████████████████▉                                                                               | 54/129 [04:40<07:18,  5.85s/it]

0: 384x640 1 animal, 236.2ms
1: 384x640 1 animal, 236.2ms
2: 384x640 1 animal, 236.2ms
3: 384x640 1 animal, 236.2ms
4: 384x640 1 animal, 236.2ms
5: 384x640 1 animal, 236.2ms
6: 384x640 1 animal, 236.2ms
7: 384x640 1 animal, 236.2ms
8: 384x640 1 animal, 236.2ms
9: 384x640 1 animal, 236.2ms
10: 384x640 1 animal, 236.2ms
11: 384x640 1 animal, 236.2ms
12: 384x640 1 animal, 236.2ms
13: 384x640 1 animal, 236.2ms
14: 384x640 1 animal, 236.2ms
15: 384x640 1 animal, 236.2ms
Speed: 1.7ms preprocess, 236.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 43%|█████████████████████████████████████████████████████████▉                                                                              | 55/129 [04:45<06:45,  5.48s/it]

0: 384x640 1 animal, 235.8ms
1: 384x640 1 animal, 235.8ms
2: 384x640 1 animal, 235.8ms
3: 384x640 1 animal, 235.8ms
4: 384x640 1 animal, 235.8ms
5: 384x640 1 animal, 235.8ms
6: 384x640 1 animal, 235.8ms
7: 384x640 1 animal, 235.8ms
8: 384x640 1 animal, 235.8ms
9: 384x640 1 animal, 235.8ms
10: 384x640 1 animal, 235.8ms
11: 384x640 1 animal, 235.8ms
12: 384x640 1 animal, 235.8ms
13: 384x640 1 animal, 235.8ms
14: 384x640 1 animal, 235.8ms
15: 384x640 1 animal, 235.8ms
Speed: 1.7ms preprocess, 235.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 43%|███████████████████████████████████████████████████████████                                                                             | 56/129 [04:49<06:20,  5.21s/it]

0: 640x640 1 animal, 399.5ms
1: 640x640 1 animal, 399.5ms
2: 640x640 1 animal, 399.5ms
3: 640x640 1 animal, 399.5ms
4: 640x640 2 animals, 399.5ms
5: 640x640 2 animals, 399.5ms
6: 640x640 (no detections), 399.5ms
7: 640x640 (no detections), 399.5ms
8: 640x640 (no detections), 399.5ms
9: 640x640 (no detections), 399.5ms
10: 640x640 (no detections), 399.5ms
11: 640x640 (no detections), 399.5ms
12: 640x640 (no detections), 399.5ms
13: 640x640 (no detections), 399.5ms
14: 640x640 1 animal, 399.5ms
15: 640x640 1 animal, 399.5ms
Speed: 2.7ms preprocess, 399.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 44%|████████████████████████████████████████████████████████████                                                                            | 57/129 [04:56<06:52,  5.74s/it]

0: 640x640 1 animal, 403.2ms
1: 640x640 1 animal, 403.2ms
2: 640x640 1 animal, 403.2ms
3: 640x640 1 animal, 403.2ms
4: 640x640 1 animal, 403.2ms
5: 640x640 1 animal, 403.2ms
6: 640x640 1 animal, 403.2ms
7: 640x640 1 animal, 403.2ms
8: 640x640 1 animal, 403.2ms
9: 640x640 1 animal, 403.2ms
10: 640x640 1 animal, 403.2ms
11: 640x640 1 animal, 403.2ms
12: 640x640 1 animal, 403.2ms
13: 640x640 1 animal, 403.2ms
14: 640x640 1 animal, 403.2ms
15: 640x640 (no detections), 403.2ms
Speed: 2.5ms preprocess, 403.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 45%|█████████████████████████████████████████████████████████████▏                                                                          | 58/129 [05:03<07:15,  6.14s/it]

0: 640x640 (no detections), 403.7ms
1: 640x640 (no detections), 403.7ms
2: 640x640 1 animal, 403.7ms
3: 640x640 1 animal, 403.7ms
4: 640x640 1 animal, 403.7ms
5: 640x640 1 animal, 403.7ms
6: 640x640 1 animal, 403.7ms
7: 640x640 1 animal, 403.7ms
8: 640x640 1 animal, 403.7ms
9: 640x640 1 animal, 403.7ms
10: 640x640 1 animal, 403.7ms
11: 640x640 1 animal, 403.7ms
12: 640x640 1 animal, 403.7ms
13: 640x640 1 animal, 403.7ms
14: 640x640 1 animal, 403.7ms
15: 640x640 1 animal, 403.7ms
Speed: 2.8ms preprocess, 403.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 46%|██████████████████████████████████████████████████████████████▏                                                                         | 59/129 [05:11<07:32,  6.47s/it]

0: 384x640 1 animal, 234.6ms
1: 384x640 1 animal, 234.6ms
2: 384x640 1 animal, 234.6ms
3: 384x640 1 animal, 234.6ms
4: 384x640 1 animal, 234.6ms
5: 384x640 1 animal, 234.6ms
6: 384x640 1 animal, 234.6ms
7: 384x640 (no detections), 234.6ms
8: 384x640 (no detections), 234.6ms
9: 384x640 (no detections), 234.6ms
10: 384x640 (no detections), 234.6ms
11: 384x640 (no detections), 234.6ms
12: 384x640 (no detections), 234.6ms
13: 384x640 (no detections), 234.6ms
14: 384x640 (no detections), 234.6ms
15: 384x640 (no detections), 234.6ms
Speed: 1.7ms preprocess, 234.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 47%|███████████████████████████████████████████████████████████████▎                                                                        | 60/129 [05:15<06:46,  5.89s/it]

0: 384x640 1 animal, 235.9ms
1: 384x640 1 animal, 235.9ms
2: 384x640 1 animal, 235.9ms
3: 384x640 1 animal, 235.9ms
4: 384x640 1 animal, 235.9ms
5: 384x640 1 animal, 235.9ms
6: 384x640 1 animal, 235.9ms
7: 384x640 1 animal, 235.9ms
8: 384x640 1 animal, 235.9ms
9: 384x640 1 animal, 235.9ms
10: 384x640 1 animal, 235.9ms
11: 384x640 1 animal, 235.9ms
12: 384x640 1 animal, 235.9ms
13: 384x640 1 animal, 235.9ms
14: 384x640 1 animal, 235.9ms
15: 384x640 1 animal, 235.9ms
Speed: 1.7ms preprocess, 235.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 47%|████████████████████████████████████████████████████████████████▎                                                                       | 61/129 [05:20<06:14,  5.50s/it]

0: 384x640 1 animal, 235.9ms
1: 384x640 1 animal, 235.9ms
2: 384x640 1 animal, 235.9ms
3: 384x640 1 animal, 235.9ms
4: 384x640 1 animal, 235.9ms
5: 384x640 1 animal, 235.9ms
6: 384x640 1 animal, 235.9ms
7: 384x640 1 animal, 235.9ms
8: 384x640 1 animal, 235.9ms
9: 384x640 1 animal, 235.9ms
10: 384x640 1 animal, 235.9ms
11: 384x640 1 animal, 235.9ms
12: 384x640 1 animal, 235.9ms
13: 384x640 1 animal, 235.9ms
14: 384x640 1 animal, 235.9ms
15: 384x640 1 animal, 235.9ms
Speed: 1.9ms preprocess, 235.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 48%|█████████████████████████████████████████████████████████████████▎                                                                      | 62/129 [05:24<05:50,  5.24s/it]

0: 384x640 1 animal, 235.9ms
1: 384x640 1 animal, 235.9ms
2: 384x640 1 animal, 235.9ms
3: 384x640 1 animal, 235.9ms
4: 384x640 1 animal, 235.9ms
5: 384x640 1 animal, 235.9ms
6: 384x640 1 animal, 235.9ms
7: 384x640 1 animal, 235.9ms
8: 384x640 1 animal, 235.9ms
9: 384x640 2 animals, 235.9ms
10: 384x640 3 animals, 235.9ms
11: 384x640 1 animal, 235.9ms
12: 384x640 1 animal, 235.9ms
13: 384x640 2 animals, 235.9ms
14: 384x640 1 animal, 235.9ms
15: 384x640 2 animals, 235.9ms
Speed: 1.9ms preprocess, 235.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 49%|██████████████████████████████████████████████████████████████████▍                                                                     | 63/129 [05:29<05:32,  5.04s/it]

0: 640x640 1 animal, 399.9ms
1: 640x640 2 animals, 399.9ms
2: 640x640 1 animal, 399.9ms
3: 640x640 1 animal, 399.9ms
4: 640x640 1 animal, 399.9ms
5: 640x640 1 animal, 399.9ms
6: 640x640 1 animal, 399.9ms
7: 640x640 1 animal, 399.9ms
8: 640x640 1 animal, 399.9ms
9: 640x640 1 animal, 399.9ms
10: 640x640 1 animal, 399.9ms
11: 640x640 1 animal, 399.9ms
12: 640x640 (no detections), 399.9ms
13: 640x640 1 animal, 399.9ms
14: 640x640 1 animal, 399.9ms
15: 640x640 1 animal, 399.9ms
Speed: 2.7ms preprocess, 399.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 50%|███████████████████████████████████████████████████████████████████▍                                                                    | 64/129 [05:36<06:04,  5.61s/it]

0: 640x640 1 animal, 401.2ms
1: 640x640 (no detections), 401.2ms
2: 640x640 (no detections), 401.2ms
3: 640x640 (no detections), 401.2ms
4: 640x640 (no detections), 401.2ms
5: 640x640 (no detections), 401.2ms
6: 640x640 1 animal, 401.2ms
7: 640x640 1 animal, 401.2ms
8: 640x640 2 animals, 401.2ms
9: 640x640 1 animal, 401.2ms
10: 640x640 2 animals, 401.2ms
11: 640x640 1 animal, 401.2ms
12: 640x640 2 animals, 401.2ms
13: 640x640 1 animal, 401.2ms
14: 640x640 1 animal, 401.2ms
15: 640x640 1 animal, 401.2ms
Speed: 2.5ms preprocess, 401.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 50%|████████████████████████████████████████████████████████████████████▌                                                                   | 65/129 [05:43<06:24,  6.01s/it]

0: 640x640 1 animal, 399.1ms
1: 640x640 1 animal, 399.1ms
2: 640x640 1 animal, 399.1ms
3: 640x640 1 animal, 399.1ms
4: 640x640 1 animal, 399.1ms
5: 640x640 1 animal, 399.1ms
6: 640x640 1 animal, 399.1ms
7: 640x640 1 animal, 399.1ms
8: 640x640 1 animal, 399.1ms
9: 640x640 1 animal, 399.1ms
10: 640x640 1 animal, 399.1ms
11: 640x640 1 animal, 399.1ms
12: 640x640 1 animal, 399.1ms
13: 640x640 1 animal, 399.1ms
14: 640x640 1 animal, 399.1ms
15: 640x640 1 animal, 399.1ms
Speed: 2.5ms preprocess, 399.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 51%|█████████████████████████████████████████████████████████████████████▌                                                                  | 66/129 [05:50<06:36,  6.29s/it]

0: 384x640 1 animal, 236.4ms
1: 384x640 1 animal, 236.4ms
2: 384x640 1 animal, 236.4ms
3: 384x640 1 animal, 236.4ms
4: 384x640 1 animal, 236.4ms
5: 384x640 1 animal, 236.4ms
6: 384x640 1 animal, 236.4ms
7: 384x640 1 animal, 236.4ms
8: 384x640 1 animal, 236.4ms
9: 384x640 1 animal, 236.4ms
10: 384x640 1 animal, 236.4ms
11: 384x640 1 animal, 236.4ms
12: 384x640 1 animal, 236.4ms
13: 384x640 1 animal, 236.4ms
14: 384x640 1 animal, 236.4ms
15: 384x640 1 animal, 236.4ms
Speed: 2.0ms preprocess, 236.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 52%|██████████████████████████████████████████████████████████████████████▋                                                                 | 67/129 [05:54<05:58,  5.78s/it]

0: 384x640 1 animal, 235.6ms
1: 384x640 1 animal, 235.6ms
2: 384x640 1 animal, 235.6ms
3: 384x640 1 animal, 235.6ms
4: 384x640 1 animal, 235.6ms
5: 384x640 1 animal, 235.6ms
6: 384x640 1 animal, 235.6ms
7: 384x640 1 animal, 235.6ms
8: 384x640 1 animal, 235.6ms
9: 384x640 1 animal, 235.6ms
10: 384x640 1 animal, 235.6ms
11: 384x640 1 animal, 235.6ms
12: 384x640 1 animal, 235.6ms
13: 384x640 1 animal, 235.6ms
14: 384x640 1 animal, 235.6ms
15: 384x640 2 animals, 235.6ms
Speed: 1.9ms preprocess, 235.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 53%|███████████████████████████████████████████████████████████████████████▋                                                                | 68/129 [05:59<05:30,  5.42s/it]

0: 384x640 1 animal, 229.4ms
1: 384x640 1 animal, 229.4ms
2: 384x640 1 animal, 229.4ms
3: 384x640 1 animal, 229.4ms
4: 384x640 1 animal, 229.4ms
5: 384x640 1 animal, 229.4ms
6: 384x640 1 animal, 229.4ms
7: 384x640 1 animal, 229.4ms
8: 384x640 1 animal, 229.4ms
9: 384x640 1 animal, 229.4ms
10: 384x640 1 animal, 229.4ms
11: 384x640 1 animal, 229.4ms
12: 384x640 1 animal, 229.4ms
13: 384x640 1 animal, 229.4ms
14: 384x640 1 animal, 229.4ms
15: 384x640 1 animal, 229.4ms
Speed: 1.9ms preprocess, 229.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 53%|████████████████████████████████████████████████████████████████████████▋                                                               | 69/129 [06:04<05:08,  5.14s/it]

0: 384x640 1 animal, 229.7ms
1: 384x640 1 animal, 229.7ms
2: 384x640 1 animal, 229.7ms
3: 384x640 1 animal, 229.7ms
4: 384x640 1 animal, 229.7ms
5: 384x640 1 animal, 229.7ms
6: 384x640 1 animal, 229.7ms
7: 384x640 1 animal, 229.7ms
8: 384x640 1 animal, 229.7ms
9: 384x640 1 animal, 229.7ms
10: 384x640 1 animal, 229.7ms
11: 384x640 1 animal, 229.7ms
12: 384x640 1 animal, 229.7ms
13: 384x640 1 animal, 229.7ms
14: 384x640 1 animal, 229.7ms
15: 384x640 1 animal, 229.7ms
Speed: 1.9ms preprocess, 229.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 54%|█████████████████████████████████████████████████████████████████████████▊                                                              | 70/129 [06:08<04:53,  4.98s/it]

0: 384x640 1 animal, 234.0ms
1: 384x640 1 animal, 234.0ms
2: 384x640 1 animal, 234.0ms
3: 384x640 1 animal, 234.0ms
4: 384x640 1 animal, 234.0ms
5: 384x640 1 animal, 234.0ms
6: 384x640 1 animal, 234.0ms
7: 384x640 1 animal, 234.0ms
8: 384x640 1 animal, 234.0ms
9: 384x640 1 animal, 234.0ms
10: 384x640 (no detections), 234.0ms
11: 384x640 (no detections), 234.0ms
12: 384x640 (no detections), 234.0ms
13: 384x640 1 animal, 234.0ms
14: 384x640 1 animal, 234.0ms
15: 384x640 1 animal, 234.0ms
Speed: 1.7ms preprocess, 234.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 55%|██████████████████████████████████████████████████████████████████████████▊                                                             | 71/129 [06:13<04:41,  4.86s/it]

0: 384x640 1 animal, 235.4ms
1: 384x640 1 animal, 235.4ms
2: 384x640 1 animal, 235.4ms
3: 384x640 1 animal, 235.4ms
4: 384x640 1 animal, 235.4ms
5: 384x640 1 animal, 235.4ms
6: 384x640 1 animal, 235.4ms
7: 384x640 1 animal, 235.4ms
8: 384x640 1 animal, 235.4ms
9: 384x640 1 animal, 235.4ms
10: 384x640 1 animal, 235.4ms
11: 384x640 1 animal, 235.4ms
12: 384x640 1 animal, 235.4ms
13: 384x640 1 animal, 235.4ms
14: 384x640 1 animal, 235.4ms
15: 384x640 1 animal, 235.4ms
Speed: 1.7ms preprocess, 235.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 56%|███████████████████████████████████████████████████████████████████████████▉                                                            | 72/129 [06:17<04:32,  4.78s/it]

0: 384x640 1 animal, 234.6ms
1: 384x640 1 animal, 234.6ms
2: 384x640 1 animal, 234.6ms
3: 384x640 1 animal, 234.6ms
4: 384x640 1 animal, 234.6ms
5: 384x640 1 animal, 234.6ms
6: 384x640 1 animal, 234.6ms
7: 384x640 1 animal, 234.6ms
8: 384x640 1 animal, 234.6ms
9: 384x640 1 animal, 234.6ms
10: 384x640 1 animal, 234.6ms
11: 384x640 1 animal, 234.6ms
12: 384x640 1 animal, 234.6ms
13: 384x640 1 animal, 234.6ms
14: 384x640 1 animal, 234.6ms
15: 384x640 1 animal, 234.6ms
Speed: 1.7ms preprocess, 234.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 57%|████████████████████████████████████████████████████████████████████████████▉                                                           | 73/129 [06:22<04:23,  4.70s/it]

0: 384x640 1 animal, 235.4ms
1: 384x640 1 animal, 235.4ms
2: 384x640 1 animal, 235.4ms
3: 384x640 2 animals, 235.4ms
4: 384x640 1 animal, 235.4ms
5: 384x640 1 animal, 235.4ms
6: 384x640 1 animal, 235.4ms
7: 384x640 1 animal, 235.4ms
8: 384x640 1 animal, 235.4ms
9: 384x640 1 animal, 235.4ms
10: 384x640 1 animal, 235.4ms
11: 384x640 1 animal, 235.4ms
12: 384x640 1 animal, 235.4ms
13: 384x640 1 animal, 235.4ms
14: 384x640 1 animal, 235.4ms
15: 384x640 1 animal, 235.4ms
Speed: 1.8ms preprocess, 235.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 57%|██████████████████████████████████████████████████████████████████████████████                                                          | 74/129 [06:26<04:15,  4.65s/it]

0: 640x640 1 animal, 400.4ms
1: 640x640 1 animal, 400.4ms
2: 640x640 1 animal, 400.4ms
3: 640x640 1 animal, 400.4ms
4: 640x640 1 animal, 400.4ms
5: 640x640 1 animal, 400.4ms
6: 640x640 (no detections), 400.4ms
7: 640x640 (no detections), 400.4ms
8: 640x640 2 animals, 400.4ms
9: 640x640 1 animal, 400.4ms
10: 640x640 (no detections), 400.4ms
11: 640x640 (no detections), 400.4ms
12: 640x640 (no detections), 400.4ms
13: 640x640 (no detections), 400.4ms
14: 640x640 (no detections), 400.4ms
15: 640x640 (no detections), 400.4ms
Speed: 2.8ms preprocess, 400.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 58%|███████████████████████████████████████████████████████████████████████████████                                                         | 75/129 [06:33<04:48,  5.35s/it]

0: 384x640 1 animal, 237.5ms
1: 384x640 1 animal, 237.5ms
2: 384x640 1 animal, 237.5ms
3: 384x640 1 animal, 237.5ms
4: 384x640 1 animal, 237.5ms
5: 384x640 1 animal, 237.5ms
6: 384x640 1 animal, 237.5ms
7: 384x640 1 animal, 237.5ms
8: 384x640 1 animal, 237.5ms
9: 384x640 1 animal, 237.5ms
10: 384x640 1 animal, 237.5ms
11: 384x640 1 animal, 237.5ms
12: 384x640 1 animal, 237.5ms
13: 384x640 1 animal, 237.5ms
14: 384x640 1 animal, 237.5ms
15: 384x640 1 animal, 237.5ms
Speed: 1.7ms preprocess, 237.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 59%|████████████████████████████████████████████████████████████████████████████████                                                        | 76/129 [06:38<04:31,  5.12s/it]

0: 384x640 (no detections), 236.4ms
1: 384x640 (no detections), 236.4ms
2: 384x640 (no detections), 236.4ms
3: 384x640 (no detections), 236.4ms
4: 384x640 1 animal, 236.4ms
5: 384x640 1 animal, 236.4ms
6: 384x640 1 animal, 236.4ms
7: 384x640 1 animal, 236.4ms
8: 384x640 1 animal, 236.4ms
9: 384x640 1 animal, 236.4ms
10: 384x640 1 animal, 236.4ms
11: 384x640 1 animal, 236.4ms
12: 384x640 1 animal, 236.4ms
13: 384x640 1 animal, 236.4ms
14: 384x640 1 animal, 236.4ms
15: 384x640 1 animal, 236.4ms
Speed: 1.9ms preprocess, 236.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 60%|█████████████████████████████████████████████████████████████████████████████████▏                                                      | 77/129 [06:42<04:17,  4.95s/it]

0: 384x640 1 animal, 235.7ms
1: 384x640 1 animal, 235.7ms
2: 384x640 1 animal, 235.7ms
3: 384x640 1 animal, 235.7ms
4: 384x640 1 animal, 235.7ms
5: 384x640 1 animal, 235.7ms
6: 384x640 1 animal, 235.7ms
7: 384x640 1 animal, 235.7ms
8: 384x640 1 animal, 235.7ms
9: 384x640 1 animal, 235.7ms
10: 384x640 1 animal, 235.7ms
11: 384x640 1 animal, 235.7ms
12: 384x640 1 animal, 235.7ms
13: 384x640 (no detections), 235.7ms
14: 384x640 1 animal, 235.7ms
15: 384x640 (no detections), 235.7ms
Speed: 1.7ms preprocess, 235.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 60%|██████████████████████████████████████████████████████████████████████████████████▏                                                     | 78/129 [06:47<04:05,  4.82s/it]

0: 384x640 (no detections), 235.8ms
1: 384x640 (no detections), 235.8ms
2: 384x640 1 animal, 235.8ms
3: 384x640 1 animal, 235.8ms
4: 384x640 1 animal, 235.8ms
5: 384x640 1 animal, 235.8ms
6: 384x640 1 animal, 235.8ms
7: 384x640 1 animal, 235.8ms
8: 384x640 1 animal, 235.8ms
9: 384x640 1 animal, 235.8ms
10: 384x640 1 animal, 235.8ms
11: 384x640 2 animals, 235.8ms
12: 384x640 1 animal, 235.8ms
13: 384x640 1 animal, 235.8ms
14: 384x640 1 animal, 235.8ms
15: 384x640 (no detections), 235.8ms
Speed: 1.9ms preprocess, 235.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 61%|███████████████████████████████████████████████████████████████████████████████████▎                                                    | 79/129 [06:52<03:56,  4.74s/it]

0: 384x640 (no detections), 234.2ms
1: 384x640 (no detections), 234.2ms
2: 384x640 (no detections), 234.2ms
3: 384x640 1 animal, 234.2ms
4: 384x640 1 animal, 234.2ms
5: 384x640 (no detections), 234.2ms
6: 384x640 1 animal, 234.2ms
7: 384x640 1 animal, 234.2ms
8: 384x640 1 animal, 234.2ms
9: 384x640 1 animal, 234.2ms
10: 384x640 1 animal, 234.2ms
11: 384x640 1 animal, 234.2ms
12: 384x640 1 animal, 234.2ms
13: 384x640 1 animal, 234.2ms
14: 384x640 1 animal, 234.2ms
15: 384x640 (no detections), 234.2ms
Speed: 1.7ms preprocess, 234.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 62%|████████████████████████████████████████████████████████████████████████████████████▎                                                   | 80/129 [06:56<03:48,  4.65s/it]

0: 384x640 1 animal, 232.6ms
1: 384x640 1 animal, 232.6ms
2: 384x640 1 animal, 232.6ms
3: 384x640 1 animal, 232.6ms
4: 384x640 (no detections), 232.6ms
5: 384x640 (no detections), 232.6ms
6: 384x640 (no detections), 232.6ms
7: 384x640 (no detections), 232.6ms
8: 384x640 (no detections), 232.6ms
9: 384x640 (no detections), 232.6ms
10: 384x640 1 animal, 232.6ms
11: 384x640 1 animal, 232.6ms
12: 384x640 1 animal, 232.6ms
13: 384x640 1 animal, 232.6ms
14: 384x640 1 animal, 232.6ms
15: 384x640 1 animal, 232.6ms
Speed: 1.9ms preprocess, 232.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 63%|█████████████████████████████████████████████████████████████████████████████████████▍                                                  | 81/129 [07:00<03:35,  4.49s/it]

0: 384x640 1 animal, 232.2ms
1: 384x640 1 animal, 232.2ms
2: 384x640 1 animal, 232.2ms
3: 384x640 1 animal, 232.2ms
4: 384x640 2 animals, 232.2ms
5: 384x640 1 animal, 232.2ms
6: 384x640 1 animal, 232.2ms
7: 384x640 1 animal, 232.2ms
8: 384x640 1 animal, 232.2ms
9: 384x640 1 animal, 232.2ms
10: 384x640 1 animal, 232.2ms
11: 384x640 1 animal, 232.2ms
12: 384x640 1 animal, 232.2ms
13: 384x640 1 animal, 232.2ms
14: 384x640 1 animal, 232.2ms
15: 384x640 1 animal, 232.2ms
Speed: 1.8ms preprocess, 232.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 64%|██████████████████████████████████████████████████████████████████████████████████████▍                                                 | 82/129 [07:04<03:25,  4.37s/it]

0: 384x640 1 animal, 232.3ms
1: 384x640 1 animal, 232.3ms
2: 384x640 1 animal, 232.3ms
3: 384x640 1 animal, 232.3ms
4: 384x640 1 animal, 232.3ms
5: 384x640 1 animal, 232.3ms
6: 384x640 1 animal, 232.3ms
7: 384x640 1 animal, 232.3ms
8: 384x640 1 animal, 232.3ms
9: 384x640 1 animal, 232.3ms
10: 384x640 1 animal, 232.3ms
11: 384x640 1 animal, 232.3ms
12: 384x640 1 animal, 232.3ms
13: 384x640 1 animal, 232.3ms
14: 384x640 1 animal, 232.3ms
15: 384x640 1 animal, 232.3ms
Speed: 1.7ms preprocess, 232.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 64%|███████████████████████████████████████████████████████████████████████████████████████▌                                                | 83/129 [07:08<03:17,  4.28s/it]

0: 640x640 1 animal, 402.1ms
1: 640x640 1 animal, 402.1ms
2: 640x640 1 animal, 402.1ms
3: 640x640 1 animal, 402.1ms
4: 640x640 1 animal, 402.1ms
5: 640x640 1 animal, 402.1ms
6: 640x640 1 animal, 402.1ms
7: 640x640 1 animal, 402.1ms
8: 640x640 1 animal, 402.1ms
9: 640x640 1 animal, 402.1ms
10: 640x640 1 animal, 402.1ms
11: 640x640 1 animal, 402.1ms
12: 640x640 1 animal, 402.1ms
13: 640x640 1 animal, 402.1ms
14: 640x640 1 animal, 402.1ms
15: 640x640 1 animal, 402.1ms
Speed: 2.6ms preprocess, 402.1ms inference, 0.5ms postprocess per image at shape (16, 3, 640, 640)

 65%|████████████████████████████████████████████████████████████████████████████████████████▌                                               | 84/129 [07:15<03:51,  5.15s/it]

0: 640x640 1 animal, 403.1ms
1: 640x640 1 animal, 403.1ms
2: 640x640 1 animal, 403.1ms
3: 640x640 1 animal, 403.1ms
4: 640x640 1 animal, 403.1ms
5: 640x640 1 animal, 403.1ms
6: 640x640 1 animal, 403.1ms
7: 640x640 1 animal, 403.1ms
8: 640x640 1 animal, 403.1ms
9: 640x640 1 animal, 403.1ms
10: 640x640 1 animal, 403.1ms
11: 640x640 1 animal, 403.1ms
12: 640x640 1 animal, 403.1ms
13: 640x640 1 animal, 403.1ms
14: 640x640 1 animal, 403.1ms
15: 640x640 1 animal, 403.1ms
Speed: 2.6ms preprocess, 403.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 66%|█████████████████████████████████████████████████████████████████████████████████████████▌                                              | 85/129 [07:23<04:12,  5.74s/it]

0: 640x640 1 animal, 398.3ms
1: 640x640 1 animal, 398.3ms
2: 640x640 1 animal, 398.3ms
3: 640x640 1 animal, 398.3ms
4: 640x640 1 animal, 398.3ms
5: 640x640 1 animal, 398.3ms
6: 640x640 1 animal, 398.3ms
7: 640x640 1 animal, 398.3ms
8: 640x640 1 animal, 398.3ms
9: 640x640 1 animal, 398.3ms
10: 640x640 1 animal, 398.3ms
11: 640x640 1 animal, 398.3ms
12: 640x640 1 animal, 398.3ms
13: 640x640 1 animal, 398.3ms
14: 640x640 1 animal, 398.3ms
15: 640x640 1 animal, 398.3ms
Speed: 2.7ms preprocess, 398.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 67%|██████████████████████████████████████████████████████████████████████████████████████████▋                                             | 86/129 [07:29<04:21,  6.09s/it]

0: 384x640 1 animal, 235.5ms
1: 384x640 1 animal, 235.5ms
2: 384x640 1 animal, 235.5ms
3: 384x640 1 animal, 235.5ms
4: 384x640 1 animal, 235.5ms
5: 384x640 1 animal, 235.5ms
6: 384x640 1 animal, 235.5ms
7: 384x640 1 animal, 235.5ms
8: 384x640 1 animal, 235.5ms
9: 384x640 1 animal, 235.5ms
10: 384x640 1 animal, 235.5ms
11: 384x640 1 animal, 235.5ms
12: 384x640 1 animal, 235.5ms
13: 384x640 1 animal, 235.5ms
14: 384x640 (no detections), 235.5ms
15: 384x640 (no detections), 235.5ms
Speed: 1.9ms preprocess, 235.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▋                                            | 87/129 [07:34<03:56,  5.63s/it]

0: 384x640 (no detections), 235.7ms
1: 384x640 1 animal, 235.7ms
2: 384x640 1 animal, 235.7ms
3: 384x640 (no detections), 235.7ms
4: 384x640 (no detections), 235.7ms
5: 384x640 (no detections), 235.7ms
6: 384x640 (no detections), 235.7ms
7: 384x640 (no detections), 235.7ms
8: 384x640 1 animal, 235.7ms
9: 384x640 1 animal, 235.7ms
10: 384x640 1 animal, 235.7ms
11: 384x640 (no detections), 235.7ms
12: 384x640 (no detections), 235.7ms
13: 384x640 (no detections), 235.7ms
14: 384x640 (no detections), 235.7ms
15: 384x640 (no detections), 235.7ms
Speed: 1.8ms preprocess, 235.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 68%|████████████████████████████████████████████████████████████████████████████████████████████▊                                           | 88/129 [07:39<03:38,  5.33s/it]

0: 384x640 (no detections), 233.9ms
1: 384x640 (no detections), 233.9ms
2: 384x640 1 animal, 233.9ms
3: 384x640 1 animal, 233.9ms
4: 384x640 1 animal, 233.9ms
5: 384x640 1 animal, 233.9ms
6: 384x640 1 animal, 233.9ms
7: 384x640 1 animal, 233.9ms
8: 384x640 1 animal, 233.9ms
9: 384x640 1 animal, 233.9ms
10: 384x640 1 animal, 233.9ms
11: 384x640 1 animal, 233.9ms
12: 384x640 1 animal, 233.9ms
13: 384x640 1 animal, 233.9ms
14: 384x640 1 animal, 233.9ms
15: 384x640 1 animal, 233.9ms
Speed: 1.7ms preprocess, 233.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 69%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 89/129 [07:43<03:22,  5.07s/it]

0: 384x640 1 animal, 234.5ms
1: 384x640 1 animal, 234.5ms
2: 384x640 1 animal, 234.5ms
3: 384x640 1 animal, 234.5ms
4: 384x640 1 animal, 234.5ms
5: 384x640 1 animal, 234.5ms
6: 384x640 1 animal, 234.5ms
7: 384x640 1 animal, 234.5ms
8: 384x640 1 animal, 234.5ms
9: 384x640 1 animal, 234.5ms
10: 384x640 1 animal, 234.5ms
11: 384x640 1 animal, 234.5ms
12: 384x640 1 animal, 234.5ms
13: 384x640 1 animal, 234.5ms
14: 384x640 (no detections), 234.5ms
15: 384x640 (no detections), 234.5ms
Speed: 1.8ms preprocess, 234.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 70%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                         | 90/129 [07:48<03:10,  4.89s/it]

0: 384x640 1 animal, 233.7ms
1: 384x640 1 animal, 233.7ms
2: 384x640 1 animal, 233.7ms
3: 384x640 1 animal, 233.7ms
4: 384x640 1 animal, 233.7ms
5: 384x640 1 animal, 233.7ms
6: 384x640 (no detections), 233.7ms
7: 384x640 (no detections), 233.7ms
8: 384x640 (no detections), 233.7ms
9: 384x640 (no detections), 233.7ms
10: 384x640 1 animal, 233.7ms
11: 384x640 1 animal, 233.7ms
12: 384x640 1 animal, 233.7ms
13: 384x640 1 animal, 233.7ms
14: 384x640 1 animal, 233.7ms
15: 384x640 1 animal, 233.7ms
Speed: 1.7ms preprocess, 233.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 71%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 91/129 [07:52<03:00,  4.76s/it]

0: 640x640 1 animal, 395.7ms
1: 640x640 1 animal, 395.7ms
2: 640x640 (no detections), 395.7ms
3: 640x640 (no detections), 395.7ms
4: 640x640 (no detections), 395.7ms
5: 640x640 1 animal, 395.7ms
6: 640x640 1 animal, 395.7ms
7: 640x640 1 animal, 395.7ms
8: 640x640 1 animal, 395.7ms
9: 640x640 1 animal, 395.7ms
10: 640x640 1 animal, 395.7ms
11: 640x640 (no detections), 395.7ms
12: 640x640 (no detections), 395.7ms
13: 640x640 (no detections), 395.7ms
14: 640x640 1 animal, 395.7ms
15: 640x640 1 animal, 395.7ms
Speed: 2.5ms preprocess, 395.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 71%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 92/129 [07:59<03:19,  5.39s/it]

0: 384x640 1 animal, 235.9ms
1: 384x640 1 animal, 235.9ms
2: 384x640 (no detections), 235.9ms
3: 384x640 (no detections), 235.9ms
4: 384x640 (no detections), 235.9ms
5: 384x640 (no detections), 235.9ms
6: 384x640 (no detections), 235.9ms
7: 384x640 (no detections), 235.9ms
8: 384x640 1 animal, 235.9ms
9: 384x640 1 animal, 235.9ms
10: 384x640 (no detections), 235.9ms
11: 384x640 (no detections), 235.9ms
12: 384x640 (no detections), 235.9ms
13: 384x640 (no detections), 235.9ms
14: 384x640 (no detections), 235.9ms
15: 384x640 (no detections), 235.9ms
Speed: 1.7ms preprocess, 235.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████                                      | 93/129 [08:03<03:04,  5.13s/it]

0: 640x640 (no detections), 400.1ms
1: 640x640 (no detections), 400.1ms
2: 640x640 1 animal, 400.1ms
3: 640x640 1 animal, 400.1ms
4: 640x640 1 animal, 400.1ms
5: 640x640 1 animal, 400.1ms
6: 640x640 1 animal, 400.1ms
7: 640x640 (no detections), 400.1ms
8: 640x640 (no detections), 400.1ms
9: 640x640 (no detections), 400.1ms
10: 640x640 (no detections), 400.1ms
11: 640x640 (no detections), 400.1ms
12: 640x640 1 animal, 400.1ms
13: 640x640 1 animal, 400.1ms
14: 640x640 1 animal, 400.1ms
15: 640x640 1 animal, 400.1ms
Speed: 2.8ms preprocess, 400.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████                                     | 94/129 [08:10<03:20,  5.72s/it]

0: 640x640 1 animal, 402.7ms
1: 640x640 1 animal, 402.7ms
2: 640x640 1 animal, 402.7ms
3: 640x640 1 animal, 402.7ms
4: 640x640 1 animal, 402.7ms
5: 640x640 2 animals, 402.7ms
6: 640x640 1 animal, 402.7ms
7: 640x640 1 animal, 402.7ms
8: 640x640 1 animal, 402.7ms
9: 640x640 1 animal, 402.7ms
10: 640x640 1 animal, 402.7ms
11: 640x640 1 animal, 402.7ms
12: 640x640 1 animal, 402.7ms
13: 640x640 1 animal, 402.7ms
14: 640x640 (no detections), 402.7ms
15: 640x640 (no detections), 402.7ms
Speed: 2.6ms preprocess, 402.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 74%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                   | 95/129 [08:18<03:28,  6.13s/it]

0: 640x640 1 animal, 398.6ms
1: 640x640 1 animal, 398.6ms
2: 640x640 1 animal, 398.6ms
3: 640x640 1 animal, 398.6ms
4: 640x640 1 animal, 398.6ms
5: 640x640 1 animal, 398.6ms
6: 640x640 1 animal, 398.6ms
7: 640x640 1 animal, 398.6ms
8: 640x640 1 animal, 398.6ms
9: 640x640 1 animal, 398.6ms
10: 640x640 1 animal, 398.6ms
11: 640x640 1 animal, 398.6ms
12: 640x640 1 animal, 398.6ms
13: 640x640 1 animal, 398.6ms
14: 640x640 1 animal, 398.6ms
15: 640x640 1 animal, 398.6ms
Speed: 2.4ms preprocess, 398.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 96/129 [08:25<03:30,  6.39s/it]

0: 640x640 1 animal, 395.4ms
1: 640x640 1 animal, 395.4ms
2: 640x640 1 animal, 395.4ms
3: 640x640 1 animal, 395.4ms
4: 640x640 1 animal, 395.4ms
5: 640x640 1 animal, 395.4ms
6: 640x640 1 animal, 395.4ms
7: 640x640 1 animal, 395.4ms
8: 640x640 1 animal, 395.4ms
9: 640x640 1 animal, 395.4ms
10: 640x640 1 animal, 395.4ms
11: 640x640 1 animal, 395.4ms
12: 640x640 1 animal, 395.4ms
13: 640x640 1 animal, 395.4ms
14: 640x640 1 animal, 395.4ms
15: 640x640 1 animal, 395.4ms
Speed: 2.4ms preprocess, 395.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 97/129 [08:31<03:28,  6.50s/it]

0: 384x640 1 animal, 233.2ms
1: 384x640 1 animal, 233.2ms
2: 384x640 1 animal, 233.2ms
3: 384x640 1 animal, 233.2ms
4: 384x640 1 animal, 233.2ms
5: 384x640 1 animal, 233.2ms
6: 384x640 1 animal, 233.2ms
7: 384x640 1 animal, 233.2ms
8: 384x640 1 animal, 233.2ms
9: 384x640 1 animal, 233.2ms
10: 384x640 1 animal, 233.2ms
11: 384x640 1 animal, 233.2ms
12: 384x640 1 animal, 233.2ms
13: 384x640 1 animal, 233.2ms
14: 384x640 1 animal, 233.2ms
15: 384x640 1 animal, 233.2ms
Speed: 1.7ms preprocess, 233.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 98/129 [08:36<03:03,  5.91s/it]

0: 640x640 1 animal, 396.1ms
1: 640x640 1 animal, 396.1ms
2: 640x640 1 animal, 396.1ms
3: 640x640 1 animal, 396.1ms
4: 640x640 (no detections), 396.1ms
5: 640x640 1 animal, 396.1ms
6: 640x640 (no detections), 396.1ms
7: 640x640 (no detections), 396.1ms
8: 640x640 (no detections), 396.1ms
9: 640x640 1 animal, 396.1ms
10: 640x640 (no detections), 396.1ms
11: 640x640 1 animal, 396.1ms
12: 640x640 1 animal, 396.1ms
13: 640x640 1 animal, 396.1ms
14: 640x640 1 animal, 396.1ms
15: 640x640 (no detections), 396.1ms
Speed: 2.8ms preprocess, 396.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 99/129 [08:43<03:06,  6.21s/it]

0: 384x640 (no detections), 233.7ms
1: 384x640 (no detections), 233.7ms
2: 384x640 (no detections), 233.7ms
3: 384x640 (no detections), 233.7ms
4: 384x640 (no detections), 233.7ms
5: 384x640 (no detections), 233.7ms
6: 384x640 1 animal, 233.7ms
7: 384x640 1 animal, 233.7ms
8: 384x640 1 animal, 233.7ms
9: 384x640 1 animal, 233.7ms
10: 384x640 1 animal, 233.7ms
11: 384x640 (no detections), 233.7ms
12: 384x640 (no detections), 233.7ms
13: 384x640 (no detections), 233.7ms
14: 384x640 (no detections), 233.7ms
15: 384x640 (no detections), 233.7ms
Speed: 1.7ms preprocess, 233.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 100/129 [08:47<02:46,  5.74s/it]

0: 384x640 1 animal, 232.9ms
1: 384x640 1 animal, 232.9ms
2: 384x640 1 animal, 232.9ms
3: 384x640 1 animal, 232.9ms
4: 384x640 1 animal, 232.9ms
5: 384x640 1 animal, 232.9ms
6: 384x640 1 animal, 232.9ms
7: 384x640 1 animal, 232.9ms
8: 384x640 1 animal, 232.9ms
9: 384x640 1 animal, 232.9ms
10: 384x640 1 animal, 232.9ms
11: 384x640 1 animal, 232.9ms
12: 384x640 1 animal, 232.9ms
13: 384x640 1 animal, 232.9ms
14: 384x640 1 animal, 232.9ms
15: 384x640 1 animal, 232.9ms
Speed: 1.7ms preprocess, 232.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 101/129 [08:52<02:30,  5.36s/it]

0: 640x640 1 animal, 399.7ms
1: 640x640 1 animal, 399.7ms
2: 640x640 1 animal, 399.7ms
3: 640x640 1 animal, 399.7ms
4: 640x640 1 animal, 399.7ms
5: 640x640 1 animal, 399.7ms
6: 640x640 1 animal, 399.7ms
7: 640x640 2 animals, 399.7ms
8: 640x640 1 animal, 399.7ms
9: 640x640 1 animal, 399.7ms
10: 640x640 1 animal, 399.7ms
11: 640x640 1 animal, 399.7ms
12: 640x640 2 animals, 399.7ms
13: 640x640 1 animal, 399.7ms
14: 640x640 1 animal, 399.7ms
15: 640x640 1 animal, 399.7ms
Speed: 2.6ms preprocess, 399.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 102/129 [08:59<02:39,  5.91s/it]

0: 640x640 2 animals, 401.1ms
1: 640x640 2 animals, 401.1ms
2: 640x640 2 animals, 401.1ms
3: 640x640 2 animals, 401.1ms
4: 640x640 2 animals, 401.1ms
5: 640x640 2 animals, 401.1ms
6: 640x640 2 animals, 401.1ms
7: 640x640 2 animals, 401.1ms
8: 640x640 1 animal, 401.1ms
9: 640x640 1 animal, 401.1ms
10: 640x640 1 animal, 401.1ms
11: 640x640 1 animal, 401.1ms
12: 640x640 1 animal, 401.1ms
13: 640x640 1 animal, 401.1ms
14: 640x640 1 animal, 401.1ms
15: 640x640 1 animal, 401.1ms
Speed: 2.7ms preprocess, 401.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 103/129 [09:06<02:42,  6.25s/it]

0: 384x640 1 animal, 234.2ms
1: 384x640 1 animal, 234.2ms
2: 384x640 1 animal, 234.2ms
3: 384x640 1 animal, 234.2ms
4: 384x640 2 animals, 234.2ms
5: 384x640 1 animal, 234.2ms
6: 384x640 1 animal, 234.2ms
7: 384x640 (no detections), 234.2ms
8: 384x640 (no detections), 234.2ms
9: 384x640 (no detections), 234.2ms
10: 384x640 (no detections), 234.2ms
11: 384x640 (no detections), 234.2ms
12: 384x640 1 animal, 234.2ms
13: 384x640 1 animal, 234.2ms
14: 384x640 1 animal, 234.2ms
15: 384x640 1 animal, 234.2ms
Speed: 1.9ms preprocess, 234.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 104/129 [09:11<02:23,  5.73s/it]

0: 384x640 1 animal, 233.7ms
1: 384x640 1 animal, 233.7ms
2: 384x640 1 animal, 233.7ms
3: 384x640 1 animal, 233.7ms
4: 384x640 1 animal, 233.7ms
5: 384x640 1 animal, 233.7ms
6: 384x640 1 animal, 233.7ms
7: 384x640 1 animal, 233.7ms
8: 384x640 1 animal, 233.7ms
9: 384x640 1 animal, 233.7ms
10: 384x640 1 animal, 233.7ms
11: 384x640 1 animal, 233.7ms
12: 384x640 1 animal, 233.7ms
13: 384x640 1 animal, 233.7ms
14: 384x640 1 animal, 233.7ms
15: 384x640 1 animal, 233.7ms
Speed: 1.7ms preprocess, 233.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 105/129 [09:15<02:08,  5.35s/it]

0: 384x640 1 animal, 233.9ms
1: 384x640 1 animal, 233.9ms
2: 384x640 1 animal, 233.9ms
3: 384x640 1 animal, 233.9ms
4: 384x640 1 animal, 233.9ms
5: 384x640 1 animal, 233.9ms
6: 384x640 (no detections), 233.9ms
7: 384x640 (no detections), 233.9ms
8: 384x640 (no detections), 233.9ms
9: 384x640 (no detections), 233.9ms
10: 384x640 1 animal, 233.9ms
11: 384x640 1 animal, 233.9ms
12: 384x640 1 animal, 233.9ms
13: 384x640 1 animal, 233.9ms
14: 384x640 1 animal, 233.9ms
15: 384x640 1 animal, 233.9ms
Speed: 1.7ms preprocess, 233.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 106/129 [09:20<01:56,  5.08s/it]

0: 384x640 1 animal, 232.1ms
1: 384x640 1 animal, 232.1ms
2: 384x640 1 animal, 232.1ms
3: 384x640 1 animal, 232.1ms
4: 384x640 1 animal, 232.1ms
5: 384x640 (no detections), 232.1ms
6: 384x640 (no detections), 232.1ms
7: 384x640 (no detections), 232.1ms
8: 384x640 (no detections), 232.1ms
9: 384x640 (no detections), 232.1ms
10: 384x640 (no detections), 232.1ms
11: 384x640 (no detections), 232.1ms
12: 384x640 (no detections), 232.1ms
13: 384x640 (no detections), 232.1ms
14: 384x640 1 animal, 232.1ms
15: 384x640 1 animal, 232.1ms
Speed: 1.9ms preprocess, 232.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 107/129 [09:24<01:48,  4.94s/it]

0: 384x640 1 animal, 225.8ms
1: 384x640 1 animal, 225.8ms
2: 384x640 1 animal, 225.8ms
3: 384x640 1 animal, 225.8ms
4: 384x640 1 animal, 225.8ms
5: 384x640 1 animal, 225.8ms
6: 384x640 1 animal, 225.8ms
7: 384x640 1 animal, 225.8ms
8: 384x640 1 animal, 225.8ms
9: 384x640 1 animal, 225.8ms
10: 384x640 1 animal, 225.8ms
11: 384x640 1 animal, 225.8ms
12: 384x640 (no detections), 225.8ms
13: 384x640 (no detections), 225.8ms
14: 384x640 1 animal, 225.8ms
15: 384x640 (no detections), 225.8ms
Speed: 1.7ms preprocess, 225.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 108/129 [09:29<01:40,  4.77s/it]

0: 384x640 (no detections), 228.1ms
1: 384x640 (no detections), 228.1ms
2: 384x640 1 animal, 228.1ms
3: 384x640 1 animal, 228.1ms
4: 384x640 1 animal, 228.1ms
5: 384x640 1 animal, 228.1ms
6: 384x640 1 animal, 228.1ms
7: 384x640 1 animal, 228.1ms
8: 384x640 1 animal, 228.1ms
9: 384x640 1 animal, 228.1ms
10: 384x640 1 animal, 228.1ms
11: 384x640 1 animal, 228.1ms
12: 384x640 1 animal, 228.1ms
13: 384x640 1 animal, 228.1ms
14: 384x640 1 animal, 228.1ms
15: 384x640 (no detections), 228.1ms
Speed: 1.7ms preprocess, 228.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 109/129 [09:33<01:32,  4.65s/it]

0: 384x640 1 animal, 228.0ms
1: 384x640 1 animal, 228.0ms
2: 384x640 1 animal, 228.0ms
3: 384x640 1 animal, 228.0ms
4: 384x640 1 animal, 228.0ms
5: 384x640 1 animal, 228.0ms
6: 384x640 1 animal, 228.0ms
7: 384x640 1 animal, 228.0ms
8: 384x640 1 animal, 228.0ms
9: 384x640 1 animal, 228.0ms
10: 384x640 1 animal, 228.0ms
11: 384x640 1 animal, 228.0ms
12: 384x640 1 animal, 228.0ms
13: 384x640 1 animal, 228.0ms
14: 384x640 1 animal, 228.0ms
15: 384x640 1 animal, 228.0ms
Speed: 1.7ms preprocess, 228.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 110/129 [09:37<01:27,  4.60s/it]

0: 384x640 1 animal, 231.6ms
1: 384x640 1 animal, 231.6ms
2: 384x640 1 animal, 231.6ms
3: 384x640 1 animal, 231.6ms
4: 384x640 1 animal, 231.6ms
5: 384x640 1 animal, 231.6ms
6: 384x640 1 animal, 231.6ms
7: 384x640 1 animal, 231.6ms
8: 384x640 1 animal, 231.6ms
9: 384x640 1 animal, 231.6ms
10: 384x640 1 animal, 231.6ms
11: 384x640 1 animal, 231.6ms
12: 384x640 1 animal, 231.6ms
13: 384x640 1 animal, 231.6ms
14: 384x640 1 animal, 231.6ms
15: 384x640 1 animal, 231.6ms
Speed: 2.0ms preprocess, 231.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 111/129 [09:42<01:22,  4.60s/it]

0: 384x640 1 animal, 232.5ms
1: 384x640 1 animal, 232.5ms
2: 384x640 1 animal, 232.5ms
3: 384x640 1 animal, 232.5ms
4: 384x640 1 animal, 232.5ms
5: 384x640 1 animal, 232.5ms
6: 384x640 1 animal, 232.5ms
7: 384x640 (no detections), 232.5ms
8: 384x640 (no detections), 232.5ms
9: 384x640 (no detections), 232.5ms
10: 384x640 (no detections), 232.5ms
11: 384x640 (no detections), 232.5ms
12: 384x640 (no detections), 232.5ms
13: 384x640 (no detections), 232.5ms
14: 384x640 1 animal, 232.5ms
15: 384x640 (no detections), 232.5ms
Speed: 1.8ms preprocess, 232.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 112/129 [09:47<01:18,  4.61s/it]

0: 384x640 (no detections), 234.7ms
1: 384x640 (no detections), 234.7ms
2: 384x640 (no detections), 234.7ms
3: 384x640 (no detections), 234.7ms
4: 384x640 (no detections), 234.7ms
5: 384x640 (no detections), 234.7ms
6: 384x640 (no detections), 234.7ms
7: 384x640 (no detections), 234.7ms
8: 384x640 1 animal, 234.7ms
9: 384x640 1 animal, 234.7ms
10: 384x640 1 animal, 234.7ms
11: 384x640 1 animal, 234.7ms
12: 384x640 1 animal, 234.7ms
13: 384x640 1 animal, 234.7ms
14: 384x640 1 animal, 234.7ms
15: 384x640 2 animals, 234.7ms
Speed: 1.7ms preprocess, 234.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 113/129 [09:51<01:14,  4.63s/it]

0: 384x640 1 animal, 229.1ms
1: 384x640 1 animal, 229.1ms
2: 384x640 1 animal, 229.1ms
3: 384x640 1 animal, 229.1ms
4: 384x640 1 animal, 229.1ms
5: 384x640 1 animal, 229.1ms
6: 384x640 1 animal, 229.1ms
7: 384x640 1 animal, 229.1ms
8: 384x640 1 animal, 229.1ms
9: 384x640 1 animal, 229.1ms
10: 384x640 1 animal, 229.1ms
11: 384x640 1 animal, 229.1ms
12: 384x640 1 animal, 229.1ms
13: 384x640 1 animal, 229.1ms
14: 384x640 1 animal, 229.1ms
15: 384x640 1 animal, 229.1ms
Speed: 1.8ms preprocess, 229.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 114/129 [09:56<01:08,  4.57s/it]

0: 384x640 1 animal, 233.6ms
1: 384x640 1 animal, 233.6ms
2: 384x640 (no detections), 233.6ms
3: 384x640 (no detections), 233.6ms
4: 384x640 (no detections), 233.6ms
5: 384x640 (no detections), 233.6ms
6: 384x640 (no detections), 233.6ms
7: 384x640 (no detections), 233.6ms
8: 384x640 (no detections), 233.6ms
9: 384x640 (no detections), 233.6ms
10: 384x640 1 animal, 233.6ms
11: 384x640 1 animal, 233.6ms
12: 384x640 1 animal, 233.6ms
13: 384x640 1 animal, 233.6ms
14: 384x640 1 animal, 233.6ms
15: 384x640 1 animal, 233.6ms
Speed: 1.8ms preprocess, 233.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎              | 115/129 [10:00<01:03,  4.54s/it]

0: 384x640 1 animal, 228.4ms
1: 384x640 1 animal, 228.4ms
2: 384x640 1 animal, 228.4ms
3: 384x640 1 animal, 228.4ms
4: 384x640 1 animal, 228.4ms
5: 384x640 2 animals, 228.4ms
6: 384x640 1 animal, 228.4ms
7: 384x640 2 animals, 228.4ms
8: 384x640 2 animals, 228.4ms
9: 384x640 2 animals, 228.4ms
10: 384x640 1 animal, 228.4ms
11: 384x640 1 animal, 228.4ms
12: 384x640 2 animals, 228.4ms
13: 384x640 1 animal, 228.4ms
14: 384x640 1 animal, 228.4ms
15: 384x640 1 animal, 228.4ms
Speed: 1.7ms preprocess, 228.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 116/129 [10:05<00:58,  4.49s/it]

0: 384x640 1 animal, 227.6ms
1: 384x640 1 animal, 227.6ms
2: 384x640 1 animal, 227.6ms
3: 384x640 1 animal, 227.6ms
4: 384x640 (no detections), 227.6ms
5: 384x640 (no detections), 227.6ms
6: 384x640 (no detections), 227.6ms
7: 384x640 1 animal, 227.6ms
8: 384x640 (no detections), 227.6ms
9: 384x640 1 animal, 227.6ms
10: 384x640 (no detections), 227.6ms
11: 384x640 (no detections), 227.6ms
12: 384x640 (no detections), 227.6ms
13: 384x640 1 animal, 227.6ms
14: 384x640 1 animal, 227.6ms
15: 384x640 1 animal, 227.6ms
Speed: 1.7ms preprocess, 227.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 117/129 [10:09<00:53,  4.46s/it]

0: 384x640 2 animals, 228.9ms
1: 384x640 1 animal, 228.9ms
2: 384x640 1 animal, 228.9ms
3: 384x640 1 animal, 228.9ms
4: 384x640 1 animal, 228.9ms
5: 384x640 1 animal, 228.9ms
6: 384x640 (no detections), 228.9ms
7: 384x640 1 animal, 228.9ms
8: 384x640 1 animal, 228.9ms
9: 384x640 1 animal, 228.9ms
10: 384x640 1 animal, 228.9ms
11: 384x640 1 animal, 228.9ms
12: 384x640 1 animal, 228.9ms
13: 384x640 1 animal, 228.9ms
14: 384x640 1 animal, 228.9ms
15: 384x640 (no detections), 228.9ms
Speed: 2.0ms preprocess, 228.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 118/129 [10:13<00:49,  4.46s/it]

0: 384x640 (no detections), 234.9ms
1: 384x640 (no detections), 234.9ms
2: 384x640 1 animal, 234.9ms
3: 384x640 1 animal, 234.9ms
4: 384x640 1 animal, 234.9ms
5: 384x640 1 animal, 234.9ms
6: 384x640 1 animal, 234.9ms
7: 384x640 1 animal, 234.9ms
8: 384x640 1 animal, 234.9ms
9: 384x640 1 animal, 234.9ms
10: 384x640 1 animal, 234.9ms
11: 384x640 1 animal, 234.9ms
12: 384x640 1 animal, 234.9ms
13: 384x640 1 animal, 234.9ms
14: 384x640 1 animal, 234.9ms
15: 384x640 1 animal, 234.9ms
Speed: 1.7ms preprocess, 234.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 119/129 [10:18<00:45,  4.52s/it]

0: 384x640 1 animal, 233.2ms
1: 384x640 1 animal, 233.2ms
2: 384x640 1 animal, 233.2ms
3: 384x640 1 animal, 233.2ms
4: 384x640 1 animal, 233.2ms
5: 384x640 1 animal, 233.2ms
6: 384x640 1 animal, 233.2ms
7: 384x640 1 animal, 233.2ms
8: 384x640 1 animal, 233.2ms
9: 384x640 1 animal, 233.2ms
10: 384x640 1 animal, 233.2ms
11: 384x640 1 animal, 233.2ms
12: 384x640 1 animal, 233.2ms
13: 384x640 1 animal, 233.2ms
14: 384x640 1 animal, 233.2ms
15: 384x640 1 animal, 233.2ms
Speed: 1.7ms preprocess, 233.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 120/129 [10:23<00:40,  4.54s/it]

0: 384x640 1 animal, 230.9ms
1: 384x640 1 animal, 230.9ms
2: 384x640 1 animal, 230.9ms
3: 384x640 2 animals, 230.9ms
4: 384x640 1 animal, 230.9ms
5: 384x640 2 animals, 230.9ms
6: 384x640 2 animals, 230.9ms
7: 384x640 (no detections), 230.9ms
8: 384x640 1 animal, 230.9ms
9: 384x640 (no detections), 230.9ms
10: 384x640 1 animal, 230.9ms
11: 384x640 1 animal, 230.9ms
12: 384x640 1 animal, 230.9ms
13: 384x640 1 animal, 230.9ms
14: 384x640 1 animal, 230.9ms
15: 384x640 1 animal, 230.9ms
Speed: 1.8ms preprocess, 230.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 121/129 [10:27<00:35,  4.50s/it]

0: 384x640 1 animal, 230.8ms
1: 384x640 1 animal, 230.8ms
2: 384x640 2 animals, 230.8ms
3: 384x640 1 animal, 230.8ms
4: 384x640 1 animal, 230.8ms
5: 384x640 1 animal, 230.8ms
6: 384x640 2 animals, 230.8ms
7: 384x640 1 animal, 230.8ms
8: 384x640 1 animal, 230.8ms
9: 384x640 1 animal, 230.8ms
10: 384x640 2 animals, 230.8ms
11: 384x640 1 animal, 230.8ms
12: 384x640 1 animal, 230.8ms
13: 384x640 (no detections), 230.8ms
14: 384x640 1 animal, 230.8ms
15: 384x640 (no detections), 230.8ms
Speed: 1.8ms preprocess, 230.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 122/129 [10:32<00:31,  4.52s/it]

0: 384x640 1 animal, 231.0ms
1: 384x640 1 animal, 231.0ms
2: 384x640 (no detections), 231.0ms
3: 384x640 (no detections), 231.0ms
4: 384x640 (no detections), 231.0ms
5: 384x640 (no detections), 231.0ms
6: 384x640 (no detections), 231.0ms
7: 384x640 (no detections), 231.0ms
8: 384x640 1 animal, 231.0ms
9: 384x640 1 animal, 231.0ms
10: 384x640 1 animal, 231.0ms
11: 384x640 1 animal, 231.0ms
12: 384x640 1 animal, 231.0ms
13: 384x640 (no detections), 231.0ms
14: 384x640 (no detections), 231.0ms
15: 384x640 (no detections), 231.0ms
Speed: 1.7ms preprocess, 231.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 123/129 [10:36<00:27,  4.55s/it]

0: 384x640 (no detections), 229.5ms
1: 384x640 (no detections), 229.5ms
2: 384x640 1 animal, 229.5ms
3: 384x640 2 animals, 229.5ms
4: 384x640 1 animal, 229.5ms
5: 384x640 1 animal, 229.5ms
6: 384x640 1 animal, 229.5ms
7: 384x640 1 animal, 229.5ms
8: 384x640 (no detections), 229.5ms
9: 384x640 1 animal, 229.5ms
10: 384x640 (no detections), 229.5ms
11: 384x640 (no detections), 229.5ms
12: 384x640 1 animal, 229.5ms
13: 384x640 1 animal, 229.5ms
14: 384x640 (no detections), 229.5ms
15: 384x640 (no detections), 229.5ms
Speed: 1.9ms preprocess, 229.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 124/129 [10:41<00:22,  4.55s/it]

0: 384x640 (no detections), 225.1ms
1: 384x640 (no detections), 225.1ms
2: 384x640 (no detections), 225.1ms
3: 384x640 (no detections), 225.1ms
4: 384x640 (no detections), 225.1ms
5: 384x640 (no detections), 225.1ms
6: 384x640 1 animal, 225.1ms
7: 384x640 1 animal, 225.1ms
8: 384x640 (no detections), 225.1ms
9: 384x640 (no detections), 225.1ms
10: 384x640 (no detections), 225.1ms
11: 384x640 (no detections), 225.1ms
12: 384x640 (no detections), 225.1ms
13: 384x640 (no detections), 225.1ms
14: 384x640 (no detections), 225.1ms
15: 384x640 (no detections), 225.1ms
Speed: 1.8ms preprocess, 225.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 125/129 [10:45<00:17,  4.47s/it]

0: 384x640 1 animal, 236.5ms
1: 384x640 1 animal, 236.5ms
2: 384x640 1 animal, 236.5ms
3: 384x640 1 animal, 236.5ms
4: 384x640 1 animal, 236.5ms
5: 384x640 1 animal, 236.5ms
6: 384x640 1 animal, 236.5ms
7: 384x640 1 animal, 236.5ms
8: 384x640 2 animals, 236.5ms
9: 384x640 1 animal, 236.5ms
10: 384x640 1 animal, 236.5ms
11: 384x640 1 animal, 236.5ms
12: 384x640 1 animal, 236.5ms
13: 384x640 1 animal, 236.5ms
14: 384x640 1 animal, 236.5ms
15: 384x640 1 animal, 236.5ms
Speed: 1.8ms preprocess, 236.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 126/129 [10:50<00:13,  4.54s/it]

0: 640x640 1 animal, 395.3ms
1: 640x640 1 animal, 395.3ms
2: 640x640 1 animal, 395.3ms
3: 640x640 1 animal, 395.3ms
4: 640x640 1 animal, 395.3ms
5: 640x640 1 animal, 395.3ms
6: 640x640 1 animal, 395.3ms
7: 640x640 1 animal, 395.3ms
8: 640x640 1 animal, 395.3ms
9: 640x640 1 animal, 395.3ms
10: 640x640 1 animal, 395.3ms
11: 640x640 1 animal, 395.3ms
12: 640x640 1 animal, 395.3ms
13: 640x640 1 animal, 395.3ms
14: 640x640 1 animal, 395.3ms
15: 640x640 1 animal, 395.3ms
Speed: 2.3ms preprocess, 395.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 127/129 [10:57<00:10,  5.24s/it]

0: 384x640 1 animal, 231.3ms
1: 384x640 1 animal, 231.3ms
2: 384x640 1 animal, 231.3ms
3: 384x640 1 animal, 231.3ms
4: 384x640 1 animal, 231.3ms
5: 384x640 1 animal, 231.3ms
6: 384x640 1 animal, 231.3ms
7: 384x640 1 animal, 231.3ms
8: 384x640 1 animal, 231.3ms
9: 384x640 1 animal, 231.3ms
10: 384x640 1 animal, 231.3ms
11: 384x640 1 animal, 231.3ms
12: 384x640 1 animal, 231.3ms
13: 384x640 1 animal, 231.3ms
14: 384x640 1 animal, 231.3ms
15: 384x640 1 animal, 231.3ms
Speed: 1.3ms preprocess, 231.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 128/129 [11:01<00:04,  4.89s/it]

0: 384x640 1 animal, 232.1ms
1: 384x640 1 animal, 232.1ms
2: 384x640 1 animal, 232.1ms
3: 384x640 (no detections), 232.1ms
4: 384x640 (no detections), 232.1ms
5: 384x640 (no detections), 232.1ms
6: 384x640 (no detections), 232.1ms
7: 384x640 (no detections), 232.1ms
8: 384x640 (no detections), 232.1ms
9: 384x640 (no detections), 232.1ms
10: 384x640 (no detections), 232.1ms
11: 384x640 (no detections), 232.1ms
Speed: 1.2ms preprocess, 232.1ms inference, 0.3ms postprocess per image at shape (12, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 129/129 [11:04<00:00,  5.15s/it]

Detecting images from REPTILES_extracted

  0%|                                                                                                                                                   | 0/2 [00:00<?, ?it/s]

0: 640x640 (no detections), 401.4ms
1: 640x640 (no detections), 401.4ms
2: 640x640 (no detections), 401.4ms
3: 640x640 (no detections), 401.4ms
4: 640x640 (no detections), 401.4ms
5: 640x640 (no detections), 401.4ms
6: 640x640 (no detections), 401.4ms
7: 640x640 (no detections), 401.4ms
8: 640x640 (no detections), 401.4ms
9: 640x640 (no detections), 401.4ms
10: 640x640 (no detections), 401.4ms
11: 640x640 1 animal, 401.4ms
12: 640x640 (no detections), 401.4ms
13: 640x640 (no detections), 401.4ms
14: 640x640 (no detections), 401.4ms
15: 640x640 (no detections), 401.4ms
Speed: 2.6ms preprocess, 401.4ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 50%|█████████████████████████████████████████████████████████████████████▌                                                                     | 1/2 [00:07<00:07,  7.23s/it]

0: 384x640 (no detections), 236.4ms
1: 384x640 (no detections), 236.4ms
2: 384x640 (no detections), 236.4ms
3: 384x640 1 animal, 236.4ms
4: 384x640 (no detections), 236.4ms
5: 384x640 (no detections), 236.4ms
6: 384x640 (no detections), 236.4ms
7: 384x640 (no detections), 236.4ms
8: 384x640 (no detections), 236.4ms
9: 384x640 (no detections), 236.4ms
10: 384x640 (no detections), 236.4ms
11: 384x640 (no detections), 236.4ms
12: 384x640 (no detections), 236.4ms
13: 384x640 (no detections), 236.4ms
Speed: 1.8ms preprocess, 236.4ms inference, 0.2ms postprocess per image at shape (14, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.46s/it]

Detecting images from BASSSEISCUS_ASTUTUS_extracted

  0%|                                                                                                                                                   | 0/4 [00:00<?, ?it/s]

0: 640x640 1 animal, 396.2ms
1: 640x640 1 animal, 396.2ms
2: 640x640 1 animal, 396.2ms
3: 640x640 (no detections), 396.2ms
4: 640x640 (no detections), 396.2ms
5: 640x640 (no detections), 396.2ms
6: 640x640 (no detections), 396.2ms
7: 640x640 (no detections), 396.2ms
8: 640x640 (no detections), 396.2ms
9: 640x640 (no detections), 396.2ms
10: 640x640 (no detections), 396.2ms
11: 640x640 1 animal, 396.2ms
12: 640x640 1 animal, 396.2ms
13: 640x640 1 animal, 396.2ms
14: 640x640 1 animal, 396.2ms
15: 640x640 1 animal, 396.2ms
Speed: 2.9ms preprocess, 396.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 25%|██████████████████████████████████▊                                                                                                        | 1/4 [00:06<00:20,  6.89s/it]

0: 640x640 2 animals, 398.6ms
1: 640x640 1 animal, 398.6ms
2: 640x640 1 animal, 398.6ms
3: 640x640 1 animal, 398.6ms
4: 640x640 1 animal, 398.6ms
5: 640x640 1 animal, 398.6ms
6: 640x640 1 animal, 398.6ms
7: 640x640 (no detections), 398.6ms
8: 640x640 (no detections), 398.6ms
9: 640x640 (no detections), 398.6ms
10: 640x640 (no detections), 398.6ms
11: 640x640 (no detections), 398.6ms
12: 640x640 (no detections), 398.6ms
13: 640x640 (no detections), 398.6ms
14: 640x640 1 animal, 398.6ms
15: 640x640 1 animal, 398.6ms
Speed: 2.5ms preprocess, 398.6ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 50%|█████████████████████████████████████████████████████████████████████▌                                                                     | 2/4 [00:13<00:13,  6.89s/it]

0: 640x640 1 animal, 404.8ms
1: 640x640 1 animal, 404.8ms
2: 640x640 1 animal, 404.8ms
3: 640x640 1 animal, 404.8ms
4: 640x640 1 animal, 404.8ms
5: 640x640 1 animal, 404.8ms
6: 640x640 1 animal, 404.8ms
7: 640x640 1 animal, 404.8ms
8: 640x640 1 animal, 404.8ms
9: 640x640 1 animal, 404.8ms
10: 640x640 1 animal, 404.8ms
11: 640x640 1 animal, 404.8ms
12: 640x640 (no detections), 404.8ms
13: 640x640 (no detections), 404.8ms
14: 640x640 (no detections), 404.8ms
15: 640x640 (no detections), 404.8ms
Speed: 2.7ms preprocess, 404.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 3/4 [00:20<00:06,  6.97s/it]

0: 384x640 1 animal, 199.3ms
1: 384x640 (no detections), 199.3ms
Speed: 1.7ms preprocess, 199.3ms inference, 0.5ms postprocess per image at shape (2, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:21<00:00,  5.34s/it]

Detecting images from SPILOGALE_GRACILIS_2022_extracted

  0%|                                                                                                                                                   | 0/4 [00:00<?, ?it/s]

0: 640x640 1 animal, 399.4ms
1: 640x640 1 animal, 399.4ms
2: 640x640 1 animal, 399.4ms
3: 640x640 1 animal, 399.4ms
4: 640x640 (no detections), 399.4ms
5: 640x640 (no detections), 399.4ms
6: 640x640 (no detections), 399.4ms
7: 640x640 (no detections), 399.4ms
8: 640x640 (no detections), 399.4ms
9: 640x640 (no detections), 399.4ms
10: 640x640 1 animal, 399.4ms
11: 640x640 1 animal, 399.4ms
12: 640x640 1 animal, 399.4ms
13: 640x640 (no detections), 399.4ms
14: 640x640 (no detections), 399.4ms
15: 640x640 (no detections), 399.4ms
Speed: 2.6ms preprocess, 399.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 25%|██████████████████████████████████▊                                                                                                        | 1/4 [00:06<00:20,  6.96s/it]

0: 384x640 (no detections), 236.2ms
1: 384x640 (no detections), 236.2ms
2: 384x640 (no detections), 236.2ms
3: 384x640 (no detections), 236.2ms
4: 384x640 1 animal, 236.2ms
5: 384x640 1 animal, 236.2ms
6: 384x640 1 animal, 236.2ms
7: 384x640 1 animal, 236.2ms
8: 384x640 1 animal, 236.2ms
9: 384x640 1 animal, 236.2ms
10: 384x640 (no detections), 236.2ms
11: 384x640 (no detections), 236.2ms
12: 384x640 (no detections), 236.2ms
13: 384x640 1 animal, 236.2ms
14: 384x640 1 animal, 236.2ms
15: 384x640 1 animal, 236.2ms
Speed: 1.8ms preprocess, 236.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 50%|█████████████████████████████████████████████████████████████████████▌                                                                     | 2/4 [00:11<00:11,  5.55s/it]

0: 384x640 (no detections), 236.6ms
1: 384x640 (no detections), 236.6ms
2: 384x640 (no detections), 236.6ms
3: 384x640 (no detections), 236.6ms
4: 384x640 (no detections), 236.6ms
5: 384x640 (no detections), 236.6ms
6: 384x640 (no detections), 236.6ms
7: 384x640 (no detections), 236.6ms
8: 384x640 1 animal, 236.6ms
9: 384x640 1 animal, 236.6ms
10: 384x640 (no detections), 236.6ms
11: 384x640 1 animal, 236.6ms
12: 384x640 (no detections), 236.6ms
13: 384x640 (no detections), 236.6ms
14: 384x640 (no detections), 236.6ms
15: 384x640 (no detections), 236.6ms
Speed: 2.0ms preprocess, 236.6ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 3/4 [00:16<00:05,  5.08s/it]

0: 384x640 (no detections), 191.1ms
1: 384x640 1 animal, 191.1ms
Speed: 1.7ms preprocess, 191.1ms inference, 0.5ms postprocess per image at shape (2, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:16<00:00,  4.13s/it]

Detecting images from LEOPARDU_wiedii_extracted

it [00:00, ?it/s]

Detecting images from PECARI_TAJACU_2022_extracted

  0%|                                                                                                                                                  | 0/68 [00:00<?, ?it/s]

0: 640x640 (no detections), 396.8ms
1: 640x640 1 animal, 396.8ms
2: 640x640 1 animal, 396.8ms
3: 640x640 1 animal, 396.8ms
4: 640x640 1 animal, 396.8ms
5: 640x640 1 animal, 396.8ms
6: 640x640 1 animal, 396.8ms
7: 640x640 1 animal, 396.8ms
8: 640x640 1 animal, 396.8ms
9: 640x640 1 animal, 396.8ms
10: 640x640 1 animal, 396.8ms
11: 640x640 1 animal, 396.8ms
12: 640x640 1 animal, 396.8ms
13: 640x640 1 animal, 396.8ms
14: 640x640 1 animal, 396.8ms
15: 640x640 1 animal, 396.8ms
Speed: 2.5ms preprocess, 396.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  1%|██                                                                                                                                        | 1/68 [00:06<07:40,  6.88s/it]

0: 640x640 (no detections), 397.5ms
1: 640x640 (no detections), 397.5ms
2: 640x640 (no detections), 397.5ms
3: 640x640 (no detections), 397.5ms
4: 640x640 3 animals, 397.5ms
5: 640x640 2 animals, 397.5ms
6: 640x640 2 animals, 397.5ms
7: 640x640 2 animals, 397.5ms
8: 640x640 1 animal, 397.5ms
9: 640x640 1 animal, 397.5ms
10: 640x640 1 animal, 397.5ms
11: 640x640 1 animal, 397.5ms
12: 640x640 1 animal, 397.5ms
13: 640x640 1 animal, 397.5ms
14: 640x640 (no detections), 397.5ms
15: 640x640 1 animal, 397.5ms
Speed: 2.4ms preprocess, 397.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  3%|████                                                                                                                                      | 2/68 [00:13<07:34,  6.88s/it]

0: 384x640 2 animals, 235.4ms
1: 384x640 2 animals, 235.4ms
2: 384x640 1 animal, 235.4ms
3: 384x640 1 animal, 235.4ms
4: 384x640 1 animal, 235.4ms
5: 384x640 1 animal, 235.4ms
6: 384x640 2 animals, 235.4ms
7: 384x640 2 animals, 235.4ms
8: 384x640 2 animals, 235.4ms
9: 384x640 2 animals, 235.4ms
10: 384x640 2 animals, 235.4ms
11: 384x640 4 animals, 235.4ms
12: 384x640 3 animals, 235.4ms
13: 384x640 1 animal, 235.4ms
14: 384x640 2 animals, 235.4ms
15: 384x640 4 animals, 235.4ms
Speed: 1.7ms preprocess, 235.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  4%|██████                                                                                                                                    | 3/68 [00:18<06:16,  5.79s/it]

0: 384x640 5 animals, 239.5ms
1: 384x640 5 animals, 239.5ms
2: 384x640 (no detections), 239.5ms
3: 384x640 1 animal, 239.5ms
4: 384x640 1 animal, 239.5ms
5: 384x640 1 animal, 239.5ms
6: 384x640 1 animal, 239.5ms
7: 384x640 1 animal, 239.5ms
8: 384x640 1 animal, 239.5ms
9: 384x640 1 animal, 239.5ms
10: 384x640 1 animal, 239.5ms
11: 384x640 1 animal, 239.5ms
12: 384x640 1 animal, 239.5ms
13: 384x640 1 animal, 239.5ms
14: 384x640 1 animal, 239.5ms
15: 384x640 1 animal, 239.5ms
Speed: 1.7ms preprocess, 239.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  6%|████████                                                                                                                                  | 4/68 [00:22<05:39,  5.30s/it]

0: 384x640 1 animal, 239.4ms
1: 384x640 1 animal, 239.4ms
2: 384x640 1 animal, 239.4ms
3: 384x640 1 animal, 239.4ms
4: 384x640 1 animal, 239.4ms
5: 384x640 1 animal, 239.4ms
6: 384x640 1 animal, 239.4ms
7: 384x640 1 animal, 239.4ms
8: 384x640 1 animal, 239.4ms
9: 384x640 1 animal, 239.4ms
10: 384x640 1 animal, 239.4ms
11: 384x640 1 animal, 239.4ms
12: 384x640 1 animal, 239.4ms
13: 384x640 1 animal, 239.4ms
14: 384x640 1 animal, 239.4ms
15: 384x640 1 animal, 239.4ms
Speed: 1.8ms preprocess, 239.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  7%|██████████▏                                                                                                                               | 5/68 [00:27<05:17,  5.03s/it]

0: 384x640 1 animal, 238.5ms
1: 384x640 1 animal, 238.5ms
2: 384x640 1 animal, 238.5ms
3: 384x640 1 animal, 238.5ms
4: 384x640 1 animal, 238.5ms
5: 384x640 1 animal, 238.5ms
6: 384x640 1 animal, 238.5ms
7: 384x640 1 animal, 238.5ms
8: 384x640 1 animal, 238.5ms
9: 384x640 1 animal, 238.5ms
10: 384x640 1 animal, 238.5ms
11: 384x640 1 animal, 238.5ms
12: 384x640 1 animal, 238.5ms
13: 384x640 1 animal, 238.5ms
14: 384x640 1 animal, 238.5ms
15: 384x640 1 animal, 238.5ms
Speed: 1.8ms preprocess, 238.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  9%|████████████▏                                                                                                                             | 6/68 [00:31<05:02,  4.87s/it]

0: 384x640 1 animal, 240.0ms
1: 384x640 1 animal, 240.0ms
2: 384x640 (no detections), 240.0ms
3: 384x640 (no detections), 240.0ms
4: 384x640 1 animal, 240.0ms
5: 384x640 1 animal, 240.0ms
6: 384x640 1 animal, 240.0ms
7: 384x640 1 animal, 240.0ms
8: 384x640 1 animal, 240.0ms
9: 384x640 1 animal, 240.0ms
10: 384x640 1 animal, 240.0ms
11: 384x640 (no detections), 240.0ms
12: 384x640 (no detections), 240.0ms
13: 384x640 (no detections), 240.0ms
14: 384x640 1 animal, 240.0ms
15: 384x640 1 animal, 240.0ms
Speed: 1.7ms preprocess, 240.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 10%|██████████████▏                                                                                                                           | 7/68 [00:36<04:51,  4.77s/it]

0: 384x640 1 animal, 240.8ms
1: 384x640 1 animal, 240.8ms
2: 384x640 1 animal, 240.8ms
3: 384x640 1 animal, 240.8ms
4: 384x640 (no detections), 240.8ms
5: 384x640 (no detections), 240.8ms
6: 384x640 1 animal, 240.8ms
7: 384x640 1 animal, 240.8ms
8: 384x640 1 animal, 240.8ms
9: 384x640 1 animal, 240.8ms
10: 384x640 1 animal, 240.8ms
11: 384x640 1 animal, 240.8ms
12: 384x640 1 animal, 240.8ms
13: 384x640 1 animal, 240.8ms
14: 384x640 (no detections), 240.8ms
15: 384x640 (no detections), 240.8ms
Speed: 1.9ms preprocess, 240.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 12%|████████████████▏                                                                                                                         | 8/68 [00:41<04:43,  4.72s/it]

0: 384x640 1 animal, 245.4ms
1: 384x640 1 animal, 245.4ms
2: 384x640 1 animal, 245.4ms
3: 384x640 1 animal, 245.4ms
4: 384x640 1 animal, 245.4ms
5: 384x640 1 animal, 245.4ms
6: 384x640 1 animal, 245.4ms
7: 384x640 1 animal, 245.4ms
8: 384x640 1 animal, 245.4ms
9: 384x640 1 animal, 245.4ms
10: 384x640 1 animal, 245.4ms
11: 384x640 1 animal, 245.4ms
12: 384x640 1 animal, 245.4ms
13: 384x640 1 animal, 245.4ms
14: 384x640 1 animal, 245.4ms
15: 384x640 1 animal, 245.4ms
Speed: 1.9ms preprocess, 245.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 13%|██████████████████▎                                                                                                                       | 9/68 [00:45<04:37,  4.71s/it]

0: 384x640 1 animal, 239.0ms
1: 384x640 1 animal, 239.0ms
2: 384x640 1 animal, 239.0ms
3: 384x640 1 animal, 239.0ms
4: 384x640 1 animal, 239.0ms
5: 384x640 1 animal, 239.0ms
6: 384x640 2 animals, 239.0ms
7: 384x640 3 animals, 239.0ms
8: 384x640 2 animals, 239.0ms
9: 384x640 3 animals, 239.0ms
10: 384x640 3 animals, 239.0ms
11: 384x640 2 animals, 239.0ms
12: 384x640 2 animals, 239.0ms
13: 384x640 3 animals, 239.0ms
14: 384x640 2 animals, 239.0ms
15: 384x640 2 animals, 239.0ms
Speed: 1.9ms preprocess, 239.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 15%|████████████████████▏                                                                                                                    | 10/68 [00:50<04:30,  4.67s/it]

0: 384x640 2 animals, 238.8ms
1: 384x640 3 animals, 238.8ms
2: 384x640 2 animals, 238.8ms
3: 384x640 3 animals, 238.8ms
4: 384x640 3 animals, 238.8ms
5: 384x640 2 animals, 238.8ms
6: 384x640 2 animals, 238.8ms
7: 384x640 3 animals, 238.8ms
8: 384x640 2 animals, 238.8ms
9: 384x640 2 animals, 238.8ms
10: 384x640 (no detections), 238.8ms
11: 384x640 1 animal, 238.8ms
12: 384x640 1 animal, 238.8ms
13: 384x640 1 animal, 238.8ms
14: 384x640 2 animals, 238.8ms
15: 384x640 2 animals, 238.8ms
Speed: 1.7ms preprocess, 238.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 16%|██████████████████████▏                                                                                                                  | 11/68 [00:54<04:23,  4.63s/it]

0: 384x640 1 animal, 240.3ms
1: 384x640 1 animal, 240.3ms
2: 384x640 1 animal, 240.3ms
3: 384x640 1 animal, 240.3ms
4: 384x640 3 animals, 240.3ms
5: 384x640 3 animals, 240.3ms
6: 384x640 3 animals, 240.3ms
7: 384x640 4 animals, 240.3ms
8: 384x640 3 animals, 240.3ms
9: 384x640 4 animals, 240.3ms
10: 384x640 4 animals, 240.3ms
11: 384x640 4 animals, 240.3ms
12: 384x640 1 animal, 240.3ms
13: 384x640 2 animals, 240.3ms
14: 384x640 1 animal, 240.3ms
15: 384x640 1 animal, 240.3ms
Speed: 1.7ms preprocess, 240.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 18%|████████████████████████▏                                                                                                                | 12/68 [00:59<04:17,  4.61s/it]

0: 384x640 1 animal, 238.9ms
1: 384x640 1 animal, 238.9ms
2: 384x640 1 animal, 238.9ms
3: 384x640 1 animal, 238.9ms
4: 384x640 1 animal, 238.9ms
5: 384x640 1 animal, 238.9ms
6: 384x640 1 animal, 238.9ms
7: 384x640 1 animal, 238.9ms
8: 384x640 1 animal, 238.9ms
9: 384x640 1 animal, 238.9ms
10: 384x640 1 animal, 238.9ms
11: 384x640 1 animal, 238.9ms
12: 384x640 1 animal, 238.9ms
13: 384x640 1 animal, 238.9ms
14: 384x640 1 animal, 238.9ms
15: 384x640 1 animal, 238.9ms
Speed: 2.0ms preprocess, 238.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 19%|██████████████████████████▏                                                                                                              | 13/68 [01:04<04:12,  4.60s/it]

0: 640x640 1 animal, 403.6ms
1: 640x640 1 animal, 403.6ms
2: 640x640 1 animal, 403.6ms
3: 640x640 2 animals, 403.6ms
4: 640x640 2 animals, 403.6ms
5: 640x640 2 animals, 403.6ms
6: 640x640 2 animals, 403.6ms
7: 640x640 3 animals, 403.6ms
8: 640x640 2 animals, 403.6ms
9: 640x640 3 animals, 403.6ms
10: 640x640 2 animals, 403.6ms
11: 640x640 2 animals, 403.6ms
12: 640x640 1 animal, 403.6ms
13: 640x640 2 animals, 403.6ms
14: 640x640 2 animals, 403.6ms
15: 640x640 2 animals, 403.6ms
Speed: 2.5ms preprocess, 403.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 21%|████████████████████████████▏                                                                                                            | 14/68 [01:10<04:45,  5.29s/it]

0: 640x640 2 animals, 405.0ms
1: 640x640 3 animals, 405.0ms
2: 640x640 2 animals, 405.0ms
3: 640x640 3 animals, 405.0ms
4: 640x640 2 animals, 405.0ms
5: 640x640 2 animals, 405.0ms
6: 640x640 1 animal, 405.0ms
7: 640x640 1 animal, 405.0ms
8: 640x640 1 animal, 405.0ms
9: 640x640 1 animal, 405.0ms
10: 640x640 1 animal, 405.0ms
11: 640x640 1 animal, 405.0ms
12: 640x640 1 animal, 405.0ms
13: 640x640 1 animal, 405.0ms
14: 640x640 1 animal, 405.0ms
15: 640x640 1 animal, 405.0ms
Speed: 2.7ms preprocess, 405.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 22%|██████████████████████████████▏                                                                                                          | 15/68 [01:18<05:09,  5.85s/it]

0: 640x640 1 animal, 400.4ms
1: 640x640 1 animal, 400.4ms
2: 640x640 1 animal, 400.4ms
3: 640x640 1 animal, 400.4ms
4: 640x640 1 animal, 400.4ms
5: 640x640 1 animal, 400.4ms
6: 640x640 1 animal, 400.4ms
7: 640x640 1 animal, 400.4ms
8: 640x640 1 animal, 400.4ms
9: 640x640 1 animal, 400.4ms
10: 640x640 1 animal, 400.4ms
11: 640x640 (no detections), 400.4ms
12: 640x640 (no detections), 400.4ms
13: 640x640 (no detections), 400.4ms
14: 640x640 (no detections), 400.4ms
15: 640x640 (no detections), 400.4ms
Speed: 2.6ms preprocess, 400.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 24%|████████████████████████████████▏                                                                                                        | 16/68 [01:25<05:21,  6.18s/it]

0: 640x640 (no detections), 403.9ms
1: 640x640 (no detections), 403.9ms
2: 640x640 (no detections), 403.9ms
3: 640x640 (no detections), 403.9ms
4: 640x640 1 animal, 403.9ms
5: 640x640 1 animal, 403.9ms
6: 640x640 1 animal, 403.9ms
7: 640x640 1 animal, 403.9ms
8: 640x640 1 animal, 403.9ms
9: 640x640 2 animals, 403.9ms
10: 640x640 2 animals, 403.9ms
11: 640x640 2 animals, 403.9ms
12: 640x640 1 animal, 403.9ms
13: 640x640 1 animal, 403.9ms
14: 640x640 1 animal, 403.9ms
15: 640x640 1 animal, 403.9ms
Speed: 2.5ms preprocess, 403.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 25%|██████████████████████████████████▎                                                                                                      | 17/68 [01:32<05:30,  6.47s/it]

0: 384x640 1 animal, 235.8ms
1: 384x640 1 animal, 235.8ms
2: 384x640 1 animal, 235.8ms
3: 384x640 1 animal, 235.8ms
4: 384x640 1 animal, 235.8ms
5: 384x640 1 animal, 235.8ms
6: 384x640 1 animal, 235.8ms
7: 384x640 1 animal, 235.8ms
8: 384x640 2 animals, 235.8ms
9: 384x640 2 animals, 235.8ms
10: 384x640 2 animals, 235.8ms
11: 384x640 2 animals, 235.8ms
12: 384x640 2 animals, 235.8ms
13: 384x640 2 animals, 235.8ms
14: 384x640 2 animals, 235.8ms
15: 384x640 2 animals, 235.8ms
Speed: 2.1ms preprocess, 235.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 26%|████████████████████████████████████▎                                                                                                    | 18/68 [01:36<04:49,  5.78s/it]

0: 640x640 2 animals, 397.5ms
1: 640x640 2 animals, 397.5ms
2: 640x640 2 animals, 397.5ms
3: 640x640 2 animals, 397.5ms
4: 640x640 2 animals, 397.5ms
5: 640x640 2 animals, 397.5ms
6: 640x640 2 animals, 397.5ms
7: 640x640 2 animals, 397.5ms
8: 640x640 2 animals, 397.5ms
9: 640x640 2 animals, 397.5ms
10: 640x640 2 animals, 397.5ms
11: 640x640 2 animals, 397.5ms
12: 640x640 (no detections), 397.5ms
13: 640x640 (no detections), 397.5ms
14: 640x640 (no detections), 397.5ms
15: 640x640 1 animal, 397.5ms
Speed: 2.5ms preprocess, 397.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 28%|██████████████████████████████████████▎                                                                                                  | 19/68 [01:43<04:58,  6.10s/it]

0: 384x640 (no detections), 241.7ms
1: 384x640 1 animal, 241.7ms
2: 384x640 1 animal, 241.7ms
3: 384x640 1 animal, 241.7ms
4: 384x640 1 animal, 241.7ms
5: 384x640 1 animal, 241.7ms
6: 384x640 1 animal, 241.7ms
7: 384x640 1 animal, 241.7ms
8: 384x640 1 animal, 241.7ms
9: 384x640 1 animal, 241.7ms
10: 384x640 2 animals, 241.7ms
11: 384x640 3 animals, 241.7ms
12: 384x640 2 animals, 241.7ms
13: 384x640 2 animals, 241.7ms
14: 384x640 2 animals, 241.7ms
15: 384x640 2 animals, 241.7ms
Speed: 1.7ms preprocess, 241.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 29%|████████████████████████████████████████▎                                                                                                | 20/68 [01:47<04:32,  5.68s/it]

0: 384x640 1 animal, 238.7ms
1: 384x640 1 animal, 238.7ms
2: 384x640 1 animal, 238.7ms
3: 384x640 1 animal, 238.7ms
4: 384x640 1 animal, 238.7ms
5: 384x640 1 animal, 238.7ms
6: 384x640 1 animal, 238.7ms
7: 384x640 2 animals, 238.7ms
8: 384x640 2 animals, 238.7ms
9: 384x640 2 animals, 238.7ms
10: 384x640 2 animals, 238.7ms
11: 384x640 1 animal, 238.7ms
12: 384x640 1 animal, 238.7ms
13: 384x640 1 animal, 238.7ms
14: 384x640 1 animal, 238.7ms
15: 384x640 1 animal, 238.7ms
Speed: 1.7ms preprocess, 238.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 31%|██████████████████████████████████████████▎                                                                                              | 21/68 [01:52<04:11,  5.36s/it]

0: 384x640 1 animal, 241.3ms
1: 384x640 1 animal, 241.3ms
2: 384x640 1 animal, 241.3ms
3: 384x640 1 animal, 241.3ms
4: 384x640 1 animal, 241.3ms
5: 384x640 1 animal, 241.3ms
6: 384x640 1 animal, 241.3ms
7: 384x640 1 animal, 241.3ms
8: 384x640 1 animal, 241.3ms
9: 384x640 1 animal, 241.3ms
10: 384x640 1 animal, 241.3ms
11: 384x640 1 animal, 241.3ms
12: 384x640 1 animal, 241.3ms
13: 384x640 3 animals, 241.3ms
14: 384x640 1 animal, 241.3ms
15: 384x640 1 animal, 241.3ms
Speed: 1.8ms preprocess, 241.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 32%|████████████████████████████████████████████▎                                                                                            | 22/68 [01:57<03:56,  5.14s/it]

0: 640x640 1 animal, 405.1ms
1: 640x640 1 animal, 405.1ms
2: 640x640 1 animal, 405.1ms
3: 640x640 1 animal, 405.1ms
4: 640x640 1 animal, 405.1ms
5: 640x640 1 animal, 405.1ms
6: 640x640 1 animal, 405.1ms
7: 640x640 1 animal, 405.1ms
8: 640x640 1 animal, 405.1ms
9: 640x640 1 animal, 405.1ms
10: 640x640 1 animal, 405.1ms
11: 640x640 1 animal, 405.1ms
12: 640x640 1 animal, 405.1ms
13: 640x640 1 animal, 405.1ms
14: 640x640 1 animal, 405.1ms
15: 640x640 2 animals, 405.1ms
Speed: 2.7ms preprocess, 405.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 34%|██████████████████████████████████████████████▎                                                                                          | 23/68 [02:04<04:19,  5.77s/it]

0: 640x640 1 animal, 399.9ms
1: 640x640 1 animal, 399.9ms
2: 640x640 1 animal, 399.9ms
3: 640x640 1 animal, 399.9ms
4: 640x640 1 animal, 399.9ms
5: 640x640 1 animal, 399.9ms
6: 640x640 2 animals, 399.9ms
7: 640x640 2 animals, 399.9ms
8: 640x640 2 animals, 399.9ms
9: 640x640 2 animals, 399.9ms
10: 640x640 3 animals, 399.9ms
11: 640x640 3 animals, 399.9ms
12: 640x640 1 animal, 399.9ms
13: 640x640 1 animal, 399.9ms
14: 640x640 (no detections), 399.9ms
15: 640x640 1 animal, 399.9ms
Speed: 2.8ms preprocess, 399.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 35%|████████████████████████████████████████████████▎                                                                                        | 24/68 [02:11<04:33,  6.22s/it]

0: 384x640 1 animal, 233.9ms
1: 384x640 1 animal, 233.9ms
2: 384x640 1 animal, 233.9ms
3: 384x640 1 animal, 233.9ms
4: 384x640 1 animal, 233.9ms
5: 384x640 1 animal, 233.9ms
6: 384x640 1 animal, 233.9ms
7: 384x640 1 animal, 233.9ms
8: 384x640 (no detections), 233.9ms
9: 384x640 (no detections), 233.9ms
10: 384x640 (no detections), 233.9ms
11: 384x640 (no detections), 233.9ms
12: 384x640 (no detections), 233.9ms
13: 384x640 (no detections), 233.9ms
14: 384x640 (no detections), 233.9ms
15: 384x640 (no detections), 233.9ms
Speed: 1.7ms preprocess, 233.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 37%|██████████████████████████████████████████████████▎                                                                                      | 25/68 [02:16<04:04,  5.69s/it]

0: 640x640 1 animal, 391.3ms
1: 640x640 1 animal, 391.3ms
2: 640x640 1 animal, 391.3ms
3: 640x640 1 animal, 391.3ms
4: 640x640 1 animal, 391.3ms
5: 640x640 1 animal, 391.3ms
6: 640x640 1 animal, 391.3ms
7: 640x640 1 animal, 391.3ms
8: 640x640 1 animal, 391.3ms
9: 640x640 1 animal, 391.3ms
10: 640x640 1 animal, 391.3ms
11: 640x640 1 animal, 391.3ms
12: 640x640 1 animal, 391.3ms
13: 640x640 1 animal, 391.3ms
14: 640x640 1 animal, 391.3ms
15: 640x640 1 animal, 391.3ms
Speed: 2.7ms preprocess, 391.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 38%|████████████████████████████████████████████████████▍                                                                                    | 26/68 [02:22<04:13,  6.04s/it]

0: 384x640 1 animal, 239.0ms
1: 384x640 1 animal, 239.0ms
2: 384x640 1 animal, 239.0ms
3: 384x640 1 animal, 239.0ms
4: 384x640 (no detections), 239.0ms
5: 384x640 (no detections), 239.0ms
6: 384x640 1 animal, 239.0ms
7: 384x640 (no detections), 239.0ms
8: 384x640 (no detections), 239.0ms
9: 384x640 (no detections), 239.0ms
10: 384x640 (no detections), 239.0ms
11: 384x640 (no detections), 239.0ms
12: 384x640 (no detections), 239.0ms
13: 384x640 (no detections), 239.0ms
14: 384x640 1 animal, 239.0ms
15: 384x640 1 animal, 239.0ms
Speed: 1.7ms preprocess, 239.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 40%|██████████████████████████████████████████████████████▍                                                                                  | 27/68 [02:27<03:49,  5.59s/it]

0: 384x640 (no detections), 239.2ms
1: 384x640 (no detections), 239.2ms
2: 384x640 (no detections), 239.2ms
3: 384x640 (no detections), 239.2ms
4: 384x640 1 animal, 239.2ms
5: 384x640 1 animal, 239.2ms
6: 384x640 1 animal, 239.2ms
7: 384x640 1 animal, 239.2ms
8: 384x640 1 animal, 239.2ms
9: 384x640 1 animal, 239.2ms
10: 384x640 1 animal, 239.2ms
11: 384x640 1 animal, 239.2ms
12: 384x640 1 animal, 239.2ms
13: 384x640 1 animal, 239.2ms
14: 384x640 3 animals, 239.2ms
15: 384x640 2 animals, 239.2ms
Speed: 1.7ms preprocess, 239.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 41%|████████████████████████████████████████████████████████▍                                                                                | 28/68 [02:32<03:30,  5.27s/it]

0: 384x640 2 animals, 239.3ms
1: 384x640 1 animal, 239.3ms
2: 384x640 (no detections), 239.3ms
3: 384x640 1 animal, 239.3ms
4: 384x640 1 animal, 239.3ms
5: 384x640 1 animal, 239.3ms
6: 384x640 1 animal, 239.3ms
7: 384x640 1 animal, 239.3ms
8: 384x640 1 animal, 239.3ms
9: 384x640 1 animal, 239.3ms
10: 384x640 1 animal, 239.3ms
11: 384x640 1 animal, 239.3ms
12: 384x640 1 animal, 239.3ms
13: 384x640 1 animal, 239.3ms
14: 384x640 1 animal, 239.3ms
15: 384x640 2 animals, 239.3ms
Speed: 1.9ms preprocess, 239.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 43%|██████████████████████████████████████████████████████████▍                                                                              | 29/68 [02:36<03:17,  5.07s/it]

0: 384x640 2 animals, 246.4ms
1: 384x640 3 animals, 246.4ms
2: 384x640 4 animals, 246.4ms
3: 384x640 4 animals, 246.4ms
4: 384x640 3 animals, 246.4ms
5: 384x640 2 animals, 246.4ms
6: 384x640 3 animals, 246.4ms
7: 384x640 2 animals, 246.4ms
8: 384x640 2 animals, 246.4ms
9: 384x640 2 animals, 246.4ms
10: 384x640 3 animals, 246.4ms
11: 384x640 2 animals, 246.4ms
12: 384x640 3 animals, 246.4ms
13: 384x640 3 animals, 246.4ms
14: 384x640 3 animals, 246.4ms
15: 384x640 2 animals, 246.4ms
Speed: 1.9ms preprocess, 246.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 44%|████████████████████████████████████████████████████████████▍                                                                            | 30/68 [02:41<03:08,  4.97s/it]

0: 384x640 1 animal, 241.3ms
1: 384x640 1 animal, 241.3ms
2: 384x640 2 animals, 241.3ms
3: 384x640 3 animals, 241.3ms
4: 384x640 4 animals, 241.3ms
5: 384x640 4 animals, 241.3ms
6: 384x640 1 animal, 241.3ms
7: 384x640 1 animal, 241.3ms
8: 384x640 1 animal, 241.3ms
9: 384x640 (no detections), 241.3ms
10: 384x640 1 animal, 241.3ms
11: 384x640 1 animal, 241.3ms
12: 384x640 1 animal, 241.3ms
13: 384x640 1 animal, 241.3ms
14: 384x640 1 animal, 241.3ms
15: 384x640 1 animal, 241.3ms
Speed: 1.9ms preprocess, 241.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 46%|██████████████████████████████████████████████████████████████▍                                                                          | 31/68 [02:45<03:00,  4.87s/it]

0: 384x640 1 animal, 241.0ms
1: 384x640 1 animal, 241.0ms
2: 384x640 1 animal, 241.0ms
3: 384x640 1 animal, 241.0ms
4: 384x640 1 animal, 241.0ms
5: 384x640 1 animal, 241.0ms
6: 384x640 1 animal, 241.0ms
7: 384x640 1 animal, 241.0ms
8: 384x640 1 animal, 241.0ms
9: 384x640 1 animal, 241.0ms
10: 384x640 (no detections), 241.0ms
11: 384x640 (no detections), 241.0ms
12: 384x640 (no detections), 241.0ms
13: 384x640 (no detections), 241.0ms
14: 384x640 1 animal, 241.0ms
15: 384x640 1 animal, 241.0ms
Speed: 1.7ms preprocess, 241.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 47%|████████████████████████████████████████████████████████████████▍                                                                        | 32/68 [02:50<02:52,  4.79s/it]

0: 384x640 1 animal, 241.2ms
1: 384x640 1 animal, 241.2ms
2: 384x640 1 animal, 241.2ms
3: 384x640 1 animal, 241.2ms
4: 384x640 1 animal, 241.2ms
5: 384x640 1 animal, 241.2ms
6: 384x640 1 animal, 241.2ms
7: 384x640 1 animal, 241.2ms
8: 384x640 1 animal, 241.2ms
9: 384x640 1 animal, 241.2ms
10: 384x640 1 animal, 241.2ms
11: 384x640 1 animal, 241.2ms
12: 384x640 1 animal, 241.2ms
13: 384x640 1 animal, 241.2ms
14: 384x640 3 animals, 241.2ms
15: 384x640 2 animals, 241.2ms
Speed: 1.7ms preprocess, 241.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 49%|██████████████████████████████████████████████████████████████████▍                                                                      | 33/68 [02:55<02:46,  4.74s/it]

0: 640x640 2 animals, 397.4ms
1: 640x640 2 animals, 397.4ms
2: 640x640 1 animal, 397.4ms
3: 640x640 1 animal, 397.4ms
4: 640x640 1 animal, 397.4ms
5: 640x640 1 animal, 397.4ms
6: 640x640 1 animal, 397.4ms
7: 640x640 1 animal, 397.4ms
8: 640x640 1 animal, 397.4ms
9: 640x640 1 animal, 397.4ms
10: 640x640 1 animal, 397.4ms
11: 640x640 1 animal, 397.4ms
12: 640x640 1 animal, 397.4ms
13: 640x640 1 animal, 397.4ms
14: 640x640 1 animal, 397.4ms
15: 640x640 1 animal, 397.4ms
Speed: 2.5ms preprocess, 397.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 50%|████████████████████████████████████████████████████████████████████▌                                                                    | 34/68 [03:02<03:03,  5.39s/it]

0: 384x640 2 animals, 238.6ms
1: 384x640 2 animals, 238.6ms
2: 384x640 2 animals, 238.6ms
3: 384x640 3 animals, 238.6ms
4: 384x640 2 animals, 238.6ms
5: 384x640 4 animals, 238.6ms
6: 384x640 2 animals, 238.6ms
7: 384x640 2 animals, 238.6ms
8: 384x640 2 animals, 238.6ms
9: 384x640 1 animal, 238.6ms
10: 384x640 2 animals, 238.6ms
11: 384x640 2 animals, 238.6ms
12: 384x640 2 animals, 238.6ms
13: 384x640 2 animals, 238.6ms
14: 384x640 2 animals, 238.6ms
15: 384x640 3 animals, 238.6ms
Speed: 1.8ms preprocess, 238.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 51%|██████████████████████████████████████████████████████████████████████▌                                                                  | 35/68 [03:06<02:50,  5.16s/it]

0: 640x640 1 animal, 399.8ms
1: 640x640 1 animal, 399.8ms
2: 640x640 1 animal, 399.8ms
3: 640x640 1 animal, 399.8ms
4: 640x640 1 animal, 399.8ms
5: 640x640 (no detections), 399.8ms
6: 640x640 (no detections), 399.8ms
7: 640x640 (no detections), 399.8ms
8: 640x640 (no detections), 399.8ms
9: 640x640 (no detections), 399.8ms
10: 640x640 1 animal, 399.8ms
11: 640x640 1 animal, 399.8ms
12: 640x640 1 animal, 399.8ms
13: 640x640 2 animals, 399.8ms
14: 640x640 (no detections), 399.8ms
15: 640x640 (no detections), 399.8ms
Speed: 2.7ms preprocess, 399.8ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 53%|████████████████████████████████████████████████████████████████████████▌                                                                | 36/68 [03:13<03:03,  5.74s/it]

0: 640x640 (no detections), 407.4ms
1: 640x640 (no detections), 407.4ms
2: 640x640 (no detections), 407.4ms
3: 640x640 (no detections), 407.4ms
4: 640x640 1 animal, 407.4ms
5: 640x640 2 animals, 407.4ms
6: 640x640 5 animals, 407.4ms
7: 640x640 3 animals, 407.4ms
8: 640x640 4 animals, 407.4ms
9: 640x640 1 animal, 407.4ms
10: 640x640 2 animals, 407.4ms
11: 640x640 1 animal, 407.4ms
12: 640x640 1 animal, 407.4ms
13: 640x640 1 animal, 407.4ms
14: 640x640 1 animal, 407.4ms
15: 640x640 1 animal, 407.4ms
Speed: 2.7ms preprocess, 407.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 54%|██████████████████████████████████████████████████████████████████████████▌                                                              | 37/68 [03:21<03:12,  6.22s/it]

0: 384x640 1 animal, 243.2ms
1: 384x640 1 animal, 243.2ms
2: 384x640 1 animal, 243.2ms
3: 384x640 1 animal, 243.2ms
4: 384x640 1 animal, 243.2ms
5: 384x640 1 animal, 243.2ms
6: 384x640 1 animal, 243.2ms
7: 384x640 (no detections), 243.2ms
8: 384x640 1 animal, 243.2ms
9: 384x640 1 animal, 243.2ms
10: 384x640 1 animal, 243.2ms
11: 384x640 1 animal, 243.2ms
12: 384x640 1 animal, 243.2ms
13: 384x640 1 animal, 243.2ms
14: 384x640 1 animal, 243.2ms
15: 384x640 1 animal, 243.2ms
Speed: 1.8ms preprocess, 243.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 56%|████████████████████████████████████████████████████████████████████████████▌                                                            | 38/68 [03:25<02:52,  5.75s/it]

0: 384x640 1 animal, 243.5ms
1: 384x640 1 animal, 243.5ms
2: 384x640 1 animal, 243.5ms
3: 384x640 1 animal, 243.5ms
4: 384x640 (no detections), 243.5ms
5: 384x640 (no detections), 243.5ms
6: 384x640 (no detections), 243.5ms
7: 384x640 (no detections), 243.5ms
8: 384x640 (no detections), 243.5ms
9: 384x640 (no detections), 243.5ms
10: 384x640 (no detections), 243.5ms
11: 384x640 (no detections), 243.5ms
12: 384x640 1 animal, 243.5ms
13: 384x640 1 animal, 243.5ms
14: 384x640 1 animal, 243.5ms
15: 384x640 2 animals, 243.5ms
Speed: 1.8ms preprocess, 243.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 57%|██████████████████████████████████████████████████████████████████████████████▌                                                          | 39/68 [03:30<02:37,  5.44s/it]

0: 384x640 4 animals, 241.4ms
1: 384x640 2 animals, 241.4ms
2: 384x640 3 animals, 241.4ms
3: 384x640 2 animals, 241.4ms
4: 384x640 3 animals, 241.4ms
5: 384x640 5 animals, 241.4ms
6: 384x640 1 animal, 241.4ms
7: 384x640 1 animal, 241.4ms
8: 384x640 2 animals, 241.4ms
9: 384x640 4 animals, 241.4ms
10: 384x640 3 animals, 241.4ms
11: 384x640 3 animals, 241.4ms
12: 384x640 3 animals, 241.4ms
13: 384x640 2 animals, 241.4ms
14: 384x640 3 animals, 241.4ms
15: 384x640 2 animals, 241.4ms
Speed: 1.8ms preprocess, 241.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 59%|████████████████████████████████████████████████████████████████████████████████▌                                                        | 40/68 [03:35<02:27,  5.26s/it]

0: 384x640 1 animal, 232.2ms
1: 384x640 1 animal, 232.2ms
2: 384x640 1 animal, 232.2ms
3: 384x640 1 animal, 232.2ms
4: 384x640 1 animal, 232.2ms
5: 384x640 1 animal, 232.2ms
6: 384x640 1 animal, 232.2ms
7: 384x640 1 animal, 232.2ms
8: 384x640 1 animal, 232.2ms
9: 384x640 2 animals, 232.2ms
10: 384x640 1 animal, 232.2ms
11: 384x640 1 animal, 232.2ms
12: 384x640 1 animal, 232.2ms
13: 384x640 1 animal, 232.2ms
14: 384x640 2 animals, 232.2ms
15: 384x640 1 animal, 232.2ms
Speed: 1.8ms preprocess, 232.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 60%|██████████████████████████████████████████████████████████████████████████████████▌                                                      | 41/68 [03:39<02:15,  5.03s/it]

0: 384x640 1 animal, 234.8ms
1: 384x640 1 animal, 234.8ms
2: 384x640 1 animal, 234.8ms
3: 384x640 (no detections), 234.8ms
4: 384x640 1 animal, 234.8ms
5: 384x640 1 animal, 234.8ms
6: 384x640 1 animal, 234.8ms
7: 384x640 1 animal, 234.8ms
8: 384x640 1 animal, 234.8ms
9: 384x640 2 animals, 234.8ms
10: 384x640 1 animal, 234.8ms
11: 384x640 1 animal, 234.8ms
12: 384x640 (no detections), 234.8ms
13: 384x640 (no detections), 234.8ms
14: 384x640 2 animals, 234.8ms
15: 384x640 2 animals, 234.8ms
Speed: 1.9ms preprocess, 234.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 62%|████████████████████████████████████████████████████████████████████████████████████▌                                                    | 42/68 [03:44<02:08,  4.92s/it]

0: 384x640 2 animals, 238.2ms
1: 384x640 2 animals, 238.2ms
2: 384x640 2 animals, 238.2ms
3: 384x640 2 animals, 238.2ms
4: 384x640 2 animals, 238.2ms
5: 384x640 2 animals, 238.2ms
6: 384x640 2 animals, 238.2ms
7: 384x640 1 animal, 238.2ms
8: 384x640 1 animal, 238.2ms
9: 384x640 1 animal, 238.2ms
10: 384x640 1 animal, 238.2ms
11: 384x640 1 animal, 238.2ms
12: 384x640 1 animal, 238.2ms
13: 384x640 1 animal, 238.2ms
14: 384x640 1 animal, 238.2ms
15: 384x640 1 animal, 238.2ms
Speed: 1.9ms preprocess, 238.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 63%|██████████████████████████████████████████████████████████████████████████████████████▋                                                  | 43/68 [03:49<02:01,  4.87s/it]

0: 640x640 1 animal, 398.6ms
1: 640x640 1 animal, 398.6ms
2: 640x640 1 animal, 398.6ms
3: 640x640 1 animal, 398.6ms
4: 640x640 1 animal, 398.6ms
5: 640x640 1 animal, 398.6ms
6: 640x640 1 animal, 398.6ms
7: 640x640 1 animal, 398.6ms
8: 640x640 1 animal, 398.6ms
9: 640x640 1 animal, 398.6ms
10: 640x640 1 animal, 398.6ms
11: 640x640 1 animal, 398.6ms
12: 640x640 1 animal, 398.6ms
13: 640x640 1 animal, 398.6ms
14: 640x640 1 animal, 398.6ms
15: 640x640 1 animal, 398.6ms
Speed: 2.7ms preprocess, 398.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 65%|████████████████████████████████████████████████████████████████████████████████████████▋                                                | 44/68 [03:56<02:13,  5.56s/it]

0: 640x640 1 animal, 396.4ms
1: 640x640 1 animal, 396.4ms
2: 640x640 1 animal, 396.4ms
3: 640x640 1 animal, 396.4ms
4: 640x640 1 animal, 396.4ms
5: 640x640 1 animal, 396.4ms
6: 640x640 4 animals, 396.4ms
7: 640x640 2 animals, 396.4ms
8: 640x640 3 animals, 396.4ms
9: 640x640 2 animals, 396.4ms
10: 640x640 2 animals, 396.4ms
11: 640x640 3 animals, 396.4ms
12: 640x640 2 animals, 396.4ms
13: 640x640 2 animals, 396.4ms
14: 640x640 2 animals, 396.4ms
15: 640x640 2 animals, 396.4ms
Speed: 2.5ms preprocess, 396.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▋                                              | 45/68 [04:03<02:17,  5.99s/it]

0: 384x640 2 animals, 236.6ms
1: 384x640 1 animal, 236.6ms
2: 384x640 1 animal, 236.6ms
3: 384x640 1 animal, 236.6ms
4: 384x640 1 animal, 236.6ms
5: 384x640 1 animal, 236.6ms
6: 384x640 1 animal, 236.6ms
7: 384x640 1 animal, 236.6ms
8: 384x640 1 animal, 236.6ms
9: 384x640 1 animal, 236.6ms
10: 384x640 1 animal, 236.6ms
11: 384x640 1 animal, 236.6ms
12: 384x640 1 animal, 236.6ms
13: 384x640 1 animal, 236.6ms
14: 384x640 1 animal, 236.6ms
15: 384x640 1 animal, 236.6ms
Speed: 1.7ms preprocess, 236.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 68%|████████████████████████████████████████████████████████████████████████████████████████████▋                                            | 46/68 [04:08<02:02,  5.55s/it]

0: 384x640 1 animal, 237.0ms
1: 384x640 1 animal, 237.0ms
2: 384x640 1 animal, 237.0ms
3: 384x640 1 animal, 237.0ms
4: 384x640 2 animals, 237.0ms
5: 384x640 2 animals, 237.0ms
6: 384x640 1 animal, 237.0ms
7: 384x640 2 animals, 237.0ms
8: 384x640 3 animals, 237.0ms
9: 384x640 2 animals, 237.0ms
10: 384x640 2 animals, 237.0ms
11: 384x640 2 animals, 237.0ms
12: 384x640 2 animals, 237.0ms
13: 384x640 1 animal, 237.0ms
14: 384x640 1 animal, 237.0ms
15: 384x640 1 animal, 237.0ms
Speed: 1.9ms preprocess, 237.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                          | 47/68 [04:12<01:50,  5.26s/it]

0: 384x640 1 animal, 233.9ms
1: 384x640 1 animal, 233.9ms
2: 384x640 (no detections), 233.9ms
3: 384x640 (no detections), 233.9ms
4: 384x640 (no detections), 233.9ms
5: 384x640 (no detections), 233.9ms
6: 384x640 (no detections), 233.9ms
7: 384x640 (no detections), 233.9ms
8: 384x640 1 animal, 233.9ms
9: 384x640 1 animal, 233.9ms
10: 384x640 1 animal, 233.9ms
11: 384x640 1 animal, 233.9ms
12: 384x640 (no detections), 233.9ms
13: 384x640 (no detections), 233.9ms
14: 384x640 (no detections), 233.9ms
15: 384x640 (no detections), 233.9ms
Speed: 2.0ms preprocess, 233.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 71%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                        | 48/68 [04:17<01:40,  5.03s/it]

0: 384x640 (no detections), 233.1ms
1: 384x640 (no detections), 233.1ms
2: 384x640 1 animal, 233.1ms
3: 384x640 1 animal, 233.1ms
4: 384x640 2 animals, 233.1ms
5: 384x640 1 animal, 233.1ms
6: 384x640 1 animal, 233.1ms
7: 384x640 1 animal, 233.1ms
8: 384x640 1 animal, 233.1ms
9: 384x640 3 animals, 233.1ms
10: 384x640 1 animal, 233.1ms
11: 384x640 1 animal, 233.1ms
12: 384x640 1 animal, 233.1ms
13: 384x640 1 animal, 233.1ms
14: 384x640 1 animal, 233.1ms
15: 384x640 1 animal, 233.1ms
Speed: 1.7ms preprocess, 233.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 49/68 [04:21<01:32,  4.88s/it]

0: 384x640 1 animal, 235.5ms
1: 384x640 1 animal, 235.5ms
2: 384x640 1 animal, 235.5ms
3: 384x640 2 animals, 235.5ms
4: 384x640 1 animal, 235.5ms
5: 384x640 (no detections), 235.5ms
6: 384x640 1 animal, 235.5ms
7: 384x640 1 animal, 235.5ms
8: 384x640 1 animal, 235.5ms
9: 384x640 1 animal, 235.5ms
10: 384x640 1 animal, 235.5ms
11: 384x640 1 animal, 235.5ms
12: 384x640 1 animal, 235.5ms
13: 384x640 1 animal, 235.5ms
14: 384x640 1 animal, 235.5ms
15: 384x640 1 animal, 235.5ms
Speed: 1.8ms preprocess, 235.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 74%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 50/68 [04:26<01:25,  4.77s/it]

0: 384x640 1 animal, 241.3ms
1: 384x640 1 animal, 241.3ms
2: 384x640 1 animal, 241.3ms
3: 384x640 1 animal, 241.3ms
4: 384x640 1 animal, 241.3ms
5: 384x640 1 animal, 241.3ms
6: 384x640 1 animal, 241.3ms
7: 384x640 1 animal, 241.3ms
8: 384x640 1 animal, 241.3ms
9: 384x640 1 animal, 241.3ms
10: 384x640 1 animal, 241.3ms
11: 384x640 1 animal, 241.3ms
12: 384x640 1 animal, 241.3ms
13: 384x640 1 animal, 241.3ms
14: 384x640 1 animal, 241.3ms
15: 384x640 1 animal, 241.3ms
Speed: 1.8ms preprocess, 241.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 51/68 [04:30<01:20,  4.74s/it]

0: 384x640 1 animal, 242.1ms
1: 384x640 1 animal, 242.1ms
2: 384x640 1 animal, 242.1ms
3: 384x640 1 animal, 242.1ms
4: 384x640 2 animals, 242.1ms
5: 384x640 1 animal, 242.1ms
6: 384x640 2 animals, 242.1ms
7: 384x640 1 animal, 242.1ms
8: 384x640 2 animals, 242.1ms
9: 384x640 (no detections), 242.1ms
10: 384x640 2 animals, 242.1ms
11: 384x640 (no detections), 242.1ms
12: 384x640 (no detections), 242.1ms
13: 384x640 (no detections), 242.1ms
14: 384x640 1 animal, 242.1ms
15: 384x640 1 animal, 242.1ms
Speed: 1.9ms preprocess, 242.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 52/68 [04:35<01:16,  4.77s/it]

0: 384x640 2 animals, 241.0ms
1: 384x640 2 animals, 241.0ms
2: 384x640 1 animal, 241.0ms
3: 384x640 1 animal, 241.0ms
4: 384x640 1 animal, 241.0ms
5: 384x640 1 animal, 241.0ms
6: 384x640 1 animal, 241.0ms
7: 384x640 1 animal, 241.0ms
8: 384x640 1 animal, 241.0ms
9: 384x640 1 animal, 241.0ms
10: 384x640 1 animal, 241.0ms
11: 384x640 (no detections), 241.0ms
12: 384x640 (no detections), 241.0ms
13: 384x640 (no detections), 241.0ms
14: 384x640 (no detections), 241.0ms
15: 384x640 (no detections), 241.0ms
Speed: 1.7ms preprocess, 241.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 53/68 [04:40<01:11,  4.79s/it]

0: 384x640 (no detections), 242.6ms
1: 384x640 (no detections), 242.6ms
2: 384x640 1 animal, 242.6ms
3: 384x640 2 animals, 242.6ms
4: 384x640 1 animal, 242.6ms
5: 384x640 1 animal, 242.6ms
6: 384x640 1 animal, 242.6ms
7: 384x640 1 animal, 242.6ms
8: 384x640 1 animal, 242.6ms
9: 384x640 1 animal, 242.6ms
10: 384x640 (no detections), 242.6ms
11: 384x640 (no detections), 242.6ms
12: 384x640 1 animal, 242.6ms
13: 384x640 1 animal, 242.6ms
14: 384x640 1 animal, 242.6ms
15: 384x640 1 animal, 242.6ms
Speed: 1.7ms preprocess, 242.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 54/68 [04:45<01:07,  4.80s/it]

0: 384x640 1 animal, 237.7ms
1: 384x640 1 animal, 237.7ms
2: 384x640 1 animal, 237.7ms
3: 384x640 1 animal, 237.7ms
4: 384x640 (no detections), 237.7ms
5: 384x640 (no detections), 237.7ms
6: 384x640 1 animal, 237.7ms
7: 384x640 1 animal, 237.7ms
8: 384x640 (no detections), 237.7ms
9: 384x640 (no detections), 237.7ms
10: 384x640 (no detections), 237.7ms
11: 384x640 1 animal, 237.7ms
12: 384x640 (no detections), 237.7ms
13: 384x640 (no detections), 237.7ms
14: 384x640 (no detections), 237.7ms
15: 384x640 (no detections), 237.7ms
Speed: 2.0ms preprocess, 237.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 55/68 [04:49<01:01,  4.75s/it]

0: 384x640 2 animals, 241.3ms
1: 384x640 2 animals, 241.3ms
2: 384x640 2 animals, 241.3ms
3: 384x640 1 animal, 241.3ms
4: 384x640 2 animals, 241.3ms
5: 384x640 2 animals, 241.3ms
6: 384x640 2 animals, 241.3ms
7: 384x640 2 animals, 241.3ms
8: 384x640 2 animals, 241.3ms
9: 384x640 2 animals, 241.3ms
10: 384x640 1 animal, 241.3ms
11: 384x640 2 animals, 241.3ms
12: 384x640 1 animal, 241.3ms
13: 384x640 1 animal, 241.3ms
14: 384x640 1 animal, 241.3ms
15: 384x640 (no detections), 241.3ms
Speed: 2.0ms preprocess, 241.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 56/68 [04:54<00:56,  4.72s/it]

0: 384x640 (no detections), 239.9ms
1: 384x640 (no detections), 239.9ms
2: 384x640 (no detections), 239.9ms
3: 384x640 (no detections), 239.9ms
4: 384x640 2 animals, 239.9ms
5: 384x640 1 animal, 239.9ms
6: 384x640 (no detections), 239.9ms
7: 384x640 (no detections), 239.9ms
8: 384x640 (no detections), 239.9ms
9: 384x640 1 animal, 239.9ms
10: 384x640 (no detections), 239.9ms
11: 384x640 (no detections), 239.9ms
12: 384x640 (no detections), 239.9ms
13: 384x640 (no detections), 239.9ms
14: 384x640 2 animals, 239.9ms
15: 384x640 4 animals, 239.9ms
Speed: 1.7ms preprocess, 239.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 57/68 [04:59<00:51,  4.70s/it]

0: 384x640 5 animals, 239.7ms
1: 384x640 5 animals, 239.7ms
2: 384x640 2 animals, 239.7ms
3: 384x640 4 animals, 239.7ms
4: 384x640 2 animals, 239.7ms
5: 384x640 1 animal, 239.7ms
6: 384x640 1 animal, 239.7ms
7: 384x640 (no detections), 239.7ms
8: 384x640 1 animal, 239.7ms
9: 384x640 1 animal, 239.7ms
10: 384x640 1 animal, 239.7ms
11: 384x640 1 animal, 239.7ms
12: 384x640 1 animal, 239.7ms
13: 384x640 1 animal, 239.7ms
14: 384x640 1 animal, 239.7ms
15: 384x640 1 animal, 239.7ms
Speed: 1.7ms preprocess, 239.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 58/68 [05:03<00:46,  4.68s/it]

0: 384x640 1 animal, 238.8ms
1: 384x640 1 animal, 238.8ms
2: 384x640 1 animal, 238.8ms
3: 384x640 1 animal, 238.8ms
4: 384x640 1 animal, 238.8ms
5: 384x640 (no detections), 238.8ms
6: 384x640 (no detections), 238.8ms
7: 384x640 (no detections), 238.8ms
8: 384x640 (no detections), 238.8ms
9: 384x640 (no detections), 238.8ms
10: 384x640 (no detections), 238.8ms
11: 384x640 (no detections), 238.8ms
12: 384x640 1 animal, 238.8ms
13: 384x640 1 animal, 238.8ms
14: 384x640 1 animal, 238.8ms
15: 384x640 (no detections), 238.8ms
Speed: 1.8ms preprocess, 238.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 59/68 [05:08<00:42,  4.69s/it]

0: 384x640 (no detections), 240.1ms
1: 384x640 (no detections), 240.1ms
2: 384x640 (no detections), 240.1ms
3: 384x640 (no detections), 240.1ms
4: 384x640 (no detections), 240.1ms
5: 384x640 (no detections), 240.1ms
6: 384x640 1 animal, 240.1ms
7: 384x640 1 animal, 240.1ms
8: 384x640 1 animal, 240.1ms
9: 384x640 1 animal, 240.1ms
10: 384x640 1 animal, 240.1ms
11: 384x640 1 animal, 240.1ms
12: 384x640 (no detections), 240.1ms
13: 384x640 (no detections), 240.1ms
14: 384x640 (no detections), 240.1ms
15: 384x640 (no detections), 240.1ms
Speed: 1.7ms preprocess, 240.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 60/68 [05:13<00:37,  4.65s/it]

0: 384x640 1 animal, 239.7ms
1: 384x640 1 animal, 239.7ms
2: 384x640 1 animal, 239.7ms
3: 384x640 1 animal, 239.7ms
4: 384x640 1 animal, 239.7ms
5: 384x640 (no detections), 239.7ms
6: 384x640 (no detections), 239.7ms
7: 384x640 (no detections), 239.7ms
8: 384x640 (no detections), 239.7ms
9: 384x640 (no detections), 239.7ms
10: 384x640 1 animal, 239.7ms
11: 384x640 1 animal, 239.7ms
12: 384x640 1 animal, 239.7ms
13: 384x640 1 animal, 239.7ms
14: 384x640 1 animal, 239.7ms
15: 384x640 1 animal, 239.7ms
Speed: 1.7ms preprocess, 239.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 61/68 [05:17<00:32,  4.67s/it]

0: 384x640 2 animals, 241.0ms
1: 384x640 3 animals, 241.0ms
2: 384x640 1 animal, 241.0ms
3: 384x640 1 animal, 241.0ms
4: 384x640 1 animal, 241.0ms
5: 384x640 1 animal, 241.0ms
6: 384x640 1 animal, 241.0ms
7: 384x640 1 animal, 241.0ms
8: 384x640 1 animal, 241.0ms
9: 384x640 1 animal, 241.0ms
10: 384x640 2 animals, 241.0ms
11: 384x640 2 animals, 241.0ms
12: 384x640 2 animals, 241.0ms
13: 384x640 (no detections), 241.0ms
14: 384x640 1 animal, 241.0ms
15: 384x640 1 animal, 241.0ms
Speed: 2.0ms preprocess, 241.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 62/68 [05:22<00:28,  4.69s/it]

0: 384x640 1 animal, 242.5ms
1: 384x640 1 animal, 242.5ms
2: 384x640 (no detections), 242.5ms
3: 384x640 (no detections), 242.5ms
4: 384x640 (no detections), 242.5ms
5: 384x640 (no detections), 242.5ms
6: 384x640 (no detections), 242.5ms
7: 384x640 (no detections), 242.5ms
8: 384x640 1 animal, 242.5ms
9: 384x640 1 animal, 242.5ms
10: 384x640 1 animal, 242.5ms
11: 384x640 1 animal, 242.5ms
12: 384x640 (no detections), 242.5ms
13: 384x640 (no detections), 242.5ms
14: 384x640 (no detections), 242.5ms
15: 384x640 (no detections), 242.5ms
Speed: 1.8ms preprocess, 242.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 63/68 [05:27<00:23,  4.68s/it]

0: 384x640 (no detections), 243.9ms
1: 384x640 (no detections), 243.9ms
2: 384x640 1 animal, 243.9ms
3: 384x640 1 animal, 243.9ms
4: 384x640 1 animal, 243.9ms
5: 384x640 1 animal, 243.9ms
6: 384x640 1 animal, 243.9ms
7: 384x640 2 animals, 243.9ms
8: 384x640 (no detections), 243.9ms
9: 384x640 (no detections), 243.9ms
10: 384x640 (no detections), 243.9ms
11: 384x640 (no detections), 243.9ms
12: 384x640 1 animal, 243.9ms
13: 384x640 1 animal, 243.9ms
14: 384x640 1 animal, 243.9ms
15: 384x640 1 animal, 243.9ms
Speed: 1.8ms preprocess, 243.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 64/68 [05:31<00:18,  4.68s/it]

0: 384x640 1 animal, 240.5ms
1: 384x640 1 animal, 240.5ms
2: 384x640 1 animal, 240.5ms
3: 384x640 1 animal, 240.5ms
4: 384x640 1 animal, 240.5ms
5: 384x640 1 animal, 240.5ms
6: 384x640 1 animal, 240.5ms
7: 384x640 1 animal, 240.5ms
8: 384x640 1 animal, 240.5ms
9: 384x640 1 animal, 240.5ms
10: 384x640 1 animal, 240.5ms
11: 384x640 1 animal, 240.5ms
12: 384x640 1 animal, 240.5ms
13: 384x640 1 animal, 240.5ms
14: 384x640 1 animal, 240.5ms
15: 384x640 1 animal, 240.5ms
Speed: 1.8ms preprocess, 240.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 65/68 [05:36<00:13,  4.66s/it]

0: 384x640 2 animals, 239.4ms
1: 384x640 1 animal, 239.4ms
2: 384x640 1 animal, 239.4ms
3: 384x640 2 animals, 239.4ms
4: 384x640 1 animal, 239.4ms
5: 384x640 2 animals, 239.4ms
6: 384x640 1 animal, 239.4ms
7: 384x640 1 animal, 239.4ms
8: 384x640 1 animal, 239.4ms
9: 384x640 1 animal, 239.4ms
10: 384x640 1 animal, 239.4ms
11: 384x640 1 animal, 239.4ms
12: 384x640 1 animal, 239.4ms
13: 384x640 (no detections), 239.4ms
14: 384x640 (no detections), 239.4ms
15: 384x640 (no detections), 239.4ms
Speed: 1.7ms preprocess, 239.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 66/68 [05:41<00:09,  4.70s/it]

0: 384x640 (no detections), 232.7ms
1: 384x640 (no detections), 232.7ms
2: 384x640 (no detections), 232.7ms
3: 384x640 (no detections), 232.7ms
4: 384x640 1 animal, 232.7ms
5: 384x640 1 animal, 232.7ms
6: 384x640 1 animal, 232.7ms
7: 384x640 1 animal, 232.7ms
8: 384x640 2 animals, 232.7ms
9: 384x640 2 animals, 232.7ms
10: 384x640 2 animals, 232.7ms
11: 384x640 3 animals, 232.7ms
12: 384x640 1 animal, 232.7ms
13: 384x640 1 animal, 232.7ms
14: 384x640 1 animal, 232.7ms
15: 384x640 1 animal, 232.7ms
Speed: 1.7ms preprocess, 232.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 67/68 [05:45<00:04,  4.67s/it]

0: 384x640 1 animal, 206.0ms
1: 384x640 1 animal, 206.0ms
2: 384x640 1 animal, 206.0ms
3: 384x640 2 animals, 206.0ms
4: 384x640 2 animals, 206.0ms
5: 384x640 2 animals, 206.0ms
6: 384x640 1 animal, 206.0ms
7: 384x640 1 animal, 206.0ms
Speed: 1.6ms preprocess, 206.0ms inference, 0.4ms postprocess per image at shape (8, 3, 384, 640)

00%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 68/68 [05:48<00:00,  5.12s/it]

Detecting images from OTOSPERMOPHILUS_VERIEGATUS_extracted

  0%|                                                                                                                                                   | 0/3 [00:00<?, ?it/s]

0: 384x640 1 animal, 231.6ms
1: 384x640 2 animals, 231.6ms
2: 384x640 2 animals, 231.6ms
3: 384x640 2 animals, 231.6ms
4: 384x640 1 animal, 231.6ms
5: 384x640 1 animal, 231.6ms
6: 384x640 1 animal, 231.6ms
7: 384x640 1 animal, 231.6ms
8: 384x640 1 animal, 231.6ms
9: 384x640 1 animal, 231.6ms
10: 384x640 1 animal, 231.6ms
11: 384x640 1 animal, 231.6ms
12: 384x640 1 animal, 231.6ms
13: 384x640 1 animal, 231.6ms
14: 384x640 1 animal, 231.6ms
15: 384x640 2 animals, 231.6ms
Speed: 1.8ms preprocess, 231.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 33%|██████████████████████████████████████████████▎                                                                                            | 1/3 [00:04<00:09,  4.61s/it]

0: 640x640 1 animal, 390.1ms
1: 640x640 (no detections), 390.1ms
2: 640x640 (no detections), 390.1ms
3: 640x640 (no detections), 390.1ms
4: 640x640 1 animal, 390.1ms
5: 640x640 1 animal, 390.1ms
6: 640x640 2 animals, 390.1ms
7: 640x640 (no detections), 390.1ms
8: 640x640 (no detections), 390.1ms
9: 640x640 (no detections), 390.1ms
10: 640x640 (no detections), 390.1ms
11: 640x640 (no detections), 390.1ms
12: 640x640 (no detections), 390.1ms
13: 640x640 (no detections), 390.1ms
14: 640x640 1 animal, 390.1ms
15: 640x640 1 animal, 390.1ms
Speed: 2.5ms preprocess, 390.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 67%|████████████████████████████████████████████████████████████████████████████████████████████▋                                              | 2/3 [00:11<00:05,  5.94s/it]

0: 384x640 1 animal, 215.6ms
1: 384x640 1 animal, 215.6ms
2: 384x640 1 animal, 215.6ms
3: 384x640 1 animal, 215.6ms
4: 384x640 1 animal, 215.6ms
5: 384x640 (no detections), 215.6ms
6: 384x640 (no detections), 215.6ms
7: 384x640 (no detections), 215.6ms
Speed: 1.6ms preprocess, 215.6ms inference, 0.4ms postprocess per image at shape (8, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:13<00:00,  4.55s/it]

Detecting images from PUMA_CONCOLOR_2022_extracted

  0%|                                                                                                                                                  | 0/22 [00:00<?, ?it/s]

0: 384x640 1 animal, 233.0ms
1: 384x640 (no detections), 233.0ms
2: 384x640 1 animal, 233.0ms
3: 384x640 1 animal, 233.0ms
4: 384x640 1 animal, 233.0ms
5: 384x640 1 animal, 233.0ms
6: 384x640 1 animal, 233.0ms
7: 384x640 2 animals, 233.0ms
8: 384x640 (no detections), 233.0ms
9: 384x640 (no detections), 233.0ms
10: 384x640 1 animal, 233.0ms
11: 384x640 1 animal, 233.0ms
12: 384x640 1 animal, 233.0ms
13: 384x640 1 animal, 233.0ms
14: 384x640 1 animal, 233.0ms
15: 384x640 1 animal, 233.0ms
Speed: 1.7ms preprocess, 233.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  5%|██████▎                                                                                                                                   | 1/22 [00:04<01:33,  4.44s/it]

0: 640x640 1 animal, 388.8ms
1: 640x640 1 animal, 388.8ms
2: 640x640 1 animal, 388.8ms
3: 640x640 1 animal, 388.8ms
4: 640x640 1 animal, 388.8ms
5: 640x640 1 animal, 388.8ms
6: 640x640 1 animal, 388.8ms
7: 640x640 (no detections), 388.8ms
8: 640x640 (no detections), 388.8ms
9: 640x640 (no detections), 388.8ms
10: 640x640 (no detections), 388.8ms
11: 640x640 (no detections), 388.8ms
12: 640x640 (no detections), 388.8ms
13: 640x640 (no detections), 388.8ms
14: 640x640 2 animals, 388.8ms
15: 640x640 1 animal, 388.8ms
Speed: 2.4ms preprocess, 388.8ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  9%|████████████▌                                                                                                                             | 2/22 [00:11<01:55,  5.79s/it]

0: 384x640 1 animal, 231.8ms
1: 384x640 1 animal, 231.8ms
2: 384x640 (no detections), 231.8ms
3: 384x640 (no detections), 231.8ms
4: 384x640 (no detections), 231.8ms
5: 384x640 (no detections), 231.8ms
6: 384x640 (no detections), 231.8ms
7: 384x640 (no detections), 231.8ms
8: 384x640 1 animal, 231.8ms
9: 384x640 1 animal, 231.8ms
10: 384x640 1 animal, 231.8ms
11: 384x640 1 animal, 231.8ms
12: 384x640 (no detections), 231.8ms
13: 384x640 1 animal, 231.8ms
14: 384x640 1 animal, 231.8ms
15: 384x640 (no detections), 231.8ms
Speed: 1.7ms preprocess, 231.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 14%|██████████████████▊                                                                                                                       | 3/22 [00:15<01:38,  5.16s/it]

0: 640x640 (no detections), 387.3ms
1: 640x640 (no detections), 387.3ms
2: 640x640 2 animals, 387.3ms
3: 640x640 1 animal, 387.3ms
4: 640x640 1 animal, 387.3ms
5: 640x640 1 animal, 387.3ms
6: 640x640 (no detections), 387.3ms
7: 640x640 (no detections), 387.3ms
8: 640x640 (no detections), 387.3ms
9: 640x640 (no detections), 387.3ms
10: 640x640 (no detections), 387.3ms
11: 640x640 (no detections), 387.3ms
12: 640x640 1 animal, 387.3ms
13: 640x640 1 animal, 387.3ms
14: 640x640 1 animal, 387.3ms
15: 640x640 1 animal, 387.3ms
Speed: 2.5ms preprocess, 387.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 18%|█████████████████████████                                                                                                                 | 4/22 [00:22<01:44,  5.83s/it]

0: 640x640 1 animal, 396.5ms
1: 640x640 1 animal, 396.5ms
2: 640x640 1 animal, 396.5ms
3: 640x640 1 animal, 396.5ms
4: 640x640 1 animal, 396.5ms
5: 640x640 1 animal, 396.5ms
6: 640x640 1 animal, 396.5ms
7: 640x640 1 animal, 396.5ms
8: 640x640 1 animal, 396.5ms
9: 640x640 1 animal, 396.5ms
10: 640x640 1 animal, 396.5ms
11: 640x640 1 animal, 396.5ms
12: 640x640 2 animals, 396.5ms
13: 640x640 (no detections), 396.5ms
14: 640x640 1 animal, 396.5ms
15: 640x640 (no detections), 396.5ms
Speed: 2.9ms preprocess, 396.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 23%|███████████████████████████████▎                                                                                                          | 5/22 [00:29<01:46,  6.28s/it]

0: 384x640 1 animal, 236.3ms
1: 384x640 1 animal, 236.3ms
2: 384x640 1 animal, 236.3ms
3: 384x640 1 animal, 236.3ms
4: 384x640 1 animal, 236.3ms
5: 384x640 1 animal, 236.3ms
6: 384x640 2 animals, 236.3ms
7: 384x640 (no detections), 236.3ms
8: 384x640 1 animal, 236.3ms
9: 384x640 1 animal, 236.3ms
10: 384x640 1 animal, 236.3ms
11: 384x640 1 animal, 236.3ms
12: 384x640 1 animal, 236.3ms
13: 384x640 1 animal, 236.3ms
14: 384x640 1 animal, 236.3ms
15: 384x640 1 animal, 236.3ms
Speed: 1.7ms preprocess, 236.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 27%|█████████████████████████████████████▋                                                                                                    | 6/22 [00:34<01:31,  5.73s/it]

0: 640x640 1 animal, 395.8ms
1: 640x640 1 animal, 395.8ms
2: 640x640 1 animal, 395.8ms
3: 640x640 1 animal, 395.8ms
4: 640x640 1 animal, 395.8ms
5: 640x640 1 animal, 395.8ms
6: 640x640 1 animal, 395.8ms
7: 640x640 (no detections), 395.8ms
8: 640x640 (no detections), 395.8ms
9: 640x640 (no detections), 395.8ms
10: 640x640 (no detections), 395.8ms
11: 640x640 (no detections), 395.8ms
12: 640x640 (no detections), 395.8ms
13: 640x640 (no detections), 395.8ms
14: 640x640 1 animal, 395.8ms
15: 640x640 1 animal, 395.8ms
Speed: 2.5ms preprocess, 395.8ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 32%|███████████████████████████████████████████▉                                                                                              | 7/22 [00:41<01:31,  6.12s/it]

0: 384x640 1 animal, 238.7ms
1: 384x640 1 animal, 238.7ms
2: 384x640 1 animal, 238.7ms
3: 384x640 1 animal, 238.7ms
4: 384x640 1 animal, 238.7ms
5: 384x640 1 animal, 238.7ms
6: 384x640 1 animal, 238.7ms
7: 384x640 (no detections), 238.7ms
8: 384x640 1 animal, 238.7ms
9: 384x640 1 animal, 238.7ms
10: 384x640 1 animal, 238.7ms
11: 384x640 1 animal, 238.7ms
12: 384x640 1 animal, 238.7ms
13: 384x640 1 animal, 238.7ms
14: 384x640 1 animal, 238.7ms
15: 384x640 1 animal, 238.7ms
Speed: 1.8ms preprocess, 238.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 36%|██████████████████████████████████████████████████▏                                                                                       | 8/22 [00:45<01:18,  5.62s/it]

0: 384x640 1 animal, 241.2ms
1: 384x640 1 animal, 241.2ms
2: 384x640 1 animal, 241.2ms
3: 384x640 1 animal, 241.2ms
4: 384x640 1 animal, 241.2ms
5: 384x640 1 animal, 241.2ms
6: 384x640 1 animal, 241.2ms
7: 384x640 1 animal, 241.2ms
8: 384x640 (no detections), 241.2ms
9: 384x640 (no detections), 241.2ms
10: 384x640 (no detections), 241.2ms
11: 384x640 (no detections), 241.2ms
12: 384x640 1 animal, 241.2ms
13: 384x640 1 animal, 241.2ms
14: 384x640 1 animal, 241.2ms
15: 384x640 1 animal, 241.2ms
Speed: 1.8ms preprocess, 241.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 41%|████████████████████████████████████████████████████████▍                                                                                 | 9/22 [00:50<01:09,  5.31s/it]

0: 384x640 1 animal, 241.2ms
1: 384x640 1 animal, 241.2ms
2: 384x640 1 animal, 241.2ms
3: 384x640 1 animal, 241.2ms
4: 384x640 1 animal, 241.2ms
5: 384x640 1 animal, 241.2ms
6: 384x640 1 animal, 241.2ms
7: 384x640 1 animal, 241.2ms
8: 384x640 1 animal, 241.2ms
9: 384x640 1 animal, 241.2ms
10: 384x640 1 animal, 241.2ms
11: 384x640 1 animal, 241.2ms
12: 384x640 1 animal, 241.2ms
13: 384x640 1 animal, 241.2ms
14: 384x640 1 animal, 241.2ms
15: 384x640 1 animal, 241.2ms
Speed: 1.7ms preprocess, 241.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 45%|██████████████████████████████████████████████████████████████▎                                                                          | 10/22 [00:55<01:01,  5.13s/it]

0: 384x640 1 animal, 241.1ms
1: 384x640 1 animal, 241.1ms
2: 384x640 2 animals, 241.1ms
3: 384x640 (no detections), 241.1ms
4: 384x640 (no detections), 241.1ms
5: 384x640 (no detections), 241.1ms
6: 384x640 (no detections), 241.1ms
7: 384x640 (no detections), 241.1ms
8: 384x640 (no detections), 241.1ms
9: 384x640 (no detections), 241.1ms
10: 384x640 1 animal, 241.1ms
11: 384x640 1 animal, 241.1ms
12: 384x640 1 animal, 241.1ms
13: 384x640 1 animal, 241.1ms
14: 384x640 1 animal, 241.1ms
15: 384x640 1 animal, 241.1ms
Speed: 2.1ms preprocess, 241.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 50%|████████████████████████████████████████████████████████████████████▌                                                                    | 11/22 [00:59<00:55,  5.02s/it]

0: 384x640 1 animal, 237.0ms
1: 384x640 1 animal, 237.0ms
2: 384x640 1 animal, 237.0ms
3: 384x640 1 animal, 237.0ms
4: 384x640 (no detections), 237.0ms
5: 384x640 1 animal, 237.0ms
6: 384x640 1 animal, 237.0ms
7: 384x640 1 animal, 237.0ms
8: 384x640 1 animal, 237.0ms
9: 384x640 1 animal, 237.0ms
10: 384x640 1 animal, 237.0ms
11: 384x640 (no detections), 237.0ms
12: 384x640 (no detections), 237.0ms
13: 384x640 (no detections), 237.0ms
14: 384x640 (no detections), 237.0ms
15: 384x640 1 animal, 237.0ms
Speed: 1.8ms preprocess, 237.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 55%|██████████████████████████████████████████████████████████████████████████▋                                                              | 12/22 [01:04<00:49,  4.92s/it]

0: 384x640 1 animal, 240.0ms
1: 384x640 1 animal, 240.0ms
2: 384x640 1 animal, 240.0ms
3: 384x640 1 animal, 240.0ms
4: 384x640 1 animal, 240.0ms
5: 384x640 1 animal, 240.0ms
6: 384x640 1 animal, 240.0ms
7: 384x640 1 animal, 240.0ms
8: 384x640 1 animal, 240.0ms
9: 384x640 1 animal, 240.0ms
10: 384x640 1 animal, 240.0ms
11: 384x640 1 animal, 240.0ms
12: 384x640 1 animal, 240.0ms
13: 384x640 1 animal, 240.0ms
14: 384x640 1 animal, 240.0ms
15: 384x640 1 animal, 240.0ms
Speed: 1.8ms preprocess, 240.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 59%|████████████████████████████████████████████████████████████████████████████████▉                                                        | 13/22 [01:09<00:43,  4.83s/it]

0: 384x640 1 animal, 240.7ms
1: 384x640 1 animal, 240.7ms
2: 384x640 1 animal, 240.7ms
3: 384x640 1 animal, 240.7ms
4: 384x640 1 animal, 240.7ms
5: 384x640 1 animal, 240.7ms
6: 384x640 1 animal, 240.7ms
7: 384x640 1 animal, 240.7ms
8: 384x640 1 animal, 240.7ms
9: 384x640 1 animal, 240.7ms
10: 384x640 1 animal, 240.7ms
11: 384x640 (no detections), 240.7ms
12: 384x640 1 animal, 240.7ms
13: 384x640 1 animal, 240.7ms
14: 384x640 1 animal, 240.7ms
15: 384x640 1 animal, 240.7ms
Speed: 1.8ms preprocess, 240.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 64%|███████████████████████████████████████████████████████████████████████████████████████▏                                                 | 14/22 [01:13<00:38,  4.77s/it]

0: 384x640 1 animal, 240.3ms
1: 384x640 1 animal, 240.3ms
2: 384x640 1 animal, 240.3ms
3: 384x640 1 animal, 240.3ms
4: 384x640 1 animal, 240.3ms
5: 384x640 (no detections), 240.3ms
6: 384x640 1 animal, 240.3ms
7: 384x640 1 animal, 240.3ms
8: 384x640 1 animal, 240.3ms
9: 384x640 1 animal, 240.3ms
10: 384x640 1 animal, 240.3ms
11: 384x640 1 animal, 240.3ms
12: 384x640 1 animal, 240.3ms
13: 384x640 1 animal, 240.3ms
14: 384x640 1 animal, 240.3ms
15: 384x640 1 animal, 240.3ms
Speed: 1.9ms preprocess, 240.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                           | 15/22 [01:18<00:33,  4.74s/it]

0: 384x640 1 animal, 240.6ms
1: 384x640 1 animal, 240.6ms
2: 384x640 2 animals, 240.6ms
3: 384x640 2 animals, 240.6ms
4: 384x640 1 animal, 240.6ms
5: 384x640 1 animal, 240.6ms
6: 384x640 (no detections), 240.6ms
7: 384x640 (no detections), 240.6ms
8: 384x640 (no detections), 240.6ms
9: 384x640 (no detections), 240.6ms
10: 384x640 (no detections), 240.6ms
11: 384x640 1 animal, 240.6ms
12: 384x640 1 animal, 240.6ms
13: 384x640 1 animal, 240.6ms
14: 384x640 1 animal, 240.6ms
15: 384x640 2 animals, 240.6ms
Speed: 1.7ms preprocess, 240.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 16/22 [01:23<00:28,  4.73s/it]

0: 384x640 1 animal, 238.2ms
1: 384x640 1 animal, 238.2ms
2: 384x640 2 animals, 238.2ms
3: 384x640 (no detections), 238.2ms
4: 384x640 1 animal, 238.2ms
5: 384x640 1 animal, 238.2ms
6: 384x640 1 animal, 238.2ms
7: 384x640 1 animal, 238.2ms
8: 384x640 1 animal, 238.2ms
9: 384x640 1 animal, 238.2ms
10: 384x640 1 animal, 238.2ms
11: 384x640 (no detections), 238.2ms
12: 384x640 (no detections), 238.2ms
13: 384x640 (no detections), 238.2ms
14: 384x640 1 animal, 238.2ms
15: 384x640 1 animal, 238.2ms
Speed: 1.8ms preprocess, 238.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 17/22 [01:27<00:23,  4.70s/it]

0: 384x640 1 animal, 238.2ms
1: 384x640 1 animal, 238.2ms
2: 384x640 1 animal, 238.2ms
3: 384x640 1 animal, 238.2ms
4: 384x640 1 animal, 238.2ms
5: 384x640 1 animal, 238.2ms
6: 384x640 1 animal, 238.2ms
7: 384x640 (no detections), 238.2ms
8: 384x640 1 animal, 238.2ms
9: 384x640 1 animal, 238.2ms
10: 384x640 1 animal, 238.2ms
11: 384x640 1 animal, 238.2ms
12: 384x640 1 animal, 238.2ms
13: 384x640 1 animal, 238.2ms
14: 384x640 1 animal, 238.2ms
15: 384x640 1 animal, 238.2ms
Speed: 2.0ms preprocess, 238.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 18/22 [01:32<00:18,  4.66s/it]

0: 640x640 1 animal, 390.7ms
1: 640x640 1 animal, 390.7ms
2: 640x640 1 animal, 390.7ms
3: 640x640 1 animal, 390.7ms
4: 640x640 1 animal, 390.7ms
5: 640x640 1 animal, 390.7ms
6: 640x640 2 animals, 390.7ms
7: 640x640 (no detections), 390.7ms
8: 640x640 (no detections), 390.7ms
9: 640x640 (no detections), 390.7ms
10: 640x640 (no detections), 390.7ms
11: 640x640 (no detections), 390.7ms
12: 640x640 1 animal, 390.7ms
13: 640x640 1 animal, 390.7ms
14: 640x640 1 animal, 390.7ms
15: 640x640 1 animal, 390.7ms
Speed: 2.5ms preprocess, 390.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 19/22 [01:39<00:15,  5.28s/it]

0: 640x640 1 animal, 400.5ms
1: 640x640 1 animal, 400.5ms
2: 640x640 (no detections), 400.5ms
3: 640x640 (no detections), 400.5ms
4: 640x640 (no detections), 400.5ms
5: 640x640 (no detections), 400.5ms
6: 640x640 1 animal, 400.5ms
7: 640x640 1 animal, 400.5ms
8: 640x640 1 animal, 400.5ms
9: 640x640 1 animal, 400.5ms
10: 640x640 (no detections), 400.5ms
11: 640x640 (no detections), 400.5ms
12: 640x640 (no detections), 400.5ms
13: 640x640 (no detections), 400.5ms
14: 640x640 (no detections), 400.5ms
15: 640x640 (no detections), 400.5ms
Speed: 2.6ms preprocess, 400.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 20/22 [01:46<00:11,  5.81s/it]

0: 384x640 1 animal, 240.3ms
1: 384x640 1 animal, 240.3ms
2: 384x640 1 animal, 240.3ms
3: 384x640 (no detections), 240.3ms
4: 384x640 (no detections), 240.3ms
5: 384x640 (no detections), 240.3ms
6: 384x640 (no detections), 240.3ms
7: 384x640 (no detections), 240.3ms
8: 384x640 (no detections), 240.3ms
9: 384x640 (no detections), 240.3ms
10: 384x640 1 animal, 240.3ms
11: 384x640 1 animal, 240.3ms
12: 384x640 1 animal, 240.3ms
13: 384x640 1 animal, 240.3ms
14: 384x640 1 animal, 240.3ms
15: 384x640 1 animal, 240.3ms
Speed: 1.8ms preprocess, 240.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 21/22 [01:50<00:05,  5.46s/it]

0: 384x640 1 animal, 231.1ms
1: 384x640 1 animal, 231.1ms
2: 384x640 1 animal, 231.1ms
3: 384x640 1 animal, 231.1ms
4: 384x640 1 animal, 231.1ms
5: 384x640 1 animal, 231.1ms
6: 384x640 1 animal, 231.1ms
7: 384x640 1 animal, 231.1ms
8: 384x640 1 animal, 231.1ms
9: 384x640 1 animal, 231.1ms
10: 384x640 1 animal, 231.1ms
11: 384x640 1 animal, 231.1ms
12: 384x640 1 animal, 231.1ms
13: 384x640 1 animal, 231.1ms
Speed: 1.7ms preprocess, 231.1ms inference, 0.4ms postprocess per image at shape (14, 3, 384, 640)

00%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [01:54<00:00,  5.21s/it]

Detecting images from AVES_2022_extracted

  0%|                                                                                                                                                 | 0/182 [00:00<?, ?it/s]

0: 640x640 (no detections), 404.4ms
1: 640x640 (no detections), 404.4ms
2: 640x640 1 person, 404.4ms
3: 640x640 1 person, 404.4ms
4: 640x640 (no detections), 404.4ms
5: 640x640 1 person, 404.4ms
6: 640x640 1 person, 404.4ms
7: 640x640 1 person, 404.4ms
8: 640x640 (no detections), 404.4ms
9: 640x640 (no detections), 404.4ms
10: 640x640 2 animals, 404.4ms
11: 640x640 1 animal, 404.4ms
12: 640x640 1 animal, 404.4ms
13: 640x640 1 animal, 404.4ms
14: 640x640 (no detections), 404.4ms
15: 640x640 (no detections), 404.4ms
Speed: 2.6ms preprocess, 404.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  1%|▊                                                                                                                                        | 1/182 [00:07<21:36,  7.16s/it]

0: 640x640 1 animal, 402.5ms
1: 640x640 (no detections), 402.5ms
2: 640x640 (no detections), 402.5ms
3: 640x640 (no detections), 402.5ms
4: 640x640 1 animal, 402.5ms
5: 640x640 1 animal, 402.5ms
6: 640x640 1 animal, 402.5ms
7: 640x640 1 animal, 402.5ms
8: 640x640 1 animal, 402.5ms
9: 640x640 1 animal, 402.5ms
10: 640x640 1 animal, 402.5ms
11: 640x640 1 animal, 402.5ms
12: 640x640 1 animal, 402.5ms
13: 640x640 1 animal, 402.5ms
14: 640x640 1 animal, 402.5ms
15: 640x640 1 animal, 402.5ms
Speed: 2.8ms preprocess, 402.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  1%|█▌                                                                                                                                       | 2/182 [00:14<21:36,  7.20s/it]

0: 384x640 1 animal, 240.6ms
1: 384x640 1 animal, 240.6ms
2: 384x640 1 animal, 240.6ms
3: 384x640 1 animal, 240.6ms
4: 384x640 1 animal, 240.6ms
5: 384x640 1 animal, 240.6ms
6: 384x640 1 animal, 240.6ms
7: 384x640 2 animals, 240.6ms
8: 384x640 1 animal, 240.6ms
9: 384x640 1 animal, 240.6ms
10: 384x640 1 animal, 240.6ms
11: 384x640 1 animal, 240.6ms
12: 384x640 1 animal, 240.6ms
13: 384x640 1 animal, 240.6ms
14: 384x640 (no detections), 240.6ms
15: 384x640 1 animal, 240.6ms
Speed: 1.7ms preprocess, 240.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  2%|██▎                                                                                                                                      | 3/182 [00:19<18:05,  6.06s/it]

0: 640x640 1 animal, 399.7ms
1: 640x640 1 animal, 399.7ms
2: 640x640 1 animal, 399.7ms
3: 640x640 1 animal, 399.7ms
4: 640x640 1 animal, 399.7ms
5: 640x640 1 animal, 399.7ms
6: 640x640 1 animal, 399.7ms
7: 640x640 1 animal, 399.7ms
8: 640x640 2 animals, 399.7ms
9: 640x640 1 animal, 399.7ms
10: 640x640 1 animal, 399.7ms
11: 640x640 1 animal, 399.7ms
12: 640x640 (no detections), 399.7ms
13: 640x640 (no detections), 399.7ms
14: 640x640 (no detections), 399.7ms
15: 640x640 (no detections), 399.7ms
Speed: 2.5ms preprocess, 399.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  2%|███                                                                                                                                      | 4/182 [00:26<19:04,  6.43s/it]

0: 384x640 (no detections), 240.3ms
1: 384x640 (no detections), 240.3ms
2: 384x640 (no detections), 240.3ms
3: 384x640 (no detections), 240.3ms
4: 384x640 (no detections), 240.3ms
5: 384x640 (no detections), 240.3ms
6: 384x640 1 animal, 240.3ms
7: 384x640 1 animal, 240.3ms
8: 384x640 1 animal, 240.3ms
9: 384x640 1 animal, 240.3ms
10: 384x640 1 animal, 240.3ms
11: 384x640 1 animal, 240.3ms
12: 384x640 1 animal, 240.3ms
13: 384x640 1 animal, 240.3ms
14: 384x640 1 animal, 240.3ms
15: 384x640 1 animal, 240.3ms
Speed: 1.7ms preprocess, 240.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  3%|███▊                                                                                                                                     | 5/182 [00:30<17:09,  5.81s/it]

0: 384x640 1 animal, 245.5ms
1: 384x640 1 animal, 245.5ms
2: 384x640 1 animal, 245.5ms
3: 384x640 1 animal, 245.5ms
4: 384x640 1 animal, 245.5ms
5: 384x640 1 animal, 245.5ms
6: 384x640 (no detections), 245.5ms
7: 384x640 (no detections), 245.5ms
8: 384x640 1 animal, 245.5ms
9: 384x640 (no detections), 245.5ms
10: 384x640 1 animal, 245.5ms
11: 384x640 1 animal, 245.5ms
12: 384x640 1 animal, 245.5ms
13: 384x640 1 animal, 245.5ms
14: 384x640 1 animal, 245.5ms
15: 384x640 1 animal, 245.5ms
Speed: 1.8ms preprocess, 245.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  3%|████▌                                                                                                                                    | 6/182 [00:35<16:03,  5.47s/it]

0: 640x640 1 animal, 403.5ms
1: 640x640 1 animal, 403.5ms
2: 640x640 1 animal, 403.5ms
3: 640x640 1 animal, 403.5ms
4: 640x640 2 animals, 403.5ms
5: 640x640 2 animals, 403.5ms
6: 640x640 2 animals, 403.5ms
7: 640x640 2 animals, 403.5ms
8: 640x640 2 animals, 403.5ms
9: 640x640 2 animals, 403.5ms
10: 640x640 2 animals, 403.5ms
11: 640x640 1 animal, 403.5ms
12: 640x640 1 animal, 403.5ms
13: 640x640 1 animal, 403.5ms
14: 640x640 1 animal, 403.5ms
15: 640x640 1 animal, 403.5ms
Speed: 2.6ms preprocess, 403.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  4%|█████▎                                                                                                                                   | 7/182 [00:42<17:31,  6.01s/it]

0: 384x640 1 animal, 241.4ms
1: 384x640 2 animals, 241.4ms
2: 384x640 1 animal, 241.4ms
3: 384x640 1 animal, 241.4ms
4: 384x640 1 animal, 241.4ms
5: 384x640 (no detections), 241.4ms
6: 384x640 (no detections), 241.4ms
7: 384x640 (no detections), 241.4ms
8: 384x640 1 animal, 241.4ms
9: 384x640 1 animal, 241.4ms
10: 384x640 1 animal, 241.4ms
11: 384x640 1 animal, 241.4ms
12: 384x640 1 animal, 241.4ms
13: 384x640 1 animal, 241.4ms
14: 384x640 1 animal, 241.4ms
15: 384x640 1 animal, 241.4ms
Speed: 2.1ms preprocess, 241.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  4%|██████                                                                                                                                   | 8/182 [00:47<16:17,  5.62s/it]

0: 384x640 1 animal, 242.2ms
1: 384x640 1 animal, 242.2ms
2: 384x640 1 animal, 242.2ms
3: 384x640 1 animal, 242.2ms
4: 384x640 (no detections), 242.2ms
5: 384x640 1 animal, 242.2ms
6: 384x640 1 animal, 242.2ms
7: 384x640 1 animal, 242.2ms
8: 384x640 1 animal, 242.2ms
9: 384x640 1 animal, 242.2ms
10: 384x640 1 animal, 242.2ms
11: 384x640 1 animal, 242.2ms
12: 384x640 3 animals, 242.2ms
13: 384x640 1 animal, 242.2ms
14: 384x640 2 animals, 242.2ms
15: 384x640 2 animals, 242.2ms
Speed: 1.9ms preprocess, 242.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  5%|██████▊                                                                                                                                  | 9/182 [00:52<15:27,  5.36s/it]

0: 384x640 3 animals, 245.8ms
1: 384x640 1 animal, 245.8ms
2: 384x640 1 animal, 245.8ms
3: 384x640 1 animal, 245.8ms
4: 384x640 1 animal, 245.8ms
5: 384x640 1 animal, 245.8ms
6: 384x640 1 animal, 245.8ms
7: 384x640 1 animal, 245.8ms
8: 384x640 1 animal, 245.8ms
9: 384x640 1 animal, 245.8ms
10: 384x640 1 animal, 245.8ms
11: 384x640 1 animal, 245.8ms
12: 384x640 1 animal, 245.8ms
13: 384x640 1 animal, 245.8ms
14: 384x640 1 animal, 245.8ms
15: 384x640 1 animal, 245.8ms
Speed: 1.8ms preprocess, 245.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  5%|███████▍                                                                                                                                | 10/182 [00:57<14:54,  5.20s/it]

0: 640x640 (no detections), 393.0ms
1: 640x640 1 animal, 393.0ms
2: 640x640 1 animal, 393.0ms
3: 640x640 1 animal, 393.0ms
4: 640x640 1 animal, 393.0ms
5: 640x640 1 animal, 393.0ms
6: 640x640 (no detections), 393.0ms
7: 640x640 (no detections), 393.0ms
8: 640x640 (no detections), 393.0ms
9: 640x640 (no detections), 393.0ms
10: 640x640 1 animal, 393.0ms
11: 640x640 1 animal, 393.0ms
12: 640x640 1 animal, 393.0ms
13: 640x640 1 animal, 393.0ms
14: 640x640 1 animal, 393.0ms
15: 640x640 (no detections), 393.0ms
Speed: 2.7ms preprocess, 393.0ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  6%|████████▏                                                                                                                               | 11/182 [01:04<16:28,  5.78s/it]

0: 640x640 (no detections), 402.5ms
1: 640x640 (no detections), 402.5ms
2: 640x640 (no detections), 402.5ms
3: 640x640 (no detections), 402.5ms
4: 640x640 (no detections), 402.5ms
5: 640x640 (no detections), 402.5ms
6: 640x640 (no detections), 402.5ms
7: 640x640 1 animal, 402.5ms
8: 640x640 (no detections), 402.5ms
9: 640x640 (no detections), 402.5ms
10: 640x640 (no detections), 402.5ms
11: 640x640 (no detections), 402.5ms
12: 640x640 (no detections), 402.5ms
13: 640x640 (no detections), 402.5ms
14: 640x640 1 animal, 402.5ms
15: 640x640 1 animal, 402.5ms
Speed: 2.7ms preprocess, 402.5ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

  7%|████████▉                                                                                                                               | 12/182 [01:11<17:37,  6.22s/it]

0: 384x640 1 animal, 240.4ms
1: 384x640 1 animal, 240.4ms
2: 384x640 1 animal, 240.4ms
3: 384x640 1 animal, 240.4ms
4: 384x640 1 animal, 240.4ms
5: 384x640 1 animal, 240.4ms
6: 384x640 1 animal, 240.4ms
7: 384x640 1 animal, 240.4ms
8: 384x640 (no detections), 240.4ms
9: 384x640 (no detections), 240.4ms
10: 384x640 (no detections), 240.4ms
11: 384x640 (no detections), 240.4ms
12: 384x640 (no detections), 240.4ms
13: 384x640 (no detections), 240.4ms
14: 384x640 1 animal, 240.4ms
15: 384x640 (no detections), 240.4ms
Speed: 1.9ms preprocess, 240.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  7%|█████████▋                                                                                                                              | 13/182 [01:16<16:16,  5.78s/it]

0: 640x640 (no detections), 401.0ms
1: 640x640 (no detections), 401.0ms
2: 640x640 (no detections), 401.0ms
3: 640x640 (no detections), 401.0ms
4: 640x640 (no detections), 401.0ms
5: 640x640 (no detections), 401.0ms
6: 640x640 (no detections), 401.0ms
7: 640x640 (no detections), 401.0ms
8: 640x640 (no detections), 401.0ms
9: 640x640 (no detections), 401.0ms
10: 640x640 (no detections), 401.0ms
11: 640x640 (no detections), 401.0ms
12: 640x640 1 animal, 401.0ms
13: 640x640 1 animal, 401.0ms
14: 640x640 (no detections), 401.0ms
15: 640x640 (no detections), 401.0ms
Speed: 2.6ms preprocess, 401.0ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

  8%|██████████▍                                                                                                                             | 14/182 [01:23<17:24,  6.22s/it]

0: 640x640 (no detections), 401.4ms
1: 640x640 (no detections), 401.4ms
2: 640x640 (no detections), 401.4ms
3: 640x640 (no detections), 401.4ms
4: 640x640 (no detections), 401.4ms
5: 640x640 (no detections), 401.4ms
6: 640x640 1 animal, 401.4ms
7: 640x640 1 animal, 401.4ms
8: 640x640 1 animal, 401.4ms
9: 640x640 1 animal, 401.4ms
10: 640x640 1 animal, 401.4ms
11: 640x640 1 animal, 401.4ms
12: 640x640 1 animal, 401.4ms
13: 640x640 1 animal, 401.4ms
14: 640x640 1 animal, 401.4ms
15: 640x640 1 animal, 401.4ms
Speed: 2.8ms preprocess, 401.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  8%|███████████▏                                                                                                                            | 15/182 [01:30<18:04,  6.50s/it]

0: 384x640 1 animal, 238.8ms
1: 384x640 1 animal, 238.8ms
2: 384x640 1 animal, 238.8ms
3: 384x640 2 animals, 238.8ms
4: 384x640 (no detections), 238.8ms
5: 384x640 (no detections), 238.8ms
6: 384x640 (no detections), 238.8ms
7: 384x640 (no detections), 238.8ms
8: 384x640 (no detections), 238.8ms
9: 384x640 (no detections), 238.8ms
10: 384x640 1 animal, 238.8ms
11: 384x640 1 animal, 238.8ms
12: 384x640 1 animal, 238.8ms
13: 384x640 1 animal, 238.8ms
14: 384x640 1 animal, 238.8ms
15: 384x640 1 animal, 238.8ms
Speed: 1.7ms preprocess, 238.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  9%|███████████▉                                                                                                                            | 16/182 [01:35<16:29,  5.96s/it]

0: 640x640 3 animals, 402.4ms
1: 640x640 1 animal, 402.4ms
2: 640x640 1 animal, 402.4ms
3: 640x640 1 animal, 402.4ms
4: 640x640 (no detections), 402.4ms
5: 640x640 (no detections), 402.4ms
6: 640x640 (no detections), 402.4ms
7: 640x640 (no detections), 402.4ms
8: 640x640 (no detections), 402.4ms
9: 640x640 (no detections), 402.4ms
10: 640x640 (no detections), 402.4ms
11: 640x640 (no detections), 402.4ms
12: 640x640 (no detections), 402.4ms
13: 640x640 (no detections), 402.4ms
14: 640x640 1 animal, 402.4ms
15: 640x640 1 animal, 402.4ms
Speed: 2.6ms preprocess, 402.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  9%|████████████▋                                                                                                                           | 17/182 [01:42<17:28,  6.36s/it]

0: 640x640 1 animal, 402.8ms
1: 640x640 1 animal, 402.8ms
2: 640x640 1 animal, 402.8ms
3: 640x640 1 animal, 402.8ms
4: 640x640 1 animal, 402.8ms
5: 640x640 (no detections), 402.8ms
6: 640x640 (no detections), 402.8ms
7: 640x640 (no detections), 402.8ms
8: 640x640 1 animal, 402.8ms
9: 640x640 2 animals, 402.8ms
10: 640x640 1 animal, 402.8ms
11: 640x640 1 animal, 402.8ms
12: 640x640 1 animal, 402.8ms
13: 640x640 1 animal, 402.8ms
14: 640x640 1 animal, 402.8ms
15: 640x640 1 animal, 402.8ms
Speed: 2.7ms preprocess, 402.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 10%|█████████████▍                                                                                                                          | 18/182 [01:49<18:00,  6.59s/it]

0: 640x640 1 animal, 399.5ms
1: 640x640 1 animal, 399.5ms
2: 640x640 1 animal, 399.5ms
3: 640x640 1 animal, 399.5ms
4: 640x640 1 animal, 399.5ms
5: 640x640 1 animal, 399.5ms
6: 640x640 1 animal, 399.5ms
7: 640x640 1 animal, 399.5ms
8: 640x640 (no detections), 399.5ms
9: 640x640 2 animals, 399.5ms
10: 640x640 1 animal, 399.5ms
11: 640x640 1 animal, 399.5ms
12: 640x640 1 animal, 399.5ms
13: 640x640 1 animal, 399.5ms
14: 640x640 1 animal, 399.5ms
15: 640x640 1 animal, 399.5ms
Speed: 2.8ms preprocess, 399.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 10%|██████████████▏                                                                                                                         | 19/182 [01:56<18:14,  6.72s/it]

0: 640x640 1 animal, 397.4ms
1: 640x640 1 animal, 397.4ms
2: 640x640 1 animal, 397.4ms
3: 640x640 1 animal, 397.4ms
4: 640x640 1 animal, 397.4ms
5: 640x640 1 animal, 397.4ms
6: 640x640 2 animals, 397.4ms
7: 640x640 2 animals, 397.4ms
8: 640x640 1 animal, 397.4ms
9: 640x640 2 animals, 397.4ms
10: 640x640 1 animal, 397.4ms
11: 640x640 2 animals, 397.4ms
12: 640x640 2 animals, 397.4ms
13: 640x640 2 animals, 397.4ms
14: 640x640 2 animals, 397.4ms
15: 640x640 1 animal, 397.4ms
Speed: 2.7ms preprocess, 397.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 11%|██████████████▉                                                                                                                         | 20/182 [02:03<18:19,  6.79s/it]

0: 640x640 1 animal, 401.8ms
1: 640x640 1 animal, 401.8ms
2: 640x640 1 animal, 401.8ms
3: 640x640 1 animal, 401.8ms
4: 640x640 1 animal, 401.8ms
5: 640x640 1 animal, 401.8ms
6: 640x640 1 animal, 401.8ms
7: 640x640 1 animal, 401.8ms
8: 640x640 1 animal, 401.8ms
9: 640x640 1 animal, 401.8ms
10: 640x640 1 animal, 401.8ms
11: 640x640 1 animal, 401.8ms
12: 640x640 1 animal, 401.8ms
13: 640x640 (no detections), 401.8ms
14: 640x640 (no detections), 401.8ms
15: 640x640 (no detections), 401.8ms
Speed: 2.8ms preprocess, 401.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 12%|███████████████▋                                                                                                                        | 21/182 [02:10<18:33,  6.91s/it]

0: 640x640 (no detections), 401.1ms
1: 640x640 (no detections), 401.1ms
2: 640x640 (no detections), 401.1ms
3: 640x640 (no detections), 401.1ms
4: 640x640 (no detections), 401.1ms
5: 640x640 (no detections), 401.1ms
6: 640x640 (no detections), 401.1ms
7: 640x640 1 animal, 401.1ms
8: 640x640 1 animal, 401.1ms
9: 640x640 1 animal, 401.1ms
10: 640x640 1 animal, 401.1ms
11: 640x640 1 animal, 401.1ms
12: 640x640 1 animal, 401.1ms
13: 640x640 1 animal, 401.1ms
14: 640x640 1 animal, 401.1ms
15: 640x640 1 animal, 401.1ms
Speed: 2.7ms preprocess, 401.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 12%|████████████████▍                                                                                                                       | 22/182 [02:18<18:40,  7.00s/it]

0: 384x640 1 animal, 239.9ms
1: 384x640 1 animal, 239.9ms
2: 384x640 2 animals, 239.9ms
3: 384x640 1 animal, 239.9ms
4: 384x640 1 animal, 239.9ms
5: 384x640 1 animal, 239.9ms
6: 384x640 (no detections), 239.9ms
7: 384x640 1 animal, 239.9ms
8: 384x640 1 animal, 239.9ms
9: 384x640 1 animal, 239.9ms
10: 384x640 (no detections), 239.9ms
11: 384x640 (no detections), 239.9ms
12: 384x640 (no detections), 239.9ms
13: 384x640 (no detections), 239.9ms
14: 384x640 (no detections), 239.9ms
15: 384x640 (no detections), 239.9ms
Speed: 1.7ms preprocess, 239.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 13%|█████████████████▏                                                                                                                      | 23/182 [02:22<16:45,  6.33s/it]

0: 384x640 (no detections), 239.5ms
1: 384x640 (no detections), 239.5ms
2: 384x640 3 animals, 239.5ms
3: 384x640 3 animals, 239.5ms
4: 384x640 1 animal, 1 person, 239.5ms
5: 384x640 3 animals, 239.5ms
6: 384x640 2 animals, 239.5ms
7: 384x640 2 animals, 239.5ms
8: 384x640 1 animal, 239.5ms
9: 384x640 1 animal, 1 person, 239.5ms
10: 384x640 2 animals, 1 person, 239.5ms
11: 384x640 1 animal, 1 person, 239.5ms
12: 384x640 (no detections), 239.5ms
13: 384x640 (no detections), 239.5ms
14: 384x640 1 animal, 239.5ms
15: 384x640 1 animal, 239.5ms
Speed: 2.0ms preprocess, 239.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 13%|█████████████████▉                                                                                                                      | 24/182 [02:27<15:23,  5.84s/it]

0: 384x640 1 animal, 240.2ms
1: 384x640 1 animal, 240.2ms
2: 384x640 1 animal, 240.2ms
3: 384x640 1 animal, 240.2ms
4: 384x640 1 animal, 240.2ms
5: 384x640 (no detections), 240.2ms
6: 384x640 (no detections), 240.2ms
7: 384x640 (no detections), 240.2ms
8: 384x640 (no detections), 240.2ms
9: 384x640 (no detections), 240.2ms
10: 384x640 (no detections), 240.2ms
11: 384x640 (no detections), 240.2ms
12: 384x640 (no detections), 240.2ms
13: 384x640 (no detections), 240.2ms
14: 384x640 (no detections), 240.2ms
15: 384x640 (no detections), 240.2ms
Speed: 1.7ms preprocess, 240.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 14%|██████████████████▋                                                                                                                     | 25/182 [02:32<14:23,  5.50s/it]

0: 640x640 1 animal, 401.6ms
1: 640x640 1 animal, 401.6ms
2: 640x640 1 animal, 401.6ms
3: 640x640 1 animal, 401.6ms
4: 640x640 1 animal, 401.6ms
5: 640x640 1 animal, 401.6ms
6: 640x640 1 animal, 401.6ms
7: 640x640 1 animal, 401.6ms
8: 640x640 1 animal, 401.6ms
9: 640x640 1 animal, 401.6ms
10: 640x640 (no detections), 401.6ms
11: 640x640 (no detections), 401.6ms
12: 640x640 (no detections), 401.6ms
13: 640x640 (no detections), 401.6ms
14: 640x640 (no detections), 401.6ms
15: 640x640 (no detections), 401.6ms
Speed: 2.6ms preprocess, 401.6ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 14%|███████████████████▍                                                                                                                    | 26/182 [02:39<15:32,  5.98s/it]

0: 640x640 (no detections), 402.3ms
1: 640x640 (no detections), 402.3ms
2: 640x640 (no detections), 402.3ms
3: 640x640 1 animal, 402.3ms
4: 640x640 1 animal, 402.3ms
5: 640x640 1 animal, 402.3ms
6: 640x640 1 animal, 402.3ms
7: 640x640 1 animal, 402.3ms
8: 640x640 (no detections), 402.3ms
9: 640x640 (no detections), 402.3ms
10: 640x640 (no detections), 402.3ms
11: 640x640 (no detections), 402.3ms
12: 640x640 (no detections), 402.3ms
13: 640x640 (no detections), 402.3ms
14: 640x640 1 animal, 402.3ms
15: 640x640 1 animal, 402.3ms
Speed: 2.6ms preprocess, 402.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 15%|████████████████████▏                                                                                                                   | 27/182 [02:46<16:29,  6.38s/it]

0: 640x640 1 animal, 404.0ms
1: 640x640 1 animal, 404.0ms
2: 640x640 1 animal, 404.0ms
3: 640x640 (no detections), 404.0ms
4: 640x640 (no detections), 404.0ms
5: 640x640 1 animal, 404.0ms
6: 640x640 1 animal, 404.0ms
7: 640x640 (no detections), 404.0ms
8: 640x640 (no detections), 404.0ms
9: 640x640 (no detections), 404.0ms
10: 640x640 (no detections), 404.0ms
11: 640x640 (no detections), 404.0ms
12: 640x640 (no detections), 404.0ms
13: 640x640 (no detections), 404.0ms
14: 640x640 (no detections), 404.0ms
15: 640x640 (no detections), 404.0ms
Speed: 2.6ms preprocess, 404.0ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 15%|████████████████████▉                                                                                                                   | 28/182 [02:53<16:58,  6.61s/it]

0: 640x640 (no detections), 399.9ms
1: 640x640 (no detections), 399.9ms
2: 640x640 1 animal, 399.9ms
3: 640x640 1 animal, 399.9ms
4: 640x640 1 animal, 399.9ms
5: 640x640 1 animal, 399.9ms
6: 640x640 (no detections), 399.9ms
7: 640x640 1 animal, 399.9ms
8: 640x640 (no detections), 399.9ms
9: 640x640 (no detections), 399.9ms
10: 640x640 1 animal, 399.9ms
11: 640x640 (no detections), 399.9ms
12: 640x640 3 animals, 399.9ms
13: 640x640 2 animals, 399.9ms
14: 640x640 1 animal, 399.9ms
15: 640x640 1 animal, 399.9ms
Speed: 2.8ms preprocess, 399.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 16%|█████████████████████▋                                                                                                                  | 29/182 [03:00<17:10,  6.73s/it]

0: 384x640 1 animal, 241.1ms
1: 384x640 (no detections), 241.1ms
2: 384x640 (no detections), 241.1ms
3: 384x640 (no detections), 241.1ms
4: 384x640 (no detections), 241.1ms
5: 384x640 (no detections), 241.1ms
6: 384x640 1 animal, 1 person, 241.1ms
7: 384x640 (no detections), 241.1ms
8: 384x640 1 animal, 241.1ms
9: 384x640 (no detections), 241.1ms
10: 384x640 (no detections), 241.1ms
11: 384x640 (no detections), 241.1ms
12: 384x640 (no detections), 241.1ms
13: 384x640 (no detections), 241.1ms
14: 384x640 (no detections), 241.1ms
15: 384x640 (no detections), 241.1ms
Speed: 1.8ms preprocess, 241.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 16%|██████████████████████▍                                                                                                                 | 30/182 [03:05<15:33,  6.14s/it]

0: 384x640 (no detections), 239.7ms
1: 384x640 (no detections), 239.7ms
2: 384x640 (no detections), 239.7ms
3: 384x640 (no detections), 239.7ms
4: 384x640 (no detections), 239.7ms
5: 384x640 (no detections), 239.7ms
6: 384x640 (no detections), 239.7ms
7: 384x640 (no detections), 239.7ms
8: 384x640 (no detections), 239.7ms
9: 384x640 (no detections), 239.7ms
10: 384x640 (no detections), 239.7ms
11: 384x640 1 animal, 239.7ms
12: 384x640 (no detections), 239.7ms
13: 384x640 (no detections), 239.7ms
14: 384x640 (no detections), 239.7ms
15: 384x640 (no detections), 239.7ms
Speed: 1.7ms preprocess, 239.7ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 17%|███████████████████████▏                                                                                                                | 31/182 [03:10<14:19,  5.69s/it]

0: 640x640 (no detections), 398.5ms
1: 640x640 (no detections), 398.5ms
2: 640x640 (no detections), 398.5ms
3: 640x640 1 animal, 398.5ms
4: 640x640 (no detections), 398.5ms
5: 640x640 1 animal, 398.5ms
6: 640x640 1 animal, 398.5ms
7: 640x640 1 animal, 398.5ms
8: 640x640 (no detections), 398.5ms
9: 640x640 (no detections), 398.5ms
10: 640x640 1 animal, 398.5ms
11: 640x640 2 animals, 398.5ms
12: 640x640 1 animal, 398.5ms
13: 640x640 1 animal, 398.5ms
14: 640x640 (no detections), 398.5ms
15: 640x640 1 animal, 398.5ms
Speed: 2.6ms preprocess, 398.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 18%|███████████████████████▉                                                                                                                | 32/182 [03:17<15:09,  6.07s/it]

0: 384x640 1 animal, 239.7ms
1: 384x640 2 animals, 239.7ms
2: 384x640 1 animal, 239.7ms
3: 384x640 (no detections), 239.7ms
4: 384x640 (no detections), 239.7ms
5: 384x640 (no detections), 239.7ms
6: 384x640 (no detections), 239.7ms
7: 384x640 (no detections), 239.7ms
8: 384x640 1 animal, 239.7ms
9: 384x640 1 animal, 239.7ms
10: 384x640 1 animal, 239.7ms
11: 384x640 1 animal, 239.7ms
12: 384x640 1 animal, 239.7ms
13: 384x640 1 animal, 239.7ms
14: 384x640 1 animal, 239.7ms
15: 384x640 1 animal, 239.7ms
Speed: 1.7ms preprocess, 239.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 18%|████████████████████████▋                                                                                                               | 33/182 [03:21<13:59,  5.63s/it]

0: 640x640 (no detections), 400.3ms
1: 640x640 1 animal, 400.3ms
2: 640x640 1 animal, 400.3ms
3: 640x640 1 animal, 400.3ms
4: 640x640 1 animal, 400.3ms
5: 640x640 1 animal, 400.3ms
6: 640x640 1 animal, 400.3ms
7: 640x640 1 animal, 400.3ms
8: 640x640 1 animal, 400.3ms
9: 640x640 (no detections), 400.3ms
10: 640x640 (no detections), 400.3ms
11: 640x640 (no detections), 400.3ms
12: 640x640 1 animal, 400.3ms
13: 640x640 (no detections), 400.3ms
14: 640x640 1 animal, 400.3ms
15: 640x640 (no detections), 400.3ms
Speed: 2.5ms preprocess, 400.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 19%|█████████████████████████▍                                                                                                              | 34/182 [03:28<14:51,  6.02s/it]

0: 384x640 1 animal, 239.1ms
1: 384x640 1 animal, 239.1ms
2: 384x640 1 animal, 239.1ms
3: 384x640 1 animal, 239.1ms
4: 384x640 1 animal, 239.1ms
5: 384x640 1 animal, 239.1ms
6: 384x640 1 animal, 239.1ms
7: 384x640 1 animal, 239.1ms
8: 384x640 1 animal, 239.1ms
9: 384x640 1 animal, 239.1ms
10: 384x640 1 animal, 239.1ms
11: 384x640 1 animal, 239.1ms
12: 384x640 1 animal, 239.1ms
13: 384x640 1 animal, 239.1ms
14: 384x640 1 animal, 239.1ms
15: 384x640 1 animal, 239.1ms
Speed: 1.9ms preprocess, 239.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 19%|██████████████████████████▏                                                                                                             | 35/182 [03:33<13:27,  5.50s/it]

0: 640x640 1 animal, 402.7ms
1: 640x640 1 animal, 402.7ms
2: 640x640 1 animal, 402.7ms
3: 640x640 1 animal, 402.7ms
4: 640x640 (no detections), 402.7ms
5: 640x640 (no detections), 402.7ms
6: 640x640 (no detections), 402.7ms
7: 640x640 (no detections), 402.7ms
8: 640x640 (no detections), 402.7ms
9: 640x640 (no detections), 402.7ms
10: 640x640 2 animals, 402.7ms
11: 640x640 2 animals, 402.7ms
12: 640x640 2 animals, 402.7ms
13: 640x640 2 animals, 402.7ms
14: 640x640 2 animals, 402.7ms
15: 640x640 2 animals, 402.7ms
Speed: 2.5ms preprocess, 402.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 20%|██████████████████████████▉                                                                                                             | 36/182 [03:40<14:36,  6.00s/it]

0: 384x640 2 animals, 237.5ms
1: 384x640 2 animals, 237.5ms
2: 384x640 2 animals, 237.5ms
3: 384x640 2 animals, 237.5ms
4: 384x640 1 animal, 237.5ms
5: 384x640 1 animal, 237.5ms
6: 384x640 1 animal, 237.5ms
7: 384x640 1 animal, 237.5ms
8: 384x640 1 animal, 237.5ms
9: 384x640 2 animals, 237.5ms
10: 384x640 (no detections), 237.5ms
11: 384x640 (no detections), 237.5ms
12: 384x640 1 animal, 237.5ms
13: 384x640 (no detections), 237.5ms
14: 384x640 1 animal, 237.5ms
15: 384x640 1 animal, 237.5ms
Speed: 1.7ms preprocess, 237.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 20%|███████████████████████████▋                                                                                                            | 37/182 [03:44<13:13,  5.47s/it]

0: 640x640 1 animal, 403.3ms
1: 640x640 1 animal, 403.3ms
2: 640x640 1 animal, 403.3ms
3: 640x640 1 animal, 403.3ms
4: 640x640 1 animal, 403.3ms
5: 640x640 (no detections), 403.3ms
6: 640x640 (no detections), 403.3ms
7: 640x640 (no detections), 403.3ms
8: 640x640 (no detections), 403.3ms
9: 640x640 (no detections), 403.3ms
10: 640x640 (no detections), 403.3ms
11: 640x640 (no detections), 403.3ms
12: 640x640 (no detections), 403.3ms
13: 640x640 (no detections), 403.3ms
14: 640x640 (no detections), 403.3ms
15: 640x640 (no detections), 403.3ms
Speed: 2.7ms preprocess, 403.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 21%|████████████████████████████▍                                                                                                           | 38/182 [03:51<14:19,  5.97s/it]

0: 640x640 (no detections), 401.0ms
1: 640x640 (no detections), 401.0ms
2: 640x640 (no detections), 401.0ms
3: 640x640 (no detections), 401.0ms
4: 640x640 (no detections), 401.0ms
5: 640x640 (no detections), 401.0ms
6: 640x640 (no detections), 401.0ms
7: 640x640 (no detections), 401.0ms
8: 640x640 (no detections), 401.0ms
9: 640x640 (no detections), 401.0ms
10: 640x640 (no detections), 401.0ms
11: 640x640 (no detections), 401.0ms
12: 640x640 (no detections), 401.0ms
13: 640x640 (no detections), 401.0ms
14: 640x640 (no detections), 401.0ms
15: 640x640 (no detections), 401.0ms
Speed: 2.6ms preprocess, 401.0ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 21%|█████████████████████████████▏                                                                                                          | 39/182 [03:58<14:59,  6.29s/it]

0: 640x640 (no detections), 409.1ms
1: 640x640 (no detections), 409.1ms
2: 640x640 (no detections), 409.1ms
3: 640x640 (no detections), 409.1ms
4: 640x640 (no detections), 409.1ms
5: 640x640 (no detections), 409.1ms
6: 640x640 2 animals, 409.1ms
7: 640x640 2 animals, 409.1ms
8: 640x640 2 animals, 409.1ms
9: 640x640 3 animals, 409.1ms
10: 640x640 3 animals, 409.1ms
11: 640x640 2 animals, 409.1ms
12: 640x640 1 animal, 409.1ms
13: 640x640 3 animals, 409.1ms
14: 640x640 1 animal, 409.1ms
15: 640x640 1 animal, 409.1ms
Speed: 2.7ms preprocess, 409.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 22%|█████████████████████████████▉                                                                                                          | 40/182 [04:05<15:30,  6.56s/it]

0: 384x640 4 animals, 245.3ms
1: 384x640 1 animal, 245.3ms
2: 384x640 3 animals, 245.3ms
3: 384x640 2 animals, 245.3ms
4: 384x640 3 animals, 245.3ms
5: 384x640 2 animals, 245.3ms
6: 384x640 4 animals, 245.3ms
7: 384x640 2 animals, 245.3ms
8: 384x640 2 animals, 245.3ms
9: 384x640 1 animal, 245.3ms
10: 384x640 (no detections), 245.3ms
11: 384x640 (no detections), 245.3ms
12: 384x640 (no detections), 245.3ms
13: 384x640 (no detections), 245.3ms
14: 384x640 (no detections), 245.3ms
15: 384x640 (no detections), 245.3ms
Speed: 1.8ms preprocess, 245.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 23%|██████████████████████████████▋                                                                                                         | 41/182 [04:10<14:12,  6.04s/it]

0: 384x640 (no detections), 244.2ms
1: 384x640 (no detections), 244.2ms
2: 384x640 (no detections), 244.2ms
3: 384x640 (no detections), 244.2ms
4: 384x640 1 animal, 244.2ms
5: 384x640 (no detections), 244.2ms
6: 384x640 1 animal, 244.2ms
7: 384x640 1 animal, 244.2ms
8: 384x640 1 animal, 244.2ms
9: 384x640 1 animal, 244.2ms
10: 384x640 1 animal, 244.2ms
11: 384x640 1 animal, 244.2ms
12: 384x640 1 animal, 244.2ms
13: 384x640 1 animal, 244.2ms
14: 384x640 1 animal, 244.2ms
15: 384x640 (no detections), 244.2ms
Speed: 1.7ms preprocess, 244.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 23%|███████████████████████████████▍                                                                                                        | 42/182 [04:15<13:13,  5.67s/it]

0: 384x640 (no detections), 244.2ms
1: 384x640 (no detections), 244.2ms
2: 384x640 (no detections), 244.2ms
3: 384x640 (no detections), 244.2ms
4: 384x640 (no detections), 244.2ms
5: 384x640 (no detections), 244.2ms
6: 384x640 (no detections), 244.2ms
7: 384x640 1 animal, 244.2ms
8: 384x640 1 animal, 244.2ms
9: 384x640 (no detections), 244.2ms
10: 384x640 (no detections), 244.2ms
11: 384x640 (no detections), 244.2ms
12: 384x640 (no detections), 244.2ms
13: 384x640 (no detections), 244.2ms
14: 384x640 (no detections), 244.2ms
15: 384x640 (no detections), 244.2ms
Speed: 2.1ms preprocess, 244.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 24%|████████████████████████████████▏                                                                                                       | 43/182 [04:20<12:32,  5.41s/it]

0: 640x640 (no detections), 409.7ms
1: 640x640 (no detections), 409.7ms
2: 640x640 (no detections), 409.7ms
3: 640x640 (no detections), 409.7ms
4: 640x640 (no detections), 409.7ms
5: 640x640 (no detections), 409.7ms
6: 640x640 1 animal, 409.7ms
7: 640x640 (no detections), 409.7ms
8: 640x640 1 animal, 409.7ms
9: 640x640 (no detections), 409.7ms
10: 640x640 (no detections), 409.7ms
11: 640x640 (no detections), 409.7ms
12: 640x640 1 animal, 409.7ms
13: 640x640 1 animal, 409.7ms
14: 640x640 1 animal, 409.7ms
15: 640x640 1 animal, 409.7ms
Speed: 2.5ms preprocess, 409.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 24%|████████████████████████████████▉                                                                                                       | 44/182 [04:27<13:35,  5.91s/it]

0: 384x640 1 animal, 241.4ms
1: 384x640 1 animal, 241.4ms
2: 384x640 1 animal, 241.4ms
3: 384x640 1 animal, 241.4ms
4: 384x640 1 animal, 241.4ms
5: 384x640 1 animal, 241.4ms
6: 384x640 1 animal, 241.4ms
7: 384x640 1 animal, 241.4ms
8: 384x640 1 animal, 241.4ms
9: 384x640 1 animal, 241.4ms
10: 384x640 1 animal, 241.4ms
11: 384x640 1 animal, 241.4ms
12: 384x640 1 animal, 241.4ms
13: 384x640 (no detections), 241.4ms
14: 384x640 (no detections), 241.4ms
15: 384x640 (no detections), 241.4ms
Speed: 1.8ms preprocess, 241.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 25%|█████████████████████████████████▋                                                                                                      | 45/182 [04:31<12:23,  5.43s/it]

0: 384x640 1 animal, 246.1ms
1: 384x640 (no detections), 246.1ms
2: 384x640 (no detections), 246.1ms
3: 384x640 (no detections), 246.1ms
4: 384x640 (no detections), 246.1ms
5: 384x640 (no detections), 246.1ms
6: 384x640 (no detections), 246.1ms
7: 384x640 (no detections), 246.1ms
8: 384x640 (no detections), 246.1ms
9: 384x640 (no detections), 246.1ms
10: 384x640 1 person, 246.1ms
11: 384x640 1 animal, 246.1ms
12: 384x640 (no detections), 246.1ms
13: 384x640 (no detections), 246.1ms
14: 384x640 (no detections), 246.1ms
15: 384x640 (no detections), 246.1ms
Speed: 2.0ms preprocess, 246.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 25%|██████████████████████████████████▎                                                                                                     | 46/182 [04:36<11:54,  5.25s/it]

0: 384x640 (no detections), 244.8ms
1: 384x640 (no detections), 244.8ms
2: 384x640 (no detections), 244.8ms
3: 384x640 (no detections), 244.8ms
4: 384x640 (no detections), 244.8ms
5: 384x640 (no detections), 244.8ms
6: 384x640 (no detections), 244.8ms
7: 384x640 (no detections), 244.8ms
8: 384x640 (no detections), 244.8ms
9: 384x640 (no detections), 244.8ms
10: 384x640 (no detections), 244.8ms
11: 384x640 (no detections), 244.8ms
12: 384x640 (no detections), 244.8ms
13: 384x640 (no detections), 244.8ms
14: 384x640 1 animal, 244.8ms
15: 384x640 1 animal, 244.8ms
Speed: 1.7ms preprocess, 244.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 26%|███████████████████████████████████                                                                                                     | 47/182 [04:41<11:30,  5.12s/it]

0: 640x640 1 animal, 413.7ms
1: 640x640 (no detections), 413.7ms
2: 640x640 (no detections), 413.7ms
3: 640x640 (no detections), 413.7ms
4: 640x640 (no detections), 413.7ms
5: 640x640 (no detections), 413.7ms
6: 640x640 (no detections), 413.7ms
7: 640x640 (no detections), 413.7ms
8: 640x640 1 animal, 413.7ms
9: 640x640 1 animal, 413.7ms
10: 640x640 1 animal, 413.7ms
11: 640x640 1 animal, 413.7ms
12: 640x640 1 animal, 413.7ms
13: 640x640 1 animal, 413.7ms
14: 640x640 1 animal, 413.7ms
15: 640x640 1 animal, 413.7ms
Speed: 2.5ms preprocess, 413.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 26%|███████████████████████████████████▊                                                                                                    | 48/182 [04:48<12:54,  5.78s/it]

0: 384x640 1 animal, 242.8ms
1: 384x640 1 animal, 242.8ms
2: 384x640 1 animal, 242.8ms
3: 384x640 1 animal, 242.8ms
4: 384x640 1 animal, 242.8ms
5: 384x640 2 animals, 242.8ms
6: 384x640 1 animal, 242.8ms
7: 384x640 (no detections), 242.8ms
8: 384x640 (no detections), 242.8ms
9: 384x640 (no detections), 242.8ms
10: 384x640 (no detections), 242.8ms
11: 384x640 (no detections), 242.8ms
12: 384x640 1 animal, 242.8ms
13: 384x640 1 animal, 242.8ms
14: 384x640 1 animal, 242.8ms
15: 384x640 1 animal, 242.8ms
Speed: 1.7ms preprocess, 242.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 27%|████████████████████████████████████▌                                                                                                   | 49/182 [04:52<11:51,  5.35s/it]

0: 640x640 1 animal, 413.3ms
1: 640x640 1 animal, 413.3ms
2: 640x640 1 animal, 413.3ms
3: 640x640 1 animal, 413.3ms
4: 640x640 1 animal, 413.3ms
5: 640x640 1 animal, 413.3ms
6: 640x640 1 animal, 413.3ms
7: 640x640 2 animals, 413.3ms
8: 640x640 (no detections), 413.3ms
9: 640x640 (no detections), 413.3ms
10: 640x640 (no detections), 413.3ms
11: 640x640 (no detections), 413.3ms
12: 640x640 1 animal, 413.3ms
13: 640x640 (no detections), 413.3ms
14: 640x640 (no detections), 413.3ms
15: 640x640 (no detections), 413.3ms
Speed: 2.6ms preprocess, 413.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 27%|█████████████████████████████████████▎                                                                                                  | 50/182 [05:00<13:06,  5.96s/it]

0: 384x640 1 animal, 246.0ms
1: 384x640 1 animal, 246.0ms
2: 384x640 (no detections), 246.0ms
3: 384x640 (no detections), 246.0ms
4: 384x640 (no detections), 246.0ms
5: 384x640 (no detections), 246.0ms
6: 384x640 (no detections), 246.0ms
7: 384x640 (no detections), 246.0ms
8: 384x640 (no detections), 246.0ms
9: 384x640 (no detections), 246.0ms
10: 384x640 1 animal, 246.0ms
11: 384x640 1 animal, 246.0ms
12: 384x640 (no detections), 246.0ms
13: 384x640 1 animal, 246.0ms
14: 384x640 (no detections), 246.0ms
15: 384x640 1 animal, 246.0ms
Speed: 1.7ms preprocess, 246.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 28%|██████████████████████████████████████                                                                                                  | 51/182 [05:05<12:15,  5.62s/it]

0: 640x640 2 animals, 410.6ms
1: 640x640 (no detections), 410.6ms
2: 640x640 (no detections), 410.6ms
3: 640x640 (no detections), 410.6ms
4: 640x640 1 animal, 410.6ms
5: 640x640 1 animal, 410.6ms
6: 640x640 1 animal, 410.6ms
7: 640x640 1 animal, 410.6ms
8: 640x640 1 animal, 410.6ms
9: 640x640 1 animal, 410.6ms
10: 640x640 1 animal, 410.6ms
11: 640x640 1 animal, 410.6ms
12: 640x640 1 animal, 410.6ms
13: 640x640 1 animal, 410.6ms
14: 640x640 (no detections), 410.6ms
15: 640x640 (no detections), 410.6ms
Speed: 2.8ms preprocess, 410.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 29%|██████████████████████████████████████▊                                                                                                 | 52/182 [05:12<13:12,  6.10s/it]

0: 384x640 (no detections), 244.8ms
1: 384x640 (no detections), 244.8ms
2: 384x640 (no detections), 244.8ms
3: 384x640 (no detections), 244.8ms
4: 384x640 (no detections), 244.8ms
5: 384x640 (no detections), 244.8ms
6: 384x640 (no detections), 244.8ms
7: 384x640 (no detections), 244.8ms
8: 384x640 1 person, 244.8ms
9: 384x640 1 person, 244.8ms
10: 384x640 1 animal, 244.8ms
11: 384x640 1 animal, 1 person, 244.8ms
12: 384x640 1 animal, 244.8ms
13: 384x640 (no detections), 244.8ms
14: 384x640 (no detections), 244.8ms
15: 384x640 (no detections), 244.8ms
Speed: 1.7ms preprocess, 244.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 29%|███████████████████████████████████████▌                                                                                                | 53/182 [05:17<12:17,  5.72s/it]

0: 640x640 (no detections), 406.3ms
1: 640x640 (no detections), 406.3ms
2: 640x640 2 animals, 406.3ms
3: 640x640 2 animals, 406.3ms
4: 640x640 2 animals, 406.3ms
5: 640x640 2 animals, 406.3ms
6: 640x640 3 animals, 406.3ms
7: 640x640 2 animals, 406.3ms
8: 640x640 1 animal, 406.3ms
9: 640x640 2 animals, 406.3ms
10: 640x640 3 animals, 406.3ms
11: 640x640 3 animals, 406.3ms
12: 640x640 2 animals, 406.3ms
13: 640x640 2 animals, 406.3ms
14: 640x640 2 animals, 406.3ms
15: 640x640 2 animals, 406.3ms
Speed: 2.5ms preprocess, 406.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 30%|████████████████████████████████████████▎                                                                                               | 54/182 [05:24<13:01,  6.10s/it]

0: 640x640 2 animals, 411.3ms
1: 640x640 3 animals, 411.3ms
2: 640x640 1 animal, 411.3ms
3: 640x640 1 animal, 411.3ms
4: 640x640 2 animals, 411.3ms
5: 640x640 2 animals, 411.3ms
6: 640x640 1 animal, 411.3ms
7: 640x640 1 animal, 411.3ms
8: 640x640 1 animal, 411.3ms
9: 640x640 1 animal, 411.3ms
10: 640x640 1 animal, 411.3ms
11: 640x640 2 animals, 411.3ms
12: 640x640 1 animal, 411.3ms
13: 640x640 1 animal, 411.3ms
14: 640x640 (no detections), 411.3ms
15: 640x640 (no detections), 411.3ms
Speed: 2.7ms preprocess, 411.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 30%|█████████████████████████████████████████                                                                                               | 55/182 [05:31<13:42,  6.48s/it]

0: 384x640 (no detections), 238.9ms
1: 384x640 (no detections), 238.9ms
2: 384x640 (no detections), 238.9ms
3: 384x640 (no detections), 238.9ms
4: 384x640 (no detections), 238.9ms
5: 384x640 (no detections), 238.9ms
6: 384x640 (no detections), 238.9ms
7: 384x640 (no detections), 238.9ms
8: 384x640 (no detections), 238.9ms
9: 384x640 (no detections), 238.9ms
10: 384x640 1 animal, 238.9ms
11: 384x640 1 animal, 238.9ms
12: 384x640 1 animal, 238.9ms
13: 384x640 1 animal, 238.9ms
14: 384x640 2 animals, 238.9ms
15: 384x640 1 animal, 238.9ms
Speed: 1.7ms preprocess, 238.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 31%|█████████████████████████████████████████▊                                                                                              | 56/182 [05:35<12:11,  5.81s/it]

0: 640x640 1 animal, 406.9ms
1: 640x640 1 animal, 406.9ms
2: 640x640 1 animal, 406.9ms
3: 640x640 1 animal, 406.9ms
4: 640x640 (no detections), 406.9ms
5: 640x640 (no detections), 406.9ms
6: 640x640 (no detections), 406.9ms
7: 640x640 (no detections), 406.9ms
8: 640x640 (no detections), 406.9ms
9: 640x640 (no detections), 406.9ms
10: 640x640 1 animal, 406.9ms
11: 640x640 1 animal, 406.9ms
12: 640x640 1 animal, 406.9ms
13: 640x640 (no detections), 406.9ms
14: 640x640 2 animals, 406.9ms
15: 640x640 1 animal, 406.9ms
Speed: 2.9ms preprocess, 406.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 31%|██████████████████████████████████████████▌                                                                                             | 57/182 [05:43<13:03,  6.27s/it]

0: 384x640 (no detections), 245.0ms
1: 384x640 (no detections), 245.0ms
2: 384x640 (no detections), 245.0ms
3: 384x640 (no detections), 245.0ms
4: 384x640 (no detections), 245.0ms
5: 384x640 (no detections), 245.0ms
6: 384x640 (no detections), 245.0ms
7: 384x640 (no detections), 245.0ms
8: 384x640 (no detections), 245.0ms
9: 384x640 (no detections), 245.0ms
10: 384x640 (no detections), 245.0ms
11: 384x640 (no detections), 245.0ms
12: 384x640 (no detections), 245.0ms
13: 384x640 (no detections), 245.0ms
14: 384x640 (no detections), 245.0ms
15: 384x640 (no detections), 245.0ms
Speed: 1.7ms preprocess, 245.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 32%|███████████████████████████████████████████▎                                                                                            | 58/182 [05:47<12:03,  5.84s/it]

0: 640x640 (no detections), 409.5ms
1: 640x640 (no detections), 409.5ms
2: 640x640 1 animal, 409.5ms
3: 640x640 1 animal, 409.5ms
4: 640x640 1 animal, 409.5ms
5: 640x640 1 animal, 409.5ms
6: 640x640 1 animal, 409.5ms
7: 640x640 1 animal, 409.5ms
8: 640x640 1 animal, 409.5ms
9: 640x640 1 animal, 409.5ms
10: 640x640 1 animal, 409.5ms
11: 640x640 1 animal, 409.5ms
12: 640x640 (no detections), 409.5ms
13: 640x640 (no detections), 409.5ms
14: 640x640 (no detections), 409.5ms
15: 640x640 (no detections), 409.5ms
Speed: 2.6ms preprocess, 409.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 32%|████████████████████████████████████████████                                                                                            | 59/182 [05:55<12:43,  6.20s/it]

0: 384x640 (no detections), 242.0ms
1: 384x640 (no detections), 242.0ms
2: 384x640 (no detections), 242.0ms
3: 384x640 (no detections), 242.0ms
4: 384x640 (no detections), 242.0ms
5: 384x640 (no detections), 242.0ms
6: 384x640 1 animal, 242.0ms
7: 384x640 1 animal, 242.0ms
8: 384x640 1 animal, 242.0ms
9: 384x640 1 animal, 242.0ms
10: 384x640 1 animal, 242.0ms
11: 384x640 1 animal, 242.0ms
12: 384x640 1 animal, 242.0ms
13: 384x640 1 animal, 242.0ms
14: 384x640 1 animal, 242.0ms
15: 384x640 1 animal, 242.0ms
Speed: 1.8ms preprocess, 242.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 33%|████████████████████████████████████████████▊                                                                                           | 60/182 [05:59<11:27,  5.63s/it]

0: 384x640 1 person, 245.5ms
1: 384x640 1 person, 245.5ms
2: 384x640 (no detections), 245.5ms
3: 384x640 1 person, 245.5ms
4: 384x640 1 person, 245.5ms
5: 384x640 1 person, 245.5ms
6: 384x640 (no detections), 245.5ms
7: 384x640 1 person, 245.5ms
8: 384x640 1 animal, 245.5ms
9: 384x640 1 animal, 245.5ms
10: 384x640 (no detections), 245.5ms
11: 384x640 (no detections), 245.5ms
12: 384x640 (no detections), 245.5ms
13: 384x640 (no detections), 245.5ms
14: 384x640 (no detections), 245.5ms
15: 384x640 (no detections), 245.5ms
Speed: 1.8ms preprocess, 245.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 34%|█████████████████████████████████████████████▌                                                                                          | 61/182 [06:04<10:53,  5.40s/it]

0: 384x640 (no detections), 246.8ms
1: 384x640 (no detections), 246.8ms
2: 384x640 (no detections), 246.8ms
3: 384x640 (no detections), 246.8ms
4: 384x640 (no detections), 246.8ms
5: 384x640 2 animals, 246.8ms
6: 384x640 (no detections), 246.8ms
7: 384x640 (no detections), 246.8ms
8: 384x640 1 animal, 246.8ms
9: 384x640 (no detections), 246.8ms
10: 384x640 (no detections), 246.8ms
11: 384x640 (no detections), 246.8ms
12: 384x640 (no detections), 246.8ms
13: 384x640 (no detections), 246.8ms
14: 384x640 (no detections), 246.8ms
15: 384x640 (no detections), 246.8ms
Speed: 1.7ms preprocess, 246.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 34%|██████████████████████████████████████████████▎                                                                                         | 62/182 [06:09<10:28,  5.24s/it]

0: 640x640 (no detections), 415.5ms
1: 640x640 (no detections), 415.5ms
2: 640x640 (no detections), 415.5ms
3: 640x640 (no detections), 415.5ms
4: 640x640 (no detections), 415.5ms
5: 640x640 (no detections), 415.5ms
6: 640x640 (no detections), 415.5ms
7: 640x640 (no detections), 415.5ms
8: 640x640 (no detections), 415.5ms
9: 640x640 1 animal, 415.5ms
10: 640x640 (no detections), 415.5ms
11: 640x640 (no detections), 415.5ms
12: 640x640 1 animal, 415.5ms
13: 640x640 1 animal, 415.5ms
14: 640x640 1 animal, 415.5ms
15: 640x640 2 animals, 415.5ms
Speed: 2.7ms preprocess, 415.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 35%|███████████████████████████████████████████████                                                                                         | 63/182 [06:16<11:38,  5.87s/it]

0: 640x640 1 animal, 415.9ms
1: 640x640 1 animal, 415.9ms
2: 640x640 1 animal, 415.9ms
3: 640x640 1 animal, 415.9ms
4: 640x640 1 animal, 415.9ms
5: 640x640 1 animal, 415.9ms
6: 640x640 1 animal, 415.9ms
7: 640x640 1 animal, 415.9ms
8: 640x640 1 animal, 415.9ms
9: 640x640 1 animal, 415.9ms
10: 640x640 (no detections), 415.9ms
11: 640x640 (no detections), 415.9ms
12: 640x640 (no detections), 415.9ms
13: 640x640 (no detections), 415.9ms
14: 640x640 (no detections), 415.9ms
15: 640x640 (no detections), 415.9ms
Speed: 2.7ms preprocess, 415.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 35%|███████████████████████████████████████████████▊                                                                                        | 64/182 [06:23<12:32,  6.38s/it]

0: 640x640 (no detections), 412.6ms
1: 640x640 (no detections), 412.6ms
2: 640x640 (no detections), 412.6ms
3: 640x640 (no detections), 412.6ms
4: 640x640 (no detections), 412.6ms
5: 640x640 (no detections), 412.6ms
6: 640x640 1 animal, 412.6ms
7: 640x640 1 animal, 412.6ms
8: 640x640 (no detections), 412.6ms
9: 640x640 (no detections), 412.6ms
10: 640x640 (no detections), 412.6ms
11: 640x640 (no detections), 412.6ms
12: 640x640 (no detections), 412.6ms
13: 640x640 (no detections), 412.6ms
14: 640x640 (no detections), 412.6ms
15: 640x640 (no detections), 412.6ms
Speed: 2.6ms preprocess, 412.6ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 36%|████████████████████████████████████████████████▌                                                                                       | 65/182 [06:31<12:55,  6.63s/it]

0: 384x640 (no detections), 246.1ms
1: 384x640 (no detections), 246.1ms
2: 384x640 (no detections), 246.1ms
3: 384x640 (no detections), 246.1ms
4: 384x640 (no detections), 246.1ms
5: 384x640 (no detections), 246.1ms
6: 384x640 (no detections), 246.1ms
7: 384x640 (no detections), 246.1ms
8: 384x640 (no detections), 246.1ms
9: 384x640 (no detections), 246.1ms
10: 384x640 (no detections), 246.1ms
11: 384x640 1 animal, 246.1ms
12: 384x640 (no detections), 246.1ms
13: 384x640 (no detections), 246.1ms
14: 384x640 (no detections), 246.1ms
15: 384x640 (no detections), 246.1ms
Speed: 1.7ms preprocess, 246.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 36%|█████████████████████████████████████████████████▎                                                                                      | 66/182 [06:35<11:45,  6.08s/it]

0: 640x640 (no detections), 415.0ms
1: 640x640 (no detections), 415.0ms
2: 640x640 (no detections), 415.0ms
3: 640x640 (no detections), 415.0ms
4: 640x640 1 animal, 415.0ms
5: 640x640 1 animal, 415.0ms
6: 640x640 (no detections), 415.0ms
7: 640x640 1 animal, 415.0ms
8: 640x640 (no detections), 415.0ms
9: 640x640 (no detections), 415.0ms
10: 640x640 (no detections), 415.0ms
11: 640x640 1 animal, 415.0ms
12: 640x640 1 animal, 415.0ms
13: 640x640 1 animal, 415.0ms
14: 640x640 (no detections), 415.0ms
15: 640x640 (no detections), 415.0ms
Speed: 2.7ms preprocess, 415.0ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 37%|██████████████████████████████████████████████████                                                                                      | 67/182 [06:43<12:28,  6.51s/it]

0: 640x640 1 animal, 411.9ms
1: 640x640 (no detections), 411.9ms
2: 640x640 (no detections), 411.9ms
3: 640x640 (no detections), 411.9ms
4: 640x640 (no detections), 411.9ms
5: 640x640 (no detections), 411.9ms
6: 640x640 (no detections), 411.9ms
7: 640x640 (no detections), 411.9ms
8: 640x640 1 animal, 411.9ms
9: 640x640 1 animal, 411.9ms
10: 640x640 1 animal, 411.9ms
11: 640x640 1 animal, 411.9ms
12: 640x640 1 animal, 411.9ms
13: 640x640 2 animals, 411.9ms
14: 640x640 1 animal, 411.9ms
15: 640x640 1 animal, 411.9ms
Speed: 2.8ms preprocess, 411.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 37%|██████████████████████████████████████████████████▊                                                                                     | 68/182 [06:50<12:45,  6.72s/it]

0: 640x640 1 animal, 401.1ms
1: 640x640 1 animal, 401.1ms
2: 640x640 1 animal, 401.1ms
3: 640x640 1 animal, 401.1ms
4: 640x640 1 animal, 401.1ms
5: 640x640 1 animal, 401.1ms
6: 640x640 1 animal, 401.1ms
7: 640x640 1 animal, 401.1ms
8: 640x640 1 animal, 401.1ms
9: 640x640 1 animal, 401.1ms
10: 640x640 1 animal, 401.1ms
11: 640x640 1 animal, 401.1ms
12: 640x640 1 animal, 401.1ms
13: 640x640 1 animal, 401.1ms
14: 640x640 1 animal, 401.1ms
15: 640x640 3 animals, 401.1ms
Speed: 2.5ms preprocess, 401.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 38%|███████████████████████████████████████████████████▌                                                                                    | 69/182 [06:57<12:48,  6.80s/it]

0: 384x640 1 animal, 239.7ms
1: 384x640 1 animal, 239.7ms
2: 384x640 1 animal, 239.7ms
3: 384x640 (no detections), 239.7ms
4: 384x640 (no detections), 239.7ms
5: 384x640 (no detections), 239.7ms
6: 384x640 1 animal, 239.7ms
7: 384x640 1 animal, 239.7ms
8: 384x640 1 animal, 239.7ms
9: 384x640 (no detections), 239.7ms
10: 384x640 (no detections), 239.7ms
11: 384x640 (no detections), 239.7ms
12: 384x640 (no detections), 239.7ms
13: 384x640 (no detections), 239.7ms
14: 384x640 (no detections), 239.7ms
15: 384x640 (no detections), 239.7ms
Speed: 1.9ms preprocess, 239.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 38%|████████████████████████████████████████████████████▎                                                                                   | 70/182 [07:02<11:26,  6.13s/it]

0: 384x640 1 person, 240.1ms
1: 384x640 1 person, 240.1ms
2: 384x640 1 person, 240.1ms
3: 384x640 1 person, 240.1ms
4: 384x640 1 person, 240.1ms
5: 384x640 1 person, 240.1ms
6: 384x640 1 animal, 240.1ms
7: 384x640 1 animal, 240.1ms
8: 384x640 1 animal, 1 person, 240.1ms
9: 384x640 (no detections), 240.1ms
10: 384x640 1 animal, 240.1ms
11: 384x640 1 animal, 240.1ms
12: 384x640 (no detections), 240.1ms
13: 384x640 1 animal, 1 person, 240.1ms
14: 384x640 (no detections), 240.1ms
15: 384x640 (no detections), 240.1ms
Speed: 1.9ms preprocess, 240.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 39%|█████████████████████████████████████████████████████                                                                                   | 71/182 [07:07<10:34,  5.72s/it]

0: 384x640 (no detections), 245.2ms
1: 384x640 (no detections), 245.2ms
2: 384x640 (no detections), 245.2ms
3: 384x640 (no detections), 245.2ms
4: 384x640 (no detections), 245.2ms
5: 384x640 (no detections), 245.2ms
6: 384x640 (no detections), 245.2ms
7: 384x640 (no detections), 245.2ms
8: 384x640 (no detections), 245.2ms
9: 384x640 (no detections), 245.2ms
10: 384x640 (no detections), 245.2ms
11: 384x640 (no detections), 245.2ms
12: 384x640 (no detections), 245.2ms
13: 384x640 (no detections), 245.2ms
14: 384x640 1 animal, 1 person, 245.2ms
15: 384x640 1 animal, 245.2ms
Speed: 1.7ms preprocess, 245.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 40%|█████████████████████████████████████████████████████▊                                                                                  | 72/182 [07:11<10:00,  5.46s/it]

0: 384x640 1 animal, 245.2ms
1: 384x640 1 person, 245.2ms
2: 384x640 1 person, 245.2ms
3: 384x640 (no detections), 245.2ms
4: 384x640 (no detections), 245.2ms
5: 384x640 (no detections), 245.2ms
6: 384x640 (no detections), 245.2ms
7: 384x640 (no detections), 245.2ms
8: 384x640 1 animal, 245.2ms
9: 384x640 (no detections), 245.2ms
10: 384x640 (no detections), 245.2ms
11: 384x640 1 animal, 245.2ms
12: 384x640 1 animal, 245.2ms
13: 384x640 1 animal, 245.2ms
14: 384x640 (no detections), 245.2ms
15: 384x640 (no detections), 245.2ms
Speed: 1.9ms preprocess, 245.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 40%|██████████████████████████████████████████████████████▌                                                                                 | 73/182 [07:16<09:35,  5.28s/it]

0: 384x640 (no detections), 245.4ms
1: 384x640 (no detections), 245.4ms
2: 384x640 1 animal, 245.4ms
3: 384x640 1 animal, 245.4ms
4: 384x640 (no detections), 245.4ms
5: 384x640 (no detections), 245.4ms
6: 384x640 (no detections), 245.4ms
7: 384x640 (no detections), 245.4ms
8: 384x640 (no detections), 245.4ms
9: 384x640 (no detections), 245.4ms
10: 384x640 (no detections), 245.4ms
11: 384x640 (no detections), 245.4ms
12: 384x640 1 animal, 245.4ms
13: 384x640 (no detections), 245.4ms
14: 384x640 (no detections), 245.4ms
15: 384x640 (no detections), 245.4ms
Speed: 2.0ms preprocess, 245.4ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 41%|███████████████████████████████████████████████████████▎                                                                                | 74/182 [07:21<09:15,  5.15s/it]

0: 384x640 (no detections), 246.1ms
1: 384x640 (no detections), 246.1ms
2: 384x640 (no detections), 246.1ms
3: 384x640 1 animal, 246.1ms
4: 384x640 (no detections), 246.1ms
5: 384x640 (no detections), 246.1ms
6: 384x640 1 animal, 246.1ms
7: 384x640 1 animal, 246.1ms
8: 384x640 (no detections), 246.1ms
9: 384x640 (no detections), 246.1ms
10: 384x640 (no detections), 246.1ms
11: 384x640 1 animal, 246.1ms
12: 384x640 (no detections), 246.1ms
13: 384x640 (no detections), 246.1ms
14: 384x640 (no detections), 246.1ms
15: 384x640 (no detections), 246.1ms
Speed: 1.9ms preprocess, 246.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 41%|████████████████████████████████████████████████████████                                                                                | 75/182 [07:26<09:00,  5.05s/it]

0: 384x640 1 animal, 244.5ms
1: 384x640 (no detections), 244.5ms
2: 384x640 (no detections), 244.5ms
3: 384x640 (no detections), 244.5ms
4: 384x640 (no detections), 244.5ms
5: 384x640 (no detections), 244.5ms
6: 384x640 (no detections), 244.5ms
7: 384x640 (no detections), 244.5ms
8: 384x640 (no detections), 244.5ms
9: 384x640 (no detections), 244.5ms
10: 384x640 (no detections), 244.5ms
11: 384x640 (no detections), 244.5ms
12: 384x640 (no detections), 244.5ms
13: 384x640 (no detections), 244.5ms
14: 384x640 (no detections), 244.5ms
15: 384x640 (no detections), 244.5ms
Speed: 1.8ms preprocess, 244.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 42%|████████████████████████████████████████████████████████▊                                                                               | 76/182 [07:31<08:48,  4.98s/it]

0: 384x640 (no detections), 247.2ms
1: 384x640 (no detections), 247.2ms
2: 384x640 (no detections), 247.2ms
3: 384x640 (no detections), 247.2ms
4: 384x640 (no detections), 247.2ms
5: 384x640 (no detections), 247.2ms
6: 384x640 (no detections), 247.2ms
7: 384x640 (no detections), 247.2ms
8: 384x640 (no detections), 247.2ms
9: 384x640 (no detections), 247.2ms
10: 384x640 (no detections), 247.2ms
11: 384x640 (no detections), 247.2ms
12: 384x640 (no detections), 247.2ms
13: 384x640 (no detections), 247.2ms
14: 384x640 (no detections), 247.2ms
15: 384x640 (no detections), 247.2ms
Speed: 1.9ms preprocess, 247.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 42%|█████████████████████████████████████████████████████████▌                                                                              | 77/182 [07:36<08:39,  4.95s/it]

0: 384x640 (no detections), 245.9ms
1: 384x640 1 animal, 245.9ms
2: 384x640 2 animals, 245.9ms
3: 384x640 1 animal, 245.9ms
4: 384x640 1 animal, 245.9ms
5: 384x640 1 animal, 245.9ms
6: 384x640 1 animal, 245.9ms
7: 384x640 1 animal, 245.9ms
8: 384x640 (no detections), 245.9ms
9: 384x640 (no detections), 245.9ms
10: 384x640 (no detections), 245.9ms
11: 384x640 (no detections), 245.9ms
12: 384x640 (no detections), 245.9ms
13: 384x640 (no detections), 245.9ms
14: 384x640 (no detections), 245.9ms
15: 384x640 (no detections), 245.9ms
Speed: 1.7ms preprocess, 245.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 43%|██████████████████████████████████████████████████████████▎                                                                             | 78/182 [07:40<08:31,  4.92s/it]

0: 384x640 (no detections), 245.8ms
1: 384x640 (no detections), 245.8ms
2: 384x640 1 animal, 245.8ms
3: 384x640 1 animal, 245.8ms
4: 384x640 (no detections), 245.8ms
5: 384x640 (no detections), 245.8ms
6: 384x640 (no detections), 245.8ms
7: 384x640 (no detections), 245.8ms
8: 384x640 (no detections), 245.8ms
9: 384x640 (no detections), 245.8ms
10: 384x640 (no detections), 245.8ms
11: 384x640 1 animal, 245.8ms
12: 384x640 1 animal, 245.8ms
13: 384x640 (no detections), 245.8ms
14: 384x640 (no detections), 245.8ms
15: 384x640 (no detections), 245.8ms
Speed: 1.8ms preprocess, 245.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 43%|███████████████████████████████████████████████████████████                                                                             | 79/182 [07:45<08:24,  4.90s/it]

0: 640x640 (no detections), 413.2ms
1: 640x640 (no detections), 413.2ms
2: 640x640 (no detections), 413.2ms
3: 640x640 (no detections), 413.2ms
4: 640x640 (no detections), 413.2ms
5: 640x640 (no detections), 413.2ms
6: 640x640 1 animal, 413.2ms
7: 640x640 1 animal, 413.2ms
8: 640x640 1 animal, 413.2ms
9: 640x640 1 animal, 413.2ms
10: 640x640 1 animal, 413.2ms
11: 640x640 1 animal, 413.2ms
12: 640x640 1 animal, 413.2ms
13: 640x640 (no detections), 413.2ms
14: 640x640 (no detections), 413.2ms
15: 640x640 (no detections), 413.2ms
Speed: 2.6ms preprocess, 413.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 44%|███████████████████████████████████████████████████████████▊                                                                            | 80/182 [07:53<09:31,  5.60s/it]

0: 384x640 1 animal, 245.3ms
1: 384x640 1 animal, 245.3ms
2: 384x640 1 animal, 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 (no detections), 245.3ms
5: 384x640 (no detections), 245.3ms
6: 384x640 (no detections), 245.3ms
7: 384x640 (no detections), 245.3ms
8: 384x640 (no detections), 245.3ms
9: 384x640 (no detections), 245.3ms
10: 384x640 1 person, 245.3ms
11: 384x640 (no detections), 245.3ms
12: 384x640 (no detections), 245.3ms
13: 384x640 (no detections), 245.3ms
14: 384x640 1 animal, 245.3ms
15: 384x640 (no detections), 245.3ms
Speed: 2.0ms preprocess, 245.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 45%|████████████████████████████████████████████████████████████▌                                                                           | 81/182 [07:57<09:03,  5.38s/it]

0: 384x640 (no detections), 246.7ms
1: 384x640 (no detections), 246.7ms
2: 384x640 (no detections), 246.7ms
3: 384x640 (no detections), 246.7ms
4: 384x640 1 animal, 1 person, 246.7ms
5: 384x640 1 animal, 246.7ms
6: 384x640 1 animal, 246.7ms
7: 384x640 (no detections), 246.7ms
8: 384x640 (no detections), 246.7ms
9: 384x640 (no detections), 246.7ms
10: 384x640 (no detections), 246.7ms
11: 384x640 (no detections), 246.7ms
12: 384x640 (no detections), 246.7ms
13: 384x640 (no detections), 246.7ms
14: 384x640 (no detections), 246.7ms
15: 384x640 (no detections), 246.7ms
Speed: 1.8ms preprocess, 246.7ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 45%|█████████████████████████████████████████████████████████████▎                                                                          | 82/182 [08:02<08:42,  5.23s/it]

0: 384x640 (no detections), 246.9ms
1: 384x640 (no detections), 246.9ms
2: 384x640 (no detections), 246.9ms
3: 384x640 (no detections), 246.9ms
4: 384x640 (no detections), 246.9ms
5: 384x640 (no detections), 246.9ms
6: 384x640 (no detections), 246.9ms
7: 384x640 (no detections), 246.9ms
8: 384x640 2 animals, 246.9ms
9: 384x640 1 animal, 246.9ms
10: 384x640 1 animal, 246.9ms
11: 384x640 (no detections), 246.9ms
12: 384x640 1 animal, 246.9ms
13: 384x640 (no detections), 246.9ms
14: 384x640 (no detections), 246.9ms
15: 384x640 (no detections), 246.9ms
Speed: 1.9ms preprocess, 246.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 46%|██████████████████████████████████████████████████████████████                                                                          | 83/182 [08:07<08:26,  5.12s/it]

0: 384x640 (no detections), 244.4ms
1: 384x640 (no detections), 244.4ms
2: 384x640 (no detections), 244.4ms
3: 384x640 (no detections), 244.4ms
4: 384x640 (no detections), 244.4ms
5: 384x640 (no detections), 244.4ms
6: 384x640 (no detections), 244.4ms
7: 384x640 (no detections), 244.4ms
8: 384x640 (no detections), 244.4ms
9: 384x640 (no detections), 244.4ms
10: 384x640 (no detections), 244.4ms
11: 384x640 (no detections), 244.4ms
12: 384x640 1 animal, 244.4ms
13: 384x640 1 animal, 244.4ms
14: 384x640 1 animal, 244.4ms
15: 384x640 1 animal, 244.4ms
Speed: 1.7ms preprocess, 244.4ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 46%|██████████████████████████████████████████████████████████████▊                                                                         | 84/182 [08:12<08:12,  5.03s/it]

0: 384x640 1 animal, 244.0ms
1: 384x640 (no detections), 244.0ms
2: 384x640 (no detections), 244.0ms
3: 384x640 (no detections), 244.0ms
4: 384x640 (no detections), 244.0ms
5: 384x640 (no detections), 244.0ms
6: 384x640 1 animal, 244.0ms
7: 384x640 2 animals, 244.0ms
8: 384x640 2 animals, 244.0ms
9: 384x640 (no detections), 244.0ms
10: 384x640 (no detections), 244.0ms
11: 384x640 (no detections), 244.0ms
12: 384x640 (no detections), 244.0ms
13: 384x640 (no detections), 244.0ms
14: 384x640 (no detections), 244.0ms
15: 384x640 (no detections), 244.0ms
Speed: 1.9ms preprocess, 244.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 47%|███████████████████████████████████████████████████████████████▌                                                                        | 85/182 [08:17<08:01,  4.97s/it]

0: 384x640 1 animal, 243.1ms
1: 384x640 (no detections), 243.1ms
2: 384x640 (no detections), 243.1ms
3: 384x640 (no detections), 243.1ms
4: 384x640 (no detections), 243.1ms
5: 384x640 (no detections), 243.1ms
6: 384x640 (no detections), 243.1ms
7: 384x640 (no detections), 243.1ms
8: 384x640 (no detections), 243.1ms
9: 384x640 (no detections), 243.1ms
10: 384x640 1 animal, 243.1ms
11: 384x640 (no detections), 243.1ms
12: 384x640 (no detections), 243.1ms
13: 384x640 (no detections), 243.1ms
14: 384x640 (no detections), 243.1ms
15: 384x640 (no detections), 243.1ms
Speed: 1.7ms preprocess, 243.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 47%|████████████████████████████████████████████████████████████████▎                                                                       | 86/182 [08:22<07:51,  4.91s/it]

0: 384x640 (no detections), 244.0ms
1: 384x640 (no detections), 244.0ms
2: 384x640 1 vehicle, 244.0ms
3: 384x640 (no detections), 244.0ms
4: 384x640 (no detections), 244.0ms
5: 384x640 (no detections), 244.0ms
6: 384x640 (no detections), 244.0ms
7: 384x640 (no detections), 244.0ms
8: 384x640 (no detections), 244.0ms
9: 384x640 (no detections), 244.0ms
10: 384x640 (no detections), 244.0ms
11: 384x640 (no detections), 244.0ms
12: 384x640 (no detections), 244.0ms
13: 384x640 (no detections), 244.0ms
14: 384x640 (no detections), 244.0ms
15: 384x640 (no detections), 244.0ms
Speed: 1.7ms preprocess, 244.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 48%|█████████████████████████████████████████████████████████████████                                                                       | 87/182 [08:26<07:43,  4.88s/it]

0: 384x640 (no detections), 246.3ms
1: 384x640 (no detections), 246.3ms
2: 384x640 (no detections), 246.3ms
3: 384x640 (no detections), 246.3ms
4: 384x640 (no detections), 246.3ms
5: 384x640 (no detections), 246.3ms
6: 384x640 (no detections), 246.3ms
7: 384x640 (no detections), 246.3ms
8: 384x640 (no detections), 246.3ms
9: 384x640 (no detections), 246.3ms
10: 384x640 (no detections), 246.3ms
11: 384x640 (no detections), 246.3ms
12: 384x640 (no detections), 246.3ms
13: 384x640 (no detections), 246.3ms
14: 384x640 (no detections), 246.3ms
15: 384x640 (no detections), 246.3ms
Speed: 2.0ms preprocess, 246.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 48%|█████████████████████████████████████████████████████████████████▊                                                                      | 88/182 [08:31<07:37,  4.86s/it]

0: 384x640 (no detections), 245.1ms
1: 384x640 (no detections), 245.1ms
2: 384x640 (no detections), 245.1ms
3: 384x640 (no detections), 245.1ms
4: 384x640 (no detections), 245.1ms
5: 384x640 (no detections), 245.1ms
6: 384x640 (no detections), 245.1ms
7: 384x640 (no detections), 245.1ms
8: 384x640 (no detections), 245.1ms
9: 384x640 (no detections), 245.1ms
10: 384x640 (no detections), 245.1ms
11: 384x640 (no detections), 245.1ms
12: 384x640 (no detections), 245.1ms
13: 384x640 (no detections), 245.1ms
14: 384x640 (no detections), 245.1ms
15: 384x640 (no detections), 245.1ms
Speed: 1.7ms preprocess, 245.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 49%|██████████████████████████████████████████████████████████████████▌                                                                     | 89/182 [08:36<07:30,  4.85s/it]

0: 384x640 (no detections), 244.5ms
1: 384x640 (no detections), 244.5ms
2: 384x640 (no detections), 244.5ms
3: 384x640 (no detections), 244.5ms
4: 384x640 (no detections), 244.5ms
5: 384x640 (no detections), 244.5ms
6: 384x640 1 animal, 244.5ms
7: 384x640 1 animal, 244.5ms
8: 384x640 1 animal, 244.5ms
9: 384x640 1 animal, 244.5ms
10: 384x640 (no detections), 244.5ms
11: 384x640 (no detections), 244.5ms
12: 384x640 1 animal, 244.5ms
13: 384x640 (no detections), 244.5ms
14: 384x640 1 animal, 244.5ms
15: 384x640 (no detections), 244.5ms
Speed: 1.7ms preprocess, 244.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 49%|███████████████████████████████████████████████████████████████████▎                                                                    | 90/182 [08:41<07:24,  4.83s/it]

0: 384x640 (no detections), 245.1ms
1: 384x640 (no detections), 245.1ms
2: 384x640 (no detections), 245.1ms
3: 384x640 (no detections), 245.1ms
4: 384x640 (no detections), 245.1ms
5: 384x640 (no detections), 245.1ms
6: 384x640 (no detections), 245.1ms
7: 384x640 (no detections), 245.1ms
8: 384x640 (no detections), 245.1ms
9: 384x640 (no detections), 245.1ms
10: 384x640 (no detections), 245.1ms
11: 384x640 (no detections), 245.1ms
12: 384x640 (no detections), 245.1ms
13: 384x640 (no detections), 245.1ms
14: 384x640 (no detections), 245.1ms
15: 384x640 (no detections), 245.1ms
Speed: 1.7ms preprocess, 245.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 50%|████████████████████████████████████████████████████████████████████                                                                    | 91/182 [08:46<07:19,  4.83s/it]

0: 384x640 (no detections), 242.9ms
1: 384x640 (no detections), 242.9ms
2: 384x640 (no detections), 242.9ms
3: 384x640 (no detections), 242.9ms
4: 384x640 1 animal, 242.9ms
5: 384x640 (no detections), 242.9ms
6: 384x640 (no detections), 242.9ms
7: 384x640 (no detections), 242.9ms
8: 384x640 (no detections), 242.9ms
9: 384x640 (no detections), 242.9ms
10: 384x640 (no detections), 242.9ms
11: 384x640 (no detections), 242.9ms
12: 384x640 (no detections), 242.9ms
13: 384x640 (no detections), 242.9ms
14: 384x640 1 animal, 242.9ms
15: 384x640 2 animals, 242.9ms
Speed: 1.7ms preprocess, 242.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 51%|████████████████████████████████████████████████████████████████████▋                                                                   | 92/182 [08:50<07:12,  4.81s/it]

0: 384x640 1 animal, 243.7ms
1: 384x640 1 animal, 243.7ms
2: 384x640 1 animal, 243.7ms
3: 384x640 1 animal, 243.7ms
4: 384x640 1 animal, 243.7ms
5: 384x640 1 animal, 243.7ms
6: 384x640 (no detections), 243.7ms
7: 384x640 (no detections), 243.7ms
8: 384x640 1 animal, 243.7ms
9: 384x640 1 animal, 243.7ms
10: 384x640 (no detections), 243.7ms
11: 384x640 (no detections), 243.7ms
12: 384x640 1 animal, 243.7ms
13: 384x640 (no detections), 243.7ms
14: 384x640 (no detections), 243.7ms
15: 384x640 (no detections), 243.7ms
Speed: 1.7ms preprocess, 243.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 51%|█████████████████████████████████████████████████████████████████████▍                                                                  | 93/182 [08:55<07:07,  4.80s/it]

0: 384x640 (no detections), 243.1ms
1: 384x640 (no detections), 243.1ms
2: 384x640 1 animal, 243.1ms
3: 384x640 1 animal, 243.1ms
4: 384x640 1 animal, 243.1ms
5: 384x640 1 animal, 243.1ms
6: 384x640 2 animals, 243.1ms
7: 384x640 (no detections), 243.1ms
8: 384x640 (no detections), 243.1ms
9: 384x640 (no detections), 243.1ms
10: 384x640 (no detections), 243.1ms
11: 384x640 (no detections), 243.1ms
12: 384x640 (no detections), 243.1ms
13: 384x640 (no detections), 243.1ms
14: 384x640 (no detections), 243.1ms
15: 384x640 (no detections), 243.1ms
Speed: 1.8ms preprocess, 243.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 52%|██████████████████████████████████████████████████████████████████████▏                                                                 | 94/182 [09:00<07:02,  4.80s/it]

0: 384x640 (no detections), 244.6ms
1: 384x640 (no detections), 244.6ms
2: 384x640 (no detections), 244.6ms
3: 384x640 (no detections), 244.6ms
4: 384x640 (no detections), 244.6ms
5: 384x640 (no detections), 244.6ms
6: 384x640 (no detections), 244.6ms
7: 384x640 1 animal, 1 person, 244.6ms
8: 384x640 1 animal, 1 person, 244.6ms
9: 384x640 1 animal, 244.6ms
10: 384x640 (no detections), 244.6ms
11: 384x640 (no detections), 244.6ms
12: 384x640 (no detections), 244.6ms
13: 384x640 (no detections), 244.6ms
14: 384x640 (no detections), 244.6ms
15: 384x640 (no detections), 244.6ms
Speed: 2.1ms preprocess, 244.6ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 52%|██████████████████████████████████████████████████████████████████████▉                                                                 | 95/182 [09:05<06:57,  4.80s/it]

0: 384x640 (no detections), 244.3ms
1: 384x640 (no detections), 244.3ms
2: 384x640 (no detections), 244.3ms
3: 384x640 (no detections), 244.3ms
4: 384x640 (no detections), 244.3ms
5: 384x640 (no detections), 244.3ms
6: 384x640 (no detections), 244.3ms
7: 384x640 (no detections), 244.3ms
8: 384x640 (no detections), 244.3ms
9: 384x640 (no detections), 244.3ms
10: 384x640 (no detections), 244.3ms
11: 384x640 (no detections), 244.3ms
12: 384x640 (no detections), 244.3ms
13: 384x640 (no detections), 244.3ms
14: 384x640 (no detections), 244.3ms
15: 384x640 (no detections), 244.3ms
Speed: 1.7ms preprocess, 244.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 53%|███████████████████████████████████████████████████████████████████████▋                                                                | 96/182 [09:10<06:51,  4.79s/it]

0: 384x640 (no detections), 245.8ms
1: 384x640 (no detections), 245.8ms
2: 384x640 (no detections), 245.8ms
3: 384x640 (no detections), 245.8ms
4: 384x640 1 animal, 245.8ms
5: 384x640 1 animal, 245.8ms
6: 384x640 1 animal, 1 person, 245.8ms
7: 384x640 (no detections), 245.8ms
8: 384x640 (no detections), 245.8ms
9: 384x640 (no detections), 245.8ms
10: 384x640 (no detections), 245.8ms
11: 384x640 (no detections), 245.8ms
12: 384x640 (no detections), 245.8ms
13: 384x640 (no detections), 245.8ms
14: 384x640 1 animal, 1 person, 245.8ms
15: 384x640 1 animal, 245.8ms
Speed: 1.7ms preprocess, 245.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 53%|████████████████████████████████████████████████████████████████████████▍                                                               | 97/182 [09:14<06:47,  4.80s/it]

0: 384x640 1 animal, 243.3ms
1: 384x640 (no detections), 243.3ms
2: 384x640 (no detections), 243.3ms
3: 384x640 (no detections), 243.3ms
4: 384x640 (no detections), 243.3ms
5: 384x640 (no detections), 243.3ms
6: 384x640 (no detections), 243.3ms
7: 384x640 (no detections), 243.3ms
8: 384x640 1 animal, 243.3ms
9: 384x640 2 animals, 243.3ms
10: 384x640 1 animal, 243.3ms
11: 384x640 (no detections), 243.3ms
12: 384x640 (no detections), 243.3ms
13: 384x640 (no detections), 243.3ms
14: 384x640 (no detections), 243.3ms
15: 384x640 (no detections), 243.3ms
Speed: 1.7ms preprocess, 243.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 54%|█████████████████████████████████████████████████████████████████████████▏                                                              | 98/182 [09:19<06:42,  4.79s/it]

0: 384x640 (no detections), 244.1ms
1: 384x640 (no detections), 244.1ms
2: 384x640 1 person, 244.1ms
3: 384x640 1 animal, 244.1ms
4: 384x640 1 person, 244.1ms
5: 384x640 (no detections), 244.1ms
6: 384x640 (no detections), 244.1ms
7: 384x640 (no detections), 244.1ms
8: 384x640 1 animal, 244.1ms
9: 384x640 (no detections), 244.1ms
10: 384x640 (no detections), 244.1ms
11: 384x640 (no detections), 244.1ms
12: 384x640 1 animal, 244.1ms
13: 384x640 1 animal, 244.1ms
14: 384x640 1 animal, 244.1ms
15: 384x640 1 animal, 244.1ms
Speed: 1.7ms preprocess, 244.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 54%|█████████████████████████████████████████████████████████████████████████▉                                                              | 99/182 [09:24<06:37,  4.79s/it]

0: 384x640 (no detections), 243.2ms
1: 384x640 (no detections), 243.2ms
2: 384x640 (no detections), 243.2ms
3: 384x640 (no detections), 243.2ms
4: 384x640 (no detections), 243.2ms
5: 384x640 (no detections), 243.2ms
6: 384x640 1 animal, 243.2ms
7: 384x640 (no detections), 243.2ms
8: 384x640 1 animal, 243.2ms
9: 384x640 1 animal, 243.2ms
10: 384x640 (no detections), 243.2ms
11: 384x640 (no detections), 243.2ms
12: 384x640 (no detections), 243.2ms
13: 384x640 1 animal, 243.2ms
14: 384x640 (no detections), 243.2ms
15: 384x640 (no detections), 243.2ms
Speed: 1.7ms preprocess, 243.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 55%|██████████████████████████████████████████████████████████████████████████▏                                                            | 100/182 [09:29<06:32,  4.78s/it]

0: 384x640 1 animal, 243.7ms
1: 384x640 2 animals, 243.7ms
2: 384x640 1 animal, 243.7ms
3: 384x640 1 animal, 243.7ms
4: 384x640 1 animal, 1 person, 243.7ms
5: 384x640 1 person, 243.7ms
6: 384x640 1 animal, 243.7ms
7: 384x640 (no detections), 243.7ms
8: 384x640 (no detections), 243.7ms
9: 384x640 1 animal, 243.7ms
10: 384x640 (no detections), 243.7ms
11: 384x640 1 animal, 243.7ms
12: 384x640 (no detections), 243.7ms
13: 384x640 (no detections), 243.7ms
14: 384x640 (no detections), 243.7ms
15: 384x640 (no detections), 243.7ms
Speed: 1.7ms preprocess, 243.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 55%|██████████████████████████████████████████████████████████████████████████▉                                                            | 101/182 [09:33<06:27,  4.79s/it]

0: 384x640 (no detections), 244.8ms
1: 384x640 (no detections), 244.8ms
2: 384x640 (no detections), 244.8ms
3: 384x640 (no detections), 244.8ms
4: 384x640 (no detections), 244.8ms
5: 384x640 (no detections), 244.8ms
6: 384x640 (no detections), 244.8ms
7: 384x640 (no detections), 244.8ms
8: 384x640 (no detections), 244.8ms
9: 384x640 1 animal, 244.8ms
10: 384x640 1 animal, 244.8ms
11: 384x640 (no detections), 244.8ms
12: 384x640 1 animal, 244.8ms
13: 384x640 (no detections), 244.8ms
14: 384x640 1 animal, 244.8ms
15: 384x640 1 animal, 244.8ms
Speed: 2.0ms preprocess, 244.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 56%|███████████████████████████████████████████████████████████████████████████▋                                                           | 102/182 [09:38<06:23,  4.79s/it]

0: 384x640 3 animals, 243.1ms
1: 384x640 (no detections), 243.1ms
2: 384x640 (no detections), 243.1ms
3: 384x640 (no detections), 243.1ms
4: 384x640 (no detections), 243.1ms
5: 384x640 (no detections), 243.1ms
6: 384x640 (no detections), 243.1ms
7: 384x640 (no detections), 243.1ms
8: 384x640 (no detections), 243.1ms
9: 384x640 (no detections), 243.1ms
10: 384x640 (no detections), 243.1ms
11: 384x640 (no detections), 243.1ms
12: 384x640 (no detections), 243.1ms
13: 384x640 (no detections), 243.1ms
14: 384x640 (no detections), 243.1ms
15: 384x640 (no detections), 243.1ms
Speed: 1.7ms preprocess, 243.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 57%|████████████████████████████████████████████████████████████████████████████▍                                                          | 103/182 [09:43<06:17,  4.78s/it]

0: 384x640 1 animal, 243.6ms
1: 384x640 (no detections), 243.6ms
2: 384x640 (no detections), 243.6ms
3: 384x640 (no detections), 243.6ms
4: 384x640 (no detections), 243.6ms
5: 384x640 (no detections), 243.6ms
6: 384x640 1 animal, 243.6ms
7: 384x640 (no detections), 243.6ms
8: 384x640 (no detections), 243.6ms
9: 384x640 (no detections), 243.6ms
10: 384x640 (no detections), 243.6ms
11: 384x640 (no detections), 243.6ms
12: 384x640 1 person, 243.6ms
13: 384x640 1 person, 243.6ms
14: 384x640 1 person, 243.6ms
15: 384x640 1 animal, 243.6ms
Speed: 1.7ms preprocess, 243.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 57%|█████████████████████████████████████████████████████████████████████████████▏                                                         | 104/182 [09:48<06:12,  4.78s/it]

0: 384x640 (no detections), 243.9ms
1: 384x640 (no detections), 243.9ms
2: 384x640 (no detections), 243.9ms
3: 384x640 (no detections), 243.9ms
4: 384x640 (no detections), 243.9ms
5: 384x640 (no detections), 243.9ms
6: 384x640 (no detections), 243.9ms
7: 384x640 (no detections), 243.9ms
8: 384x640 (no detections), 243.9ms
9: 384x640 (no detections), 243.9ms
10: 384x640 (no detections), 243.9ms
11: 384x640 (no detections), 243.9ms
12: 384x640 (no detections), 243.9ms
13: 384x640 (no detections), 243.9ms
14: 384x640 (no detections), 243.9ms
15: 384x640 (no detections), 243.9ms
Speed: 1.7ms preprocess, 243.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 58%|█████████████████████████████████████████████████████████████████████████████▉                                                         | 105/182 [09:53<06:08,  4.78s/it]

0: 384x640 (no detections), 244.8ms
1: 384x640 (no detections), 244.8ms
2: 384x640 (no detections), 244.8ms
3: 384x640 (no detections), 244.8ms
4: 384x640 (no detections), 244.8ms
5: 384x640 (no detections), 244.8ms
6: 384x640 (no detections), 244.8ms
7: 384x640 (no detections), 244.8ms
8: 384x640 (no detections), 244.8ms
9: 384x640 (no detections), 244.8ms
10: 384x640 (no detections), 244.8ms
11: 384x640 (no detections), 244.8ms
12: 384x640 (no detections), 244.8ms
13: 384x640 (no detections), 244.8ms
14: 384x640 (no detections), 244.8ms
15: 384x640 (no detections), 244.8ms
Speed: 1.7ms preprocess, 244.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 58%|██████████████████████████████████████████████████████████████████████████████▋                                                        | 106/182 [09:57<06:04,  4.79s/it]

0: 384x640 (no detections), 245.4ms
1: 384x640 (no detections), 245.4ms
2: 384x640 (no detections), 245.4ms
3: 384x640 (no detections), 245.4ms
4: 384x640 (no detections), 245.4ms
5: 384x640 (no detections), 245.4ms
6: 384x640 (no detections), 245.4ms
7: 384x640 (no detections), 245.4ms
8: 384x640 (no detections), 245.4ms
9: 384x640 (no detections), 245.4ms
10: 384x640 (no detections), 245.4ms
11: 384x640 (no detections), 245.4ms
12: 384x640 (no detections), 245.4ms
13: 384x640 (no detections), 245.4ms
14: 384x640 (no detections), 245.4ms
15: 384x640 (no detections), 245.4ms
Speed: 1.7ms preprocess, 245.4ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 59%|███████████████████████████████████████████████████████████████████████████████▎                                                       | 107/182 [10:02<05:59,  4.80s/it]

0: 384x640 (no detections), 244.5ms
1: 384x640 (no detections), 244.5ms
2: 384x640 (no detections), 244.5ms
3: 384x640 (no detections), 244.5ms
4: 384x640 (no detections), 244.5ms
5: 384x640 (no detections), 244.5ms
6: 384x640 (no detections), 244.5ms
7: 384x640 (no detections), 244.5ms
8: 384x640 (no detections), 244.5ms
9: 384x640 2 animals, 244.5ms
10: 384x640 1 animal, 244.5ms
11: 384x640 (no detections), 244.5ms
12: 384x640 (no detections), 244.5ms
13: 384x640 (no detections), 244.5ms
14: 384x640 1 animal, 244.5ms
15: 384x640 1 animal, 244.5ms
Speed: 1.8ms preprocess, 244.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 59%|████████████████████████████████████████████████████████████████████████████████                                                       | 108/182 [10:07<05:54,  4.79s/it]

0: 384x640 (no detections), 245.4ms
1: 384x640 (no detections), 245.4ms
2: 384x640 1 animal, 245.4ms
3: 384x640 2 animals, 245.4ms
4: 384x640 1 animal, 245.4ms
5: 384x640 1 animal, 245.4ms
6: 384x640 1 animal, 245.4ms
7: 384x640 1 animal, 245.4ms
8: 384x640 1 animal, 245.4ms
9: 384x640 2 animals, 245.4ms
10: 384x640 1 animal, 245.4ms
11: 384x640 2 animals, 245.4ms
12: 384x640 1 animal, 245.4ms
13: 384x640 1 animal, 245.4ms
14: 384x640 1 animal, 245.4ms
15: 384x640 2 animals, 245.4ms
Speed: 2.0ms preprocess, 245.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 60%|████████████████████████████████████████████████████████████████████████████████▊                                                      | 109/182 [10:12<05:46,  4.75s/it]

0: 384x640 2 animals, 245.9ms
1: 384x640 2 animals, 245.9ms
2: 384x640 1 animal, 245.9ms
3: 384x640 1 animal, 245.9ms
4: 384x640 1 animal, 245.9ms
5: 384x640 1 animal, 245.9ms
6: 384x640 3 animals, 245.9ms
7: 384x640 1 animal, 245.9ms
8: 384x640 3 animals, 245.9ms
9: 384x640 3 animals, 245.9ms
10: 384x640 3 animals, 245.9ms
11: 384x640 1 animal, 245.9ms
12: 384x640 1 animal, 245.9ms
13: 384x640 1 animal, 245.9ms
14: 384x640 1 animal, 245.9ms
15: 384x640 1 animal, 245.9ms
Speed: 1.7ms preprocess, 245.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 60%|█████████████████████████████████████████████████████████████████████████████████▌                                                     | 110/182 [10:16<05:41,  4.75s/it]

0: 384x640 (no detections), 245.2ms
1: 384x640 (no detections), 245.2ms
2: 384x640 (no detections), 245.2ms
3: 384x640 (no detections), 245.2ms
4: 384x640 (no detections), 245.2ms
5: 384x640 (no detections), 245.2ms
6: 384x640 (no detections), 245.2ms
7: 384x640 (no detections), 245.2ms
8: 384x640 (no detections), 245.2ms
9: 384x640 (no detections), 245.2ms
10: 384x640 2 animals, 245.2ms
11: 384x640 1 animal, 245.2ms
12: 384x640 1 animal, 245.2ms
13: 384x640 1 animal, 245.2ms
14: 384x640 1 animal, 245.2ms
15: 384x640 1 animal, 245.2ms
Speed: 1.7ms preprocess, 245.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 61%|██████████████████████████████████████████████████████████████████████████████████▎                                                    | 111/182 [10:21<05:37,  4.76s/it]

0: 384x640 1 animal, 245.2ms
1: 384x640 (no detections), 245.2ms
2: 384x640 (no detections), 245.2ms
3: 384x640 (no detections), 245.2ms
4: 384x640 (no detections), 245.2ms
5: 384x640 (no detections), 245.2ms
6: 384x640 (no detections), 245.2ms
7: 384x640 (no detections), 245.2ms
8: 384x640 (no detections), 245.2ms
9: 384x640 (no detections), 245.2ms
10: 384x640 (no detections), 245.2ms
11: 384x640 (no detections), 245.2ms
12: 384x640 (no detections), 245.2ms
13: 384x640 (no detections), 245.2ms
14: 384x640 1 animal, 245.2ms
15: 384x640 1 animal, 245.2ms
Speed: 1.7ms preprocess, 245.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 62%|███████████████████████████████████████████████████████████████████████████████████                                                    | 112/182 [10:26<05:33,  4.77s/it]

0: 384x640 1 animal, 244.2ms
1: 384x640 1 animal, 244.2ms
2: 384x640 1 animal, 244.2ms
3: 384x640 1 animal, 244.2ms
4: 384x640 (no detections), 244.2ms
5: 384x640 (no detections), 244.2ms
6: 384x640 (no detections), 244.2ms
7: 384x640 (no detections), 244.2ms
8: 384x640 (no detections), 244.2ms
9: 384x640 (no detections), 244.2ms
10: 384x640 (no detections), 244.2ms
11: 384x640 (no detections), 244.2ms
12: 384x640 1 animal, 244.2ms
13: 384x640 1 animal, 244.2ms
14: 384x640 (no detections), 244.2ms
15: 384x640 (no detections), 244.2ms
Speed: 1.7ms preprocess, 244.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 62%|███████████████████████████████████████████████████████████████████████████████████▊                                                   | 113/182 [10:31<05:29,  4.77s/it]

0: 384x640 (no detections), 247.8ms
1: 384x640 (no detections), 247.8ms
2: 384x640 1 animal, 247.8ms
3: 384x640 1 animal, 247.8ms
4: 384x640 1 animal, 247.8ms
5: 384x640 1 animal, 247.8ms
6: 384x640 1 animal, 247.8ms
7: 384x640 (no detections), 247.8ms
8: 384x640 (no detections), 247.8ms
9: 384x640 (no detections), 247.8ms
10: 384x640 (no detections), 247.8ms
11: 384x640 (no detections), 247.8ms
12: 384x640 1 animal, 247.8ms
13: 384x640 1 animal, 247.8ms
14: 384x640 1 animal, 247.8ms
15: 384x640 1 animal, 247.8ms
Speed: 1.7ms preprocess, 247.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 63%|████████████████████████████████████████████████████████████████████████████████████▌                                                  | 114/182 [10:36<05:26,  4.80s/it]

0: 384x640 1 animal, 238.4ms
1: 384x640 1 animal, 238.4ms
2: 384x640 1 animal, 238.4ms
3: 384x640 1 animal, 238.4ms
4: 384x640 1 animal, 238.4ms
5: 384x640 1 animal, 238.4ms
6: 384x640 1 animal, 238.4ms
7: 384x640 1 animal, 238.4ms
8: 384x640 1 animal, 238.4ms
9: 384x640 1 animal, 238.4ms
10: 384x640 1 animal, 238.4ms
11: 384x640 1 animal, 238.4ms
12: 384x640 (no detections), 238.4ms
13: 384x640 (no detections), 238.4ms
14: 384x640 (no detections), 238.4ms
15: 384x640 (no detections), 238.4ms
Speed: 1.7ms preprocess, 238.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 63%|█████████████████████████████████████████████████████████████████████████████████████▎                                                 | 115/182 [10:40<05:19,  4.78s/it]

0: 384x640 1 animal, 238.8ms
1: 384x640 1 animal, 238.8ms
2: 384x640 1 animal, 238.8ms
3: 384x640 1 animal, 238.8ms
4: 384x640 1 animal, 238.8ms
5: 384x640 2 animals, 238.8ms
6: 384x640 1 animal, 238.8ms
7: 384x640 1 animal, 238.8ms
8: 384x640 1 animal, 238.8ms
9: 384x640 1 animal, 238.8ms
10: 384x640 1 animal, 238.8ms
11: 384x640 1 animal, 238.8ms
12: 384x640 1 animal, 238.8ms
13: 384x640 1 animal, 238.8ms
14: 384x640 1 animal, 238.8ms
15: 384x640 (no detections), 238.8ms
Speed: 1.8ms preprocess, 238.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 64%|██████████████████████████████████████████████████████████████████████████████████████                                                 | 116/182 [10:45<05:14,  4.76s/it]

0: 384x640 (no detections), 239.0ms
1: 384x640 (no detections), 239.0ms
2: 384x640 (no detections), 239.0ms
3: 384x640 (no detections), 239.0ms
4: 384x640 (no detections), 239.0ms
5: 384x640 (no detections), 239.0ms
6: 384x640 (no detections), 239.0ms
7: 384x640 (no detections), 239.0ms
8: 384x640 (no detections), 239.0ms
9: 384x640 (no detections), 239.0ms
10: 384x640 (no detections), 239.0ms
11: 384x640 (no detections), 239.0ms
12: 384x640 (no detections), 239.0ms
13: 384x640 (no detections), 239.0ms
14: 384x640 1 animal, 239.0ms
15: 384x640 1 animal, 239.0ms
Speed: 1.9ms preprocess, 239.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 64%|██████████████████████████████████████████████████████████████████████████████████████▊                                                | 117/182 [10:50<05:08,  4.75s/it]

0: 384x640 1 animal, 242.5ms
1: 384x640 (no detections), 242.5ms
2: 384x640 (no detections), 242.5ms
3: 384x640 (no detections), 242.5ms
4: 384x640 (no detections), 242.5ms
5: 384x640 (no detections), 242.5ms
6: 384x640 (no detections), 242.5ms
7: 384x640 (no detections), 242.5ms
8: 384x640 (no detections), 242.5ms
9: 384x640 (no detections), 242.5ms
10: 384x640 (no detections), 242.5ms
11: 384x640 (no detections), 242.5ms
12: 384x640 (no detections), 242.5ms
13: 384x640 (no detections), 242.5ms
14: 384x640 (no detections), 242.5ms
15: 384x640 (no detections), 242.5ms
Speed: 1.7ms preprocess, 242.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 65%|███████████████████████████████████████████████████████████████████████████████████████▌                                               | 118/182 [10:55<05:04,  4.76s/it]

0: 384x640 (no detections), 245.3ms
1: 384x640 (no detections), 245.3ms
2: 384x640 (no detections), 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 (no detections), 245.3ms
5: 384x640 (no detections), 245.3ms
6: 384x640 (no detections), 245.3ms
7: 384x640 (no detections), 245.3ms
8: 384x640 (no detections), 245.3ms
9: 384x640 (no detections), 245.3ms
10: 384x640 (no detections), 245.3ms
11: 384x640 (no detections), 245.3ms
12: 384x640 (no detections), 245.3ms
13: 384x640 1 animal, 245.3ms
14: 384x640 (no detections), 245.3ms
15: 384x640 (no detections), 245.3ms
Speed: 1.7ms preprocess, 245.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 65%|████████████████████████████████████████████████████████████████████████████████████████▎                                              | 119/182 [10:59<05:00,  4.78s/it]

0: 384x640 1 animal, 247.0ms
1: 384x640 1 animal, 247.0ms
2: 384x640 1 animal, 247.0ms
3: 384x640 1 animal, 247.0ms
4: 384x640 2 animals, 247.0ms
5: 384x640 1 animal, 247.0ms
6: 384x640 (no detections), 247.0ms
7: 384x640 (no detections), 247.0ms
8: 384x640 (no detections), 247.0ms
9: 384x640 1 animal, 247.0ms
10: 384x640 (no detections), 247.0ms
11: 384x640 (no detections), 247.0ms
12: 384x640 (no detections), 247.0ms
13: 384x640 (no detections), 247.0ms
14: 384x640 (no detections), 247.0ms
15: 384x640 (no detections), 247.0ms
Speed: 1.7ms preprocess, 247.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 66%|█████████████████████████████████████████████████████████████████████████████████████████                                              | 120/182 [11:04<04:57,  4.79s/it]

0: 384x640 (no detections), 246.3ms
1: 384x640 1 animal, 246.3ms
2: 384x640 1 animal, 246.3ms
3: 384x640 1 animal, 246.3ms
4: 384x640 (no detections), 246.3ms
5: 384x640 (no detections), 246.3ms
6: 384x640 (no detections), 246.3ms
7: 384x640 (no detections), 246.3ms
8: 384x640 (no detections), 246.3ms
9: 384x640 (no detections), 246.3ms
10: 384x640 1 animal, 246.3ms
11: 384x640 1 animal, 246.3ms
12: 384x640 1 animal, 246.3ms
13: 384x640 1 animal, 246.3ms
14: 384x640 1 animal, 246.3ms
15: 384x640 1 animal, 246.3ms
Speed: 1.7ms preprocess, 246.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 66%|█████████████████████████████████████████████████████████████████████████████████████████▊                                             | 121/182 [11:09<04:51,  4.78s/it]

0: 384x640 1 animal, 245.0ms
1: 384x640 1 animal, 245.0ms
2: 384x640 1 animal, 245.0ms
3: 384x640 1 animal, 245.0ms
4: 384x640 1 animal, 245.0ms
5: 384x640 1 animal, 245.0ms
6: 384x640 1 animal, 245.0ms
7: 384x640 1 animal, 245.0ms
8: 384x640 1 animal, 245.0ms
9: 384x640 2 animals, 245.0ms
10: 384x640 1 animal, 245.0ms
11: 384x640 1 animal, 245.0ms
12: 384x640 1 animal, 245.0ms
13: 384x640 1 animal, 245.0ms
14: 384x640 1 animal, 245.0ms
15: 384x640 1 animal, 245.0ms
Speed: 1.7ms preprocess, 245.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 67%|██████████████████████████████████████████████████████████████████████████████████████████▍                                            | 122/182 [11:14<04:45,  4.76s/it]

0: 384x640 1 animal, 246.3ms
1: 384x640 1 animal, 246.3ms
2: 384x640 1 animal, 246.3ms
3: 384x640 1 animal, 246.3ms
4: 384x640 1 animal, 246.3ms
5: 384x640 1 animal, 246.3ms
6: 384x640 1 animal, 246.3ms
7: 384x640 1 animal, 246.3ms
8: 384x640 1 animal, 246.3ms
9: 384x640 1 animal, 246.3ms
10: 384x640 1 animal, 246.3ms
11: 384x640 1 animal, 246.3ms
12: 384x640 1 animal, 246.3ms
13: 384x640 1 animal, 246.3ms
14: 384x640 1 animal, 246.3ms
15: 384x640 (no detections), 246.3ms
Speed: 2.0ms preprocess, 246.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 68%|███████████████████████████████████████████████████████████████████████████████████████████▏                                           | 123/182 [11:18<04:41,  4.76s/it]

0: 384x640 (no detections), 245.8ms
1: 384x640 (no detections), 245.8ms
2: 384x640 2 animals, 245.8ms
3: 384x640 (no detections), 245.8ms
4: 384x640 1 animal, 245.8ms
5: 384x640 1 animal, 245.8ms
6: 384x640 1 animal, 245.8ms
7: 384x640 1 animal, 245.8ms
8: 384x640 (no detections), 245.8ms
9: 384x640 1 animal, 245.8ms
10: 384x640 1 animal, 245.8ms
11: 384x640 1 animal, 245.8ms
12: 384x640 (no detections), 245.8ms
13: 384x640 (no detections), 245.8ms
14: 384x640 (no detections), 245.8ms
15: 384x640 (no detections), 245.8ms
Speed: 1.7ms preprocess, 245.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 68%|███████████████████████████████████████████████████████████████████████████████████████████▉                                           | 124/182 [11:23<04:37,  4.78s/it]

0: 384x640 (no detections), 245.5ms
1: 384x640 (no detections), 245.5ms
2: 384x640 (no detections), 245.5ms
3: 384x640 (no detections), 245.5ms
4: 384x640 (no detections), 245.5ms
5: 384x640 (no detections), 245.5ms
6: 384x640 (no detections), 245.5ms
7: 384x640 (no detections), 245.5ms
8: 384x640 (no detections), 245.5ms
9: 384x640 (no detections), 245.5ms
10: 384x640 (no detections), 245.5ms
11: 384x640 (no detections), 245.5ms
12: 384x640 (no detections), 245.5ms
13: 384x640 (no detections), 245.5ms
14: 384x640 (no detections), 245.5ms
15: 384x640 (no detections), 245.5ms
Speed: 1.8ms preprocess, 245.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 69%|████████████████████████████████████████████████████████████████████████████████████████████▋                                          | 125/182 [11:28<04:33,  4.79s/it]

0: 384x640 1 animal, 244.5ms
1: 384x640 1 animal, 244.5ms
2: 384x640 1 animal, 244.5ms
3: 384x640 (no detections), 244.5ms
4: 384x640 (no detections), 244.5ms
5: 384x640 (no detections), 244.5ms
6: 384x640 (no detections), 244.5ms
7: 384x640 (no detections), 244.5ms
8: 384x640 (no detections), 244.5ms
9: 384x640 (no detections), 244.5ms
10: 384x640 1 animal, 244.5ms
11: 384x640 1 animal, 244.5ms
12: 384x640 2 animals, 244.5ms
13: 384x640 (no detections), 244.5ms
14: 384x640 (no detections), 244.5ms
15: 384x640 (no detections), 244.5ms
Speed: 1.7ms preprocess, 244.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 69%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 126/182 [11:33<04:28,  4.80s/it]

0: 384x640 (no detections), 246.7ms
1: 384x640 (no detections), 246.7ms
2: 384x640 (no detections), 246.7ms
3: 384x640 (no detections), 246.7ms
4: 384x640 (no detections), 246.7ms
5: 384x640 (no detections), 246.7ms
6: 384x640 (no detections), 246.7ms
7: 384x640 (no detections), 246.7ms
8: 384x640 (no detections), 246.7ms
9: 384x640 (no detections), 246.7ms
10: 384x640 (no detections), 246.7ms
11: 384x640 (no detections), 246.7ms
12: 384x640 (no detections), 246.7ms
13: 384x640 1 animal, 246.7ms
14: 384x640 (no detections), 246.7ms
15: 384x640 (no detections), 246.7ms
Speed: 1.8ms preprocess, 246.7ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 70%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 127/182 [11:38<04:24,  4.81s/it]

0: 384x640 (no detections), 245.7ms
1: 384x640 (no detections), 245.7ms
2: 384x640 (no detections), 245.7ms
3: 384x640 (no detections), 245.7ms
4: 384x640 (no detections), 245.7ms
5: 384x640 1 animal, 245.7ms
6: 384x640 (no detections), 245.7ms
7: 384x640 1 animal, 245.7ms
8: 384x640 (no detections), 245.7ms
9: 384x640 (no detections), 245.7ms
10: 384x640 1 person, 245.7ms
11: 384x640 (no detections), 245.7ms
12: 384x640 (no detections), 245.7ms
13: 384x640 (no detections), 245.7ms
14: 384x640 (no detections), 245.7ms
15: 384x640 (no detections), 245.7ms
Speed: 1.9ms preprocess, 245.7ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 70%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 128/182 [11:43<04:19,  4.81s/it]

0: 384x640 (no detections), 245.6ms
1: 384x640 (no detections), 245.6ms
2: 384x640 (no detections), 245.6ms
3: 384x640 1 animal, 245.6ms
4: 384x640 1 animal, 245.6ms
5: 384x640 (no detections), 245.6ms
6: 384x640 (no detections), 245.6ms
7: 384x640 (no detections), 245.6ms
8: 384x640 (no detections), 245.6ms
9: 384x640 (no detections), 245.6ms
10: 384x640 (no detections), 245.6ms
11: 384x640 (no detections), 245.6ms
12: 384x640 1 animal, 245.6ms
13: 384x640 1 animal, 245.6ms
14: 384x640 1 animal, 245.6ms
15: 384x640 2 animals, 1 person, 245.6ms
Speed: 1.7ms preprocess, 245.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 71%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 129/182 [11:47<04:15,  4.81s/it]

0: 384x640 2 animals, 246.1ms
1: 384x640 1 animal, 246.1ms
2: 384x640 1 animal, 246.1ms
3: 384x640 (no detections), 246.1ms
4: 384x640 1 animal, 246.1ms
5: 384x640 (no detections), 246.1ms
6: 384x640 1 animal, 246.1ms
7: 384x640 (no detections), 246.1ms
8: 384x640 (no detections), 246.1ms
9: 384x640 (no detections), 246.1ms
10: 384x640 (no detections), 246.1ms
11: 384x640 (no detections), 246.1ms
12: 384x640 (no detections), 246.1ms
13: 384x640 (no detections), 246.1ms
14: 384x640 (no detections), 246.1ms
15: 384x640 (no detections), 246.1ms
Speed: 2.1ms preprocess, 246.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 71%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 130/182 [11:52<04:10,  4.82s/it]

0: 384x640 1 animal, 245.3ms
1: 384x640 1 animal, 245.3ms
2: 384x640 1 animal, 245.3ms
3: 384x640 2 animals, 245.3ms
4: 384x640 1 animal, 245.3ms
5: 384x640 1 animal, 245.3ms
6: 384x640 1 animal, 245.3ms
7: 384x640 1 animal, 245.3ms
8: 384x640 1 animal, 245.3ms
9: 384x640 1 animal, 245.3ms
10: 384x640 1 animal, 245.3ms
11: 384x640 1 person, 245.3ms
12: 384x640 1 person, 245.3ms
13: 384x640 1 animal, 1 person, 245.3ms
14: 384x640 3 animals, 245.3ms
15: 384x640 (no detections), 245.3ms
Speed: 1.7ms preprocess, 245.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 72%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 131/182 [11:57<04:06,  4.83s/it]

0: 384x640 (no detections), 245.1ms
1: 384x640 (no detections), 245.1ms
2: 384x640 (no detections), 245.1ms
3: 384x640 (no detections), 245.1ms
4: 384x640 (no detections), 245.1ms
5: 384x640 (no detections), 245.1ms
6: 384x640 (no detections), 245.1ms
7: 384x640 (no detections), 245.1ms
8: 384x640 (no detections), 245.1ms
9: 384x640 (no detections), 245.1ms
10: 384x640 (no detections), 245.1ms
11: 384x640 (no detections), 245.1ms
12: 384x640 (no detections), 245.1ms
13: 384x640 (no detections), 245.1ms
14: 384x640 (no detections), 245.1ms
15: 384x640 (no detections), 245.1ms
Speed: 1.7ms preprocess, 245.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 73%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 132/182 [12:02<04:00,  4.82s/it]

0: 384x640 (no detections), 245.0ms
1: 384x640 (no detections), 245.0ms
2: 384x640 (no detections), 245.0ms
3: 384x640 (no detections), 245.0ms
4: 384x640 (no detections), 245.0ms
5: 384x640 (no detections), 245.0ms
6: 384x640 (no detections), 245.0ms
7: 384x640 (no detections), 245.0ms
8: 384x640 (no detections), 245.0ms
9: 384x640 (no detections), 245.0ms
10: 384x640 (no detections), 245.0ms
11: 384x640 (no detections), 245.0ms
12: 384x640 (no detections), 245.0ms
13: 384x640 (no detections), 245.0ms
14: 384x640 (no detections), 245.0ms
15: 384x640 (no detections), 245.0ms
Speed: 1.8ms preprocess, 245.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 73%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 133/182 [12:07<03:55,  4.81s/it]

0: 384x640 (no detections), 245.5ms
1: 384x640 (no detections), 245.5ms
2: 384x640 (no detections), 245.5ms
3: 384x640 (no detections), 245.5ms
4: 384x640 (no detections), 245.5ms
5: 384x640 (no detections), 245.5ms
6: 384x640 (no detections), 245.5ms
7: 384x640 (no detections), 245.5ms
8: 384x640 (no detections), 245.5ms
9: 384x640 (no detections), 245.5ms
10: 384x640 (no detections), 245.5ms
11: 384x640 (no detections), 245.5ms
12: 384x640 (no detections), 245.5ms
13: 384x640 (no detections), 245.5ms
14: 384x640 (no detections), 245.5ms
15: 384x640 (no detections), 245.5ms
Speed: 1.7ms preprocess, 245.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 74%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 134/182 [12:11<03:51,  4.81s/it]

0: 384x640 (no detections), 245.0ms
1: 384x640 (no detections), 245.0ms
2: 384x640 (no detections), 245.0ms
3: 384x640 (no detections), 245.0ms
4: 384x640 (no detections), 245.0ms
5: 384x640 (no detections), 245.0ms
6: 384x640 (no detections), 245.0ms
7: 384x640 (no detections), 245.0ms
8: 384x640 (no detections), 245.0ms
9: 384x640 (no detections), 245.0ms
10: 384x640 (no detections), 245.0ms
11: 384x640 (no detections), 245.0ms
12: 384x640 (no detections), 245.0ms
13: 384x640 (no detections), 245.0ms
14: 384x640 (no detections), 245.0ms
15: 384x640 (no detections), 245.0ms
Speed: 1.8ms preprocess, 245.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 74%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 135/182 [12:16<03:46,  4.81s/it]

0: 384x640 (no detections), 244.7ms
1: 384x640 (no detections), 244.7ms
2: 384x640 (no detections), 244.7ms
3: 384x640 (no detections), 244.7ms
4: 384x640 (no detections), 244.7ms
5: 384x640 (no detections), 244.7ms
6: 384x640 (no detections), 244.7ms
7: 384x640 (no detections), 244.7ms
8: 384x640 (no detections), 244.7ms
9: 384x640 (no detections), 244.7ms
10: 384x640 (no detections), 244.7ms
11: 384x640 (no detections), 244.7ms
12: 384x640 (no detections), 244.7ms
13: 384x640 (no detections), 244.7ms
14: 384x640 (no detections), 244.7ms
15: 384x640 (no detections), 244.7ms
Speed: 1.7ms preprocess, 244.7ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 136/182 [12:21<03:41,  4.81s/it]

0: 384x640 (no detections), 244.9ms
1: 384x640 (no detections), 244.9ms
2: 384x640 (no detections), 244.9ms
3: 384x640 (no detections), 244.9ms
4: 384x640 1 animal, 244.9ms
5: 384x640 (no detections), 244.9ms
6: 384x640 (no detections), 244.9ms
7: 384x640 (no detections), 244.9ms
8: 384x640 (no detections), 244.9ms
9: 384x640 (no detections), 244.9ms
10: 384x640 (no detections), 244.9ms
11: 384x640 (no detections), 244.9ms
12: 384x640 (no detections), 244.9ms
13: 384x640 (no detections), 244.9ms
14: 384x640 1 animal, 244.9ms
15: 384x640 1 animal, 244.9ms
Speed: 1.9ms preprocess, 244.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 75%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 137/182 [12:26<03:35,  4.80s/it]

0: 384x640 1 animal, 243.0ms
1: 384x640 1 animal, 243.0ms
2: 384x640 1 animal, 243.0ms
3: 384x640 1 animal, 243.0ms
4: 384x640 1 animal, 243.0ms
5: 384x640 1 animal, 243.0ms
6: 384x640 1 animal, 243.0ms
7: 384x640 1 animal, 243.0ms
8: 384x640 2 animals, 243.0ms
9: 384x640 2 animals, 243.0ms
10: 384x640 3 animals, 243.0ms
11: 384x640 3 animals, 243.0ms
12: 384x640 1 animal, 243.0ms
13: 384x640 1 animal, 243.0ms
14: 384x640 1 animal, 243.0ms
15: 384x640 1 animal, 243.0ms
Speed: 1.7ms preprocess, 243.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 138/182 [12:30<03:28,  4.74s/it]

0: 384x640 1 animal, 244.4ms
1: 384x640 1 animal, 244.4ms
2: 384x640 1 animal, 244.4ms
3: 384x640 1 animal, 244.4ms
4: 384x640 1 animal, 244.4ms
5: 384x640 1 animal, 244.4ms
6: 384x640 1 animal, 244.4ms
7: 384x640 2 animals, 244.4ms
8: 384x640 1 animal, 244.4ms
9: 384x640 1 animal, 244.4ms
10: 384x640 1 animal, 244.4ms
11: 384x640 2 animals, 244.4ms
12: 384x640 (no detections), 244.4ms
13: 384x640 (no detections), 244.4ms
14: 384x640 (no detections), 244.4ms
15: 384x640 (no detections), 244.4ms
Speed: 1.7ms preprocess, 244.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                | 139/182 [12:35<03:23,  4.73s/it]

0: 384x640 (no detections), 243.6ms
1: 384x640 (no detections), 243.6ms
2: 384x640 (no detections), 243.6ms
3: 384x640 (no detections), 243.6ms
4: 384x640 (no detections), 243.6ms
5: 384x640 (no detections), 243.6ms
6: 384x640 (no detections), 243.6ms
7: 384x640 (no detections), 243.6ms
8: 384x640 (no detections), 243.6ms
9: 384x640 (no detections), 243.6ms
10: 384x640 (no detections), 243.6ms
11: 384x640 (no detections), 243.6ms
12: 384x640 (no detections), 243.6ms
13: 384x640 (no detections), 243.6ms
14: 384x640 (no detections), 243.6ms
15: 384x640 (no detections), 243.6ms
Speed: 1.7ms preprocess, 243.6ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 140/182 [12:40<03:19,  4.75s/it]

0: 384x640 1 animal, 244.9ms
1: 384x640 1 animal, 244.9ms
2: 384x640 1 animal, 244.9ms
3: 384x640 1 animal, 244.9ms
4: 384x640 1 animal, 244.9ms
5: 384x640 1 animal, 244.9ms
6: 384x640 1 animal, 244.9ms
7: 384x640 1 animal, 244.9ms
8: 384x640 1 animal, 244.9ms
9: 384x640 1 animal, 244.9ms
10: 384x640 (no detections), 244.9ms
11: 384x640 (no detections), 244.9ms
12: 384x640 (no detections), 244.9ms
13: 384x640 (no detections), 244.9ms
14: 384x640 (no detections), 244.9ms
15: 384x640 (no detections), 244.9ms
Speed: 1.8ms preprocess, 244.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 141/182 [12:45<03:15,  4.77s/it]

0: 384x640 (no detections), 244.3ms
1: 384x640 (no detections), 244.3ms
2: 384x640 (no detections), 244.3ms
3: 384x640 (no detections), 244.3ms
4: 384x640 1 animal, 244.3ms
5: 384x640 1 animal, 244.3ms
6: 384x640 2 animals, 244.3ms
7: 384x640 1 animal, 244.3ms
8: 384x640 1 animal, 244.3ms
9: 384x640 1 animal, 244.3ms
10: 384x640 (no detections), 244.3ms
11: 384x640 (no detections), 244.3ms
12: 384x640 (no detections), 244.3ms
13: 384x640 (no detections), 244.3ms
14: 384x640 2 animals, 244.3ms
15: 384x640 1 animal, 244.3ms
Speed: 1.8ms preprocess, 244.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 142/182 [12:50<03:11,  4.78s/it]

0: 384x640 1 animal, 244.8ms
1: 384x640 1 animal, 244.8ms
2: 384x640 1 animal, 244.8ms
3: 384x640 1 animal, 244.8ms
4: 384x640 1 animal, 244.8ms
5: 384x640 (no detections), 244.8ms
6: 384x640 (no detections), 244.8ms
7: 384x640 (no detections), 244.8ms
8: 384x640 1 person, 244.8ms
9: 384x640 1 animal, 244.8ms
10: 384x640 (no detections), 244.8ms
11: 384x640 1 animal, 1 person, 244.8ms
12: 384x640 1 animal, 244.8ms
13: 384x640 1 animal, 244.8ms
14: 384x640 1 animal, 244.8ms
15: 384x640 1 animal, 244.8ms
Speed: 1.7ms preprocess, 244.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 143/182 [12:54<03:06,  4.79s/it]

0: 384x640 1 animal, 245.3ms
1: 384x640 1 animal, 245.3ms
2: 384x640 (no detections), 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 (no detections), 245.3ms
5: 384x640 (no detections), 245.3ms
6: 384x640 (no detections), 245.3ms
7: 384x640 (no detections), 245.3ms
8: 384x640 (no detections), 245.3ms
9: 384x640 (no detections), 245.3ms
10: 384x640 (no detections), 245.3ms
11: 384x640 (no detections), 245.3ms
12: 384x640 (no detections), 245.3ms
13: 384x640 (no detections), 245.3ms
14: 384x640 (no detections), 245.3ms
15: 384x640 (no detections), 245.3ms
Speed: 2.0ms preprocess, 245.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 144/182 [12:59<03:02,  4.81s/it]

0: 384x640 (no detections), 243.8ms
1: 384x640 (no detections), 243.8ms
2: 384x640 (no detections), 243.8ms
3: 384x640 (no detections), 243.8ms
4: 384x640 (no detections), 243.8ms
5: 384x640 (no detections), 243.8ms
6: 384x640 1 animal, 243.8ms
7: 384x640 1 animal, 243.8ms
8: 384x640 (no detections), 243.8ms
9: 384x640 (no detections), 243.8ms
10: 384x640 (no detections), 243.8ms
11: 384x640 (no detections), 243.8ms
12: 384x640 (no detections), 243.8ms
13: 384x640 (no detections), 243.8ms
14: 384x640 (no detections), 243.8ms
15: 384x640 (no detections), 243.8ms
Speed: 1.7ms preprocess, 243.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 145/182 [13:04<02:57,  4.80s/it]

0: 384x640 1 animal, 238.1ms
1: 384x640 1 animal, 238.1ms
2: 384x640 1 animal, 238.1ms
3: 384x640 1 animal, 238.1ms
4: 384x640 (no detections), 238.1ms
5: 384x640 (no detections), 238.1ms
6: 384x640 1 animal, 238.1ms
7: 384x640 1 animal, 238.1ms
8: 384x640 1 animal, 238.1ms
9: 384x640 1 animal, 238.1ms
10: 384x640 1 animal, 238.1ms
11: 384x640 1 animal, 238.1ms
12: 384x640 1 animal, 238.1ms
13: 384x640 1 animal, 238.1ms
14: 384x640 1 animal, 238.1ms
15: 384x640 1 animal, 238.1ms
Speed: 1.7ms preprocess, 238.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 146/182 [13:09<02:51,  4.77s/it]

0: 384x640 1 animal, 241.1ms
1: 384x640 1 animal, 241.1ms
2: 384x640 1 animal, 241.1ms
3: 384x640 1 animal, 241.1ms
4: 384x640 1 animal, 1 person, 241.1ms
5: 384x640 (no detections), 241.1ms
6: 384x640 (no detections), 241.1ms
7: 384x640 (no detections), 241.1ms
8: 384x640 (no detections), 241.1ms
9: 384x640 (no detections), 241.1ms
10: 384x640 (no detections), 241.1ms
11: 384x640 (no detections), 241.1ms
12: 384x640 (no detections), 241.1ms
13: 384x640 (no detections), 241.1ms
14: 384x640 (no detections), 241.1ms
15: 384x640 (no detections), 241.1ms
Speed: 1.7ms preprocess, 241.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 147/182 [13:13<02:46,  4.76s/it]

0: 384x640 (no detections), 246.2ms
1: 384x640 (no detections), 246.2ms
2: 384x640 (no detections), 246.2ms
3: 384x640 (no detections), 246.2ms
4: 384x640 (no detections), 246.2ms
5: 384x640 (no detections), 246.2ms
6: 384x640 (no detections), 246.2ms
7: 384x640 (no detections), 246.2ms
8: 384x640 (no detections), 246.2ms
9: 384x640 (no detections), 246.2ms
10: 384x640 (no detections), 246.2ms
11: 384x640 (no detections), 246.2ms
12: 384x640 (no detections), 246.2ms
13: 384x640 (no detections), 246.2ms
14: 384x640 (no detections), 246.2ms
15: 384x640 (no detections), 246.2ms
Speed: 1.7ms preprocess, 246.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 148/182 [13:18<02:42,  4.78s/it]

0: 384x640 (no detections), 246.9ms
1: 384x640 (no detections), 246.9ms
2: 384x640 (no detections), 246.9ms
3: 384x640 (no detections), 246.9ms
4: 384x640 (no detections), 246.9ms
5: 384x640 (no detections), 246.9ms
6: 384x640 (no detections), 246.9ms
7: 384x640 (no detections), 246.9ms
8: 384x640 (no detections), 246.9ms
9: 384x640 (no detections), 246.9ms
10: 384x640 (no detections), 246.9ms
11: 384x640 (no detections), 246.9ms
12: 384x640 1 animal, 246.9ms
13: 384x640 1 animal, 246.9ms
14: 384x640 1 animal, 246.9ms
15: 384x640 1 animal, 246.9ms
Speed: 1.8ms preprocess, 246.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 149/182 [13:23<02:38,  4.81s/it]

0: 384x640 2 animals, 245.9ms
1: 384x640 1 animal, 245.9ms
2: 384x640 1 animal, 1 person, 245.9ms
3: 384x640 (no detections), 245.9ms
4: 384x640 (no detections), 245.9ms
5: 384x640 (no detections), 245.9ms
6: 384x640 (no detections), 245.9ms
7: 384x640 (no detections), 245.9ms
8: 384x640 (no detections), 245.9ms
9: 384x640 (no detections), 245.9ms
10: 384x640 (no detections), 245.9ms
11: 384x640 (no detections), 245.9ms
12: 384x640 (no detections), 245.9ms
13: 384x640 (no detections), 245.9ms
14: 384x640 (no detections), 245.9ms
15: 384x640 (no detections), 245.9ms
Speed: 1.7ms preprocess, 245.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 150/182 [13:28<02:34,  4.82s/it]

0: 384x640 (no detections), 247.3ms
1: 384x640 (no detections), 247.3ms
2: 384x640 (no detections), 247.3ms
3: 384x640 (no detections), 247.3ms
4: 384x640 (no detections), 247.3ms
5: 384x640 (no detections), 247.3ms
6: 384x640 (no detections), 247.3ms
7: 384x640 (no detections), 247.3ms
8: 384x640 (no detections), 247.3ms
9: 384x640 (no detections), 247.3ms
10: 384x640 (no detections), 247.3ms
11: 384x640 (no detections), 247.3ms
12: 384x640 (no detections), 247.3ms
13: 384x640 (no detections), 247.3ms
14: 384x640 (no detections), 247.3ms
15: 384x640 (no detections), 247.3ms
Speed: 1.8ms preprocess, 247.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 151/182 [13:33<02:29,  4.83s/it]

0: 384x640 (no detections), 243.9ms
1: 384x640 (no detections), 243.9ms
2: 384x640 (no detections), 243.9ms
3: 384x640 (no detections), 243.9ms
4: 384x640 (no detections), 243.9ms
5: 384x640 (no detections), 243.9ms
6: 384x640 (no detections), 243.9ms
7: 384x640 (no detections), 243.9ms
8: 384x640 (no detections), 243.9ms
9: 384x640 (no detections), 243.9ms
10: 384x640 (no detections), 243.9ms
11: 384x640 (no detections), 243.9ms
12: 384x640 (no detections), 243.9ms
13: 384x640 (no detections), 243.9ms
14: 384x640 (no detections), 243.9ms
15: 384x640 1 person, 243.9ms
Speed: 1.7ms preprocess, 243.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 152/182 [13:38<02:24,  4.82s/it]

0: 384x640 (no detections), 247.3ms
1: 384x640 (no detections), 247.3ms
2: 384x640 (no detections), 247.3ms
3: 384x640 (no detections), 247.3ms
4: 384x640 1 animal, 247.3ms
5: 384x640 (no detections), 247.3ms
6: 384x640 (no detections), 247.3ms
7: 384x640 (no detections), 247.3ms
8: 384x640 1 animal, 247.3ms
9: 384x640 1 animal, 247.3ms
10: 384x640 1 animal, 247.3ms
11: 384x640 1 animal, 247.3ms
12: 384x640 1 animal, 247.3ms
13: 384x640 1 animal, 247.3ms
14: 384x640 1 animal, 247.3ms
15: 384x640 1 animal, 247.3ms
Speed: 1.8ms preprocess, 247.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 153/182 [13:42<02:19,  4.81s/it]

0: 384x640 1 animal, 246.1ms
1: 384x640 1 animal, 246.1ms
2: 384x640 1 animal, 246.1ms
3: 384x640 1 person, 246.1ms
4: 384x640 (no detections), 246.1ms
5: 384x640 (no detections), 246.1ms
6: 384x640 1 animal, 246.1ms
7: 384x640 1 animal, 246.1ms
8: 384x640 1 animal, 246.1ms
9: 384x640 (no detections), 246.1ms
10: 384x640 (no detections), 246.1ms
11: 384x640 (no detections), 246.1ms
12: 384x640 1 animal, 246.1ms
13: 384x640 1 animal, 246.1ms
14: 384x640 1 person, 246.1ms
15: 384x640 (no detections), 246.1ms
Speed: 1.8ms preprocess, 246.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 154/182 [13:47<02:14,  4.82s/it]

0: 384x640 (no detections), 245.5ms
1: 384x640 (no detections), 245.5ms
2: 384x640 (no detections), 245.5ms
3: 384x640 (no detections), 245.5ms
4: 384x640 (no detections), 245.5ms
5: 384x640 (no detections), 245.5ms
6: 384x640 (no detections), 245.5ms
7: 384x640 (no detections), 245.5ms
8: 384x640 (no detections), 245.5ms
9: 384x640 (no detections), 245.5ms
10: 384x640 (no detections), 245.5ms
11: 384x640 (no detections), 245.5ms
12: 384x640 (no detections), 245.5ms
13: 384x640 (no detections), 245.5ms
14: 384x640 (no detections), 245.5ms
15: 384x640 (no detections), 245.5ms
Speed: 1.8ms preprocess, 245.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 155/182 [13:52<02:10,  4.84s/it]

0: 384x640 1 animal, 244.7ms
1: 384x640 (no detections), 244.7ms
2: 384x640 1 animal, 244.7ms
3: 384x640 (no detections), 244.7ms
4: 384x640 2 animals, 244.7ms
5: 384x640 1 animal, 244.7ms
6: 384x640 (no detections), 244.7ms
7: 384x640 (no detections), 244.7ms
8: 384x640 1 animal, 244.7ms
9: 384x640 (no detections), 244.7ms
10: 384x640 (no detections), 244.7ms
11: 384x640 (no detections), 244.7ms
12: 384x640 (no detections), 244.7ms
13: 384x640 (no detections), 244.7ms
14: 384x640 (no detections), 244.7ms
15: 384x640 (no detections), 244.7ms
Speed: 1.8ms preprocess, 244.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 156/182 [13:57<02:05,  4.83s/it]

0: 384x640 (no detections), 246.7ms
1: 384x640 (no detections), 246.7ms
2: 384x640 (no detections), 246.7ms
3: 384x640 (no detections), 246.7ms
4: 384x640 1 animal, 246.7ms
5: 384x640 1 animal, 246.7ms
6: 384x640 1 animal, 246.7ms
7: 384x640 1 animal, 246.7ms
8: 384x640 1 animal, 246.7ms
9: 384x640 2 animals, 246.7ms
10: 384x640 2 animals, 246.7ms
11: 384x640 1 animal, 246.7ms
12: 384x640 (no detections), 246.7ms
13: 384x640 (no detections), 246.7ms
14: 384x640 3 animals, 246.7ms
15: 384x640 2 animals, 246.7ms
Speed: 1.9ms preprocess, 246.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 157/182 [14:02<02:01,  4.85s/it]

0: 384x640 1 animal, 243.9ms
1: 384x640 1 animal, 243.9ms
2: 384x640 (no detections), 243.9ms
3: 384x640 1 animal, 243.9ms
4: 384x640 1 animal, 243.9ms
5: 384x640 2 animals, 243.9ms
6: 384x640 (no detections), 243.9ms
7: 384x640 (no detections), 243.9ms
8: 384x640 (no detections), 243.9ms
9: 384x640 (no detections), 243.9ms
10: 384x640 (no detections), 243.9ms
11: 384x640 (no detections), 243.9ms
12: 384x640 (no detections), 243.9ms
13: 384x640 (no detections), 243.9ms
14: 384x640 (no detections), 243.9ms
15: 384x640 (no detections), 243.9ms
Speed: 2.0ms preprocess, 243.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 158/182 [14:07<01:56,  4.85s/it]

0: 384x640 (no detections), 245.8ms
1: 384x640 (no detections), 245.8ms
2: 384x640 (no detections), 245.8ms
3: 384x640 (no detections), 245.8ms
4: 384x640 (no detections), 245.8ms
5: 384x640 (no detections), 245.8ms
6: 384x640 (no detections), 245.8ms
7: 384x640 (no detections), 245.8ms
8: 384x640 (no detections), 245.8ms
9: 384x640 (no detections), 245.8ms
10: 384x640 (no detections), 245.8ms
11: 384x640 (no detections), 245.8ms
12: 384x640 (no detections), 245.8ms
13: 384x640 (no detections), 245.8ms
14: 384x640 (no detections), 245.8ms
15: 384x640 1 animal, 245.8ms
Speed: 1.9ms preprocess, 245.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 159/182 [14:12<01:51,  4.85s/it]

0: 384x640 (no detections), 244.6ms
1: 384x640 (no detections), 244.6ms
2: 384x640 (no detections), 244.6ms
3: 384x640 (no detections), 244.6ms
4: 384x640 (no detections), 244.6ms
5: 384x640 (no detections), 244.6ms
6: 384x640 1 animal, 244.6ms
7: 384x640 1 animal, 244.6ms
8: 384x640 1 animal, 244.6ms
9: 384x640 1 animal, 244.6ms
10: 384x640 1 animal, 244.6ms
11: 384x640 1 animal, 244.6ms
12: 384x640 1 animal, 244.6ms
13: 384x640 1 animal, 244.6ms
14: 384x640 1 animal, 244.6ms
15: 384x640 1 animal, 244.6ms
Speed: 1.8ms preprocess, 244.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                | 160/182 [14:16<01:46,  4.85s/it]

0: 384x640 (no detections), 246.2ms
1: 384x640 1 animal, 246.2ms
2: 384x640 (no detections), 246.2ms
3: 384x640 2 animals, 246.2ms
4: 384x640 1 animal, 246.2ms
5: 384x640 (no detections), 246.2ms
6: 384x640 2 animals, 246.2ms
7: 384x640 (no detections), 246.2ms
8: 384x640 (no detections), 246.2ms
9: 384x640 (no detections), 246.2ms
10: 384x640 (no detections), 246.2ms
11: 384x640 2 animals, 246.2ms
12: 384x640 (no detections), 246.2ms
13: 384x640 2 animals, 246.2ms
14: 384x640 1 animal, 246.2ms
15: 384x640 (no detections), 246.2ms
Speed: 1.8ms preprocess, 246.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 161/182 [14:21<01:42,  4.86s/it]

0: 384x640 1 animal, 244.9ms
1: 384x640 1 animal, 244.9ms
2: 384x640 1 animal, 244.9ms
3: 384x640 (no detections), 244.9ms
4: 384x640 1 animal, 244.9ms
5: 384x640 1 animal, 244.9ms
6: 384x640 1 animal, 244.9ms
7: 384x640 1 animal, 244.9ms
8: 384x640 1 animal, 244.9ms
9: 384x640 1 animal, 244.9ms
10: 384x640 1 animal, 244.9ms
11: 384x640 1 animal, 244.9ms
12: 384x640 (no detections), 244.9ms
13: 384x640 (no detections), 244.9ms
14: 384x640 1 animal, 244.9ms
15: 384x640 1 animal, 244.9ms
Speed: 1.8ms preprocess, 244.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 162/182 [14:26<01:37,  4.86s/it]

0: 384x640 1 animal, 245.2ms
1: 384x640 1 animal, 245.2ms
2: 384x640 1 animal, 245.2ms
3: 384x640 1 animal, 245.2ms
4: 384x640 1 animal, 245.2ms
5: 384x640 1 animal, 245.2ms
6: 384x640 1 animal, 245.2ms
7: 384x640 (no detections), 245.2ms
8: 384x640 1 animal, 245.2ms
9: 384x640 1 animal, 245.2ms
10: 384x640 1 animal, 245.2ms
11: 384x640 1 animal, 245.2ms
12: 384x640 1 animal, 245.2ms
13: 384x640 1 animal, 245.2ms
14: 384x640 1 animal, 245.2ms
15: 384x640 2 animals, 245.2ms
Speed: 1.7ms preprocess, 245.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 163/182 [14:31<01:32,  4.87s/it]

0: 384x640 2 animals, 243.4ms
1: 384x640 2 animals, 243.4ms
2: 384x640 1 animal, 243.4ms
3: 384x640 (no detections), 243.4ms
4: 384x640 1 animal, 243.4ms
5: 384x640 1 animal, 243.4ms
6: 384x640 (no detections), 243.4ms
7: 384x640 1 animal, 243.4ms
8: 384x640 1 animal, 243.4ms
9: 384x640 1 animal, 243.4ms
10: 384x640 1 animal, 243.4ms
11: 384x640 1 animal, 243.4ms
12: 384x640 (no detections), 243.4ms
13: 384x640 (no detections), 243.4ms
14: 384x640 (no detections), 243.4ms
15: 384x640 1 animal, 243.4ms
Speed: 1.7ms preprocess, 243.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 164/182 [14:36<01:27,  4.85s/it]

0: 384x640 (no detections), 243.5ms
1: 384x640 (no detections), 243.5ms
2: 384x640 1 animal, 243.5ms
3: 384x640 1 animal, 243.5ms
4: 384x640 1 animal, 243.5ms
5: 384x640 (no detections), 243.5ms
6: 384x640 1 animal, 243.5ms
7: 384x640 (no detections), 243.5ms
8: 384x640 (no detections), 243.5ms
9: 384x640 (no detections), 243.5ms
10: 384x640 (no detections), 243.5ms
11: 384x640 (no detections), 243.5ms
12: 384x640 (no detections), 243.5ms
13: 384x640 (no detections), 243.5ms
14: 384x640 (no detections), 243.5ms
15: 384x640 (no detections), 243.5ms
Speed: 2.0ms preprocess, 243.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 165/182 [14:41<01:22,  4.83s/it]

0: 384x640 1 animal, 244.1ms
1: 384x640 1 animal, 244.1ms
2: 384x640 1 animal, 244.1ms
3: 384x640 1 animal, 244.1ms
4: 384x640 1 animal, 244.1ms
5: 384x640 1 animal, 244.1ms
6: 384x640 2 animals, 244.1ms
7: 384x640 1 animal, 244.1ms
8: 384x640 (no detections), 244.1ms
9: 384x640 1 animal, 244.1ms
10: 384x640 (no detections), 244.1ms
11: 384x640 (no detections), 244.1ms
12: 384x640 (no detections), 244.1ms
13: 384x640 (no detections), 244.1ms
14: 384x640 (no detections), 244.1ms
15: 384x640 (no detections), 244.1ms
Speed: 1.8ms preprocess, 244.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 166/182 [14:45<01:17,  4.83s/it]

0: 384x640 (no detections), 243.4ms
1: 384x640 (no detections), 243.4ms
2: 384x640 (no detections), 243.4ms
3: 384x640 (no detections), 243.4ms
4: 384x640 (no detections), 243.4ms
5: 384x640 (no detections), 243.4ms
6: 384x640 (no detections), 243.4ms
7: 384x640 (no detections), 243.4ms
8: 384x640 (no detections), 243.4ms
9: 384x640 (no detections), 243.4ms
10: 384x640 (no detections), 243.4ms
11: 384x640 (no detections), 243.4ms
12: 384x640 (no detections), 243.4ms
13: 384x640 (no detections), 243.4ms
14: 384x640 (no detections), 243.4ms
15: 384x640 (no detections), 243.4ms
Speed: 1.8ms preprocess, 243.4ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 167/182 [14:50<01:12,  4.83s/it]

0: 384x640 (no detections), 242.5ms
1: 384x640 (no detections), 242.5ms
2: 384x640 (no detections), 242.5ms
3: 384x640 (no detections), 242.5ms
4: 384x640 (no detections), 242.5ms
5: 384x640 (no detections), 242.5ms
6: 384x640 (no detections), 242.5ms
7: 384x640 (no detections), 242.5ms
8: 384x640 (no detections), 242.5ms
9: 384x640 (no detections), 242.5ms
10: 384x640 (no detections), 242.5ms
11: 384x640 (no detections), 242.5ms
12: 384x640 (no detections), 242.5ms
13: 384x640 (no detections), 242.5ms
14: 384x640 (no detections), 242.5ms
15: 384x640 (no detections), 242.5ms
Speed: 1.8ms preprocess, 242.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 168/182 [14:55<01:07,  4.82s/it]

0: 384x640 (no detections), 245.5ms
1: 384x640 (no detections), 245.5ms
2: 384x640 1 animal, 245.5ms
3: 384x640 2 animals, 245.5ms
4: 384x640 (no detections), 245.5ms
5: 384x640 1 animal, 245.5ms
6: 384x640 2 animals, 245.5ms
7: 384x640 1 animal, 245.5ms
8: 384x640 (no detections), 245.5ms
9: 384x640 (no detections), 245.5ms
10: 384x640 (no detections), 245.5ms
11: 384x640 (no detections), 245.5ms
12: 384x640 (no detections), 245.5ms
13: 384x640 (no detections), 245.5ms
14: 384x640 (no detections), 245.5ms
15: 384x640 (no detections), 245.5ms
Speed: 1.7ms preprocess, 245.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 169/182 [15:00<01:02,  4.84s/it]

0: 384x640 (no detections), 242.1ms
1: 384x640 (no detections), 242.1ms
2: 384x640 (no detections), 242.1ms
3: 384x640 (no detections), 242.1ms
4: 384x640 (no detections), 242.1ms
5: 384x640 (no detections), 242.1ms
6: 384x640 (no detections), 242.1ms
7: 384x640 1 animal, 242.1ms
8: 384x640 (no detections), 242.1ms
9: 384x640 (no detections), 242.1ms
10: 384x640 (no detections), 242.1ms
11: 384x640 (no detections), 242.1ms
12: 384x640 (no detections), 242.1ms
13: 384x640 (no detections), 242.1ms
14: 384x640 1 animal, 242.1ms
15: 384x640 (no detections), 242.1ms
Speed: 1.7ms preprocess, 242.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 170/182 [15:05<00:57,  4.82s/it]

0: 384x640 2 animals, 242.9ms
1: 384x640 1 animal, 242.9ms
2: 384x640 (no detections), 242.9ms
3: 384x640 (no detections), 242.9ms
4: 384x640 (no detections), 242.9ms
5: 384x640 (no detections), 242.9ms
6: 384x640 (no detections), 242.9ms
7: 384x640 (no detections), 242.9ms
8: 384x640 (no detections), 242.9ms
9: 384x640 1 animal, 242.9ms
10: 384x640 2 animals, 242.9ms
11: 384x640 1 animal, 242.9ms
12: 384x640 2 animals, 242.9ms
13: 384x640 2 animals, 242.9ms
14: 384x640 1 animal, 242.9ms
15: 384x640 1 animal, 242.9ms
Speed: 2.0ms preprocess, 242.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 171/182 [15:10<00:52,  4.81s/it]

0: 384x640 1 animal, 244.2ms
1: 384x640 1 animal, 244.2ms
2: 384x640 1 animal, 244.2ms
3: 384x640 1 animal, 244.2ms
4: 384x640 (no detections), 244.2ms
5: 384x640 1 person, 244.2ms
6: 384x640 1 animal, 244.2ms
7: 384x640 1 animal, 244.2ms
8: 384x640 (no detections), 244.2ms
9: 384x640 (no detections), 244.2ms
10: 384x640 1 animal, 244.2ms
11: 384x640 (no detections), 244.2ms
12: 384x640 (no detections), 244.2ms
13: 384x640 1 animal, 244.2ms
14: 384x640 (no detections), 244.2ms
15: 384x640 (no detections), 244.2ms
Speed: 2.0ms preprocess, 244.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 172/182 [15:14<00:48,  4.81s/it]

0: 384x640 (no detections), 238.5ms
1: 384x640 (no detections), 238.5ms
2: 384x640 (no detections), 238.5ms
3: 384x640 (no detections), 238.5ms
4: 384x640 (no detections), 238.5ms
5: 384x640 (no detections), 238.5ms
6: 384x640 (no detections), 238.5ms
7: 384x640 (no detections), 238.5ms
8: 384x640 (no detections), 238.5ms
9: 384x640 (no detections), 238.5ms
10: 384x640 (no detections), 238.5ms
11: 384x640 (no detections), 238.5ms
12: 384x640 (no detections), 238.5ms
13: 384x640 (no detections), 238.5ms
14: 384x640 (no detections), 238.5ms
15: 384x640 (no detections), 238.5ms
Speed: 1.9ms preprocess, 238.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 173/182 [15:19<00:43,  4.78s/it]

0: 384x640 (no detections), 245.7ms
1: 384x640 (no detections), 245.7ms
2: 384x640 (no detections), 245.7ms
3: 384x640 (no detections), 245.7ms
4: 384x640 (no detections), 245.7ms
5: 384x640 (no detections), 245.7ms
6: 384x640 (no detections), 245.7ms
7: 384x640 (no detections), 245.7ms
8: 384x640 (no detections), 245.7ms
9: 384x640 (no detections), 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 (no detections), 245.7ms
12: 384x640 1 animal, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 (no detections), 245.7ms
Speed: 1.8ms preprocess, 245.7ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 174/182 [15:24<00:38,  4.79s/it]

0: 384x640 (no detections), 243.2ms
1: 384x640 (no detections), 243.2ms
2: 384x640 (no detections), 243.2ms
3: 384x640 (no detections), 243.2ms
4: 384x640 (no detections), 243.2ms
5: 384x640 (no detections), 243.2ms
6: 384x640 (no detections), 243.2ms
7: 384x640 (no detections), 243.2ms
8: 384x640 (no detections), 243.2ms
9: 384x640 (no detections), 243.2ms
10: 384x640 (no detections), 243.2ms
11: 384x640 (no detections), 243.2ms
12: 384x640 (no detections), 243.2ms
13: 384x640 (no detections), 243.2ms
14: 384x640 (no detections), 243.2ms
15: 384x640 (no detections), 243.2ms
Speed: 1.7ms preprocess, 243.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 175/182 [15:29<00:33,  4.79s/it]

0: 384x640 3 animals, 244.0ms
1: 384x640 1 animal, 244.0ms
2: 384x640 1 animal, 244.0ms
3: 384x640 2 animals, 244.0ms
4: 384x640 3 animals, 244.0ms
5: 384x640 2 animals, 244.0ms
6: 384x640 1 animal, 244.0ms
7: 384x640 2 animals, 244.0ms
8: 384x640 1 animal, 244.0ms
9: 384x640 1 animal, 244.0ms
10: 384x640 (no detections), 244.0ms
11: 384x640 1 animal, 244.0ms
12: 384x640 (no detections), 244.0ms
13: 384x640 (no detections), 244.0ms
14: 384x640 (no detections), 244.0ms
15: 384x640 (no detections), 244.0ms
Speed: 1.7ms preprocess, 244.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 176/182 [15:33<00:28,  4.79s/it]

0: 384x640 (no detections), 245.3ms
1: 384x640 (no detections), 245.3ms
2: 384x640 (no detections), 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 (no detections), 245.3ms
5: 384x640 (no detections), 245.3ms
6: 384x640 1 animal, 245.3ms
7: 384x640 (no detections), 245.3ms
8: 384x640 1 animal, 245.3ms
9: 384x640 1 animal, 245.3ms
10: 384x640 1 animal, 245.3ms
11: 384x640 1 animal, 245.3ms
12: 384x640 (no detections), 245.3ms
13: 384x640 2 animals, 245.3ms
14: 384x640 (no detections), 245.3ms
15: 384x640 (no detections), 245.3ms
Speed: 1.9ms preprocess, 245.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 177/182 [15:38<00:23,  4.79s/it]

0: 384x640 (no detections), 242.6ms
1: 384x640 (no detections), 242.6ms
2: 384x640 (no detections), 242.6ms
3: 384x640 (no detections), 242.6ms
4: 384x640 (no detections), 242.6ms
5: 384x640 (no detections), 242.6ms
6: 384x640 (no detections), 242.6ms
7: 384x640 (no detections), 242.6ms
8: 384x640 1 animal, 242.6ms
9: 384x640 1 animal, 242.6ms
10: 384x640 1 animal, 242.6ms
11: 384x640 1 animal, 242.6ms
12: 384x640 1 animal, 242.6ms
13: 384x640 1 animal, 242.6ms
14: 384x640 1 animal, 242.6ms
15: 384x640 1 animal, 242.6ms
Speed: 1.9ms preprocess, 242.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 178/182 [15:43<00:19,  4.77s/it]

0: 384x640 1 animal, 245.7ms
1: 384x640 1 animal, 245.7ms
2: 384x640 1 animal, 245.7ms
3: 384x640 (no detections), 245.7ms
4: 384x640 1 animal, 245.7ms
5: 384x640 1 animal, 245.7ms
6: 384x640 1 animal, 245.7ms
7: 384x640 1 animal, 245.7ms
8: 384x640 1 animal, 245.7ms
9: 384x640 1 animal, 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 1 animal, 245.7ms
12: 384x640 (no detections), 245.7ms
13: 384x640 (no detections), 245.7ms
14: 384x640 (no detections), 245.7ms
15: 384x640 (no detections), 245.7ms
Speed: 1.9ms preprocess, 245.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 179/182 [15:48<00:14,  4.78s/it]

0: 384x640 (no detections), 245.2ms
1: 384x640 (no detections), 245.2ms
2: 384x640 (no detections), 245.2ms
3: 384x640 (no detections), 245.2ms
4: 384x640 (no detections), 245.2ms
5: 384x640 (no detections), 245.2ms
6: 384x640 1 animal, 245.2ms
7: 384x640 1 animal, 245.2ms
8: 384x640 1 animal, 245.2ms
9: 384x640 1 animal, 245.2ms
10: 384x640 1 animal, 245.2ms
11: 384x640 1 animal, 245.2ms
12: 384x640 1 animal, 245.2ms
13: 384x640 1 animal, 245.2ms
14: 384x640 (no detections), 245.2ms
15: 384x640 (no detections), 245.2ms
Speed: 1.7ms preprocess, 245.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 180/182 [15:53<00:09,  4.79s/it]

0: 384x640 1 animal, 245.7ms
1: 384x640 1 animal, 245.7ms
2: 384x640 1 animal, 245.7ms
3: 384x640 3 animals, 245.7ms
4: 384x640 2 animals, 245.7ms
5: 384x640 2 animals, 245.7ms
6: 384x640 1 animal, 245.7ms
7: 384x640 2 animals, 245.7ms
8: 384x640 (no detections), 245.7ms
9: 384x640 2 animals, 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 1 animal, 245.7ms
12: 384x640 1 animal, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 1 animal, 245.7ms
Speed: 1.9ms preprocess, 245.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 181/182 [15:57<00:04,  4.80s/it]

0: 384x640 1 animal, 237.9ms
1: 384x640 1 animal, 237.9ms
2: 384x640 1 animal, 237.9ms
3: 384x640 1 animal, 237.9ms
4: 384x640 1 animal, 237.9ms
5: 384x640 1 animal, 237.9ms
6: 384x640 1 animal, 237.9ms
7: 384x640 1 animal, 237.9ms
8: 384x640 1 animal, 237.9ms
9: 384x640 1 animal, 237.9ms
10: 384x640 1 animal, 237.9ms
11: 384x640 1 animal, 237.9ms
12: 384x640 1 animal, 237.9ms
13: 384x640 1 animal, 237.9ms
Speed: 1.9ms preprocess, 237.9ms inference, 0.4ms postprocess per image at shape (14, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 182/182 [16:02<00:00,  5.29s/it]

Detecting images from ODOCOILEUS_VIRGINIANUS_2022_extracted

  0%|                                                                                                                                                  | 0/29 [00:00<?, ?it/s]

0: 640x640 (no detections), 411.7ms
1: 640x640 1 animal, 411.7ms
2: 640x640 1 animal, 411.7ms
3: 640x640 1 animal, 411.7ms
4: 640x640 1 animal, 411.7ms
5: 640x640 1 animal, 411.7ms
6: 640x640 1 animal, 411.7ms
7: 640x640 1 animal, 411.7ms
8: 640x640 1 animal, 411.7ms
9: 640x640 1 animal, 411.7ms
10: 640x640 1 animal, 411.7ms
11: 640x640 1 animal, 411.7ms
12: 640x640 1 animal, 411.7ms
13: 640x640 1 animal, 411.7ms
14: 640x640 1 animal, 411.7ms
15: 640x640 1 animal, 411.7ms
Speed: 2.7ms preprocess, 411.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  3%|████▊                                                                                                                                     | 1/29 [00:07<03:24,  7.29s/it]

0: 640x640 1 animal, 411.5ms
1: 640x640 1 animal, 411.5ms
2: 640x640 1 animal, 411.5ms
3: 640x640 1 animal, 411.5ms
4: 640x640 1 animal, 411.5ms
5: 640x640 1 animal, 411.5ms
6: 640x640 1 animal, 411.5ms
7: 640x640 1 animal, 411.5ms
8: 640x640 1 animal, 411.5ms
9: 640x640 1 animal, 411.5ms
10: 640x640 1 animal, 411.5ms
11: 640x640 1 animal, 411.5ms
12: 640x640 1 animal, 411.5ms
13: 640x640 1 animal, 411.5ms
14: 640x640 1 animal, 411.5ms
15: 640x640 1 animal, 411.5ms
Speed: 2.6ms preprocess, 411.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  7%|█████████▌                                                                                                                                | 2/29 [00:14<03:16,  7.29s/it]

0: 640x640 1 animal, 413.8ms
1: 640x640 1 animal, 413.8ms
2: 640x640 1 animal, 413.8ms
3: 640x640 (no detections), 413.8ms
4: 640x640 (no detections), 413.8ms
5: 640x640 (no detections), 413.8ms
6: 640x640 (no detections), 413.8ms
7: 640x640 (no detections), 413.8ms
8: 640x640 1 animal, 413.8ms
9: 640x640 2 animals, 413.8ms
10: 640x640 2 animals, 413.8ms
11: 640x640 2 animals, 413.8ms
12: 640x640 2 animals, 413.8ms
13: 640x640 2 animals, 413.8ms
14: 640x640 1 animal, 413.8ms
15: 640x640 1 animal, 413.8ms
Speed: 2.7ms preprocess, 413.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 10%|██████████████▎                                                                                                                           | 3/29 [00:21<03:10,  7.32s/it]

0: 640x640 2 animals, 411.5ms
1: 640x640 2 animals, 411.5ms
2: 640x640 (no detections), 411.5ms
3: 640x640 2 animals, 411.5ms
4: 640x640 1 animal, 411.5ms
5: 640x640 1 animal, 411.5ms
6: 640x640 1 animal, 411.5ms
7: 640x640 (no detections), 411.5ms
8: 640x640 (no detections), 411.5ms
9: 640x640 (no detections), 411.5ms
10: 640x640 (no detections), 411.5ms
11: 640x640 2 animals, 411.5ms
12: 640x640 1 animal, 411.5ms
13: 640x640 1 animal, 411.5ms
14: 640x640 1 animal, 411.5ms
15: 640x640 1 animal, 411.5ms
Speed: 2.6ms preprocess, 411.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 14%|███████████████████                                                                                                                       | 4/29 [00:29<03:03,  7.32s/it]

0: 384x640 1 animal, 242.2ms
1: 384x640 1 animal, 242.2ms
2: 384x640 1 animal, 242.2ms
3: 384x640 1 animal, 242.2ms
4: 384x640 1 animal, 242.2ms
5: 384x640 1 animal, 242.2ms
6: 384x640 1 animal, 242.2ms
7: 384x640 1 animal, 242.2ms
8: 384x640 1 animal, 242.2ms
9: 384x640 1 animal, 242.2ms
10: 384x640 1 animal, 242.2ms
11: 384x640 1 animal, 242.2ms
12: 384x640 1 animal, 242.2ms
13: 384x640 1 animal, 242.2ms
14: 384x640 1 animal, 242.2ms
15: 384x640 1 animal, 242.2ms
Speed: 1.7ms preprocess, 242.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 17%|███████████████████████▊                                                                                                                  | 5/29 [00:33<02:29,  6.23s/it]

0: 384x640 1 animal, 244.4ms
1: 384x640 1 animal, 244.4ms
2: 384x640 1 animal, 244.4ms
3: 384x640 1 animal, 244.4ms
4: 384x640 1 animal, 244.4ms
5: 384x640 1 animal, 244.4ms
6: 384x640 1 animal, 244.4ms
7: 384x640 1 animal, 244.4ms
8: 384x640 1 animal, 244.4ms
9: 384x640 1 animal, 244.4ms
10: 384x640 1 animal, 244.4ms
11: 384x640 1 animal, 244.4ms
12: 384x640 1 animal, 244.4ms
13: 384x640 1 animal, 244.4ms
14: 384x640 1 animal, 244.4ms
15: 384x640 1 animal, 244.4ms
Speed: 1.7ms preprocess, 244.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 21%|████████████████████████████▌                                                                                                             | 6/29 [00:37<02:08,  5.58s/it]

0: 640x640 1 animal, 416.2ms
1: 640x640 1 animal, 416.2ms
2: 640x640 1 animal, 416.2ms
3: 640x640 1 animal, 416.2ms
4: 640x640 1 animal, 416.2ms
5: 640x640 1 animal, 416.2ms
6: 640x640 1 animal, 416.2ms
7: 640x640 1 animal, 416.2ms
8: 640x640 1 animal, 416.2ms
9: 640x640 1 animal, 416.2ms
10: 640x640 1 animal, 416.2ms
11: 640x640 1 animal, 416.2ms
12: 640x640 1 animal, 416.2ms
13: 640x640 1 animal, 416.2ms
14: 640x640 1 animal, 416.2ms
15: 640x640 1 animal, 416.2ms
Speed: 2.8ms preprocess, 416.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 24%|█████████████████████████████████▎                                                                                                        | 7/29 [00:45<02:16,  6.21s/it]

0: 384x640 1 animal, 247.7ms
1: 384x640 1 animal, 247.7ms
2: 384x640 1 animal, 247.7ms
3: 384x640 1 animal, 247.7ms
4: 384x640 1 animal, 247.7ms
5: 384x640 1 animal, 247.7ms
6: 384x640 1 animal, 247.7ms
7: 384x640 1 animal, 247.7ms
8: 384x640 1 animal, 247.7ms
9: 384x640 1 animal, 247.7ms
10: 384x640 1 animal, 247.7ms
11: 384x640 1 animal, 247.7ms
12: 384x640 1 animal, 247.7ms
13: 384x640 1 animal, 247.7ms
14: 384x640 1 animal, 247.7ms
15: 384x640 1 animal, 247.7ms
Speed: 2.0ms preprocess, 247.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 28%|██████████████████████████████████████                                                                                                    | 8/29 [00:50<02:01,  5.79s/it]

0: 640x640 1 animal, 409.2ms
1: 640x640 1 animal, 409.2ms
2: 640x640 3 animals, 409.2ms
3: 640x640 2 animals, 409.2ms
4: 640x640 2 animals, 409.2ms
5: 640x640 2 animals, 409.2ms
6: 640x640 2 animals, 409.2ms
7: 640x640 2 animals, 409.2ms
8: 640x640 3 animals, 409.2ms
9: 640x640 4 animals, 409.2ms
10: 640x640 3 animals, 409.2ms
11: 640x640 3 animals, 409.2ms
12: 640x640 2 animals, 409.2ms
13: 640x640 2 animals, 409.2ms
14: 640x640 1 animal, 409.2ms
15: 640x640 1 animal, 409.2ms
Speed: 2.1ms preprocess, 409.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 31%|██████████████████████████████████████████▊                                                                                               | 9/29 [00:57<02:03,  6.18s/it]

0: 384x640 1 animal, 242.4ms
1: 384x640 1 animal, 242.4ms
2: 384x640 1 animal, 242.4ms
3: 384x640 1 animal, 242.4ms
4: 384x640 2 animals, 242.4ms
5: 384x640 2 animals, 242.4ms
6: 384x640 2 animals, 242.4ms
7: 384x640 2 animals, 242.4ms
8: 384x640 2 animals, 242.4ms
9: 384x640 2 animals, 242.4ms
10: 384x640 2 animals, 242.4ms
11: 384x640 2 animals, 242.4ms
12: 384x640 2 animals, 242.4ms
13: 384x640 2 animals, 242.4ms
14: 384x640 1 animal, 242.4ms
15: 384x640 2 animals, 242.4ms
Speed: 1.3ms preprocess, 242.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 34%|███████████████████████████████████████████████▏                                                                                         | 10/29 [01:01<01:46,  5.59s/it]

0: 384x640 2 animals, 239.7ms
1: 384x640 2 animals, 239.7ms
2: 384x640 2 animals, 239.7ms
3: 384x640 1 animal, 239.7ms
4: 384x640 2 animals, 239.7ms
5: 384x640 1 animal, 239.7ms
6: 384x640 2 animals, 239.7ms
7: 384x640 1 animal, 239.7ms
8: 384x640 1 animal, 239.7ms
9: 384x640 1 animal, 239.7ms
10: 384x640 2 animals, 239.7ms
11: 384x640 2 animals, 239.7ms
12: 384x640 2 animals, 239.7ms
13: 384x640 2 animals, 239.7ms
14: 384x640 2 animals, 239.7ms
15: 384x640 2 animals, 239.7ms
Speed: 1.4ms preprocess, 239.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 38%|███████████████████████████████████████████████████▉                                                                                     | 11/29 [01:05<01:33,  5.18s/it]

0: 384x640 2 animals, 241.0ms
1: 384x640 2 animals, 241.0ms
2: 384x640 2 animals, 241.0ms
3: 384x640 2 animals, 241.0ms
4: 384x640 1 animal, 241.0ms
5: 384x640 1 animal, 241.0ms
6: 384x640 1 animal, 241.0ms
7: 384x640 3 animals, 241.0ms
8: 384x640 1 animal, 241.0ms
9: 384x640 1 animal, 241.0ms
10: 384x640 1 animal, 241.0ms
11: 384x640 1 animal, 241.0ms
12: 384x640 1 animal, 241.0ms
13: 384x640 1 animal, 241.0ms
14: 384x640 1 animal, 241.0ms
15: 384x640 1 animal, 241.0ms
Speed: 1.3ms preprocess, 241.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 41%|████████████████████████████████████████████████████████▋                                                                                | 12/29 [01:10<01:23,  4.90s/it]

0: 384x640 1 animal, 245.7ms
1: 384x640 1 animal, 245.7ms
2: 384x640 1 animal, 245.7ms
3: 384x640 1 animal, 245.7ms
4: 384x640 1 animal, 245.7ms
5: 384x640 1 animal, 245.7ms
6: 384x640 1 animal, 245.7ms
7: 384x640 1 animal, 245.7ms
8: 384x640 1 animal, 245.7ms
9: 384x640 1 animal, 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 1 animal, 245.7ms
12: 384x640 1 animal, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 1 animal, 245.7ms
Speed: 1.4ms preprocess, 245.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 45%|█████████████████████████████████████████████████████████████▍                                                                           | 13/29 [01:14<01:15,  4.72s/it]

0: 384x640 1 animal, 240.3ms
1: 384x640 1 animal, 240.3ms
2: 384x640 1 animal, 240.3ms
3: 384x640 1 animal, 240.3ms
4: 384x640 1 animal, 240.3ms
5: 384x640 1 animal, 240.3ms
6: 384x640 1 animal, 240.3ms
7: 384x640 1 animal, 240.3ms
8: 384x640 1 animal, 240.3ms
9: 384x640 1 animal, 240.3ms
10: 384x640 1 animal, 240.3ms
11: 384x640 1 animal, 240.3ms
12: 384x640 1 animal, 240.3ms
13: 384x640 1 animal, 240.3ms
14: 384x640 1 animal, 240.3ms
15: 384x640 1 animal, 240.3ms
Speed: 1.4ms preprocess, 240.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 48%|██████████████████████████████████████████████████████████████████▏                                                                      | 14/29 [01:18<01:08,  4.58s/it]

0: 384x640 1 animal, 241.0ms
1: 384x640 1 animal, 241.0ms
2: 384x640 1 animal, 241.0ms
3: 384x640 1 animal, 241.0ms
4: 384x640 1 animal, 241.0ms
5: 384x640 1 animal, 241.0ms
6: 384x640 1 animal, 241.0ms
7: 384x640 1 animal, 241.0ms
8: 384x640 1 animal, 241.0ms
9: 384x640 1 animal, 241.0ms
10: 384x640 1 animal, 241.0ms
11: 384x640 1 animal, 241.0ms
12: 384x640 1 animal, 241.0ms
13: 384x640 1 animal, 241.0ms
14: 384x640 1 animal, 241.0ms
15: 384x640 1 animal, 241.0ms
Speed: 1.4ms preprocess, 241.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 52%|██████████████████████████████████████████████████████████████████████▊                                                                  | 15/29 [01:22<01:02,  4.48s/it]

0: 384x640 1 animal, 237.8ms
1: 384x640 1 animal, 237.8ms
2: 384x640 1 animal, 237.8ms
3: 384x640 1 animal, 237.8ms
4: 384x640 1 animal, 237.8ms
5: 384x640 1 animal, 237.8ms
6: 384x640 1 animal, 237.8ms
7: 384x640 1 animal, 237.8ms
8: 384x640 1 animal, 237.8ms
9: 384x640 1 animal, 237.8ms
10: 384x640 1 person, 237.8ms
11: 384x640 (no detections), 237.8ms
12: 384x640 (no detections), 237.8ms
13: 384x640 (no detections), 237.8ms
14: 384x640 (no detections), 237.8ms
15: 384x640 1 animal, 1 person, 237.8ms
Speed: 1.3ms preprocess, 237.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 55%|███████████████████████████████████████████████████████████████████████████▌                                                             | 16/29 [01:27<00:57,  4.39s/it]

0: 384x640 1 animal, 243.0ms
1: 384x640 1 animal, 243.0ms
2: 384x640 1 animal, 243.0ms
3: 384x640 1 person, 243.0ms
4: 384x640 (no detections), 243.0ms
5: 384x640 (no detections), 243.0ms
6: 384x640 (no detections), 243.0ms
7: 384x640 (no detections), 243.0ms
8: 384x640 (no detections), 243.0ms
9: 384x640 (no detections), 243.0ms
10: 384x640 (no detections), 243.0ms
11: 384x640 (no detections), 243.0ms
12: 384x640 (no detections), 243.0ms
13: 384x640 (no detections), 243.0ms
14: 384x640 1 animal, 243.0ms
15: 384x640 1 animal, 243.0ms
Speed: 1.3ms preprocess, 243.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 59%|████████████████████████████████████████████████████████████████████████████████▎                                                        | 17/29 [01:31<00:52,  4.35s/it]

0: 384x640 1 animal, 242.8ms
1: 384x640 1 animal, 242.8ms
2: 384x640 1 animal, 242.8ms
3: 384x640 1 animal, 242.8ms
4: 384x640 1 animal, 242.8ms
5: 384x640 1 animal, 242.8ms
6: 384x640 1 animal, 242.8ms
7: 384x640 1 animal, 242.8ms
8: 384x640 1 animal, 242.8ms
9: 384x640 1 animal, 242.8ms
10: 384x640 2 animals, 242.8ms
11: 384x640 2 animals, 242.8ms
12: 384x640 1 animal, 242.8ms
13: 384x640 1 animal, 242.8ms
14: 384x640 1 animal, 242.8ms
15: 384x640 (no detections), 242.8ms
Speed: 1.3ms preprocess, 242.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 62%|█████████████████████████████████████████████████████████████████████████████████████                                                    | 18/29 [01:35<00:47,  4.33s/it]

0: 384x640 (no detections), 241.1ms
1: 384x640 (no detections), 241.1ms
2: 384x640 (no detections), 241.1ms
3: 384x640 1 animal, 241.1ms
4: 384x640 1 animal, 241.1ms
5: 384x640 1 animal, 241.1ms
6: 384x640 1 animal, 241.1ms
7: 384x640 1 animal, 241.1ms
8: 384x640 1 animal, 241.1ms
9: 384x640 1 animal, 241.1ms
10: 384x640 1 animal, 241.1ms
11: 384x640 1 animal, 241.1ms
12: 384x640 1 animal, 241.1ms
13: 384x640 2 animals, 241.1ms
14: 384x640 2 animals, 241.1ms
15: 384x640 2 animals, 241.1ms
Speed: 1.3ms preprocess, 241.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 66%|█████████████████████████████████████████████████████████████████████████████████████████▊                                               | 19/29 [01:39<00:43,  4.30s/it]

0: 384x640 2 animals, 242.0ms
1: 384x640 3 animals, 242.0ms
2: 384x640 1 animal, 242.0ms
3: 384x640 1 animal, 242.0ms
4: 384x640 2 animals, 242.0ms
5: 384x640 2 animals, 242.0ms
6: 384x640 1 animal, 242.0ms
7: 384x640 1 animal, 242.0ms
8: 384x640 1 animal, 242.0ms
9: 384x640 1 animal, 242.0ms
10: 384x640 1 animal, 242.0ms
11: 384x640 1 animal, 242.0ms
12: 384x640 1 animal, 242.0ms
13: 384x640 1 animal, 242.0ms
14: 384x640 1 animal, 242.0ms
15: 384x640 1 animal, 242.0ms
Speed: 1.4ms preprocess, 242.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 69%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                          | 20/29 [01:44<00:38,  4.29s/it]

0: 384x640 4 animals, 243.0ms
1: 384x640 1 animal, 243.0ms
2: 384x640 1 animal, 243.0ms
3: 384x640 2 animals, 243.0ms
4: 384x640 2 animals, 243.0ms
5: 384x640 1 animal, 243.0ms
6: 384x640 2 animals, 243.0ms
7: 384x640 2 animals, 243.0ms
8: 384x640 1 animal, 243.0ms
9: 384x640 1 animal, 243.0ms
10: 384x640 1 person, 243.0ms
11: 384x640 1 animal, 1 person, 243.0ms
12: 384x640 1 person, 243.0ms
13: 384x640 1 animal, 243.0ms
14: 384x640 1 person, 243.0ms
15: 384x640 1 animal, 1 person, 243.0ms
Speed: 1.4ms preprocess, 243.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 21/29 [01:48<00:34,  4.29s/it]

0: 384x640 1 person, 245.7ms
1: 384x640 1 animal, 245.7ms
2: 384x640 1 animal, 245.7ms
3: 384x640 1 animal, 245.7ms
4: 384x640 1 animal, 245.7ms
5: 384x640 2 animals, 245.7ms
6: 384x640 1 animal, 1 person, 245.7ms
7: 384x640 1 person, 245.7ms
8: 384x640 1 person, 245.7ms
9: 384x640 2 animals, 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 1 animal, 245.7ms
12: 384x640 2 animals, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 1 animal, 245.7ms
Speed: 1.3ms preprocess, 245.7ms inference, 0.5ms postprocess per image at shape (16, 3, 384, 640)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 22/29 [01:52<00:30,  4.30s/it]

0: 384x640 1 animal, 242.3ms
1: 384x640 1 animal, 242.3ms
2: 384x640 1 animal, 242.3ms
3: 384x640 1 animal, 242.3ms
4: 384x640 1 animal, 242.3ms
5: 384x640 1 animal, 242.3ms
6: 384x640 1 animal, 242.3ms
7: 384x640 1 animal, 242.3ms
8: 384x640 1 animal, 242.3ms
9: 384x640 1 animal, 242.3ms
10: 384x640 1 animal, 242.3ms
11: 384x640 1 animal, 242.3ms
12: 384x640 1 animal, 242.3ms
13: 384x640 1 animal, 242.3ms
14: 384x640 1 animal, 242.3ms
15: 384x640 2 animals, 242.3ms
Speed: 1.5ms preprocess, 242.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 23/29 [01:57<00:25,  4.30s/it]

0: 384x640 3 animals, 240.8ms
1: 384x640 1 animal, 240.8ms
2: 384x640 1 animal, 240.8ms
3: 384x640 1 animal, 240.8ms
4: 384x640 1 animal, 240.8ms
5: 384x640 1 animal, 240.8ms
6: 384x640 1 animal, 240.8ms
7: 384x640 1 animal, 240.8ms
8: 384x640 1 animal, 240.8ms
9: 384x640 1 animal, 240.8ms
10: 384x640 1 animal, 240.8ms
11: 384x640 1 animal, 240.8ms
12: 384x640 2 animals, 240.8ms
13: 384x640 2 animals, 240.8ms
14: 384x640 2 animals, 240.8ms
15: 384x640 2 animals, 240.8ms
Speed: 1.3ms preprocess, 240.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 24/29 [02:01<00:21,  4.29s/it]

0: 384x640 1 animal, 243.5ms
1: 384x640 1 animal, 243.5ms
2: 384x640 1 animal, 243.5ms
3: 384x640 1 animal, 243.5ms
4: 384x640 1 animal, 243.5ms
5: 384x640 2 animals, 243.5ms
6: 384x640 1 animal, 243.5ms
7: 384x640 2 animals, 243.5ms
8: 384x640 1 animal, 243.5ms
9: 384x640 2 animals, 243.5ms
10: 384x640 2 animals, 243.5ms
11: 384x640 1 animal, 243.5ms
12: 384x640 1 animal, 243.5ms
13: 384x640 1 animal, 243.5ms
14: 384x640 2 animals, 243.5ms
15: 384x640 2 animals, 243.5ms
Speed: 1.4ms preprocess, 243.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 25/29 [02:05<00:17,  4.29s/it]

0: 384x640 2 animals, 240.7ms
1: 384x640 2 animals, 240.7ms
2: 384x640 3 animals, 240.7ms
3: 384x640 2 animals, 240.7ms
4: 384x640 3 animals, 240.7ms
5: 384x640 3 animals, 240.7ms
6: 384x640 3 animals, 240.7ms
7: 384x640 4 animals, 240.7ms
8: 384x640 2 animals, 240.7ms
9: 384x640 3 animals, 240.7ms
10: 384x640 1 animal, 240.7ms
11: 384x640 1 animal, 240.7ms
12: 384x640 1 animal, 240.7ms
13: 384x640 1 animal, 240.7ms
14: 384x640 1 animal, 240.7ms
15: 384x640 1 animal, 240.7ms
Speed: 1.4ms preprocess, 240.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 26/29 [02:09<00:12,  4.28s/it]

0: 384x640 1 animal, 240.6ms
1: 384x640 1 animal, 240.6ms
2: 384x640 1 animal, 240.6ms
3: 384x640 1 animal, 240.6ms
4: 384x640 1 animal, 240.6ms
5: 384x640 1 animal, 240.6ms
6: 384x640 1 animal, 240.6ms
7: 384x640 1 animal, 240.6ms
8: 384x640 1 animal, 240.6ms
9: 384x640 1 animal, 240.6ms
10: 384x640 1 animal, 240.6ms
11: 384x640 1 animal, 240.6ms
12: 384x640 1 animal, 240.6ms
13: 384x640 1 animal, 240.6ms
14: 384x640 1 animal, 240.6ms
15: 384x640 1 animal, 240.6ms
Speed: 1.4ms preprocess, 240.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 27/29 [02:14<00:08,  4.28s/it]

0: 384x640 1 animal, 240.6ms
1: 384x640 1 animal, 240.6ms
2: 384x640 1 animal, 240.6ms
3: 384x640 1 animal, 240.6ms
4: 384x640 1 animal, 240.6ms
5: 384x640 1 animal, 240.6ms
6: 384x640 1 animal, 240.6ms
7: 384x640 1 animal, 240.6ms
8: 384x640 1 animal, 240.6ms
9: 384x640 1 animal, 240.6ms
10: 384x640 1 animal, 240.6ms
11: 384x640 1 animal, 240.6ms
12: 384x640 1 animal, 240.6ms
13: 384x640 1 animal, 240.6ms
14: 384x640 1 animal, 240.6ms
15: 384x640 1 animal, 240.6ms
Speed: 1.3ms preprocess, 240.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 28/29 [02:18<00:04,  4.27s/it]

0: 384x640 1 animal, 191.2ms
1: 384x640 1 animal, 191.2ms
Speed: 1.3ms preprocess, 191.2ms inference, 0.6ms postprocess per image at shape (2, 3, 384, 640)

00%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [02:18<00:00,  4.79s/it]

Detecting images from UROCYON_CINEREORGENTEUS_extracted

  0%|                                                                                                                                                 | 0/182 [00:00<?, ?it/s]

0: 384x640 1 animal, 244.0ms
1: 384x640 1 animal, 244.0ms
2: 384x640 1 animal, 244.0ms
3: 384x640 1 animal, 244.0ms
4: 384x640 1 animal, 244.0ms
5: 384x640 1 animal, 244.0ms
6: 384x640 1 animal, 244.0ms
7: 384x640 1 animal, 244.0ms
8: 384x640 1 animal, 244.0ms
9: 384x640 1 animal, 244.0ms
10: 384x640 1 animal, 244.0ms
11: 384x640 1 animal, 244.0ms
12: 384x640 1 animal, 244.0ms
13: 384x640 1 animal, 244.0ms
14: 384x640 1 animal, 244.0ms
15: 384x640 1 animal, 244.0ms
Speed: 1.7ms preprocess, 244.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  1%|▊                                                                                                                                        | 1/182 [00:04<12:54,  4.28s/it]

0: 384x640 1 animal, 241.7ms
1: 384x640 1 animal, 241.7ms
2: 384x640 1 animal, 241.7ms
3: 384x640 1 animal, 241.7ms
4: 384x640 1 animal, 241.7ms
5: 384x640 1 animal, 241.7ms
6: 384x640 1 animal, 241.7ms
7: 384x640 1 animal, 241.7ms
8: 384x640 1 animal, 241.7ms
9: 384x640 1 animal, 241.7ms
10: 384x640 (no detections), 241.7ms
11: 384x640 (no detections), 241.7ms
12: 384x640 (no detections), 241.7ms
13: 384x640 (no detections), 241.7ms
14: 384x640 (no detections), 241.7ms
15: 384x640 (no detections), 241.7ms
Speed: 1.8ms preprocess, 241.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  1%|█▌                                                                                                                                       | 2/182 [00:08<12:48,  4.27s/it]

0: 640x640 (no detections), 409.1ms
1: 640x640 (no detections), 409.1ms
2: 640x640 (no detections), 409.1ms
3: 640x640 1 animal, 409.1ms
4: 640x640 1 animal, 409.1ms
5: 640x640 1 animal, 409.1ms
6: 640x640 1 animal, 409.1ms
7: 640x640 1 animal, 409.1ms
8: 640x640 1 animal, 409.1ms
9: 640x640 1 animal, 409.1ms
10: 640x640 1 animal, 409.1ms
11: 640x640 1 animal, 409.1ms
12: 640x640 (no detections), 409.1ms
13: 640x640 1 animal, 409.1ms
14: 640x640 (no detections), 409.1ms
15: 640x640 (no detections), 409.1ms
Speed: 2.5ms preprocess, 409.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  2%|██▎                                                                                                                                      | 3/182 [00:15<16:36,  5.57s/it]

0: 640x640 (no detections), 404.4ms
1: 640x640 (no detections), 404.4ms
2: 640x640 1 animal, 404.4ms
3: 640x640 1 animal, 404.4ms
4: 640x640 1 animal, 404.4ms
5: 640x640 1 animal, 404.4ms
6: 640x640 1 animal, 404.4ms
7: 640x640 1 animal, 404.4ms
8: 640x640 1 animal, 404.4ms
9: 640x640 1 animal, 404.4ms
10: 640x640 1 animal, 404.4ms
11: 640x640 1 animal, 404.4ms
12: 640x640 1 animal, 404.4ms
13: 640x640 1 animal, 404.4ms
14: 640x640 1 animal, 404.4ms
15: 640x640 1 animal, 404.4ms
Speed: 2.6ms preprocess, 404.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  2%|███                                                                                                                                      | 4/182 [00:22<18:11,  6.13s/it]

0: 384x640 1 animal, 247.3ms
1: 384x640 1 animal, 247.3ms
2: 384x640 1 animal, 247.3ms
3: 384x640 1 animal, 247.3ms
4: 384x640 1 animal, 247.3ms
5: 384x640 1 animal, 247.3ms
6: 384x640 1 animal, 247.3ms
7: 384x640 1 animal, 247.3ms
8: 384x640 1 animal, 247.3ms
9: 384x640 (no detections), 247.3ms
10: 384x640 (no detections), 247.3ms
11: 384x640 (no detections), 247.3ms
12: 384x640 1 animal, 247.3ms
13: 384x640 1 animal, 247.3ms
14: 384x640 1 animal, 247.3ms
15: 384x640 1 animal, 247.3ms
Speed: 1.7ms preprocess, 247.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  3%|███▊                                                                                                                                     | 5/182 [00:27<16:34,  5.62s/it]

0: 384x640 1 animal, 245.2ms
1: 384x640 (no detections), 245.2ms
2: 384x640 (no detections), 245.2ms
3: 384x640 (no detections), 245.2ms
4: 384x640 (no detections), 245.2ms
5: 384x640 (no detections), 245.2ms
6: 384x640 (no detections), 245.2ms
7: 384x640 (no detections), 245.2ms
8: 384x640 (no detections), 245.2ms
9: 384x640 (no detections), 245.2ms
10: 384x640 1 animal, 245.2ms
11: 384x640 (no detections), 245.2ms
12: 384x640 (no detections), 245.2ms
13: 384x640 (no detections), 245.2ms
14: 384x640 (no detections), 245.2ms
15: 384x640 (no detections), 245.2ms
Speed: 1.7ms preprocess, 245.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

  3%|████▌                                                                                                                                    | 6/182 [00:32<15:32,  5.30s/it]

0: 384x640 (no detections), 245.6ms
1: 384x640 (no detections), 245.6ms
2: 384x640 (no detections), 245.6ms
3: 384x640 (no detections), 245.6ms
4: 384x640 1 animal, 245.6ms
5: 384x640 1 animal, 245.6ms
6: 384x640 1 animal, 245.6ms
7: 384x640 1 animal, 245.6ms
8: 384x640 1 animal, 245.6ms
9: 384x640 (no detections), 245.6ms
10: 384x640 (no detections), 245.6ms
11: 384x640 (no detections), 245.6ms
12: 384x640 (no detections), 245.6ms
13: 384x640 (no detections), 245.6ms
14: 384x640 (no detections), 245.6ms
15: 384x640 (no detections), 245.6ms
Speed: 1.7ms preprocess, 245.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  4%|█████▎                                                                                                                                   | 7/182 [00:36<14:50,  5.09s/it]

0: 384x640 1 animal, 247.2ms
1: 384x640 1 animal, 247.2ms
2: 384x640 1 animal, 247.2ms
3: 384x640 1 animal, 247.2ms
4: 384x640 1 animal, 247.2ms
5: 384x640 1 animal, 247.2ms
6: 384x640 1 animal, 247.2ms
7: 384x640 1 animal, 247.2ms
8: 384x640 (no detections), 247.2ms
9: 384x640 (no detections), 247.2ms
10: 384x640 1 animal, 247.2ms
11: 384x640 1 animal, 247.2ms
12: 384x640 1 animal, 247.2ms
13: 384x640 1 animal, 247.2ms
14: 384x640 1 animal, 247.2ms
15: 384x640 1 animal, 247.2ms
Speed: 2.0ms preprocess, 247.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  4%|██████                                                                                                                                   | 8/182 [00:41<14:22,  4.95s/it]

0: 384x640 1 animal, 245.0ms
1: 384x640 1 animal, 245.0ms
2: 384x640 (no detections), 245.0ms
3: 384x640 (no detections), 245.0ms
4: 384x640 1 animal, 245.0ms
5: 384x640 1 animal, 245.0ms
6: 384x640 1 animal, 245.0ms
7: 384x640 1 animal, 245.0ms
8: 384x640 1 animal, 245.0ms
9: 384x640 1 animal, 245.0ms
10: 384x640 1 animal, 245.0ms
11: 384x640 1 animal, 245.0ms
12: 384x640 1 animal, 245.0ms
13: 384x640 1 animal, 245.0ms
14: 384x640 1 animal, 245.0ms
15: 384x640 1 animal, 245.0ms
Speed: 1.7ms preprocess, 245.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  5%|██████▊                                                                                                                                  | 9/182 [00:46<14:01,  4.86s/it]

0: 384x640 1 animal, 245.3ms
1: 384x640 1 animal, 245.3ms
2: 384x640 1 animal, 245.3ms
3: 384x640 1 animal, 245.3ms
4: 384x640 1 animal, 245.3ms
5: 384x640 1 animal, 245.3ms
6: 384x640 1 animal, 245.3ms
7: 384x640 2 animals, 245.3ms
8: 384x640 1 animal, 245.3ms
9: 384x640 1 animal, 245.3ms
10: 384x640 1 animal, 245.3ms
11: 384x640 1 animal, 245.3ms
12: 384x640 1 animal, 245.3ms
13: 384x640 1 animal, 245.3ms
14: 384x640 1 animal, 245.3ms
15: 384x640 1 animal, 245.3ms
Speed: 1.7ms preprocess, 245.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  5%|███████▍                                                                                                                                | 10/182 [00:50<13:46,  4.80s/it]

0: 384x640 1 animal, 243.6ms
1: 384x640 1 animal, 243.6ms
2: 384x640 1 animal, 243.6ms
3: 384x640 2 animals, 243.6ms
4: 384x640 (no detections), 243.6ms
5: 384x640 (no detections), 243.6ms
6: 384x640 (no detections), 243.6ms
7: 384x640 (no detections), 243.6ms
8: 384x640 (no detections), 243.6ms
9: 384x640 (no detections), 243.6ms
10: 384x640 1 animal, 243.6ms
11: 384x640 1 animal, 243.6ms
12: 384x640 2 animals, 243.6ms
13: 384x640 (no detections), 243.6ms
14: 384x640 (no detections), 243.6ms
15: 384x640 (no detections), 243.6ms
Speed: 1.8ms preprocess, 243.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  6%|████████▏                                                                                                                               | 11/182 [00:54<13:14,  4.65s/it]

0: 640x640 (no detections), 414.1ms
1: 640x640 (no detections), 414.1ms
2: 640x640 (no detections), 414.1ms
3: 640x640 (no detections), 414.1ms
4: 640x640 1 animal, 414.1ms
5: 640x640 1 animal, 414.1ms
6: 640x640 1 animal, 414.1ms
7: 640x640 1 animal, 414.1ms
8: 640x640 1 animal, 414.1ms
9: 640x640 1 animal, 414.1ms
10: 640x640 (no detections), 414.1ms
11: 640x640 (no detections), 414.1ms
12: 640x640 (no detections), 414.1ms
13: 640x640 (no detections), 414.1ms
14: 640x640 1 animal, 414.1ms
15: 640x640 1 animal, 414.1ms
Speed: 2.7ms preprocess, 414.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  7%|████████▉                                                                                                                               | 12/182 [01:02<15:26,  5.45s/it]

0: 384x640 1 animal, 246.9ms
1: 384x640 1 animal, 246.9ms
2: 384x640 (no detections), 246.9ms
3: 384x640 (no detections), 246.9ms
4: 384x640 (no detections), 246.9ms
5: 384x640 (no detections), 246.9ms
6: 384x640 (no detections), 246.9ms
7: 384x640 (no detections), 246.9ms
8: 384x640 1 animal, 246.9ms
9: 384x640 1 animal, 246.9ms
10: 384x640 1 animal, 246.9ms
11: 384x640 1 animal, 246.9ms
12: 384x640 1 animal, 246.9ms
13: 384x640 1 animal, 246.9ms
14: 384x640 (no detections), 246.9ms
15: 384x640 (no detections), 246.9ms
Speed: 1.7ms preprocess, 246.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  7%|█████████▋                                                                                                                              | 13/182 [01:06<14:41,  5.22s/it]

0: 640x640 (no detections), 413.8ms
1: 640x640 (no detections), 413.8ms
2: 640x640 1 animal, 413.8ms
3: 640x640 1 animal, 413.8ms
4: 640x640 1 animal, 413.8ms
5: 640x640 1 animal, 413.8ms
6: 640x640 (no detections), 413.8ms
7: 640x640 (no detections), 413.8ms
8: 640x640 (no detections), 413.8ms
9: 640x640 (no detections), 413.8ms
10: 640x640 (no detections), 413.8ms
11: 640x640 (no detections), 413.8ms
12: 640x640 1 animal, 413.8ms
13: 640x640 1 animal, 413.8ms
14: 640x640 1 animal, 413.8ms
15: 640x640 1 animal, 413.8ms
Speed: 2.8ms preprocess, 413.8ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  8%|██████████▍                                                                                                                             | 14/182 [01:14<16:14,  5.80s/it]

0: 384x640 1 animal, 247.2ms
1: 384x640 1 animal, 247.2ms
2: 384x640 1 animal, 247.2ms
3: 384x640 1 animal, 247.2ms
4: 384x640 1 animal, 247.2ms
5: 384x640 1 animal, 247.2ms
6: 384x640 1 animal, 247.2ms
7: 384x640 1 animal, 247.2ms
8: 384x640 1 animal, 247.2ms
9: 384x640 1 animal, 247.2ms
10: 384x640 1 animal, 247.2ms
11: 384x640 1 animal, 247.2ms
12: 384x640 1 animal, 247.2ms
13: 384x640 1 animal, 247.2ms
14: 384x640 1 animal, 247.2ms
15: 384x640 1 animal, 247.2ms
Speed: 1.9ms preprocess, 247.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  8%|███████████▏                                                                                                                            | 15/182 [01:18<15:12,  5.47s/it]

0: 384x640 1 animal, 252.0ms
1: 384x640 1 animal, 252.0ms
2: 384x640 2 animals, 252.0ms
3: 384x640 1 animal, 252.0ms
4: 384x640 1 animal, 252.0ms
5: 384x640 1 animal, 252.0ms
6: 384x640 1 animal, 252.0ms
7: 384x640 (no detections), 252.0ms
8: 384x640 (no detections), 252.0ms
9: 384x640 (no detections), 252.0ms
10: 384x640 1 animal, 252.0ms
11: 384x640 1 animal, 252.0ms
12: 384x640 1 animal, 252.0ms
13: 384x640 1 animal, 252.0ms
14: 384x640 1 animal, 252.0ms
15: 384x640 1 animal, 252.0ms
Speed: 1.8ms preprocess, 252.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  9%|███████████▉                                                                                                                            | 16/182 [01:23<14:39,  5.30s/it]

0: 384x640 2 animals, 243.1ms
1: 384x640 2 animals, 243.1ms
2: 384x640 1 animal, 243.1ms
3: 384x640 (no detections), 243.1ms
4: 384x640 1 animal, 243.1ms
5: 384x640 1 animal, 243.1ms
6: 384x640 2 animals, 243.1ms
7: 384x640 1 animal, 243.1ms
8: 384x640 1 animal, 243.1ms
9: 384x640 1 animal, 243.1ms
10: 384x640 1 animal, 243.1ms
11: 384x640 (no detections), 243.1ms
12: 384x640 (no detections), 243.1ms
13: 384x640 (no detections), 243.1ms
14: 384x640 1 animal, 243.1ms
15: 384x640 1 animal, 243.1ms
Speed: 1.8ms preprocess, 243.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  9%|████████████▋                                                                                                                           | 17/182 [01:28<14:04,  5.12s/it]

0: 384x640 1 animal, 246.8ms
1: 384x640 1 animal, 246.8ms
2: 384x640 1 animal, 246.8ms
3: 384x640 1 animal, 246.8ms
4: 384x640 1 animal, 246.8ms
5: 384x640 1 animal, 246.8ms
6: 384x640 1 animal, 246.8ms
7: 384x640 1 animal, 246.8ms
8: 384x640 1 animal, 246.8ms
9: 384x640 1 animal, 246.8ms
10: 384x640 1 animal, 246.8ms
11: 384x640 1 animal, 246.8ms
12: 384x640 1 animal, 246.8ms
13: 384x640 1 animal, 246.8ms
14: 384x640 1 animal, 246.8ms
15: 384x640 1 animal, 246.8ms
Speed: 1.8ms preprocess, 246.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 10%|█████████████▍                                                                                                                          | 18/182 [01:33<13:38,  4.99s/it]

0: 640x640 1 animal, 410.6ms
1: 640x640 1 animal, 410.6ms
2: 640x640 1 animal, 410.6ms
3: 640x640 1 animal, 410.6ms
4: 640x640 1 animal, 410.6ms
5: 640x640 1 animal, 410.6ms
6: 640x640 1 animal, 410.6ms
7: 640x640 1 animal, 410.6ms
8: 640x640 1 animal, 410.6ms
9: 640x640 1 animal, 410.6ms
10: 640x640 1 animal, 410.6ms
11: 640x640 1 animal, 410.6ms
12: 640x640 1 animal, 410.6ms
13: 640x640 1 animal, 410.6ms
14: 640x640 1 animal, 410.6ms
15: 640x640 1 animal, 410.6ms
Speed: 2.6ms preprocess, 410.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 10%|██████████████▏                                                                                                                         | 19/182 [01:40<15:25,  5.68s/it]

0: 640x640 1 animal, 417.0ms
1: 640x640 1 animal, 417.0ms
2: 640x640 1 animal, 417.0ms
3: 640x640 2 animals, 417.0ms
4: 640x640 1 animal, 417.0ms
5: 640x640 (no detections), 417.0ms
6: 640x640 1 animal, 417.0ms
7: 640x640 (no detections), 417.0ms
8: 640x640 (no detections), 417.0ms
9: 640x640 (no detections), 417.0ms
10: 640x640 (no detections), 417.0ms
11: 640x640 (no detections), 417.0ms
12: 640x640 (no detections), 417.0ms
13: 640x640 (no detections), 417.0ms
14: 640x640 (no detections), 417.0ms
15: 640x640 1 animal, 417.0ms
Speed: 2.8ms preprocess, 417.0ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 11%|██████████████▉                                                                                                                         | 20/182 [01:47<16:40,  6.18s/it]

0: 384x640 1 animal, 245.9ms
1: 384x640 1 animal, 245.9ms
2: 384x640 1 animal, 245.9ms
3: 384x640 (no detections), 245.9ms
4: 384x640 (no detections), 245.9ms
5: 384x640 (no detections), 245.9ms
6: 384x640 (no detections), 245.9ms
7: 384x640 (no detections), 245.9ms
8: 384x640 (no detections), 245.9ms
9: 384x640 (no detections), 245.9ms
10: 384x640 (no detections), 245.9ms
11: 384x640 (no detections), 245.9ms
12: 384x640 1 animal, 245.9ms
13: 384x640 1 animal, 245.9ms
14: 384x640 1 animal, 245.9ms
15: 384x640 1 animal, 245.9ms
Speed: 1.7ms preprocess, 245.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 12%|███████████████▋                                                                                                                        | 21/182 [01:52<15:20,  5.72s/it]

0: 384x640 1 animal, 243.4ms
1: 384x640 1 animal, 243.4ms
2: 384x640 1 animal, 243.4ms
3: 384x640 1 animal, 243.4ms
4: 384x640 1 animal, 243.4ms
5: 384x640 1 animal, 243.4ms
6: 384x640 1 animal, 243.4ms
7: 384x640 1 animal, 243.4ms
8: 384x640 1 animal, 243.4ms
9: 384x640 1 animal, 243.4ms
10: 384x640 1 animal, 243.4ms
11: 384x640 1 animal, 243.4ms
12: 384x640 1 animal, 243.4ms
13: 384x640 1 animal, 243.4ms
14: 384x640 (no detections), 243.4ms
15: 384x640 (no detections), 243.4ms
Speed: 1.9ms preprocess, 243.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 12%|████████████████▍                                                                                                                       | 22/182 [01:56<14:22,  5.39s/it]

0: 640x640 1 animal, 409.1ms
1: 640x640 1 animal, 409.1ms
2: 640x640 2 animals, 409.1ms
3: 640x640 1 animal, 409.1ms
4: 640x640 1 animal, 409.1ms
5: 640x640 1 animal, 409.1ms
6: 640x640 1 animal, 409.1ms
7: 640x640 1 animal, 409.1ms
8: 640x640 1 animal, 409.1ms
9: 640x640 1 animal, 409.1ms
10: 640x640 1 animal, 409.1ms
11: 640x640 1 animal, 409.1ms
12: 640x640 1 animal, 409.1ms
13: 640x640 1 animal, 409.1ms
14: 640x640 1 animal, 409.1ms
15: 640x640 1 animal, 409.1ms
Speed: 2.4ms preprocess, 409.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 13%|█████████████████▏                                                                                                                      | 23/182 [02:04<15:38,  5.91s/it]

0: 640x640 1 animal, 411.9ms
1: 640x640 1 animal, 411.9ms
2: 640x640 1 animal, 411.9ms
3: 640x640 1 animal, 411.9ms
4: 640x640 1 animal, 411.9ms
5: 640x640 1 animal, 411.9ms
6: 640x640 1 animal, 411.9ms
7: 640x640 1 animal, 411.9ms
8: 640x640 1 animal, 411.9ms
9: 640x640 1 animal, 411.9ms
10: 640x640 1 animal, 411.9ms
11: 640x640 1 animal, 411.9ms
12: 640x640 1 animal, 411.9ms
13: 640x640 1 animal, 411.9ms
14: 640x640 (no detections), 411.9ms
15: 640x640 (no detections), 411.9ms
Speed: 2.5ms preprocess, 411.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 13%|█████████████████▉                                                                                                                      | 24/182 [02:11<16:38,  6.32s/it]

0: 384x640 (no detections), 244.8ms
1: 384x640 (no detections), 244.8ms
2: 384x640 (no detections), 244.8ms
3: 384x640 (no detections), 244.8ms
4: 384x640 (no detections), 244.8ms
5: 384x640 (no detections), 244.8ms
6: 384x640 1 animal, 244.8ms
7: 384x640 1 animal, 244.8ms
8: 384x640 1 animal, 244.8ms
9: 384x640 (no detections), 244.8ms
10: 384x640 (no detections), 244.8ms
11: 384x640 (no detections), 244.8ms
12: 384x640 (no detections), 244.8ms
13: 384x640 (no detections), 244.8ms
14: 384x640 (no detections), 244.8ms
15: 384x640 (no detections), 244.8ms
Speed: 2.0ms preprocess, 244.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 14%|██████████████████▋                                                                                                                     | 25/182 [02:16<15:12,  5.81s/it]

0: 384x640 1 animal, 242.8ms
1: 384x640 1 animal, 242.8ms
2: 384x640 1 animal, 242.8ms
3: 384x640 1 animal, 242.8ms
4: 384x640 1 animal, 242.8ms
5: 384x640 1 animal, 242.8ms
6: 384x640 1 animal, 242.8ms
7: 384x640 (no detections), 242.8ms
8: 384x640 (no detections), 242.8ms
9: 384x640 (no detections), 242.8ms
10: 384x640 1 animal, 242.8ms
11: 384x640 1 animal, 242.8ms
12: 384x640 1 animal, 242.8ms
13: 384x640 1 animal, 242.8ms
14: 384x640 1 animal, 242.8ms
15: 384x640 (no detections), 242.8ms
Speed: 1.7ms preprocess, 242.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 14%|███████████████████▍                                                                                                                    | 26/182 [02:20<14:10,  5.45s/it]

0: 384x640 (no detections), 235.9ms
1: 384x640 (no detections), 235.9ms
2: 384x640 (no detections), 235.9ms
3: 384x640 (no detections), 235.9ms
4: 384x640 1 animal, 235.9ms
5: 384x640 1 animal, 235.9ms
6: 384x640 1 animal, 235.9ms
7: 384x640 1 animal, 235.9ms
8: 384x640 1 animal, 235.9ms
9: 384x640 (no detections), 235.9ms
10: 384x640 (no detections), 235.9ms
11: 384x640 (no detections), 235.9ms
12: 384x640 (no detections), 235.9ms
13: 384x640 (no detections), 235.9ms
14: 384x640 1 animal, 235.9ms
15: 384x640 1 animal, 235.9ms
Speed: 1.7ms preprocess, 235.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 15%|████████████████████▏                                                                                                                   | 27/182 [02:25<13:20,  5.16s/it]

0: 384x640 1 animal, 244.5ms
1: 384x640 (no detections), 244.5ms
2: 384x640 (no detections), 244.5ms
3: 384x640 (no detections), 244.5ms
4: 384x640 (no detections), 244.5ms
5: 384x640 (no detections), 244.5ms
6: 384x640 (no detections), 244.5ms
7: 384x640 (no detections), 244.5ms
8: 384x640 1 animal, 244.5ms
9: 384x640 1 animal, 244.5ms
10: 384x640 1 animal, 244.5ms
11: 384x640 1 animal, 244.5ms
12: 384x640 (no detections), 244.5ms
13: 384x640 (no detections), 244.5ms
14: 384x640 (no detections), 244.5ms
15: 384x640 (no detections), 244.5ms
Speed: 2.0ms preprocess, 244.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 15%|████████████████████▉                                                                                                                   | 28/182 [02:29<12:50,  5.00s/it]

0: 640x640 (no detections), 409.1ms
1: 640x640 (no detections), 409.1ms
2: 640x640 1 animal, 409.1ms
3: 640x640 (no detections), 409.1ms
4: 640x640 (no detections), 409.1ms
5: 640x640 (no detections), 409.1ms
6: 640x640 (no detections), 409.1ms
7: 640x640 (no detections), 409.1ms
8: 640x640 (no detections), 409.1ms
9: 640x640 (no detections), 409.1ms
10: 640x640 (no detections), 409.1ms
11: 640x640 (no detections), 409.1ms
12: 640x640 1 animal, 409.1ms
13: 640x640 1 animal, 409.1ms
14: 640x640 1 animal, 409.1ms
15: 640x640 1 animal, 409.1ms
Speed: 2.7ms preprocess, 409.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 16%|█████████████████████▋                                                                                                                  | 29/182 [02:36<14:21,  5.63s/it]

0: 384x640 1 animal, 244.6ms
1: 384x640 1 animal, 244.6ms
2: 384x640 1 animal, 244.6ms
3: 384x640 1 animal, 244.6ms
4: 384x640 (no detections), 244.6ms
5: 384x640 (no detections), 244.6ms
6: 384x640 1 animal, 244.6ms
7: 384x640 1 animal, 244.6ms
8: 384x640 1 animal, 244.6ms
9: 384x640 1 animal, 244.6ms
10: 384x640 1 animal, 244.6ms
11: 384x640 1 animal, 244.6ms
12: 384x640 1 animal, 244.6ms
13: 384x640 1 animal, 244.6ms
14: 384x640 1 animal, 244.6ms
15: 384x640 1 animal, 244.6ms
Speed: 1.7ms preprocess, 244.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 16%|██████████████████████▍                                                                                                                 | 30/182 [02:41<13:30,  5.33s/it]

0: 384x640 1 animal, 242.5ms
1: 384x640 (no detections), 242.5ms
2: 384x640 1 animal, 242.5ms
3: 384x640 1 animal, 242.5ms
4: 384x640 1 animal, 242.5ms
5: 384x640 1 animal, 242.5ms
6: 384x640 1 animal, 242.5ms
7: 384x640 1 animal, 242.5ms
8: 384x640 1 animal, 242.5ms
9: 384x640 1 animal, 242.5ms
10: 384x640 2 animals, 242.5ms
11: 384x640 (no detections), 242.5ms
12: 384x640 (no detections), 242.5ms
13: 384x640 (no detections), 242.5ms
14: 384x640 (no detections), 242.5ms
15: 384x640 (no detections), 242.5ms
Speed: 2.0ms preprocess, 242.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 17%|███████████████████████▏                                                                                                                | 31/182 [02:46<12:52,  5.12s/it]

0: 384x640 (no detections), 243.0ms
1: 384x640 (no detections), 243.0ms
2: 384x640 (no detections), 243.0ms
3: 384x640 (no detections), 243.0ms
4: 384x640 1 animal, 243.0ms
5: 384x640 (no detections), 243.0ms
6: 384x640 (no detections), 243.0ms
7: 384x640 (no detections), 243.0ms
8: 384x640 (no detections), 243.0ms
9: 384x640 (no detections), 243.0ms
10: 384x640 (no detections), 243.0ms
11: 384x640 (no detections), 243.0ms
12: 384x640 (no detections), 243.0ms
13: 384x640 (no detections), 243.0ms
14: 384x640 1 animal, 243.0ms
15: 384x640 1 animal, 243.0ms
Speed: 1.7ms preprocess, 243.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 18%|███████████████████████▉                                                                                                                | 32/182 [02:50<12:25,  4.97s/it]

0: 384x640 1 animal, 245.1ms
1: 384x640 2 animals, 245.1ms
2: 384x640 (no detections), 245.1ms
3: 384x640 (no detections), 245.1ms
4: 384x640 (no detections), 245.1ms
5: 384x640 (no detections), 245.1ms
6: 384x640 1 animal, 245.1ms
7: 384x640 (no detections), 245.1ms
8: 384x640 1 animal, 245.1ms
9: 384x640 1 animal, 245.1ms
10: 384x640 1 animal, 245.1ms
11: 384x640 1 animal, 245.1ms
12: 384x640 1 animal, 245.1ms
13: 384x640 1 animal, 245.1ms
14: 384x640 1 animal, 245.1ms
15: 384x640 1 animal, 245.1ms
Speed: 1.7ms preprocess, 245.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 18%|████████████████████████▋                                                                                                               | 33/182 [02:55<12:10,  4.90s/it]

0: 384x640 1 animal, 245.5ms
1: 384x640 1 animal, 245.5ms
2: 384x640 1 animal, 245.5ms
3: 384x640 1 animal, 245.5ms
4: 384x640 1 animal, 245.5ms
5: 384x640 1 animal, 245.5ms
6: 384x640 1 animal, 245.5ms
7: 384x640 1 animal, 245.5ms
8: 384x640 1 animal, 245.5ms
9: 384x640 1 animal, 245.5ms
10: 384x640 1 animal, 245.5ms
11: 384x640 1 animal, 245.5ms
12: 384x640 1 animal, 245.5ms
13: 384x640 1 animal, 245.5ms
14: 384x640 1 animal, 245.5ms
15: 384x640 (no detections), 245.5ms
Speed: 1.7ms preprocess, 245.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 19%|█████████████████████████▍                                                                                                              | 34/182 [03:00<11:54,  4.83s/it]

0: 640x640 (no detections), 408.7ms
1: 640x640 (no detections), 408.7ms
2: 640x640 (no detections), 408.7ms
3: 640x640 (no detections), 408.7ms
4: 640x640 (no detections), 408.7ms
5: 640x640 (no detections), 408.7ms
6: 640x640 1 animal, 408.7ms
7: 640x640 1 animal, 408.7ms
8: 640x640 1 animal, 408.7ms
9: 640x640 2 animals, 408.7ms
10: 640x640 (no detections), 408.7ms
11: 640x640 (no detections), 408.7ms
12: 640x640 (no detections), 408.7ms
13: 640x640 (no detections), 408.7ms
14: 640x640 (no detections), 408.7ms
15: 640x640 (no detections), 408.7ms
Speed: 2.5ms preprocess, 408.7ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 19%|██████████████████████████▏                                                                                                             | 35/182 [03:07<13:29,  5.51s/it]

0: 640x640 1 animal, 408.3ms
1: 640x640 1 animal, 408.3ms
2: 640x640 1 animal, 408.3ms
3: 640x640 1 animal, 408.3ms
4: 640x640 (no detections), 408.3ms
5: 640x640 (no detections), 408.3ms
6: 640x640 (no detections), 408.3ms
7: 640x640 (no detections), 408.3ms
8: 640x640 (no detections), 408.3ms
9: 640x640 (no detections), 408.3ms
10: 640x640 1 animal, 408.3ms
11: 640x640 1 animal, 408.3ms
12: 640x640 1 animal, 408.3ms
13: 640x640 1 animal, 408.3ms
14: 640x640 1 animal, 408.3ms
15: 640x640 1 animal, 408.3ms
Speed: 2.5ms preprocess, 408.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 20%|██████████████████████████▉                                                                                                             | 36/182 [03:14<14:31,  5.97s/it]

0: 384x640 1 animal, 244.1ms
1: 384x640 1 animal, 244.1ms
2: 384x640 1 animal, 244.1ms
3: 384x640 (no detections), 244.1ms
4: 384x640 1 animal, 244.1ms
5: 384x640 1 animal, 244.1ms
6: 384x640 1 animal, 244.1ms
7: 384x640 1 animal, 244.1ms
8: 384x640 1 animal, 244.1ms
9: 384x640 1 animal, 244.1ms
10: 384x640 1 animal, 244.1ms
11: 384x640 1 animal, 244.1ms
12: 384x640 1 animal, 244.1ms
13: 384x640 1 animal, 244.1ms
14: 384x640 1 animal, 244.1ms
15: 384x640 1 animal, 244.1ms
Speed: 1.8ms preprocess, 244.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 20%|███████████████████████████▋                                                                                                            | 37/182 [03:18<13:27,  5.57s/it]

0: 384x640 1 animal, 244.9ms
1: 384x640 1 animal, 244.9ms
2: 384x640 (no detections), 244.9ms
3: 384x640 (no detections), 244.9ms
4: 384x640 (no detections), 244.9ms
5: 384x640 (no detections), 244.9ms
6: 384x640 (no detections), 244.9ms
7: 384x640 (no detections), 244.9ms
8: 384x640 1 animal, 244.9ms
9: 384x640 1 animal, 244.9ms
10: 384x640 1 animal, 244.9ms
11: 384x640 1 animal, 244.9ms
12: 384x640 1 animal, 244.9ms
13: 384x640 1 animal, 244.9ms
14: 384x640 1 animal, 244.9ms
15: 384x640 1 animal, 244.9ms
Speed: 1.9ms preprocess, 244.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 21%|████████████████████████████▍                                                                                                           | 38/182 [03:23<12:42,  5.30s/it]

0: 640x640 1 animal, 411.5ms
1: 640x640 1 animal, 411.5ms
2: 640x640 1 animal, 411.5ms
3: 640x640 1 animal, 411.5ms
4: 640x640 1 animal, 411.5ms
5: 640x640 1 animal, 411.5ms
6: 640x640 1 animal, 411.5ms
7: 640x640 (no detections), 411.5ms
8: 640x640 (no detections), 411.5ms
9: 640x640 (no detections), 411.5ms
10: 640x640 (no detections), 411.5ms
11: 640x640 (no detections), 411.5ms
12: 640x640 1 animal, 411.5ms
13: 640x640 1 animal, 411.5ms
14: 640x640 1 animal, 411.5ms
15: 640x640 1 animal, 411.5ms
Speed: 2.6ms preprocess, 411.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 21%|█████████████████████████████▏                                                                                                          | 39/182 [03:30<13:57,  5.86s/it]

0: 384x640 1 animal, 248.2ms
1: 384x640 1 animal, 248.2ms
2: 384x640 (no detections), 248.2ms
3: 384x640 (no detections), 248.2ms
4: 384x640 (no detections), 248.2ms
5: 384x640 (no detections), 248.2ms
6: 384x640 1 animal, 248.2ms
7: 384x640 1 animal, 248.2ms
8: 384x640 1 animal, 248.2ms
9: 384x640 1 animal, 248.2ms
10: 384x640 1 animal, 248.2ms
11: 384x640 1 animal, 248.2ms
12: 384x640 1 animal, 248.2ms
13: 384x640 1 animal, 248.2ms
14: 384x640 1 animal, 248.2ms
15: 384x640 1 animal, 248.2ms
Speed: 1.9ms preprocess, 248.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 22%|█████████████████████████████▉                                                                                                          | 40/182 [03:35<13:08,  5.55s/it]

0: 640x640 1 animal, 409.1ms
1: 640x640 1 animal, 409.1ms
2: 640x640 (no detections), 409.1ms
3: 640x640 (no detections), 409.1ms
4: 640x640 (no detections), 409.1ms
5: 640x640 (no detections), 409.1ms
6: 640x640 (no detections), 409.1ms
7: 640x640 (no detections), 409.1ms
8: 640x640 (no detections), 409.1ms
9: 640x640 (no detections), 409.1ms
10: 640x640 1 animal, 409.1ms
11: 640x640 1 animal, 409.1ms
12: 640x640 1 animal, 409.1ms
13: 640x640 1 animal, 409.1ms
14: 640x640 2 animals, 409.1ms
15: 640x640 (no detections), 409.1ms
Speed: 2.6ms preprocess, 409.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 23%|██████████████████████████████▋                                                                                                         | 41/182 [03:42<14:09,  6.02s/it]

0: 640x640 (no detections), 409.7ms
1: 640x640 (no detections), 409.7ms
2: 640x640 (no detections), 409.7ms
3: 640x640 (no detections), 409.7ms
4: 640x640 1 animal, 409.7ms
5: 640x640 1 animal, 409.7ms
6: 640x640 1 animal, 409.7ms
7: 640x640 (no detections), 409.7ms
8: 640x640 (no detections), 409.7ms
9: 640x640 (no detections), 409.7ms
10: 640x640 (no detections), 409.7ms
11: 640x640 (no detections), 409.7ms
12: 640x640 (no detections), 409.7ms
13: 640x640 (no detections), 409.7ms
14: 640x640 1 animal, 409.7ms
15: 640x640 1 animal, 409.7ms
Speed: 2.5ms preprocess, 409.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 23%|███████████████████████████████▍                                                                                                        | 42/182 [03:49<14:48,  6.35s/it]

0: 384x640 (no detections), 246.7ms
1: 384x640 (no detections), 246.7ms
2: 384x640 (no detections), 246.7ms
3: 384x640 (no detections), 246.7ms
4: 384x640 (no detections), 246.7ms
5: 384x640 (no detections), 246.7ms
6: 384x640 (no detections), 246.7ms
7: 384x640 (no detections), 246.7ms
8: 384x640 1 animal, 246.7ms
9: 384x640 1 animal, 246.7ms
10: 384x640 1 animal, 246.7ms
11: 384x640 1 animal, 246.7ms
12: 384x640 1 animal, 246.7ms
13: 384x640 1 animal, 246.7ms
14: 384x640 1 animal, 246.7ms
15: 384x640 1 animal, 246.7ms
Speed: 2.1ms preprocess, 246.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 24%|████████████████████████████████▏                                                                                                       | 43/182 [03:54<13:33,  5.85s/it]

0: 384x640 (no detections), 244.2ms
1: 384x640 (no detections), 244.2ms
2: 384x640 (no detections), 244.2ms
3: 384x640 (no detections), 244.2ms
4: 384x640 (no detections), 244.2ms
5: 384x640 (no detections), 244.2ms
6: 384x640 (no detections), 244.2ms
7: 384x640 (no detections), 244.2ms
8: 384x640 1 animal, 244.2ms
9: 384x640 1 animal, 244.2ms
10: 384x640 1 animal, 244.2ms
11: 384x640 1 animal, 244.2ms
12: 384x640 1 animal, 244.2ms
13: 384x640 1 animal, 244.2ms
14: 384x640 1 animal, 244.2ms
15: 384x640 1 animal, 244.2ms
Speed: 1.7ms preprocess, 244.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 24%|████████████████████████████████▉                                                                                                       | 44/182 [03:59<12:37,  5.49s/it]

0: 384x640 1 animal, 245.8ms
1: 384x640 1 animal, 245.8ms
2: 384x640 (no detections), 245.8ms
3: 384x640 (no detections), 245.8ms
4: 384x640 (no detections), 245.8ms
5: 384x640 (no detections), 245.8ms
6: 384x640 1 animal, 245.8ms
7: 384x640 1 animal, 245.8ms
8: 384x640 2 animals, 245.8ms
9: 384x640 1 animal, 245.8ms
10: 384x640 1 animal, 245.8ms
11: 384x640 1 animal, 245.8ms
12: 384x640 2 animals, 245.8ms
13: 384x640 (no detections), 245.8ms
14: 384x640 (no detections), 245.8ms
15: 384x640 (no detections), 245.8ms
Speed: 1.7ms preprocess, 245.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 25%|█████████████████████████████████▋                                                                                                      | 45/182 [04:03<11:57,  5.24s/it]

0: 640x640 1 animal, 409.3ms
1: 640x640 1 animal, 409.3ms
2: 640x640 1 animal, 409.3ms
3: 640x640 1 animal, 409.3ms
4: 640x640 1 animal, 409.3ms
5: 640x640 (no detections), 409.3ms
6: 640x640 (no detections), 409.3ms
7: 640x640 (no detections), 409.3ms
8: 640x640 (no detections), 409.3ms
9: 640x640 (no detections), 409.3ms
10: 640x640 1 animal, 409.3ms
11: 640x640 1 animal, 409.3ms
12: 640x640 1 animal, 409.3ms
13: 640x640 1 animal, 409.3ms
14: 640x640 1 animal, 409.3ms
15: 640x640 (no detections), 409.3ms
Speed: 2.5ms preprocess, 409.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 25%|██████████████████████████████████▎                                                                                                     | 46/182 [04:10<13:08,  5.80s/it]

0: 384x640 (no detections), 245.7ms
1: 384x640 (no detections), 245.7ms
2: 384x640 (no detections), 245.7ms
3: 384x640 (no detections), 245.7ms
4: 384x640 1 animal, 245.7ms
5: 384x640 1 animal, 245.7ms
6: 384x640 1 animal, 245.7ms
7: 384x640 1 animal, 245.7ms
8: 384x640 1 animal, 245.7ms
9: 384x640 1 animal, 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 (no detections), 245.7ms
12: 384x640 1 animal, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 1 animal, 245.7ms
Speed: 1.9ms preprocess, 245.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 26%|███████████████████████████████████                                                                                                     | 47/182 [04:15<12:23,  5.51s/it]

0: 384x640 1 animal, 245.4ms
1: 384x640 (no detections), 245.4ms
2: 384x640 (no detections), 245.4ms
3: 384x640 (no detections), 245.4ms
4: 384x640 (no detections), 245.4ms
5: 384x640 (no detections), 245.4ms
6: 384x640 (no detections), 245.4ms
7: 384x640 (no detections), 245.4ms
8: 384x640 1 animal, 245.4ms
9: 384x640 1 animal, 245.4ms
10: 384x640 1 animal, 245.4ms
11: 384x640 1 animal, 245.4ms
12: 384x640 1 animal, 245.4ms
13: 384x640 1 animal, 245.4ms
14: 384x640 1 animal, 245.4ms
15: 384x640 1 animal, 245.4ms
Speed: 1.7ms preprocess, 245.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 26%|███████████████████████████████████▊                                                                                                    | 48/182 [04:20<11:49,  5.30s/it]

0: 384x640 1 animal, 244.9ms
1: 384x640 1 animal, 244.9ms
2: 384x640 1 animal, 244.9ms
3: 384x640 1 animal, 244.9ms
4: 384x640 1 animal, 244.9ms
5: 384x640 1 animal, 244.9ms
6: 384x640 1 animal, 244.9ms
7: 384x640 1 animal, 244.9ms
8: 384x640 1 animal, 244.9ms
9: 384x640 1 animal, 244.9ms
10: 384x640 1 animal, 244.9ms
11: 384x640 1 animal, 244.9ms
12: 384x640 1 animal, 244.9ms
13: 384x640 1 animal, 244.9ms
14: 384x640 1 animal, 244.9ms
15: 384x640 (no detections), 244.9ms
Speed: 2.0ms preprocess, 244.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 27%|████████████████████████████████████▌                                                                                                   | 49/182 [04:25<11:20,  5.11s/it]

0: 384x640 (no detections), 244.3ms
1: 384x640 (no detections), 244.3ms
2: 384x640 (no detections), 244.3ms
3: 384x640 (no detections), 244.3ms
4: 384x640 (no detections), 244.3ms
5: 384x640 (no detections), 244.3ms
6: 384x640 1 animal, 244.3ms
7: 384x640 (no detections), 244.3ms
8: 384x640 (no detections), 244.3ms
9: 384x640 (no detections), 244.3ms
10: 384x640 (no detections), 244.3ms
11: 384x640 (no detections), 244.3ms
12: 384x640 (no detections), 244.3ms
13: 384x640 (no detections), 244.3ms
14: 384x640 (no detections), 244.3ms
15: 384x640 (no detections), 244.3ms
Speed: 1.7ms preprocess, 244.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 27%|█████████████████████████████████████▎                                                                                                  | 50/182 [04:29<10:55,  4.96s/it]

0: 384x640 1 animal, 243.9ms
1: 384x640 1 animal, 243.9ms
2: 384x640 1 animal, 243.9ms
3: 384x640 2 animals, 243.9ms
4: 384x640 (no detections), 243.9ms
5: 384x640 (no detections), 243.9ms
6: 384x640 (no detections), 243.9ms
7: 384x640 (no detections), 243.9ms
8: 384x640 (no detections), 243.9ms
9: 384x640 (no detections), 243.9ms
10: 384x640 1 animal, 243.9ms
11: 384x640 1 animal, 243.9ms
12: 384x640 1 animal, 243.9ms
13: 384x640 1 animal, 243.9ms
14: 384x640 1 animal, 243.9ms
15: 384x640 1 animal, 243.9ms
Speed: 1.7ms preprocess, 243.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 28%|██████████████████████████████████████                                                                                                  | 51/182 [04:34<10:37,  4.87s/it]

0: 640x640 1 animal, 409.7ms
1: 640x640 1 animal, 409.7ms
2: 640x640 1 animal, 409.7ms
3: 640x640 (no detections), 409.7ms
4: 640x640 1 animal, 409.7ms
5: 640x640 1 animal, 409.7ms
6: 640x640 1 animal, 409.7ms
7: 640x640 1 animal, 409.7ms
8: 640x640 1 animal, 409.7ms
9: 640x640 2 animals, 409.7ms
10: 640x640 1 animal, 409.7ms
11: 640x640 (no detections), 409.7ms
12: 640x640 (no detections), 409.7ms
13: 640x640 (no detections), 409.7ms
14: 640x640 1 animal, 409.7ms
15: 640x640 1 animal, 409.7ms
Speed: 2.5ms preprocess, 409.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 29%|██████████████████████████████████████▊                                                                                                 | 52/182 [04:41<11:59,  5.53s/it]

0: 640x640 1 animal, 409.7ms
1: 640x640 1 animal, 409.7ms
2: 640x640 1 animal, 409.7ms
3: 640x640 1 animal, 409.7ms
4: 640x640 1 animal, 409.7ms
5: 640x640 (no detections), 409.7ms
6: 640x640 (no detections), 409.7ms
7: 640x640 (no detections), 409.7ms
8: 640x640 1 animal, 409.7ms
9: 640x640 1 animal, 409.7ms
10: 640x640 (no detections), 409.7ms
11: 640x640 (no detections), 409.7ms
12: 640x640 (no detections), 409.7ms
13: 640x640 1 animal, 409.7ms
14: 640x640 (no detections), 409.7ms
15: 640x640 (no detections), 409.7ms
Speed: 2.4ms preprocess, 409.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 29%|███████████████████████████████████████▌                                                                                                | 53/182 [04:48<12:55,  6.01s/it]

0: 640x640 1 animal, 413.2ms
1: 640x640 1 animal, 413.2ms
2: 640x640 2 animals, 413.2ms
3: 640x640 1 animal, 413.2ms
4: 640x640 1 animal, 413.2ms
5: 640x640 1 animal, 413.2ms
6: 640x640 1 animal, 413.2ms
7: 640x640 1 animal, 413.2ms
8: 640x640 1 animal, 413.2ms
9: 640x640 1 animal, 413.2ms
10: 640x640 1 animal, 413.2ms
11: 640x640 1 animal, 413.2ms
12: 640x640 1 animal, 413.2ms
13: 640x640 1 animal, 413.2ms
14: 640x640 1 animal, 413.2ms
15: 640x640 1 animal, 413.2ms
Speed: 2.5ms preprocess, 413.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 30%|████████████████████████████████████████▎                                                                                               | 54/182 [04:55<13:38,  6.40s/it]

0: 384x640 1 animal, 247.3ms
1: 384x640 1 animal, 247.3ms
2: 384x640 1 animal, 247.3ms
3: 384x640 1 animal, 247.3ms
4: 384x640 1 animal, 247.3ms
5: 384x640 1 animal, 247.3ms
6: 384x640 1 animal, 247.3ms
7: 384x640 1 animal, 247.3ms
8: 384x640 1 animal, 247.3ms
9: 384x640 1 animal, 247.3ms
10: 384x640 1 animal, 247.3ms
11: 384x640 (no detections), 247.3ms
12: 384x640 1 animal, 247.3ms
13: 384x640 (no detections), 247.3ms
14: 384x640 (no detections), 247.3ms
15: 384x640 (no detections), 247.3ms
Speed: 2.0ms preprocess, 247.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 30%|█████████████████████████████████████████                                                                                               | 55/182 [05:00<12:28,  5.89s/it]

0: 384x640 1 animal, 245.6ms
1: 384x640 1 animal, 245.6ms
2: 384x640 1 animal, 245.6ms
3: 384x640 1 animal, 245.6ms
4: 384x640 1 animal, 245.6ms
5: 384x640 1 animal, 245.6ms
6: 384x640 (no detections), 245.6ms
7: 384x640 (no detections), 245.6ms
8: 384x640 (no detections), 245.6ms
9: 384x640 (no detections), 245.6ms
10: 384x640 1 animal, 245.6ms
11: 384x640 1 animal, 245.6ms
12: 384x640 1 animal, 245.6ms
13: 384x640 1 animal, 245.6ms
14: 384x640 1 animal, 245.6ms
15: 384x640 1 animal, 245.6ms
Speed: 1.7ms preprocess, 245.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 31%|█████████████████████████████████████████▊                                                                                              | 56/182 [05:05<11:35,  5.52s/it]

0: 384x640 1 animal, 245.3ms
1: 384x640 (no detections), 245.3ms
2: 384x640 (no detections), 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 1 animal, 245.3ms
5: 384x640 1 animal, 245.3ms
6: 384x640 1 animal, 245.3ms
7: 384x640 1 animal, 245.3ms
8: 384x640 1 animal, 245.3ms
9: 384x640 1 animal, 245.3ms
10: 384x640 1 animal, 245.3ms
11: 384x640 1 animal, 245.3ms
12: 384x640 1 animal, 245.3ms
13: 384x640 1 animal, 245.3ms
14: 384x640 1 animal, 245.3ms
15: 384x640 2 animals, 245.3ms
Speed: 1.9ms preprocess, 245.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 31%|██████████████████████████████████████████▌                                                                                             | 57/182 [05:10<10:59,  5.27s/it]

0: 384x640 2 animals, 243.1ms
1: 384x640 2 animals, 243.1ms
2: 384x640 2 animals, 243.1ms
3: 384x640 2 animals, 243.1ms
4: 384x640 1 animal, 243.1ms
5: 384x640 3 animals, 243.1ms
6: 384x640 2 animals, 243.1ms
7: 384x640 2 animals, 243.1ms
8: 384x640 (no detections), 243.1ms
9: 384x640 1 animal, 243.1ms
10: 384x640 2 animals, 243.1ms
11: 384x640 1 animal, 243.1ms
12: 384x640 1 animal, 243.1ms
13: 384x640 1 animal, 243.1ms
14: 384x640 1 animal, 243.1ms
15: 384x640 1 animal, 243.1ms
Speed: 1.9ms preprocess, 243.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 32%|███████████████████████████████████████████▎                                                                                            | 58/182 [05:14<10:30,  5.08s/it]

0: 640x640 1 animal, 412.1ms
1: 640x640 1 animal, 412.1ms
2: 640x640 1 animal, 412.1ms
3: 640x640 1 animal, 412.1ms
4: 640x640 (no detections), 412.1ms
5: 640x640 1 animal, 412.1ms
6: 640x640 1 animal, 412.1ms
7: 640x640 1 animal, 412.1ms
8: 640x640 1 animal, 412.1ms
9: 640x640 1 animal, 412.1ms
10: 640x640 (no detections), 412.1ms
11: 640x640 (no detections), 412.1ms
12: 640x640 1 animal, 412.1ms
13: 640x640 1 animal, 412.1ms
14: 640x640 (no detections), 412.1ms
15: 640x640 1 animal, 412.1ms
Speed: 2.5ms preprocess, 412.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 32%|████████████████████████████████████████████                                                                                            | 59/182 [05:21<11:45,  5.73s/it]

0: 640x640 1 animal, 414.4ms
1: 640x640 (no detections), 414.4ms
2: 640x640 1 animal, 414.4ms
3: 640x640 1 animal, 414.4ms
4: 640x640 1 animal, 414.4ms
5: 640x640 1 animal, 414.4ms
6: 640x640 1 animal, 414.4ms
7: 640x640 1 animal, 414.4ms
8: 640x640 1 animal, 414.4ms
9: 640x640 2 animals, 414.4ms
10: 640x640 (no detections), 414.4ms
11: 640x640 1 animal, 414.4ms
12: 640x640 1 animal, 414.4ms
13: 640x640 (no detections), 414.4ms
14: 640x640 1 animal, 414.4ms
15: 640x640 (no detections), 414.4ms
Speed: 2.8ms preprocess, 414.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 33%|████████████████████████████████████████████▊                                                                                           | 60/182 [05:29<12:35,  6.19s/it]

0: 384x640 1 animal, 244.9ms
1: 384x640 1 animal, 244.9ms
2: 384x640 1 animal, 244.9ms
3: 384x640 1 animal, 244.9ms
4: 384x640 1 animal, 244.9ms
5: 384x640 1 animal, 244.9ms
6: 384x640 2 animals, 244.9ms
7: 384x640 2 animals, 244.9ms
8: 384x640 2 animals, 244.9ms
9: 384x640 1 animal, 244.9ms
10: 384x640 1 animal, 244.9ms
11: 384x640 (no detections), 244.9ms
12: 384x640 1 animal, 244.9ms
13: 384x640 (no detections), 244.9ms
14: 384x640 (no detections), 244.9ms
15: 384x640 (no detections), 244.9ms
Speed: 1.9ms preprocess, 244.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 34%|█████████████████████████████████████████████▌                                                                                          | 61/182 [05:33<11:34,  5.74s/it]

0: 640x640 (no detections), 407.2ms
1: 640x640 (no detections), 407.2ms
2: 640x640 (no detections), 407.2ms
3: 640x640 (no detections), 407.2ms
4: 640x640 1 animal, 407.2ms
5: 640x640 1 animal, 407.2ms
6: 640x640 (no detections), 407.2ms
7: 640x640 (no detections), 407.2ms
8: 640x640 1 animal, 407.2ms
9: 640x640 2 animals, 407.2ms
10: 640x640 2 animals, 407.2ms
11: 640x640 2 animals, 407.2ms
12: 640x640 2 animals, 407.2ms
13: 640x640 2 animals, 407.2ms
14: 640x640 1 animal, 407.2ms
15: 640x640 1 animal, 407.2ms
Speed: 2.6ms preprocess, 407.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 34%|██████████████████████████████████████████████▎                                                                                         | 62/182 [05:41<12:26,  6.22s/it]

0: 640x640 1 animal, 409.0ms
1: 640x640 1 animal, 409.0ms
2: 640x640 1 animal, 409.0ms
3: 640x640 1 animal, 409.0ms
4: 640x640 (no detections), 409.0ms
5: 640x640 (no detections), 409.0ms
6: 640x640 (no detections), 409.0ms
7: 640x640 (no detections), 409.0ms
8: 640x640 1 animal, 409.0ms
9: 640x640 1 animal, 409.0ms
10: 640x640 1 animal, 409.0ms
11: 640x640 1 animal, 409.0ms
12: 640x640 1 animal, 409.0ms
13: 640x640 1 animal, 409.0ms
14: 640x640 1 animal, 409.0ms
15: 640x640 1 animal, 409.0ms
Speed: 2.8ms preprocess, 409.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 35%|███████████████████████████████████████████████                                                                                         | 63/182 [05:48<12:54,  6.51s/it]

0: 384x640 1 animal, 243.5ms
1: 384x640 1 animal, 243.5ms
2: 384x640 1 animal, 243.5ms
3: 384x640 1 animal, 243.5ms
4: 384x640 1 animal, 243.5ms
5: 384x640 1 animal, 243.5ms
6: 384x640 1 animal, 243.5ms
7: 384x640 1 animal, 243.5ms
8: 384x640 1 animal, 243.5ms
9: 384x640 1 animal, 243.5ms
10: 384x640 (no detections), 243.5ms
11: 384x640 (no detections), 243.5ms
12: 384x640 1 animal, 243.5ms
13: 384x640 1 animal, 243.5ms
14: 384x640 1 animal, 243.5ms
15: 384x640 1 animal, 243.5ms
Speed: 1.7ms preprocess, 243.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 35%|███████████████████████████████████████████████▊                                                                                        | 64/182 [05:53<11:42,  5.95s/it]

0: 640x640 1 animal, 407.8ms
1: 640x640 (no detections), 407.8ms
2: 640x640 (no detections), 407.8ms
3: 640x640 (no detections), 407.8ms
4: 640x640 (no detections), 407.8ms
5: 640x640 (no detections), 407.8ms
6: 640x640 1 animal, 407.8ms
7: 640x640 1 animal, 407.8ms
8: 640x640 (no detections), 407.8ms
9: 640x640 (no detections), 407.8ms
10: 640x640 (no detections), 407.8ms
11: 640x640 (no detections), 407.8ms
12: 640x640 (no detections), 407.8ms
13: 640x640 (no detections), 407.8ms
14: 640x640 (no detections), 407.8ms
15: 640x640 (no detections), 407.8ms
Speed: 2.4ms preprocess, 407.8ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 36%|████████████████████████████████████████████████▌                                                                                       | 65/182 [06:00<12:15,  6.28s/it]

0: 384x640 2 animals, 246.3ms
1: 384x640 (no detections), 246.3ms
2: 384x640 (no detections), 246.3ms
3: 384x640 (no detections), 246.3ms
4: 384x640 (no detections), 246.3ms
5: 384x640 (no detections), 246.3ms
6: 384x640 (no detections), 246.3ms
7: 384x640 (no detections), 246.3ms
8: 384x640 (no detections), 246.3ms
9: 384x640 (no detections), 246.3ms
10: 384x640 1 animal, 246.3ms
11: 384x640 (no detections), 246.3ms
12: 384x640 (no detections), 246.3ms
13: 384x640 (no detections), 246.3ms
14: 384x640 (no detections), 246.3ms
15: 384x640 (no detections), 246.3ms
Speed: 2.0ms preprocess, 246.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 36%|█████████████████████████████████████████████████▎                                                                                      | 66/182 [06:04<11:13,  5.81s/it]

0: 384x640 (no detections), 244.9ms
1: 384x640 (no detections), 244.9ms
2: 384x640 (no detections), 244.9ms
3: 384x640 (no detections), 244.9ms
4: 384x640 1 animal, 244.9ms
5: 384x640 1 animal, 244.9ms
6: 384x640 1 animal, 244.9ms
7: 384x640 1 animal, 244.9ms
8: 384x640 1 animal, 244.9ms
9: 384x640 1 animal, 244.9ms
10: 384x640 1 animal, 244.9ms
11: 384x640 1 animal, 244.9ms
12: 384x640 1 animal, 244.9ms
13: 384x640 1 animal, 244.9ms
14: 384x640 1 animal, 244.9ms
15: 384x640 1 animal, 244.9ms
Speed: 1.7ms preprocess, 244.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 37%|██████████████████████████████████████████████████                                                                                      | 67/182 [06:09<10:27,  5.46s/it]

0: 384x640 1 animal, 243.6ms
1: 384x640 1 animal, 243.6ms
2: 384x640 1 animal, 243.6ms
3: 384x640 (no detections), 243.6ms
4: 384x640 (no detections), 243.6ms
5: 384x640 (no detections), 243.6ms
6: 384x640 (no detections), 243.6ms
7: 384x640 (no detections), 243.6ms
8: 384x640 1 animal, 243.6ms
9: 384x640 1 animal, 243.6ms
10: 384x640 1 animal, 243.6ms
11: 384x640 1 animal, 243.6ms
12: 384x640 (no detections), 243.6ms
13: 384x640 (no detections), 243.6ms
14: 384x640 (no detections), 243.6ms
15: 384x640 (no detections), 243.6ms
Speed: 1.9ms preprocess, 243.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 37%|██████████████████████████████████████████████████▊                                                                                     | 68/182 [06:14<09:54,  5.22s/it]

0: 640x640 (no detections), 413.0ms
1: 640x640 (no detections), 413.0ms
2: 640x640 1 animal, 413.0ms
3: 640x640 1 animal, 413.0ms
4: 640x640 (no detections), 413.0ms
5: 640x640 (no detections), 413.0ms
6: 640x640 (no detections), 413.0ms
7: 640x640 (no detections), 413.0ms
8: 640x640 (no detections), 413.0ms
9: 640x640 (no detections), 413.0ms
10: 640x640 (no detections), 413.0ms
11: 640x640 (no detections), 413.0ms
12: 640x640 1 animal, 413.0ms
13: 640x640 1 animal, 413.0ms
14: 640x640 1 animal, 413.0ms
15: 640x640 1 animal, 413.0ms
Speed: 2.7ms preprocess, 413.0ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 38%|███████████████████████████████████████████████████▌                                                                                    | 69/182 [06:21<10:54,  5.79s/it]

0: 384x640 1 animal, 245.4ms
1: 384x640 1 animal, 245.4ms
2: 384x640 1 animal, 245.4ms
3: 384x640 1 animal, 245.4ms
4: 384x640 1 animal, 245.4ms
5: 384x640 (no detections), 245.4ms
6: 384x640 (no detections), 245.4ms
7: 384x640 (no detections), 245.4ms
8: 384x640 1 animal, 245.4ms
9: 384x640 1 animal, 245.4ms
10: 384x640 1 animal, 245.4ms
11: 384x640 1 animal, 245.4ms
12: 384x640 1 animal, 245.4ms
13: 384x640 1 animal, 245.4ms
14: 384x640 1 animal, 245.4ms
15: 384x640 (no detections), 245.4ms
Speed: 1.9ms preprocess, 245.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 38%|████████████████████████████████████████████████████▎                                                                                   | 70/182 [06:25<10:10,  5.45s/it]

0: 384x640 1 animal, 244.4ms
1: 384x640 1 animal, 244.4ms
2: 384x640 (no detections), 244.4ms
3: 384x640 (no detections), 244.4ms
4: 384x640 (no detections), 244.4ms
5: 384x640 (no detections), 244.4ms
6: 384x640 (no detections), 244.4ms
7: 384x640 (no detections), 244.4ms
8: 384x640 (no detections), 244.4ms
9: 384x640 (no detections), 244.4ms
10: 384x640 1 animal, 244.4ms
11: 384x640 1 animal, 244.4ms
12: 384x640 1 animal, 244.4ms
13: 384x640 1 animal, 244.4ms
14: 384x640 1 animal, 244.4ms
15: 384x640 1 animal, 244.4ms
Speed: 1.7ms preprocess, 244.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 39%|█████████████████████████████████████████████████████                                                                                   | 71/182 [06:30<09:38,  5.21s/it]

0: 640x640 1 animal, 404.3ms
1: 640x640 1 animal, 404.3ms
2: 640x640 1 animal, 404.3ms
3: 640x640 1 animal, 404.3ms
4: 640x640 1 animal, 404.3ms
5: 640x640 1 animal, 404.3ms
6: 640x640 1 animal, 404.3ms
7: 640x640 1 animal, 404.3ms
8: 640x640 (no detections), 404.3ms
9: 640x640 (no detections), 404.3ms
10: 640x640 (no detections), 404.3ms
11: 640x640 (no detections), 404.3ms
12: 640x640 (no detections), 404.3ms
13: 640x640 (no detections), 404.3ms
14: 640x640 1 animal, 404.3ms
15: 640x640 1 animal, 404.3ms
Speed: 2.5ms preprocess, 404.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 40%|█████████████████████████████████████████████████████▊                                                                                  | 72/182 [06:37<10:32,  5.75s/it]

0: 640x640 1 animal, 416.2ms
1: 640x640 1 animal, 416.2ms
2: 640x640 1 animal, 416.2ms
3: 640x640 1 animal, 416.2ms
4: 640x640 1 animal, 416.2ms
5: 640x640 1 animal, 416.2ms
6: 640x640 1 animal, 416.2ms
7: 640x640 1 animal, 416.2ms
8: 640x640 1 animal, 416.2ms
9: 640x640 1 animal, 416.2ms
10: 640x640 1 animal, 416.2ms
11: 640x640 1 animal, 416.2ms
12: 640x640 (no detections), 416.2ms
13: 640x640 (no detections), 416.2ms
14: 640x640 (no detections), 416.2ms
15: 640x640 (no detections), 416.2ms
Speed: 2.5ms preprocess, 416.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 40%|██████████████████████████████████████████████████████▌                                                                                 | 73/182 [06:44<11:16,  6.20s/it]

0: 384x640 (no detections), 242.1ms
1: 384x640 (no detections), 242.1ms
2: 384x640 1 animal, 242.1ms
3: 384x640 1 animal, 242.1ms
4: 384x640 1 animal, 242.1ms
5: 384x640 1 animal, 242.1ms
6: 384x640 1 animal, 242.1ms
7: 384x640 1 animal, 242.1ms
8: 384x640 1 animal, 242.1ms
9: 384x640 1 animal, 242.1ms
10: 384x640 1 animal, 242.1ms
11: 384x640 1 animal, 242.1ms
12: 384x640 1 animal, 242.1ms
13: 384x640 1 animal, 242.1ms
14: 384x640 1 animal, 242.1ms
15: 384x640 1 animal, 242.1ms
Speed: 1.6ms preprocess, 242.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 41%|███████████████████████████████████████████████████████▎                                                                                | 74/182 [06:49<10:06,  5.62s/it]

0: 384x640 1 animal, 241.3ms
1: 384x640 1 animal, 241.3ms
2: 384x640 1 animal, 241.3ms
3: 384x640 2 animals, 241.3ms
4: 384x640 2 animals, 241.3ms
5: 384x640 2 animals, 241.3ms
6: 384x640 1 animal, 241.3ms
7: 384x640 1 animal, 241.3ms
8: 384x640 1 animal, 241.3ms
9: 384x640 (no detections), 241.3ms
10: 384x640 (no detections), 241.3ms
11: 384x640 (no detections), 241.3ms
12: 384x640 (no detections), 241.3ms
13: 384x640 (no detections), 241.3ms
14: 384x640 (no detections), 241.3ms
15: 384x640 (no detections), 241.3ms
Speed: 1.7ms preprocess, 241.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 41%|████████████████████████████████████████████████████████                                                                                | 75/182 [06:53<09:16,  5.20s/it]

0: 640x640 1 animal, 408.1ms
1: 640x640 1 animal, 408.1ms
2: 640x640 1 animal, 408.1ms
3: 640x640 1 animal, 408.1ms
4: 640x640 1 animal, 408.1ms
5: 640x640 (no detections), 408.1ms
6: 640x640 (no detections), 408.1ms
7: 640x640 (no detections), 408.1ms
8: 640x640 (no detections), 408.1ms
9: 640x640 (no detections), 408.1ms
10: 640x640 1 animal, 408.1ms
11: 640x640 1 animal, 408.1ms
12: 640x640 1 animal, 408.1ms
13: 640x640 1 animal, 408.1ms
14: 640x640 1 animal, 408.1ms
15: 640x640 1 animal, 408.1ms
Speed: 2.5ms preprocess, 408.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 42%|████████████████████████████████████████████████████████▊                                                                               | 76/182 [07:00<10:10,  5.76s/it]

0: 640x640 1 animal, 412.8ms
1: 640x640 1 animal, 412.8ms
2: 640x640 1 animal, 412.8ms
3: 640x640 1 animal, 412.8ms
4: 640x640 2 animals, 412.8ms
5: 640x640 1 animal, 412.8ms
6: 640x640 1 animal, 412.8ms
7: 640x640 1 animal, 412.8ms
8: 640x640 1 animal, 412.8ms
9: 640x640 1 animal, 412.8ms
10: 640x640 1 animal, 412.8ms
11: 640x640 1 animal, 412.8ms
12: 640x640 1 animal, 412.8ms
13: 640x640 1 animal, 412.8ms
14: 640x640 1 animal, 412.8ms
15: 640x640 1 animal, 412.8ms
Speed: 2.5ms preprocess, 412.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 42%|█████████████████████████████████████████████████████████▌                                                                              | 77/182 [07:07<10:53,  6.22s/it]

0: 640x640 (no detections), 409.7ms
1: 640x640 (no detections), 409.7ms
2: 640x640 (no detections), 409.7ms
3: 640x640 (no detections), 409.7ms
4: 640x640 (no detections), 409.7ms
5: 640x640 (no detections), 409.7ms
6: 640x640 (no detections), 409.7ms
7: 640x640 (no detections), 409.7ms
8: 640x640 1 animal, 409.7ms
9: 640x640 2 animals, 409.7ms
10: 640x640 1 animal, 409.7ms
11: 640x640 2 animals, 409.7ms
12: 640x640 1 animal, 409.7ms
13: 640x640 1 animal, 409.7ms
14: 640x640 1 animal, 409.7ms
15: 640x640 1 animal, 409.7ms
Speed: 2.6ms preprocess, 409.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 43%|██████████████████████████████████████████████████████████▎                                                                             | 78/182 [07:14<11:14,  6.49s/it]

0: 384x640 1 animal, 243.9ms
1: 384x640 1 animal, 243.9ms
2: 384x640 1 animal, 243.9ms
3: 384x640 1 animal, 243.9ms
4: 384x640 1 animal, 243.9ms
5: 384x640 1 animal, 243.9ms
6: 384x640 1 animal, 243.9ms
7: 384x640 1 animal, 243.9ms
8: 384x640 1 animal, 243.9ms
9: 384x640 1 animal, 243.9ms
10: 384x640 1 animal, 243.9ms
11: 384x640 1 animal, 243.9ms
12: 384x640 2 animals, 243.9ms
13: 384x640 1 animal, 243.9ms
14: 384x640 1 animal, 243.9ms
15: 384x640 1 animal, 243.9ms
Speed: 1.8ms preprocess, 243.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 43%|███████████████████████████████████████████████████████████                                                                             | 79/182 [07:19<10:10,  5.93s/it]

0: 640x640 1 animal, 412.2ms
1: 640x640 1 animal, 412.2ms
2: 640x640 1 animal, 412.2ms
3: 640x640 1 animal, 412.2ms
4: 640x640 1 animal, 412.2ms
5: 640x640 1 animal, 412.2ms
6: 640x640 1 animal, 412.2ms
7: 640x640 1 animal, 412.2ms
8: 640x640 1 animal, 412.2ms
9: 640x640 1 animal, 412.2ms
10: 640x640 1 animal, 412.2ms
11: 640x640 1 animal, 412.2ms
12: 640x640 1 animal, 412.2ms
13: 640x640 (no detections), 412.2ms
14: 640x640 (no detections), 412.2ms
15: 640x640 (no detections), 412.2ms
Speed: 2.4ms preprocess, 412.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 44%|███████████████████████████████████████████████████████████▊                                                                            | 80/182 [07:26<10:41,  6.29s/it]

0: 640x640 2 animals, 414.9ms
1: 640x640 1 animal, 414.9ms
2: 640x640 1 animal, 414.9ms
3: 640x640 1 animal, 414.9ms
4: 640x640 1 animal, 414.9ms
5: 640x640 1 animal, 414.9ms
6: 640x640 1 animal, 414.9ms
7: 640x640 1 animal, 414.9ms
8: 640x640 1 animal, 414.9ms
9: 640x640 2 animals, 414.9ms
10: 640x640 1 animal, 414.9ms
11: 640x640 1 animal, 414.9ms
12: 640x640 1 animal, 414.9ms
13: 640x640 1 animal, 414.9ms
14: 640x640 1 animal, 414.9ms
15: 640x640 1 animal, 414.9ms
Speed: 2.5ms preprocess, 414.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 45%|████████████████████████████████████████████████████████████▌                                                                           | 81/182 [07:33<11:04,  6.58s/it]

0: 640x640 1 animal, 411.7ms
1: 640x640 1 animal, 411.7ms
2: 640x640 1 animal, 411.7ms
3: 640x640 (no detections), 411.7ms
4: 640x640 1 animal, 411.7ms
5: 640x640 1 animal, 411.7ms
6: 640x640 1 animal, 411.7ms
7: 640x640 1 animal, 411.7ms
8: 640x640 1 animal, 411.7ms
9: 640x640 1 animal, 411.7ms
10: 640x640 (no detections), 411.7ms
11: 640x640 (no detections), 411.7ms
12: 640x640 (no detections), 411.7ms
13: 640x640 (no detections), 411.7ms
14: 640x640 1 animal, 411.7ms
15: 640x640 1 animal, 411.7ms
Speed: 2.5ms preprocess, 411.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 45%|█████████████████████████████████████████████████████████████▎                                                                          | 82/182 [07:41<11:18,  6.78s/it]

0: 384x640 1 animal, 246.0ms
1: 384x640 1 animal, 246.0ms
2: 384x640 (no detections), 246.0ms
3: 384x640 (no detections), 246.0ms
4: 384x640 (no detections), 246.0ms
5: 384x640 (no detections), 246.0ms
6: 384x640 (no detections), 246.0ms
7: 384x640 1 animal, 246.0ms
8: 384x640 1 animal, 246.0ms
9: 384x640 (no detections), 246.0ms
10: 384x640 (no detections), 246.0ms
11: 384x640 (no detections), 246.0ms
12: 384x640 (no detections), 246.0ms
13: 384x640 (no detections), 246.0ms
14: 384x640 (no detections), 246.0ms
15: 384x640 (no detections), 246.0ms
Speed: 2.0ms preprocess, 246.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 46%|██████████████████████████████████████████████████████████████                                                                          | 83/182 [07:45<10:09,  6.16s/it]

0: 640x640 (no detections), 411.2ms
1: 640x640 (no detections), 411.2ms
2: 640x640 1 animal, 411.2ms
3: 640x640 1 animal, 411.2ms
4: 640x640 1 animal, 411.2ms
5: 640x640 1 animal, 411.2ms
6: 640x640 (no detections), 411.2ms
7: 640x640 (no detections), 411.2ms
8: 640x640 (no detections), 411.2ms
9: 640x640 (no detections), 411.2ms
10: 640x640 (no detections), 411.2ms
11: 640x640 (no detections), 411.2ms
12: 640x640 1 animal, 411.2ms
13: 640x640 (no detections), 411.2ms
14: 640x640 (no detections), 411.2ms
15: 640x640 (no detections), 411.2ms
Speed: 2.5ms preprocess, 411.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 46%|██████████████████████████████████████████████████████████████▊                                                                         | 84/182 [07:52<10:31,  6.44s/it]

0: 384x640 (no detections), 245.6ms
1: 384x640 (no detections), 245.6ms
2: 384x640 (no detections), 245.6ms
3: 384x640 (no detections), 245.6ms
4: 384x640 (no detections), 245.6ms
5: 384x640 (no detections), 245.6ms
6: 384x640 1 animal, 245.6ms
7: 384x640 1 animal, 245.6ms
8: 384x640 1 animal, 245.6ms
9: 384x640 1 animal, 245.6ms
10: 384x640 1 animal, 245.6ms
11: 384x640 1 animal, 245.6ms
12: 384x640 1 animal, 245.6ms
13: 384x640 1 animal, 245.6ms
14: 384x640 1 animal, 245.6ms
15: 384x640 1 animal, 245.6ms
Speed: 1.7ms preprocess, 245.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 47%|███████████████████████████████████████████████████████████████▌                                                                        | 85/182 [07:57<09:33,  5.91s/it]

0: 384x640 1 animal, 246.1ms
1: 384x640 1 animal, 246.1ms
2: 384x640 1 animal, 246.1ms
3: 384x640 1 animal, 246.1ms
4: 384x640 1 animal, 246.1ms
5: 384x640 1 animal, 246.1ms
6: 384x640 1 animal, 246.1ms
7: 384x640 1 animal, 246.1ms
8: 384x640 1 animal, 246.1ms
9: 384x640 1 animal, 246.1ms
10: 384x640 1 animal, 246.1ms
11: 384x640 (no detections), 246.1ms
12: 384x640 (no detections), 246.1ms
13: 384x640 (no detections), 246.1ms
14: 384x640 (no detections), 246.1ms
15: 384x640 (no detections), 246.1ms
Speed: 1.7ms preprocess, 246.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 47%|████████████████████████████████████████████████████████████████▎                                                                       | 86/182 [08:02<08:51,  5.54s/it]

0: 640x640 (no detections), 409.1ms
1: 640x640 (no detections), 409.1ms
2: 640x640 (no detections), 409.1ms
3: 640x640 (no detections), 409.1ms
4: 640x640 1 animal, 409.1ms
5: 640x640 1 animal, 409.1ms
6: 640x640 1 animal, 409.1ms
7: 640x640 (no detections), 409.1ms
8: 640x640 (no detections), 409.1ms
9: 640x640 (no detections), 409.1ms
10: 640x640 (no detections), 409.1ms
11: 640x640 (no detections), 409.1ms
12: 640x640 (no detections), 409.1ms
13: 640x640 (no detections), 409.1ms
14: 640x640 1 animal, 409.1ms
15: 640x640 1 animal, 409.1ms
Speed: 2.4ms preprocess, 409.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 48%|█████████████████████████████████████████████████████████████████                                                                       | 87/182 [08:09<09:28,  5.99s/it]

0: 384x640 1 animal, 240.8ms
1: 384x640 (no detections), 240.8ms
2: 384x640 (no detections), 240.8ms
3: 384x640 (no detections), 240.8ms
4: 384x640 (no detections), 240.8ms
5: 384x640 (no detections), 240.8ms
6: 384x640 (no detections), 240.8ms
7: 384x640 (no detections), 240.8ms
8: 384x640 1 animal, 240.8ms
9: 384x640 1 animal, 240.8ms
10: 384x640 (no detections), 240.8ms
11: 384x640 (no detections), 240.8ms
12: 384x640 (no detections), 240.8ms
13: 384x640 (no detections), 240.8ms
14: 384x640 (no detections), 240.8ms
15: 384x640 (no detections), 240.8ms
Speed: 1.8ms preprocess, 240.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 48%|█████████████████████████████████████████████████████████████████▊                                                                      | 88/182 [08:13<08:33,  5.46s/it]

0: 640x640 (no detections), 411.5ms
1: 640x640 (no detections), 411.5ms
2: 640x640 1 animal, 411.5ms
3: 640x640 1 animal, 411.5ms
4: 640x640 1 animal, 411.5ms
5: 640x640 1 animal, 411.5ms
6: 640x640 1 animal, 411.5ms
7: 640x640 1 animal, 411.5ms
8: 640x640 1 animal, 411.5ms
9: 640x640 1 animal, 411.5ms
10: 640x640 (no detections), 411.5ms
11: 640x640 (no detections), 411.5ms
12: 640x640 1 animal, 411.5ms
13: 640x640 1 animal, 411.5ms
14: 640x640 1 animal, 411.5ms
15: 640x640 1 animal, 411.5ms
Speed: 2.5ms preprocess, 411.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 49%|██████████████████████████████████████████████████████████████████▌                                                                     | 89/182 [08:20<09:12,  5.94s/it]

0: 384x640 1 animal, 245.2ms
1: 384x640 1 animal, 245.2ms
2: 384x640 1 animal, 245.2ms
3: 384x640 1 animal, 245.2ms
4: 384x640 (no detections), 245.2ms
5: 384x640 (no detections), 245.2ms
6: 384x640 1 animal, 245.2ms
7: 384x640 1 animal, 245.2ms
8: 384x640 1 animal, 245.2ms
9: 384x640 1 animal, 245.2ms
10: 384x640 1 animal, 245.2ms
11: 384x640 1 animal, 245.2ms
12: 384x640 1 animal, 245.2ms
13: 384x640 1 animal, 245.2ms
14: 384x640 1 animal, 245.2ms
15: 384x640 (no detections), 245.2ms
Speed: 1.8ms preprocess, 245.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 49%|███████████████████████████████████████████████████████████████████▎                                                                    | 90/182 [08:25<08:31,  5.56s/it]

0: 384x640 1 animal, 242.6ms
1: 384x640 1 animal, 242.6ms
2: 384x640 1 animal, 242.6ms
3: 384x640 (no detections), 242.6ms
4: 384x640 (no detections), 242.6ms
5: 384x640 1 animal, 242.6ms
6: 384x640 (no detections), 242.6ms
7: 384x640 (no detections), 242.6ms
8: 384x640 (no detections), 242.6ms
9: 384x640 (no detections), 242.6ms
10: 384x640 1 animal, 242.6ms
11: 384x640 1 animal, 242.6ms
12: 384x640 1 animal, 242.6ms
13: 384x640 1 animal, 242.6ms
14: 384x640 1 animal, 242.6ms
15: 384x640 1 animal, 242.6ms
Speed: 1.8ms preprocess, 242.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 50%|████████████████████████████████████████████████████████████████████                                                                    | 91/182 [08:29<08:00,  5.28s/it]

0: 384x640 1 animal, 236.2ms
1: 384x640 (no detections), 236.2ms
2: 384x640 (no detections), 236.2ms
3: 384x640 (no detections), 236.2ms
4: 384x640 1 animal, 236.2ms
5: 384x640 1 animal, 236.2ms
6: 384x640 1 animal, 236.2ms
7: 384x640 (no detections), 236.2ms
8: 384x640 (no detections), 236.2ms
9: 384x640 (no detections), 236.2ms
10: 384x640 (no detections), 236.2ms
11: 384x640 (no detections), 236.2ms
12: 384x640 (no detections), 236.2ms
13: 384x640 (no detections), 236.2ms
14: 384x640 1 animal, 236.2ms
15: 384x640 (no detections), 236.2ms
Speed: 1.7ms preprocess, 236.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 51%|████████████████████████████████████████████████████████████████████▋                                                                   | 92/182 [08:34<07:34,  5.05s/it]

0: 384x640 1 animal, 238.1ms
1: 384x640 1 animal, 238.1ms
2: 384x640 1 animal, 238.1ms
3: 384x640 1 animal, 238.1ms
4: 384x640 1 animal, 238.1ms
5: 384x640 1 animal, 238.1ms
6: 384x640 (no detections), 238.1ms
7: 384x640 (no detections), 238.1ms
8: 384x640 1 animal, 238.1ms
9: 384x640 1 animal, 238.1ms
10: 384x640 (no detections), 238.1ms
11: 384x640 (no detections), 238.1ms
12: 384x640 (no detections), 238.1ms
13: 384x640 (no detections), 238.1ms
14: 384x640 (no detections), 238.1ms
15: 384x640 (no detections), 238.1ms
Speed: 1.7ms preprocess, 238.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 51%|█████████████████████████████████████████████████████████████████████▍                                                                  | 93/182 [08:38<07:15,  4.89s/it]

0: 384x640 (no detections), 241.0ms
1: 384x640 (no detections), 241.0ms
2: 384x640 (no detections), 241.0ms
3: 384x640 (no detections), 241.0ms
4: 384x640 (no detections), 241.0ms
5: 384x640 (no detections), 241.0ms
6: 384x640 (no detections), 241.0ms
7: 384x640 (no detections), 241.0ms
8: 384x640 (no detections), 241.0ms
9: 384x640 (no detections), 241.0ms
10: 384x640 (no detections), 241.0ms
11: 384x640 (no detections), 241.0ms
12: 384x640 1 animal, 241.0ms
13: 384x640 (no detections), 241.0ms
14: 384x640 (no detections), 241.0ms
15: 384x640 (no detections), 241.0ms
Speed: 1.7ms preprocess, 241.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 52%|██████████████████████████████████████████████████████████████████████▏                                                                 | 94/182 [08:43<07:01,  4.79s/it]

0: 384x640 (no detections), 243.5ms
1: 384x640 (no detections), 243.5ms
2: 384x640 (no detections), 243.5ms
3: 384x640 (no detections), 243.5ms
4: 384x640 (no detections), 243.5ms
5: 384x640 (no detections), 243.5ms
6: 384x640 1 animal, 243.5ms
7: 384x640 1 animal, 243.5ms
8: 384x640 1 animal, 243.5ms
9: 384x640 1 animal, 243.5ms
10: 384x640 1 animal, 243.5ms
11: 384x640 (no detections), 243.5ms
12: 384x640 (no detections), 243.5ms
13: 384x640 (no detections), 243.5ms
14: 384x640 (no detections), 243.5ms
15: 384x640 (no detections), 243.5ms
Speed: 2.0ms preprocess, 243.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 52%|██████████████████████████████████████████████████████████████████████▉                                                                 | 95/182 [08:48<06:53,  4.75s/it]

0: 384x640 1 animal, 244.2ms
1: 384x640 1 animal, 244.2ms
2: 384x640 1 animal, 244.2ms
3: 384x640 (no detections), 244.2ms
4: 384x640 (no detections), 244.2ms
5: 384x640 (no detections), 244.2ms
6: 384x640 (no detections), 244.2ms
7: 384x640 (no detections), 244.2ms
8: 384x640 (no detections), 244.2ms
9: 384x640 (no detections), 244.2ms
10: 384x640 1 animal, 244.2ms
11: 384x640 1 animal, 244.2ms
12: 384x640 (no detections), 244.2ms
13: 384x640 (no detections), 244.2ms
14: 384x640 (no detections), 244.2ms
15: 384x640 (no detections), 244.2ms
Speed: 1.7ms preprocess, 244.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 53%|███████████████████████████████████████████████████████████████████████▋                                                                | 96/182 [08:52<06:45,  4.72s/it]

0: 384x640 (no detections), 244.6ms
1: 384x640 (no detections), 244.6ms
2: 384x640 (no detections), 244.6ms
3: 384x640 (no detections), 244.6ms
4: 384x640 1 animal, 244.6ms
5: 384x640 1 animal, 244.6ms
6: 384x640 1 animal, 244.6ms
7: 384x640 1 animal, 244.6ms
8: 384x640 1 animal, 244.6ms
9: 384x640 1 animal, 244.6ms
10: 384x640 1 animal, 244.6ms
11: 384x640 1 animal, 244.6ms
12: 384x640 1 animal, 244.6ms
13: 384x640 1 animal, 244.6ms
14: 384x640 1 animal, 244.6ms
15: 384x640 1 animal, 244.6ms
Speed: 1.9ms preprocess, 244.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 53%|████████████████████████████████████████████████████████████████████████▍                                                               | 97/182 [08:57<06:40,  4.71s/it]

0: 640x640 (no detections), 407.9ms
1: 640x640 (no detections), 407.9ms
2: 640x640 1 animal, 407.9ms
3: 640x640 1 animal, 407.9ms
4: 640x640 1 animal, 407.9ms
5: 640x640 1 animal, 407.9ms
6: 640x640 1 animal, 407.9ms
7: 640x640 (no detections), 407.9ms
8: 640x640 1 animal, 407.9ms
9: 640x640 1 animal, 407.9ms
10: 640x640 (no detections), 407.9ms
11: 640x640 (no detections), 407.9ms
12: 640x640 (no detections), 407.9ms
13: 640x640 (no detections), 407.9ms
14: 640x640 (no detections), 407.9ms
15: 640x640 (no detections), 407.9ms
Speed: 2.6ms preprocess, 407.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 54%|█████████████████████████████████████████████████████████████████████████▏                                                              | 98/182 [09:04<07:35,  5.43s/it]

0: 640x640 (no detections), 411.9ms
1: 640x640 (no detections), 411.9ms
2: 640x640 2 animals, 411.9ms
3: 640x640 1 animal, 411.9ms
4: 640x640 1 animal, 411.9ms
5: 640x640 1 animal, 411.9ms
6: 640x640 (no detections), 411.9ms
7: 640x640 (no detections), 411.9ms
8: 640x640 1 animal, 411.9ms
9: 640x640 (no detections), 411.9ms
10: 640x640 1 animal, 411.9ms
11: 640x640 (no detections), 411.9ms
12: 640x640 1 animal, 411.9ms
13: 640x640 2 animals, 411.9ms
14: 640x640 1 animal, 411.9ms
15: 640x640 (no detections), 411.9ms
Speed: 2.5ms preprocess, 411.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 54%|█████████████████████████████████████████████████████████████████████████▉                                                              | 99/182 [09:11<08:17,  6.00s/it]

0: 640x640 (no detections), 409.8ms
1: 640x640 (no detections), 409.8ms
2: 640x640 (no detections), 409.8ms
3: 640x640 (no detections), 409.8ms
4: 640x640 (no detections), 409.8ms
5: 640x640 (no detections), 409.8ms
6: 640x640 1 animal, 409.8ms
7: 640x640 1 animal, 409.8ms
8: 640x640 1 animal, 409.8ms
9: 640x640 1 animal, 409.8ms
10: 640x640 1 animal, 409.8ms
11: 640x640 1 animal, 409.8ms
12: 640x640 1 animal, 409.8ms
13: 640x640 1 animal, 409.8ms
14: 640x640 1 animal, 409.8ms
15: 640x640 1 animal, 409.8ms
Speed: 2.5ms preprocess, 409.8ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 55%|██████████████████████████████████████████████████████████████████████████▏                                                            | 100/182 [09:18<08:40,  6.35s/it]

0: 640x640 1 animal, 407.2ms
1: 640x640 1 animal, 407.2ms
2: 640x640 1 animal, 407.2ms
3: 640x640 1 animal, 407.2ms
4: 640x640 1 animal, 407.2ms
5: 640x640 1 animal, 407.2ms
6: 640x640 1 animal, 407.2ms
7: 640x640 1 animal, 407.2ms
8: 640x640 1 animal, 407.2ms
9: 640x640 1 animal, 407.2ms
10: 640x640 1 animal, 407.2ms
11: 640x640 1 animal, 407.2ms
12: 640x640 (no detections), 407.2ms
13: 640x640 (no detections), 407.2ms
14: 640x640 (no detections), 407.2ms
15: 640x640 (no detections), 407.2ms
Speed: 2.5ms preprocess, 407.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 55%|██████████████████████████████████████████████████████████████████████████▉                                                            | 101/182 [09:26<08:52,  6.58s/it]

0: 640x640 (no detections), 409.7ms
1: 640x640 (no detections), 409.7ms
2: 640x640 (no detections), 409.7ms
3: 640x640 (no detections), 409.7ms
4: 640x640 1 animal, 409.7ms
5: 640x640 1 animal, 409.7ms
6: 640x640 1 animal, 409.7ms
7: 640x640 1 animal, 409.7ms
8: 640x640 1 animal, 409.7ms
9: 640x640 (no detections), 409.7ms
10: 640x640 (no detections), 409.7ms
11: 640x640 (no detections), 409.7ms
12: 640x640 (no detections), 409.7ms
13: 640x640 (no detections), 409.7ms
14: 640x640 1 animal, 409.7ms
15: 640x640 1 animal, 409.7ms
Speed: 2.4ms preprocess, 409.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 56%|███████████████████████████████████████████████████████████████████████████▋                                                           | 102/182 [09:33<08:56,  6.70s/it]

0: 640x640 1 animal, 411.2ms
1: 640x640 2 animals, 411.2ms
2: 640x640 1 animal, 411.2ms
3: 640x640 1 animal, 411.2ms
4: 640x640 1 animal, 411.2ms
5: 640x640 1 animal, 411.2ms
6: 640x640 1 animal, 411.2ms
7: 640x640 1 animal, 411.2ms
8: 640x640 1 animal, 411.2ms
9: 640x640 1 animal, 411.2ms
10: 640x640 1 animal, 411.2ms
11: 640x640 (no detections), 411.2ms
12: 640x640 (no detections), 411.2ms
13: 640x640 (no detections), 411.2ms
14: 640x640 (no detections), 411.2ms
15: 640x640 (no detections), 411.2ms
Speed: 2.4ms preprocess, 411.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 57%|████████████████████████████████████████████████████████████████████████████▍                                                          | 103/182 [09:40<09:00,  6.84s/it]

0: 384x640 (no detections), 241.9ms
1: 384x640 (no detections), 241.9ms
2: 384x640 1 animal, 241.9ms
3: 384x640 1 animal, 241.9ms
4: 384x640 1 animal, 241.9ms
5: 384x640 (no detections), 241.9ms
6: 384x640 (no detections), 241.9ms
7: 384x640 (no detections), 241.9ms
8: 384x640 (no detections), 241.9ms
9: 384x640 (no detections), 241.9ms
10: 384x640 (no detections), 241.9ms
11: 384x640 (no detections), 241.9ms
12: 384x640 1 animal, 241.9ms
13: 384x640 1 animal, 241.9ms
14: 384x640 1 animal, 241.9ms
15: 384x640 (no detections), 241.9ms
Speed: 1.6ms preprocess, 241.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 57%|█████████████████████████████████████████████████████████████████████████████▏                                                         | 104/182 [09:44<07:52,  6.06s/it]

0: 640x640 (no detections), 411.9ms
1: 640x640 (no detections), 411.9ms
2: 640x640 (no detections), 411.9ms
3: 640x640 (no detections), 411.9ms
4: 640x640 (no detections), 411.9ms
5: 640x640 1 animal, 411.9ms
6: 640x640 1 animal, 411.9ms
7: 640x640 1 animal, 411.9ms
8: 640x640 1 animal, 411.9ms
9: 640x640 1 animal, 411.9ms
10: 640x640 1 animal, 411.9ms
11: 640x640 2 animals, 411.9ms
12: 640x640 1 animal, 411.9ms
13: 640x640 1 animal, 411.9ms
14: 640x640 1 animal, 411.9ms
15: 640x640 1 animal, 411.9ms
Speed: 2.7ms preprocess, 411.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 58%|█████████████████████████████████████████████████████████████████████████████▉                                                         | 105/182 [09:51<08:13,  6.41s/it]

0: 384x640 1 animal, 247.4ms
1: 384x640 1 animal, 247.4ms
2: 384x640 1 animal, 247.4ms
3: 384x640 1 animal, 247.4ms
4: 384x640 (no detections), 247.4ms
5: 384x640 (no detections), 247.4ms
6: 384x640 (no detections), 247.4ms
7: 384x640 (no detections), 247.4ms
8: 384x640 (no detections), 247.4ms
9: 384x640 (no detections), 247.4ms
10: 384x640 1 animal, 247.4ms
11: 384x640 1 animal, 247.4ms
12: 384x640 (no detections), 247.4ms
13: 384x640 (no detections), 247.4ms
14: 384x640 (no detections), 247.4ms
15: 384x640 1 animal, 247.4ms
Speed: 2.0ms preprocess, 247.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 58%|██████████████████████████████████████████████████████████████████████████████▋                                                        | 106/182 [09:56<07:29,  5.91s/it]

0: 384x640 (no detections), 244.7ms
1: 384x640 (no detections), 244.7ms
2: 384x640 (no detections), 244.7ms
3: 384x640 (no detections), 244.7ms
4: 384x640 1 animal, 244.7ms
5: 384x640 1 animal, 244.7ms
6: 384x640 1 animal, 244.7ms
7: 384x640 1 animal, 244.7ms
8: 384x640 1 animal, 244.7ms
9: 384x640 1 animal, 244.7ms
10: 384x640 1 animal, 244.7ms
11: 384x640 1 animal, 244.7ms
12: 384x640 1 animal, 244.7ms
13: 384x640 1 animal, 244.7ms
14: 384x640 1 animal, 244.7ms
15: 384x640 1 animal, 244.7ms
Speed: 1.7ms preprocess, 244.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 59%|███████████████████████████████████████████████████████████████████████████████▎                                                       | 107/182 [10:01<06:56,  5.55s/it]

0: 384x640 1 animal, 245.1ms
1: 384x640 (no detections), 245.1ms
2: 384x640 (no detections), 245.1ms
3: 384x640 (no detections), 245.1ms
4: 384x640 (no detections), 245.1ms
5: 384x640 (no detections), 245.1ms
6: 384x640 (no detections), 245.1ms
7: 384x640 (no detections), 245.1ms
8: 384x640 1 animal, 245.1ms
9: 384x640 1 animal, 245.1ms
10: 384x640 2 animals, 245.1ms
11: 384x640 1 animal, 245.1ms
12: 384x640 1 animal, 245.1ms
13: 384x640 1 animal, 245.1ms
14: 384x640 2 animals, 245.1ms
15: 384x640 (no detections), 245.1ms
Speed: 1.7ms preprocess, 245.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 59%|████████████████████████████████████████████████████████████████████████████████                                                       | 108/182 [10:05<06:31,  5.29s/it]

0: 640x640 (no detections), 412.1ms
1: 640x640 (no detections), 412.1ms
2: 640x640 1 animal, 412.1ms
3: 640x640 (no detections), 412.1ms
4: 640x640 (no detections), 412.1ms
5: 640x640 (no detections), 412.1ms
6: 640x640 (no detections), 412.1ms
7: 640x640 (no detections), 412.1ms
8: 640x640 (no detections), 412.1ms
9: 640x640 (no detections), 412.1ms
10: 640x640 (no detections), 412.1ms
11: 640x640 (no detections), 412.1ms
12: 640x640 1 animal, 412.1ms
13: 640x640 1 animal, 412.1ms
14: 640x640 1 animal, 412.1ms
15: 640x640 1 animal, 412.1ms
Speed: 2.5ms preprocess, 412.1ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 60%|████████████████████████████████████████████████████████████████████████████████▊                                                      | 109/182 [10:13<07:09,  5.88s/it]

0: 640x640 (no detections), 412.3ms
1: 640x640 (no detections), 412.3ms
2: 640x640 (no detections), 412.3ms
3: 640x640 (no detections), 412.3ms
4: 640x640 (no detections), 412.3ms
5: 640x640 1 animal, 412.3ms
6: 640x640 1 animal, 412.3ms
7: 640x640 (no detections), 412.3ms
8: 640x640 (no detections), 412.3ms
9: 640x640 (no detections), 412.3ms
10: 640x640 (no detections), 412.3ms
11: 640x640 (no detections), 412.3ms
12: 640x640 (no detections), 412.3ms
13: 640x640 (no detections), 412.3ms
14: 640x640 (no detections), 412.3ms
15: 640x640 (no detections), 412.3ms
Speed: 2.5ms preprocess, 412.3ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 60%|█████████████████████████████████████████████████████████████████████████████████▌                                                     | 110/182 [10:20<07:32,  6.28s/it]

0: 640x640 (no detections), 409.0ms
1: 640x640 (no detections), 409.0ms
2: 640x640 (no detections), 409.0ms
3: 640x640 (no detections), 409.0ms
4: 640x640 (no detections), 409.0ms
5: 640x640 (no detections), 409.0ms
6: 640x640 (no detections), 409.0ms
7: 640x640 (no detections), 409.0ms
8: 640x640 (no detections), 409.0ms
9: 640x640 (no detections), 409.0ms
10: 640x640 (no detections), 409.0ms
11: 640x640 (no detections), 409.0ms
12: 640x640 1 animal, 409.0ms
13: 640x640 1 animal, 409.0ms
14: 640x640 1 animal, 409.0ms
15: 640x640 1 animal, 409.0ms
Speed: 2.4ms preprocess, 409.0ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 61%|██████████████████████████████████████████████████████████████████████████████████▎                                                    | 111/182 [10:27<07:42,  6.51s/it]

0: 640x640 1 animal, 409.1ms
1: 640x640 1 animal, 409.1ms
2: 640x640 1 animal, 409.1ms
3: 640x640 1 animal, 409.1ms
4: 640x640 1 animal, 409.1ms
5: 640x640 1 animal, 409.1ms
6: 640x640 1 animal, 409.1ms
7: 640x640 1 animal, 409.1ms
8: 640x640 1 animal, 409.1ms
9: 640x640 1 animal, 409.1ms
10: 640x640 1 animal, 409.1ms
11: 640x640 1 animal, 409.1ms
12: 640x640 1 animal, 409.1ms
13: 640x640 1 animal, 409.1ms
14: 640x640 1 animal, 409.1ms
15: 640x640 1 animal, 409.1ms
Speed: 2.7ms preprocess, 409.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 62%|███████████████████████████████████████████████████████████████████████████████████                                                    | 112/182 [10:34<07:46,  6.67s/it]

0: 384x640 1 animal, 240.0ms
1: 384x640 1 animal, 240.0ms
2: 384x640 1 animal, 240.0ms
3: 384x640 1 animal, 240.0ms
4: 384x640 1 animal, 240.0ms
5: 384x640 1 animal, 240.0ms
6: 384x640 1 animal, 240.0ms
7: 384x640 1 animal, 240.0ms
8: 384x640 1 animal, 240.0ms
9: 384x640 1 animal, 240.0ms
10: 384x640 1 animal, 240.0ms
11: 384x640 1 animal, 240.0ms
12: 384x640 1 animal, 240.0ms
13: 384x640 1 animal, 240.0ms
14: 384x640 1 animal, 240.0ms
15: 384x640 1 animal, 240.0ms
Speed: 1.8ms preprocess, 240.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 62%|███████████████████████████████████████████████████████████████████████████████████▊                                                   | 113/182 [10:38<06:49,  5.94s/it]

0: 640x640 1 animal, 401.4ms
1: 640x640 1 animal, 401.4ms
2: 640x640 1 animal, 401.4ms
3: 640x640 1 animal, 401.4ms
4: 640x640 1 animal, 401.4ms
5: 640x640 (no detections), 401.4ms
6: 640x640 (no detections), 401.4ms
7: 640x640 (no detections), 401.4ms
8: 640x640 (no detections), 401.4ms
9: 640x640 (no detections), 401.4ms
10: 640x640 (no detections), 401.4ms
11: 640x640 (no detections), 401.4ms
12: 640x640 1 animal, 401.4ms
13: 640x640 3 animals, 401.4ms
14: 640x640 2 animals, 401.4ms
15: 640x640 2 animals, 401.4ms
Speed: 2.4ms preprocess, 401.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 63%|████████████████████████████████████████████████████████████████████████████████████▌                                                  | 114/182 [10:45<07:03,  6.23s/it]

0: 640x640 1 animal, 397.8ms
1: 640x640 1 animal, 397.8ms
2: 640x640 1 animal, 397.8ms
3: 640x640 (no detections), 397.8ms
4: 640x640 (no detections), 397.8ms
5: 640x640 1 animal, 397.8ms
6: 640x640 1 animal, 397.8ms
7: 640x640 1 animal, 397.8ms
8: 640x640 (no detections), 397.8ms
9: 640x640 (no detections), 397.8ms
10: 640x640 (no detections), 397.8ms
11: 640x640 (no detections), 397.8ms
12: 640x640 (no detections), 397.8ms
13: 640x640 (no detections), 397.8ms
14: 640x640 (no detections), 397.8ms
15: 640x640 (no detections), 397.8ms
Speed: 2.4ms preprocess, 397.8ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 63%|█████████████████████████████████████████████████████████████████████████████████████▎                                                 | 115/182 [10:52<07:10,  6.42s/it]

0: 384x640 1 animal, 236.0ms
1: 384x640 1 animal, 236.0ms
2: 384x640 (no detections), 236.0ms
3: 384x640 (no detections), 236.0ms
4: 384x640 (no detections), 236.0ms
5: 384x640 (no detections), 236.0ms
6: 384x640 (no detections), 236.0ms
7: 384x640 (no detections), 236.0ms
8: 384x640 (no detections), 236.0ms
9: 384x640 (no detections), 236.0ms
10: 384x640 1 animal, 236.0ms
11: 384x640 1 animal, 236.0ms
12: 384x640 1 animal, 236.0ms
13: 384x640 1 animal, 236.0ms
14: 384x640 1 animal, 236.0ms
15: 384x640 1 animal, 236.0ms
Speed: 1.7ms preprocess, 236.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 64%|██████████████████████████████████████████████████████████████████████████████████████                                                 | 116/182 [10:56<06:25,  5.85s/it]

0: 640x640 1 animal, 394.0ms
1: 640x640 1 animal, 394.0ms
2: 640x640 1 animal, 394.0ms
3: 640x640 1 animal, 394.0ms
4: 640x640 1 animal, 394.0ms
5: 640x640 1 animal, 394.0ms
6: 640x640 1 animal, 394.0ms
7: 640x640 (no detections), 394.0ms
8: 640x640 (no detections), 394.0ms
9: 640x640 (no detections), 394.0ms
10: 640x640 (no detections), 394.0ms
11: 640x640 (no detections), 394.0ms
12: 640x640 (no detections), 394.0ms
13: 640x640 (no detections), 394.0ms
14: 640x640 1 animal, 394.0ms
15: 640x640 1 animal, 394.0ms
Speed: 2.4ms preprocess, 394.0ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 64%|██████████████████████████████████████████████████████████████████████████████████████▊                                                | 117/182 [11:03<06:39,  6.14s/it]

0: 640x640 1 animal, 399.1ms
1: 640x640 1 animal, 399.1ms
2: 640x640 (no detections), 399.1ms
3: 640x640 (no detections), 399.1ms
4: 640x640 (no detections), 399.1ms
5: 640x640 (no detections), 399.1ms
6: 640x640 (no detections), 399.1ms
7: 640x640 (no detections), 399.1ms
8: 640x640 1 animal, 399.1ms
9: 640x640 1 animal, 399.1ms
10: 640x640 (no detections), 399.1ms
11: 640x640 1 animal, 399.1ms
12: 640x640 (no detections), 399.1ms
13: 640x640 1 animal, 399.1ms
14: 640x640 (no detections), 399.1ms
15: 640x640 (no detections), 399.1ms
Speed: 2.6ms preprocess, 399.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 65%|███████████████████████████████████████████████████████████████████████████████████████▌                                               | 118/182 [11:10<06:48,  6.39s/it]

0: 384x640 (no detections), 237.3ms
1: 384x640 (no detections), 237.3ms
2: 384x640 1 animal, 237.3ms
3: 384x640 1 animal, 237.3ms
4: 384x640 1 animal, 237.3ms
5: 384x640 1 animal, 237.3ms
6: 384x640 (no detections), 237.3ms
7: 384x640 (no detections), 237.3ms
8: 384x640 (no detections), 237.3ms
9: 384x640 (no detections), 237.3ms
10: 384x640 (no detections), 237.3ms
11: 384x640 (no detections), 237.3ms
12: 384x640 (no detections), 237.3ms
13: 384x640 1 animal, 237.3ms
14: 384x640 2 animals, 237.3ms
15: 384x640 (no detections), 237.3ms
Speed: 1.7ms preprocess, 237.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 65%|████████████████████████████████████████████████████████████████████████████████████████▎                                              | 119/182 [11:15<06:07,  5.83s/it]

0: 384x640 (no detections), 245.3ms
1: 384x640 (no detections), 245.3ms
2: 384x640 (no detections), 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 (no detections), 245.3ms
5: 384x640 (no detections), 245.3ms
6: 384x640 1 animal, 245.3ms
7: 384x640 1 animal, 245.3ms
8: 384x640 1 animal, 245.3ms
9: 384x640 1 animal, 245.3ms
10: 384x640 1 animal, 245.3ms
11: 384x640 1 animal, 245.3ms
12: 384x640 (no detections), 245.3ms
13: 384x640 (no detections), 245.3ms
14: 384x640 (no detections), 245.3ms
15: 384x640 (no detections), 245.3ms
Speed: 1.7ms preprocess, 245.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 66%|█████████████████████████████████████████████████████████████████████████████████████████                                              | 120/182 [11:20<05:41,  5.51s/it]

0: 640x640 1 animal, 412.4ms
1: 640x640 1 animal, 412.4ms
2: 640x640 1 animal, 412.4ms
3: 640x640 1 animal, 412.4ms
4: 640x640 (no detections), 412.4ms
5: 640x640 (no detections), 412.4ms
6: 640x640 (no detections), 412.4ms
7: 640x640 (no detections), 412.4ms
8: 640x640 (no detections), 412.4ms
9: 640x640 (no detections), 412.4ms
10: 640x640 1 animal, 412.4ms
11: 640x640 1 animal, 412.4ms
12: 640x640 1 animal, 412.4ms
13: 640x640 1 animal, 412.4ms
14: 640x640 1 animal, 412.4ms
15: 640x640 2 animals, 412.4ms
Speed: 2.5ms preprocess, 412.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 66%|█████████████████████████████████████████████████████████████████████████████████████████▊                                             | 121/182 [11:27<06:08,  6.03s/it]

0: 640x640 1 animal, 413.1ms
1: 640x640 3 animals, 413.1ms
2: 640x640 1 animal, 413.1ms
3: 640x640 1 animal, 413.1ms
4: 640x640 1 animal, 413.1ms
5: 640x640 2 animals, 413.1ms
6: 640x640 1 animal, 413.1ms
7: 640x640 1 animal, 413.1ms
8: 640x640 1 animal, 413.1ms
9: 640x640 1 animal, 413.1ms
10: 640x640 1 animal, 413.1ms
11: 640x640 1 animal, 413.1ms
12: 640x640 1 animal, 413.1ms
13: 640x640 1 animal, 413.1ms
14: 640x640 1 animal, 413.1ms
15: 640x640 1 animal, 413.1ms
Speed: 2.7ms preprocess, 413.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 67%|██████████████████████████████████████████████████████████████████████████████████████████▍                                            | 122/182 [11:34<06:23,  6.39s/it]

0: 640x640 1 animal, 415.1ms
1: 640x640 1 animal, 415.1ms
2: 640x640 1 animal, 415.1ms
3: 640x640 1 animal, 415.1ms
4: 640x640 1 animal, 415.1ms
5: 640x640 1 animal, 415.1ms
6: 640x640 (no detections), 415.1ms
7: 640x640 (no detections), 415.1ms
8: 640x640 1 animal, 415.1ms
9: 640x640 1 animal, 415.1ms
10: 640x640 2 animals, 415.1ms
11: 640x640 1 animal, 415.1ms
12: 640x640 1 animal, 415.1ms
13: 640x640 1 animal, 415.1ms
14: 640x640 1 animal, 415.1ms
15: 640x640 1 animal, 415.1ms
Speed: 2.8ms preprocess, 415.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 68%|███████████████████████████████████████████████████████████████████████████████████████████▏                                           | 123/182 [11:41<06:31,  6.63s/it]

0: 384x640 1 animal, 247.7ms
1: 384x640 1 animal, 247.7ms
2: 384x640 1 animal, 247.7ms
3: 384x640 1 animal, 247.7ms
4: 384x640 1 animal, 247.7ms
5: 384x640 1 animal, 247.7ms
6: 384x640 1 animal, 247.7ms
7: 384x640 1 animal, 247.7ms
8: 384x640 1 animal, 247.7ms
9: 384x640 1 animal, 247.7ms
10: 384x640 1 animal, 247.7ms
11: 384x640 1 animal, 247.7ms
12: 384x640 1 animal, 247.7ms
13: 384x640 1 animal, 247.7ms
14: 384x640 1 animal, 247.7ms
15: 384x640 1 animal, 247.7ms
Speed: 1.9ms preprocess, 247.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 68%|███████████████████████████████████████████████████████████████████████████████████████████▉                                           | 124/182 [11:46<05:50,  6.05s/it]

0: 384x640 (no detections), 246.6ms
1: 384x640 (no detections), 246.6ms
2: 384x640 (no detections), 246.6ms
3: 384x640 1 animal, 246.6ms
4: 384x640 1 animal, 246.6ms
5: 384x640 1 animal, 246.6ms
6: 384x640 1 animal, 246.6ms
7: 384x640 1 animal, 246.6ms
8: 384x640 1 animal, 246.6ms
9: 384x640 1 animal, 246.6ms
10: 384x640 1 animal, 246.6ms
11: 384x640 1 animal, 246.6ms
12: 384x640 1 animal, 246.6ms
13: 384x640 (no detections), 246.6ms
14: 384x640 (no detections), 246.6ms
15: 384x640 (no detections), 246.6ms
Speed: 1.7ms preprocess, 246.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 69%|████████████████████████████████████████████████████████████████████████████████████████████▋                                          | 125/182 [11:51<05:21,  5.64s/it]

0: 384x640 1 animal, 242.7ms
1: 384x640 2 animals, 242.7ms
2: 384x640 1 animal, 242.7ms
3: 384x640 1 animal, 242.7ms
4: 384x640 (no detections), 242.7ms
5: 384x640 (no detections), 242.7ms
6: 384x640 (no detections), 242.7ms
7: 384x640 (no detections), 242.7ms
8: 384x640 (no detections), 242.7ms
9: 384x640 (no detections), 242.7ms
10: 384x640 1 animal, 242.7ms
11: 384x640 1 animal, 242.7ms
12: 384x640 1 animal, 242.7ms
13: 384x640 1 animal, 242.7ms
14: 384x640 1 animal, 242.7ms
15: 384x640 2 animals, 242.7ms
Speed: 1.7ms preprocess, 242.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 69%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 126/182 [11:55<04:52,  5.22s/it]

0: 640x640 1 animal, 416.0ms
1: 640x640 1 animal, 416.0ms
2: 640x640 (no detections), 416.0ms
3: 640x640 (no detections), 416.0ms
4: 640x640 1 animal, 416.0ms
5: 640x640 1 animal, 416.0ms
6: 640x640 1 animal, 416.0ms
7: 640x640 1 animal, 416.0ms
8: 640x640 1 animal, 416.0ms
9: 640x640 1 animal, 416.0ms
10: 640x640 1 animal, 416.0ms
11: 640x640 (no detections), 416.0ms
12: 640x640 (no detections), 416.0ms
13: 640x640 (no detections), 416.0ms
14: 640x640 1 animal, 416.0ms
15: 640x640 1 animal, 416.0ms
Speed: 2.6ms preprocess, 416.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 70%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 127/182 [12:02<05:22,  5.86s/it]

0: 640x640 1 animal, 416.0ms
1: 640x640 1 animal, 416.0ms
2: 640x640 1 animal, 416.0ms
3: 640x640 1 animal, 416.0ms
4: 640x640 1 animal, 416.0ms
5: 640x640 (no detections), 416.0ms
6: 640x640 (no detections), 416.0ms
7: 640x640 (no detections), 416.0ms
8: 640x640 1 animal, 416.0ms
9: 640x640 1 animal, 416.0ms
10: 640x640 1 animal, 416.0ms
11: 640x640 1 animal, 416.0ms
12: 640x640 (no detections), 416.0ms
13: 640x640 (no detections), 416.0ms
14: 640x640 1 animal, 416.0ms
15: 640x640 (no detections), 416.0ms
Speed: 2.7ms preprocess, 416.0ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 70%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 128/182 [12:09<05:39,  6.29s/it]

0: 640x640 (no detections), 410.6ms
1: 640x640 (no detections), 410.6ms
2: 640x640 (no detections), 410.6ms
3: 640x640 1 animal, 410.6ms
4: 640x640 1 animal, 410.6ms
5: 640x640 1 animal, 410.6ms
6: 640x640 1 animal, 410.6ms
7: 640x640 1 animal, 410.6ms
8: 640x640 1 animal, 410.6ms
9: 640x640 1 animal, 410.6ms
10: 640x640 1 animal, 410.6ms
11: 640x640 1 animal, 410.6ms
12: 640x640 1 animal, 410.6ms
13: 640x640 1 animal, 410.6ms
14: 640x640 1 animal, 410.6ms
15: 640x640 1 animal, 410.6ms
Speed: 2.8ms preprocess, 410.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 71%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 129/182 [12:17<05:48,  6.58s/it]

0: 384x640 1 animal, 245.1ms
1: 384x640 1 animal, 245.1ms
2: 384x640 1 animal, 245.1ms
3: 384x640 1 animal, 245.1ms
4: 384x640 1 animal, 245.1ms
5: 384x640 1 animal, 245.1ms
6: 384x640 1 animal, 245.1ms
7: 384x640 1 animal, 245.1ms
8: 384x640 2 animals, 245.1ms
9: 384x640 3 animals, 245.1ms
10: 384x640 2 animals, 245.1ms
11: 384x640 2 animals, 245.1ms
12: 384x640 1 animal, 245.1ms
13: 384x640 1 animal, 245.1ms
14: 384x640 1 animal, 245.1ms
15: 384x640 1 animal, 245.1ms
Speed: 1.7ms preprocess, 245.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 71%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 130/182 [12:21<05:12,  6.00s/it]

0: 384x640 1 animal, 246.8ms
1: 384x640 1 animal, 246.8ms
2: 384x640 (no detections), 246.8ms
3: 384x640 (no detections), 246.8ms
4: 384x640 (no detections), 246.8ms
5: 384x640 (no detections), 246.8ms
6: 384x640 (no detections), 246.8ms
7: 384x640 (no detections), 246.8ms
8: 384x640 (no detections), 246.8ms
9: 384x640 (no detections), 246.8ms
10: 384x640 1 animal, 246.8ms
11: 384x640 1 animal, 246.8ms
12: 384x640 1 animal, 246.8ms
13: 384x640 1 animal, 246.8ms
14: 384x640 1 animal, 246.8ms
15: 384x640 1 animal, 246.8ms
Speed: 1.7ms preprocess, 246.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 72%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 131/182 [12:26<04:46,  5.61s/it]

0: 384x640 1 animal, 245.8ms
1: 384x640 (no detections), 245.8ms
2: 384x640 (no detections), 245.8ms
3: 384x640 (no detections), 245.8ms
4: 384x640 1 animal, 245.8ms
5: 384x640 1 animal, 245.8ms
6: 384x640 1 animal, 245.8ms
7: 384x640 (no detections), 245.8ms
8: 384x640 (no detections), 245.8ms
9: 384x640 (no detections), 245.8ms
10: 384x640 (no detections), 245.8ms
11: 384x640 (no detections), 245.8ms
12: 384x640 (no detections), 245.8ms
13: 384x640 (no detections), 245.8ms
14: 384x640 1 animal, 245.8ms
15: 384x640 1 animal, 245.8ms
Speed: 1.7ms preprocess, 245.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 73%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 132/182 [12:31<04:26,  5.32s/it]

0: 384x640 2 animals, 246.3ms
1: 384x640 1 animal, 246.3ms
2: 384x640 (no detections), 246.3ms
3: 384x640 (no detections), 246.3ms
4: 384x640 (no detections), 246.3ms
5: 384x640 (no detections), 246.3ms
6: 384x640 (no detections), 246.3ms
7: 384x640 (no detections), 246.3ms
8: 384x640 1 animal, 246.3ms
9: 384x640 1 animal, 246.3ms
10: 384x640 1 animal, 246.3ms
11: 384x640 1 animal, 246.3ms
12: 384x640 1 animal, 246.3ms
13: 384x640 1 animal, 246.3ms
14: 384x640 1 animal, 246.3ms
15: 384x640 1 animal, 246.3ms
Speed: 1.7ms preprocess, 246.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 73%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 133/182 [12:35<04:11,  5.13s/it]

0: 384x640 1 animal, 248.1ms
1: 384x640 1 animal, 248.1ms
2: 384x640 1 animal, 248.1ms
3: 384x640 1 animal, 248.1ms
4: 384x640 1 animal, 248.1ms
5: 384x640 1 animal, 248.1ms
6: 384x640 1 animal, 248.1ms
7: 384x640 2 animals, 248.1ms
8: 384x640 1 animal, 248.1ms
9: 384x640 1 animal, 248.1ms
10: 384x640 1 animal, 248.1ms
11: 384x640 1 animal, 248.1ms
12: 384x640 1 animal, 248.1ms
13: 384x640 1 animal, 248.1ms
14: 384x640 1 animal, 248.1ms
15: 384x640 1 animal, 248.1ms
Speed: 1.9ms preprocess, 248.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 74%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 134/182 [12:40<04:00,  5.00s/it]

0: 384x640 1 animal, 247.2ms
1: 384x640 1 animal, 247.2ms
2: 384x640 1 animal, 247.2ms
3: 384x640 1 animal, 247.2ms
4: 384x640 (no detections), 247.2ms
5: 384x640 (no detections), 247.2ms
6: 384x640 1 animal, 247.2ms
7: 384x640 1 animal, 247.2ms
8: 384x640 (no detections), 247.2ms
9: 384x640 (no detections), 247.2ms
10: 384x640 (no detections), 247.2ms
11: 384x640 (no detections), 247.2ms
12: 384x640 (no detections), 247.2ms
13: 384x640 (no detections), 247.2ms
14: 384x640 (no detections), 247.2ms
15: 384x640 (no detections), 247.2ms
Speed: 2.1ms preprocess, 247.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 74%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 135/182 [12:45<03:50,  4.91s/it]

0: 384x640 1 animal, 246.8ms
1: 384x640 1 animal, 246.8ms
2: 384x640 1 animal, 246.8ms
3: 384x640 (no detections), 246.8ms
4: 384x640 1 animal, 246.8ms
5: 384x640 (no detections), 246.8ms
6: 384x640 (no detections), 246.8ms
7: 384x640 (no detections), 246.8ms
8: 384x640 (no detections), 246.8ms
9: 384x640 (no detections), 246.8ms
10: 384x640 1 animal, 246.8ms
11: 384x640 1 animal, 246.8ms
12: 384x640 1 animal, 246.8ms
13: 384x640 1 animal, 246.8ms
14: 384x640 1 animal, 246.8ms
15: 384x640 1 animal, 246.8ms
Speed: 1.7ms preprocess, 246.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 136/182 [12:49<03:42,  4.84s/it]

0: 384x640 (no detections), 245.4ms
1: 384x640 (no detections), 245.4ms
2: 384x640 (no detections), 245.4ms
3: 384x640 (no detections), 245.4ms
4: 384x640 1 animal, 245.4ms
5: 384x640 1 animal, 245.4ms
6: 384x640 1 animal, 245.4ms
7: 384x640 1 animal, 245.4ms
8: 384x640 (no detections), 245.4ms
9: 384x640 (no detections), 245.4ms
10: 384x640 1 animal, 245.4ms
11: 384x640 (no detections), 245.4ms
12: 384x640 1 animal, 245.4ms
13: 384x640 (no detections), 245.4ms
14: 384x640 1 animal, 245.4ms
15: 384x640 (no detections), 245.4ms
Speed: 1.7ms preprocess, 245.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 75%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 137/182 [12:54<03:34,  4.78s/it]

0: 384x640 1 animal, 245.4ms
1: 384x640 1 animal, 245.4ms
2: 384x640 1 animal, 245.4ms
3: 384x640 1 animal, 245.4ms
4: 384x640 1 animal, 245.4ms
5: 384x640 (no detections), 245.4ms
6: 384x640 (no detections), 245.4ms
7: 384x640 1 animal, 245.4ms
8: 384x640 1 animal, 245.4ms
9: 384x640 1 animal, 245.4ms
10: 384x640 (no detections), 245.4ms
11: 384x640 (no detections), 245.4ms
12: 384x640 (no detections), 245.4ms
13: 384x640 (no detections), 245.4ms
14: 384x640 (no detections), 245.4ms
15: 384x640 (no detections), 245.4ms
Speed: 1.7ms preprocess, 245.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 138/182 [12:59<03:28,  4.74s/it]

0: 384x640 (no detections), 249.2ms
1: 384x640 (no detections), 249.2ms
2: 384x640 1 animal, 249.2ms
3: 384x640 1 animal, 249.2ms
4: 384x640 1 animal, 249.2ms
5: 384x640 1 animal, 249.2ms
6: 384x640 1 animal, 249.2ms
7: 384x640 1 animal, 249.2ms
8: 384x640 1 animal, 249.2ms
9: 384x640 1 animal, 249.2ms
10: 384x640 1 animal, 249.2ms
11: 384x640 1 animal, 249.2ms
12: 384x640 1 animal, 249.2ms
13: 384x640 1 animal, 249.2ms
14: 384x640 1 animal, 249.2ms
15: 384x640 (no detections), 249.2ms
Speed: 1.7ms preprocess, 249.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                | 139/182 [13:03<03:23,  4.74s/it]

0: 384x640 (no detections), 247.2ms
1: 384x640 1 animal, 247.2ms
2: 384x640 1 animal, 247.2ms
3: 384x640 (no detections), 247.2ms
4: 384x640 (no detections), 247.2ms
5: 384x640 (no detections), 247.2ms
6: 384x640 1 animal, 247.2ms
7: 384x640 1 animal, 247.2ms
8: 384x640 1 animal, 247.2ms
9: 384x640 1 animal, 247.2ms
10: 384x640 1 animal, 247.2ms
11: 384x640 (no detections), 247.2ms
12: 384x640 (no detections), 247.2ms
13: 384x640 (no detections), 247.2ms
14: 384x640 (no detections), 247.2ms
15: 384x640 (no detections), 247.2ms
Speed: 2.0ms preprocess, 247.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 140/182 [13:08<03:18,  4.73s/it]

0: 384x640 1 animal, 246.8ms
1: 384x640 1 animal, 246.8ms
2: 384x640 1 animal, 246.8ms
3: 384x640 1 animal, 246.8ms
4: 384x640 2 animals, 246.8ms
5: 384x640 (no detections), 246.8ms
6: 384x640 (no detections), 246.8ms
7: 384x640 (no detections), 246.8ms
8: 384x640 (no detections), 246.8ms
9: 384x640 (no detections), 246.8ms
10: 384x640 1 animal, 246.8ms
11: 384x640 1 animal, 246.8ms
12: 384x640 1 animal, 246.8ms
13: 384x640 1 animal, 246.8ms
14: 384x640 1 animal, 246.8ms
15: 384x640 1 animal, 246.8ms
Speed: 1.7ms preprocess, 246.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 141/182 [13:13<03:13,  4.72s/it]

0: 384x640 1 animal, 245.5ms
1: 384x640 1 animal, 245.5ms
2: 384x640 (no detections), 245.5ms
3: 384x640 (no detections), 245.5ms
4: 384x640 1 animal, 245.5ms
5: 384x640 (no detections), 245.5ms
6: 384x640 (no detections), 245.5ms
7: 384x640 (no detections), 245.5ms
8: 384x640 (no detections), 245.5ms
9: 384x640 (no detections), 245.5ms
10: 384x640 (no detections), 245.5ms
11: 384x640 (no detections), 245.5ms
12: 384x640 (no detections), 245.5ms
13: 384x640 (no detections), 245.5ms
14: 384x640 1 animal, 245.5ms
15: 384x640 1 animal, 245.5ms
Speed: 2.0ms preprocess, 245.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 142/182 [13:18<03:08,  4.70s/it]

0: 384x640 1 animal, 236.4ms
1: 384x640 1 animal, 236.4ms
2: 384x640 1 animal, 236.4ms
3: 384x640 1 animal, 236.4ms
4: 384x640 1 animal, 236.4ms
5: 384x640 1 animal, 236.4ms
6: 384x640 1 animal, 236.4ms
7: 384x640 1 animal, 236.4ms
8: 384x640 1 animal, 236.4ms
9: 384x640 1 animal, 236.4ms
10: 384x640 (no detections), 236.4ms
11: 384x640 (no detections), 236.4ms
12: 384x640 (no detections), 236.4ms
13: 384x640 (no detections), 236.4ms
14: 384x640 (no detections), 236.4ms
15: 384x640 (no detections), 236.4ms
Speed: 1.7ms preprocess, 236.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 143/182 [13:22<03:01,  4.65s/it]

0: 384x640 (no detections), 239.3ms
1: 384x640 (no detections), 239.3ms
2: 384x640 1 animal, 239.3ms
3: 384x640 (no detections), 239.3ms
4: 384x640 (no detections), 239.3ms
5: 384x640 (no detections), 239.3ms
6: 384x640 (no detections), 239.3ms
7: 384x640 (no detections), 239.3ms
8: 384x640 (no detections), 239.3ms
9: 384x640 (no detections), 239.3ms
10: 384x640 (no detections), 239.3ms
11: 384x640 (no detections), 239.3ms
12: 384x640 1 animal, 239.3ms
13: 384x640 1 animal, 239.3ms
14: 384x640 1 animal, 239.3ms
15: 384x640 1 animal, 239.3ms
Speed: 1.7ms preprocess, 239.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 144/182 [13:27<02:55,  4.63s/it]

0: 384x640 2 animals, 238.6ms
1: 384x640 (no detections), 238.6ms
2: 384x640 (no detections), 238.6ms
3: 384x640 (no detections), 238.6ms
4: 384x640 (no detections), 238.6ms
5: 384x640 (no detections), 238.6ms
6: 384x640 1 animal, 238.6ms
7: 384x640 1 animal, 238.6ms
8: 384x640 (no detections), 238.6ms
9: 384x640 (no detections), 238.6ms
10: 384x640 (no detections), 238.6ms
11: 384x640 (no detections), 238.6ms
12: 384x640 (no detections), 238.6ms
13: 384x640 (no detections), 238.6ms
14: 384x640 (no detections), 238.6ms
15: 384x640 1 animal, 238.6ms
Speed: 1.7ms preprocess, 238.6ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 145/182 [13:31<02:50,  4.60s/it]

0: 384x640 1 animal, 239.5ms
1: 384x640 1 animal, 239.5ms
2: 384x640 1 animal, 239.5ms
3: 384x640 1 animal, 239.5ms
4: 384x640 1 animal, 239.5ms
5: 384x640 1 animal, 239.5ms
6: 384x640 1 animal, 239.5ms
7: 384x640 1 animal, 239.5ms
8: 384x640 1 animal, 239.5ms
9: 384x640 (no detections), 239.5ms
10: 384x640 1 animal, 239.5ms
11: 384x640 2 animals, 239.5ms
12: 384x640 2 animals, 239.5ms
13: 384x640 (no detections), 239.5ms
14: 384x640 (no detections), 239.5ms
15: 384x640 (no detections), 239.5ms
Speed: 1.7ms preprocess, 239.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 146/182 [13:36<02:45,  4.61s/it]

0: 384x640 1 animal, 238.8ms
1: 384x640 1 animal, 238.8ms
2: 384x640 (no detections), 238.8ms
3: 384x640 (no detections), 238.8ms
4: 384x640 1 animal, 238.8ms
5: 384x640 1 animal, 238.8ms
6: 384x640 1 animal, 238.8ms
7: 384x640 1 animal, 238.8ms
8: 384x640 1 animal, 238.8ms
9: 384x640 1 animal, 238.8ms
10: 384x640 1 animal, 238.8ms
11: 384x640 1 animal, 238.8ms
12: 384x640 1 animal, 238.8ms
13: 384x640 1 animal, 238.8ms
14: 384x640 1 animal, 238.8ms
15: 384x640 1 animal, 238.8ms
Speed: 1.9ms preprocess, 238.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 147/182 [13:40<02:41,  4.60s/it]

0: 384x640 1 animal, 246.0ms
1: 384x640 1 animal, 246.0ms
2: 384x640 1 animal, 246.0ms
3: 384x640 1 animal, 246.0ms
4: 384x640 1 animal, 246.0ms
5: 384x640 1 animal, 246.0ms
6: 384x640 1 animal, 246.0ms
7: 384x640 2 animals, 246.0ms
8: 384x640 1 animal, 246.0ms
9: 384x640 1 animal, 246.0ms
10: 384x640 1 animal, 246.0ms
11: 384x640 2 animals, 246.0ms
12: 384x640 (no detections), 246.0ms
13: 384x640 1 animal, 246.0ms
14: 384x640 (no detections), 246.0ms
15: 384x640 (no detections), 246.0ms
Speed: 1.9ms preprocess, 246.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 148/182 [13:45<02:37,  4.62s/it]

0: 384x640 (no detections), 245.8ms
1: 384x640 (no detections), 245.8ms
2: 384x640 1 animal, 245.8ms
3: 384x640 1 animal, 245.8ms
4: 384x640 1 animal, 245.8ms
5: 384x640 1 animal, 245.8ms
6: 384x640 1 animal, 245.8ms
7: 384x640 1 animal, 245.8ms
8: 384x640 1 animal, 245.8ms
9: 384x640 1 animal, 245.8ms
10: 384x640 1 animal, 245.8ms
11: 384x640 2 animals, 245.8ms
12: 384x640 1 animal, 245.8ms
13: 384x640 1 animal, 245.8ms
14: 384x640 1 animal, 245.8ms
15: 384x640 1 animal, 245.8ms
Speed: 2.0ms preprocess, 245.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 149/182 [13:50<02:32,  4.63s/it]

0: 384x640 1 animal, 241.9ms
1: 384x640 1 animal, 241.9ms
2: 384x640 (no detections), 241.9ms
3: 384x640 (no detections), 241.9ms
4: 384x640 (no detections), 241.9ms
5: 384x640 1 animal, 241.9ms
6: 384x640 1 animal, 241.9ms
7: 384x640 1 animal, 241.9ms
8: 384x640 1 animal, 241.9ms
9: 384x640 1 animal, 241.9ms
10: 384x640 1 animal, 241.9ms
11: 384x640 1 animal, 241.9ms
12: 384x640 1 animal, 241.9ms
13: 384x640 1 animal, 241.9ms
14: 384x640 1 animal, 241.9ms
15: 384x640 1 animal, 241.9ms
Speed: 1.7ms preprocess, 241.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 150/182 [13:54<02:28,  4.63s/it]

0: 384x640 1 animal, 242.2ms
1: 384x640 1 animal, 242.2ms
2: 384x640 (no detections), 242.2ms
3: 384x640 (no detections), 242.2ms
4: 384x640 (no detections), 242.2ms
5: 384x640 (no detections), 242.2ms
6: 384x640 (no detections), 242.2ms
7: 384x640 (no detections), 242.2ms
8: 384x640 (no detections), 242.2ms
9: 384x640 (no detections), 242.2ms
10: 384x640 1 animal, 242.2ms
11: 384x640 (no detections), 242.2ms
12: 384x640 (no detections), 242.2ms
13: 384x640 (no detections), 242.2ms
14: 384x640 (no detections), 242.2ms
15: 384x640 (no detections), 242.2ms
Speed: 1.9ms preprocess, 242.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 151/182 [13:59<02:24,  4.66s/it]

0: 384x640 (no detections), 239.7ms
1: 384x640 (no detections), 239.7ms
2: 384x640 (no detections), 239.7ms
3: 384x640 (no detections), 239.7ms
4: 384x640 1 animal, 239.7ms
5: 384x640 1 animal, 239.7ms
6: 384x640 1 animal, 239.7ms
7: 384x640 (no detections), 239.7ms
8: 384x640 (no detections), 239.7ms
9: 384x640 (no detections), 239.7ms
10: 384x640 (no detections), 239.7ms
11: 384x640 (no detections), 239.7ms
12: 384x640 (no detections), 239.7ms
13: 384x640 (no detections), 239.7ms
14: 384x640 1 animal, 239.7ms
15: 384x640 1 animal, 239.7ms
Speed: 1.7ms preprocess, 239.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 152/182 [14:04<02:18,  4.63s/it]

0: 384x640 1 animal, 238.3ms
1: 384x640 1 animal, 238.3ms
2: 384x640 1 animal, 238.3ms
3: 384x640 1 animal, 238.3ms
4: 384x640 1 animal, 238.3ms
5: 384x640 1 animal, 238.3ms
6: 384x640 (no detections), 238.3ms
7: 384x640 (no detections), 238.3ms
8: 384x640 1 animal, 238.3ms
9: 384x640 1 animal, 238.3ms
10: 384x640 1 animal, 238.3ms
11: 384x640 1 animal, 238.3ms
12: 384x640 2 animals, 238.3ms
13: 384x640 2 animals, 238.3ms
14: 384x640 2 animals, 238.3ms
15: 384x640 2 animals, 238.3ms
Speed: 1.7ms preprocess, 238.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 153/182 [14:08<02:13,  4.61s/it]

0: 384x640 1 animal, 240.1ms
1: 384x640 1 animal, 240.1ms
2: 384x640 1 animal, 240.1ms
3: 384x640 1 animal, 240.1ms
4: 384x640 1 animal, 240.1ms
5: 384x640 1 animal, 240.1ms
6: 384x640 1 animal, 240.1ms
7: 384x640 1 animal, 240.1ms
8: 384x640 1 animal, 240.1ms
9: 384x640 1 animal, 240.1ms
10: 384x640 1 animal, 240.1ms
11: 384x640 1 animal, 240.1ms
12: 384x640 1 animal, 240.1ms
13: 384x640 1 animal, 240.1ms
14: 384x640 1 animal, 240.1ms
15: 384x640 1 animal, 240.1ms
Speed: 1.7ms preprocess, 240.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 154/182 [14:13<02:08,  4.59s/it]

0: 384x640 1 animal, 236.5ms
1: 384x640 (no detections), 236.5ms
2: 384x640 (no detections), 236.5ms
3: 384x640 (no detections), 236.5ms
4: 384x640 (no detections), 236.5ms
5: 384x640 (no detections), 236.5ms
6: 384x640 1 animal, 236.5ms
7: 384x640 1 animal, 236.5ms
8: 384x640 1 animal, 236.5ms
9: 384x640 1 animal, 236.5ms
10: 384x640 1 animal, 236.5ms
11: 384x640 1 animal, 236.5ms
12: 384x640 1 animal, 236.5ms
13: 384x640 (no detections), 236.5ms
14: 384x640 (no detections), 236.5ms
15: 384x640 (no detections), 236.5ms
Speed: 1.7ms preprocess, 236.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 155/182 [14:17<02:03,  4.57s/it]

0: 384x640 1 animal, 239.1ms
1: 384x640 1 animal, 239.1ms
2: 384x640 1 animal, 239.1ms
3: 384x640 1 animal, 239.1ms
4: 384x640 1 animal, 239.1ms
5: 384x640 1 animal, 239.1ms
6: 384x640 1 animal, 239.1ms
7: 384x640 (no detections), 239.1ms
8: 384x640 (no detections), 239.1ms
9: 384x640 (no detections), 239.1ms
10: 384x640 1 animal, 239.1ms
11: 384x640 1 animal, 239.1ms
12: 384x640 (no detections), 239.1ms
13: 384x640 (no detections), 239.1ms
14: 384x640 (no detections), 239.1ms
15: 384x640 (no detections), 239.1ms
Speed: 2.0ms preprocess, 239.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 156/182 [14:22<01:58,  4.57s/it]

0: 384x640 (no detections), 236.3ms
1: 384x640 (no detections), 236.3ms
2: 384x640 (no detections), 236.3ms
3: 384x640 (no detections), 236.3ms
4: 384x640 1 animal, 236.3ms
5: 384x640 1 animal, 236.3ms
6: 384x640 1 animal, 236.3ms
7: 384x640 1 animal, 236.3ms
8: 384x640 1 animal, 236.3ms
9: 384x640 1 animal, 236.3ms
10: 384x640 1 animal, 236.3ms
11: 384x640 1 animal, 236.3ms
12: 384x640 1 animal, 236.3ms
13: 384x640 1 animal, 236.3ms
14: 384x640 1 animal, 236.3ms
15: 384x640 (no detections), 236.3ms
Speed: 1.7ms preprocess, 236.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 157/182 [14:26<01:53,  4.55s/it]

0: 384x640 (no detections), 241.9ms
1: 384x640 (no detections), 241.9ms
2: 384x640 (no detections), 241.9ms
3: 384x640 (no detections), 241.9ms
4: 384x640 (no detections), 241.9ms
5: 384x640 (no detections), 241.9ms
6: 384x640 (no detections), 241.9ms
7: 384x640 (no detections), 241.9ms
8: 384x640 1 animal, 241.9ms
9: 384x640 1 animal, 241.9ms
10: 384x640 1 animal, 241.9ms
11: 384x640 1 animal, 241.9ms
12: 384x640 1 animal, 241.9ms
13: 384x640 1 animal, 241.9ms
14: 384x640 1 animal, 241.9ms
15: 384x640 1 animal, 241.9ms
Speed: 1.7ms preprocess, 241.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 158/182 [14:31<01:49,  4.57s/it]

0: 384x640 1 animal, 239.6ms
1: 384x640 1 animal, 239.6ms
2: 384x640 1 animal, 239.6ms
3: 384x640 (no detections), 239.6ms
4: 384x640 (no detections), 239.6ms
5: 384x640 (no detections), 239.6ms
6: 384x640 (no detections), 239.6ms
7: 384x640 (no detections), 239.6ms
8: 384x640 (no detections), 239.6ms
9: 384x640 (no detections), 239.6ms
10: 384x640 (no detections), 239.6ms
11: 384x640 (no detections), 239.6ms
12: 384x640 1 animal, 239.6ms
13: 384x640 1 animal, 239.6ms
14: 384x640 (no detections), 239.6ms
15: 384x640 (no detections), 239.6ms
Speed: 1.7ms preprocess, 239.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 159/182 [14:36<01:45,  4.57s/it]

0: 384x640 (no detections), 240.7ms
1: 384x640 (no detections), 240.7ms
2: 384x640 (no detections), 240.7ms
3: 384x640 (no detections), 240.7ms
4: 384x640 (no detections), 240.7ms
5: 384x640 (no detections), 240.7ms
6: 384x640 1 animal, 240.7ms
7: 384x640 1 animal, 240.7ms
8: 384x640 1 animal, 240.7ms
9: 384x640 1 animal, 240.7ms
10: 384x640 1 animal, 240.7ms
11: 384x640 (no detections), 240.7ms
12: 384x640 (no detections), 240.7ms
13: 384x640 (no detections), 240.7ms
14: 384x640 (no detections), 240.7ms
15: 384x640 (no detections), 240.7ms
Speed: 1.7ms preprocess, 240.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                | 160/182 [14:40<01:40,  4.56s/it]

0: 384x640 1 animal, 238.8ms
1: 384x640 1 animal, 238.8ms
2: 384x640 (no detections), 238.8ms
3: 384x640 (no detections), 238.8ms
4: 384x640 (no detections), 238.8ms
5: 384x640 (no detections), 238.8ms
6: 384x640 (no detections), 238.8ms
7: 384x640 (no detections), 238.8ms
8: 384x640 (no detections), 238.8ms
9: 384x640 (no detections), 238.8ms
10: 384x640 1 animal, 238.8ms
11: 384x640 1 animal, 238.8ms
12: 384x640 1 animal, 238.8ms
13: 384x640 1 animal, 238.8ms
14: 384x640 1 animal, 238.8ms
15: 384x640 1 animal, 238.8ms
Speed: 1.7ms preprocess, 238.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 161/182 [14:45<01:35,  4.55s/it]

0: 384x640 (no detections), 239.0ms
1: 384x640 (no detections), 239.0ms
2: 384x640 (no detections), 239.0ms
3: 384x640 (no detections), 239.0ms
4: 384x640 1 animal, 239.0ms
5: 384x640 1 animal, 239.0ms
6: 384x640 1 animal, 239.0ms
7: 384x640 1 animal, 239.0ms
8: 384x640 1 animal, 239.0ms
9: 384x640 1 animal, 239.0ms
10: 384x640 1 animal, 239.0ms
11: 384x640 1 animal, 239.0ms
12: 384x640 (no detections), 239.0ms
13: 384x640 (no detections), 239.0ms
14: 384x640 1 animal, 239.0ms
15: 384x640 1 animal, 239.0ms
Speed: 1.8ms preprocess, 239.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 162/182 [14:49<01:30,  4.55s/it]

0: 384x640 (no detections), 239.8ms
1: 384x640 (no detections), 239.8ms
2: 384x640 (no detections), 239.8ms
3: 384x640 (no detections), 239.8ms
4: 384x640 (no detections), 239.8ms
5: 384x640 (no detections), 239.8ms
6: 384x640 (no detections), 239.8ms
7: 384x640 (no detections), 239.8ms
8: 384x640 1 animal, 239.8ms
9: 384x640 (no detections), 239.8ms
10: 384x640 (no detections), 239.8ms
11: 384x640 (no detections), 239.8ms
12: 384x640 (no detections), 239.8ms
13: 384x640 (no detections), 239.8ms
14: 384x640 (no detections), 239.8ms
15: 384x640 (no detections), 239.8ms
Speed: 2.0ms preprocess, 239.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 163/182 [14:54<01:27,  4.61s/it]

0: 384x640 (no detections), 238.5ms
1: 384x640 (no detections), 238.5ms
2: 384x640 1 animal, 238.5ms
3: 384x640 1 animal, 238.5ms
4: 384x640 1 animal, 238.5ms
5: 384x640 1 animal, 238.5ms
6: 384x640 1 animal, 238.5ms
7: 384x640 2 animals, 238.5ms
8: 384x640 (no detections), 238.5ms
9: 384x640 (no detections), 238.5ms
10: 384x640 (no detections), 238.5ms
11: 384x640 (no detections), 238.5ms
12: 384x640 1 animal, 238.5ms
13: 384x640 1 animal, 238.5ms
14: 384x640 1 animal, 238.5ms
15: 384x640 1 animal, 238.5ms
Speed: 1.9ms preprocess, 238.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 164/182 [14:58<01:22,  4.60s/it]

0: 384x640 1 animal, 239.2ms
1: 384x640 1 animal, 239.2ms
2: 384x640 1 animal, 239.2ms
3: 384x640 (no detections), 239.2ms
4: 384x640 (no detections), 239.2ms
5: 384x640 (no detections), 239.2ms
6: 384x640 1 animal, 239.2ms
7: 384x640 1 animal, 239.2ms
8: 384x640 1 animal, 239.2ms
9: 384x640 1 animal, 239.2ms
10: 384x640 1 animal, 239.2ms
11: 384x640 1 animal, 239.2ms
12: 384x640 1 animal, 239.2ms
13: 384x640 (no detections), 239.2ms
14: 384x640 (no detections), 239.2ms
15: 384x640 (no detections), 239.2ms
Speed: 1.7ms preprocess, 239.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 165/182 [15:03<01:17,  4.59s/it]

0: 384x640 1 animal, 238.0ms
1: 384x640 1 animal, 238.0ms
2: 384x640 1 animal, 238.0ms
3: 384x640 1 animal, 238.0ms
4: 384x640 (no detections), 238.0ms
5: 384x640 (no detections), 238.0ms
6: 384x640 (no detections), 238.0ms
7: 384x640 (no detections), 238.0ms
8: 384x640 (no detections), 238.0ms
9: 384x640 (no detections), 238.0ms
10: 384x640 1 animal, 238.0ms
11: 384x640 1 animal, 238.0ms
12: 384x640 1 animal, 238.0ms
13: 384x640 1 animal, 238.0ms
14: 384x640 1 animal, 238.0ms
15: 384x640 1 animal, 238.0ms
Speed: 1.7ms preprocess, 238.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 166/182 [15:08<01:13,  4.58s/it]

0: 384x640 1 animal, 236.0ms
1: 384x640 1 animal, 236.0ms
2: 384x640 1 animal, 236.0ms
3: 384x640 (no detections), 236.0ms
4: 384x640 1 animal, 236.0ms
5: 384x640 1 animal, 236.0ms
6: 384x640 1 animal, 236.0ms
7: 384x640 1 animal, 236.0ms
8: 384x640 (no detections), 236.0ms
9: 384x640 (no detections), 236.0ms
10: 384x640 (no detections), 236.0ms
11: 384x640 (no detections), 236.0ms
12: 384x640 (no detections), 236.0ms
13: 384x640 (no detections), 236.0ms
14: 384x640 1 animal, 236.0ms
15: 384x640 1 animal, 236.0ms
Speed: 1.7ms preprocess, 236.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 167/182 [15:12<01:08,  4.55s/it]

0: 384x640 1 animal, 238.4ms
1: 384x640 (no detections), 238.4ms
2: 384x640 (no detections), 238.4ms
3: 384x640 (no detections), 238.4ms
4: 384x640 (no detections), 238.4ms
5: 384x640 (no detections), 238.4ms
6: 384x640 (no detections), 238.4ms
7: 384x640 (no detections), 238.4ms
8: 384x640 1 animal, 238.4ms
9: 384x640 1 animal, 238.4ms
10: 384x640 1 animal, 238.4ms
11: 384x640 1 animal, 238.4ms
12: 384x640 1 animal, 238.4ms
13: 384x640 1 animal, 238.4ms
14: 384x640 1 animal, 238.4ms
15: 384x640 1 animal, 238.4ms
Speed: 1.7ms preprocess, 238.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 168/182 [15:17<01:03,  4.55s/it]

0: 384x640 1 animal, 241.6ms
1: 384x640 1 animal, 241.6ms
2: 384x640 1 animal, 241.6ms
3: 384x640 1 animal, 241.6ms
4: 384x640 1 animal, 241.6ms
5: 384x640 1 animal, 241.6ms
6: 384x640 1 animal, 241.6ms
7: 384x640 1 animal, 241.6ms
8: 384x640 (no detections), 241.6ms
9: 384x640 (no detections), 241.6ms
10: 384x640 (no detections), 241.6ms
11: 384x640 (no detections), 241.6ms
12: 384x640 1 animal, 241.6ms
13: 384x640 1 animal, 241.6ms
14: 384x640 1 animal, 241.6ms
15: 384x640 (no detections), 241.6ms
Speed: 1.9ms preprocess, 241.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 169/182 [15:21<00:59,  4.56s/it]

0: 384x640 (no detections), 235.4ms
1: 384x640 (no detections), 235.4ms
2: 384x640 (no detections), 235.4ms
3: 384x640 (no detections), 235.4ms
4: 384x640 (no detections), 235.4ms
5: 384x640 (no detections), 235.4ms
6: 384x640 1 animal, 235.4ms
7: 384x640 1 animal, 235.4ms
8: 384x640 1 animal, 235.4ms
9: 384x640 (no detections), 235.4ms
10: 384x640 (no detections), 235.4ms
11: 384x640 (no detections), 235.4ms
12: 384x640 (no detections), 235.4ms
13: 384x640 (no detections), 235.4ms
14: 384x640 (no detections), 235.4ms
15: 384x640 (no detections), 235.4ms
Speed: 2.0ms preprocess, 235.4ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 170/182 [15:26<00:54,  4.53s/it]

0: 384x640 1 animal, 237.8ms
1: 384x640 1 animal, 237.8ms
2: 384x640 1 animal, 237.8ms
3: 384x640 1 animal, 237.8ms
4: 384x640 1 animal, 237.8ms
5: 384x640 1 animal, 237.8ms
6: 384x640 (no detections), 237.8ms
7: 384x640 (no detections), 237.8ms
8: 384x640 (no detections), 237.8ms
9: 384x640 (no detections), 237.8ms
10: 384x640 1 animal, 237.8ms
11: 384x640 1 animal, 237.8ms
12: 384x640 1 animal, 237.8ms
13: 384x640 1 animal, 237.8ms
14: 384x640 2 animals, 237.8ms
15: 384x640 1 animal, 237.8ms
Speed: 1.7ms preprocess, 237.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 171/182 [15:30<00:49,  4.53s/it]

0: 384x640 1 animal, 238.5ms
1: 384x640 (no detections), 238.5ms
2: 384x640 (no detections), 238.5ms
3: 384x640 (no detections), 238.5ms
4: 384x640 1 animal, 238.5ms
5: 384x640 1 animal, 238.5ms
6: 384x640 1 animal, 238.5ms
7: 384x640 1 animal, 238.5ms
8: 384x640 1 animal, 238.5ms
9: 384x640 1 animal, 238.5ms
10: 384x640 1 animal, 238.5ms
11: 384x640 1 animal, 238.5ms
12: 384x640 (no detections), 238.5ms
13: 384x640 (no detections), 238.5ms
14: 384x640 1 animal, 238.5ms
15: 384x640 1 animal, 238.5ms
Speed: 1.7ms preprocess, 238.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 172/182 [15:35<00:45,  4.54s/it]

0: 384x640 1 animal, 240.7ms
1: 384x640 (no detections), 240.7ms
2: 384x640 (no detections), 240.7ms
3: 384x640 1 animal, 240.7ms
4: 384x640 (no detections), 240.7ms
5: 384x640 (no detections), 240.7ms
6: 384x640 (no detections), 240.7ms
7: 384x640 1 animal, 240.7ms
8: 384x640 1 animal, 240.7ms
9: 384x640 1 animal, 240.7ms
10: 384x640 1 animal, 240.7ms
11: 384x640 2 animals, 240.7ms
12: 384x640 2 animals, 240.7ms
13: 384x640 2 animals, 240.7ms
14: 384x640 1 animal, 240.7ms
15: 384x640 1 animal, 240.7ms
Speed: 1.7ms preprocess, 240.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 173/182 [15:39<00:41,  4.58s/it]

0: 384x640 1 animal, 239.0ms
1: 384x640 (no detections), 239.0ms
2: 384x640 1 animal, 239.0ms
3: 384x640 1 animal, 239.0ms
4: 384x640 1 animal, 239.0ms
5: 384x640 1 animal, 239.0ms
6: 384x640 1 animal, 239.0ms
7: 384x640 1 animal, 239.0ms
8: 384x640 1 animal, 239.0ms
9: 384x640 1 animal, 239.0ms
10: 384x640 1 animal, 239.0ms
11: 384x640 1 animal, 239.0ms
12: 384x640 1 animal, 239.0ms
13: 384x640 1 animal, 239.0ms
14: 384x640 (no detections), 239.0ms
15: 384x640 (no detections), 239.0ms
Speed: 1.7ms preprocess, 239.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 174/182 [15:44<00:36,  4.59s/it]

0: 384x640 (no detections), 236.6ms
1: 384x640 (no detections), 236.6ms
2: 384x640 (no detections), 236.6ms
3: 384x640 (no detections), 236.6ms
4: 384x640 (no detections), 236.6ms
5: 384x640 (no detections), 236.6ms
6: 384x640 1 animal, 236.6ms
7: 384x640 1 animal, 236.6ms
8: 384x640 1 animal, 236.6ms
9: 384x640 1 animal, 236.6ms
10: 384x640 1 animal, 236.6ms
11: 384x640 2 animals, 236.6ms
12: 384x640 1 animal, 236.6ms
13: 384x640 1 animal, 236.6ms
14: 384x640 1 animal, 236.6ms
15: 384x640 (no detections), 236.6ms
Speed: 1.7ms preprocess, 236.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 175/182 [15:49<00:32,  4.57s/it]

0: 384x640 1 animal, 246.0ms
1: 384x640 1 animal, 246.0ms
2: 384x640 1 animal, 246.0ms
3: 384x640 1 animal, 246.0ms
4: 384x640 1 animal, 246.0ms
5: 384x640 1 animal, 246.0ms
6: 384x640 (no detections), 246.0ms
7: 384x640 (no detections), 246.0ms
8: 384x640 (no detections), 246.0ms
9: 384x640 (no detections), 246.0ms
10: 384x640 1 animal, 246.0ms
11: 384x640 1 animal, 246.0ms
12: 384x640 2 animals, 246.0ms
13: 384x640 (no detections), 246.0ms
14: 384x640 (no detections), 246.0ms
15: 384x640 (no detections), 246.0ms
Speed: 1.9ms preprocess, 246.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 176/182 [15:53<00:27,  4.62s/it]

0: 384x640 (no detections), 245.7ms
1: 384x640 (no detections), 245.7ms
2: 384x640 (no detections), 245.7ms
3: 384x640 (no detections), 245.7ms
4: 384x640 1 animal, 245.7ms
5: 384x640 1 animal, 245.7ms
6: 384x640 1 animal, 245.7ms
7: 384x640 1 animal, 245.7ms
8: 384x640 (no detections), 245.7ms
9: 384x640 (no detections), 245.7ms
10: 384x640 (no detections), 245.7ms
11: 384x640 (no detections), 245.7ms
12: 384x640 (no detections), 245.7ms
13: 384x640 (no detections), 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 1 animal, 245.7ms
Speed: 2.0ms preprocess, 245.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 177/182 [15:58<00:23,  4.64s/it]

0: 384x640 (no detections), 245.3ms
1: 384x640 (no detections), 245.3ms
2: 384x640 (no detections), 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 (no detections), 245.3ms
5: 384x640 (no detections), 245.3ms
6: 384x640 (no detections), 245.3ms
7: 384x640 (no detections), 245.3ms
8: 384x640 1 animal, 245.3ms
9: 384x640 1 animal, 245.3ms
10: 384x640 (no detections), 245.3ms
11: 384x640 (no detections), 245.3ms
12: 384x640 (no detections), 245.3ms
13: 384x640 (no detections), 245.3ms
14: 384x640 (no detections), 245.3ms
15: 384x640 (no detections), 245.3ms
Speed: 1.7ms preprocess, 245.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 178/182 [16:03<00:18,  4.65s/it]

0: 384x640 (no detections), 247.6ms
1: 384x640 (no detections), 247.6ms
2: 384x640 1 animal, 247.6ms
3: 384x640 1 animal, 247.6ms
4: 384x640 (no detections), 247.6ms
5: 384x640 (no detections), 247.6ms
6: 384x640 (no detections), 247.6ms
7: 384x640 (no detections), 247.6ms
8: 384x640 (no detections), 247.6ms
9: 384x640 (no detections), 247.6ms
10: 384x640 (no detections), 247.6ms
11: 384x640 (no detections), 247.6ms
12: 384x640 1 animal, 247.6ms
13: 384x640 1 animal, 247.6ms
14: 384x640 1 animal, 247.6ms
15: 384x640 1 animal, 247.6ms
Speed: 1.7ms preprocess, 247.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 179/182 [16:07<00:14,  4.70s/it]

0: 384x640 1 animal, 242.7ms
1: 384x640 1 animal, 242.7ms
2: 384x640 (no detections), 242.7ms
3: 384x640 (no detections), 242.7ms
4: 384x640 (no detections), 242.7ms
5: 384x640 (no detections), 242.7ms
6: 384x640 1 animal, 242.7ms
7: 384x640 1 animal, 242.7ms
8: 384x640 1 animal, 242.7ms
9: 384x640 1 animal, 242.7ms
10: 384x640 1 animal, 242.7ms
11: 384x640 1 animal, 242.7ms
12: 384x640 (no detections), 242.7ms
13: 384x640 (no detections), 242.7ms
14: 384x640 (no detections), 242.7ms
15: 384x640 (no detections), 242.7ms
Speed: 1.7ms preprocess, 242.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 180/182 [16:12<00:09,  4.68s/it]

0: 640x640 1 animal, 399.7ms
1: 640x640 1 animal, 399.7ms
2: 640x640 2 animals, 399.7ms
3: 640x640 (no detections), 399.7ms
4: 640x640 (no detections), 399.7ms
5: 640x640 (no detections), 399.7ms
6: 640x640 (no detections), 399.7ms
7: 640x640 (no detections), 399.7ms
8: 640x640 (no detections), 399.7ms
9: 640x640 (no detections), 399.7ms
10: 640x640 2 animals, 399.7ms
11: 640x640 2 animals, 399.7ms
12: 640x640 2 animals, 399.7ms
13: 640x640 2 animals, 399.7ms
14: 640x640 2 animals, 399.7ms
15: 640x640 2 animals, 399.7ms
Speed: 2.3ms preprocess, 399.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 181/182 [16:19<00:05,  5.38s/it]

0: 384x640 2 animals, 229.9ms
1: 384x640 2 animals, 229.9ms
2: 384x640 1 animal, 229.9ms
3: 384x640 1 animal, 229.9ms
4: 384x640 2 animals, 229.9ms
5: 384x640 3 animals, 229.9ms
6: 384x640 3 animals, 229.9ms
7: 384x640 4 animals, 229.9ms
8: 384x640 3 animals, 229.9ms
9: 384x640 3 animals, 229.9ms
10: 384x640 3 animals, 229.9ms
11: 384x640 4 animals, 229.9ms
12: 384x640 2 animals, 229.9ms
13: 384x640 3 animals, 229.9ms
Speed: 1.3ms preprocess, 229.9ms inference, 0.4ms postprocess per image at shape (14, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 182/182 [16:23<00:00,  5.40s/it]

Detecting images from PERROS_extracted

  0%|                                                                                                                                                   | 0/2 [00:00<?, ?it/s]

0: 640x640 2 animals, 408.3ms
1: 640x640 1 animal, 408.3ms
2: 640x640 1 animal, 408.3ms
3: 640x640 1 animal, 408.3ms
4: 640x640 1 animal, 408.3ms
5: 640x640 1 animal, 408.3ms
6: 640x640 1 animal, 408.3ms
7: 640x640 1 animal, 408.3ms
8: 640x640 (no detections), 408.3ms
9: 640x640 (no detections), 408.3ms
10: 640x640 1 animal, 408.3ms
11: 640x640 2 animals, 408.3ms
12: 640x640 3 animals, 408.3ms
13: 640x640 1 animal, 408.3ms
14: 640x640 1 animal, 408.3ms
15: 640x640 1 animal, 408.3ms
Speed: 2.5ms preprocess, 408.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 50%|█████████████████████████████████████████████████████████████████████▌                                                                     | 1/2 [00:07<00:07,  7.11s/it]

0: 384x640 1 animal, 203.7ms
1: 384x640 1 animal, 203.7ms
2: 384x640 1 animal, 203.7ms
3: 384x640 1 animal, 203.7ms
Speed: 2.0ms preprocess, 203.7ms inference, 0.5ms postprocess per image at shape (4, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.07s/it]

Detecting images from CONEPATUS_LEUCONOTUS_2022_extracted

  0%|                                                                                                                                                  | 0/25 [00:00<?, ?it/s]

0: 384x640 1 animal, 246.8ms
1: 384x640 2 animals, 246.8ms
2: 384x640 2 animals, 246.8ms
3: 384x640 1 animal, 246.8ms
4: 384x640 1 animal, 246.8ms
5: 384x640 1 animal, 246.8ms
6: 384x640 1 animal, 246.8ms
7: 384x640 (no detections), 246.8ms
8: 384x640 (no detections), 246.8ms
9: 384x640 (no detections), 246.8ms
10: 384x640 1 animal, 246.8ms
11: 384x640 1 animal, 246.8ms
12: 384x640 (no detections), 246.8ms
13: 384x640 (no detections), 246.8ms
14: 384x640 (no detections), 246.8ms
15: 384x640 (no detections), 246.8ms
Speed: 1.7ms preprocess, 246.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  4%|█████▌                                                                                                                                    | 1/25 [00:04<01:52,  4.68s/it]

0: 640x640 (no detections), 409.4ms
1: 640x640 (no detections), 409.4ms
2: 640x640 (no detections), 409.4ms
3: 640x640 (no detections), 409.4ms
4: 640x640 1 animal, 409.4ms
5: 640x640 1 animal, 409.4ms
6: 640x640 2 animals, 409.4ms
7: 640x640 1 animal, 409.4ms
8: 640x640 1 animal, 409.4ms
9: 640x640 1 animal, 409.4ms
10: 640x640 1 animal, 409.4ms
11: 640x640 1 animal, 409.4ms
12: 640x640 2 animals, 409.4ms
13: 640x640 2 animals, 409.4ms
14: 640x640 1 animal, 409.4ms
15: 640x640 1 animal, 409.4ms
Speed: 2.6ms preprocess, 409.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

  8%|███████████                                                                                                                               | 2/25 [00:11<02:20,  6.10s/it]

0: 384x640 1 animal, 245.0ms
1: 384x640 1 animal, 245.0ms
2: 384x640 1 animal, 245.0ms
3: 384x640 (no detections), 245.0ms
4: 384x640 (no detections), 245.0ms
5: 384x640 (no detections), 245.0ms
6: 384x640 (no detections), 245.0ms
7: 384x640 (no detections), 245.0ms
8: 384x640 1 animal, 245.0ms
9: 384x640 1 animal, 245.0ms
10: 384x640 1 animal, 245.0ms
11: 384x640 1 animal, 245.0ms
12: 384x640 1 animal, 245.0ms
13: 384x640 1 animal, 245.0ms
14: 384x640 1 animal, 245.0ms
15: 384x640 2 animals, 245.0ms
Speed: 1.7ms preprocess, 245.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 12%|████████████████▌                                                                                                                         | 3/25 [00:16<01:59,  5.44s/it]

0: 384x640 (no detections), 246.1ms
1: 384x640 (no detections), 246.1ms
2: 384x640 1 animal, 246.1ms
3: 384x640 1 animal, 246.1ms
4: 384x640 1 animal, 246.1ms
5: 384x640 (no detections), 246.1ms
6: 384x640 (no detections), 246.1ms
7: 384x640 (no detections), 246.1ms
8: 384x640 (no detections), 246.1ms
9: 384x640 (no detections), 246.1ms
10: 384x640 (no detections), 246.1ms
11: 384x640 (no detections), 246.1ms
12: 384x640 1 animal, 246.1ms
13: 384x640 1 animal, 246.1ms
14: 384x640 1 animal, 246.1ms
15: 384x640 1 animal, 246.1ms
Speed: 1.7ms preprocess, 246.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 16%|██████████████████████                                                                                                                    | 4/25 [00:21<01:47,  5.12s/it]

0: 640x640 (no detections), 410.6ms
1: 640x640 1 animal, 410.6ms
2: 640x640 1 animal, 410.6ms
3: 640x640 1 animal, 410.6ms
4: 640x640 1 animal, 410.6ms
5: 640x640 (no detections), 410.6ms
6: 640x640 1 animal, 410.6ms
7: 640x640 1 animal, 410.6ms
8: 640x640 1 animal, 410.6ms
9: 640x640 1 animal, 410.6ms
10: 640x640 1 animal, 410.6ms
11: 640x640 1 animal, 410.6ms
12: 640x640 1 animal, 410.6ms
13: 640x640 1 animal, 410.6ms
14: 640x640 1 animal, 410.6ms
15: 640x640 1 animal, 410.6ms
Speed: 2.6ms preprocess, 410.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 20%|███████████████████████████▌                                                                                                              | 5/25 [00:28<01:56,  5.83s/it]

0: 384x640 1 animal, 246.8ms
1: 384x640 1 animal, 246.8ms
2: 384x640 1 animal, 246.8ms
3: 384x640 1 animal, 246.8ms
4: 384x640 1 animal, 246.8ms
5: 384x640 1 animal, 246.8ms
6: 384x640 1 animal, 246.8ms
7: 384x640 1 animal, 246.8ms
8: 384x640 1 animal, 246.8ms
9: 384x640 (no detections), 246.8ms
10: 384x640 1 animal, 246.8ms
11: 384x640 1 animal, 246.8ms
12: 384x640 1 animal, 246.8ms
13: 384x640 1 animal, 246.8ms
14: 384x640 1 animal, 246.8ms
15: 384x640 (no detections), 246.8ms
Speed: 1.7ms preprocess, 246.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 24%|█████████████████████████████████                                                                                                         | 6/25 [00:32<01:43,  5.44s/it]

0: 384x640 (no detections), 245.6ms
1: 384x640 (no detections), 245.6ms
2: 384x640 (no detections), 245.6ms
3: 384x640 (no detections), 245.6ms
4: 384x640 1 animal, 245.6ms
5: 384x640 2 animals, 245.6ms
6: 384x640 1 animal, 245.6ms
7: 384x640 (no detections), 245.6ms
8: 384x640 (no detections), 245.6ms
9: 384x640 (no detections), 245.6ms
10: 384x640 (no detections), 245.6ms
11: 384x640 (no detections), 245.6ms
12: 384x640 (no detections), 245.6ms
13: 384x640 (no detections), 245.6ms
14: 384x640 1 animal, 245.6ms
15: 384x640 1 animal, 245.6ms
Speed: 2.0ms preprocess, 245.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 28%|██████████████████████████████████████▋                                                                                                   | 7/25 [00:37<01:33,  5.18s/it]

0: 640x640 1 animal, 410.2ms
1: 640x640 2 animals, 410.2ms
2: 640x640 1 animal, 410.2ms
3: 640x640 (no detections), 410.2ms
4: 640x640 (no detections), 410.2ms
5: 640x640 1 animal, 410.2ms
6: 640x640 1 animal, 410.2ms
7: 640x640 1 animal, 410.2ms
8: 640x640 1 animal, 410.2ms
9: 640x640 1 animal, 410.2ms
10: 640x640 1 animal, 410.2ms
11: 640x640 1 animal, 410.2ms
12: 640x640 (no detections), 410.2ms
13: 640x640 (no detections), 410.2ms
14: 640x640 (no detections), 410.2ms
15: 640x640 (no detections), 410.2ms
Speed: 2.7ms preprocess, 410.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 32%|████████████████████████████████████████████▏                                                                                             | 8/25 [00:44<01:38,  5.81s/it]

0: 640x640 (no detections), 414.3ms
1: 640x640 (no detections), 414.3ms
2: 640x640 1 animal, 414.3ms
3: 640x640 (no detections), 414.3ms
4: 640x640 (no detections), 414.3ms
5: 640x640 (no detections), 414.3ms
6: 640x640 (no detections), 414.3ms
7: 640x640 (no detections), 414.3ms
8: 640x640 (no detections), 414.3ms
9: 640x640 (no detections), 414.3ms
10: 640x640 (no detections), 414.3ms
11: 640x640 (no detections), 414.3ms
12: 640x640 1 animal, 414.3ms
13: 640x640 2 animals, 414.3ms
14: 640x640 1 animal, 414.3ms
15: 640x640 1 animal, 414.3ms
Speed: 2.5ms preprocess, 414.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 36%|█████████████████████████████████████████████████▋                                                                                        | 9/25 [00:51<01:40,  6.28s/it]

0: 640x640 1 animal, 411.4ms
1: 640x640 1 animal, 411.4ms
2: 640x640 1 animal, 411.4ms
3: 640x640 1 animal, 411.4ms
4: 640x640 1 animal, 411.4ms
5: 640x640 1 animal, 411.4ms
6: 640x640 1 animal, 411.4ms
7: 640x640 1 animal, 411.4ms
8: 640x640 (no detections), 411.4ms
9: 640x640 (no detections), 411.4ms
10: 640x640 (no detections), 411.4ms
11: 640x640 (no detections), 411.4ms
12: 640x640 (no detections), 411.4ms
13: 640x640 (no detections), 411.4ms
14: 640x640 (no detections), 411.4ms
15: 640x640 (no detections), 411.4ms
Speed: 2.6ms preprocess, 411.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 40%|██████████████████████████████████████████████████████▊                                                                                  | 10/25 [00:59<01:38,  6.54s/it]

0: 640x640 1 animal, 414.9ms
1: 640x640 1 animal, 414.9ms
2: 640x640 1 animal, 414.9ms
3: 640x640 1 animal, 414.9ms
4: 640x640 (no detections), 414.9ms
5: 640x640 (no detections), 414.9ms
6: 640x640 (no detections), 414.9ms
7: 640x640 (no detections), 414.9ms
8: 640x640 (no detections), 414.9ms
9: 640x640 (no detections), 414.9ms
10: 640x640 1 animal, 414.9ms
11: 640x640 1 animal, 414.9ms
12: 640x640 1 animal, 414.9ms
13: 640x640 1 animal, 414.9ms
14: 640x640 (no detections), 414.9ms
15: 640x640 (no detections), 414.9ms
Speed: 2.7ms preprocess, 414.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 44%|████████████████████████████████████████████████████████████▎                                                                            | 11/25 [01:06<01:34,  6.74s/it]

0: 640x640 (no detections), 416.1ms
1: 640x640 (no detections), 416.1ms
2: 640x640 (no detections), 416.1ms
3: 640x640 (no detections), 416.1ms
4: 640x640 1 animal, 416.1ms
5: 640x640 1 animal, 416.1ms
6: 640x640 1 animal, 416.1ms
7: 640x640 1 animal, 416.1ms
8: 640x640 1 animal, 416.1ms
9: 640x640 1 animal, 416.1ms
10: 640x640 1 animal, 416.1ms
11: 640x640 1 animal, 416.1ms
12: 640x640 1 animal, 416.1ms
13: 640x640 1 animal, 416.1ms
14: 640x640 1 animal, 416.1ms
15: 640x640 1 animal, 416.1ms
Speed: 2.8ms preprocess, 416.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 48%|█████████████████████████████████████████████████████████████████▊                                                                       | 12/25 [01:13<01:30,  6.93s/it]

0: 640x640 (no detections), 416.1ms
1: 640x640 (no detections), 416.1ms
2: 640x640 (no detections), 416.1ms
3: 640x640 (no detections), 416.1ms
4: 640x640 (no detections), 416.1ms
5: 640x640 (no detections), 416.1ms
6: 640x640 1 animal, 416.1ms
7: 640x640 (no detections), 416.1ms
8: 640x640 1 animal, 416.1ms
9: 640x640 (no detections), 416.1ms
10: 640x640 (no detections), 416.1ms
11: 640x640 (no detections), 416.1ms
12: 640x640 (no detections), 416.1ms
13: 640x640 (no detections), 416.1ms
14: 640x640 (no detections), 416.1ms
15: 640x640 (no detections), 416.1ms
Speed: 2.5ms preprocess, 416.1ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 52%|███████████████████████████████████████████████████████████████████████▏                                                                 | 13/25 [01:20<01:24,  7.02s/it]

0: 640x640 (no detections), 413.2ms
1: 640x640 (no detections), 413.2ms
2: 640x640 2 animals, 413.2ms
3: 640x640 (no detections), 413.2ms
4: 640x640 (no detections), 413.2ms
5: 640x640 (no detections), 413.2ms
6: 640x640 (no detections), 413.2ms
7: 640x640 (no detections), 413.2ms
8: 640x640 (no detections), 413.2ms
9: 640x640 (no detections), 413.2ms
10: 640x640 (no detections), 413.2ms
11: 640x640 (no detections), 413.2ms
12: 640x640 1 animal, 413.2ms
13: 640x640 1 animal, 413.2ms
14: 640x640 1 animal, 413.2ms
15: 640x640 1 animal, 413.2ms
Speed: 2.5ms preprocess, 413.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 56%|████████████████████████████████████████████████████████████████████████████▋                                                            | 14/25 [01:28<01:18,  7.10s/it]

0: 384x640 1 animal, 245.3ms
1: 384x640 1 animal, 245.3ms
2: 384x640 1 animal, 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 (no detections), 245.3ms
5: 384x640 (no detections), 245.3ms
6: 384x640 1 animal, 245.3ms
7: 384x640 (no detections), 245.3ms
8: 384x640 (no detections), 245.3ms
9: 384x640 (no detections), 245.3ms
10: 384x640 (no detections), 245.3ms
11: 384x640 (no detections), 245.3ms
12: 384x640 (no detections), 245.3ms
13: 384x640 (no detections), 245.3ms
14: 384x640 (no detections), 245.3ms
15: 384x640 (no detections), 245.3ms
Speed: 1.6ms preprocess, 245.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 60%|██████████████████████████████████████████████████████████████████████████████████▏                                                      | 15/25 [01:32<01:02,  6.26s/it]

0: 640x640 2 animals, 410.9ms
1: 640x640 2 animals, 410.9ms
2: 640x640 2 animals, 410.9ms
3: 640x640 1 animal, 410.9ms
4: 640x640 1 animal, 410.9ms
5: 640x640 (no detections), 410.9ms
6: 640x640 (no detections), 410.9ms
7: 640x640 (no detections), 410.9ms
8: 640x640 (no detections), 410.9ms
9: 640x640 1 animal, 410.9ms
10: 640x640 1 animal, 410.9ms
11: 640x640 1 animal, 410.9ms
12: 640x640 1 animal, 410.9ms
13: 640x640 (no detections), 410.9ms
14: 640x640 (no detections), 410.9ms
15: 640x640 (no detections), 410.9ms
Speed: 2.5ms preprocess, 410.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 64%|███████████████████████████████████████████████████████████████████████████████████████▋                                                 | 16/25 [01:39<00:58,  6.54s/it]

0: 640x640 (no detections), 416.1ms
1: 640x640 (no detections), 416.1ms
2: 640x640 (no detections), 416.1ms
3: 640x640 (no detections), 416.1ms
4: 640x640 1 animal, 416.1ms
5: 640x640 1 animal, 416.1ms
6: 640x640 1 animal, 416.1ms
7: 640x640 1 animal, 416.1ms
8: 640x640 (no detections), 416.1ms
9: 640x640 (no detections), 416.1ms
10: 640x640 (no detections), 416.1ms
11: 640x640 (no detections), 416.1ms
12: 640x640 (no detections), 416.1ms
13: 640x640 (no detections), 416.1ms
14: 640x640 1 animal, 416.1ms
15: 640x640 (no detections), 416.1ms
Speed: 2.6ms preprocess, 416.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                           | 17/25 [01:46<00:54,  6.77s/it]

0: 640x640 (no detections), 416.1ms
1: 640x640 (no detections), 416.1ms
2: 640x640 (no detections), 416.1ms
3: 640x640 (no detections), 416.1ms
4: 640x640 (no detections), 416.1ms
5: 640x640 (no detections), 416.1ms
6: 640x640 (no detections), 416.1ms
7: 640x640 (no detections), 416.1ms
8: 640x640 1 animal, 416.1ms
9: 640x640 1 animal, 416.1ms
10: 640x640 2 animals, 416.1ms
11: 640x640 1 animal, 416.1ms
12: 640x640 1 animal, 416.1ms
13: 640x640 2 animals, 416.1ms
14: 640x640 1 animal, 416.1ms
15: 640x640 1 animal, 416.1ms
Speed: 2.7ms preprocess, 416.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 18/25 [01:54<00:48,  6.91s/it]

0: 640x640 1 animal, 410.2ms
1: 640x640 1 animal, 410.2ms
2: 640x640 1 animal, 410.2ms
3: 640x640 1 animal, 410.2ms
4: 640x640 1 animal, 410.2ms
5: 640x640 (no detections), 410.2ms
6: 640x640 (no detections), 410.2ms
7: 640x640 (no detections), 410.2ms
8: 640x640 (no detections), 410.2ms
9: 640x640 (no detections), 410.2ms
10: 640x640 (no detections), 410.2ms
11: 640x640 (no detections), 410.2ms
12: 640x640 1 animal, 410.2ms
13: 640x640 1 animal, 410.2ms
14: 640x640 (no detections), 410.2ms
15: 640x640 (no detections), 410.2ms
Speed: 2.6ms preprocess, 410.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 19/25 [02:01<00:41,  6.97s/it]

0: 384x640 (no detections), 248.0ms
1: 384x640 (no detections), 248.0ms
2: 384x640 (no detections), 248.0ms
3: 384x640 (no detections), 248.0ms
4: 384x640 (no detections), 248.0ms
5: 384x640 (no detections), 248.0ms
6: 384x640 1 animal, 248.0ms
7: 384x640 1 animal, 248.0ms
8: 384x640 2 animals, 248.0ms
9: 384x640 (no detections), 248.0ms
10: 384x640 (no detections), 248.0ms
11: 384x640 (no detections), 248.0ms
12: 384x640 (no detections), 248.0ms
13: 384x640 (no detections), 248.0ms
14: 384x640 (no detections), 248.0ms
15: 384x640 (no detections), 248.0ms
Speed: 1.7ms preprocess, 248.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 20/25 [02:05<00:31,  6.29s/it]

0: 384x640 1 animal, 245.3ms
1: 384x640 1 animal, 245.3ms
2: 384x640 1 animal, 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 (no detections), 245.3ms
5: 384x640 (no detections), 245.3ms
6: 384x640 (no detections), 245.3ms
7: 384x640 (no detections), 245.3ms
8: 384x640 (no detections), 245.3ms
9: 384x640 (no detections), 245.3ms
10: 384x640 1 animal, 245.3ms
11: 384x640 1 animal, 245.3ms
12: 384x640 1 animal, 245.3ms
13: 384x640 2 animals, 245.3ms
14: 384x640 2 animals, 245.3ms
15: 384x640 1 animal, 245.3ms
Speed: 1.9ms preprocess, 245.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 21/25 [02:10<00:23,  5.80s/it]

0: 384x640 1 animal, 244.4ms
1: 384x640 2 animals, 244.4ms
2: 384x640 1 animal, 244.4ms
3: 384x640 (no detections), 244.4ms
4: 384x640 1 animal, 244.4ms
5: 384x640 1 animal, 244.4ms
6: 384x640 1 animal, 244.4ms
7: 384x640 1 animal, 244.4ms
8: 384x640 (no detections), 244.4ms
9: 384x640 (no detections), 244.4ms
10: 384x640 (no detections), 244.4ms
11: 384x640 (no detections), 244.4ms
12: 384x640 (no detections), 244.4ms
13: 384x640 (no detections), 244.4ms
14: 384x640 1 animal, 244.4ms
15: 384x640 1 animal, 244.4ms
Speed: 2.0ms preprocess, 244.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 22/25 [02:15<00:16,  5.46s/it]

0: 384x640 (no detections), 245.4ms
1: 384x640 (no detections), 245.4ms
2: 384x640 (no detections), 245.4ms
3: 384x640 (no detections), 245.4ms
4: 384x640 (no detections), 245.4ms
5: 384x640 (no detections), 245.4ms
6: 384x640 (no detections), 245.4ms
7: 384x640 (no detections), 245.4ms
8: 384x640 1 animal, 245.4ms
9: 384x640 1 animal, 245.4ms
10: 384x640 (no detections), 245.4ms
11: 384x640 (no detections), 245.4ms
12: 384x640 (no detections), 245.4ms
13: 384x640 (no detections), 245.4ms
14: 384x640 (no detections), 245.4ms
15: 384x640 (no detections), 245.4ms
Speed: 1.9ms preprocess, 245.4ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 23/25 [02:20<00:10,  5.23s/it]

0: 640x640 (no detections), 411.2ms
1: 640x640 (no detections), 411.2ms
2: 640x640 1 animal, 411.2ms
3: 640x640 1 animal, 411.2ms
4: 640x640 1 animal, 411.2ms
5: 640x640 1 animal, 411.2ms
6: 640x640 1 animal, 411.2ms
7: 640x640 (no detections), 411.2ms
8: 640x640 (no detections), 411.2ms
9: 640x640 (no detections), 411.2ms
10: 640x640 (no detections), 411.2ms
11: 640x640 (no detections), 411.2ms
12: 640x640 2 animals, 411.2ms
13: 640x640 2 animals, 411.2ms
14: 640x640 2 animals, 411.2ms
15: 640x640 2 animals, 411.2ms
Speed: 2.4ms preprocess, 411.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 24/25 [02:27<00:05,  5.84s/it]

0: 384x640 2 animals, 210.0ms
1: 384x640 2 animals, 210.0ms
2: 384x640 2 animals, 210.0ms
3: 384x640 1 animal, 210.0ms
4: 384x640 1 animal, 210.0ms
5: 384x640 1 animal, 210.0ms
Speed: 1.1ms preprocess, 210.0ms inference, 0.5ms postprocess per image at shape (6, 3, 384, 640)

00%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [02:28<00:00,  5.95s/it]

Detecting images from NASUA_NARICA_2022_extracted

  0%|                                                                                                                                                   | 0/3 [00:00<?, ?it/s]

0: 384x640 1 animal, 241.9ms
1: 384x640 1 animal, 241.9ms
2: 384x640 (no detections), 241.9ms
3: 384x640 (no detections), 241.9ms
4: 384x640 (no detections), 241.9ms
5: 384x640 (no detections), 241.9ms
6: 384x640 (no detections), 241.9ms
7: 384x640 (no detections), 241.9ms
8: 384x640 (no detections), 241.9ms
9: 384x640 (no detections), 241.9ms
10: 384x640 (no detections), 241.9ms
11: 384x640 (no detections), 241.9ms
12: 384x640 (no detections), 241.9ms
13: 384x640 (no detections), 241.9ms
14: 384x640 (no detections), 241.9ms
15: 384x640 (no detections), 241.9ms
Speed: 2.1ms preprocess, 241.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 33%|██████████████████████████████████████████████▎                                                                                            | 1/3 [00:04<00:08,  4.32s/it]

0: 384x640 1 animal, 242.8ms
1: 384x640 1 animal, 242.8ms
2: 384x640 (no detections), 242.8ms
3: 384x640 1 animal, 242.8ms
4: 384x640 1 animal, 242.8ms
5: 384x640 2 animals, 242.8ms
6: 384x640 1 animal, 242.8ms
7: 384x640 1 animal, 242.8ms
8: 384x640 1 animal, 242.8ms
9: 384x640 (no detections), 242.8ms
10: 384x640 (no detections), 242.8ms
11: 384x640 (no detections), 242.8ms
12: 384x640 1 animal, 242.8ms
13: 384x640 1 animal, 242.8ms
14: 384x640 2 animals, 242.8ms
15: 384x640 2 animals, 242.8ms
Speed: 1.8ms preprocess, 242.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 67%|████████████████████████████████████████████████████████████████████████████████████████████▋                                              | 2/3 [00:08<00:04,  4.33s/it]

0: 384x640 2 animals, 219.4ms
1: 384x640 1 animal, 219.4ms
2: 384x640 2 animals, 219.4ms
3: 384x640 1 animal, 219.4ms
4: 384x640 2 animals, 219.4ms
5: 384x640 2 animals, 219.4ms
6: 384x640 2 animals, 219.4ms
7: 384x640 2 animals, 219.4ms
Speed: 1.5ms preprocess, 219.4ms inference, 0.5ms postprocess per image at shape (8, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:10<00:00,  3.55s/it]

Detecting images from ROEDORES_extracted

  0%|                                                                                                                                                   | 0/8 [00:00<?, ?it/s]

0: 384x640 (no detections), 244.4ms
1: 384x640 (no detections), 244.4ms
2: 384x640 (no detections), 244.4ms
3: 384x640 (no detections), 244.4ms
4: 384x640 (no detections), 244.4ms
5: 384x640 (no detections), 244.4ms
6: 384x640 (no detections), 244.4ms
7: 384x640 (no detections), 244.4ms
8: 384x640 (no detections), 244.4ms
9: 384x640 (no detections), 244.4ms
10: 384x640 1 animal, 244.4ms
11: 384x640 1 animal, 244.4ms
12: 384x640 1 animal, 244.4ms
13: 384x640 1 animal, 244.4ms
14: 384x640 1 animal, 244.4ms
15: 384x640 2 animals, 244.4ms
Speed: 1.7ms preprocess, 244.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 12%|█████████████████▍                                                                                                                         | 1/8 [00:04<00:32,  4.63s/it]

0: 640x640 1 animal, 411.8ms
1: 640x640 2 animals, 411.8ms
2: 640x640 1 animal, 411.8ms
3: 640x640 1 animal, 411.8ms
4: 640x640 1 animal, 411.8ms
5: 640x640 1 animal, 411.8ms
6: 640x640 1 animal, 411.8ms
7: 640x640 1 animal, 411.8ms
8: 640x640 2 animals, 411.8ms
9: 640x640 3 animals, 411.8ms
10: 640x640 1 animal, 411.8ms
11: 640x640 1 animal, 411.8ms
12: 640x640 2 animals, 411.8ms
13: 640x640 1 animal, 411.8ms
14: 640x640 1 animal, 411.8ms
15: 640x640 2 animals, 411.8ms
Speed: 2.8ms preprocess, 411.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 25%|██████████████████████████████████▊                                                                                                        | 2/8 [00:11<00:37,  6.19s/it]

0: 384x640 1 animal, 241.0ms
1: 384x640 1 animal, 241.0ms
2: 384x640 1 animal, 241.0ms
3: 384x640 1 animal, 241.0ms
4: 384x640 1 animal, 241.0ms
5: 384x640 1 animal, 241.0ms
6: 384x640 1 animal, 241.0ms
7: 384x640 1 animal, 241.0ms
8: 384x640 2 animals, 241.0ms
9: 384x640 1 animal, 241.0ms
10: 384x640 1 animal, 241.0ms
11: 384x640 1 animal, 241.0ms
12: 384x640 1 animal, 241.0ms
13: 384x640 1 animal, 241.0ms
14: 384x640 1 animal, 241.0ms
15: 384x640 1 animal, 241.0ms
Speed: 1.7ms preprocess, 241.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 38%|████████████████████████████████████████████████████▏                                                                                      | 3/8 [00:16<00:26,  5.31s/it]

0: 640x640 1 animal, 412.3ms
1: 640x640 1 animal, 412.3ms
2: 640x640 1 animal, 412.3ms
3: 640x640 (no detections), 412.3ms
4: 640x640 (no detections), 412.3ms
5: 640x640 (no detections), 412.3ms
6: 640x640 (no detections), 412.3ms
7: 640x640 (no detections), 412.3ms
8: 640x640 (no detections), 412.3ms
9: 640x640 (no detections), 412.3ms
10: 640x640 (no detections), 412.3ms
11: 640x640 (no detections), 412.3ms
12: 640x640 1 animal, 412.3ms
13: 640x640 (no detections), 412.3ms
14: 640x640 (no detections), 412.3ms
15: 640x640 (no detections), 412.3ms
Speed: 2.7ms preprocess, 412.3ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 50%|█████████████████████████████████████████████████████████████████████▌                                                                     | 4/8 [00:23<00:24,  6.06s/it]

0: 384x640 1 animal, 240.7ms
1: 384x640 1 animal, 240.7ms
2: 384x640 (no detections), 240.7ms
3: 384x640 (no detections), 240.7ms
4: 384x640 1 animal, 240.7ms
5: 384x640 1 animal, 240.7ms
6: 384x640 1 animal, 240.7ms
7: 384x640 1 animal, 240.7ms
8: 384x640 (no detections), 240.7ms
9: 384x640 1 animal, 240.7ms
10: 384x640 1 animal, 240.7ms
11: 384x640 (no detections), 240.7ms
12: 384x640 (no detections), 240.7ms
13: 384x640 1 animal, 240.7ms
14: 384x640 (no detections), 240.7ms
15: 384x640 (no detections), 240.7ms
Speed: 1.8ms preprocess, 240.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 62%|██████████████████████████████████████████████████████████████████████████████████████▉                                                    | 5/8 [00:27<00:16,  5.40s/it]

0: 384x640 (no detections), 241.0ms
1: 384x640 (no detections), 241.0ms
2: 384x640 (no detections), 241.0ms
3: 384x640 (no detections), 241.0ms
4: 384x640 (no detections), 241.0ms
5: 384x640 (no detections), 241.0ms
6: 384x640 (no detections), 241.0ms
7: 384x640 (no detections), 241.0ms
8: 384x640 (no detections), 241.0ms
9: 384x640 (no detections), 241.0ms
10: 384x640 (no detections), 241.0ms
11: 384x640 (no detections), 241.0ms
12: 384x640 (no detections), 241.0ms
13: 384x640 (no detections), 241.0ms
14: 384x640 (no detections), 241.0ms
15: 384x640 (no detections), 241.0ms
Speed: 1.8ms preprocess, 241.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 6/8 [00:31<00:10,  5.01s/it]

0: 384x640 (no detections), 242.1ms
1: 384x640 (no detections), 242.1ms
2: 384x640 (no detections), 242.1ms
3: 384x640 (no detections), 242.1ms
4: 384x640 2 animals, 242.1ms
5: 384x640 2 animals, 242.1ms
6: 384x640 1 animal, 242.1ms
7: 384x640 1 animal, 242.1ms
8: 384x640 1 animal, 242.1ms
9: 384x640 1 animal, 242.1ms
10: 384x640 1 animal, 242.1ms
11: 384x640 1 animal, 242.1ms
12: 384x640 3 animals, 242.1ms
13: 384x640 1 animal, 242.1ms
14: 384x640 1 animal, 242.1ms
15: 384x640 1 animal, 242.1ms
Speed: 1.7ms preprocess, 242.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 7/8 [00:36<00:04,  4.76s/it]

0: 384x640 1 animal, 218.8ms
1: 384x640 1 animal, 218.8ms
2: 384x640 (no detections), 218.8ms
3: 384x640 (no detections), 218.8ms
4: 384x640 (no detections), 218.8ms
5: 384x640 (no detections), 218.8ms
6: 384x640 (no detections), 218.8ms
7: 384x640 (no detections), 218.8ms
Speed: 1.8ms preprocess, 218.8ms inference, 0.3ms postprocess per image at shape (8, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:38<00:00,  4.76s/it]

Detecting images from SCIURUS_OCOLATUS_extracted

  0%|                                                                                                                                                  | 0/27 [00:00<?, ?it/s]

0: 384x640 1 animal, 247.4ms
1: 384x640 1 animal, 247.4ms
2: 384x640 2 animals, 247.4ms
3: 384x640 1 animal, 247.4ms
4: 384x640 1 animal, 247.4ms
5: 384x640 1 animal, 247.4ms
6: 384x640 (no detections), 247.4ms
7: 384x640 1 animal, 247.4ms
8: 384x640 (no detections), 247.4ms
9: 384x640 (no detections), 247.4ms
10: 384x640 1 animal, 247.4ms
11: 384x640 1 animal, 247.4ms
12: 384x640 1 animal, 247.4ms
13: 384x640 1 animal, 247.4ms
14: 384x640 1 animal, 247.4ms
15: 384x640 1 animal, 247.4ms
Speed: 1.7ms preprocess, 247.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  4%|█████                                                                                                                                     | 1/27 [00:04<02:07,  4.91s/it]

0: 384x640 (no detections), 246.3ms
1: 384x640 (no detections), 246.3ms
2: 384x640 (no detections), 246.3ms
3: 384x640 (no detections), 246.3ms
4: 384x640 1 animal, 246.3ms
5: 384x640 (no detections), 246.3ms
6: 384x640 (no detections), 246.3ms
7: 384x640 1 animal, 246.3ms
8: 384x640 1 animal, 246.3ms
9: 384x640 1 animal, 246.3ms
10: 384x640 1 animal, 246.3ms
11: 384x640 1 animal, 246.3ms
12: 384x640 1 animal, 246.3ms
13: 384x640 1 animal, 246.3ms
14: 384x640 (no detections), 246.3ms
15: 384x640 (no detections), 246.3ms
Speed: 1.7ms preprocess, 246.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  7%|██████████▏                                                                                                                               | 2/27 [00:09<02:02,  4.92s/it]

0: 384x640 (no detections), 246.8ms
1: 384x640 (no detections), 246.8ms
2: 384x640 (no detections), 246.8ms
3: 384x640 (no detections), 246.8ms
4: 384x640 (no detections), 246.8ms
5: 384x640 (no detections), 246.8ms
6: 384x640 (no detections), 246.8ms
7: 384x640 1 animal, 246.8ms
8: 384x640 1 animal, 246.8ms
9: 384x640 1 animal, 246.8ms
10: 384x640 1 animal, 246.8ms
11: 384x640 1 animal, 246.8ms
12: 384x640 1 animal, 246.8ms
13: 384x640 (no detections), 246.8ms
14: 384x640 (no detections), 246.8ms
15: 384x640 (no detections), 246.8ms
Speed: 1.7ms preprocess, 246.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 11%|███████████████▎                                                                                                                          | 3/27 [00:14<01:57,  4.91s/it]

0: 384x640 (no detections), 246.3ms
1: 384x640 (no detections), 246.3ms
2: 384x640 1 animal, 246.3ms
3: 384x640 1 animal, 246.3ms
4: 384x640 1 animal, 246.3ms
5: 384x640 1 animal, 246.3ms
6: 384x640 (no detections), 246.3ms
7: 384x640 (no detections), 246.3ms
8: 384x640 (no detections), 246.3ms
9: 384x640 (no detections), 246.3ms
10: 384x640 (no detections), 246.3ms
11: 384x640 (no detections), 246.3ms
12: 384x640 1 animal, 246.3ms
13: 384x640 1 animal, 246.3ms
14: 384x640 1 animal, 246.3ms
15: 384x640 1 animal, 246.3ms
Speed: 1.7ms preprocess, 246.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 15%|████████████████████▍                                                                                                                     | 4/27 [00:19<01:52,  4.90s/it]

0: 384x640 1 animal, 237.8ms
1: 384x640 1 animal, 237.8ms
2: 384x640 1 animal, 237.8ms
3: 384x640 1 animal, 237.8ms
4: 384x640 1 animal, 237.8ms
5: 384x640 1 animal, 237.8ms
6: 384x640 1 animal, 237.8ms
7: 384x640 1 animal, 237.8ms
8: 384x640 1 animal, 237.8ms
9: 384x640 1 animal, 237.8ms
10: 384x640 1 animal, 237.8ms
11: 384x640 1 animal, 237.8ms
12: 384x640 1 animal, 237.8ms
13: 384x640 1 animal, 237.8ms
14: 384x640 1 animal, 237.8ms
15: 384x640 1 animal, 237.8ms
Speed: 1.7ms preprocess, 237.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 19%|█████████████████████████▌                                                                                                                | 5/27 [00:24<01:46,  4.84s/it]

0: 640x640 1 animal, 396.7ms
1: 640x640 1 animal, 396.7ms
2: 640x640 1 animal, 396.7ms
3: 640x640 1 animal, 396.7ms
4: 640x640 1 animal, 396.7ms
5: 640x640 1 animal, 396.7ms
6: 640x640 1 animal, 396.7ms
7: 640x640 1 animal, 396.7ms
8: 640x640 (no detections), 396.7ms
9: 640x640 1 animal, 396.7ms
10: 640x640 (no detections), 396.7ms
11: 640x640 (no detections), 396.7ms
12: 640x640 (no detections), 396.7ms
13: 640x640 (no detections), 396.7ms
14: 640x640 (no detections), 396.7ms
15: 640x640 (no detections), 396.7ms
Speed: 2.5ms preprocess, 396.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 22%|██████████████████████████████▋                                                                                                           | 6/27 [00:31<01:57,  5.60s/it]

0: 640x640 (no detections), 399.8ms
1: 640x640 (no detections), 399.8ms
2: 640x640 (no detections), 399.8ms
3: 640x640 (no detections), 399.8ms
4: 640x640 1 animal, 399.8ms
5: 640x640 (no detections), 399.8ms
6: 640x640 1 animal, 399.8ms
7: 640x640 (no detections), 399.8ms
8: 640x640 (no detections), 399.8ms
9: 640x640 (no detections), 399.8ms
10: 640x640 (no detections), 399.8ms
11: 640x640 (no detections), 399.8ms
12: 640x640 (no detections), 399.8ms
13: 640x640 (no detections), 399.8ms
14: 640x640 1 animal, 399.8ms
15: 640x640 1 animal, 399.8ms
Speed: 3.0ms preprocess, 399.8ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 26%|███████████████████████████████████▊                                                                                                      | 7/27 [00:38<02:02,  6.15s/it]

0: 384x640 (no detections), 243.2ms
1: 384x640 (no detections), 243.2ms
2: 384x640 (no detections), 243.2ms
3: 384x640 (no detections), 243.2ms
4: 384x640 (no detections), 243.2ms
5: 384x640 (no detections), 243.2ms
6: 384x640 (no detections), 243.2ms
7: 384x640 (no detections), 243.2ms
8: 384x640 1 animal, 243.2ms
9: 384x640 1 animal, 243.2ms
10: 384x640 1 animal, 243.2ms
11: 384x640 1 animal, 243.2ms
12: 384x640 1 animal, 243.2ms
13: 384x640 1 animal, 243.2ms
14: 384x640 1 animal, 243.2ms
15: 384x640 1 animal, 243.2ms
Speed: 1.7ms preprocess, 243.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 30%|████████████████████████████████████████▉                                                                                                 | 8/27 [00:43<01:48,  5.69s/it]

0: 384x640 1 animal, 244.0ms
1: 384x640 1 animal, 244.0ms
2: 384x640 2 animals, 244.0ms
3: 384x640 1 animal, 244.0ms
4: 384x640 1 animal, 244.0ms
5: 384x640 (no detections), 244.0ms
6: 384x640 (no detections), 244.0ms
7: 384x640 (no detections), 244.0ms
8: 384x640 (no detections), 244.0ms
9: 384x640 (no detections), 244.0ms
10: 384x640 (no detections), 244.0ms
11: 384x640 (no detections), 244.0ms
12: 384x640 (no detections), 244.0ms
13: 384x640 1 animal, 244.0ms
14: 384x640 1 animal, 244.0ms
15: 384x640 (no detections), 244.0ms
Speed: 1.7ms preprocess, 244.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 33%|██████████████████████████████████████████████                                                                                            | 9/27 [00:48<01:37,  5.40s/it]

0: 384x640 (no detections), 243.6ms
1: 384x640 (no detections), 243.6ms
2: 384x640 (no detections), 243.6ms
3: 384x640 (no detections), 243.6ms
4: 384x640 (no detections), 243.6ms
5: 384x640 (no detections), 243.6ms
6: 384x640 1 animal, 243.6ms
7: 384x640 1 animal, 243.6ms
8: 384x640 1 animal, 243.6ms
9: 384x640 (no detections), 243.6ms
10: 384x640 (no detections), 243.6ms
11: 384x640 (no detections), 243.6ms
12: 384x640 (no detections), 243.6ms
13: 384x640 (no detections), 243.6ms
14: 384x640 (no detections), 243.6ms
15: 384x640 (no detections), 243.6ms
Speed: 1.7ms preprocess, 243.6ms inference, 0.7ms postprocess per image at shape (16, 3, 384, 640)

 37%|██████████████████████████████████████████████████▋                                                                                      | 10/27 [00:53<01:28,  5.23s/it]

0: 384x640 1 animal, 244.3ms
1: 384x640 1 animal, 244.3ms
2: 384x640 1 animal, 244.3ms
3: 384x640 (no detections), 244.3ms
4: 384x640 (no detections), 244.3ms
5: 384x640 (no detections), 244.3ms
6: 384x640 (no detections), 244.3ms
7: 384x640 (no detections), 244.3ms
8: 384x640 (no detections), 244.3ms
9: 384x640 (no detections), 244.3ms
10: 384x640 1 animal, 244.3ms
11: 384x640 (no detections), 244.3ms
12: 384x640 (no detections), 244.3ms
13: 384x640 (no detections), 244.3ms
14: 384x640 (no detections), 244.3ms
15: 384x640 (no detections), 244.3ms
Speed: 1.7ms preprocess, 244.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 41%|███████████████████████████████████████████████████████▊                                                                                 | 11/27 [00:57<01:21,  5.11s/it]

0: 384x640 (no detections), 246.1ms
1: 384x640 (no detections), 246.1ms
2: 384x640 (no detections), 246.1ms
3: 384x640 (no detections), 246.1ms
4: 384x640 (no detections), 246.1ms
5: 384x640 (no detections), 246.1ms
6: 384x640 (no detections), 246.1ms
7: 384x640 2 animals, 246.1ms
8: 384x640 (no detections), 246.1ms
9: 384x640 (no detections), 246.1ms
10: 384x640 (no detections), 246.1ms
11: 384x640 (no detections), 246.1ms
12: 384x640 (no detections), 246.1ms
13: 384x640 (no detections), 246.1ms
14: 384x640 1 animal, 246.1ms
15: 384x640 1 animal, 246.1ms
Speed: 1.8ms preprocess, 246.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 44%|████████████████████████████████████████████████████████████▉                                                                            | 12/27 [01:02<01:15,  5.05s/it]

0: 384x640 1 animal, 246.9ms
1: 384x640 1 animal, 246.9ms
2: 384x640 (no detections), 246.9ms
3: 384x640 (no detections), 246.9ms
4: 384x640 (no detections), 246.9ms
5: 384x640 (no detections), 246.9ms
6: 384x640 (no detections), 246.9ms
7: 384x640 (no detections), 246.9ms
8: 384x640 3 animals, 246.9ms
9: 384x640 1 animal, 246.9ms
10: 384x640 (no detections), 246.9ms
11: 384x640 (no detections), 246.9ms
12: 384x640 (no detections), 246.9ms
13: 384x640 (no detections), 246.9ms
14: 384x640 (no detections), 246.9ms
15: 384x640 (no detections), 246.9ms
Speed: 1.8ms preprocess, 246.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 48%|█████████████████████████████████████████████████████████████████▉                                                                       | 13/27 [01:07<01:10,  5.01s/it]

0: 384x640 (no detections), 247.5ms
1: 384x640 (no detections), 247.5ms
2: 384x640 4 animals, 247.5ms
3: 384x640 1 animal, 247.5ms
4: 384x640 3 animals, 247.5ms
5: 384x640 (no detections), 247.5ms
6: 384x640 (no detections), 247.5ms
7: 384x640 (no detections), 247.5ms
8: 384x640 (no detections), 247.5ms
9: 384x640 (no detections), 247.5ms
10: 384x640 (no detections), 247.5ms
11: 384x640 (no detections), 247.5ms
12: 384x640 1 animal, 247.5ms
13: 384x640 1 animal, 247.5ms
14: 384x640 (no detections), 247.5ms
15: 384x640 2 animals, 247.5ms
Speed: 2.1ms preprocess, 247.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 52%|███████████████████████████████████████████████████████████████████████                                                                  | 14/27 [01:12<01:04,  4.98s/it]

0: 384x640 (no detections), 246.8ms
1: 384x640 1 animal, 246.8ms
2: 384x640 (no detections), 246.8ms
3: 384x640 1 animal, 246.8ms
4: 384x640 1 animal, 246.8ms
5: 384x640 (no detections), 246.8ms
6: 384x640 1 animal, 246.8ms
7: 384x640 1 animal, 246.8ms
8: 384x640 1 animal, 246.8ms
9: 384x640 1 animal, 246.8ms
10: 384x640 1 animal, 246.8ms
11: 384x640 1 animal, 246.8ms
12: 384x640 1 animal, 246.8ms
13: 384x640 1 animal, 246.8ms
14: 384x640 1 animal, 246.8ms
15: 384x640 1 animal, 246.8ms
Speed: 1.7ms preprocess, 246.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 56%|████████████████████████████████████████████████████████████████████████████                                                             | 15/27 [01:17<00:59,  4.95s/it]

0: 640x640 1 animal, 413.8ms
1: 640x640 1 animal, 413.8ms
2: 640x640 (no detections), 413.8ms
3: 640x640 (no detections), 413.8ms
4: 640x640 1 animal, 413.8ms
5: 640x640 1 animal, 413.8ms
6: 640x640 2 animals, 413.8ms
7: 640x640 1 animal, 413.8ms
8: 640x640 1 animal, 413.8ms
9: 640x640 (no detections), 413.8ms
10: 640x640 (no detections), 413.8ms
11: 640x640 1 animal, 413.8ms
12: 640x640 1 animal, 413.8ms
13: 640x640 (no detections), 413.8ms
14: 640x640 (no detections), 413.8ms
15: 640x640 (no detections), 413.8ms
Speed: 2.8ms preprocess, 413.8ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 59%|█████████████████████████████████████████████████████████████████████████████████▏                                                       | 16/27 [01:24<01:02,  5.69s/it]

0: 640x640 (no detections), 416.3ms
1: 640x640 (no detections), 416.3ms
2: 640x640 (no detections), 416.3ms
3: 640x640 (no detections), 416.3ms
4: 640x640 2 animals, 416.3ms
5: 640x640 (no detections), 416.3ms
6: 640x640 (no detections), 416.3ms
7: 640x640 (no detections), 416.3ms
8: 640x640 (no detections), 416.3ms
9: 640x640 (no detections), 416.3ms
10: 640x640 (no detections), 416.3ms
11: 640x640 (no detections), 416.3ms
12: 640x640 (no detections), 416.3ms
13: 640x640 (no detections), 416.3ms
14: 640x640 2 animals, 416.3ms
15: 640x640 1 animal, 416.3ms
Speed: 2.7ms preprocess, 416.3ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 63%|██████████████████████████████████████████████████████████████████████████████████████▎                                                  | 17/27 [01:32<01:02,  6.24s/it]

0: 384x640 1 animal, 245.0ms
1: 384x640 1 animal, 245.0ms
2: 384x640 1 animal, 245.0ms
3: 384x640 1 animal, 245.0ms
4: 384x640 1 animal, 245.0ms
5: 384x640 1 animal, 245.0ms
6: 384x640 1 animal, 245.0ms
7: 384x640 1 animal, 245.0ms
8: 384x640 1 animal, 245.0ms
9: 384x640 (no detections), 245.0ms
10: 384x640 (no detections), 245.0ms
11: 384x640 1 animal, 245.0ms
12: 384x640 1 animal, 245.0ms
13: 384x640 (no detections), 245.0ms
14: 384x640 2 animals, 245.0ms
15: 384x640 (no detections), 245.0ms
Speed: 1.9ms preprocess, 245.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 67%|███████████████████████████████████████████████████████████████████████████████████████████▎                                             | 18/27 [01:37<00:52,  5.83s/it]

0: 384x640 (no detections), 246.2ms
1: 384x640 (no detections), 246.2ms
2: 384x640 1 animal, 246.2ms
3: 384x640 1 animal, 246.2ms
4: 384x640 (no detections), 246.2ms
5: 384x640 (no detections), 246.2ms
6: 384x640 (no detections), 246.2ms
7: 384x640 (no detections), 246.2ms
8: 384x640 (no detections), 246.2ms
9: 384x640 (no detections), 246.2ms
10: 384x640 (no detections), 246.2ms
11: 384x640 (no detections), 246.2ms
12: 384x640 1 animal, 246.2ms
13: 384x640 1 animal, 246.2ms
14: 384x640 1 animal, 246.2ms
15: 384x640 1 animal, 246.2ms
Speed: 2.0ms preprocess, 246.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 19/27 [01:42<00:44,  5.55s/it]

0: 384x640 1 animal, 244.7ms
1: 384x640 1 animal, 244.7ms
2: 384x640 1 animal, 244.7ms
3: 384x640 1 animal, 244.7ms
4: 384x640 (no detections), 244.7ms
5: 384x640 1 animal, 244.7ms
6: 384x640 1 animal, 244.7ms
7: 384x640 1 animal, 244.7ms
8: 384x640 1 animal, 244.7ms
9: 384x640 1 animal, 244.7ms
10: 384x640 1 animal, 244.7ms
11: 384x640 (no detections), 244.7ms
12: 384x640 (no detections), 244.7ms
13: 384x640 (no detections), 244.7ms
14: 384x640 (no detections), 244.7ms
15: 384x640 (no detections), 244.7ms
Speed: 1.7ms preprocess, 244.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 20/27 [01:47<00:37,  5.34s/it]

0: 384x640 1 animal, 245.9ms
1: 384x640 1 animal, 245.9ms
2: 384x640 1 animal, 245.9ms
3: 384x640 1 animal, 245.9ms
4: 384x640 1 animal, 245.9ms
5: 384x640 (no detections), 245.9ms
6: 384x640 (no detections), 245.9ms
7: 384x640 (no detections), 245.9ms
8: 384x640 (no detections), 245.9ms
9: 384x640 (no detections), 245.9ms
10: 384x640 1 animal, 245.9ms
11: 384x640 2 animals, 245.9ms
12: 384x640 1 animal, 245.9ms
13: 384x640 1 animal, 245.9ms
14: 384x640 1 animal, 245.9ms
15: 384x640 1 animal, 245.9ms
Speed: 1.7ms preprocess, 245.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 21/27 [01:51<00:31,  5.20s/it]

0: 384x640 1 animal, 244.5ms
1: 384x640 1 animal, 244.5ms
2: 384x640 1 animal, 244.5ms
3: 384x640 1 animal, 244.5ms
4: 384x640 (no detections), 244.5ms
5: 384x640 1 animal, 244.5ms
6: 384x640 1 animal, 244.5ms
7: 384x640 (no detections), 244.5ms
8: 384x640 (no detections), 244.5ms
9: 384x640 (no detections), 244.5ms
10: 384x640 (no detections), 244.5ms
11: 384x640 (no detections), 244.5ms
12: 384x640 (no detections), 244.5ms
13: 384x640 (no detections), 244.5ms
14: 384x640 1 animal, 244.5ms
15: 384x640 1 animal, 244.5ms
Speed: 1.7ms preprocess, 244.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 22/27 [01:56<00:25,  5.07s/it]

0: 384x640 1 animal, 240.9ms
1: 384x640 1 animal, 240.9ms
2: 384x640 (no detections), 240.9ms
3: 384x640 (no detections), 240.9ms
4: 384x640 (no detections), 240.9ms
5: 384x640 (no detections), 240.9ms
6: 384x640 (no detections), 240.9ms
7: 384x640 (no detections), 240.9ms
8: 384x640 1 animal, 240.9ms
9: 384x640 1 animal, 240.9ms
10: 384x640 1 animal, 240.9ms
11: 384x640 2 animals, 240.9ms
12: 384x640 1 animal, 240.9ms
13: 384x640 (no detections), 240.9ms
14: 384x640 (no detections), 240.9ms
15: 384x640 (no detections), 240.9ms
Speed: 1.9ms preprocess, 240.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 23/27 [02:01<00:19,  5.00s/it]

0: 640x640 (no detections), 410.4ms
1: 640x640 (no detections), 410.4ms
2: 640x640 1 animal, 410.4ms
3: 640x640 1 animal, 410.4ms
4: 640x640 1 animal, 410.4ms
5: 640x640 1 animal, 410.4ms
6: 640x640 1 animal, 410.4ms
7: 640x640 (no detections), 410.4ms
8: 640x640 (no detections), 410.4ms
9: 640x640 (no detections), 410.4ms
10: 640x640 (no detections), 410.4ms
11: 640x640 (no detections), 410.4ms
12: 640x640 (no detections), 410.4ms
13: 640x640 (no detections), 410.4ms
14: 640x640 (no detections), 410.4ms
15: 640x640 (no detections), 410.4ms
Speed: 2.5ms preprocess, 410.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 24/27 [02:08<00:16,  5.62s/it]

0: 384x640 (no detections), 241.8ms
1: 384x640 (no detections), 241.8ms
2: 384x640 (no detections), 241.8ms
3: 384x640 (no detections), 241.8ms
4: 384x640 (no detections), 241.8ms
5: 384x640 (no detections), 241.8ms
6: 384x640 1 animal, 241.8ms
7: 384x640 1 animal, 241.8ms
8: 384x640 1 animal, 241.8ms
9: 384x640 1 animal, 241.8ms
10: 384x640 (no detections), 241.8ms
11: 384x640 (no detections), 241.8ms
12: 384x640 (no detections), 241.8ms
13: 384x640 (no detections), 241.8ms
14: 384x640 (no detections), 241.8ms
15: 384x640 (no detections), 241.8ms
Speed: 1.8ms preprocess, 241.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 25/27 [02:12<00:10,  5.22s/it]

0: 384x640 2 animals, 240.6ms
1: 384x640 2 animals, 240.6ms
2: 384x640 1 animal, 240.6ms
3: 384x640 2 animals, 240.6ms
4: 384x640 (no detections), 240.6ms
5: 384x640 (no detections), 240.6ms
6: 384x640 (no detections), 240.6ms
7: 384x640 (no detections), 240.6ms
8: 384x640 (no detections), 240.6ms
9: 384x640 (no detections), 240.6ms
10: 384x640 1 animal, 240.6ms
11: 384x640 3 animals, 240.6ms
12: 384x640 3 animals, 240.6ms
13: 384x640 2 animals, 240.6ms
14: 384x640 3 animals, 240.6ms
15: 384x640 3 animals, 240.6ms
Speed: 1.7ms preprocess, 240.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 26/27 [02:17<00:04,  4.95s/it]

0: 640x640 2 animals, 402.5ms
1: 640x640 1 animal, 402.5ms
2: 640x640 3 animals, 402.5ms
3: 640x640 1 animal, 402.5ms
4: 640x640 1 animal, 402.5ms
5: 640x640 1 animal, 402.5ms
6: 640x640 1 animal, 402.5ms
7: 640x640 1 animal, 402.5ms
8: 640x640 1 animal, 402.5ms
9: 640x640 1 animal, 402.5ms
10: 640x640 1 animal, 402.5ms
11: 640x640 (no detections), 402.5ms
12: 640x640 (no detections), 402.5ms
13: 640x640 (no detections), 402.5ms
Speed: 2.6ms preprocess, 402.5ms inference, 0.4ms postprocess per image at shape (14, 3, 640, 640)

00%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [02:23<00:00,  5.32s/it]

Detecting images from GANADO_2022_extracted

  0%|                                                                                                                                                 | 0/195 [00:00<?, ?it/s]

0: 384x640 1 animal, 243.5ms
1: 384x640 1 animal, 243.5ms
2: 384x640 3 animals, 243.5ms
3: 384x640 2 animals, 243.5ms
4: 384x640 1 animal, 243.5ms
5: 384x640 1 animal, 243.5ms
6: 384x640 1 animal, 243.5ms
7: 384x640 2 animals, 243.5ms
8: 384x640 3 animals, 243.5ms
9: 384x640 3 animals, 243.5ms
10: 384x640 2 animals, 243.5ms
11: 384x640 2 animals, 243.5ms
12: 384x640 2 animals, 243.5ms
13: 384x640 (no detections), 243.5ms
14: 384x640 1 animal, 243.5ms
15: 384x640 1 animal, 243.5ms
Speed: 1.8ms preprocess, 243.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  1%|▋                                                                                                                                        | 1/195 [00:04<14:57,  4.62s/it]

0: 384x640 (no detections), 243.5ms
1: 384x640 (no detections), 243.5ms
2: 384x640 (no detections), 243.5ms
3: 384x640 (no detections), 243.5ms
4: 384x640 1 animal, 243.5ms
5: 384x640 1 animal, 243.5ms
6: 384x640 1 animal, 243.5ms
7: 384x640 1 animal, 243.5ms
8: 384x640 1 animal, 243.5ms
9: 384x640 1 animal, 243.5ms
10: 384x640 1 animal, 243.5ms
11: 384x640 1 animal, 243.5ms
12: 384x640 1 animal, 243.5ms
13: 384x640 1 animal, 243.5ms
14: 384x640 1 animal, 243.5ms
15: 384x640 2 animals, 243.5ms
Speed: 1.9ms preprocess, 243.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  1%|█▍                                                                                                                                       | 2/195 [00:09<15:01,  4.67s/it]

0: 384x640 1 animal, 243.6ms
1: 384x640 1 animal, 243.6ms
2: 384x640 1 animal, 243.6ms
3: 384x640 1 animal, 243.6ms
4: 384x640 1 animal, 243.6ms
5: 384x640 1 animal, 243.6ms
6: 384x640 1 animal, 243.6ms
7: 384x640 1 animal, 243.6ms
8: 384x640 2 animals, 243.6ms
9: 384x640 1 animal, 243.6ms
10: 384x640 1 animal, 243.6ms
11: 384x640 3 animals, 243.6ms
12: 384x640 2 animals, 243.6ms
13: 384x640 2 animals, 243.6ms
14: 384x640 2 animals, 243.6ms
15: 384x640 2 animals, 243.6ms
Speed: 1.9ms preprocess, 243.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  2%|██                                                                                                                                       | 3/195 [00:14<15:02,  4.70s/it]

0: 384x640 2 animals, 246.3ms
1: 384x640 2 animals, 246.3ms
2: 384x640 1 animal, 246.3ms
3: 384x640 1 animal, 246.3ms
4: 384x640 1 animal, 246.3ms
5: 384x640 1 animal, 246.3ms
6: 384x640 1 animal, 246.3ms
7: 384x640 1 animal, 246.3ms
8: 384x640 1 animal, 246.3ms
9: 384x640 (no detections), 246.3ms
10: 384x640 (no detections), 246.3ms
11: 384x640 (no detections), 246.3ms
12: 384x640 1 animal, 246.3ms
13: 384x640 1 animal, 246.3ms
14: 384x640 1 animal, 246.3ms
15: 384x640 1 animal, 246.3ms
Speed: 2.1ms preprocess, 246.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  2%|██▊                                                                                                                                      | 4/195 [00:18<15:10,  4.76s/it]

0: 384x640 1 animal, 244.1ms
1: 384x640 1 animal, 244.1ms
2: 384x640 1 animal, 244.1ms
3: 384x640 1 animal, 244.1ms
4: 384x640 1 animal, 244.1ms
5: 384x640 1 animal, 244.1ms
6: 384x640 1 animal, 244.1ms
7: 384x640 1 animal, 244.1ms
8: 384x640 1 animal, 244.1ms
9: 384x640 1 animal, 244.1ms
10: 384x640 1 animal, 244.1ms
11: 384x640 1 animal, 244.1ms
12: 384x640 1 animal, 244.1ms
13: 384x640 1 animal, 244.1ms
14: 384x640 1 animal, 244.1ms
15: 384x640 1 animal, 244.1ms
Speed: 2.2ms preprocess, 244.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  3%|███▌                                                                                                                                     | 5/195 [00:23<15:08,  4.78s/it]

0: 384x640 3 animals, 244.6ms
1: 384x640 2 animals, 244.6ms
2: 384x640 2 animals, 244.6ms
3: 384x640 1 animal, 244.6ms
4: 384x640 1 animal, 244.6ms
5: 384x640 1 animal, 244.6ms
6: 384x640 1 animal, 244.6ms
7: 384x640 1 animal, 244.6ms
8: 384x640 1 animal, 244.6ms
9: 384x640 1 animal, 244.6ms
10: 384x640 1 animal, 244.6ms
11: 384x640 1 animal, 244.6ms
12: 384x640 (no detections), 244.6ms
13: 384x640 (no detections), 244.6ms
14: 384x640 (no detections), 244.6ms
15: 384x640 (no detections), 244.6ms
Speed: 1.9ms preprocess, 244.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  3%|████▏                                                                                                                                    | 6/195 [00:28<15:03,  4.78s/it]

0: 384x640 (no detections), 244.0ms
1: 384x640 (no detections), 244.0ms
2: 384x640 1 animal, 244.0ms
3: 384x640 (no detections), 244.0ms
4: 384x640 3 animals, 244.0ms
5: 384x640 3 animals, 244.0ms
6: 384x640 2 animals, 244.0ms
7: 384x640 4 animals, 244.0ms
8: 384x640 6 animals, 244.0ms
9: 384x640 4 animals, 244.0ms
10: 384x640 3 animals, 244.0ms
11: 384x640 4 animals, 244.0ms
12: 384x640 3 animals, 244.0ms
13: 384x640 3 animals, 244.0ms
14: 384x640 1 animal, 244.0ms
15: 384x640 1 animal, 244.0ms
Speed: 1.9ms preprocess, 244.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  4%|████▉                                                                                                                                    | 7/195 [00:33<15:00,  4.79s/it]

0: 384x640 1 animal, 242.8ms
1: 384x640 (no detections), 242.8ms
2: 384x640 1 person, 242.8ms
3: 384x640 (no detections), 242.8ms
4: 384x640 1 animal, 242.8ms
5: 384x640 1 animal, 242.8ms
6: 384x640 (no detections), 242.8ms
7: 384x640 1 animal, 242.8ms
8: 384x640 1 person, 242.8ms
9: 384x640 (no detections), 242.8ms
10: 384x640 (no detections), 242.8ms
11: 384x640 (no detections), 242.8ms
12: 384x640 (no detections), 242.8ms
13: 384x640 (no detections), 242.8ms
14: 384x640 (no detections), 242.8ms
15: 384x640 (no detections), 242.8ms
Speed: 1.9ms preprocess, 242.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  4%|█████▌                                                                                                                                   | 8/195 [00:38<14:53,  4.78s/it]

0: 384x640 (no detections), 243.7ms
1: 384x640 (no detections), 243.7ms
2: 384x640 1 animal, 243.7ms
3: 384x640 1 animal, 243.7ms
4: 384x640 2 animals, 243.7ms
5: 384x640 2 animals, 243.7ms
6: 384x640 2 animals, 243.7ms
7: 384x640 1 animal, 243.7ms
8: 384x640 1 animal, 243.7ms
9: 384x640 1 animal, 243.7ms
10: 384x640 1 animal, 243.7ms
11: 384x640 1 animal, 243.7ms
12: 384x640 1 animal, 243.7ms
13: 384x640 1 animal, 243.7ms
14: 384x640 2 animals, 243.7ms
15: 384x640 2 animals, 243.7ms
Speed: 1.9ms preprocess, 243.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  5%|██████▎                                                                                                                                  | 9/195 [00:42<14:48,  4.78s/it]

0: 384x640 2 animals, 243.4ms
1: 384x640 1 animal, 243.4ms
2: 384x640 1 animal, 243.4ms
3: 384x640 1 animal, 243.4ms
4: 384x640 1 animal, 243.4ms
5: 384x640 1 animal, 243.4ms
6: 384x640 1 animal, 243.4ms
7: 384x640 1 animal, 243.4ms
8: 384x640 1 animal, 243.4ms
9: 384x640 1 animal, 243.4ms
10: 384x640 1 animal, 243.4ms
11: 384x640 1 animal, 243.4ms
12: 384x640 1 animal, 243.4ms
13: 384x640 1 animal, 243.4ms
14: 384x640 1 animal, 243.4ms
15: 384x640 1 animal, 243.4ms
Speed: 1.9ms preprocess, 243.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  5%|██████▉                                                                                                                                 | 10/195 [00:47<14:38,  4.75s/it]

0: 384x640 1 animal, 244.1ms
1: 384x640 1 animal, 244.1ms
2: 384x640 1 animal, 244.1ms
3: 384x640 1 animal, 244.1ms
4: 384x640 1 animal, 244.1ms
5: 384x640 1 animal, 244.1ms
6: 384x640 1 animal, 244.1ms
7: 384x640 1 animal, 244.1ms
8: 384x640 1 animal, 244.1ms
9: 384x640 1 animal, 244.1ms
10: 384x640 1 animal, 244.1ms
11: 384x640 1 animal, 244.1ms
12: 384x640 1 animal, 244.1ms
13: 384x640 1 animal, 244.1ms
14: 384x640 (no detections), 244.1ms
15: 384x640 (no detections), 244.1ms
Speed: 1.8ms preprocess, 244.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  6%|███████▋                                                                                                                                | 11/195 [00:52<14:28,  4.72s/it]

0: 384x640 (no detections), 244.0ms
1: 384x640 (no detections), 244.0ms
2: 384x640 (no detections), 244.0ms
3: 384x640 (no detections), 244.0ms
4: 384x640 1 animal, 244.0ms
5: 384x640 1 animal, 244.0ms
6: 384x640 1 animal, 244.0ms
7: 384x640 1 animal, 244.0ms
8: 384x640 1 animal, 244.0ms
9: 384x640 1 animal, 244.0ms
10: 384x640 1 animal, 244.0ms
11: 384x640 1 animal, 244.0ms
12: 384x640 1 animal, 244.0ms
13: 384x640 1 animal, 244.0ms
14: 384x640 1 animal, 244.0ms
15: 384x640 1 animal, 244.0ms
Speed: 2.1ms preprocess, 244.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  6%|████████▎                                                                                                                               | 12/195 [00:56<14:27,  4.74s/it]

0: 384x640 1 animal, 236.8ms
1: 384x640 1 animal, 236.8ms
2: 384x640 1 animal, 236.8ms
3: 384x640 1 animal, 236.8ms
4: 384x640 1 animal, 236.8ms
5: 384x640 1 animal, 236.8ms
6: 384x640 1 animal, 236.8ms
7: 384x640 1 animal, 236.8ms
8: 384x640 1 animal, 236.8ms
9: 384x640 2 animals, 236.8ms
10: 384x640 1 animal, 236.8ms
11: 384x640 1 animal, 236.8ms
12: 384x640 1 animal, 236.8ms
13: 384x640 1 animal, 236.8ms
14: 384x640 1 animal, 236.8ms
15: 384x640 1 animal, 236.8ms
Speed: 1.9ms preprocess, 236.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  7%|█████████                                                                                                                               | 13/195 [01:01<14:16,  4.70s/it]

0: 384x640 1 animal, 238.4ms
1: 384x640 1 animal, 238.4ms
2: 384x640 1 animal, 238.4ms
3: 384x640 1 animal, 238.4ms
4: 384x640 1 animal, 238.4ms
5: 384x640 1 animal, 238.4ms
6: 384x640 1 animal, 238.4ms
7: 384x640 1 animal, 238.4ms
8: 384x640 1 animal, 238.4ms
9: 384x640 1 animal, 238.4ms
10: 384x640 1 animal, 238.4ms
11: 384x640 1 animal, 238.4ms
12: 384x640 1 animal, 238.4ms
13: 384x640 1 animal, 238.4ms
14: 384x640 1 animal, 238.4ms
15: 384x640 1 animal, 238.4ms
Speed: 1.9ms preprocess, 238.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  7%|█████████▊                                                                                                                              | 14/195 [01:06<14:07,  4.68s/it]

0: 384x640 1 animal, 236.6ms
1: 384x640 1 animal, 236.6ms
2: 384x640 1 animal, 236.6ms
3: 384x640 1 animal, 236.6ms
4: 384x640 1 animal, 236.6ms
5: 384x640 (no detections), 236.6ms
6: 384x640 1 animal, 236.6ms
7: 384x640 1 animal, 236.6ms
8: 384x640 1 person, 236.6ms
9: 384x640 1 animal, 236.6ms
10: 384x640 1 animal, 236.6ms
11: 384x640 1 animal, 236.6ms
12: 384x640 1 animal, 236.6ms
13: 384x640 1 animal, 236.6ms
14: 384x640 1 animal, 236.6ms
15: 384x640 1 animal, 236.6ms
Speed: 1.9ms preprocess, 236.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  8%|██████████▍                                                                                                                             | 15/195 [01:10<13:58,  4.66s/it]

0: 384x640 1 animal, 238.0ms
1: 384x640 1 animal, 238.0ms
2: 384x640 1 animal, 238.0ms
3: 384x640 1 animal, 238.0ms
4: 384x640 1 animal, 238.0ms
5: 384x640 1 animal, 238.0ms
6: 384x640 1 animal, 238.0ms
7: 384x640 1 animal, 238.0ms
8: 384x640 1 animal, 238.0ms
9: 384x640 1 animal, 238.0ms
10: 384x640 1 animal, 238.0ms
11: 384x640 1 animal, 238.0ms
12: 384x640 1 animal, 238.0ms
13: 384x640 1 animal, 238.0ms
14: 384x640 1 animal, 238.0ms
15: 384x640 1 animal, 238.0ms
Speed: 1.9ms preprocess, 238.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  8%|███████████▏                                                                                                                            | 16/195 [01:15<13:54,  4.66s/it]

0: 384x640 1 animal, 243.0ms
1: 384x640 1 animal, 243.0ms
2: 384x640 1 animal, 243.0ms
3: 384x640 1 animal, 243.0ms
4: 384x640 (no detections), 243.0ms
5: 384x640 1 animal, 243.0ms
6: 384x640 1 animal, 243.0ms
7: 384x640 1 animal, 243.0ms
8: 384x640 1 animal, 243.0ms
9: 384x640 1 animal, 243.0ms
10: 384x640 1 animal, 243.0ms
11: 384x640 1 animal, 243.0ms
12: 384x640 1 animal, 243.0ms
13: 384x640 1 animal, 243.0ms
14: 384x640 3 animals, 243.0ms
15: 384x640 (no detections), 243.0ms
Speed: 1.9ms preprocess, 243.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  9%|███████████▊                                                                                                                            | 17/195 [01:20<13:50,  4.67s/it]

0: 384x640 1 animal, 242.6ms
1: 384x640 2 animals, 242.6ms
2: 384x640 2 animals, 242.6ms
3: 384x640 1 animal, 242.6ms
4: 384x640 1 animal, 242.6ms
5: 384x640 1 animal, 242.6ms
6: 384x640 1 animal, 242.6ms
7: 384x640 2 animals, 242.6ms
8: 384x640 1 animal, 242.6ms
9: 384x640 1 animal, 242.6ms
10: 384x640 1 animal, 242.6ms
11: 384x640 1 animal, 242.6ms
12: 384x640 1 animal, 242.6ms
13: 384x640 1 animal, 242.6ms
14: 384x640 1 animal, 242.6ms
15: 384x640 1 animal, 242.6ms
Speed: 1.9ms preprocess, 242.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

  9%|████████████▌                                                                                                                           | 18/195 [01:24<13:53,  4.71s/it]

0: 384x640 1 animal, 243.5ms
1: 384x640 1 animal, 243.5ms
2: 384x640 1 animal, 243.5ms
3: 384x640 1 animal, 243.5ms
4: 384x640 1 animal, 243.5ms
5: 384x640 1 animal, 243.5ms
6: 384x640 1 animal, 243.5ms
7: 384x640 1 animal, 243.5ms
8: 384x640 1 animal, 243.5ms
9: 384x640 1 animal, 243.5ms
10: 384x640 1 animal, 243.5ms
11: 384x640 1 animal, 243.5ms
12: 384x640 1 animal, 243.5ms
13: 384x640 1 animal, 243.5ms
14: 384x640 1 animal, 243.5ms
15: 384x640 1 animal, 243.5ms
Speed: 2.1ms preprocess, 243.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 10%|█████████████▎                                                                                                                          | 19/195 [01:29<13:51,  4.73s/it]

0: 384x640 1 animal, 243.7ms
1: 384x640 1 animal, 243.7ms
2: 384x640 1 animal, 243.7ms
3: 384x640 1 animal, 243.7ms
4: 384x640 1 animal, 243.7ms
5: 384x640 1 animal, 243.7ms
6: 384x640 1 animal, 243.7ms
7: 384x640 1 animal, 243.7ms
8: 384x640 1 animal, 243.7ms
9: 384x640 1 animal, 243.7ms
10: 384x640 1 animal, 243.7ms
11: 384x640 1 animal, 243.7ms
12: 384x640 1 animal, 243.7ms
13: 384x640 1 animal, 243.7ms
14: 384x640 1 animal, 243.7ms
15: 384x640 1 animal, 243.7ms
Speed: 1.9ms preprocess, 243.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 10%|█████████████▉                                                                                                                          | 20/195 [01:34<13:50,  4.75s/it]

0: 384x640 1 animal, 244.0ms
1: 384x640 1 animal, 244.0ms
2: 384x640 1 animal, 244.0ms
3: 384x640 1 animal, 244.0ms
4: 384x640 1 animal, 244.0ms
5: 384x640 1 animal, 244.0ms
6: 384x640 1 animal, 244.0ms
7: 384x640 1 animal, 244.0ms
8: 384x640 1 animal, 244.0ms
9: 384x640 1 animal, 244.0ms
10: 384x640 1 animal, 244.0ms
11: 384x640 1 animal, 244.0ms
12: 384x640 1 animal, 244.0ms
13: 384x640 1 animal, 244.0ms
14: 384x640 1 animal, 244.0ms
15: 384x640 1 animal, 244.0ms
Speed: 1.9ms preprocess, 244.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 11%|██████████████▋                                                                                                                         | 21/195 [01:39<13:46,  4.75s/it]

0: 384x640 1 animal, 244.3ms
1: 384x640 1 animal, 244.3ms
2: 384x640 1 animal, 244.3ms
3: 384x640 (no detections), 244.3ms
4: 384x640 1 animal, 244.3ms
5: 384x640 1 animal, 244.3ms
6: 384x640 1 animal, 244.3ms
7: 384x640 1 animal, 244.3ms
8: 384x640 1 animal, 244.3ms
9: 384x640 (no detections), 244.3ms
10: 384x640 (no detections), 244.3ms
11: 384x640 (no detections), 244.3ms
12: 384x640 (no detections), 244.3ms
13: 384x640 (no detections), 244.3ms
14: 384x640 1 animal, 244.3ms
15: 384x640 1 animal, 244.3ms
Speed: 2.3ms preprocess, 244.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 11%|███████████████▎                                                                                                                        | 22/195 [01:44<13:43,  4.76s/it]

0: 384x640 1 animal, 244.2ms
1: 384x640 1 animal, 244.2ms
2: 384x640 1 animal, 244.2ms
3: 384x640 1 animal, 244.2ms
4: 384x640 1 animal, 244.2ms
5: 384x640 1 animal, 244.2ms
6: 384x640 1 animal, 244.2ms
7: 384x640 1 animal, 244.2ms
8: 384x640 2 animals, 244.2ms
9: 384x640 1 animal, 244.2ms
10: 384x640 3 animals, 244.2ms
11: 384x640 (no detections), 244.2ms
12: 384x640 (no detections), 244.2ms
13: 384x640 1 animal, 244.2ms
14: 384x640 (no detections), 244.2ms
15: 384x640 (no detections), 244.2ms
Speed: 1.9ms preprocess, 244.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 12%|████████████████                                                                                                                        | 23/195 [01:48<13:41,  4.78s/it]

0: 384x640 1 animal, 242.6ms
1: 384x640 1 animal, 242.6ms
2: 384x640 1 animal, 242.6ms
3: 384x640 1 animal, 242.6ms
4: 384x640 1 animal, 242.6ms
5: 384x640 1 animal, 242.6ms
6: 384x640 1 animal, 242.6ms
7: 384x640 1 animal, 242.6ms
8: 384x640 1 animal, 242.6ms
9: 384x640 1 animal, 242.6ms
10: 384x640 1 animal, 242.6ms
11: 384x640 1 animal, 242.6ms
12: 384x640 1 animal, 242.6ms
13: 384x640 1 animal, 242.6ms
14: 384x640 1 animal, 242.6ms
15: 384x640 1 animal, 242.6ms
Speed: 1.9ms preprocess, 242.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 12%|████████████████▋                                                                                                                       | 24/195 [01:53<13:36,  4.77s/it]

0: 384x640 1 animal, 242.1ms
1: 384x640 1 animal, 242.1ms
2: 384x640 1 animal, 242.1ms
3: 384x640 1 animal, 242.1ms
4: 384x640 1 animal, 242.1ms
5: 384x640 1 animal, 242.1ms
6: 384x640 (no detections), 242.1ms
7: 384x640 1 animal, 242.1ms
8: 384x640 1 animal, 242.1ms
9: 384x640 1 animal, 242.1ms
10: 384x640 1 animal, 242.1ms
11: 384x640 1 animal, 242.1ms
12: 384x640 1 animal, 242.1ms
13: 384x640 1 animal, 242.1ms
14: 384x640 1 animal, 242.1ms
15: 384x640 1 animal, 242.1ms
Speed: 1.8ms preprocess, 242.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 13%|█████████████████▍                                                                                                                      | 25/195 [01:58<13:24,  4.73s/it]

0: 384x640 1 animal, 243.1ms
1: 384x640 1 animal, 243.1ms
2: 384x640 1 animal, 243.1ms
3: 384x640 1 animal, 243.1ms
4: 384x640 1 animal, 243.1ms
5: 384x640 1 animal, 243.1ms
6: 384x640 1 animal, 243.1ms
7: 384x640 1 animal, 243.1ms
8: 384x640 1 animal, 243.1ms
9: 384x640 1 animal, 243.1ms
10: 384x640 1 animal, 243.1ms
11: 384x640 1 animal, 243.1ms
12: 384x640 1 animal, 243.1ms
13: 384x640 1 animal, 243.1ms
14: 384x640 1 animal, 243.1ms
15: 384x640 1 animal, 243.1ms
Speed: 2.2ms preprocess, 243.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 13%|██████████████████▏                                                                                                                     | 26/195 [02:02<13:17,  4.72s/it]

0: 384x640 1 animal, 244.2ms
1: 384x640 1 animal, 244.2ms
2: 384x640 1 animal, 244.2ms
3: 384x640 1 animal, 244.2ms
4: 384x640 1 animal, 1 person, 244.2ms
5: 384x640 1 animal, 244.2ms
6: 384x640 2 animals, 244.2ms
7: 384x640 1 animal, 244.2ms
8: 384x640 (no detections), 244.2ms
9: 384x640 (no detections), 244.2ms
10: 384x640 (no detections), 244.2ms
11: 384x640 (no detections), 244.2ms
12: 384x640 (no detections), 244.2ms
13: 384x640 (no detections), 244.2ms
14: 384x640 1 animal, 244.2ms
15: 384x640 3 animals, 244.2ms
Speed: 1.9ms preprocess, 244.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 14%|██████████████████▊                                                                                                                     | 27/195 [02:07<13:16,  4.74s/it]

0: 384x640 2 animals, 243.8ms
1: 384x640 2 animals, 243.8ms
2: 384x640 3 animals, 243.8ms
3: 384x640 3 animals, 243.8ms
4: 384x640 2 animals, 243.8ms
5: 384x640 2 animals, 243.8ms
6: 384x640 2 animals, 243.8ms
7: 384x640 3 animals, 243.8ms
8: 384x640 1 animal, 243.8ms
9: 384x640 1 animal, 243.8ms
10: 384x640 (no detections), 243.8ms
11: 384x640 (no detections), 243.8ms
12: 384x640 (no detections), 243.8ms
13: 384x640 (no detections), 243.8ms
14: 384x640 (no detections), 243.8ms
15: 384x640 (no detections), 243.8ms
Speed: 1.9ms preprocess, 243.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 14%|███████████████████▌                                                                                                                    | 28/195 [02:12<13:13,  4.75s/it]

0: 384x640 (no detections), 245.6ms
1: 384x640 (no detections), 245.6ms
2: 384x640 (no detections), 245.6ms
3: 384x640 (no detections), 245.6ms
4: 384x640 (no detections), 245.6ms
5: 384x640 2 animals, 245.6ms
6: 384x640 1 animal, 245.6ms
7: 384x640 1 animal, 245.6ms
8: 384x640 1 animal, 245.6ms
9: 384x640 1 animal, 245.6ms
10: 384x640 1 animal, 245.6ms
11: 384x640 1 animal, 245.6ms
12: 384x640 1 animal, 245.6ms
13: 384x640 1 animal, 245.6ms
14: 384x640 1 animal, 245.6ms
15: 384x640 1 animal, 245.6ms
Speed: 2.1ms preprocess, 245.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 15%|████████████████████▏                                                                                                                   | 29/195 [02:17<13:13,  4.78s/it]

0: 384x640 1 animal, 245.5ms
1: 384x640 1 animal, 245.5ms
2: 384x640 1 animal, 245.5ms
3: 384x640 1 animal, 245.5ms
4: 384x640 1 animal, 245.5ms
5: 384x640 1 animal, 245.5ms
6: 384x640 1 animal, 245.5ms
7: 384x640 1 animal, 245.5ms
8: 384x640 1 animal, 245.5ms
9: 384x640 1 animal, 245.5ms
10: 384x640 1 animal, 245.5ms
11: 384x640 1 animal, 245.5ms
12: 384x640 1 animal, 245.5ms
13: 384x640 1 animal, 245.5ms
14: 384x640 1 animal, 245.5ms
15: 384x640 1 animal, 245.5ms
Speed: 1.9ms preprocess, 245.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 15%|████████████████████▉                                                                                                                   | 30/195 [02:22<13:10,  4.79s/it]

0: 384x640 1 animal, 244.1ms
1: 384x640 1 animal, 244.1ms
2: 384x640 1 animal, 244.1ms
3: 384x640 1 animal, 244.1ms
4: 384x640 1 animal, 244.1ms
5: 384x640 1 animal, 244.1ms
6: 384x640 1 animal, 244.1ms
7: 384x640 1 animal, 244.1ms
8: 384x640 1 animal, 244.1ms
9: 384x640 1 animal, 244.1ms
10: 384x640 1 animal, 244.1ms
11: 384x640 1 animal, 244.1ms
12: 384x640 1 animal, 244.1ms
13: 384x640 1 animal, 244.1ms
14: 384x640 1 animal, 244.1ms
15: 384x640 1 animal, 244.1ms
Speed: 1.9ms preprocess, 244.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 16%|█████████████████████▌                                                                                                                  | 31/195 [02:26<13:04,  4.78s/it]

0: 640x640 1 animal, 421.5ms
1: 640x640 1 animal, 421.5ms
2: 640x640 1 animal, 421.5ms
3: 640x640 1 animal, 421.5ms
4: 640x640 1 animal, 421.5ms
5: 640x640 1 animal, 1 person, 421.5ms
6: 640x640 1 animal, 421.5ms
7: 640x640 1 animal, 421.5ms
8: 640x640 2 animals, 421.5ms
9: 640x640 1 animal, 421.5ms
10: 640x640 1 animal, 421.5ms
11: 640x640 (no detections), 421.5ms
12: 640x640 (no detections), 421.5ms
13: 640x640 (no detections), 421.5ms
14: 640x640 1 animal, 2 persons, 421.5ms
15: 640x640 1 animal, 421.5ms
Speed: 2.7ms preprocess, 421.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 16%|██████████████████████▎                                                                                                                 | 32/195 [02:34<15:03,  5.54s/it]

0: 384x640 (no detections), 242.2ms
1: 384x640 (no detections), 242.2ms
2: 384x640 (no detections), 242.2ms
3: 384x640 (no detections), 242.2ms
4: 384x640 (no detections), 242.2ms
5: 384x640 (no detections), 242.2ms
6: 384x640 (no detections), 242.2ms
7: 384x640 (no detections), 242.2ms
8: 384x640 1 animal, 242.2ms
9: 384x640 1 animal, 242.2ms
10: 384x640 1 animal, 242.2ms
11: 384x640 1 animal, 242.2ms
12: 384x640 (no detections), 242.2ms
13: 384x640 (no detections), 242.2ms
14: 384x640 (no detections), 242.2ms
15: 384x640 (no detections), 242.2ms
Speed: 2.0ms preprocess, 242.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 17%|███████████████████████                                                                                                                 | 33/195 [02:38<13:58,  5.18s/it]

0: 640x640 1 animal, 424.9ms
1: 640x640 1 animal, 424.9ms
2: 640x640 1 animal, 424.9ms
3: 640x640 1 animal, 424.9ms
4: 640x640 1 animal, 424.9ms
5: 640x640 1 animal, 424.9ms
6: 640x640 1 animal, 424.9ms
7: 640x640 1 animal, 424.9ms
8: 640x640 1 animal, 424.9ms
9: 640x640 1 animal, 424.9ms
10: 640x640 1 animal, 424.9ms
11: 640x640 (no detections), 424.9ms
12: 640x640 1 animal, 424.9ms
13: 640x640 1 animal, 424.9ms
14: 640x640 1 animal, 424.9ms
15: 640x640 1 animal, 424.9ms
Speed: 2.6ms preprocess, 424.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 17%|███████████████████████▋                                                                                                                | 34/195 [02:46<15:50,  5.91s/it]

0: 384x640 1 animal, 246.5ms
1: 384x640 1 animal, 246.5ms
2: 384x640 1 animal, 246.5ms
3: 384x640 1 animal, 246.5ms
4: 384x640 1 animal, 246.5ms
5: 384x640 1 animal, 246.5ms
6: 384x640 1 animal, 246.5ms
7: 384x640 1 animal, 246.5ms
8: 384x640 1 animal, 246.5ms
9: 384x640 1 animal, 246.5ms
10: 384x640 1 animal, 246.5ms
11: 384x640 2 animals, 246.5ms
12: 384x640 1 animal, 246.5ms
13: 384x640 1 animal, 246.5ms
14: 384x640 1 animal, 246.5ms
15: 384x640 1 animal, 246.5ms
Speed: 2.1ms preprocess, 246.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 18%|████████████████████████▍                                                                                                               | 35/195 [02:51<14:51,  5.57s/it]

0: 384x640 1 animal, 245.7ms
1: 384x640 1 animal, 245.7ms
2: 384x640 1 animal, 245.7ms
3: 384x640 1 animal, 245.7ms
4: 384x640 1 animal, 245.7ms
5: 384x640 1 animal, 245.7ms
6: 384x640 1 animal, 245.7ms
7: 384x640 1 animal, 245.7ms
8: 384x640 1 animal, 245.7ms
9: 384x640 1 animal, 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 1 animal, 245.7ms
12: 384x640 1 animal, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 1 animal, 245.7ms
Speed: 1.9ms preprocess, 245.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 18%|█████████████████████████                                                                                                               | 36/195 [02:55<14:09,  5.34s/it]

0: 384x640 2 animals, 244.2ms
1: 384x640 2 animals, 244.2ms
2: 384x640 1 animal, 244.2ms
3: 384x640 2 animals, 244.2ms
4: 384x640 1 animal, 244.2ms
5: 384x640 1 animal, 244.2ms
6: 384x640 1 animal, 244.2ms
7: 384x640 1 animal, 244.2ms
8: 384x640 1 animal, 244.2ms
9: 384x640 1 animal, 244.2ms
10: 384x640 (no detections), 244.2ms
11: 384x640 (no detections), 244.2ms
12: 384x640 (no detections), 244.2ms
13: 384x640 (no detections), 244.2ms
14: 384x640 1 animal, 244.2ms
15: 384x640 1 animal, 244.2ms
Speed: 1.9ms preprocess, 244.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 19%|█████████████████████████▊                                                                                                              | 37/195 [03:00<13:37,  5.17s/it]

0: 384x640 1 animal, 246.5ms
1: 384x640 1 animal, 246.5ms
2: 384x640 1 animal, 246.5ms
3: 384x640 1 animal, 246.5ms
4: 384x640 1 animal, 246.5ms
5: 384x640 1 animal, 246.5ms
6: 384x640 1 animal, 246.5ms
7: 384x640 1 animal, 246.5ms
8: 384x640 2 animals, 246.5ms
9: 384x640 (no detections), 246.5ms
10: 384x640 (no detections), 246.5ms
11: 384x640 (no detections), 246.5ms
12: 384x640 (no detections), 246.5ms
13: 384x640 1 animal, 246.5ms
14: 384x640 (no detections), 246.5ms
15: 384x640 (no detections), 246.5ms
Speed: 1.9ms preprocess, 246.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 19%|██████████████████████████▌                                                                                                             | 38/195 [03:05<13:14,  5.06s/it]

0: 384x640 (no detections), 244.7ms
1: 384x640 (no detections), 244.7ms
2: 384x640 2 animals, 244.7ms
3: 384x640 1 person, 244.7ms
4: 384x640 1 animal, 244.7ms
5: 384x640 1 animal, 244.7ms
6: 384x640 1 animal, 244.7ms
7: 384x640 1 animal, 244.7ms
8: 384x640 1 animal, 244.7ms
9: 384x640 1 animal, 244.7ms
10: 384x640 1 animal, 244.7ms
11: 384x640 1 animal, 244.7ms
12: 384x640 (no detections), 244.7ms
13: 384x640 (no detections), 244.7ms
14: 384x640 1 animal, 244.7ms
15: 384x640 2 animals, 244.7ms
Speed: 2.1ms preprocess, 244.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 20%|███████████████████████████▏                                                                                                            | 39/195 [03:10<12:51,  4.95s/it]

0: 384x640 1 animal, 245.2ms
1: 384x640 1 animal, 245.2ms
2: 384x640 1 animal, 245.2ms
3: 384x640 1 animal, 245.2ms
4: 384x640 1 animal, 245.2ms
5: 384x640 1 animal, 245.2ms
6: 384x640 (no detections), 245.2ms
7: 384x640 (no detections), 245.2ms
8: 384x640 1 animal, 245.2ms
9: 384x640 2 animals, 245.2ms
10: 384x640 1 animal, 245.2ms
11: 384x640 1 animal, 245.2ms
12: 384x640 1 animal, 245.2ms
13: 384x640 1 animal, 245.2ms
14: 384x640 1 animal, 245.2ms
15: 384x640 1 animal, 245.2ms
Speed: 2.0ms preprocess, 245.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 21%|███████████████████████████▉                                                                                                            | 40/195 [03:14<12:31,  4.85s/it]

0: 384x640 1 animal, 245.9ms
1: 384x640 1 animal, 245.9ms
2: 384x640 1 animal, 245.9ms
3: 384x640 1 animal, 245.9ms
4: 384x640 1 animal, 245.9ms
5: 384x640 1 animal, 245.9ms
6: 384x640 1 animal, 245.9ms
7: 384x640 1 animal, 245.9ms
8: 384x640 1 animal, 245.9ms
9: 384x640 1 animal, 245.9ms
10: 384x640 1 animal, 245.9ms
11: 384x640 1 animal, 245.9ms
12: 384x640 1 animal, 245.9ms
13: 384x640 1 animal, 245.9ms
14: 384x640 1 animal, 245.9ms
15: 384x640 1 animal, 245.9ms
Speed: 1.9ms preprocess, 245.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 21%|████████████████████████████▌                                                                                                           | 41/195 [03:19<12:17,  4.79s/it]

0: 384x640 1 animal, 245.0ms
1: 384x640 1 animal, 245.0ms
2: 384x640 1 animal, 245.0ms
3: 384x640 1 animal, 245.0ms
4: 384x640 1 animal, 245.0ms
5: 384x640 1 animal, 245.0ms
6: 384x640 (no detections), 245.0ms
7: 384x640 (no detections), 245.0ms
8: 384x640 (no detections), 245.0ms
9: 384x640 (no detections), 245.0ms
10: 384x640 (no detections), 245.0ms
11: 384x640 (no detections), 245.0ms
12: 384x640 (no detections), 245.0ms
13: 384x640 (no detections), 245.0ms
14: 384x640 1 animal, 245.0ms
15: 384x640 1 animal, 245.0ms
Speed: 1.9ms preprocess, 245.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 22%|█████████████████████████████▎                                                                                                          | 42/195 [03:24<12:07,  4.75s/it]

0: 384x640 (no detections), 245.4ms
1: 384x640 (no detections), 245.4ms
2: 384x640 (no detections), 245.4ms
3: 384x640 (no detections), 245.4ms
4: 384x640 (no detections), 245.4ms
5: 384x640 (no detections), 245.4ms
6: 384x640 (no detections), 245.4ms
7: 384x640 (no detections), 245.4ms
8: 384x640 2 animals, 245.4ms
9: 384x640 1 animal, 245.4ms
10: 384x640 1 animal, 245.4ms
11: 384x640 1 animal, 245.4ms
12: 384x640 1 animal, 245.4ms
13: 384x640 1 animal, 245.4ms
14: 384x640 1 animal, 245.4ms
15: 384x640 1 animal, 245.4ms
Speed: 2.1ms preprocess, 245.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 22%|█████████████████████████████▉                                                                                                          | 43/195 [03:28<12:02,  4.75s/it]

0: 384x640 2 animals, 244.5ms
1: 384x640 2 animals, 244.5ms
2: 384x640 1 animal, 244.5ms
3: 384x640 1 animal, 244.5ms
4: 384x640 1 animal, 244.5ms
5: 384x640 1 animal, 244.5ms
6: 384x640 1 animal, 244.5ms
7: 384x640 1 animal, 244.5ms
8: 384x640 1 animal, 244.5ms
9: 384x640 1 animal, 244.5ms
10: 384x640 1 animal, 244.5ms
11: 384x640 1 animal, 244.5ms
12: 384x640 1 animal, 244.5ms
13: 384x640 1 animal, 244.5ms
14: 384x640 1 animal, 244.5ms
15: 384x640 1 animal, 244.5ms
Speed: 2.1ms preprocess, 244.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 23%|██████████████████████████████▋                                                                                                         | 44/195 [03:33<11:56,  4.74s/it]

0: 384x640 1 animal, 243.4ms
1: 384x640 1 animal, 243.4ms
2: 384x640 1 animal, 243.4ms
3: 384x640 1 animal, 243.4ms
4: 384x640 1 animal, 243.4ms
5: 384x640 1 animal, 243.4ms
6: 384x640 1 animal, 243.4ms
7: 384x640 1 animal, 243.4ms
8: 384x640 1 animal, 243.4ms
9: 384x640 1 animal, 243.4ms
10: 384x640 1 animal, 243.4ms
11: 384x640 1 animal, 243.4ms
12: 384x640 1 person, 243.4ms
13: 384x640 (no detections), 243.4ms
14: 384x640 (no detections), 243.4ms
15: 384x640 (no detections), 243.4ms
Speed: 1.9ms preprocess, 243.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 23%|███████████████████████████████▍                                                                                                        | 45/195 [03:38<11:51,  4.74s/it]

0: 384x640 1 animal, 241.5ms
1: 384x640 1 animal, 241.5ms
2: 384x640 1 animal, 241.5ms
3: 384x640 2 animals, 241.5ms
4: 384x640 1 animal, 241.5ms
5: 384x640 (no detections), 241.5ms
6: 384x640 (no detections), 241.5ms
7: 384x640 (no detections), 241.5ms
8: 384x640 (no detections), 241.5ms
9: 384x640 (no detections), 241.5ms
10: 384x640 1 animal, 241.5ms
11: 384x640 1 animal, 241.5ms
12: 384x640 (no detections), 241.5ms
13: 384x640 (no detections), 241.5ms
14: 384x640 (no detections), 241.5ms
15: 384x640 (no detections), 241.5ms
Speed: 2.1ms preprocess, 241.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 24%|████████████████████████████████                                                                                                        | 46/195 [03:42<11:27,  4.62s/it]

0: 640x640 (no detections), 424.5ms
1: 640x640 (no detections), 424.5ms
2: 640x640 (no detections), 424.5ms
3: 640x640 (no detections), 424.5ms
4: 640x640 1 animal, 424.5ms
5: 640x640 1 animal, 424.5ms
6: 640x640 1 animal, 424.5ms
7: 640x640 2 animals, 424.5ms
8: 640x640 1 animal, 424.5ms
9: 640x640 2 animals, 424.5ms
10: 640x640 1 animal, 424.5ms
11: 640x640 2 animals, 424.5ms
12: 640x640 2 animals, 424.5ms
13: 640x640 2 animals, 424.5ms
14: 640x640 1 animal, 424.5ms
15: 640x640 2 animals, 424.5ms
Speed: 2.6ms preprocess, 424.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 24%|████████████████████████████████▊                                                                                                       | 47/195 [03:50<13:29,  5.47s/it]

0: 384x640 2 animals, 240.1ms
1: 384x640 2 animals, 240.1ms
2: 384x640 2 animals, 240.1ms
3: 384x640 1 animal, 240.1ms
4: 384x640 1 animal, 240.1ms
5: 384x640 1 animal, 240.1ms
6: 384x640 (no detections), 240.1ms
7: 384x640 (no detections), 240.1ms
8: 384x640 1 animal, 240.1ms
9: 384x640 1 animal, 240.1ms
10: 384x640 1 animal, 240.1ms
11: 384x640 1 animal, 240.1ms
12: 384x640 1 animal, 240.1ms
13: 384x640 1 animal, 240.1ms
14: 384x640 1 animal, 240.1ms
15: 384x640 (no detections), 240.1ms
Speed: 2.0ms preprocess, 240.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 25%|█████████████████████████████████▍                                                                                                      | 48/195 [03:54<12:32,  5.12s/it]

0: 640x640 (no detections), 424.9ms
1: 640x640 (no detections), 424.9ms
2: 640x640 1 animal, 424.9ms
3: 640x640 1 animal, 1 person, 424.9ms
4: 640x640 1 animal, 1 person, 424.9ms
5: 640x640 1 animal, 1 person, 424.9ms
6: 640x640 1 animal, 1 person, 424.9ms
7: 640x640 1 animal, 1 person, 424.9ms
8: 640x640 1 animal, 1 person, 424.9ms
9: 640x640 (no detections), 424.9ms
10: 640x640 (no detections), 424.9ms
11: 640x640 (no detections), 424.9ms
12: 640x640 1 animal, 424.9ms
13: 640x640 2 animals, 424.9ms
14: 640x640 1 animal, 424.9ms
15: 640x640 1 animal, 424.9ms
Speed: 2.6ms preprocess, 424.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 25%|██████████████████████████████████▏                                                                                                     | 49/195 [04:01<14:18,  5.88s/it]

0: 384x640 1 animal, 246.2ms
1: 384x640 1 animal, 246.2ms
2: 384x640 1 animal, 246.2ms
3: 384x640 1 animal, 246.2ms
4: 384x640 1 animal, 246.2ms
5: 384x640 1 animal, 246.2ms
6: 384x640 1 animal, 246.2ms
7: 384x640 1 animal, 246.2ms
8: 384x640 1 animal, 246.2ms
9: 384x640 1 animal, 246.2ms
10: 384x640 1 animal, 246.2ms
11: 384x640 1 animal, 246.2ms
12: 384x640 1 animal, 246.2ms
13: 384x640 1 animal, 246.2ms
14: 384x640 1 animal, 246.2ms
15: 384x640 1 animal, 246.2ms
Speed: 2.1ms preprocess, 246.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 26%|██████████████████████████████████▊                                                                                                     | 50/195 [04:06<13:27,  5.57s/it]

0: 640x640 1 animal, 424.9ms
1: 640x640 1 animal, 424.9ms
2: 640x640 1 animal, 424.9ms
3: 640x640 1 animal, 424.9ms
4: 640x640 1 animal, 424.9ms
5: 640x640 1 animal, 424.9ms
6: 640x640 1 animal, 424.9ms
7: 640x640 1 animal, 424.9ms
8: 640x640 (no detections), 424.9ms
9: 640x640 (no detections), 424.9ms
10: 640x640 1 animal, 424.9ms
11: 640x640 1 animal, 424.9ms
12: 640x640 1 animal, 424.9ms
13: 640x640 1 animal, 424.9ms
14: 640x640 1 animal, 424.9ms
15: 640x640 1 animal, 424.9ms
Speed: 2.8ms preprocess, 424.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 26%|███████████████████████████████████▌                                                                                                    | 51/195 [04:14<14:42,  6.13s/it]

0: 640x640 1 animal, 426.7ms
1: 640x640 1 animal, 426.7ms
2: 640x640 1 animal, 426.7ms
3: 640x640 1 animal, 426.7ms
4: 640x640 1 animal, 426.7ms
5: 640x640 1 animal, 426.7ms
6: 640x640 1 animal, 426.7ms
7: 640x640 1 animal, 426.7ms
8: 640x640 1 animal, 426.7ms
9: 640x640 1 animal, 426.7ms
10: 640x640 1 animal, 426.7ms
11: 640x640 1 animal, 426.7ms
12: 640x640 1 animal, 426.7ms
13: 640x640 1 animal, 426.7ms
14: 640x640 1 animal, 426.7ms
15: 640x640 1 animal, 426.7ms
Speed: 3.0ms preprocess, 426.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 27%|████████████████████████████████████▎                                                                                                   | 52/195 [04:21<15:43,  6.59s/it]

0: 384x640 1 animal, 240.5ms
1: 384x640 (no detections), 240.5ms
2: 384x640 (no detections), 240.5ms
3: 384x640 (no detections), 240.5ms
4: 384x640 (no detections), 240.5ms
5: 384x640 (no detections), 240.5ms
6: 384x640 (no detections), 240.5ms
7: 384x640 (no detections), 240.5ms
8: 384x640 1 animal, 240.5ms
9: 384x640 1 animal, 240.5ms
10: 384x640 1 animal, 240.5ms
11: 384x640 1 animal, 240.5ms
12: 384x640 1 animal, 240.5ms
13: 384x640 1 animal, 240.5ms
14: 384x640 1 animal, 240.5ms
15: 384x640 1 animal, 240.5ms
Speed: 1.9ms preprocess, 240.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 27%|████████████████████████████████████▉                                                                                                   | 53/195 [04:26<13:57,  5.90s/it]

0: 640x640 1 animal, 426.1ms
1: 640x640 1 animal, 426.1ms
2: 640x640 1 animal, 426.1ms
3: 640x640 1 animal, 426.1ms
4: 640x640 1 animal, 426.1ms
5: 640x640 1 animal, 426.1ms
6: 640x640 1 animal, 426.1ms
7: 640x640 1 animal, 426.1ms
8: 640x640 1 animal, 426.1ms
9: 640x640 1 animal, 426.1ms
10: 640x640 1 animal, 426.1ms
11: 640x640 1 animal, 426.1ms
12: 640x640 1 animal, 426.1ms
13: 640x640 1 animal, 426.1ms
14: 640x640 1 animal, 426.1ms
15: 640x640 1 animal, 426.1ms
Speed: 2.8ms preprocess, 426.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 28%|█████████████████████████████████████▋                                                                                                  | 54/195 [04:33<15:02,  6.40s/it]

0: 640x640 1 animal, 427.1ms
1: 640x640 1 animal, 427.1ms
2: 640x640 1 animal, 427.1ms
3: 640x640 1 animal, 427.1ms
4: 640x640 1 animal, 427.1ms
5: 640x640 1 animal, 427.1ms
6: 640x640 1 animal, 427.1ms
7: 640x640 (no detections), 427.1ms
8: 640x640 (no detections), 427.1ms
9: 640x640 1 animal, 427.1ms
10: 640x640 (no detections), 427.1ms
11: 640x640 (no detections), 427.1ms
12: 640x640 (no detections), 427.1ms
13: 640x640 (no detections), 427.1ms
14: 640x640 1 animal, 427.1ms
15: 640x640 1 animal, 427.1ms
Speed: 2.6ms preprocess, 427.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 28%|██████████████████████████████████████▎                                                                                                 | 55/195 [04:41<15:44,  6.75s/it]

0: 384x640 1 animal, 244.3ms
1: 384x640 1 animal, 244.3ms
2: 384x640 1 animal, 244.3ms
3: 384x640 1 animal, 244.3ms
4: 384x640 1 animal, 244.3ms
5: 384x640 1 animal, 244.3ms
6: 384x640 1 animal, 244.3ms
7: 384x640 (no detections), 244.3ms
8: 384x640 (no detections), 244.3ms
9: 384x640 (no detections), 244.3ms
10: 384x640 1 animal, 244.3ms
11: 384x640 1 animal, 244.3ms
12: 384x640 1 animal, 244.3ms
13: 384x640 1 animal, 244.3ms
14: 384x640 1 animal, 244.3ms
15: 384x640 1 animal, 244.3ms
Speed: 2.1ms preprocess, 244.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 29%|███████████████████████████████████████                                                                                                 | 56/195 [04:46<14:18,  6.18s/it]

0: 640x640 1 animal, 425.5ms
1: 640x640 1 animal, 425.5ms
2: 640x640 1 animal, 425.5ms
3: 640x640 1 animal, 425.5ms
4: 640x640 3 animals, 425.5ms
5: 640x640 4 animals, 425.5ms
6: 640x640 3 animals, 425.5ms
7: 640x640 3 animals, 425.5ms
8: 640x640 3 animals, 425.5ms
9: 640x640 4 animals, 425.5ms
10: 640x640 4 animals, 425.5ms
11: 640x640 5 animals, 425.5ms
12: 640x640 3 animals, 425.5ms
13: 640x640 4 animals, 425.5ms
14: 640x640 1 animal, 425.5ms
15: 640x640 1 animal, 425.5ms
Speed: 2.9ms preprocess, 425.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 29%|███████████████████████████████████████▊                                                                                                | 57/195 [04:53<15:13,  6.62s/it]

0: 384x640 1 animal, 240.8ms
1: 384x640 (no detections), 240.8ms
2: 384x640 (no detections), 240.8ms
3: 384x640 (no detections), 240.8ms
4: 384x640 (no detections), 240.8ms
5: 384x640 (no detections), 240.8ms
6: 384x640 (no detections), 240.8ms
7: 384x640 (no detections), 240.8ms
8: 384x640 (no detections), 240.8ms
9: 384x640 (no detections), 240.8ms
10: 384x640 (no detections), 240.8ms
11: 384x640 (no detections), 240.8ms
12: 384x640 (no detections), 240.8ms
13: 384x640 (no detections), 240.8ms
14: 384x640 1 animal, 240.8ms
15: 384x640 1 animal, 240.8ms
Speed: 1.8ms preprocess, 240.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 30%|████████████████████████████████████████▍                                                                                               | 58/195 [04:58<13:28,  5.90s/it]

0: 640x640 1 animal, 426.3ms
1: 640x640 1 animal, 426.3ms
2: 640x640 1 animal, 426.3ms
3: 640x640 1 animal, 426.3ms
4: 640x640 1 animal, 426.3ms
5: 640x640 1 animal, 426.3ms
6: 640x640 1 animal, 426.3ms
7: 640x640 1 animal, 426.3ms
8: 640x640 1 animal, 426.3ms
9: 640x640 (no detections), 426.3ms
10: 640x640 (no detections), 426.3ms
11: 640x640 (no detections), 426.3ms
12: 640x640 (no detections), 426.3ms
13: 640x640 (no detections), 426.3ms
14: 640x640 (no detections), 426.3ms
15: 640x640 (no detections), 426.3ms
Speed: 2.8ms preprocess, 426.3ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 30%|█████████████████████████████████████████▏                                                                                              | 59/195 [05:05<14:29,  6.39s/it]

0: 384x640 (no detections), 241.0ms
1: 384x640 (no detections), 241.0ms
2: 384x640 (no detections), 241.0ms
3: 384x640 (no detections), 241.0ms
4: 384x640 (no detections), 241.0ms
5: 384x640 (no detections), 241.0ms
6: 384x640 1 animal, 241.0ms
7: 384x640 1 animal, 241.0ms
8: 384x640 1 animal, 1 person, 241.0ms
9: 384x640 (no detections), 241.0ms
10: 384x640 (no detections), 241.0ms
11: 384x640 (no detections), 241.0ms
12: 384x640 (no detections), 241.0ms
13: 384x640 (no detections), 241.0ms
14: 384x640 (no detections), 241.0ms
15: 384x640 (no detections), 241.0ms
Speed: 1.9ms preprocess, 241.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 31%|█████████████████████████████████████████▊                                                                                              | 60/195 [05:09<12:55,  5.75s/it]

0: 384x640 1 animal, 245.4ms
1: 384x640 2 animals, 245.4ms
2: 384x640 1 animal, 245.4ms
3: 384x640 1 animal, 245.4ms
4: 384x640 1 animal, 245.4ms
5: 384x640 1 animal, 245.4ms
6: 384x640 1 animal, 245.4ms
7: 384x640 1 animal, 245.4ms
8: 384x640 1 animal, 245.4ms
9: 384x640 1 animal, 245.4ms
10: 384x640 1 animal, 245.4ms
11: 384x640 1 animal, 245.4ms
12: 384x640 1 animal, 245.4ms
13: 384x640 1 animal, 245.4ms
14: 384x640 1 animal, 245.4ms
15: 384x640 1 animal, 245.4ms
Speed: 1.9ms preprocess, 245.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 31%|██████████████████████████████████████████▌                                                                                             | 61/195 [05:14<12:14,  5.48s/it]

0: 640x640 1 animal, 422.7ms
1: 640x640 1 animal, 422.7ms
2: 640x640 1 animal, 422.7ms
3: 640x640 1 animal, 422.7ms
4: 640x640 1 animal, 422.7ms
5: 640x640 1 animal, 422.7ms
6: 640x640 1 animal, 422.7ms
7: 640x640 1 animal, 422.7ms
8: 640x640 1 animal, 422.7ms
9: 640x640 1 animal, 422.7ms
10: 640x640 1 animal, 422.7ms
11: 640x640 1 animal, 422.7ms
12: 640x640 1 animal, 422.7ms
13: 640x640 1 animal, 422.7ms
14: 640x640 1 animal, 422.7ms
15: 640x640 1 animal, 422.7ms
Speed: 2.7ms preprocess, 422.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 32%|███████████████████████████████████████████▏                                                                                            | 62/195 [05:22<13:23,  6.04s/it]

0: 640x640 1 animal, 427.3ms
1: 640x640 1 animal, 427.3ms
2: 640x640 2 animals, 427.3ms
3: 640x640 2 animals, 427.3ms
4: 640x640 2 animals, 427.3ms
5: 640x640 1 animal, 427.3ms
6: 640x640 1 animal, 427.3ms
7: 640x640 1 animal, 427.3ms
8: 640x640 1 animal, 427.3ms
9: 640x640 1 animal, 427.3ms
10: 640x640 1 animal, 427.3ms
11: 640x640 1 animal, 427.3ms
12: 640x640 3 animals, 427.3ms
13: 640x640 1 animal, 427.3ms
14: 640x640 3 animals, 427.3ms
15: 640x640 2 animals, 427.3ms
Speed: 2.9ms preprocess, 427.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 32%|███████████████████████████████████████████▉                                                                                            | 63/195 [05:29<14:16,  6.49s/it]

0: 384x640 2 animals, 237.6ms
1: 384x640 2 animals, 237.6ms
2: 384x640 1 animal, 237.6ms
3: 384x640 2 animals, 237.6ms
4: 384x640 1 animal, 237.6ms
5: 384x640 1 animal, 237.6ms
6: 384x640 1 animal, 237.6ms
7: 384x640 1 animal, 237.6ms
8: 384x640 2 animals, 237.6ms
9: 384x640 2 animals, 237.6ms
10: 384x640 1 animal, 237.6ms
11: 384x640 1 animal, 237.6ms
12: 384x640 2 animals, 237.6ms
13: 384x640 2 animals, 237.6ms
14: 384x640 2 animals, 237.6ms
15: 384x640 1 animal, 237.6ms
Speed: 2.1ms preprocess, 237.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 33%|████████████████████████████████████████████▋                                                                                           | 64/195 [05:34<13:00,  5.96s/it]

0: 384x640 1 animal, 243.5ms
1: 384x640 1 animal, 243.5ms
2: 384x640 1 animal, 243.5ms
3: 384x640 1 animal, 243.5ms
4: 384x640 1 animal, 243.5ms
5: 384x640 1 animal, 243.5ms
6: 384x640 1 animal, 243.5ms
7: 384x640 1 animal, 243.5ms
8: 384x640 1 animal, 243.5ms
9: 384x640 1 animal, 243.5ms
10: 384x640 1 animal, 243.5ms
11: 384x640 1 animal, 243.5ms
12: 384x640 1 animal, 243.5ms
13: 384x640 1 animal, 243.5ms
14: 384x640 1 animal, 243.5ms
15: 384x640 1 animal, 243.5ms
Speed: 1.9ms preprocess, 243.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 33%|█████████████████████████████████████████████▎                                                                                          | 65/195 [05:39<12:07,  5.60s/it]

0: 640x640 2 animals, 425.1ms
1: 640x640 1 animal, 425.1ms
2: 640x640 1 animal, 425.1ms
3: 640x640 2 animals, 425.1ms
4: 640x640 1 animal, 425.1ms
5: 640x640 3 animals, 425.1ms
6: 640x640 2 animals, 425.1ms
7: 640x640 3 animals, 425.1ms
8: 640x640 2 animals, 425.1ms
9: 640x640 3 animals, 425.1ms
10: 640x640 1 animal, 425.1ms
11: 640x640 2 animals, 425.1ms
12: 640x640 1 animal, 425.1ms
13: 640x640 2 animals, 425.1ms
14: 640x640 2 animals, 425.1ms
15: 640x640 1 animal, 425.1ms
Speed: 2.5ms preprocess, 425.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 34%|██████████████████████████████████████████████                                                                                          | 66/195 [05:46<13:13,  6.15s/it]

0: 384x640 1 animal, 238.7ms
1: 384x640 1 animal, 238.7ms
2: 384x640 1 animal, 238.7ms
3: 384x640 (no detections), 238.7ms
4: 384x640 1 animal, 238.7ms
5: 384x640 1 animal, 238.7ms
6: 384x640 1 animal, 238.7ms
7: 384x640 1 animal, 238.7ms
8: 384x640 1 animal, 238.7ms
9: 384x640 1 animal, 238.7ms
10: 384x640 (no detections), 238.7ms
11: 384x640 (no detections), 238.7ms
12: 384x640 (no detections), 238.7ms
13: 384x640 (no detections), 238.7ms
14: 384x640 1 animal, 238.7ms
15: 384x640 1 animal, 238.7ms
Speed: 1.8ms preprocess, 238.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 34%|██████████████████████████████████████████████▋                                                                                         | 67/195 [05:50<11:54,  5.58s/it]

0: 640x640 1 animal, 421.8ms
1: 640x640 1 animal, 421.8ms
2: 640x640 1 animal, 421.8ms
3: 640x640 1 animal, 421.8ms
4: 640x640 1 animal, 421.8ms
5: 640x640 1 animal, 421.8ms
6: 640x640 1 animal, 421.8ms
7: 640x640 1 animal, 421.8ms
8: 640x640 1 animal, 421.8ms
9: 640x640 1 animal, 421.8ms
10: 640x640 1 animal, 421.8ms
11: 640x640 1 animal, 421.8ms
12: 640x640 1 animal, 421.8ms
13: 640x640 1 animal, 421.8ms
14: 640x640 1 animal, 421.8ms
15: 640x640 1 animal, 421.8ms
Speed: 2.7ms preprocess, 421.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 35%|███████████████████████████████████████████████▍                                                                                        | 68/195 [05:58<13:00,  6.14s/it]

0: 640x640 (no detections), 424.6ms
1: 640x640 (no detections), 424.6ms
2: 640x640 1 animal, 424.6ms
3: 640x640 1 animal, 424.6ms
4: 640x640 1 animal, 424.6ms
5: 640x640 1 animal, 424.6ms
6: 640x640 1 animal, 424.6ms
7: 640x640 1 animal, 424.6ms
8: 640x640 1 animal, 424.6ms
9: 640x640 1 animal, 424.6ms
10: 640x640 1 animal, 424.6ms
11: 640x640 1 animal, 424.6ms
12: 640x640 1 animal, 424.6ms
13: 640x640 1 animal, 424.6ms
14: 640x640 1 animal, 424.6ms
15: 640x640 1 animal, 424.6ms
Speed: 2.9ms preprocess, 424.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 35%|████████████████████████████████████████████████                                                                                        | 69/195 [06:05<13:42,  6.53s/it]

0: 640x640 1 animal, 424.4ms
1: 640x640 1 animal, 424.4ms
2: 640x640 1 animal, 424.4ms
3: 640x640 1 animal, 424.4ms
4: 640x640 1 animal, 424.4ms
5: 640x640 1 animal, 424.4ms
6: 640x640 1 animal, 424.4ms
7: 640x640 1 animal, 424.4ms
8: 640x640 1 animal, 424.4ms
9: 640x640 1 animal, 424.4ms
10: 640x640 2 animals, 424.4ms
11: 640x640 2 animals, 424.4ms
12: 640x640 1 animal, 424.4ms
13: 640x640 1 animal, 424.4ms
14: 640x640 1 animal, 424.4ms
15: 640x640 (no detections), 424.4ms
Speed: 2.6ms preprocess, 424.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 36%|████████████████████████████████████████████████▊                                                                                       | 70/195 [06:13<14:10,  6.80s/it]

0: 640x640 1 animal, 422.0ms
1: 640x640 1 animal, 422.0ms
2: 640x640 1 animal, 422.0ms
3: 640x640 1 animal, 422.0ms
4: 640x640 1 animal, 422.0ms
5: 640x640 1 animal, 422.0ms
6: 640x640 1 animal, 422.0ms
7: 640x640 1 animal, 422.0ms
8: 640x640 1 animal, 422.0ms
9: 640x640 1 animal, 422.0ms
10: 640x640 1 animal, 422.0ms
11: 640x640 1 animal, 422.0ms
12: 640x640 1 animal, 422.0ms
13: 640x640 1 animal, 422.0ms
14: 640x640 1 animal, 422.0ms
15: 640x640 1 animal, 422.0ms
Speed: 2.6ms preprocess, 422.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 36%|█████████████████████████████████████████████████▌                                                                                      | 71/195 [06:20<14:30,  7.02s/it]

0: 640x640 1 animal, 422.9ms
1: 640x640 1 animal, 422.9ms
2: 640x640 1 animal, 422.9ms
3: 640x640 1 animal, 422.9ms
4: 640x640 1 animal, 422.9ms
5: 640x640 1 animal, 422.9ms
6: 640x640 1 animal, 422.9ms
7: 640x640 1 animal, 422.9ms
8: 640x640 1 animal, 422.9ms
9: 640x640 1 animal, 422.9ms
10: 640x640 1 animal, 422.9ms
11: 640x640 1 animal, 422.9ms
12: 640x640 1 animal, 422.9ms
13: 640x640 1 animal, 422.9ms
14: 640x640 2 animals, 422.9ms
15: 640x640 2 animals, 422.9ms
Speed: 2.6ms preprocess, 422.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 37%|██████████████████████████████████████████████████▏                                                                                     | 72/195 [06:28<14:44,  7.19s/it]

0: 640x640 1 animal, 424.7ms
1: 640x640 1 animal, 424.7ms
2: 640x640 1 animal, 424.7ms
3: 640x640 1 animal, 424.7ms
4: 640x640 1 animal, 424.7ms
5: 640x640 1 animal, 424.7ms
6: 640x640 1 animal, 424.7ms
7: 640x640 1 animal, 424.7ms
8: 640x640 1 animal, 424.7ms
9: 640x640 1 animal, 424.7ms
10: 640x640 1 animal, 424.7ms
11: 640x640 1 animal, 424.7ms
12: 640x640 1 animal, 424.7ms
13: 640x640 1 animal, 424.7ms
14: 640x640 1 animal, 424.7ms
15: 640x640 1 animal, 424.7ms
Speed: 2.9ms preprocess, 424.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 37%|██████████████████████████████████████████████████▉                                                                                     | 73/195 [06:35<14:49,  7.29s/it]

0: 640x640 1 animal, 424.9ms
1: 640x640 1 animal, 424.9ms
2: 640x640 1 animal, 424.9ms
3: 640x640 1 animal, 424.9ms
4: 640x640 1 animal, 424.9ms
5: 640x640 1 animal, 424.9ms
6: 640x640 1 animal, 424.9ms
7: 640x640 1 animal, 424.9ms
8: 640x640 1 animal, 424.9ms
9: 640x640 1 animal, 424.9ms
10: 640x640 1 animal, 424.9ms
11: 640x640 1 animal, 424.9ms
12: 640x640 1 animal, 424.9ms
13: 640x640 1 animal, 424.9ms
14: 640x640 1 animal, 424.9ms
15: 640x640 1 animal, 424.9ms
Speed: 2.5ms preprocess, 424.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 38%|███████████████████████████████████████████████████▌                                                                                    | 74/195 [06:43<14:44,  7.31s/it]

0: 640x640 1 animal, 424.4ms
1: 640x640 1 animal, 424.4ms
2: 640x640 1 animal, 424.4ms
3: 640x640 (no detections), 424.4ms
4: 640x640 (no detections), 424.4ms
5: 640x640 (no detections), 424.4ms
6: 640x640 1 animal, 424.4ms
7: 640x640 1 animal, 424.4ms
8: 640x640 1 animal, 424.4ms
9: 640x640 1 animal, 424.4ms
10: 640x640 1 animal, 424.4ms
11: 640x640 1 animal, 424.4ms
12: 640x640 1 animal, 424.4ms
13: 640x640 (no detections), 424.4ms
14: 640x640 (no detections), 424.4ms
15: 640x640 (no detections), 424.4ms
Speed: 2.5ms preprocess, 424.4ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 38%|████████████████████████████████████████████████████▎                                                                                   | 75/195 [06:50<14:41,  7.34s/it]

0: 384x640 1 animal, 244.6ms
1: 384x640 1 animal, 244.6ms
2: 384x640 1 animal, 244.6ms
3: 384x640 3 animals, 244.6ms
4: 384x640 2 animals, 244.6ms
5: 384x640 2 animals, 244.6ms
6: 384x640 3 animals, 244.6ms
7: 384x640 4 animals, 244.6ms
8: 384x640 2 animals, 244.6ms
9: 384x640 1 animal, 244.6ms
10: 384x640 1 animal, 244.6ms
11: 384x640 1 animal, 244.6ms
12: 384x640 1 animal, 244.6ms
13: 384x640 1 animal, 244.6ms
14: 384x640 1 animal, 244.6ms
15: 384x640 1 animal, 244.6ms
Speed: 1.9ms preprocess, 244.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 39%|█████████████████████████████████████████████████████                                                                                   | 76/195 [06:55<13:04,  6.59s/it]

0: 640x640 1 animal, 424.6ms
1: 640x640 1 animal, 424.6ms
2: 640x640 1 animal, 424.6ms
3: 640x640 1 animal, 424.6ms
4: 640x640 1 animal, 424.6ms
5: 640x640 1 animal, 424.6ms
6: 640x640 1 animal, 424.6ms
7: 640x640 3 animals, 424.6ms
8: 640x640 2 animals, 424.6ms
9: 640x640 2 animals, 424.6ms
10: 640x640 3 animals, 424.6ms
11: 640x640 4 animals, 424.6ms
12: 640x640 2 animals, 424.6ms
13: 640x640 1 animal, 424.6ms
14: 640x640 1 animal, 424.6ms
15: 640x640 1 animal, 424.6ms
Speed: 2.9ms preprocess, 424.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 39%|█████████████████████████████████████████████████████▋                                                                                  | 77/195 [07:03<13:36,  6.92s/it]

0: 640x640 1 animal, 426.5ms
1: 640x640 1 animal, 426.5ms
2: 640x640 1 animal, 426.5ms
3: 640x640 1 animal, 426.5ms
4: 640x640 1 animal, 426.5ms
5: 640x640 1 animal, 426.5ms
6: 640x640 1 animal, 426.5ms
7: 640x640 1 animal, 426.5ms
8: 640x640 2 animals, 426.5ms
9: 640x640 1 animal, 426.5ms
10: 640x640 2 animals, 426.5ms
11: 640x640 2 animals, 426.5ms
12: 640x640 1 animal, 426.5ms
13: 640x640 1 animal, 426.5ms
14: 640x640 2 animals, 426.5ms
15: 640x640 2 animals, 426.5ms
Speed: 3.0ms preprocess, 426.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 40%|██████████████████████████████████████████████████████▍                                                                                 | 78/195 [07:10<13:57,  7.16s/it]

0: 640x640 2 animals, 426.9ms
1: 640x640 1 animal, 426.9ms
2: 640x640 1 animal, 426.9ms
3: 640x640 1 animal, 426.9ms
4: 640x640 1 animal, 426.9ms
5: 640x640 1 animal, 426.9ms
6: 640x640 (no detections), 426.9ms
7: 640x640 (no detections), 426.9ms
8: 640x640 (no detections), 426.9ms
9: 640x640 (no detections), 426.9ms
10: 640x640 (no detections), 426.9ms
11: 640x640 (no detections), 426.9ms
12: 640x640 1 animal, 426.9ms
13: 640x640 1 animal, 426.9ms
14: 640x640 1 animal, 426.9ms
15: 640x640 1 animal, 426.9ms
Speed: 2.8ms preprocess, 426.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 41%|███████████████████████████████████████████████████████                                                                                 | 79/195 [07:18<14:01,  7.25s/it]

0: 640x640 1 animal, 425.3ms
1: 640x640 1 animal, 425.3ms
2: 640x640 1 animal, 425.3ms
3: 640x640 1 animal, 425.3ms
4: 640x640 1 animal, 425.3ms
5: 640x640 1 animal, 425.3ms
6: 640x640 1 animal, 425.3ms
7: 640x640 1 animal, 425.3ms
8: 640x640 1 animal, 425.3ms
9: 640x640 1 animal, 425.3ms
10: 640x640 1 animal, 425.3ms
11: 640x640 (no detections), 425.3ms
12: 640x640 (no detections), 425.3ms
13: 640x640 (no detections), 425.3ms
14: 640x640 (no detections), 425.3ms
15: 640x640 (no detections), 425.3ms
Speed: 2.5ms preprocess, 425.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 41%|███████████████████████████████████████████████████████▊                                                                                | 80/195 [07:25<14:00,  7.30s/it]

0: 384x640 1 animal, 244.3ms
1: 384x640 1 animal, 244.3ms
2: 384x640 1 animal, 244.3ms
3: 384x640 1 animal, 244.3ms
4: 384x640 1 animal, 244.3ms
5: 384x640 1 animal, 244.3ms
6: 384x640 (no detections), 244.3ms
7: 384x640 (no detections), 244.3ms
8: 384x640 (no detections), 244.3ms
9: 384x640 (no detections), 244.3ms
10: 384x640 1 animal, 244.3ms
11: 384x640 1 animal, 244.3ms
12: 384x640 1 animal, 244.3ms
13: 384x640 1 animal, 244.3ms
14: 384x640 1 animal, 244.3ms
15: 384x640 2 animals, 244.3ms
Speed: 1.9ms preprocess, 244.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 42%|████████████████████████████████████████████████████████▍                                                                               | 81/195 [07:30<12:23,  6.52s/it]

0: 640x640 1 animal, 420.9ms
1: 640x640 1 animal, 420.9ms
2: 640x640 1 animal, 420.9ms
3: 640x640 (no detections), 420.9ms
4: 640x640 1 animal, 420.9ms
5: 640x640 1 animal, 420.9ms
6: 640x640 1 animal, 420.9ms
7: 640x640 1 animal, 420.9ms
8: 640x640 (no detections), 420.9ms
9: 640x640 (no detections), 420.9ms
10: 640x640 (no detections), 420.9ms
11: 640x640 (no detections), 420.9ms
12: 640x640 (no detections), 420.9ms
13: 640x640 (no detections), 420.9ms
14: 640x640 1 animal, 420.9ms
15: 640x640 1 animal, 420.9ms
Speed: 2.7ms preprocess, 420.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 42%|█████████████████████████████████████████████████████████▏                                                                              | 82/195 [07:37<12:43,  6.76s/it]

0: 384x640 1 animal, 240.7ms
1: 384x640 1 animal, 240.7ms
2: 384x640 1 animal, 240.7ms
3: 384x640 (no detections), 240.7ms
4: 384x640 (no detections), 240.7ms
5: 384x640 (no detections), 240.7ms
6: 384x640 (no detections), 240.7ms
7: 384x640 (no detections), 240.7ms
8: 384x640 1 animal, 240.7ms
9: 384x640 1 animal, 240.7ms
10: 384x640 1 animal, 240.7ms
11: 384x640 1 animal, 240.7ms
12: 384x640 1 animal, 240.7ms
13: 384x640 (no detections), 240.7ms
14: 384x640 1 animal, 240.7ms
15: 384x640 (no detections), 240.7ms
Speed: 2.0ms preprocess, 240.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 43%|█████████████████████████████████████████████████████████▉                                                                              | 83/195 [07:41<11:14,  6.02s/it]

0: 384x640 (no detections), 240.5ms
1: 384x640 (no detections), 240.5ms
2: 384x640 1 animal, 240.5ms
3: 384x640 1 animal, 240.5ms
4: 384x640 1 animal, 240.5ms
5: 384x640 1 animal, 240.5ms
6: 384x640 1 animal, 240.5ms
7: 384x640 (no detections), 240.5ms
8: 384x640 (no detections), 240.5ms
9: 384x640 1 animal, 240.5ms
10: 384x640 (no detections), 240.5ms
11: 384x640 (no detections), 240.5ms
12: 384x640 1 animal, 240.5ms
13: 384x640 1 animal, 240.5ms
14: 384x640 1 animal, 240.5ms
15: 384x640 1 animal, 240.5ms
Speed: 1.8ms preprocess, 240.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 43%|██████████████████████████████████████████████████████████▌                                                                             | 84/195 [07:46<10:10,  5.50s/it]

0: 640x640 1 animal, 424.4ms
1: 640x640 2 animals, 424.4ms
2: 640x640 2 animals, 424.4ms
3: 640x640 1 animal, 424.4ms
4: 640x640 (no detections), 424.4ms
5: 640x640 1 animal, 424.4ms
6: 640x640 1 animal, 424.4ms
7: 640x640 1 animal, 424.4ms
8: 640x640 1 animal, 424.4ms
9: 640x640 1 animal, 424.4ms
10: 640x640 1 animal, 424.4ms
11: 640x640 1 animal, 424.4ms
12: 640x640 1 animal, 424.4ms
13: 640x640 1 animal, 424.4ms
14: 640x640 1 animal, 424.4ms
15: 640x640 1 animal, 424.4ms
Speed: 2.8ms preprocess, 424.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 44%|███████████████████████████████████████████████████████████▎                                                                            | 85/195 [07:53<11:12,  6.12s/it]

0: 384x640 2 animals, 240.2ms
1: 384x640 1 animal, 240.2ms
2: 384x640 1 animal, 240.2ms
3: 384x640 1 animal, 240.2ms
4: 384x640 1 animal, 240.2ms
5: 384x640 1 animal, 240.2ms
6: 384x640 1 animal, 240.2ms
7: 384x640 1 animal, 240.2ms
8: 384x640 1 animal, 240.2ms
9: 384x640 1 animal, 240.2ms
10: 384x640 1 animal, 240.2ms
11: 384x640 1 animal, 240.2ms
12: 384x640 1 animal, 240.2ms
13: 384x640 1 animal, 240.2ms
14: 384x640 1 animal, 240.2ms
15: 384x640 1 animal, 240.2ms
Speed: 1.8ms preprocess, 240.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 44%|███████████████████████████████████████████████████████████▉                                                                            | 86/195 [07:58<10:06,  5.57s/it]

0: 384x640 1 animal, 240.5ms
1: 384x640 1 animal, 240.5ms
2: 384x640 (no detections), 240.5ms
3: 384x640 (no detections), 240.5ms
4: 384x640 1 animal, 240.5ms
5: 384x640 1 animal, 240.5ms
6: 384x640 1 animal, 240.5ms
7: 384x640 1 animal, 240.5ms
8: 384x640 1 animal, 240.5ms
9: 384x640 (no detections), 240.5ms
10: 384x640 (no detections), 240.5ms
11: 384x640 (no detections), 240.5ms
12: 384x640 (no detections), 240.5ms
13: 384x640 (no detections), 240.5ms
14: 384x640 1 animal, 240.5ms
15: 384x640 1 animal, 240.5ms
Speed: 1.8ms preprocess, 240.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 45%|████████████████████████████████████████████████████████████▋                                                                           | 87/195 [08:02<09:19,  5.18s/it]

0: 384x640 1 animal, 242.1ms
1: 384x640 1 animal, 242.1ms
2: 384x640 1 animal, 242.1ms
3: 384x640 1 animal, 242.1ms
4: 384x640 (no detections), 242.1ms
5: 384x640 (no detections), 242.1ms
6: 384x640 (no detections), 242.1ms
7: 384x640 (no detections), 242.1ms
8: 384x640 1 animal, 242.1ms
9: 384x640 1 animal, 242.1ms
10: 384x640 1 animal, 242.1ms
11: 384x640 1 animal, 242.1ms
12: 384x640 1 animal, 242.1ms
13: 384x640 1 animal, 242.1ms
14: 384x640 1 animal, 242.1ms
15: 384x640 1 animal, 242.1ms
Speed: 1.9ms preprocess, 242.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 45%|█████████████████████████████████████████████████████████████▎                                                                          | 88/195 [08:06<08:46,  4.93s/it]

0: 640x640 1 animal, 408.0ms
1: 640x640 1 animal, 408.0ms
2: 640x640 1 animal, 408.0ms
3: 640x640 1 animal, 408.0ms
4: 640x640 1 animal, 408.0ms
5: 640x640 1 animal, 408.0ms
6: 640x640 1 animal, 408.0ms
7: 640x640 1 animal, 408.0ms
8: 640x640 1 animal, 408.0ms
9: 640x640 1 animal, 408.0ms
10: 640x640 1 animal, 408.0ms
11: 640x640 1 animal, 408.0ms
12: 640x640 1 animal, 408.0ms
13: 640x640 1 animal, 408.0ms
14: 640x640 1 animal, 408.0ms
15: 640x640 1 animal, 408.0ms
Speed: 2.7ms preprocess, 408.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 46%|██████████████████████████████████████████████████████████████                                                                          | 89/195 [08:13<09:57,  5.63s/it]

0: 640x640 1 animal, 410.3ms
1: 640x640 (no detections), 410.3ms
2: 640x640 (no detections), 410.3ms
3: 640x640 (no detections), 410.3ms
4: 640x640 (no detections), 410.3ms
5: 640x640 (no detections), 410.3ms
6: 640x640 1 animal, 410.3ms
7: 640x640 1 animal, 410.3ms
8: 640x640 (no detections), 410.3ms
9: 640x640 (no detections), 410.3ms
10: 640x640 (no detections), 410.3ms
11: 640x640 (no detections), 410.3ms
12: 640x640 (no detections), 410.3ms
13: 640x640 (no detections), 410.3ms
14: 640x640 (no detections), 410.3ms
15: 640x640 (no detections), 410.3ms
Speed: 2.7ms preprocess, 410.3ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 46%|██████████████████████████████████████████████████████████████▊                                                                         | 90/195 [08:21<10:43,  6.13s/it]

0: 640x640 1 animal, 409.5ms
1: 640x640 1 animal, 409.5ms
2: 640x640 1 animal, 409.5ms
3: 640x640 1 animal, 409.5ms
4: 640x640 1 animal, 409.5ms
5: 640x640 1 animal, 409.5ms
6: 640x640 1 animal, 409.5ms
7: 640x640 (no detections), 409.5ms
8: 640x640 (no detections), 409.5ms
9: 640x640 (no detections), 409.5ms
10: 640x640 2 animals, 409.5ms
11: 640x640 1 animal, 409.5ms
12: 640x640 1 animal, 409.5ms
13: 640x640 1 animal, 409.5ms
14: 640x640 1 animal, 409.5ms
15: 640x640 1 animal, 409.5ms
Speed: 2.6ms preprocess, 409.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 47%|███████████████████████████████████████████████████████████████▍                                                                        | 91/195 [08:28<11:09,  6.44s/it]

0: 640x640 1 animal, 410.0ms
1: 640x640 1 animal, 410.0ms
2: 640x640 1 animal, 410.0ms
3: 640x640 1 animal, 410.0ms
4: 640x640 1 animal, 410.0ms
5: 640x640 1 animal, 410.0ms
6: 640x640 1 animal, 410.0ms
7: 640x640 1 animal, 410.0ms
8: 640x640 1 animal, 410.0ms
9: 640x640 1 animal, 410.0ms
10: 640x640 1 animal, 410.0ms
11: 640x640 1 animal, 410.0ms
12: 640x640 1 animal, 410.0ms
13: 640x640 1 animal, 410.0ms
14: 640x640 1 animal, 410.0ms
15: 640x640 1 animal, 410.0ms
Speed: 2.6ms preprocess, 410.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 47%|████████████████████████████████████████████████████████████████▏                                                                       | 92/195 [08:35<11:31,  6.72s/it]

0: 384x640 1 animal, 235.6ms
1: 384x640 1 animal, 235.6ms
2: 384x640 1 animal, 235.6ms
3: 384x640 1 animal, 235.6ms
4: 384x640 (no detections), 235.6ms
5: 384x640 (no detections), 235.6ms
6: 384x640 (no detections), 235.6ms
7: 384x640 (no detections), 235.6ms
8: 384x640 1 animal, 235.6ms
9: 384x640 1 animal, 235.6ms
10: 384x640 1 animal, 235.6ms
11: 384x640 1 animal, 235.6ms
12: 384x640 1 animal, 235.6ms
13: 384x640 (no detections), 235.6ms
14: 384x640 (no detections), 235.6ms
15: 384x640 (no detections), 235.6ms
Speed: 1.8ms preprocess, 235.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 48%|████████████████████████████████████████████████████████████████▊                                                                       | 93/195 [08:39<10:07,  5.96s/it]

0: 384x640 (no detections), 238.8ms
1: 384x640 (no detections), 238.8ms
2: 384x640 1 animal, 238.8ms
3: 384x640 1 animal, 238.8ms
4: 384x640 1 animal, 238.8ms
5: 384x640 3 animals, 238.8ms
6: 384x640 2 animals, 238.8ms
7: 384x640 2 animals, 238.8ms
8: 384x640 2 animals, 238.8ms
9: 384x640 2 animals, 238.8ms
10: 384x640 2 animals, 238.8ms
11: 384x640 1 animal, 238.8ms
12: 384x640 1 animal, 238.8ms
13: 384x640 1 animal, 238.8ms
14: 384x640 1 animal, 238.8ms
15: 384x640 1 animal, 238.8ms
Speed: 1.8ms preprocess, 238.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 48%|█████████████████████████████████████████████████████████████████▌                                                                      | 94/195 [08:44<09:10,  5.45s/it]

0: 640x640 1 animal, 429.0ms
1: 640x640 1 animal, 429.0ms
2: 640x640 1 animal, 429.0ms
3: 640x640 1 animal, 429.0ms
4: 640x640 1 animal, 429.0ms
5: 640x640 1 animal, 429.0ms
6: 640x640 2 animals, 429.0ms
7: 640x640 1 animal, 429.0ms
8: 640x640 1 animal, 429.0ms
9: 640x640 1 animal, 429.0ms
10: 640x640 1 animal, 429.0ms
11: 640x640 1 animal, 429.0ms
12: 640x640 1 animal, 429.0ms
13: 640x640 1 animal, 429.0ms
14: 640x640 1 animal, 429.0ms
15: 640x640 1 animal, 429.0ms
Speed: 2.9ms preprocess, 429.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 49%|██████████████████████████████████████████████████████████████████▎                                                                     | 95/195 [08:51<10:10,  6.10s/it]

0: 640x640 1 animal, 425.0ms
1: 640x640 1 animal, 425.0ms
2: 640x640 1 animal, 425.0ms
3: 640x640 (no detections), 425.0ms
4: 640x640 1 animal, 425.0ms
5: 640x640 1 animal, 425.0ms
6: 640x640 1 animal, 425.0ms
7: 640x640 1 animal, 425.0ms
8: 640x640 1 animal, 425.0ms
9: 640x640 1 animal, 425.0ms
10: 640x640 2 animals, 425.0ms
11: 640x640 2 animals, 425.0ms
12: 640x640 1 animal, 425.0ms
13: 640x640 1 animal, 425.0ms
14: 640x640 4 animals, 425.0ms
15: 640x640 3 animals, 425.0ms
Speed: 2.6ms preprocess, 425.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 49%|██████████████████████████████████████████████████████████████████▉                                                                     | 96/195 [08:59<10:43,  6.50s/it]

0: 640x640 4 animals, 427.4ms
1: 640x640 4 animals, 427.4ms
2: 640x640 3 animals, 427.4ms
3: 640x640 3 animals, 427.4ms
4: 640x640 1 animal, 427.4ms
5: 640x640 1 animal, 1 person, 427.4ms
6: 640x640 1 person, 427.4ms
7: 640x640 1 animal, 427.4ms
8: 640x640 1 animal, 427.4ms
9: 640x640 1 animal, 427.4ms
10: 640x640 1 animal, 427.4ms
11: 640x640 1 animal, 427.4ms
12: 640x640 1 animal, 427.4ms
13: 640x640 1 animal, 427.4ms
14: 640x640 1 animal, 427.4ms
15: 640x640 1 animal, 427.4ms
Speed: 2.7ms preprocess, 427.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 50%|███████████████████████████████████████████████████████████████████▋                                                                    | 97/195 [09:06<11:12,  6.86s/it]

0: 640x640 1 animal, 426.6ms
1: 640x640 1 animal, 426.6ms
2: 640x640 2 animals, 426.6ms
3: 640x640 2 animals, 426.6ms
4: 640x640 1 animal, 426.6ms
5: 640x640 1 animal, 426.6ms
6: 640x640 1 animal, 426.6ms
7: 640x640 1 animal, 426.6ms
8: 640x640 1 animal, 426.6ms
9: 640x640 1 animal, 426.6ms
10: 640x640 1 animal, 426.6ms
11: 640x640 1 animal, 426.6ms
12: 640x640 1 animal, 426.6ms
13: 640x640 1 animal, 426.6ms
14: 640x640 1 animal, 426.6ms
15: 640x640 1 animal, 426.6ms
Speed: 2.6ms preprocess, 426.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 50%|████████████████████████████████████████████████████████████████████▎                                                                   | 98/195 [09:14<11:23,  7.05s/it]

0: 640x640 1 animal, 429.7ms
1: 640x640 1 animal, 429.7ms
2: 640x640 1 animal, 429.7ms
3: 640x640 1 animal, 429.7ms
4: 640x640 1 animal, 429.7ms
5: 640x640 1 animal, 429.7ms
6: 640x640 1 animal, 429.7ms
7: 640x640 1 animal, 429.7ms
8: 640x640 1 animal, 429.7ms
9: 640x640 1 animal, 429.7ms
10: 640x640 1 animal, 429.7ms
11: 640x640 1 animal, 429.7ms
12: 640x640 1 animal, 429.7ms
13: 640x640 1 animal, 429.7ms
14: 640x640 1 animal, 429.7ms
15: 640x640 1 animal, 429.7ms
Speed: 2.8ms preprocess, 429.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 51%|█████████████████████████████████████████████████████████████████████                                                                   | 99/195 [09:22<11:30,  7.19s/it]

0: 640x640 1 animal, 427.2ms
1: 640x640 1 animal, 427.2ms
2: 640x640 1 animal, 427.2ms
3: 640x640 1 animal, 427.2ms
4: 640x640 1 animal, 427.2ms
5: 640x640 1 animal, 427.2ms
6: 640x640 1 animal, 427.2ms
7: 640x640 1 animal, 427.2ms
8: 640x640 1 animal, 427.2ms
9: 640x640 2 animals, 427.2ms
10: 640x640 2 animals, 427.2ms
11: 640x640 2 animals, 427.2ms
12: 640x640 2 animals, 427.2ms
13: 640x640 1 animal, 427.2ms
14: 640x640 1 animal, 427.2ms
15: 640x640 1 animal, 427.2ms
Speed: 2.5ms preprocess, 427.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 51%|█████████████████████████████████████████████████████████████████████▏                                                                 | 100/195 [09:29<11:31,  7.28s/it]

0: 640x640 1 animal, 430.4ms
1: 640x640 1 animal, 430.4ms
2: 640x640 1 animal, 430.4ms
3: 640x640 1 animal, 430.4ms
4: 640x640 1 animal, 430.4ms
5: 640x640 1 animal, 430.4ms
6: 640x640 1 animal, 430.4ms
7: 640x640 1 animal, 430.4ms
8: 640x640 1 animal, 430.4ms
9: 640x640 (no detections), 430.4ms
10: 640x640 3 animals, 430.4ms
11: 640x640 4 animals, 430.4ms
12: 640x640 4 animals, 430.4ms
13: 640x640 3 animals, 430.4ms
14: 640x640 2 animals, 430.4ms
15: 640x640 2 animals, 430.4ms
Speed: 2.6ms preprocess, 430.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 52%|█████████████████████████████████████████████████████████████████████▉                                                                 | 101/195 [09:37<11:33,  7.38s/it]

0: 640x640 2 animals, 424.2ms
1: 640x640 2 animals, 424.2ms
2: 640x640 2 animals, 424.2ms
3: 640x640 1 animal, 424.2ms
4: 640x640 4 animals, 424.2ms
5: 640x640 2 animals, 424.2ms
6: 640x640 1 animal, 424.2ms
7: 640x640 1 animal, 424.2ms
8: 640x640 1 animal, 424.2ms
9: 640x640 1 animal, 424.2ms
10: 640x640 1 animal, 424.2ms
11: 640x640 1 animal, 424.2ms
12: 640x640 1 animal, 424.2ms
13: 640x640 1 animal, 424.2ms
14: 640x640 2 animals, 424.2ms
15: 640x640 1 animal, 424.2ms
Speed: 2.5ms preprocess, 424.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 52%|██████████████████████████████████████████████████████████████████████▌                                                                | 102/195 [09:44<11:24,  7.36s/it]

0: 640x640 1 animal, 428.7ms
1: 640x640 1 animal, 428.7ms
2: 640x640 1 animal, 428.7ms
3: 640x640 1 animal, 428.7ms
4: 640x640 1 animal, 428.7ms
5: 640x640 2 animals, 428.7ms
6: 640x640 2 animals, 428.7ms
7: 640x640 2 animals, 428.7ms
8: 640x640 1 animal, 428.7ms
9: 640x640 1 animal, 428.7ms
10: 640x640 1 animal, 428.7ms
11: 640x640 1 animal, 428.7ms
12: 640x640 1 animal, 428.7ms
13: 640x640 1 animal, 428.7ms
14: 640x640 1 animal, 428.7ms
15: 640x640 1 animal, 428.7ms
Speed: 2.8ms preprocess, 428.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 53%|███████████████████████████████████████████████████████████████████████▎                                                               | 103/195 [09:51<11:22,  7.42s/it]

0: 640x640 (no detections), 430.6ms
1: 640x640 (no detections), 430.6ms
2: 640x640 1 animal, 430.6ms
3: 640x640 1 animal, 430.6ms
4: 640x640 1 animal, 430.6ms
5: 640x640 1 animal, 430.6ms
6: 640x640 1 animal, 430.6ms
7: 640x640 1 animal, 430.6ms
8: 640x640 1 animal, 430.6ms
9: 640x640 1 animal, 430.6ms
10: 640x640 1 animal, 430.6ms
11: 640x640 1 animal, 430.6ms
12: 640x640 1 animal, 430.6ms
13: 640x640 1 animal, 430.6ms
14: 640x640 1 animal, 430.6ms
15: 640x640 1 animal, 430.6ms
Speed: 3.0ms preprocess, 430.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 53%|████████████████████████████████████████████████████████████████████████                                                               | 104/195 [09:59<11:23,  7.51s/it]

0: 384x640 1 animal, 245.1ms
1: 384x640 1 animal, 245.1ms
2: 384x640 1 animal, 245.1ms
3: 384x640 (no detections), 245.1ms
4: 384x640 (no detections), 245.1ms
5: 384x640 (no detections), 245.1ms
6: 384x640 2 animals, 245.1ms
7: 384x640 2 animals, 245.1ms
8: 384x640 2 animals, 245.1ms
9: 384x640 2 animals, 245.1ms
10: 384x640 1 animal, 245.1ms
11: 384x640 1 animal, 245.1ms
12: 384x640 1 animal, 245.1ms
13: 384x640 1 animal, 245.1ms
14: 384x640 1 animal, 245.1ms
15: 384x640 1 animal, 245.1ms
Speed: 2.1ms preprocess, 245.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 54%|████████████████████████████████████████████████████████████████████████▋                                                              | 105/195 [10:04<10:03,  6.71s/it]

0: 640x640 1 animal, 427.9ms
1: 640x640 1 animal, 427.9ms
2: 640x640 1 animal, 427.9ms
3: 640x640 1 animal, 427.9ms
4: 640x640 1 animal, 427.9ms
5: 640x640 (no detections), 427.9ms
6: 640x640 (no detections), 427.9ms
7: 640x640 (no detections), 427.9ms
8: 640x640 (no detections), 427.9ms
9: 640x640 (no detections), 427.9ms
10: 640x640 1 animal, 427.9ms
11: 640x640 1 animal, 427.9ms
12: 640x640 1 animal, 427.9ms
13: 640x640 1 animal, 427.9ms
14: 640x640 1 animal, 427.9ms
15: 640x640 1 animal, 427.9ms
Speed: 2.5ms preprocess, 427.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 54%|█████████████████████████████████████████████████████████████████████████▍                                                             | 106/195 [10:11<10:16,  6.93s/it]

0: 640x640 1 animal, 423.3ms
1: 640x640 1 animal, 423.3ms
2: 640x640 1 animal, 423.3ms
3: 640x640 2 animals, 423.3ms
4: 640x640 1 animal, 423.3ms
5: 640x640 1 animal, 423.3ms
6: 640x640 1 animal, 423.3ms
7: 640x640 2 animals, 423.3ms
8: 640x640 2 animals, 423.3ms
9: 640x640 1 animal, 423.3ms
10: 640x640 1 animal, 423.3ms
11: 640x640 1 animal, 423.3ms
12: 640x640 1 animal, 423.3ms
13: 640x640 1 animal, 423.3ms
14: 640x640 (no detections), 423.3ms
15: 640x640 (no detections), 423.3ms
Speed: 2.5ms preprocess, 423.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 55%|██████████████████████████████████████████████████████████████████████████                                                             | 107/195 [10:19<10:21,  7.06s/it]

0: 640x640 (no detections), 427.9ms
1: 640x640 (no detections), 427.9ms
2: 640x640 (no detections), 427.9ms
3: 640x640 (no detections), 427.9ms
4: 640x640 (no detections), 427.9ms
5: 640x640 (no detections), 427.9ms
6: 640x640 (no detections), 427.9ms
7: 640x640 (no detections), 427.9ms
8: 640x640 1 animal, 427.9ms
9: 640x640 1 animal, 427.9ms
10: 640x640 1 animal, 427.9ms
11: 640x640 1 animal, 427.9ms
12: 640x640 1 animal, 427.9ms
13: 640x640 1 animal, 427.9ms
14: 640x640 (no detections), 427.9ms
15: 640x640 (no detections), 427.9ms
Speed: 2.5ms preprocess, 427.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 55%|██████████████████████████████████████████████████████████████████████████▊                                                            | 108/195 [10:26<10:24,  7.18s/it]

0: 640x640 (no detections), 424.7ms
1: 640x640 (no detections), 424.7ms
2: 640x640 1 animal, 424.7ms
3: 640x640 1 animal, 424.7ms
4: 640x640 1 animal, 424.7ms
5: 640x640 1 animal, 424.7ms
6: 640x640 1 animal, 424.7ms
7: 640x640 1 animal, 424.7ms
8: 640x640 1 animal, 424.7ms
9: 640x640 (no detections), 424.7ms
10: 640x640 (no detections), 424.7ms
11: 640x640 (no detections), 424.7ms
12: 640x640 1 animal, 424.7ms
13: 640x640 1 animal, 424.7ms
14: 640x640 1 animal, 424.7ms
15: 640x640 1 animal, 424.7ms
Speed: 2.9ms preprocess, 424.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 56%|███████████████████████████████████████████████████████████████████████████▍                                                           | 109/195 [10:34<10:22,  7.24s/it]

0: 640x640 1 animal, 428.0ms
1: 640x640 1 animal, 428.0ms
2: 640x640 1 animal, 428.0ms
3: 640x640 1 animal, 428.0ms
4: 640x640 1 animal, 428.0ms
5: 640x640 1 animal, 428.0ms
6: 640x640 1 animal, 428.0ms
7: 640x640 1 animal, 428.0ms
8: 640x640 1 animal, 428.0ms
9: 640x640 1 animal, 428.0ms
10: 640x640 1 animal, 428.0ms
11: 640x640 1 animal, 428.0ms
12: 640x640 2 animals, 428.0ms
13: 640x640 1 animal, 428.0ms
14: 640x640 (no detections), 428.0ms
15: 640x640 (no detections), 428.0ms
Speed: 2.7ms preprocess, 428.0ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 56%|████████████████████████████████████████████████████████████████████████████▏                                                          | 110/195 [10:41<10:21,  7.31s/it]

0: 640x640 1 animal, 430.7ms
1: 640x640 1 animal, 430.7ms
2: 640x640 1 animal, 430.7ms
3: 640x640 2 animals, 430.7ms
4: 640x640 1 animal, 430.7ms
5: 640x640 1 animal, 430.7ms
6: 640x640 1 animal, 430.7ms
7: 640x640 1 animal, 430.7ms
8: 640x640 1 animal, 430.7ms
9: 640x640 (no detections), 430.7ms
10: 640x640 (no detections), 430.7ms
11: 640x640 1 animal, 430.7ms
12: 640x640 (no detections), 430.7ms
13: 640x640 (no detections), 430.7ms
14: 640x640 (no detections), 430.7ms
15: 640x640 (no detections), 430.7ms
Speed: 2.5ms preprocess, 430.7ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 57%|████████████████████████████████████████████████████████████████████████████▊                                                          | 111/195 [10:49<10:19,  7.37s/it]

0: 640x640 (no detections), 428.4ms
1: 640x640 (no detections), 428.4ms
2: 640x640 (no detections), 428.4ms
3: 640x640 (no detections), 428.4ms
4: 640x640 1 animal, 428.4ms
5: 640x640 1 animal, 428.4ms
6: 640x640 1 animal, 428.4ms
7: 640x640 1 animal, 428.4ms
8: 640x640 2 animals, 428.4ms
9: 640x640 1 animal, 428.4ms
10: 640x640 1 animal, 428.4ms
11: 640x640 1 animal, 428.4ms
12: 640x640 1 animal, 428.4ms
13: 640x640 1 animal, 428.4ms
14: 640x640 2 animals, 428.4ms
15: 640x640 2 animals, 428.4ms
Speed: 2.8ms preprocess, 428.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 57%|█████████████████████████████████████████████████████████████████████████████▌                                                         | 112/195 [10:56<10:15,  7.41s/it]

0: 384x640 1 animal, 246.1ms
1: 384x640 1 animal, 246.1ms
2: 384x640 1 animal, 246.1ms
3: 384x640 1 animal, 246.1ms
4: 384x640 1 animal, 246.1ms
5: 384x640 1 animal, 246.1ms
6: 384x640 1 animal, 246.1ms
7: 384x640 1 animal, 246.1ms
8: 384x640 3 animals, 246.1ms
9: 384x640 2 animals, 246.1ms
10: 384x640 2 animals, 246.1ms
11: 384x640 2 animals, 246.1ms
12: 384x640 2 animals, 246.1ms
13: 384x640 2 animals, 246.1ms
14: 384x640 3 animals, 246.1ms
15: 384x640 1 animal, 246.1ms
Speed: 2.2ms preprocess, 246.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 58%|██████████████████████████████████████████████████████████████████████████████▏                                                        | 113/195 [11:01<09:04,  6.64s/it]

0: 640x640 1 animal, 429.9ms
1: 640x640 1 animal, 429.9ms
2: 640x640 1 animal, 429.9ms
3: 640x640 1 animal, 429.9ms
4: 640x640 1 animal, 429.9ms
5: 640x640 2 animals, 429.9ms
6: 640x640 2 animals, 429.9ms
7: 640x640 2 animals, 429.9ms
8: 640x640 1 animal, 429.9ms
9: 640x640 2 animals, 429.9ms
10: 640x640 1 animal, 429.9ms
11: 640x640 1 animal, 429.9ms
12: 640x640 2 animals, 429.9ms
13: 640x640 1 animal, 429.9ms
14: 640x640 1 animal, 429.9ms
15: 640x640 1 animal, 429.9ms
Speed: 2.7ms preprocess, 429.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 58%|██████████████████████████████████████████████████████████████████████████████▉                                                        | 114/195 [11:09<09:19,  6.90s/it]

0: 384x640 1 animal, 246.5ms
1: 384x640 1 animal, 246.5ms
2: 384x640 1 animal, 246.5ms
3: 384x640 1 animal, 246.5ms
4: 384x640 1 animal, 246.5ms
5: 384x640 1 animal, 246.5ms
6: 384x640 1 animal, 246.5ms
7: 384x640 1 animal, 246.5ms
8: 384x640 1 animal, 246.5ms
9: 384x640 1 animal, 246.5ms
10: 384x640 1 animal, 246.5ms
11: 384x640 1 animal, 246.5ms
12: 384x640 1 animal, 246.5ms
13: 384x640 1 animal, 246.5ms
14: 384x640 1 animal, 246.5ms
15: 384x640 1 animal, 246.5ms
Speed: 1.9ms preprocess, 246.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 59%|███████████████████████████████████████████████████████████████████████████████▌                                                       | 115/195 [11:13<08:22,  6.28s/it]

0: 640x640 1 animal, 422.4ms
1: 640x640 1 animal, 422.4ms
2: 640x640 1 animal, 422.4ms
3: 640x640 1 animal, 422.4ms
4: 640x640 1 animal, 422.4ms
5: 640x640 1 animal, 422.4ms
6: 640x640 1 animal, 422.4ms
7: 640x640 (no detections), 422.4ms
8: 640x640 (no detections), 422.4ms
9: 640x640 (no detections), 422.4ms
10: 640x640 1 animal, 422.4ms
11: 640x640 2 animals, 422.4ms
12: 640x640 2 animals, 422.4ms
13: 640x640 (no detections), 422.4ms
14: 640x640 (no detections), 422.4ms
15: 640x640 1 animal, 422.4ms
Speed: 2.5ms preprocess, 422.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 59%|████████████████████████████████████████████████████████████████████████████████▎                                                      | 116/195 [11:21<08:40,  6.59s/it]

0: 384x640 (no detections), 244.1ms
1: 384x640 (no detections), 244.1ms
2: 384x640 (no detections), 244.1ms
3: 384x640 1 animal, 244.1ms
4: 384x640 1 animal, 244.1ms
5: 384x640 1 animal, 244.1ms
6: 384x640 1 animal, 244.1ms
7: 384x640 1 animal, 244.1ms
8: 384x640 1 animal, 244.1ms
9: 384x640 1 animal, 244.1ms
10: 384x640 1 animal, 244.1ms
11: 384x640 1 animal, 244.1ms
12: 384x640 1 animal, 244.1ms
13: 384x640 1 animal, 244.1ms
14: 384x640 1 animal, 244.1ms
15: 384x640 1 animal, 244.1ms
Speed: 1.9ms preprocess, 244.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 60%|█████████████████████████████████████████████████████████████████████████████████                                                      | 117/195 [11:25<07:51,  6.04s/it]

0: 640x640 1 animal, 423.3ms
1: 640x640 1 animal, 423.3ms
2: 640x640 1 animal, 423.3ms
3: 640x640 1 animal, 423.3ms
4: 640x640 1 animal, 423.3ms
5: 640x640 1 animal, 423.3ms
6: 640x640 1 animal, 423.3ms
7: 640x640 1 animal, 423.3ms
8: 640x640 1 animal, 423.3ms
9: 640x640 1 animal, 423.3ms
10: 640x640 1 animal, 423.3ms
11: 640x640 1 animal, 423.3ms
12: 640x640 1 animal, 423.3ms
13: 640x640 1 animal, 423.3ms
14: 640x640 (no detections), 423.3ms
15: 640x640 (no detections), 423.3ms
Speed: 2.5ms preprocess, 423.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 61%|█████████████████████████████████████████████████████████████████████████████████▋                                                     | 118/195 [11:33<08:16,  6.44s/it]

0: 640x640 (no detections), 422.1ms
1: 640x640 (no detections), 422.1ms
2: 640x640 1 animal, 422.1ms
3: 640x640 1 animal, 422.1ms
4: 640x640 1 animal, 422.1ms
5: 640x640 1 animal, 422.1ms
6: 640x640 1 animal, 422.1ms
7: 640x640 1 animal, 422.1ms
8: 640x640 1 animal, 422.1ms
9: 640x640 1 animal, 422.1ms
10: 640x640 1 animal, 422.1ms
11: 640x640 1 animal, 422.1ms
12: 640x640 1 animal, 422.1ms
13: 640x640 1 animal, 422.1ms
14: 640x640 1 animal, 422.1ms
15: 640x640 1 animal, 422.1ms
Speed: 2.8ms preprocess, 422.1ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 61%|██████████████████████████████████████████████████████████████████████████████████▍                                                    | 119/195 [11:40<08:31,  6.73s/it]

0: 640x640 1 animal, 423.7ms
1: 640x640 (no detections), 423.7ms
2: 640x640 (no detections), 423.7ms
3: 640x640 (no detections), 423.7ms
4: 640x640 (no detections), 423.7ms
5: 640x640 (no detections), 423.7ms
6: 640x640 1 animal, 423.7ms
7: 640x640 1 animal, 423.7ms
8: 640x640 1 animal, 423.7ms
9: 640x640 1 animal, 423.7ms
10: 640x640 1 animal, 423.7ms
11: 640x640 1 animal, 423.7ms
12: 640x640 1 animal, 423.7ms
13: 640x640 1 animal, 423.7ms
14: 640x640 1 animal, 423.7ms
15: 640x640 1 animal, 423.7ms
Speed: 2.5ms preprocess, 423.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 62%|███████████████████████████████████████████████████████████████████████████████████                                                    | 120/195 [11:48<08:40,  6.93s/it]

0: 384x640 1 animal, 246.4ms
1: 384x640 1 animal, 246.4ms
2: 384x640 1 animal, 246.4ms
3: 384x640 1 animal, 246.4ms
4: 384x640 1 animal, 246.4ms
5: 384x640 1 animal, 246.4ms
6: 384x640 1 animal, 246.4ms
7: 384x640 1 animal, 246.4ms
8: 384x640 1 animal, 246.4ms
9: 384x640 1 animal, 246.4ms
10: 384x640 1 animal, 246.4ms
11: 384x640 1 animal, 246.4ms
12: 384x640 1 animal, 246.4ms
13: 384x640 1 animal, 246.4ms
14: 384x640 2 animals, 246.4ms
15: 384x640 1 animal, 246.4ms
Speed: 1.9ms preprocess, 246.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 62%|███████████████████████████████████████████████████████████████████████████████████▊                                                   | 121/195 [11:52<07:46,  6.30s/it]

0: 640x640 1 animal, 423.4ms
1: 640x640 1 animal, 423.4ms
2: 640x640 1 animal, 423.4ms
3: 640x640 1 animal, 423.4ms
4: 640x640 1 animal, 423.4ms
5: 640x640 1 animal, 423.4ms
6: 640x640 1 animal, 423.4ms
7: 640x640 1 animal, 423.4ms
8: 640x640 1 animal, 423.4ms
9: 640x640 1 animal, 423.4ms
10: 640x640 1 animal, 423.4ms
11: 640x640 1 animal, 423.4ms
12: 640x640 (no detections), 423.4ms
13: 640x640 (no detections), 423.4ms
14: 640x640 1 animal, 423.4ms
15: 640x640 1 animal, 423.4ms
Speed: 2.5ms preprocess, 423.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 63%|████████████████████████████████████████████████████████████████████████████████████▍                                                  | 122/195 [12:00<08:03,  6.62s/it]

0: 640x640 1 animal, 424.7ms
1: 640x640 1 animal, 424.7ms
2: 640x640 1 animal, 424.7ms
3: 640x640 1 animal, 424.7ms
4: 640x640 1 animal, 424.7ms
5: 640x640 1 animal, 424.7ms
6: 640x640 1 animal, 424.7ms
7: 640x640 2 animals, 424.7ms
8: 640x640 (no detections), 424.7ms
9: 640x640 2 animals, 424.7ms
10: 640x640 3 animals, 424.7ms
11: 640x640 2 animals, 424.7ms
12: 640x640 1 animal, 424.7ms
13: 640x640 1 animal, 424.7ms
14: 640x640 1 animal, 424.7ms
15: 640x640 1 animal, 424.7ms
Speed: 2.6ms preprocess, 424.7ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 63%|█████████████████████████████████████████████████████████████████████████████████████▏                                                 | 123/195 [12:07<08:15,  6.88s/it]

0: 640x640 1 animal, 426.9ms
1: 640x640 1 animal, 426.9ms
2: 640x640 1 animal, 426.9ms
3: 640x640 1 animal, 426.9ms
4: 640x640 1 animal, 426.9ms
5: 640x640 1 animal, 426.9ms
6: 640x640 1 animal, 426.9ms
7: 640x640 1 animal, 426.9ms
8: 640x640 1 animal, 426.9ms
9: 640x640 1 animal, 426.9ms
10: 640x640 1 animal, 426.9ms
11: 640x640 1 animal, 426.9ms
12: 640x640 1 animal, 426.9ms
13: 640x640 1 animal, 426.9ms
14: 640x640 1 animal, 426.9ms
15: 640x640 1 animal, 426.9ms
Speed: 2.9ms preprocess, 426.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 64%|█████████████████████████████████████████████████████████████████████████████████████▊                                                 | 124/195 [12:15<08:24,  7.11s/it]

0: 384x640 1 animal, 242.5ms
1: 384x640 1 animal, 242.5ms
2: 384x640 1 animal, 242.5ms
3: 384x640 1 animal, 242.5ms
4: 384x640 1 animal, 242.5ms
5: 384x640 1 animal, 242.5ms
6: 384x640 1 animal, 242.5ms
7: 384x640 1 animal, 242.5ms
8: 384x640 1 animal, 242.5ms
9: 384x640 1 animal, 242.5ms
10: 384x640 1 animal, 242.5ms
11: 384x640 1 animal, 242.5ms
12: 384x640 (no detections), 242.5ms
13: 384x640 (no detections), 242.5ms
14: 384x640 1 animal, 242.5ms
15: 384x640 (no detections), 242.5ms
Speed: 1.8ms preprocess, 242.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 64%|██████████████████████████████████████████████████████████████████████████████████████▌                                                | 125/195 [12:19<07:18,  6.27s/it]

0: 384x640 2 animals, 241.0ms
1: 384x640 2 animals, 241.0ms
2: 384x640 1 animal, 241.0ms
3: 384x640 1 animal, 241.0ms
4: 384x640 1 animal, 241.0ms
5: 384x640 1 animal, 241.0ms
6: 384x640 1 animal, 241.0ms
7: 384x640 1 animal, 241.0ms
8: 384x640 1 animal, 241.0ms
9: 384x640 1 animal, 241.0ms
10: 384x640 2 animals, 241.0ms
11: 384x640 1 animal, 241.0ms
12: 384x640 1 animal, 241.0ms
13: 384x640 1 animal, 241.0ms
14: 384x640 1 animal, 241.0ms
15: 384x640 1 animal, 241.0ms
Speed: 1.9ms preprocess, 241.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 65%|███████████████████████████████████████████████████████████████████████████████████████▏                                               | 126/195 [12:24<06:41,  5.82s/it]

0: 640x640 1 animal, 409.5ms
1: 640x640 1 animal, 409.5ms
2: 640x640 (no detections), 409.5ms
3: 640x640 (no detections), 409.5ms
4: 640x640 1 animal, 409.5ms
5: 640x640 1 animal, 409.5ms
6: 640x640 1 animal, 409.5ms
7: 640x640 1 animal, 409.5ms
8: 640x640 1 animal, 409.5ms
9: 640x640 1 animal, 409.5ms
10: 640x640 1 animal, 409.5ms
11: 640x640 1 animal, 409.5ms
12: 640x640 1 animal, 409.5ms
13: 640x640 1 animal, 409.5ms
14: 640x640 1 animal, 409.5ms
15: 640x640 1 animal, 409.5ms
Speed: 2.6ms preprocess, 409.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 65%|███████████████████████████████████████████████████████████████████████████████████████▉                                               | 127/195 [12:31<07:07,  6.29s/it]

0: 640x640 1 animal, 412.9ms
1: 640x640 1 animal, 412.9ms
2: 640x640 1 animal, 412.9ms
3: 640x640 1 animal, 412.9ms
4: 640x640 1 animal, 412.9ms
5: 640x640 1 animal, 412.9ms
6: 640x640 1 animal, 412.9ms
7: 640x640 1 animal, 412.9ms
8: 640x640 2 animals, 412.9ms
9: 640x640 2 animals, 412.9ms
10: 640x640 2 animals, 412.9ms
11: 640x640 2 animals, 412.9ms
12: 640x640 2 animals, 412.9ms
13: 640x640 3 animals, 412.9ms
14: 640x640 4 animals, 412.9ms
15: 640x640 3 animals, 412.9ms
Speed: 2.6ms preprocess, 412.9ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 66%|████████████████████████████████████████████████████████████████████████████████████████▌                                              | 128/195 [12:39<07:21,  6.59s/it]

0: 640x640 (no detections), 425.5ms
1: 640x640 (no detections), 425.5ms
2: 640x640 2 animals, 425.5ms
3: 640x640 1 animal, 425.5ms
4: 640x640 1 animal, 425.5ms
5: 640x640 1 animal, 425.5ms
6: 640x640 1 animal, 425.5ms
7: 640x640 1 animal, 425.5ms
8: 640x640 1 animal, 425.5ms
9: 640x640 1 animal, 425.5ms
10: 640x640 1 animal, 425.5ms
11: 640x640 1 animal, 425.5ms
12: 640x640 1 animal, 425.5ms
13: 640x640 1 animal, 425.5ms
14: 640x640 1 animal, 425.5ms
15: 640x640 1 animal, 425.5ms
Speed: 2.9ms preprocess, 425.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 66%|█████████████████████████████████████████████████████████████████████████████████████████▎                                             | 129/195 [12:46<07:29,  6.81s/it]

0: 640x640 1 animal, 423.8ms
1: 640x640 1 animal, 423.8ms
2: 640x640 1 animal, 423.8ms
3: 640x640 (no detections), 423.8ms
4: 640x640 3 animals, 423.8ms
5: 640x640 1 animal, 423.8ms
6: 640x640 3 animals, 423.8ms
7: 640x640 3 animals, 423.8ms
8: 640x640 2 animals, 423.8ms
9: 640x640 2 animals, 423.8ms
10: 640x640 1 animal, 423.8ms
11: 640x640 2 animals, 423.8ms
12: 640x640 2 animals, 423.8ms
13: 640x640 1 animal, 423.8ms
14: 640x640 1 animal, 423.8ms
15: 640x640 2 animals, 423.8ms
Speed: 2.8ms preprocess, 423.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 67%|██████████████████████████████████████████████████████████████████████████████████████████                                             | 130/195 [12:54<07:36,  7.03s/it]

0: 640x640 1 animal, 429.4ms
1: 640x640 1 animal, 429.4ms
2: 640x640 1 animal, 429.4ms
3: 640x640 1 animal, 429.4ms
4: 640x640 1 animal, 429.4ms
5: 640x640 1 animal, 429.4ms
6: 640x640 1 animal, 429.4ms
7: 640x640 1 animal, 429.4ms
8: 640x640 (no detections), 429.4ms
9: 640x640 (no detections), 429.4ms
10: 640x640 2 animals, 429.4ms
11: 640x640 2 animals, 429.4ms
12: 640x640 2 animals, 429.4ms
13: 640x640 2 animals, 429.4ms
14: 640x640 2 animals, 429.4ms
15: 640x640 2 animals, 429.4ms
Speed: 2.6ms preprocess, 429.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 67%|██████████████████████████████████████████████████████████████████████████████████████████▋                                            | 131/195 [13:01<07:37,  7.15s/it]

0: 640x640 3 animals, 431.3ms
1: 640x640 2 animals, 431.3ms
2: 640x640 2 animals, 431.3ms
3: 640x640 2 animals, 431.3ms
4: 640x640 1 animal, 431.3ms
5: 640x640 1 animal, 431.3ms
6: 640x640 1 animal, 431.3ms
7: 640x640 3 animals, 431.3ms
8: 640x640 2 animals, 431.3ms
9: 640x640 2 animals, 431.3ms
10: 640x640 2 animals, 431.3ms
11: 640x640 2 animals, 431.3ms
12: 640x640 3 animals, 431.3ms
13: 640x640 1 animal, 431.3ms
14: 640x640 1 animal, 431.3ms
15: 640x640 1 animal, 431.3ms
Speed: 2.6ms preprocess, 431.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 68%|███████████████████████████████████████████████████████████████████████████████████████████▍                                           | 132/195 [13:09<07:41,  7.32s/it]

0: 640x640 1 animal, 429.5ms
1: 640x640 1 animal, 429.5ms
2: 640x640 2 animals, 429.5ms
3: 640x640 1 animal, 429.5ms
4: 640x640 1 animal, 429.5ms
5: 640x640 1 animal, 429.5ms
6: 640x640 1 animal, 429.5ms
7: 640x640 1 animal, 429.5ms
8: 640x640 1 animal, 429.5ms
9: 640x640 1 animal, 429.5ms
10: 640x640 1 animal, 429.5ms
11: 640x640 1 animal, 429.5ms
12: 640x640 1 animal, 429.5ms
13: 640x640 1 animal, 429.5ms
14: 640x640 1 animal, 429.5ms
15: 640x640 1 animal, 429.5ms
Speed: 3.0ms preprocess, 429.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 68%|████████████████████████████████████████████████████████████████████████████████████████████                                           | 133/195 [13:16<07:38,  7.40s/it]

0: 640x640 1 animal, 429.2ms
1: 640x640 1 animal, 429.2ms
2: 640x640 2 animals, 429.2ms
3: 640x640 2 animals, 429.2ms
4: 640x640 2 animals, 429.2ms
5: 640x640 2 animals, 429.2ms
6: 640x640 2 animals, 429.2ms
7: 640x640 2 animals, 429.2ms
8: 640x640 2 animals, 429.2ms
9: 640x640 2 animals, 429.2ms
10: 640x640 2 animals, 429.2ms
11: 640x640 2 animals, 429.2ms
12: 640x640 1 animal, 429.2ms
13: 640x640 1 animal, 429.2ms
14: 640x640 1 animal, 429.2ms
15: 640x640 1 animal, 429.2ms
Speed: 2.8ms preprocess, 429.2ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 69%|████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 134/195 [13:24<07:36,  7.48s/it]

0: 640x640 1 animal, 431.1ms
1: 640x640 1 animal, 431.1ms
2: 640x640 1 animal, 431.1ms
3: 640x640 (no detections), 431.1ms
4: 640x640 (no detections), 431.1ms
5: 640x640 (no detections), 431.1ms
6: 640x640 1 animal, 431.1ms
7: 640x640 1 animal, 431.1ms
8: 640x640 1 animal, 431.1ms
9: 640x640 (no detections), 431.1ms
10: 640x640 (no detections), 431.1ms
11: 640x640 (no detections), 431.1ms
12: 640x640 (no detections), 431.1ms
13: 640x640 (no detections), 431.1ms
14: 640x640 1 animal, 431.1ms
15: 640x640 (no detections), 431.1ms
Speed: 2.5ms preprocess, 431.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 69%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                         | 135/195 [13:32<07:30,  7.50s/it]

0: 384x640 2 animals, 247.6ms
1: 384x640 1 animal, 247.6ms
2: 384x640 1 animal, 247.6ms
3: 384x640 1 animal, 247.6ms
4: 384x640 1 animal, 247.6ms
5: 384x640 1 animal, 247.6ms
6: 384x640 1 animal, 247.6ms
7: 384x640 1 animal, 247.6ms
8: 384x640 1 animal, 247.6ms
9: 384x640 1 animal, 247.6ms
10: 384x640 1 animal, 247.6ms
11: 384x640 1 animal, 247.6ms
12: 384x640 (no detections), 247.6ms
13: 384x640 (no detections), 247.6ms
14: 384x640 (no detections), 247.6ms
15: 384x640 (no detections), 247.6ms
Speed: 1.9ms preprocess, 247.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 70%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 136/195 [13:36<06:35,  6.70s/it]

0: 640x640 (no detections), 426.2ms
1: 640x640 (no detections), 426.2ms
2: 640x640 (no detections), 426.2ms
3: 640x640 (no detections), 426.2ms
4: 640x640 1 animal, 426.2ms
5: 640x640 1 animal, 426.2ms
6: 640x640 1 animal, 426.2ms
7: 640x640 1 animal, 426.2ms
8: 640x640 1 animal, 426.2ms
9: 640x640 1 animal, 426.2ms
10: 640x640 1 animal, 426.2ms
11: 640x640 (no detections), 426.2ms
12: 640x640 (no detections), 426.2ms
13: 640x640 (no detections), 426.2ms
14: 640x640 1 animal, 426.2ms
15: 640x640 1 animal, 426.2ms
Speed: 2.5ms preprocess, 426.2ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 70%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 137/195 [13:44<06:40,  6.91s/it]

0: 640x640 1 animal, 432.3ms
1: 640x640 1 animal, 432.3ms
2: 640x640 1 animal, 432.3ms
3: 640x640 1 animal, 432.3ms
4: 640x640 1 animal, 432.3ms
5: 640x640 1 animal, 432.3ms
6: 640x640 1 animal, 432.3ms
7: 640x640 1 animal, 432.3ms
8: 640x640 1 animal, 432.3ms
9: 640x640 1 animal, 432.3ms
10: 640x640 1 animal, 432.3ms
11: 640x640 1 animal, 432.3ms
12: 640x640 1 animal, 432.3ms
13: 640x640 1 animal, 432.3ms
14: 640x640 1 animal, 432.3ms
15: 640x640 1 animal, 432.3ms
Speed: 2.8ms preprocess, 432.3ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 71%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 138/195 [13:51<06:45,  7.12s/it]

0: 384x640 1 animal, 244.2ms
1: 384x640 1 animal, 244.2ms
2: 384x640 1 animal, 244.2ms
3: 384x640 1 animal, 244.2ms
4: 384x640 1 animal, 1 person, 244.2ms
5: 384x640 1 animal, 244.2ms
6: 384x640 (no detections), 244.2ms
7: 384x640 1 animal, 244.2ms
8: 384x640 (no detections), 244.2ms
9: 384x640 1 animal, 244.2ms
10: 384x640 1 animal, 244.2ms
11: 384x640 1 animal, 244.2ms
12: 384x640 1 animal, 244.2ms
13: 384x640 1 animal, 244.2ms
14: 384x640 1 animal, 244.2ms
15: 384x640 1 animal, 244.2ms
Speed: 1.8ms preprocess, 244.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 71%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 139/195 [13:56<05:52,  6.29s/it]

0: 384x640 1 animal, 244.8ms
1: 384x640 1 animal, 244.8ms
2: 384x640 1 animal, 244.8ms
3: 384x640 1 animal, 244.8ms
4: 384x640 1 animal, 244.8ms
5: 384x640 (no detections), 244.8ms
6: 384x640 1 animal, 244.8ms
7: 384x640 1 animal, 244.8ms
8: 384x640 1 animal, 244.8ms
9: 384x640 1 animal, 244.8ms
10: 384x640 1 animal, 244.8ms
11: 384x640 1 animal, 244.8ms
12: 384x640 (no detections), 244.8ms
13: 384x640 (no detections), 244.8ms
14: 384x640 1 animal, 244.8ms
15: 384x640 (no detections), 244.8ms
Speed: 1.9ms preprocess, 244.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 72%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                      | 140/195 [14:00<05:14,  5.72s/it]

0: 384x640 2 animals, 246.1ms
1: 384x640 1 animal, 246.1ms
2: 384x640 1 animal, 246.1ms
3: 384x640 1 animal, 246.1ms
4: 384x640 1 animal, 246.1ms
5: 384x640 1 animal, 246.1ms
6: 384x640 1 animal, 246.1ms
7: 384x640 1 animal, 246.1ms
8: 384x640 1 animal, 246.1ms
9: 384x640 1 animal, 246.1ms
10: 384x640 (no detections), 246.1ms
11: 384x640 (no detections), 246.1ms
12: 384x640 (no detections), 246.1ms
13: 384x640 (no detections), 246.1ms
14: 384x640 (no detections), 246.1ms
15: 384x640 (no detections), 246.1ms
Speed: 1.9ms preprocess, 246.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 72%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                     | 141/195 [14:05<04:54,  5.45s/it]

0: 384x640 (no detections), 247.6ms
1: 384x640 (no detections), 247.6ms
2: 384x640 (no detections), 247.6ms
3: 384x640 (no detections), 247.6ms
4: 384x640 1 animal, 247.6ms
5: 384x640 1 animal, 247.6ms
6: 384x640 1 animal, 247.6ms
7: 384x640 1 animal, 247.6ms
8: 384x640 1 animal, 247.6ms
9: 384x640 1 animal, 247.6ms
10: 384x640 1 animal, 247.6ms
11: 384x640 1 animal, 247.6ms
12: 384x640 1 animal, 247.6ms
13: 384x640 1 animal, 247.6ms
14: 384x640 1 animal, 247.6ms
15: 384x640 3 animals, 247.6ms
Speed: 2.2ms preprocess, 247.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 73%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 142/195 [14:10<04:39,  5.27s/it]

0: 384x640 3 animals, 246.6ms
1: 384x640 3 animals, 246.6ms
2: 384x640 2 animals, 246.6ms
3: 384x640 2 animals, 246.6ms
4: 384x640 3 animals, 246.6ms
5: 384x640 3 animals, 246.6ms
6: 384x640 3 animals, 246.6ms
7: 384x640 3 animals, 246.6ms
8: 384x640 1 animal, 246.6ms
9: 384x640 1 animal, 246.6ms
10: 384x640 1 animal, 246.6ms
11: 384x640 1 animal, 246.6ms
12: 384x640 1 animal, 246.6ms
13: 384x640 1 animal, 246.6ms
14: 384x640 1 animal, 246.6ms
15: 384x640 1 animal, 246.6ms
Speed: 1.9ms preprocess, 246.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████                                    | 143/195 [14:15<04:26,  5.13s/it]

0: 384x640 1 animal, 235.6ms
1: 384x640 1 animal, 235.6ms
2: 384x640 (no detections), 235.6ms
3: 384x640 (no detections), 235.6ms
4: 384x640 (no detections), 235.6ms
5: 384x640 (no detections), 235.6ms
6: 384x640 (no detections), 235.6ms
7: 384x640 (no detections), 235.6ms
8: 384x640 (no detections), 235.6ms
9: 384x640 (no detections), 235.6ms
10: 384x640 (no detections), 235.6ms
11: 384x640 (no detections), 235.6ms
12: 384x640 1 animal, 235.6ms
13: 384x640 3 animals, 235.6ms
14: 384x640 3 animals, 235.6ms
15: 384x640 3 animals, 235.6ms
Speed: 1.9ms preprocess, 235.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 74%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                   | 144/195 [14:19<04:13,  4.97s/it]

0: 384x640 3 animals, 246.5ms
1: 384x640 2 animals, 246.5ms
2: 384x640 3 animals, 246.5ms
3: 384x640 4 animals, 246.5ms
4: 384x640 3 animals, 246.5ms
5: 384x640 2 animals, 246.5ms
6: 384x640 1 animal, 246.5ms
7: 384x640 1 animal, 246.5ms
8: 384x640 1 animal, 246.5ms
9: 384x640 1 animal, 246.5ms
10: 384x640 1 animal, 246.5ms
11: 384x640 (no detections), 246.5ms
12: 384x640 (no detections), 246.5ms
13: 384x640 (no detections), 246.5ms
14: 384x640 (no detections), 246.5ms
15: 384x640 (no detections), 246.5ms
Speed: 1.9ms preprocess, 246.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 74%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 145/195 [14:24<04:05,  4.92s/it]

0: 384x640 2 animals, 246.9ms
1: 384x640 2 animals, 246.9ms
2: 384x640 2 animals, 246.9ms
3: 384x640 2 animals, 246.9ms
4: 384x640 3 animals, 246.9ms
5: 384x640 2 animals, 246.9ms
6: 384x640 1 animal, 246.9ms
7: 384x640 1 animal, 246.9ms
8: 384x640 2 animals, 246.9ms
9: 384x640 1 animal, 246.9ms
10: 384x640 2 animals, 246.9ms
11: 384x640 1 animal, 246.9ms
12: 384x640 1 animal, 246.9ms
13: 384x640 1 animal, 246.9ms
14: 384x640 1 animal, 246.9ms
15: 384x640 1 animal, 246.9ms
Speed: 2.1ms preprocess, 246.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 75%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 146/195 [14:29<03:59,  4.90s/it]

0: 384x640 1 animal, 246.1ms
1: 384x640 1 animal, 246.1ms
2: 384x640 1 animal, 246.1ms
3: 384x640 1 animal, 246.1ms
4: 384x640 2 animals, 246.1ms
5: 384x640 1 animal, 246.1ms
6: 384x640 1 animal, 246.1ms
7: 384x640 1 animal, 246.1ms
8: 384x640 1 animal, 246.1ms
9: 384x640 1 animal, 246.1ms
10: 384x640 1 animal, 246.1ms
11: 384x640 1 animal, 246.1ms
12: 384x640 1 animal, 246.1ms
13: 384x640 1 animal, 246.1ms
14: 384x640 1 animal, 246.1ms
15: 384x640 1 animal, 246.1ms
Speed: 2.1ms preprocess, 246.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 75%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 147/195 [14:34<03:54,  4.88s/it]

0: 384x640 1 animal, 247.9ms
1: 384x640 1 animal, 247.9ms
2: 384x640 1 animal, 247.9ms
3: 384x640 1 animal, 247.9ms
4: 384x640 1 animal, 247.9ms
5: 384x640 1 animal, 247.9ms
6: 384x640 1 animal, 247.9ms
7: 384x640 1 animal, 247.9ms
8: 384x640 1 animal, 247.9ms
9: 384x640 1 animal, 247.9ms
10: 384x640 1 animal, 247.9ms
11: 384x640 1 animal, 247.9ms
12: 384x640 1 animal, 247.9ms
13: 384x640 1 animal, 247.9ms
14: 384x640 1 animal, 247.9ms
15: 384x640 1 animal, 247.9ms
Speed: 1.9ms preprocess, 247.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 148/195 [14:38<03:48,  4.86s/it]

0: 384x640 (no detections), 246.7ms
1: 384x640 (no detections), 246.7ms
2: 384x640 3 animals, 246.7ms
3: 384x640 2 animals, 246.7ms
4: 384x640 2 animals, 246.7ms
5: 384x640 2 animals, 246.7ms
6: 384x640 2 animals, 246.7ms
7: 384x640 2 animals, 246.7ms
8: 384x640 2 animals, 246.7ms
9: 384x640 2 animals, 246.7ms
10: 384x640 2 animals, 246.7ms
11: 384x640 2 animals, 246.7ms
12: 384x640 1 animal, 246.7ms
13: 384x640 1 animal, 246.7ms
14: 384x640 1 animal, 246.7ms
15: 384x640 1 animal, 246.7ms
Speed: 1.9ms preprocess, 246.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 149/195 [14:43<03:43,  4.85s/it]

0: 384x640 1 animal, 247.4ms
1: 384x640 1 animal, 247.4ms
2: 384x640 (no detections), 247.4ms
3: 384x640 (no detections), 247.4ms
4: 384x640 (no detections), 247.4ms
5: 384x640 (no detections), 247.4ms
6: 384x640 5 animals, 247.4ms
7: 384x640 4 animals, 247.4ms
8: 384x640 4 animals, 247.4ms
9: 384x640 4 animals, 247.4ms
10: 384x640 4 animals, 247.4ms
11: 384x640 3 animals, 247.4ms
12: 384x640 4 animals, 247.4ms
13: 384x640 5 animals, 247.4ms
14: 384x640 4 animals, 247.4ms
15: 384x640 5 animals, 247.4ms
Speed: 2.1ms preprocess, 247.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 150/195 [14:48<03:38,  4.86s/it]

0: 384x640 1 animal, 247.3ms
1: 384x640 1 animal, 247.3ms
2: 384x640 1 animal, 247.3ms
3: 384x640 1 animal, 247.3ms
4: 384x640 1 animal, 247.3ms
5: 384x640 1 animal, 247.3ms
6: 384x640 1 animal, 247.3ms
7: 384x640 1 animal, 247.3ms
8: 384x640 1 animal, 247.3ms
9: 384x640 1 animal, 247.3ms
10: 384x640 1 animal, 247.3ms
11: 384x640 1 animal, 247.3ms
12: 384x640 1 animal, 247.3ms
13: 384x640 1 animal, 247.3ms
14: 384x640 1 animal, 247.3ms
15: 384x640 1 animal, 247.3ms
Speed: 2.2ms preprocess, 247.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 77%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 151/195 [14:53<03:33,  4.86s/it]

0: 384x640 1 animal, 245.1ms
1: 384x640 1 animal, 245.1ms
2: 384x640 1 animal, 245.1ms
3: 384x640 1 animal, 245.1ms
4: 384x640 4 animals, 245.1ms
5: 384x640 1 animal, 245.1ms
6: 384x640 1 animal, 245.1ms
7: 384x640 1 animal, 245.1ms
8: 384x640 2 animals, 245.1ms
9: 384x640 3 animals, 245.1ms
10: 384x640 3 animals, 245.1ms
11: 384x640 3 animals, 245.1ms
12: 384x640 2 animals, 245.1ms
13: 384x640 2 animals, 245.1ms
14: 384x640 2 animals, 245.1ms
15: 384x640 2 animals, 245.1ms
Speed: 2.1ms preprocess, 245.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 152/195 [14:58<03:28,  4.84s/it]

0: 384x640 2 animals, 247.6ms
1: 384x640 2 animals, 247.6ms
2: 384x640 2 animals, 247.6ms
3: 384x640 2 animals, 247.6ms
4: 384x640 2 animals, 247.6ms
5: 384x640 2 animals, 247.6ms
6: 384x640 2 animals, 247.6ms
7: 384x640 2 animals, 247.6ms
8: 384x640 2 animals, 247.6ms
9: 384x640 2 animals, 247.6ms
10: 384x640 2 animals, 247.6ms
11: 384x640 1 animal, 247.6ms
12: 384x640 2 animals, 247.6ms
13: 384x640 1 animal, 247.6ms
14: 384x640 1 animal, 247.6ms
15: 384x640 1 animal, 247.6ms
Speed: 2.1ms preprocess, 247.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 153/195 [15:03<03:23,  4.84s/it]

0: 384x640 2 animals, 246.9ms
1: 384x640 1 animal, 246.9ms
2: 384x640 (no detections), 246.9ms
3: 384x640 (no detections), 246.9ms
4: 384x640 (no detections), 246.9ms
5: 384x640 (no detections), 246.9ms
6: 384x640 (no detections), 246.9ms
7: 384x640 (no detections), 246.9ms
8: 384x640 (no detections), 246.9ms
9: 384x640 (no detections), 246.9ms
10: 384x640 (no detections), 246.9ms
11: 384x640 (no detections), 246.9ms
12: 384x640 (no detections), 246.9ms
13: 384x640 (no detections), 246.9ms
14: 384x640 (no detections), 246.9ms
15: 384x640 (no detections), 246.9ms
Speed: 1.9ms preprocess, 246.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 154/195 [15:07<03:16,  4.79s/it]

0: 384x640 (no detections), 244.9ms
1: 384x640 (no detections), 244.9ms
2: 384x640 (no detections), 244.9ms
3: 384x640 (no detections), 244.9ms
4: 384x640 (no detections), 244.9ms
5: 384x640 (no detections), 244.9ms
6: 384x640 1 animal, 244.9ms
7: 384x640 1 animal, 244.9ms
8: 384x640 1 animal, 244.9ms
9: 384x640 1 animal, 244.9ms
10: 384x640 1 animal, 244.9ms
11: 384x640 1 animal, 244.9ms
12: 384x640 1 animal, 244.9ms
13: 384x640 (no detections), 244.9ms
14: 384x640 (no detections), 244.9ms
15: 384x640 (no detections), 244.9ms
Speed: 2.2ms preprocess, 244.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 155/195 [15:12<03:11,  4.78s/it]

0: 384x640 2 animals, 246.6ms
1: 384x640 2 animals, 246.6ms
2: 384x640 3 animals, 246.6ms
3: 384x640 2 animals, 246.6ms
4: 384x640 2 animals, 246.6ms
5: 384x640 2 animals, 246.6ms
6: 384x640 2 animals, 246.6ms
7: 384x640 2 animals, 246.6ms
8: 384x640 1 animal, 246.6ms
9: 384x640 1 animal, 246.6ms
10: 384x640 1 animal, 246.6ms
11: 384x640 1 animal, 246.6ms
12: 384x640 1 animal, 246.6ms
13: 384x640 1 animal, 246.6ms
14: 384x640 1 animal, 246.6ms
15: 384x640 1 animal, 246.6ms
Speed: 1.9ms preprocess, 246.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 156/195 [15:17<03:07,  4.81s/it]

0: 384x640 1 animal, 245.5ms
1: 384x640 1 animal, 245.5ms
2: 384x640 1 animal, 245.5ms
3: 384x640 1 animal, 245.5ms
4: 384x640 1 animal, 245.5ms
5: 384x640 1 animal, 245.5ms
6: 384x640 1 animal, 245.5ms
7: 384x640 1 animal, 245.5ms
8: 384x640 1 animal, 245.5ms
9: 384x640 1 animal, 245.5ms
10: 384x640 (no detections), 245.5ms
11: 384x640 (no detections), 245.5ms
12: 384x640 (no detections), 245.5ms
13: 384x640 (no detections), 245.5ms
14: 384x640 1 animal, 245.5ms
15: 384x640 1 animal, 245.5ms
Speed: 2.0ms preprocess, 245.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 157/195 [15:22<03:03,  4.82s/it]

0: 384x640 1 animal, 248.1ms
1: 384x640 1 animal, 248.1ms
2: 384x640 1 animal, 248.1ms
3: 384x640 1 animal, 248.1ms
4: 384x640 1 animal, 248.1ms
5: 384x640 1 animal, 248.1ms
6: 384x640 1 animal, 248.1ms
7: 384x640 1 animal, 248.1ms
8: 384x640 1 animal, 248.1ms
9: 384x640 1 animal, 248.1ms
10: 384x640 (no detections), 248.1ms
11: 384x640 (no detections), 248.1ms
12: 384x640 (no detections), 248.1ms
13: 384x640 (no detections), 248.1ms
14: 384x640 (no detections), 248.1ms
15: 384x640 (no detections), 248.1ms
Speed: 2.2ms preprocess, 248.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 158/195 [15:27<02:59,  4.84s/it]

0: 384x640 (no detections), 247.1ms
1: 384x640 (no detections), 247.1ms
2: 384x640 1 animal, 247.1ms
3: 384x640 1 animal, 247.1ms
4: 384x640 2 animals, 247.1ms
5: 384x640 1 animal, 247.1ms
6: 384x640 1 animal, 247.1ms
7: 384x640 1 animal, 247.1ms
8: 384x640 (no detections), 247.1ms
9: 384x640 (no detections), 247.1ms
10: 384x640 (no detections), 247.1ms
11: 384x640 (no detections), 247.1ms
12: 384x640 1 animal, 247.1ms
13: 384x640 1 animal, 247.1ms
14: 384x640 1 animal, 247.1ms
15: 384x640 1 animal, 247.1ms
Speed: 1.9ms preprocess, 247.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 159/195 [15:31<02:53,  4.81s/it]

0: 384x640 1 animal, 244.5ms
1: 384x640 1 animal, 244.5ms
2: 384x640 1 animal, 244.5ms
3: 384x640 1 animal, 244.5ms
4: 384x640 1 animal, 244.5ms
5: 384x640 1 animal, 244.5ms
6: 384x640 1 animal, 244.5ms
7: 384x640 1 animal, 244.5ms
8: 384x640 1 animal, 244.5ms
9: 384x640 1 animal, 244.5ms
10: 384x640 1 animal, 244.5ms
11: 384x640 (no detections), 244.5ms
12: 384x640 (no detections), 244.5ms
13: 384x640 1 animal, 244.5ms
14: 384x640 1 animal, 244.5ms
15: 384x640 1 animal, 244.5ms
Speed: 2.0ms preprocess, 244.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 160/195 [15:36<02:47,  4.78s/it]

0: 384x640 2 animals, 245.2ms
1: 384x640 2 animals, 245.2ms
2: 384x640 2 animals, 245.2ms
3: 384x640 2 animals, 245.2ms
4: 384x640 2 animals, 245.2ms
5: 384x640 2 animals, 245.2ms
6: 384x640 1 animal, 245.2ms
7: 384x640 2 animals, 245.2ms
8: 384x640 1 animal, 245.2ms
9: 384x640 2 animals, 245.2ms
10: 384x640 2 animals, 245.2ms
11: 384x640 2 animals, 245.2ms
12: 384x640 2 animals, 245.2ms
13: 384x640 2 animals, 245.2ms
14: 384x640 1 animal, 245.2ms
15: 384x640 1 animal, 245.2ms
Speed: 1.9ms preprocess, 245.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 161/195 [15:41<02:43,  4.80s/it]

0: 384x640 1 animal, 245.3ms
1: 384x640 1 animal, 245.3ms
2: 384x640 1 animal, 245.3ms
3: 384x640 1 animal, 245.3ms
4: 384x640 2 animals, 1 person, 245.3ms
5: 384x640 2 animals, 245.3ms
6: 384x640 2 animals, 245.3ms
7: 384x640 3 animals, 245.3ms
8: 384x640 2 animals, 245.3ms
9: 384x640 2 animals, 245.3ms
10: 384x640 3 animals, 245.3ms
11: 384x640 4 animals, 245.3ms
12: 384x640 3 animals, 245.3ms
13: 384x640 4 animals, 245.3ms
14: 384x640 2 animals, 245.3ms
15: 384x640 2 animals, 245.3ms
Speed: 2.0ms preprocess, 245.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 162/195 [15:46<02:39,  4.82s/it]

0: 384x640 1 animal, 238.4ms
1: 384x640 1 animal, 238.4ms
2: 384x640 1 animal, 238.4ms
3: 384x640 1 animal, 238.4ms
4: 384x640 (no detections), 238.4ms
5: 384x640 (no detections), 238.4ms
6: 384x640 (no detections), 238.4ms
7: 384x640 (no detections), 238.4ms
8: 384x640 1 animal, 238.4ms
9: 384x640 1 animal, 238.4ms
10: 384x640 (no detections), 238.4ms
11: 384x640 (no detections), 238.4ms
12: 384x640 (no detections), 238.4ms
13: 384x640 (no detections), 238.4ms
14: 384x640 1 animal, 238.4ms
15: 384x640 1 animal, 238.4ms
Speed: 2.1ms preprocess, 238.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 163/195 [15:51<02:32,  4.77s/it]

0: 384x640 1 animal, 245.7ms
1: 384x640 1 animal, 245.7ms
2: 384x640 1 animal, 245.7ms
3: 384x640 1 animal, 245.7ms
4: 384x640 1 animal, 245.7ms
5: 384x640 2 animals, 245.7ms
6: 384x640 1 animal, 245.7ms
7: 384x640 1 animal, 245.7ms
8: 384x640 1 animal, 245.7ms
9: 384x640 1 animal, 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 1 animal, 245.7ms
12: 384x640 1 animal, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 3 animals, 245.7ms
Speed: 1.9ms preprocess, 245.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 164/195 [15:55<02:27,  4.75s/it]

0: 384x640 2 animals, 247.8ms
1: 384x640 2 animals, 247.8ms
2: 384x640 2 animals, 247.8ms
3: 384x640 1 animal, 247.8ms
4: 384x640 1 animal, 247.8ms
5: 384x640 2 animals, 247.8ms
6: 384x640 1 animal, 247.8ms
7: 384x640 1 animal, 247.8ms
8: 384x640 1 animal, 247.8ms
9: 384x640 1 animal, 247.8ms
10: 384x640 1 animal, 247.8ms
11: 384x640 1 animal, 247.8ms
12: 384x640 1 animal, 247.8ms
13: 384x640 1 animal, 247.8ms
14: 384x640 1 animal, 247.8ms
15: 384x640 1 animal, 247.8ms
Speed: 2.3ms preprocess, 247.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 165/195 [16:00<02:23,  4.79s/it]

0: 384x640 4 animals, 245.1ms
1: 384x640 3 animals, 245.1ms
2: 384x640 2 animals, 245.1ms
3: 384x640 1 animal, 245.1ms
4: 384x640 1 animal, 245.1ms
5: 384x640 1 animal, 245.1ms
6: 384x640 1 animal, 245.1ms
7: 384x640 1 animal, 245.1ms
8: 384x640 1 animal, 245.1ms
9: 384x640 (no detections), 245.1ms
10: 384x640 1 animal, 245.1ms
11: 384x640 1 animal, 245.1ms
12: 384x640 1 animal, 245.1ms
13: 384x640 1 animal, 245.1ms
14: 384x640 1 animal, 245.1ms
15: 384x640 1 animal, 245.1ms
Speed: 1.9ms preprocess, 245.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 166/195 [16:05<02:19,  4.81s/it]

0: 384x640 1 animal, 244.5ms
1: 384x640 1 animal, 244.5ms
2: 384x640 1 animal, 244.5ms
3: 384x640 1 animal, 244.5ms
4: 384x640 1 animal, 244.5ms
5: 384x640 1 animal, 244.5ms
6: 384x640 (no detections), 244.5ms
7: 384x640 (no detections), 244.5ms
8: 384x640 (no detections), 244.5ms
9: 384x640 (no detections), 244.5ms
10: 384x640 (no detections), 244.5ms
11: 384x640 (no detections), 244.5ms
12: 384x640 (no detections), 244.5ms
13: 384x640 (no detections), 244.5ms
14: 384x640 1 animal, 244.5ms
15: 384x640 1 animal, 244.5ms
Speed: 2.2ms preprocess, 244.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 167/195 [16:10<02:14,  4.81s/it]

0: 384x640 4 animals, 246.0ms
1: 384x640 1 animal, 246.0ms
2: 384x640 2 animals, 246.0ms
3: 384x640 2 animals, 246.0ms
4: 384x640 2 animals, 246.0ms
5: 384x640 2 animals, 246.0ms
6: 384x640 2 animals, 246.0ms
7: 384x640 2 animals, 246.0ms
8: 384x640 1 animal, 246.0ms
9: 384x640 1 animal, 246.0ms
10: 384x640 1 animal, 246.0ms
11: 384x640 1 animal, 246.0ms
12: 384x640 1 animal, 246.0ms
13: 384x640 1 animal, 246.0ms
14: 384x640 1 animal, 246.0ms
15: 384x640 1 animal, 246.0ms
Speed: 1.9ms preprocess, 246.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 168/195 [16:15<02:09,  4.80s/it]

0: 384x640 1 animal, 247.0ms
1: 384x640 1 animal, 247.0ms
2: 384x640 3 animals, 247.0ms
3: 384x640 3 animals, 247.0ms
4: 384x640 3 animals, 247.0ms
5: 384x640 3 animals, 247.0ms
6: 384x640 3 animals, 247.0ms
7: 384x640 3 animals, 247.0ms
8: 384x640 2 animals, 247.0ms
9: 384x640 3 animals, 247.0ms
10: 384x640 3 animals, 247.0ms
11: 384x640 3 animals, 247.0ms
12: 384x640 1 animal, 247.0ms
13: 384x640 1 animal, 247.0ms
14: 384x640 1 animal, 247.0ms
15: 384x640 1 animal, 247.0ms
Speed: 1.9ms preprocess, 247.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 169/195 [16:19<02:05,  4.81s/it]

0: 384x640 1 animal, 244.4ms
1: 384x640 1 animal, 244.4ms
2: 384x640 1 animal, 244.4ms
3: 384x640 1 animal, 244.4ms
4: 384x640 1 animal, 244.4ms
5: 384x640 1 animal, 244.4ms
6: 384x640 1 animal, 244.4ms
7: 384x640 1 animal, 244.4ms
8: 384x640 1 animal, 244.4ms
9: 384x640 1 animal, 244.4ms
10: 384x640 1 animal, 244.4ms
11: 384x640 1 animal, 244.4ms
12: 384x640 1 animal, 244.4ms
13: 384x640 1 animal, 244.4ms
14: 384x640 1 animal, 244.4ms
15: 384x640 1 animal, 244.4ms
Speed: 1.9ms preprocess, 244.4ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 170/195 [16:24<02:00,  4.80s/it]

0: 384x640 (no detections), 245.3ms
1: 384x640 (no detections), 245.3ms
2: 384x640 (no detections), 245.3ms
3: 384x640 (no detections), 245.3ms
4: 384x640 (no detections), 245.3ms
5: 384x640 (no detections), 245.3ms
6: 384x640 (no detections), 245.3ms
7: 384x640 (no detections), 245.3ms
8: 384x640 (no detections), 245.3ms
9: 384x640 1 animal, 245.3ms
10: 384x640 1 animal, 1 person, 245.3ms
11: 384x640 1 animal, 245.3ms
12: 384x640 1 animal, 245.3ms
13: 384x640 1 animal, 245.3ms
14: 384x640 1 animal, 245.3ms
15: 384x640 1 animal, 245.3ms
Speed: 2.0ms preprocess, 245.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 171/195 [16:29<01:55,  4.83s/it]

0: 384x640 1 animal, 246.5ms
1: 384x640 1 animal, 246.5ms
2: 384x640 2 animals, 246.5ms
3: 384x640 2 animals, 246.5ms
4: 384x640 1 animal, 246.5ms
5: 384x640 1 animal, 246.5ms
6: 384x640 1 animal, 246.5ms
7: 384x640 1 animal, 246.5ms
8: 384x640 1 animal, 246.5ms
9: 384x640 1 animal, 246.5ms
10: 384x640 2 animals, 246.5ms
11: 384x640 1 animal, 246.5ms
12: 384x640 1 animal, 246.5ms
13: 384x640 1 animal, 246.5ms
14: 384x640 1 animal, 246.5ms
15: 384x640 1 animal, 246.5ms
Speed: 2.4ms preprocess, 246.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 172/195 [16:34<01:51,  4.84s/it]

0: 384x640 1 animal, 247.4ms
1: 384x640 1 animal, 247.4ms
2: 384x640 1 animal, 247.4ms
3: 384x640 1 animal, 247.4ms
4: 384x640 1 animal, 247.4ms
5: 384x640 1 animal, 247.4ms
6: 384x640 1 animal, 247.4ms
7: 384x640 1 animal, 247.4ms
8: 384x640 1 animal, 247.4ms
9: 384x640 1 animal, 247.4ms
10: 384x640 (no detections), 247.4ms
11: 384x640 (no detections), 247.4ms
12: 384x640 (no detections), 247.4ms
13: 384x640 (no detections), 247.4ms
14: 384x640 (no detections), 247.4ms
15: 384x640 (no detections), 247.4ms
Speed: 2.1ms preprocess, 247.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 173/195 [16:39<01:46,  4.85s/it]

0: 384x640 (no detections), 246.1ms
1: 384x640 (no detections), 246.1ms
2: 384x640 1 animal, 246.1ms
3: 384x640 1 animal, 246.1ms
4: 384x640 1 animal, 246.1ms
5: 384x640 1 animal, 246.1ms
6: 384x640 1 animal, 246.1ms
7: 384x640 1 animal, 246.1ms
8: 384x640 1 animal, 246.1ms
9: 384x640 (no detections), 246.1ms
10: 384x640 1 animal, 246.1ms
11: 384x640 1 animal, 246.1ms
12: 384x640 1 animal, 246.1ms
13: 384x640 (no detections), 246.1ms
14: 384x640 (no detections), 246.1ms
15: 384x640 (no detections), 246.1ms
Speed: 1.9ms preprocess, 246.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 174/195 [16:44<01:41,  4.84s/it]

0: 384x640 (no detections), 245.1ms
1: 384x640 (no detections), 245.1ms
2: 384x640 (no detections), 245.1ms
3: 384x640 (no detections), 245.1ms
4: 384x640 (no detections), 245.1ms
5: 384x640 (no detections), 245.1ms
6: 384x640 1 animal, 245.1ms
7: 384x640 1 animal, 245.1ms
8: 384x640 1 animal, 245.1ms
9: 384x640 1 animal, 245.1ms
10: 384x640 1 animal, 245.1ms
11: 384x640 1 animal, 245.1ms
12: 384x640 1 animal, 245.1ms
13: 384x640 1 animal, 245.1ms
14: 384x640 (no detections), 245.1ms
15: 384x640 (no detections), 245.1ms
Speed: 2.1ms preprocess, 245.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 175/195 [16:48<01:36,  4.82s/it]

0: 384x640 2 animals, 245.9ms
1: 384x640 1 animal, 245.9ms
2: 384x640 1 animal, 245.9ms
3: 384x640 1 animal, 245.9ms
4: 384x640 1 animal, 245.9ms
5: 384x640 1 animal, 245.9ms
6: 384x640 1 animal, 245.9ms
7: 384x640 1 animal, 245.9ms
8: 384x640 1 animal, 245.9ms
9: 384x640 1 animal, 245.9ms
10: 384x640 1 animal, 245.9ms
11: 384x640 1 animal, 245.9ms
12: 384x640 1 animal, 245.9ms
13: 384x640 1 animal, 245.9ms
14: 384x640 1 animal, 245.9ms
15: 384x640 1 animal, 245.9ms
Speed: 2.1ms preprocess, 245.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 176/195 [16:53<01:31,  4.83s/it]

0: 384x640 1 animal, 248.5ms
1: 384x640 1 animal, 248.5ms
2: 384x640 1 animal, 248.5ms
3: 384x640 1 animal, 248.5ms
4: 384x640 1 animal, 248.5ms
5: 384x640 1 animal, 248.5ms
6: 384x640 1 animal, 248.5ms
7: 384x640 3 animals, 248.5ms
8: 384x640 2 animals, 248.5ms
9: 384x640 2 animals, 248.5ms
10: 384x640 1 animal, 248.5ms
11: 384x640 1 animal, 248.5ms
12: 384x640 1 animal, 248.5ms
13: 384x640 1 animal, 248.5ms
14: 384x640 1 animal, 248.5ms
15: 384x640 2 animals, 248.5ms
Speed: 2.1ms preprocess, 248.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 177/195 [16:58<01:27,  4.85s/it]

0: 384x640 1 animal, 247.1ms
1: 384x640 1 animal, 247.1ms
2: 384x640 1 animal, 247.1ms
3: 384x640 1 animal, 247.1ms
4: 384x640 1 animal, 247.1ms
5: 384x640 1 animal, 247.1ms
6: 384x640 1 animal, 247.1ms
7: 384x640 1 animal, 247.1ms
8: 384x640 1 animal, 247.1ms
9: 384x640 1 animal, 247.1ms
10: 384x640 1 animal, 247.1ms
11: 384x640 1 animal, 247.1ms
12: 384x640 1 animal, 247.1ms
13: 384x640 1 animal, 247.1ms
14: 384x640 1 animal, 247.1ms
15: 384x640 1 animal, 247.1ms
Speed: 1.9ms preprocess, 247.1ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 178/195 [17:03<01:22,  4.85s/it]

0: 384x640 1 animal, 245.5ms
1: 384x640 1 animal, 245.5ms
2: 384x640 1 animal, 245.5ms
3: 384x640 1 animal, 245.5ms
4: 384x640 1 animal, 245.5ms
5: 384x640 1 animal, 245.5ms
6: 384x640 1 animal, 245.5ms
7: 384x640 1 animal, 245.5ms
8: 384x640 1 animal, 245.5ms
9: 384x640 1 animal, 245.5ms
10: 384x640 1 animal, 245.5ms
11: 384x640 1 animal, 245.5ms
12: 384x640 1 vehicle, 245.5ms
13: 384x640 2 persons, 1 vehicle, 245.5ms
14: 384x640 1 person, 1 vehicle, 245.5ms
15: 384x640 1 person, 1 vehicle, 245.5ms
Speed: 2.2ms preprocess, 245.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 179/195 [17:08<01:17,  4.85s/it]

0: 384x640 3 persons, 1 vehicle, 237.8ms
1: 384x640 1 person, 1 vehicle, 237.8ms
2: 384x640 (no detections), 237.8ms
3: 384x640 (no detections), 237.8ms
4: 384x640 (no detections), 237.8ms
5: 384x640 (no detections), 237.8ms
6: 384x640 2 animals, 237.8ms
7: 384x640 2 animals, 237.8ms
8: 384x640 2 animals, 237.8ms
9: 384x640 2 animals, 237.8ms
10: 384x640 1 animal, 237.8ms
11: 384x640 1 animal, 237.8ms
12: 384x640 1 animal, 237.8ms
13: 384x640 1 animal, 237.8ms
14: 384x640 1 animal, 237.8ms
15: 384x640 1 animal, 237.8ms
Speed: 2.1ms preprocess, 237.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 180/195 [17:13<01:12,  4.81s/it]

0: 384x640 1 animal, 237.2ms
1: 384x640 1 animal, 237.2ms
2: 384x640 1 animal, 237.2ms
3: 384x640 1 animal, 237.2ms
4: 384x640 1 animal, 237.2ms
5: 384x640 1 animal, 237.2ms
6: 384x640 1 animal, 237.2ms
7: 384x640 1 animal, 237.2ms
8: 384x640 1 animal, 237.2ms
9: 384x640 1 animal, 237.2ms
10: 384x640 1 animal, 237.2ms
11: 384x640 (no detections), 237.2ms
12: 384x640 (no detections), 237.2ms
13: 384x640 (no detections), 237.2ms
14: 384x640 (no detections), 237.2ms
15: 384x640 (no detections), 237.2ms
Speed: 1.9ms preprocess, 237.2ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 181/195 [17:17<01:06,  4.78s/it]

0: 384x640 (no detections), 234.3ms
1: 384x640 (no detections), 234.3ms
2: 384x640 (no detections), 234.3ms
3: 384x640 (no detections), 234.3ms
4: 384x640 1 animal, 234.3ms
5: 384x640 1 animal, 234.3ms
6: 384x640 1 animal, 234.3ms
7: 384x640 1 animal, 234.3ms
8: 384x640 1 animal, 234.3ms
9: 384x640 1 animal, 234.3ms
10: 384x640 1 animal, 234.3ms
11: 384x640 1 animal, 234.3ms
12: 384x640 1 animal, 234.3ms
13: 384x640 1 animal, 234.3ms
14: 384x640 1 animal, 234.3ms
15: 384x640 1 animal, 234.3ms
Speed: 1.9ms preprocess, 234.3ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 182/195 [17:22<01:01,  4.73s/it]

0: 384x640 1 animal, 237.2ms
1: 384x640 1 animal, 237.2ms
2: 384x640 1 animal, 237.2ms
3: 384x640 1 animal, 237.2ms
4: 384x640 1 animal, 237.2ms
5: 384x640 1 animal, 237.2ms
6: 384x640 1 animal, 237.2ms
7: 384x640 1 animal, 237.2ms
8: 384x640 1 animal, 237.2ms
9: 384x640 1 animal, 237.2ms
10: 384x640 1 animal, 237.2ms
11: 384x640 1 animal, 237.2ms
12: 384x640 1 animal, 237.2ms
13: 384x640 1 animal, 237.2ms
14: 384x640 1 animal, 237.2ms
15: 384x640 1 animal, 237.2ms
Speed: 1.9ms preprocess, 237.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 183/195 [17:27<00:56,  4.72s/it]

0: 384x640 1 animal, 235.0ms
1: 384x640 1 animal, 235.0ms
2: 384x640 2 animals, 235.0ms
3: 384x640 2 animals, 235.0ms
4: 384x640 1 animal, 235.0ms
5: 384x640 1 animal, 235.0ms
6: 384x640 1 animal, 235.0ms
7: 384x640 1 animal, 235.0ms
8: 384x640 1 animal, 235.0ms
9: 384x640 2 animals, 235.0ms
10: 384x640 2 animals, 235.0ms
11: 384x640 2 animals, 235.0ms
12: 384x640 2 animals, 235.0ms
13: 384x640 2 animals, 235.0ms
14: 384x640 1 animal, 1 person, 235.0ms
15: 384x640 1 animal, 1 person, 235.0ms
Speed: 1.9ms preprocess, 235.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 184/195 [17:31<00:51,  4.70s/it]

0: 384x640 1 animal, 234.8ms
1: 384x640 1 animal, 234.8ms
2: 384x640 1 animal, 234.8ms
3: 384x640 1 animal, 234.8ms
4: 384x640 1 animal, 234.8ms
5: 384x640 (no detections), 234.8ms
6: 384x640 2 animals, 234.8ms
7: 384x640 2 animals, 234.8ms
8: 384x640 1 animal, 1 person, 234.8ms
9: 384x640 1 animal, 1 person, 234.8ms
10: 384x640 1 animal, 234.8ms
11: 384x640 1 animal, 234.8ms
12: 384x640 1 animal, 234.8ms
13: 384x640 1 animal, 234.8ms
14: 384x640 1 animal, 234.8ms
15: 384x640 (no detections), 234.8ms
Speed: 1.9ms preprocess, 234.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 185/195 [17:36<00:46,  4.68s/it]

0: 384x640 1 animal, 238.8ms
1: 384x640 (no detections), 238.8ms
2: 384x640 (no detections), 238.8ms
3: 384x640 (no detections), 238.8ms
4: 384x640 (no detections), 238.8ms
5: 384x640 (no detections), 238.8ms
6: 384x640 (no detections), 238.8ms
7: 384x640 (no detections), 238.8ms
8: 384x640 (no detections), 238.8ms
9: 384x640 (no detections), 238.8ms
10: 384x640 1 animal, 238.8ms
11: 384x640 (no detections), 238.8ms
12: 384x640 (no detections), 238.8ms
13: 384x640 (no detections), 238.8ms
14: 384x640 (no detections), 238.8ms
15: 384x640 (no detections), 238.8ms
Speed: 2.0ms preprocess, 238.8ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 186/195 [17:41<00:42,  4.69s/it]

0: 384x640 (no detections), 242.9ms
1: 384x640 (no detections), 242.9ms
2: 384x640 (no detections), 242.9ms
3: 384x640 (no detections), 242.9ms
4: 384x640 1 animal, 242.9ms
5: 384x640 1 animal, 242.9ms
6: 384x640 1 animal, 242.9ms
7: 384x640 3 animals, 242.9ms
8: 384x640 3 animals, 242.9ms
9: 384x640 2 animals, 242.9ms
10: 384x640 2 animals, 242.9ms
11: 384x640 3 animals, 242.9ms
12: 384x640 2 animals, 242.9ms
13: 384x640 1 animal, 242.9ms
14: 384x640 1 animal, 242.9ms
15: 384x640 1 animal, 242.9ms
Speed: 1.9ms preprocess, 242.9ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 187/195 [17:45<00:37,  4.72s/it]

0: 384x640 1 animal, 244.6ms
1: 384x640 3 animals, 244.6ms
2: 384x640 3 animals, 244.6ms
3: 384x640 2 animals, 244.6ms
4: 384x640 2 animals, 244.6ms
5: 384x640 3 animals, 244.6ms
6: 384x640 2 animals, 244.6ms
7: 384x640 1 animal, 244.6ms
8: 384x640 2 animals, 244.6ms
9: 384x640 4 animals, 244.6ms
10: 384x640 2 animals, 244.6ms
11: 384x640 3 animals, 244.6ms
12: 384x640 3 animals, 244.6ms
13: 384x640 1 animal, 244.6ms
14: 384x640 1 animal, 244.6ms
15: 384x640 1 animal, 244.6ms
Speed: 2.2ms preprocess, 244.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 188/195 [17:50<00:33,  4.76s/it]

0: 384x640 (no detections), 246.6ms
1: 384x640 (no detections), 246.6ms
2: 384x640 3 animals, 246.6ms
3: 384x640 3 animals, 246.6ms
4: 384x640 2 animals, 246.6ms
5: 384x640 2 animals, 246.6ms
6: 384x640 2 animals, 246.6ms
7: 384x640 3 animals, 246.6ms
8: 384x640 3 animals, 246.6ms
9: 384x640 2 animals, 246.6ms
10: 384x640 3 animals, 246.6ms
11: 384x640 2 animals, 246.6ms
12: 384x640 1 animal, 246.6ms
13: 384x640 2 animals, 246.6ms
14: 384x640 1 animal, 246.6ms
15: 384x640 1 animal, 246.6ms
Speed: 2.0ms preprocess, 246.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 189/195 [17:55<00:28,  4.80s/it]

0: 384x640 1 animal, 245.8ms
1: 384x640 1 animal, 245.8ms
2: 384x640 1 animal, 245.8ms
3: 384x640 1 animal, 245.8ms
4: 384x640 1 animal, 245.8ms
5: 384x640 1 animal, 245.8ms
6: 384x640 1 animal, 245.8ms
7: 384x640 1 animal, 245.8ms
8: 384x640 1 animal, 245.8ms
9: 384x640 1 animal, 245.8ms
10: 384x640 1 animal, 245.8ms
11: 384x640 1 animal, 245.8ms
12: 384x640 1 animal, 245.8ms
13: 384x640 1 animal, 245.8ms
14: 384x640 1 animal, 245.8ms
15: 384x640 2 animals, 245.8ms
Speed: 2.1ms preprocess, 245.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 190/195 [18:00<00:24,  4.82s/it]

0: 384x640 1 animal, 245.7ms
1: 384x640 1 animal, 245.7ms
2: 384x640 1 animal, 245.7ms
3: 384x640 (no detections), 245.7ms
4: 384x640 (no detections), 245.7ms
5: 384x640 1 animal, 245.7ms
6: 384x640 1 animal, 245.7ms
7: 384x640 1 animal, 245.7ms
8: 384x640 (no detections), 245.7ms
9: 384x640 (no detections), 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 1 animal, 245.7ms
12: 384x640 1 animal, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 2 animals, 245.7ms
Speed: 1.9ms preprocess, 245.7ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 191/195 [18:05<00:19,  4.83s/it]

0: 384x640 2 animals, 244.6ms
1: 384x640 2 animals, 244.6ms
2: 384x640 2 animals, 244.6ms
3: 384x640 2 animals, 244.6ms
4: 384x640 1 animal, 244.6ms
5: 384x640 1 animal, 244.6ms
6: 384x640 1 animal, 244.6ms
7: 384x640 1 animal, 244.6ms
8: 384x640 1 animal, 244.6ms
9: 384x640 1 animal, 244.6ms
10: 384x640 1 animal, 244.6ms
11: 384x640 1 animal, 244.6ms
12: 384x640 1 animal, 244.6ms
13: 384x640 1 animal, 244.6ms
14: 384x640 2 animals, 244.6ms
15: 384x640 2 animals, 244.6ms
Speed: 2.2ms preprocess, 244.6ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 192/195 [18:10<00:14,  4.83s/it]

0: 384x640 2 animals, 243.8ms
1: 384x640 2 animals, 243.8ms
2: 384x640 2 animals, 243.8ms
3: 384x640 2 animals, 243.8ms
4: 384x640 2 animals, 243.8ms
5: 384x640 2 animals, 243.8ms
6: 384x640 2 animals, 243.8ms
7: 384x640 2 animals, 243.8ms
8: 384x640 1 animal, 243.8ms
9: 384x640 1 animal, 243.8ms
10: 384x640 (no detections), 243.8ms
11: 384x640 (no detections), 243.8ms
12: 384x640 (no detections), 243.8ms
13: 384x640 (no detections), 243.8ms
14: 384x640 (no detections), 243.8ms
15: 384x640 (no detections), 243.8ms
Speed: 2.2ms preprocess, 243.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 193/195 [18:15<00:09,  4.83s/it]

0: 384x640 (no detections), 243.3ms
1: 384x640 (no detections), 243.3ms
2: 384x640 3 animals, 243.3ms
3: 384x640 1 animal, 243.3ms
4: 384x640 1 animal, 243.3ms
5: 384x640 1 animal, 243.3ms
6: 384x640 (no detections), 243.3ms
7: 384x640 (no detections), 243.3ms
8: 384x640 (no detections), 243.3ms
9: 384x640 (no detections), 243.3ms
10: 384x640 (no detections), 243.3ms
11: 384x640 (no detections), 243.3ms
12: 384x640 1 animal, 1 person, 243.3ms
13: 384x640 1 animal, 243.3ms
14: 384x640 1 animal, 243.3ms
15: 384x640 1 animal, 243.3ms
Speed: 1.9ms preprocess, 243.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 194/195 [18:19<00:04,  4.78s/it]

0: 384x640 1 animal, 244.0ms
1: 384x640 1 animal, 244.0ms
2: 384x640 1 animal, 244.0ms
3: 384x640 1 animal, 244.0ms
4: 384x640 1 animal, 244.0ms
5: 384x640 1 animal, 244.0ms
6: 384x640 1 animal, 244.0ms
7: 384x640 1 animal, 244.0ms
8: 384x640 1 animal, 244.0ms
9: 384x640 3 animals, 244.0ms
10: 384x640 3 animals, 244.0ms
11: 384x640 2 animals, 244.0ms
12: 384x640 3 animals, 244.0ms
13: 384x640 2 animals, 244.0ms
14: 384x640 4 animals, 244.0ms
15: 384x640 4 animals, 244.0ms
Speed: 2.1ms preprocess, 244.0ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

00%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 195/195 [18:24<00:00,  5.66s/it]

Detecting images from MEPITIS_MACROURA_2022_extracted

  0%|                                                                                                                                                  | 0/50 [00:00<?, ?it/s]

0: 640x640 1 animal, 426.5ms
1: 640x640 1 animal, 426.5ms
2: 640x640 1 animal, 426.5ms
3: 640x640 1 animal, 426.5ms
4: 640x640 1 animal, 426.5ms
5: 640x640 (no detections), 426.5ms
6: 640x640 (no detections), 426.5ms
7: 640x640 (no detections), 426.5ms
8: 640x640 (no detections), 426.5ms
9: 640x640 (no detections), 426.5ms
10: 640x640 1 animal, 426.5ms
11: 640x640 1 animal, 426.5ms
12: 640x640 1 animal, 426.5ms
13: 640x640 (no detections), 426.5ms
14: 640x640 (no detections), 426.5ms
15: 640x640 (no detections), 426.5ms
Speed: 2.7ms preprocess, 426.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

  2%|██▊                                                                                                                                       | 1/50 [00:07<06:00,  7.35s/it]

0: 384x640 1 animal, 247.1ms
1: 384x640 1 animal, 247.1ms
2: 384x640 1 animal, 247.1ms
3: 384x640 1 animal, 247.1ms
4: 384x640 1 animal, 247.1ms
5: 384x640 1 animal, 247.1ms
6: 384x640 (no detections), 247.1ms
7: 384x640 (no detections), 247.1ms
8: 384x640 (no detections), 247.1ms
9: 384x640 (no detections), 247.1ms
10: 384x640 (no detections), 247.1ms
11: 384x640 (no detections), 247.1ms
12: 384x640 (no detections), 247.1ms
13: 384x640 (no detections), 247.1ms
14: 384x640 1 animal, 247.1ms
15: 384x640 2 animals, 247.1ms
Speed: 2.0ms preprocess, 247.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  4%|█████▌                                                                                                                                    | 2/50 [00:12<04:37,  5.78s/it]

0: 384x640 (no detections), 246.5ms
1: 384x640 (no detections), 246.5ms
2: 384x640 (no detections), 246.5ms
3: 384x640 (no detections), 246.5ms
4: 384x640 (no detections), 246.5ms
5: 384x640 (no detections), 246.5ms
6: 384x640 (no detections), 246.5ms
7: 384x640 (no detections), 246.5ms
8: 384x640 2 animals, 246.5ms
9: 384x640 1 animal, 246.5ms
10: 384x640 1 animal, 246.5ms
11: 384x640 (no detections), 246.5ms
12: 384x640 (no detections), 246.5ms
13: 384x640 (no detections), 246.5ms
14: 384x640 (no detections), 246.5ms
15: 384x640 (no detections), 246.5ms
Speed: 1.9ms preprocess, 246.5ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

  6%|████████▎                                                                                                                                 | 3/50 [00:16<04:08,  5.28s/it]

0: 384x640 (no detections), 245.7ms
1: 384x640 (no detections), 245.7ms
2: 384x640 1 animal, 245.7ms
3: 384x640 1 animal, 245.7ms
4: 384x640 1 animal, 245.7ms
5: 384x640 (no detections), 245.7ms
6: 384x640 (no detections), 245.7ms
7: 384x640 (no detections), 245.7ms
8: 384x640 (no detections), 245.7ms
9: 384x640 (no detections), 245.7ms
10: 384x640 (no detections), 245.7ms
11: 384x640 (no detections), 245.7ms
12: 384x640 1 animal, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 2 animals, 245.7ms
Speed: 2.2ms preprocess, 245.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

  8%|███████████                                                                                                                               | 4/50 [00:21<03:52,  5.05s/it]

0: 384x640 1 animal, 247.6ms
1: 384x640 1 animal, 247.6ms
2: 384x640 1 animal, 247.6ms
3: 384x640 1 animal, 247.6ms
4: 384x640 1 animal, 247.6ms
5: 384x640 1 animal, 247.6ms
6: 384x640 1 animal, 247.6ms
7: 384x640 1 animal, 247.6ms
8: 384x640 1 animal, 247.6ms
9: 384x640 (no detections), 247.6ms
10: 384x640 (no detections), 247.6ms
11: 384x640 (no detections), 247.6ms
12: 384x640 (no detections), 247.6ms
13: 384x640 (no detections), 247.6ms
14: 384x640 (no detections), 247.6ms
15: 384x640 (no detections), 247.6ms
Speed: 1.9ms preprocess, 247.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 10%|█████████████▊                                                                                                                            | 5/50 [00:26<03:42,  4.95s/it]

0: 384x640 (no detections), 245.9ms
1: 384x640 1 animal, 245.9ms
2: 384x640 1 animal, 245.9ms
3: 384x640 1 animal, 245.9ms
4: 384x640 1 animal, 245.9ms
5: 384x640 1 animal, 245.9ms
6: 384x640 (no detections), 245.9ms
7: 384x640 (no detections), 245.9ms
8: 384x640 (no detections), 245.9ms
9: 384x640 (no detections), 245.9ms
10: 384x640 1 animal, 245.9ms
11: 384x640 1 animal, 245.9ms
12: 384x640 1 animal, 245.9ms
13: 384x640 1 animal, 245.9ms
14: 384x640 1 animal, 245.9ms
15: 384x640 1 animal, 245.9ms
Speed: 2.1ms preprocess, 245.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 12%|████████████████▌                                                                                                                         | 6/50 [00:30<03:33,  4.85s/it]

0: 384x640 (no detections), 247.5ms
1: 384x640 (no detections), 247.5ms
2: 384x640 (no detections), 247.5ms
3: 384x640 (no detections), 247.5ms
4: 384x640 2 animals, 247.5ms
5: 384x640 1 animal, 247.5ms
6: 384x640 1 animal, 247.5ms
7: 384x640 1 animal, 247.5ms
8: 384x640 1 animal, 247.5ms
9: 384x640 1 animal, 247.5ms
10: 384x640 2 animals, 247.5ms
11: 384x640 1 animal, 247.5ms
12: 384x640 (no detections), 247.5ms
13: 384x640 (no detections), 247.5ms
14: 384x640 1 animal, 247.5ms
15: 384x640 (no detections), 247.5ms
Speed: 2.1ms preprocess, 247.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 14%|███████████████████▎                                                                                                                      | 7/50 [00:35<03:26,  4.80s/it]

0: 640x640 (no detections), 425.6ms
1: 640x640 (no detections), 425.6ms
2: 640x640 (no detections), 425.6ms
3: 640x640 (no detections), 425.6ms
4: 640x640 (no detections), 425.6ms
5: 640x640 (no detections), 425.6ms
6: 640x640 (no detections), 425.6ms
7: 640x640 (no detections), 425.6ms
8: 640x640 1 animal, 425.6ms
9: 640x640 1 animal, 425.6ms
10: 640x640 (no detections), 425.6ms
11: 640x640 (no detections), 425.6ms
12: 640x640 (no detections), 425.6ms
13: 640x640 (no detections), 425.6ms
14: 640x640 (no detections), 425.6ms
15: 640x640 (no detections), 425.6ms
Speed: 2.7ms preprocess, 425.6ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 16%|██████████████████████                                                                                                                    | 8/50 [00:42<03:56,  5.62s/it]

0: 640x640 (no detections), 427.4ms
1: 640x640 (no detections), 427.4ms
2: 640x640 1 animal, 427.4ms
3: 640x640 1 animal, 427.4ms
4: 640x640 1 animal, 427.4ms
5: 640x640 1 animal, 427.4ms
6: 640x640 1 animal, 427.4ms
7: 640x640 1 animal, 427.4ms
8: 640x640 1 animal, 427.4ms
9: 640x640 1 animal, 427.4ms
10: 640x640 1 animal, 427.4ms
11: 640x640 1 animal, 427.4ms
12: 640x640 1 animal, 427.4ms
13: 640x640 1 animal, 427.4ms
14: 640x640 (no detections), 427.4ms
15: 640x640 (no detections), 427.4ms
Speed: 3.0ms preprocess, 427.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 18%|████████████████████████▊                                                                                                                 | 9/50 [00:50<04:15,  6.23s/it]

0: 384x640 (no detections), 247.1ms
1: 384x640 (no detections), 247.1ms
2: 384x640 (no detections), 247.1ms
3: 384x640 (no detections), 247.1ms
4: 384x640 (no detections), 247.1ms
5: 384x640 (no detections), 247.1ms
6: 384x640 1 animal, 247.1ms
7: 384x640 1 animal, 247.1ms
8: 384x640 1 animal, 247.1ms
9: 384x640 1 animal, 247.1ms
10: 384x640 1 animal, 247.1ms
11: 384x640 (no detections), 247.1ms
12: 384x640 (no detections), 247.1ms
13: 384x640 (no detections), 247.1ms
14: 384x640 (no detections), 247.1ms
15: 384x640 (no detections), 247.1ms
Speed: 2.1ms preprocess, 247.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 20%|███████████████████████████▍                                                                                                             | 10/50 [00:55<03:50,  5.75s/it]

0: 384x640 2 animals, 246.3ms
1: 384x640 2 animals, 246.3ms
2: 384x640 (no detections), 246.3ms
3: 384x640 (no detections), 246.3ms
4: 384x640 (no detections), 246.3ms
5: 384x640 (no detections), 246.3ms
6: 384x640 (no detections), 246.3ms
7: 384x640 (no detections), 246.3ms
8: 384x640 (no detections), 246.3ms
9: 384x640 (no detections), 246.3ms
10: 384x640 1 animal, 246.3ms
11: 384x640 1 animal, 246.3ms
12: 384x640 1 animal, 246.3ms
13: 384x640 1 animal, 246.3ms
14: 384x640 1 animal, 246.3ms
15: 384x640 1 animal, 246.3ms
Speed: 1.9ms preprocess, 246.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 22%|██████████████████████████████▏                                                                                                          | 11/50 [00:59<03:31,  5.42s/it]

0: 640x640 1 animal, 427.1ms
1: 640x640 1 animal, 427.1ms
2: 640x640 1 animal, 427.1ms
3: 640x640 (no detections), 427.1ms
4: 640x640 2 animals, 427.1ms
5: 640x640 1 animal, 427.1ms
6: 640x640 1 animal, 427.1ms
7: 640x640 (no detections), 427.1ms
8: 640x640 1 animal, 427.1ms
9: 640x640 (no detections), 427.1ms
10: 640x640 (no detections), 427.1ms
11: 640x640 (no detections), 427.1ms
12: 640x640 (no detections), 427.1ms
13: 640x640 (no detections), 427.1ms
14: 640x640 1 animal, 427.1ms
15: 640x640 1 animal, 427.1ms
Speed: 2.7ms preprocess, 427.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 24%|████████████████████████████████▉                                                                                                        | 12/50 [01:07<03:50,  6.06s/it]

0: 384x640 (no detections), 242.1ms
1: 384x640 (no detections), 242.1ms
2: 384x640 (no detections), 242.1ms
3: 384x640 (no detections), 242.1ms
4: 384x640 (no detections), 242.1ms
5: 384x640 (no detections), 242.1ms
6: 384x640 (no detections), 242.1ms
7: 384x640 (no detections), 242.1ms
8: 384x640 1 animal, 242.1ms
9: 384x640 1 animal, 242.1ms
10: 384x640 1 animal, 242.1ms
11: 384x640 1 animal, 242.1ms
12: 384x640 1 animal, 242.1ms
13: 384x640 1 animal, 242.1ms
14: 384x640 1 animal, 242.1ms
15: 384x640 1 animal, 242.1ms
Speed: 1.9ms preprocess, 242.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 26%|███████████████████████████████████▌                                                                                                     | 13/50 [01:11<03:24,  5.52s/it]

0: 640x640 1 animal, 427.9ms
1: 640x640 1 animal, 427.9ms
2: 640x640 1 animal, 427.9ms
3: 640x640 1 animal, 427.9ms
4: 640x640 (no detections), 427.9ms
5: 640x640 (no detections), 427.9ms
6: 640x640 (no detections), 427.9ms
7: 640x640 (no detections), 427.9ms
8: 640x640 (no detections), 427.9ms
9: 640x640 (no detections), 427.9ms
10: 640x640 (no detections), 427.9ms
11: 640x640 (no detections), 427.9ms
12: 640x640 (no detections), 427.9ms
13: 640x640 (no detections), 427.9ms
14: 640x640 (no detections), 427.9ms
15: 640x640 (no detections), 427.9ms
Speed: 2.5ms preprocess, 427.9ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 28%|██████████████████████████████████████▎                                                                                                  | 14/50 [01:19<03:40,  6.12s/it]

0: 384x640 (no detections), 245.1ms
1: 384x640 (no detections), 245.1ms
2: 384x640 (no detections), 245.1ms
3: 384x640 (no detections), 245.1ms
4: 384x640 (no detections), 245.1ms
5: 384x640 1 animal, 245.1ms
6: 384x640 (no detections), 245.1ms
7: 384x640 (no detections), 245.1ms
8: 384x640 (no detections), 245.1ms
9: 384x640 1 animal, 245.1ms
10: 384x640 1 animal, 245.1ms
11: 384x640 (no detections), 245.1ms
12: 384x640 (no detections), 245.1ms
13: 384x640 (no detections), 245.1ms
14: 384x640 (no detections), 245.1ms
15: 384x640 (no detections), 245.1ms
Speed: 1.8ms preprocess, 245.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 30%|█████████████████████████████████████████                                                                                                | 15/50 [01:23<03:18,  5.67s/it]

0: 384x640 2 animals, 245.7ms
1: 384x640 (no detections), 245.7ms
2: 384x640 1 animal, 245.7ms
3: 384x640 (no detections), 245.7ms
4: 384x640 (no detections), 245.7ms
5: 384x640 (no detections), 245.7ms
6: 384x640 (no detections), 245.7ms
7: 384x640 (no detections), 245.7ms
8: 384x640 (no detections), 245.7ms
9: 384x640 (no detections), 245.7ms
10: 384x640 1 animal, 245.7ms
11: 384x640 1 animal, 245.7ms
12: 384x640 1 animal, 245.7ms
13: 384x640 1 animal, 245.7ms
14: 384x640 1 animal, 245.7ms
15: 384x640 1 animal, 245.7ms
Speed: 2.2ms preprocess, 245.7ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 32%|███████████████████████████████████████████▊                                                                                             | 16/50 [01:28<03:02,  5.37s/it]

0: 640x640 (no detections), 416.1ms
1: 640x640 (no detections), 416.1ms
2: 640x640 (no detections), 416.1ms
3: 640x640 (no detections), 416.1ms
4: 640x640 1 animal, 416.1ms
5: 640x640 3 animals, 416.1ms
6: 640x640 1 animal, 416.1ms
7: 640x640 1 animal, 416.1ms
8: 640x640 1 animal, 416.1ms
9: 640x640 1 animal, 416.1ms
10: 640x640 (no detections), 416.1ms
11: 640x640 (no detections), 416.1ms
12: 640x640 (no detections), 416.1ms
13: 640x640 (no detections), 416.1ms
14: 640x640 1 animal, 416.1ms
15: 640x640 1 animal, 416.1ms
Speed: 2.5ms preprocess, 416.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 34%|██████████████████████████████████████████████▌                                                                                          | 17/50 [01:35<03:16,  5.96s/it]

0: 384x640 (no detections), 240.6ms
1: 384x640 (no detections), 240.6ms
2: 384x640 (no detections), 240.6ms
3: 384x640 (no detections), 240.6ms
4: 384x640 (no detections), 240.6ms
5: 384x640 (no detections), 240.6ms
6: 384x640 (no detections), 240.6ms
7: 384x640 (no detections), 240.6ms
8: 384x640 1 animal, 240.6ms
9: 384x640 (no detections), 240.6ms
10: 384x640 (no detections), 240.6ms
11: 384x640 (no detections), 240.6ms
12: 384x640 (no detections), 240.6ms
13: 384x640 (no detections), 240.6ms
14: 384x640 (no detections), 240.6ms
15: 384x640 (no detections), 240.6ms
Speed: 1.8ms preprocess, 240.6ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 36%|█████████████████████████████████████████████████▎                                                                                       | 18/50 [01:40<02:54,  5.44s/it]

0: 640x640 (no detections), 427.5ms
1: 640x640 (no detections), 427.5ms
2: 640x640 1 animal, 427.5ms
3: 640x640 1 animal, 427.5ms
4: 640x640 1 animal, 427.5ms
5: 640x640 1 animal, 427.5ms
6: 640x640 1 animal, 427.5ms
7: 640x640 1 animal, 427.5ms
8: 640x640 1 animal, 427.5ms
9: 640x640 (no detections), 427.5ms
10: 640x640 1 animal, 427.5ms
11: 640x640 (no detections), 427.5ms
12: 640x640 1 animal, 427.5ms
13: 640x640 (no detections), 427.5ms
14: 640x640 (no detections), 427.5ms
15: 640x640 (no detections), 427.5ms
Speed: 2.6ms preprocess, 427.5ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 38%|████████████████████████████████████████████████████                                                                                     | 19/50 [01:47<03:07,  6.05s/it]

0: 640x640 (no detections), 429.1ms
1: 640x640 (no detections), 429.1ms
2: 640x640 (no detections), 429.1ms
3: 640x640 (no detections), 429.1ms
4: 640x640 (no detections), 429.1ms
5: 640x640 (no detections), 429.1ms
6: 640x640 1 animal, 429.1ms
7: 640x640 2 animals, 429.1ms
8: 640x640 1 animal, 429.1ms
9: 640x640 2 animals, 429.1ms
10: 640x640 1 animal, 429.1ms
11: 640x640 1 animal, 429.1ms
12: 640x640 (no detections), 429.1ms
13: 640x640 1 animal, 429.1ms
14: 640x640 1 animal, 429.1ms
15: 640x640 1 animal, 429.1ms
Speed: 2.5ms preprocess, 429.1ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 40%|██████████████████████████████████████████████████████▊                                                                                  | 20/50 [01:54<03:14,  6.48s/it]

0: 384x640 1 animal, 243.2ms
1: 384x640 (no detections), 243.2ms
2: 384x640 (no detections), 243.2ms
3: 384x640 (no detections), 243.2ms
4: 384x640 (no detections), 243.2ms
5: 384x640 (no detections), 243.2ms
6: 384x640 (no detections), 243.2ms
7: 384x640 (no detections), 243.2ms
8: 384x640 (no detections), 243.2ms
9: 384x640 (no detections), 243.2ms
10: 384x640 1 animal, 243.2ms
11: 384x640 2 animals, 243.2ms
12: 384x640 (no detections), 243.2ms
13: 384x640 (no detections), 243.2ms
14: 384x640 (no detections), 243.2ms
15: 384x640 (no detections), 243.2ms
Speed: 2.0ms preprocess, 243.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 42%|█████████████████████████████████████████████████████████▌                                                                               | 21/50 [01:59<02:48,  5.82s/it]

0: 384x640 (no detections), 247.1ms
1: 384x640 (no detections), 247.1ms
2: 384x640 (no detections), 247.1ms
3: 384x640 (no detections), 247.1ms
4: 384x640 1 animal, 247.1ms
5: 384x640 1 animal, 247.1ms
6: 384x640 1 animal, 247.1ms
7: 384x640 2 animals, 247.1ms
8: 384x640 1 animal, 247.1ms
9: 384x640 (no detections), 247.1ms
10: 384x640 (no detections), 247.1ms
11: 384x640 (no detections), 247.1ms
12: 384x640 (no detections), 247.1ms
13: 384x640 (no detections), 247.1ms
14: 384x640 1 animal, 247.1ms
15: 384x640 (no detections), 247.1ms
Speed: 2.0ms preprocess, 247.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 44%|████████████████████████████████████████████████████████████▎                                                                            | 22/50 [02:03<02:30,  5.37s/it]

0: 384x640 (no detections), 244.3ms
1: 384x640 (no detections), 244.3ms
2: 384x640 (no detections), 244.3ms
3: 384x640 (no detections), 244.3ms
4: 384x640 (no detections), 244.3ms
5: 384x640 (no detections), 244.3ms
6: 384x640 (no detections), 244.3ms
7: 384x640 (no detections), 244.3ms
8: 384x640 1 animal, 244.3ms
9: 384x640 2 animals, 244.3ms
10: 384x640 (no detections), 244.3ms
11: 384x640 (no detections), 244.3ms
12: 384x640 (no detections), 244.3ms
13: 384x640 (no detections), 244.3ms
14: 384x640 (no detections), 244.3ms
15: 384x640 (no detections), 244.3ms
Speed: 1.9ms preprocess, 244.3ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 46%|███████████████████████████████████████████████████████████████                                                                          | 23/50 [02:07<02:16,  5.05s/it]

0: 384x640 (no detections), 243.0ms
1: 384x640 (no detections), 243.0ms
2: 384x640 1 animal, 243.0ms
3: 384x640 1 animal, 243.0ms
4: 384x640 (no detections), 243.0ms
5: 384x640 (no detections), 243.0ms
6: 384x640 (no detections), 243.0ms
7: 384x640 (no detections), 243.0ms
8: 384x640 (no detections), 243.0ms
9: 384x640 (no detections), 243.0ms
10: 384x640 (no detections), 243.0ms
11: 384x640 (no detections), 243.0ms
12: 384x640 1 animal, 243.0ms
13: 384x640 1 animal, 243.0ms
14: 384x640 (no detections), 243.0ms
15: 384x640 (no detections), 243.0ms
Speed: 1.9ms preprocess, 243.0ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 48%|█████████████████████████████████████████████████████████████████▊                                                                       | 24/50 [02:12<02:05,  4.82s/it]

0: 384x640 (no detections), 243.9ms
1: 384x640 (no detections), 243.9ms
2: 384x640 (no detections), 243.9ms
3: 384x640 (no detections), 243.9ms
4: 384x640 (no detections), 243.9ms
5: 384x640 (no detections), 243.9ms
6: 384x640 1 animal, 243.9ms
7: 384x640 (no detections), 243.9ms
8: 384x640 (no detections), 243.9ms
9: 384x640 (no detections), 243.9ms
10: 384x640 (no detections), 243.9ms
11: 384x640 (no detections), 243.9ms
12: 384x640 (no detections), 243.9ms
13: 384x640 (no detections), 243.9ms
14: 384x640 (no detections), 243.9ms
15: 384x640 (no detections), 243.9ms
Speed: 2.0ms preprocess, 243.9ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 50%|████████████████████████████████████████████████████████████████████▌                                                                    | 25/50 [02:16<01:56,  4.66s/it]

0: 384x640 1 animal, 243.2ms
1: 384x640 (no detections), 243.2ms
2: 384x640 (no detections), 243.2ms
3: 384x640 (no detections), 243.2ms
4: 384x640 (no detections), 243.2ms
5: 384x640 (no detections), 243.2ms
6: 384x640 (no detections), 243.2ms
7: 384x640 (no detections), 243.2ms
8: 384x640 (no detections), 243.2ms
9: 384x640 (no detections), 243.2ms
10: 384x640 (no detections), 243.2ms
11: 384x640 (no detections), 243.2ms
12: 384x640 (no detections), 243.2ms
13: 384x640 (no detections), 243.2ms
14: 384x640 (no detections), 243.2ms
15: 384x640 (no detections), 243.2ms
Speed: 2.0ms preprocess, 243.2ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 52%|███████████████████████████████████████████████████████████████████████▏                                                                 | 26/50 [02:20<01:49,  4.54s/it]

0: 640x640 (no detections), 432.8ms
1: 640x640 (no detections), 432.8ms
2: 640x640 (no detections), 432.8ms
3: 640x640 (no detections), 432.8ms
4: 640x640 1 animal, 432.8ms
5: 640x640 1 animal, 432.8ms
6: 640x640 (no detections), 432.8ms
7: 640x640 1 animal, 432.8ms
8: 640x640 1 animal, 432.8ms
9: 640x640 1 animal, 432.8ms
10: 640x640 (no detections), 432.8ms
11: 640x640 1 animal, 432.8ms
12: 640x640 1 animal, 432.8ms
13: 640x640 1 animal, 432.8ms
14: 640x640 1 animal, 432.8ms
15: 640x640 1 animal, 432.8ms
Speed: 2.7ms preprocess, 432.8ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 54%|█████████████████████████████████████████████████████████████████████████▉                                                               | 27/50 [02:28<02:05,  5.44s/it]

0: 384x640 1 animal, 243.6ms
1: 384x640 1 animal, 243.6ms
2: 384x640 1 animal, 243.6ms
3: 384x640 (no detections), 243.6ms
4: 384x640 (no detections), 243.6ms
5: 384x640 (no detections), 243.6ms
6: 384x640 (no detections), 243.6ms
7: 384x640 (no detections), 243.6ms
8: 384x640 1 animal, 243.6ms
9: 384x640 1 animal, 243.6ms
10: 384x640 (no detections), 243.6ms
11: 384x640 (no detections), 243.6ms
12: 384x640 (no detections), 243.6ms
13: 384x640 (no detections), 243.6ms
14: 384x640 (no detections), 243.6ms
15: 384x640 (no detections), 243.6ms
Speed: 2.4ms preprocess, 243.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 56%|████████████████████████████████████████████████████████████████████████████▋                                                            | 28/50 [02:32<01:52,  5.11s/it]

0: 384x640 (no detections), 244.1ms
1: 384x640 (no detections), 244.1ms
2: 384x640 1 animal, 244.1ms
3: 384x640 1 animal, 244.1ms
4: 384x640 1 animal, 244.1ms
5: 384x640 (no detections), 244.1ms
6: 384x640 (no detections), 244.1ms
7: 384x640 (no detections), 244.1ms
8: 384x640 (no detections), 244.1ms
9: 384x640 (no detections), 244.1ms
10: 384x640 (no detections), 244.1ms
11: 384x640 1 animal, 244.1ms
12: 384x640 1 animal, 244.1ms
13: 384x640 1 animal, 244.1ms
14: 384x640 (no detections), 244.1ms
15: 384x640 (no detections), 244.1ms
Speed: 1.9ms preprocess, 244.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 58%|███████████████████████████████████████████████████████████████████████████████▍                                                         | 29/50 [02:36<01:42,  4.86s/it]

0: 640x640 (no detections), 430.1ms
1: 640x640 (no detections), 430.1ms
2: 640x640 (no detections), 430.1ms
3: 640x640 (no detections), 430.1ms
4: 640x640 (no detections), 430.1ms
5: 640x640 (no detections), 430.1ms
6: 640x640 (no detections), 430.1ms
7: 640x640 1 animal, 430.1ms
8: 640x640 (no detections), 430.1ms
9: 640x640 (no detections), 430.1ms
10: 640x640 (no detections), 430.1ms
11: 640x640 (no detections), 430.1ms
12: 640x640 (no detections), 430.1ms
13: 640x640 1 animal, 430.1ms
14: 640x640 (no detections), 430.1ms
15: 640x640 (no detections), 430.1ms
Speed: 2.7ms preprocess, 430.1ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 60%|██████████████████████████████████████████████████████████████████████████████████▏                                                      | 30/50 [02:44<01:53,  5.65s/it]

0: 384x640 1 animal, 244.6ms
1: 384x640 1 animal, 244.6ms
2: 384x640 2 animals, 244.6ms
3: 384x640 1 animal, 244.6ms
4: 384x640 (no detections), 244.6ms
5: 384x640 (no detections), 244.6ms
6: 384x640 1 animal, 244.6ms
7: 384x640 1 animal, 244.6ms
8: 384x640 1 animal, 244.6ms
9: 384x640 (no detections), 244.6ms
10: 384x640 1 animal, 244.6ms
11: 384x640 1 animal, 244.6ms
12: 384x640 (no detections), 244.6ms
13: 384x640 (no detections), 244.6ms
14: 384x640 (no detections), 244.6ms
15: 384x640 (no detections), 244.6ms
Speed: 1.9ms preprocess, 244.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 62%|████████████████████████████████████████████████████████████████████████████████████▉                                                    | 31/50 [02:48<01:39,  5.25s/it]

0: 384x640 (no detections), 243.8ms
1: 384x640 (no detections), 243.8ms
2: 384x640 (no detections), 243.8ms
3: 384x640 (no detections), 243.8ms
4: 384x640 1 animal, 243.8ms
5: 384x640 1 animal, 243.8ms
6: 384x640 (no detections), 243.8ms
7: 384x640 (no detections), 243.8ms
8: 384x640 (no detections), 243.8ms
9: 384x640 (no detections), 243.8ms
10: 384x640 (no detections), 243.8ms
11: 384x640 (no detections), 243.8ms
12: 384x640 (no detections), 243.8ms
13: 384x640 (no detections), 243.8ms
14: 384x640 1 animal, 243.8ms
15: 384x640 1 animal, 243.8ms
Speed: 2.0ms preprocess, 243.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 64%|███████████████████████████████████████████████████████████████████████████████████████▋                                                 | 32/50 [02:52<01:29,  4.96s/it]

0: 384x640 (no detections), 243.1ms
1: 384x640 (no detections), 243.1ms
2: 384x640 (no detections), 243.1ms
3: 384x640 (no detections), 243.1ms
4: 384x640 (no detections), 243.1ms
5: 384x640 (no detections), 243.1ms
6: 384x640 (no detections), 243.1ms
7: 384x640 (no detections), 243.1ms
8: 384x640 1 animal, 243.1ms
9: 384x640 1 animal, 243.1ms
10: 384x640 (no detections), 243.1ms
11: 384x640 (no detections), 243.1ms
12: 384x640 (no detections), 243.1ms
13: 384x640 (no detections), 243.1ms
14: 384x640 (no detections), 243.1ms
15: 384x640 (no detections), 243.1ms
Speed: 2.1ms preprocess, 243.1ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 66%|██████████████████████████████████████████████████████████████████████████████████████████▍                                              | 33/50 [02:57<01:20,  4.76s/it]

0: 640x640 (no detections), 427.9ms
1: 640x640 (no detections), 427.9ms
2: 640x640 1 animal, 427.9ms
3: 640x640 1 animal, 427.9ms
4: 640x640 (no detections), 427.9ms
5: 640x640 (no detections), 427.9ms
6: 640x640 (no detections), 427.9ms
7: 640x640 (no detections), 427.9ms
8: 640x640 (no detections), 427.9ms
9: 640x640 (no detections), 427.9ms
10: 640x640 (no detections), 427.9ms
11: 640x640 (no detections), 427.9ms
12: 640x640 1 animal, 427.9ms
13: 640x640 1 animal, 427.9ms
14: 640x640 1 animal, 427.9ms
15: 640x640 (no detections), 427.9ms
Speed: 2.6ms preprocess, 427.9ms inference, 0.3ms postprocess per image at shape (16, 3, 640, 640)

 68%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                           | 34/50 [03:04<01:28,  5.53s/it]

0: 640x640 (no detections), 425.8ms
1: 640x640 (no detections), 425.8ms
2: 640x640 (no detections), 425.8ms
3: 640x640 (no detections), 425.8ms
4: 640x640 (no detections), 425.8ms
5: 640x640 (no detections), 425.8ms
6: 640x640 1 animal, 425.8ms
7: 640x640 1 animal, 425.8ms
8: 640x640 (no detections), 425.8ms
9: 640x640 (no detections), 425.8ms
10: 640x640 (no detections), 425.8ms
11: 640x640 (no detections), 425.8ms
12: 640x640 (no detections), 425.8ms
13: 640x640 (no detections), 425.8ms
14: 640x640 (no detections), 425.8ms
15: 640x640 (no detections), 425.8ms
Speed: 2.6ms preprocess, 425.8ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 70%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                         | 35/50 [03:11<01:31,  6.08s/it]

0: 640x640 1 animal, 429.5ms
1: 640x640 1 animal, 429.5ms
2: 640x640 (no detections), 429.5ms
3: 640x640 1 animal, 429.5ms
4: 640x640 1 animal, 429.5ms
5: 640x640 1 animal, 429.5ms
6: 640x640 1 animal, 429.5ms
7: 640x640 1 animal, 429.5ms
8: 640x640 1 animal, 429.5ms
9: 640x640 1 animal, 429.5ms
10: 640x640 1 animal, 429.5ms
11: 640x640 1 animal, 429.5ms
12: 640x640 1 animal, 429.5ms
13: 640x640 1 animal, 429.5ms
14: 640x640 (no detections), 429.5ms
15: 640x640 (no detections), 429.5ms
Speed: 2.8ms preprocess, 429.5ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 36/50 [03:19<01:31,  6.50s/it]

0: 640x640 (no detections), 429.3ms
1: 640x640 (no detections), 429.3ms
2: 640x640 (no detections), 429.3ms
3: 640x640 (no detections), 429.3ms
4: 640x640 2 animals, 429.3ms
5: 640x640 1 animal, 429.3ms
6: 640x640 (no detections), 429.3ms
7: 640x640 (no detections), 429.3ms
8: 640x640 (no detections), 429.3ms
9: 640x640 (no detections), 429.3ms
10: 640x640 (no detections), 429.3ms
11: 640x640 (no detections), 429.3ms
12: 640x640 (no detections), 429.3ms
13: 640x640 (no detections), 429.3ms
14: 640x640 1 animal, 429.3ms
15: 640x640 1 animal, 429.3ms
Speed: 2.7ms preprocess, 429.3ms inference, 0.2ms postprocess per image at shape (16, 3, 640, 640)

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 37/50 [03:26<01:28,  6.80s/it]

0: 384x640 1 animal, 240.0ms
1: 384x640 1 animal, 240.0ms
2: 384x640 1 animal, 240.0ms
3: 384x640 (no detections), 240.0ms
4: 384x640 (no detections), 240.0ms
5: 384x640 1 animal, 240.0ms
6: 384x640 1 animal, 240.0ms
7: 384x640 (no detections), 240.0ms
8: 384x640 (no detections), 240.0ms
9: 384x640 (no detections), 240.0ms
10: 384x640 (no detections), 240.0ms
11: 384x640 (no detections), 240.0ms
12: 384x640 (no detections), 240.0ms
13: 384x640 (no detections), 240.0ms
14: 384x640 (no detections), 240.0ms
15: 384x640 (no detections), 240.0ms
Speed: 1.7ms preprocess, 240.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 38/50 [03:31<01:12,  6.02s/it]

0: 384x640 (no detections), 240.6ms
1: 384x640 (no detections), 240.6ms
2: 384x640 1 animal, 240.6ms
3: 384x640 1 animal, 240.6ms
4: 384x640 (no detections), 240.6ms
5: 384x640 (no detections), 240.6ms
6: 384x640 (no detections), 240.6ms
7: 384x640 (no detections), 240.6ms
8: 384x640 (no detections), 240.6ms
9: 384x640 (no detections), 240.6ms
10: 384x640 (no detections), 240.6ms
11: 384x640 (no detections), 240.6ms
12: 384x640 1 animal, 240.6ms
13: 384x640 1 animal, 240.6ms
14: 384x640 (no detections), 240.6ms
15: 384x640 (no detections), 240.6ms
Speed: 1.7ms preprocess, 240.6ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 39/50 [03:35<01:00,  5.48s/it]

0: 384x640 (no detections), 242.4ms
1: 384x640 (no detections), 242.4ms
2: 384x640 (no detections), 242.4ms
3: 384x640 (no detections), 242.4ms
4: 384x640 (no detections), 242.4ms
5: 384x640 (no detections), 242.4ms
6: 384x640 1 animal, 242.4ms
7: 384x640 (no detections), 242.4ms
8: 384x640 (no detections), 242.4ms
9: 384x640 (no detections), 242.4ms
10: 384x640 (no detections), 242.4ms
11: 384x640 (no detections), 242.4ms
12: 384x640 (no detections), 242.4ms
13: 384x640 (no detections), 242.4ms
14: 384x640 (no detections), 242.4ms
15: 384x640 (no detections), 242.4ms
Speed: 2.1ms preprocess, 242.4ms inference, 0.2ms postprocess per image at shape (16, 3, 384, 640)

 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 40/50 [03:39<00:51,  5.12s/it]

0: 384x640 1 animal, 244.5ms
1: 384x640 (no detections), 244.5ms
2: 384x640 (no detections), 244.5ms
3: 384x640 (no detections), 244.5ms
4: 384x640 (no detections), 244.5ms
5: 384x640 (no detections), 244.5ms
6: 384x640 (no detections), 244.5ms
7: 384x640 (no detections), 244.5ms
8: 384x640 (no detections), 244.5ms
9: 384x640 (no detections), 244.5ms
10: 384x640 1 animal, 244.5ms
11: 384x640 2 animals, 244.5ms
12: 384x640 2 animals, 244.5ms
13: 384x640 1 animal, 244.5ms
14: 384x640 1 animal, 244.5ms
15: 384x640 1 animal, 244.5ms
Speed: 1.9ms preprocess, 244.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 41/50 [03:44<00:44,  4.99s/it]

0: 640x640 1 animal, 419.6ms
1: 640x640 1 animal, 419.6ms
2: 640x640 1 animal, 419.6ms
3: 640x640 1 animal, 419.6ms
4: 640x640 1 animal, 419.6ms
5: 640x640 1 animal, 419.6ms
6: 640x640 1 animal, 419.6ms
7: 640x640 1 animal, 419.6ms
8: 640x640 2 animals, 419.6ms
9: 640x640 2 animals, 419.6ms
10: 640x640 2 animals, 419.6ms
11: 640x640 2 animals, 419.6ms
12: 640x640 2 animals, 419.6ms
13: 640x640 2 animals, 419.6ms
14: 640x640 (no detections), 419.6ms
15: 640x640 2 animals, 419.6ms
Speed: 2.5ms preprocess, 419.6ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 42/50 [03:51<00:45,  5.66s/it]

0: 384x640 1 animal, 245.0ms
1: 384x640 (no detections), 245.0ms
2: 384x640 (no detections), 245.0ms
3: 384x640 (no detections), 245.0ms
4: 384x640 (no detections), 245.0ms
5: 384x640 (no detections), 245.0ms
6: 384x640 (no detections), 245.0ms
7: 384x640 (no detections), 245.0ms
8: 384x640 1 animal, 245.0ms
9: 384x640 2 animals, 245.0ms
10: 384x640 2 animals, 245.0ms
11: 384x640 1 animal, 245.0ms
12: 384x640 (no detections), 245.0ms
13: 384x640 (no detections), 245.0ms
14: 384x640 (no detections), 245.0ms
15: 384x640 (no detections), 245.0ms
Speed: 1.9ms preprocess, 245.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 43/50 [03:56<00:37,  5.36s/it]

0: 384x640 1 animal, 245.1ms
1: 384x640 1 animal, 245.1ms
2: 384x640 1 animal, 245.1ms
3: 384x640 (no detections), 245.1ms
4: 384x640 (no detections), 245.1ms
5: 384x640 1 animal, 245.1ms
6: 384x640 (no detections), 245.1ms
7: 384x640 (no detections), 245.1ms
8: 384x640 (no detections), 245.1ms
9: 384x640 (no detections), 245.1ms
10: 384x640 (no detections), 245.1ms
11: 384x640 (no detections), 245.1ms
12: 384x640 1 animal, 245.1ms
13: 384x640 1 animal, 245.1ms
14: 384x640 2 animals, 245.1ms
15: 384x640 2 animals, 245.1ms
Speed: 1.9ms preprocess, 245.1ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 44/50 [04:00<00:30,  5.15s/it]

0: 384x640 (no detections), 244.4ms
1: 384x640 (no detections), 244.4ms
2: 384x640 (no detections), 244.4ms
3: 384x640 (no detections), 244.4ms
4: 384x640 (no detections), 244.4ms
5: 384x640 (no detections), 244.4ms
6: 384x640 1 animal, 244.4ms
7: 384x640 2 animals, 244.4ms
8: 384x640 1 animal, 244.4ms
9: 384x640 1 animal, 244.4ms
10: 384x640 1 animal, 244.4ms
11: 384x640 1 animal, 244.4ms
12: 384x640 1 animal, 244.4ms
13: 384x640 1 animal, 244.4ms
14: 384x640 1 animal, 244.4ms
15: 384x640 2 animals, 244.4ms
Speed: 2.0ms preprocess, 244.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 45/50 [04:05<00:24,  5.00s/it]

0: 384x640 2 animals, 244.5ms
1: 384x640 1 animal, 244.5ms
2: 384x640 1 animal, 244.5ms
3: 384x640 2 animals, 244.5ms
4: 384x640 (no detections), 244.5ms
5: 384x640 (no detections), 244.5ms
6: 384x640 (no detections), 244.5ms
7: 384x640 (no detections), 244.5ms
8: 384x640 (no detections), 244.5ms
9: 384x640 (no detections), 244.5ms
10: 384x640 1 animal, 244.5ms
11: 384x640 2 animals, 244.5ms
12: 384x640 1 animal, 244.5ms
13: 384x640 1 animal, 244.5ms
14: 384x640 1 animal, 244.5ms
15: 384x640 1 animal, 244.5ms
Speed: 2.1ms preprocess, 244.5ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 46/50 [04:10<00:19,  4.89s/it]

0: 384x640 1 animal, 243.9ms
1: 384x640 (no detections), 243.9ms
2: 384x640 (no detections), 243.9ms
3: 384x640 (no detections), 243.9ms
4: 384x640 (no detections), 243.9ms
5: 384x640 1 animal, 243.9ms
6: 384x640 1 animal, 243.9ms
7: 384x640 1 animal, 243.9ms
8: 384x640 1 animal, 243.9ms
9: 384x640 (no detections), 243.9ms
10: 384x640 (no detections), 243.9ms
11: 384x640 (no detections), 243.9ms
12: 384x640 (no detections), 243.9ms
13: 384x640 (no detections), 243.9ms
14: 384x640 1 animal, 243.9ms
15: 384x640 1 animal, 243.9ms
Speed: 2.0ms preprocess, 243.9ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 47/50 [04:14<00:14,  4.81s/it]

0: 384x640 1 animal, 243.8ms
1: 384x640 (no detections), 243.8ms
2: 384x640 (no detections), 243.8ms
3: 384x640 (no detections), 243.8ms
4: 384x640 (no detections), 243.8ms
5: 384x640 (no detections), 243.8ms
6: 384x640 (no detections), 243.8ms
7: 384x640 (no detections), 243.8ms
8: 384x640 1 animal, 243.8ms
9: 384x640 1 animal, 243.8ms
10: 384x640 1 animal, 243.8ms
11: 384x640 (no detections), 243.8ms
12: 384x640 (no detections), 243.8ms
13: 384x640 (no detections), 243.8ms
14: 384x640 (no detections), 243.8ms
15: 384x640 (no detections), 243.8ms
Speed: 1.9ms preprocess, 243.8ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 48/50 [04:19<00:09,  4.75s/it]

0: 384x640 (no detections), 244.0ms
1: 384x640 (no detections), 244.0ms
2: 384x640 1 animal, 244.0ms
3: 384x640 1 animal, 244.0ms
4: 384x640 (no detections), 244.0ms
5: 384x640 (no detections), 244.0ms
6: 384x640 (no detections), 244.0ms
7: 384x640 (no detections), 244.0ms
8: 384x640 (no detections), 244.0ms
9: 384x640 (no detections), 244.0ms
10: 384x640 (no detections), 244.0ms
11: 384x640 (no detections), 244.0ms
12: 384x640 1 animal, 244.0ms
13: 384x640 1 animal, 244.0ms
14: 384x640 1 animal, 244.0ms
15: 384x640 (no detections), 244.0ms
Speed: 1.9ms preprocess, 244.0ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 49/50 [04:23<00:04,  4.71s/it]

0: 384x640 (no detections), 242.6ms
1: 384x640 (no detections), 242.6ms
2: 384x640 (no detections), 242.6ms
3: 384x640 (no detections), 242.6ms
4: 384x640 (no detections), 242.6ms
5: 384x640 (no detections), 242.6ms
6: 384x640 1 animal, 242.6ms
7: 384x640 1 animal, 242.6ms
8: 384x640 1 animal, 242.6ms
9: 384x640 1 animal, 242.6ms
10: 384x640 (no detections), 242.6ms
11: 384x640 (no detections), 242.6ms
12: 384x640 (no detections), 242.6ms
13: 384x640 (no detections), 242.6ms
14: 384x640 (no detections), 242.6ms
15: 384x640 (no detections), 242.6ms
Speed: 1.8ms preprocess, 242.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

00%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [04:28<00:00,  5.37s/it]

Detecting images from LYNX_RUFUS_extracted

  0%|                                                                                                                                                  | 0/10 [00:00<?, ?it/s]

0: 384x640 1 animal, 244.6ms
1: 384x640 1 animal, 244.6ms
2: 384x640 1 animal, 244.6ms
3: 384x640 1 animal, 244.6ms
4: 384x640 2 animals, 244.6ms
5: 384x640 (no detections), 244.6ms
6: 384x640 (no detections), 244.6ms
7: 384x640 (no detections), 244.6ms
8: 384x640 (no detections), 244.6ms
9: 384x640 (no detections), 244.6ms
10: 384x640 1 animal, 244.6ms
11: 384x640 1 animal, 244.6ms
12: 384x640 1 animal, 244.6ms
13: 384x640 1 animal, 244.6ms
14: 384x640 1 animal, 244.6ms
15: 384x640 (no detections), 244.6ms
Speed: 2.0ms preprocess, 244.6ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 10%|█████████████▊                                                                                                                            | 1/10 [00:04<00:41,  4.66s/it]

0: 384x640 (no detections), 241.3ms
1: 384x640 (no detections), 241.3ms
2: 384x640 (no detections), 241.3ms
3: 384x640 (no detections), 241.3ms
4: 384x640 1 animal, 241.3ms
5: 384x640 1 animal, 241.3ms
6: 384x640 1 animal, 241.3ms
7: 384x640 1 animal, 241.3ms
8: 384x640 1 animal, 241.3ms
9: 384x640 1 animal, 241.3ms
10: 384x640 1 animal, 241.3ms
11: 384x640 (no detections), 241.3ms
12: 384x640 (no detections), 241.3ms
13: 384x640 (no detections), 241.3ms
14: 384x640 1 animal, 241.3ms
15: 384x640 2 animals, 241.3ms
Speed: 2.0ms preprocess, 241.3ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 20%|███████████████████████████▌                                                                                                              | 2/10 [00:09<00:36,  4.62s/it]

0: 384x640 (no detections), 243.4ms
1: 384x640 (no detections), 243.4ms
2: 384x640 (no detections), 243.4ms
3: 384x640 (no detections), 243.4ms
4: 384x640 (no detections), 243.4ms
5: 384x640 (no detections), 243.4ms
6: 384x640 (no detections), 243.4ms
7: 384x640 (no detections), 243.4ms
8: 384x640 1 animal, 243.4ms
9: 384x640 1 animal, 243.4ms
10: 384x640 1 animal, 243.4ms
11: 384x640 1 animal, 243.4ms
12: 384x640 1 animal, 243.4ms
13: 384x640 1 animal, 243.4ms
14: 384x640 1 animal, 243.4ms
15: 384x640 1 animal, 243.4ms
Speed: 2.0ms preprocess, 243.4ms inference, 0.3ms postprocess per image at shape (16, 3, 384, 640)

 30%|█████████████████████████████████████████▍                                                                                                | 3/10 [00:13<00:32,  4.62s/it]

0: 384x640 1 animal, 244.5ms
1: 384x640 (no detections), 244.5ms
2: 384x640 1 animal, 244.5ms
3: 384x640 1 animal, 244.5ms
4: 384x640 1 animal, 244.5ms
5: 384x640 1 animal, 244.5ms
6: 384x640 1 animal, 244.5ms
7: 384x640 2 animals, 244.5ms
8: 384x640 1 animal, 244.5ms
9: 384x640 1 animal, 244.5ms
10: 384x640 1 animal, 244.5ms
11: 384x640 (no detections), 244.5ms
12: 384x640 1 animal, 244.5ms
13: 384x640 1 animal, 244.5ms
14: 384x640 1 animal, 244.5ms
15: 384x640 1 animal, 244.5ms
Speed: 1.9ms preprocess, 244.5ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 40%|███████████████████████████████████████████████████████▏                                                                                  | 4/10 [00:18<00:28,  4.68s/it]

0: 384x640 1 animal, 244.2ms
1: 384x640 1 animal, 244.2ms
2: 384x640 (no detections), 244.2ms
3: 384x640 (no detections), 244.2ms
4: 384x640 (no detections), 244.2ms
5: 384x640 (no detections), 244.2ms
6: 384x640 2 animals, 244.2ms
7: 384x640 1 animal, 244.2ms
8: 384x640 1 animal, 244.2ms
9: 384x640 1 animal, 244.2ms
10: 384x640 2 animals, 244.2ms
11: 384x640 2 animals, 244.2ms
12: 384x640 1 animal, 244.2ms
13: 384x640 1 animal, 244.2ms
14: 384x640 1 animal, 244.2ms
15: 384x640 1 animal, 244.2ms
Speed: 1.9ms preprocess, 244.2ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 50%|█████████████████████████████████████████████████████████████████████                                                                     | 5/10 [00:23<00:23,  4.71s/it]

0: 384x640 1 animal, 244.8ms
1: 384x640 1 animal, 244.8ms
2: 384x640 1 animal, 244.8ms
3: 384x640 1 animal, 244.8ms
4: 384x640 1 animal, 244.8ms
5: 384x640 1 animal, 244.8ms
6: 384x640 1 animal, 244.8ms
7: 384x640 1 animal, 244.8ms
8: 384x640 1 animal, 244.8ms
9: 384x640 1 animal, 244.8ms
10: 384x640 1 animal, 244.8ms
11: 384x640 1 animal, 244.8ms
12: 384x640 1 animal, 244.8ms
13: 384x640 1 animal, 244.8ms
14: 384x640 1 animal, 244.8ms
15: 384x640 2 animals, 244.8ms
Speed: 1.9ms preprocess, 244.8ms inference, 0.4ms postprocess per image at shape (16, 3, 384, 640)

 60%|██████████████████████████████████████████████████████████████████████████████████▊                                                       | 6/10 [00:28<00:18,  4.71s/it]

0: 640x640 1 animal, 424.8ms
1: 640x640 (no detections), 424.8ms
2: 640x640 (no detections), 424.8ms
3: 640x640 (no detections), 424.8ms
4: 640x640 1 animal, 424.8ms
5: 640x640 1 animal, 424.8ms
6: 640x640 2 animals, 424.8ms
7: 640x640 1 animal, 424.8ms
8: 640x640 1 animal, 424.8ms
9: 640x640 1 animal, 424.8ms
10: 640x640 1 animal, 424.8ms
11: 640x640 1 animal, 424.8ms
12: 640x640 1 animal, 424.8ms
13: 640x640 1 animal, 424.8ms
14: 640x640 1 animal, 424.8ms
15: 640x640 1 animal, 424.8ms
Speed: 2.6ms preprocess, 424.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 70%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 7/10 [00:35<00:17,  5.68s/it]

0: 640x640 1 animal, 424.4ms
1: 640x640 1 animal, 424.4ms
2: 640x640 1 animal, 424.4ms
3: 640x640 1 animal, 424.4ms
4: 640x640 1 animal, 424.4ms
5: 640x640 (no detections), 424.4ms
6: 640x640 1 animal, 424.4ms
7: 640x640 (no detections), 424.4ms
8: 640x640 1 animal, 424.4ms
9: 640x640 1 animal, 424.4ms
10: 640x640 1 animal, 424.4ms
11: 640x640 1 animal, 424.4ms
12: 640x640 1 animal, 424.4ms
13: 640x640 1 animal, 424.4ms
14: 640x640 1 animal, 424.4ms
15: 640x640 1 animal, 424.4ms
Speed: 2.5ms preprocess, 424.4ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 8/10 [00:43<00:12,  6.23s/it]

0: 640x640 1 animal, 425.8ms
1: 640x640 1 animal, 425.8ms
2: 640x640 1 animal, 425.8ms
3: 640x640 1 animal, 425.8ms
4: 640x640 1 animal, 425.8ms
5: 640x640 1 animal, 425.8ms
6: 640x640 1 animal, 425.8ms
7: 640x640 2 animals, 425.8ms
8: 640x640 1 animal, 425.8ms
9: 640x640 1 animal, 425.8ms
10: 640x640 (no detections), 425.8ms
11: 640x640 (no detections), 425.8ms
12: 640x640 1 animal, 425.8ms
13: 640x640 3 animals, 425.8ms
14: 640x640 2 animals, 425.8ms
15: 640x640 1 animal, 425.8ms
Speed: 2.9ms preprocess, 425.8ms inference, 0.4ms postprocess per image at shape (16, 3, 640, 640)

 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 9/10 [00:50<00:06,  6.61s/it]

0: 640x640 2 animals, 424.3ms
1: 640x640 3 animals, 424.3ms
2: 640x640 4 animals, 424.3ms
3: 640x640 2 animals, 424.3ms
4: 640x640 6 animals, 424.3ms
5: 640x640 2 animals, 424.3ms
6: 640x640 1 animal, 424.3ms
7: 640x640 1 animal, 424.3ms
8: 640x640 1 animal, 424.3ms
9: 640x640 1 animal, 424.3ms
10: 640x640 1 animal, 424.3ms
11: 640x640 1 animal, 424.3ms
12: 640x640 1 animal, 424.3ms
13: 640x640 1 animal, 424.3ms
14: 640x640 1 animal, 424.3ms
15: 640x640 1 animal, 424.3ms
Speed: 2.5ms preprocess, 424.3ms inference, 0.5ms postprocess per image at shape (16, 3, 640, 640)

00%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:58<00:00,  5.81s/it]

## Seleccion de imagenes con animales

Vamos a seleccionar las imagenes en las que si se detectó un animal y generar la tabla de metadatos para cada especie

In [5]:
import pandas as pd
import os

In [12]:
file_list = os.listdir('../data/img_from_video_metadata')

dfs = [pd.read_csv(os.path.join('../data/img_from_video_metadata',file)) for file in file_list]

In [15]:
df = pd.concat(dfs)
df

,Unnamed: 0,img_id,label,certainty
0,0,../data/mod_images_from_videos/CONEPATUS_LEUCO...,animal,0.86
1,1,../data/mod_images_from_videos/CONEPATUS_LEUCO...,animal,0.68
2,2,../data/mod_images_from_videos/CONEPATUS_LEUCO...,animal,0.47
3,3,../data/mod_images_from_videos/CONEPATUS_LEUCO...,animal,0.36
4,4,../data/mod_images_from_videos/CONEPATUS_LEUCO...,animal,0.48
...,...,...,...,...
1048,1048,../data/mod_images_from_videos/ODOCOILEUS_VIRG...,animal,0.93
1049,1049,../data/mod_images_from_videos/ODOCOILEUS_VIRG...,animal,0.93
1050,1050,../data/mod_images_from_videos/ODOCOILEUS_VIRG...,animal,0.92
1051,1051,../data/mod_images_from_videos/ODOCOILEUS_VIRG...,animal,0.92
1052,1052,../data/mod_images_from_videos/ODOCOILEUS_VIRG...,animal,0.92